Repository bbc/simorgh, pull requests merged in 2018-10, with the labels that each got.

#668 Create image placeholder
  src/app/components/Figure/Image/__snapshots__/index.test.jsx.snap
  src/app/components/Figure/Image/index.jsx
  src/app/components/Figure/ImagePlaceholder/__snapshots__/index.test.jsx.snap
  src/app/components/Figure/ImagePlaceholder/index.jsx
  src/app/components/Figure/ImagePlaceholder/index.stories.jsx
  src/app/components/Figure/ImagePlaceholder/index.test.jsx
  src/app/components/Figure/__snapshots__/index.test.jsx.snap
  src/app/components/Figure/fixtureData.jsx
  src/app/lib/constants/styles.js
Labels: Image component

#780 Add inline link container
  src/app/containers/InlineLink/__snapshots__/index.new.test.jsx.snap
  src/app/containers/InlineLink/index.new.jsx
  src/app/containers/InlineLink/index.new.test.jsx
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/index.jsx
  src/app/containers/Paragraph/index.test.jsx
  src/app/models/propTypes/fragment/index.js
  src/app/models/propTypes/inlineLink/index.js
  src/app/models/propTypes/paragraph/index.js
Labels: alpha-1.0

#797 remove blockid's from fragmented data
  data/fragmented/prod/news/c0000000025o.json
  data/fragmented/prod/news/c0000000027o.json
  data/fragmented/prod/persian/c0000000028o.json
  data/fragmented/test/news/c0000000001o.json
  data/fragmented/test/news/c0000000002o.json
  data/fragmented/test/news/c0000000003o.json
  data/fragmented/test/news/c0000000004o.json
  data/fragmented/test/news/c0000000005o.json
  data/fragmented/test/news/c0000000006o.json
  data/fragmented/test/news/c0000000007o.json
  data/fragmented/test/news/c0000000008o.json
  data/fragmented/test/news/c0000000009o.json
  data/fragmented/test/news/c0000000010o.json
  data/fragmented/test/news/c0000000011o.json
  data/fragmented/test/news/c0000000012o.json
  data/fragmented/test/news/c0000000013o.json
  data/fragmented/test/news/c0000000014o.json
  data/fragmented/test/news/c0000000015o.json
  data/fragmented/test/news/c0000000016o.json
  data/fragmented/test/news/c0000000017o.json
  data/fragmented/test/news/c0000000018o.json
  data/fragmented/test/news/c0000000019o.json
  data/fragmented/test/news/c0000000020o.json
  data/fragmented/test/news/c0000000021o.json
  data/fragmented/test/news/c0000000022o.json
  data/fragmented/test/news/c0000000024o.json
  data/fragmented/test/news/c0000000025o.json
  data/fragmented/test/news/c0000000027o.json
  data/fragmented/test/persian/c0000000026o.json
  data/fragmented/test/persian/c0000000028o.json
Labels: alpha-1.0

#783 Use fragmented data in Text
  src/app/containers/Text/__snapshots__/index.test.jsx.snap
  src/app/containers/Text/index.jsx
  src/app/containers/Text/index.test.jsx
  src/app/models/propTypes/text/index.js
  src/server/index.jsx
Labels: alpha-1.0

#817 Make seoHeadline optional and default to an empty string
  data/schema.yaml
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.jsx
  src/app/components/Metadata/index.test.jsx
  src/app/models/propTypes/promo/index.js
Labels: alpha-1.0, high priority

#819 Align local data path with environment data paths
  cypress/integration/dataSpec.js
  src/app/routes/getInitialData/index.js
  src/app/routes/getInitialData/index.test.js
  src/app/routes/index.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: high priority

#803 Strip absolute urls on links to /news/articles/
  package-lock.json
  package.json
  src/app/containers/InlineLink/__snapshots__/index.new.test.jsx.snap
  src/app/containers/InlineLink/index.new.jsx
  src/app/containers/InlineLink/index.new.test.jsx
Labels: alpha-1.0

#809 Validate fragmented data
  data/schema.yaml
  src/app/dataValidator/helpers/validators/validateNode.test.js
Labels: Data Validation

#822 Make links absolute
  data/prod/news/articles/c85pqyj5m2ko.json
  data/prod/news/articles/c9rpqy7pmypo.json
  data/test/news/articles/c0000000007o.json
  data/test/news/articles/c0000000008o.json
  data/test/news/articles/c0000000011o.json
  data/test/news/articles/c0000000020o.json
  data/test/news/articles/c85pqyj5m2ko.json
  data/test/news/articles/c9rpqy7pmypo.json
Labels: alpha-1.0

#788 Remove "required" values no longer required for alpha deadline
  data/fragmented/test/news/articles/c85pqyj5m2ko.json
  data/fragmented/test/news/articles/c9rpqy7pmypo.json
  data/schema.yaml
  src/app/models/propTypes/metadata/index.js
Labels: Data Validation, alpha-1.0

#823 Fix footer grid&margin bug
  src/app/components/Footer/List/__snapshots__/index.test.jsx.snap
  src/app/components/Footer/List/index.jsx
  src/app/components/Footer/__snapshots__/index.test.jsx.snap
Labels: alpha-1.0, bug, high priority

#843 Temporarily comment out end-to-end tests that are externally blocked
  cypress/integration/metaNewsSpec.js
  cypress/integration/metaPersianSpec.js
  cypress/integration/newsBodySpec.js
  cypress/integration/persianBodySpec.js
  cypress/support/metaTestHelper.js
Labels: alpha-1.0, high priority

#829 Timestamp component
  src/app/components/Timestamp/__snapshots__/index.test.jsx.snap
  src/app/components/Timestamp/index.jsx
  src/app/components/Timestamp/index.stories.jsx
  src/app/components/Timestamp/index.test.jsx
  src/app/lib/constants/styles.js
Labels: alpha-1.0

#849 Split blocks by headline and render individual Blocks component
  src/app/containers/Article/__snapshots__/index.test.jsx.snap
  src/app/containers/Article/index.jsx
  src/app/containers/Article/index.test.jsx
Labels: alpha-1.0

#857 Integrate timestamp component
  cypress/integration/newsBodySpec.js
  src/app/components/Timestamp/__snapshots__/index.test.jsx.snap
  src/app/components/Timestamp/index.jsx
  src/app/components/Timestamp/index.stories.jsx
  src/app/components/Timestamp/index.test.jsx
  src/app/containers/Article/__snapshots__/index.test.jsx.snap
  src/app/containers/Article/index.jsx
Labels: alpha-1.0

#874 Grid Layout and Applying Oat Background
  src/app/components/Brand/__snapshots__/index.test.jsx.snap
  src/app/components/Brand/index.jsx
  src/app/components/Footer/List/__snapshots__/index.test.jsx.snap
  src/app/components/Footer/__snapshots__/index.test.jsx.snap
  src/app/components/Footer/index.jsx
  src/app/components/Header/__snapshots__/index.test.jsx.snap
  src/app/components/MainContent/__snapshots__/index.test.jsx.snap
  src/app/components/MainContent/index.jsx
  src/app/components/MainContent/index.stories.jsx
  src/app/components/MainContent/index.test.jsx
  src/app/containers/Article/__snapshots__/index.test.jsx.snap
  src/app/containers/Article/index.jsx
  src/app/lib/constants/styles.js
  src/app/lib/layoutGrid.js
Labels: alpha-1.0, high priority

#851 make data request absolute
  src/app/routes/getInitialData/index.js
  src/app/routes/getInitialData/index.test.js
Labels: bug
