Repository bbc/simorgh, pull requests merged in 2018-12, with the labels that each got.

#1018 Use npm package for styles
  package-lock.json
  package.json
  src/app/components/Brand/index.jsx
  src/app/components/Document/index.jsx
  src/app/components/Figure/Caption/index.jsx
  src/app/components/Figure/Copyright/index.jsx
  src/app/components/Figure/ImagePlaceholder/index.jsx
  src/app/components/Footer/Link/index.jsx
  src/app/components/Footer/List/index.jsx
  src/app/components/Footer/index.jsx
  src/app/components/Headings/index.jsx
  src/app/components/HorizontalRule/index.jsx
  src/app/components/InlineLink/index.jsx
  src/app/components/Paragraph/index.jsx
  src/app/components/Timestamp/index.jsx
  src/app/containers/Article/index.jsx
  src/app/lib/constants/styles.js
Labels: alpha-2

#1024 Added schema text attributes
  data/schema.yaml
  src/app/dataValidator/helpers/validators/validateNode.test.js
Labels: enhancement

#1036 fix #1035: moves contexts to contexts/ dir
  package-lock.json
  src/app/components/Figure/fixtureData.jsx
  src/app/components/Footer/index.test.jsx
  src/app/containers/Article/index.jsx
  src/app/containers/Brand/index.jsx
  src/app/containers/Caption/index.jsx
  src/app/containers/Caption/index.test.jsx
  src/app/containers/Header/index.test.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/contexts/PlatformContext/__snapshots__/index.test.jsx.snap
  src/app/contexts/PlatformContext/index.jsx
  src/app/contexts/PlatformContext/index.test.jsx
  src/app/contexts/ServiceContext/__snapshots__/index.test.jsx.snap
  src/app/contexts/ServiceContext/index.jsx
  src/app/contexts/ServiceContext/index.test.jsx
Labels: high priority, mergeable

#1031 Copyright container
  src/app/components/Figure/Copyright/__snapshots__/index.test.jsx.snap
  src/app/components/Figure/Copyright/index.jsx
  src/app/components/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/Copyright/__snapshots__/index.test.jsx.snap
  src/app/containers/Copyright/index.jsx
  src/app/containers/Copyright/index.test.jsx
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/Figure/index.jsx
  src/app/lib/config/services/index.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
Labels: mergeable

#1042 Styled components 4
  .storybook/config.js
  package-lock.json
  package.json
  src/app/components/Document/index.jsx
  src/app/containers/Article/__snapshots__/index.test.jsx.snap
  src/app/containers/Article/index.jsx
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineLink/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/lib/__snapshots__/globalStyles.test.js.snap
  src/app/lib/globalStyles.js
  src/app/lib/globalStyles.test.js
  src/server/styles.jsx
  src/server/styles.test.jsx
Labels: alpha-2, high priority

#1044 Simplify Figure component tests/stories, move complexity to container
  src/app/components/Figure/Caption/index.stories.jsx
  src/app/components/Figure/Image/index.stories.jsx
  src/app/components/Figure/__snapshots__/index.test.jsx.snap
  src/app/components/Figure/index.test.jsx
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/Figure/fixtureData.jsx
  src/app/containers/Figure/index.stories.jsx
  src/app/containers/Figure/index.test.jsx
Labels: high priority, mergeable

#1026 Use Psammead Headings package in Simorgh
  package-lock.json
  package.json
  src/app/components/Headings/README.md
  src/app/components/Headings/__snapshots__/index.test.jsx.snap
  src/app/components/Headings/index.stories.jsx
  src/app/components/Headings/index.test.jsx
  src/app/containers/Headings/index.jsx
Labels: alpha-2, high priority

#1058 Add tick box to prompt people to assign PR/issue
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation, enhancement

#1048 Enforce npm and node versions
  package.json
  scripts/enforceVersions.sh
Labels: mergeable

#1054 Use Psammead VisuallyHiddenText
  package-lock.json
  package.json
  src/app/components/Brand/index.jsx
  src/app/components/Figure/Caption/__snapshots__/index.test.jsx.snap
  src/app/components/Figure/Caption/index.test.jsx
  src/app/components/VisuallyHiddenText/README.md
  src/app/components/VisuallyHiddenText/__snapshots__/index.test.jsx.snap
  src/app/components/VisuallyHiddenText/index.jsx
  src/app/components/VisuallyHiddenText/index.stories.jsx
  src/app/components/VisuallyHiddenText/index.test.jsx
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/index.jsx
  src/app/containers/Copyright/__snapshots__/index.test.jsx.snap
  src/app/containers/Copyright/index.jsx
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
Labels: mergeable

#1051 Use psammead-paragraph
  package-lock.json
  package.json
  src/app/components/HorizontalRule/index.stories.jsx
  src/app/components/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/components/Paragraph/index.jsx
  src/app/components/Paragraph/index.stories.jsx
  src/app/components/Paragraph/index.test.jsx
  src/app/containers/Paragraph/index.jsx
Labels: alpha-2, mergeable

#1062 Remove HR component
  src/app/components/HorizontalRule/__snapshots__/index.test.jsx.snap
  src/app/components/HorizontalRule/index.jsx
  src/app/components/HorizontalRule/index.stories.jsx
  src/app/components/HorizontalRule/index.test.jsx
  src/app/containers/Text/__snapshots__/index.test.jsx.snap
  src/app/containers/Text/index.jsx
  src/app/containers/Text/index.test.jsx
Labels: alpha-2, should

#1067 Updating package lock; Adding core-js as devDependency
  .nvmrc
  .travis.yml
  package-lock.json
  package.json
Labels: high priority

#1064 Use @bbc/psammead-sitewide-links in Simorgh
  package-lock.json
  package.json
  src/app/components/SitewideLinks/Link/__snapshots__/index.test.jsx.snap
  src/app/components/SitewideLinks/Link/index.jsx
  src/app/components/SitewideLinks/Link/index.test.jsx
  src/app/components/SitewideLinks/List/__snapshots__/index.test.jsx.snap
  src/app/components/SitewideLinks/List/index.jsx
  src/app/components/SitewideLinks/List/index.test.jsx
  src/app/components/SitewideLinks/README.md
  src/app/components/SitewideLinks/__snapshots__/index.test.jsx.snap
  src/app/components/SitewideLinks/index.jsx
  src/app/components/SitewideLinks/index.stories.jsx
  src/app/components/SitewideLinks/index.test.jsx
  src/app/containers/Footer/index.jsx
Labels: alpha-2, must

#1071 Use psammead copyright
  package-lock.json
  package.json
  src/app/components/Figure/Copyright/README.md
  src/app/components/Figure/Copyright/__snapshots__/index.test.jsx.snap
  src/app/components/Figure/Copyright/index.jsx
  src/app/components/Figure/Copyright/index.stories.jsx
  src/app/components/Figure/Copyright/index.test.jsx
  src/app/containers/Copyright/index.jsx
Labels: alpha-2, must

#1074 Remove Headings which seems to have snuck through
  src/app/components/Headings/index.jsx
Labels: bug

#1068 Use psammead-brand
  package-lock.json
  package.json
  src/app/components/Brand/README.md
  src/app/components/Brand/__snapshots__/index.test.jsx.snap
  src/app/components/Brand/index.jsx
  src/app/components/Brand/index.stories.jsx
  src/app/components/Brand/index.test.jsx
  src/app/containers/Brand/index.jsx
Labels: alpha-2, mergeable, must

#1079 Use @bbc/psammead-caption
  package-lock.json
  package.json
  src/app/components/Figure/Caption/__snapshots__/index.test.jsx.snap
  src/app/components/Figure/Caption/index.jsx
  src/app/components/Figure/Caption/index.stories.jsx
  src/app/components/Figure/Caption/index.test.jsx
  src/app/containers/Caption/index.jsx
  src/app/containers/Caption/index.test.jsx
Labels: alpha-2, mergeable, must

#1075 Use ASCII hyphen for title, not HTML escaped en-dash
  cypress/integration/newsBodySpec.js
  cypress/integration/persianBodySpec.js
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
Labels: mergeable

#1103 Use psammead ImagePlaceholder
  package-lock.json
  package.json
  src/app/components/Figure/ImagePlaceholder/__snapshots__/index.test.jsx.snap
  src/app/components/Figure/ImagePlaceholder/index.jsx
  src/app/components/Figure/ImagePlaceholder/index.stories.jsx
  src/app/components/Figure/ImagePlaceholder/index.test.jsx
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/Figure/index.jsx
Labels: mergeable
