Repository bbc/simorgh, pull requests merged in 2018-08, with the labels that each got.

#391 Define Image props
  src/app/containers/Image/index.jsx
  src/app/models/propTypes/general/getMissingRequiredProps.js
  src/app/models/propTypes/general/getMissingRequiredProps.test.js
  src/app/models/propTypes/general/index.js
  src/app/models/propTypes/general/index.test.js
  src/app/models/propTypes/image/index.js
  src/app/models/propTypes/index.js
  src/app/models/propTypes/mainContent/index.js
Labels: blocked

#499 Update originCode data type
  data/schema.yaml
Labels: Data Validation, Image component

#474 Add image caption offscreen text
  src/app/components/Article/__snapshots__/index.test.jsx.snap
  src/app/components/Brand/__snapshots__/index.test.jsx.snap
  src/app/components/Brand/index.jsx
  src/app/components/Figure/Caption/__snapshots__/index.test.jsx.snap
  src/app/components/Figure/Caption/index.jsx
  src/app/components/Figure/Caption/index.test.jsx
  src/app/components/Figure/__snapshots__/index.test.jsx.snap
  src/app/components/Footer/__snapshots__/index.test.jsx.snap
  src/app/components/Header/__snapshots__/index.test.jsx.snap
  src/app/components/VisuallyHiddenText/__snapshots__/index.test.jsx.snap
  src/app/components/VisuallyHiddenText/index.jsx
  src/app/components/VisuallyHiddenText/index.stories.jsx
  src/app/components/VisuallyHiddenText/index.test.jsx
  src/app/containers/Article/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/MainContent/__snapshots__/index.test.jsx.snap
Labels: a11y
