Repository bbc/simorgh, pull requests merged in 2018-11, with the labels that each got.

#931 Comment out the inline link Cypress test
  cypress/integration/newsBodySpec.js
Labels: alpha-2, bug, high priority

#892 Update deps (npm update)
  .storybook/cypress/integration/index.js
  package-lock.json
  package.json
Labels: mergeable

#901 Fix the footer bug
  src/app/components/Footer/__snapshots__/index.test.jsx.snap
  src/app/components/Footer/index.jsx
  src/app/lib/layoutGrid.js
Labels: alpha-2, bug, mergeable

#906 Greenkeeper/prettier 1.15.0
  package-lock.json
  package.json
  src/app/components/Headings/index.test.jsx
  src/app/containers/Article/index.jsx
Labels: greenkeeper

#858 Fix validator silent errors and ensure process exit on validation error
  data/test/news/articles/c0000000005o.json
  package.json
  src/app/dataValidator/helpers/dataLoader/readScenario.js
  src/app/dataValidator/helpers/dataLoader/readScenario.test.js
  src/app/dataValidator/invalidScenario.json
Labels: Data Validation, bug, mergeable

#889 Re-enable eslint JSX-a11y rule
  .eslintrc.js
Labels: mergeable

#846 Increase metadata test coverage
  src/app/containers/Article/__snapshots__/index.test.jsx.snap
  src/app/containers/Article/fixtureData.js
  src/app/containers/Metadata/index.test.jsx
Labels: mergeable

#890 Makes seoHeadline required again and enables tests
  cypress/integration/newsBodySpec.js
  cypress/integration/persianBodySpec.js
  data/schema.yaml
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.jsx
  src/app/components/Metadata/index.test.jsx
  src/app/models/propTypes/promo/index.js
Labels: alpha-2, high priority, mergeable

#907 avoid inline JavaScript for AMP
  cypress/integration/ampSpec.js
  src/app/components/Document/index.jsx
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.jsx
Labels: mergeable

#924 Add video test asset list
  data/README.md
Labels: alpha-2, mergeable

#951 Ensure <title> test expectation matches seoHeadline value
  cypress/integration/newsBodySpec.js
Labels: alpha-2, bug, cypress

#956 Add chrome-launcher to dev-dependencies
  package-lock.json
  package.json
Labels: bug

#942 resolves #412: removes hacky c0000000023o check
  data/test/news/articles/c0000000023o.json
  src/app/dataValidator/helpers/dataLoader/asyncValidateDir.test.js
  src/app/dataValidator/helpers/dataLoader/readScenario.js
  src/app/dataValidator/helpers/dataLoader/readScenario.test.js
  src/app/dataValidator/helpers/validators/validateData.test.js
Labels: mergeable

#954 Add Amp Decorator, amp styles and snapshot tests
  src/app/helpers/storybook/ampDecorator/__snapshots__/index.test.jsx.snap
  src/app/helpers/storybook/ampDecorator/index.jsx
  src/app/helpers/storybook/ampDecorator/index.test.jsx
  src/app/lib/constants/styles.js
Labels: AMP, alpha-2, mergeable

#902 Remove grid from brand
  src/app/components/Brand/__snapshots__/index.test.jsx.snap
  src/app/components/Brand/index.jsx
  src/app/components/Brand/index.stories.jsx
  src/app/components/Brand/index.test.jsx
  src/app/components/Footer/__snapshots__/index.test.jsx.snap
  src/app/components/Footer/index.jsx
  src/app/components/Header/__snapshots__/index.test.jsx.snap
  src/app/components/Header/index.jsx
Labels: Footer component, Header component, mergeable

#946 Fix dependencies identified by Greenkeeper
  package-lock.json
  package.json
Labels: alpha-2, mergeable

#947 Create Header component README.md
  src/app/components/Header/README.md
Labels: alpha-2, mergeable

#967 Add README.md for Figure Copyright
  src/app/components/Figure/Copyright/README.md
Labels: mergeable

#958 Add amp-boilerplate styles on .amp pages
  src/app/components/Document/__snapshots__/index.test.jsx.snap
  src/app/components/Document/index.jsx
  src/app/components/Document/index.test.jsx
Labels: mergeable

#973 Updates the testing note section in the template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: alpha-2, mergeable

#968 Create Headings README.md
  src/app/components/Headings/README.md
Labels: alpha-2, mergeable

#980 Inline link readme
  src/app/components/InlineLink/README.md
Labels: alpha-2

#979 Add Text Component README.md
  package-lock.json
  src/app/components/Text/README.md
Labels: alpha-2

#991 upgrade npm-run-all to v4.1.5
  package-lock.json
  package.json
Labels: alpha-2, high priority

#984 Update Visually Hidden Text README.md
  src/app/components/VisuallyHiddenText/README.md
Labels: mergeable

#982 Add PlatformContext & remove passing of isAmp
  src/app/components/PlatformContext/__snapshots__/index.test.jsx.snap
  src/app/components/PlatformContext/index.jsx
  src/app/components/PlatformContext/index.test.jsx
  src/app/containers/Article/__snapshots__/index.test.jsx.snap
  src/app/containers/Article/index.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
Labels: mergeable

#921 Fixes AMP validation: mandatory attribute 'amp-custom' is missing
  package-lock.json
  src/app/components/Document/__snapshots__/index.test.jsx.snap
  src/app/components/Document/index.test.jsx
  src/server/index.jsx
  src/server/index.test.jsx
  src/server/styles.jsx
  src/server/styles.test.jsx
Labels: AMP, alpha-2

#1015 add react/no-danger eslint disable line
  src/server/styles.jsx
Labels: bug

#1007 Fix bug when passing props from validateProperty
  src/app/dataValidator/helpers/validators/validateNode.js
  src/app/dataValidator/helpers/validators/validateNode.test.js
Labels: Data Validation, alpha-2, bug

#981 add Merging process section to readme
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: Documentation, alpha-2

#1008 Add array support to validator
  data/schema.yaml
  src/app/dataValidator/helpers/validators/validateNode.test.js
  src/app/dataValidator/helpers/validators/validateType.js
  src/app/dataValidator/helpers/validators/validateType.test.js
Labels: Data Validation, alpha-2
