Repository bbc/simorgh, pull requests merged in 2019-08, with the labels that each got.

#2694 Optimise srcset for ws frontpages
  src/app/containers/Image/helpers/srcSet.js
  src/app/containers/ImageWithPlaceholder/index.jsx
  src/app/containers/StoryPromo/index.jsx
Labels: ws-fp-phase2, ws-frontpage-stream

#2735 Moving prod deps to dev
  .travis.yml
  Jenkinsfile
  Makefile
  package-lock.json
  package.json
Labels: dependencies, simorgh-core-stream

#2865 move speculate to prod dep
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2816 Add the other manifest files
  cypress/integration/application/index.js
  public/afaanoromoo/manifest.json
  public/afrique/manifest.json
  public/amharic/manifest.json
  public/arabic/manifest.json
  public/azeri/manifest.json
  public/bengali/manifest.json
  public/burmese/manifest.json
  public/cymrufyw/manifest.json
  public/gahuza/manifest.json
  public/gujarati/manifest.json
  public/hausa/manifest.json
  public/hindi/manifest.json
  public/igbo/manifest.json
  public/indonesia/manifest.json
  public/japanese/manifest.json
  public/korean/manifest.json
  public/kyrgyz/manifest.json
  public/marathi/manifest.json
  public/mundo/manifest.json
  public/naidheachdan/manifest.json
  public/nepali/manifest.json
  public/pashto/manifest.json
  public/portuguese/manifest.json
  public/punjabi/manifest.json
  public/russian/manifest.json
  public/serbian/manifest.json
  public/sinhala/manifest.json
  public/somali/manifest.json
  public/swahili/manifest.json
  public/tamil/manifest.json
  public/telugu/manifest.json
  public/thai/manifest.json
  public/tigrinya/manifest.json
  public/turkce/manifest.json
  public/ukchina/manifest.json
  public/ukrainian/manifest.json
  public/urdu/manifest.json
  public/uzbek/manifest.json
  public/vietnamese/manifest.json
  public/zhongwen/manifest.json
Labels: simorgh-core-stream

#2709 Refactor metadata helpers
  cypress/integration/ampSpec.js
  cypress/integration/frontpageAmpSpec.js
  cypress/integration/metaArticleSpec.js
  cypress/integration/metaNewsSpec.js
  cypress/support/commands/index.js
  cypress/support/commands/metaData.js
  cypress/support/index.js
  cypress/support/metaTestHelper.js
Labels: simorgh-core-stream

#2793 Refactor bodyHelper commands
  cypress/integration/ampSpec.js
  cypress/integration/articleBodySpec.js
  cypress/integration/cookieBannerWS.js
  cypress/integration/errorPageArticle.js
  cypress/integration/metaArticleSpec.js
  cypress/support/bodyTestHelper.js
  cypress/support/commands/index.js
  cypress/support/commands/pageTestFragment/articleBody.js
  cypress/support/commands/pageTestFragment/metaData.js
  cypress/support/index.js
Labels: simorgh-core-stream

#2874 Rmv storybook cypress
  .storybook/cypress.json
  .storybook/cypress/fixtures/.keep
  .storybook/cypress/integration/index.js
  .storybook/cypress/plugins/.keep
  .storybook/cypress/support/index.js
  .travis.yml
  Makefile
  package.json
Labels: simorgh-core-stream

#2875 Correct all old localhost refs
  puppeteer/bundleRequests.test.js
  src/server/assets/assetsFilter/index.test.js
  src/server/assets/fixture.json
  src/server/assets/fixtureMissingKey.json
  src/server/assets/index.test.js
  src/server/index.test.jsx
Labels: simorgh-core-stream

#2879 adding chromatic credentials to test prod stage
  Jenkinsfile
Labels: simorgh-core-stream

#2549 Use nassim fonts in simorgh
  package-lock.json
  package.json
  scripts/bundleSize.sh
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorPage/index.jsx
  src/app/components/ErrorPage/index.test.jsx
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/index.jsx
  src/app/containers/Headings/index.stories.jsx
  src/app/containers/Headings/index.test.jsx
  src/app/containers/MediaPage/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageMain/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/persian.js
Labels: articles-current-epic, articles-features-stream

#2818 Update ichef locator for portrait videos
  data/news/articles/c0000000013o.json
  data/news/articles/c3wmq4d1y3wo.json
Labels: articles-av-epic, articles-features-stream

#2815 Fix env for Amp showing as "test" locally.
  src/app/contexts/RequestContext/getOriginContext/index.js
  src/app/contexts/RequestContext/getOriginContext/index.test.js
Labels: articles-current-epic, articles-features-stream

#2845 New apup fixtures
  data/arabic/articles/c8j91j2ljppo.json
  data/arabic/articles/clr0em3yzkmo.json
  data/pashto/articles/c70970g2251o.json
  data/pashto/articles/cm53wmz0x39o.json
  data/urdu/articles/c2n75x5wrlzo.json
  data/urdu/articles/c4qg7qq63y6o.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
Labels: articles-current-epic, articles-features-stream

#2761 ATI domain preconnect
  src/server/assets/index.js
  src/server/assets/index.test.js
  src/server/index.test.jsx
Labels: shared-components, simorgh-core-stream

#2884 Fix React warnings in src/app/components/Metadata/index.test.jsx
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.test.jsx
Labels: Good first issue, bug, simorgh-core-stream

#2867 Use localised relative timestamps on front pages
  package-lock.json
  package.json
  src/app/containers/ArticleTimestamp/helpers.js
  src/app/containers/ArticleTimestamp/helpers.test.js
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/lib/utilities/isTenHoursAgo/index.js
  src/app/lib/utilities/isTenHoursAgo/index.test.js
Labels: high priority, ws-frontpage-stream

#2887 Added cypress folder to codeowners
  .github/CODEOWNERS
Labels: Iolaus, high priority, simorgh-core-stream

#2905 Try sequence of parallels in prod tests
  .travis.yml
  cypress/integration/articleBodySpec.js
  package.json
Labels: infra-tooling-stream

#2647 Fix react warnings
  package.json
  src/app/components/ErrorPage/index.test.jsx
  src/app/components/Metadata/helpers/iconLinks.jsx
  src/app/components/Metadata/index.jsx
  src/app/containers/Article/index.test.jsx
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Blocks/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/index.test.jsx
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/index.test.jsx
  src/app/containers/FrontPage/index.test.jsx
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/ImageWithPlaceholder/fixtureData.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/PageHandlers/withData/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withError/index.jsx
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/index.test.jsx
  src/app/containers/StoryPromo/LinkContents/index.jsx
  src/app/containers/StoryPromo/LinkContents/index.test.jsx
  src/app/containers/StoryPromo/MediaIndicator/index.jsx
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/models/blocks/index.js
  src/app/models/blocks/index.test.js
  src/app/models/propTypes/storyItem/index.js
  src/testHelpers/setupTests.js
Labels: simorgh-core-stream

#2923 Correct typo in e2e test
  cypress/integration/cookieBannerWS.js
Labels: simorgh-core-stream

#2886 Local host duplication
  puppeteer/bundleRequests.test.js
  src/app/containers/ChartbeatAnalytics/index.test.jsx
  src/app/containers/ConsentBanner/CanonicalLogic/cookieOvenUrl.test.js
  src/app/contexts/RequestContext/getEnv/index.test.js
  src/app/routes/getInitialData/utils/getBaseUrl.test.js
  src/server/assets/assetsFilter/index.test.js
  src/server/assets/index.test.js
  src/server/index.test.jsx
  src/testHelpers/config.js
Labels: Heracles, simorgh-core-stream

#2925 Rmv unecessary beforeEachs
  cypress/integration/metaArticleSpec.js
  cypress/integration/scriptSpec.js
Labels: integration-testing, simorgh-core-stream

#2926 Revert "Correct typo in e2e test"
  cypress/integration/cookieBannerWS.js
Labels: high priority, simorgh-core-stream

#2928 Standardise config
  cypress/integration/pages/articlePages/metaArticleSpec.js
  cypress/integration/pages/articlePages/needsRefactoringIntoParentDir/articleBodySpec.js
  cypress/integration/pages/articlePages/needsRefactoringIntoParentDir/newsArticleAmpSpec.js
  cypress/integration/pages/articlePages/needsRefactoringIntoParentDir/newsArticleHeaderSpec.js
  cypress/integration/pages/articlePages/newsArticleFooterSpec.js
  cypress/integration/pages/frontpages/frontpageAmpSpec.js
  cypress/integration/pages/frontpages/frontpageLayoutSpec.js
  cypress/integration/shouldBeRefactoredIntoOtherFolders/atiSpec.js
  cypress/integration/shouldBeRefactoredIntoOtherFolders/chartbeatSpec.js
  cypress/integration/shouldBeRefactoredIntoOtherFolders/cookieBanner.amp.js
  cypress/integration/shouldBeRefactoredIntoOtherFolders/cookieBanner.canonical.js
  cypress/integration/shouldBeRefactoredIntoOtherFolders/cookieBannerWS.js
  cypress/integration/shouldBeRefactoredIntoOtherFolders/dataSpec.js
  cypress/integration/shouldBeRefactoredIntoOtherFolders/errorPageArticle.js
  cypress/integration/shouldBeRefactoredIntoOtherFolders/scriptSpec.js
  cypress/support/config/services.js
  puppeteer/bundleRequests.test.js
Labels: simorgh-core-stream

#2922 Re-enable the running of storybook-chromatic
  .storybook/config.js
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2929 Move data spec
  3rdPartyCypress/cypress/integration/dataEndpoints.js
  3rdPartyCypress/cypress/support/commands.js
  3rdPartyCypress/cypress/support/index.js
  cypress/integration/shouldBeRefactoredIntoOtherFolders/dataSpec.js
Labels: simorgh-core-stream

#2931 Correct error page tests
  cypress/integration/pages/errorPages/.keep
  cypress/integration/pages/errorPages/index.js
Labels: simorgh-core-stream

#2932 Do a minor clean on frontpages
  cypress/integration/pages/frontPage/amp.js
  cypress/integration/pages/frontPage/canonical.js
  cypress/integration/pages/frontpages/frontpageAmpSpec.js
  cypress/integration/pages/frontpages/frontpageLayoutSpec.js
Labels: simorgh-core-stream

#2930 Combine article tests into canonical and amp
  cypress/integration/pages/article/amp.js
  cypress/integration/pages/article/canonical.js
  cypress/integration/pages/articlePages/metaArticleSpec.js
  cypress/integration/pages/articlePages/needsRefactoringIntoParentDir/articleBodySpec.js
  cypress/integration/pages/articlePages/needsRefactoringIntoParentDir/newsArticleAmpSpec.js
  cypress/integration/pages/articlePages/needsRefactoringIntoParentDir/newsArticleHeaderSpec.js
  cypress/integration/pages/articlePages/newsArticleFooterSpec.js
Labels: simorgh-core-stream

#2800 Fix storybook console warnings.
  src/app/containers/Article/fixtureData.js
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleFigure/fixtureData.jsx
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMain/index.stories.jsx
  src/app/containers/ArticleTimestamp/index.stories.jsx
  src/app/containers/Blocks/__snapshots__/index.test.jsx.snap
  src/app/containers/Blocks/index.jsx
  src/app/containers/ConsentBanner/index.stories.jsx
  src/app/containers/FrontPage/index.stories.jsx
  src/app/containers/FrontPageSection/index.stories.jsx
  src/app/containers/Headings/testHelpers.js
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/ImageWithPlaceholder/fixtureData.jsx
  src/app/containers/InlineLink/index.stories.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withData/__snapshots__/index.test.jsx.snap
  src/app/models/blocks/index.js
  src/app/models/blocks/index.test.js
Labels: articles-features-stream, bug, high priority, simorgh-core-stream, ws-frontpage-stream

#2915 add psammead translations for yo
  src/app/containers/StoryPromo/index.test.jsx
  src/app/lib/config/services/yoruba.js
Labels: ws-frontpage-stream

#2934 Clean up ATI, Chartbeat & Scripts
  cypress/integration/pages/article/amp.js
  cypress/integration/pages/article/canonical.js
  cypress/integration/pages/frontPage/amp.js
  cypress/integration/pages/frontPage/canonical.js
  cypress/integration/shouldBeRefactoredIntoOtherFolders/atiSpec.js
  cypress/integration/shouldBeRefactoredIntoOtherFolders/chartbeatSpec.js
  cypress/integration/shouldBeRefactoredIntoOtherFolders/scriptSpec.js
  cypress/support/commands/index.js
  cypress/support/commands/pageTestFragment/analytics.js
  cypress/support/commands/pageTestFragment/scripts.js
  cypress/support/config/envs.js
  cypress/support/config/services.js
Labels: simorgh-core-stream

#2933 Cookie
  cypress/integration/shouldBeRefactoredIntoOtherFolders/cookieBanner.amp.js
  cypress/integration/shouldBeRefactoredIntoOtherFolders/cookieBanner.canonical.js
  cypress/integration/specialFeatures/cookieBanner.amp.js
  cypress/integration/specialFeatures/cookieBanner.canonical.js
Labels: simorgh-core-stream

#2863 Bump up simorgh's packages && version
  package-lock.json
  package.json
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPage/__snapshots__/index.test.jsx.snap
Labels: articles-current-epic, articles-features-stream, blocked

#2880 Add visually hidden text to LinkContents for PGL.
  src/app/containers/StoryPromo/LinkContents/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/LinkContents/index.jsx
  src/app/containers/StoryPromo/LinkContents/index.test.jsx
Labels: high priority, ws-fp-phase2, ws-frontpage-stream

#2885 simorgh dependabot updates
  package-lock.json
  package.json
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineLink/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPage/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
Labels: simorgh-core-stream

#2894 Addlivepromos
  package-lock.json
  package.json
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/lib/utilities/preprocessor/rules/cpstypes.js
  src/app/lib/utilities/preprocessor/rules/cpstypes.test.js
Labels: ws-fp-phase2, ws-frontpage-stream

#2952 Move cookie translations, use all services & pagetypes across cypress
  cypress/integration/pages/article/amp.js
  cypress/integration/pages/article/canonical.js
  cypress/integration/pages/errorPages/index.js
  cypress/integration/pages/frontPage/amp.js
  cypress/integration/pages/frontPage/canonical.js
  cypress/integration/shouldBeRefactoredIntoOtherFolders/cookieBannerWS.js
  cypress/integration/specialFeatures/cookieBanner.amp.js
  cypress/integration/specialFeatures/cookieBanner.canonical.js
  cypress/support/commands/index.js
  cypress/support/commands/pageTestFragment/articleBody.js
  cypress/support/commands/pageTestFragment/consentBanner.js
  cypress/support/config/services.js
  data/afaanoromoo/articles/c4g19kgl85ko.json
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
Labels: simorgh-core-stream

#2984 Disable naidheachdan on test
  cypress/support/config/services.js
Labels: simorgh-core-stream

#2986 Wales homepage 404 on test
  cypress/support/config/services.js
Labels: simorgh-core-stream

#2907 Added persian live asset ID to cypress test
  cypress/support/config/services.js
Labels: articles-current-epic, articles-features-stream

#2972 Fix react warning
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.jsx
  src/app/components/Metadata/index.test.jsx
Labels: simorgh-core-stream

#2988 Add new live articles for pashto, arabic & urdu to e2e's enabling the…
  cypress/support/config/services.js
Labels: simorgh-core-stream

#2914 Lint only changed files in hooks
  package-lock.json
  package.json
Labels: infra-tooling-stream

#2992 prevent tests running for error pages on APUP services
  cypress/support/config/services.js
Labels: simorgh-core-stream

#2999 Increase jenkins time limit
  Jenkinsfile
Labels: simorgh-core-stream

#2837 Incorrect chartbeat object
  cypress/support/commands/pageTestFragment/analytics.js
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/ChartbeatAnalytics/__snapshots__/index.test.jsx.snap
  src/app/containers/ChartbeatAnalytics/amp/index.jsx
  src/app/containers/ChartbeatAnalytics/amp/index.test.jsx
  src/app/containers/ChartbeatAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ChartbeatAnalytics/canonical/index.jsx
  src/app/containers/ChartbeatAnalytics/canonical/index.test.jsx
  src/app/containers/ChartbeatAnalytics/index.jsx
  src/app/containers/ChartbeatAnalytics/index.test.jsx
  src/app/lib/analyticsUtils/chartbeat/index.js
  src/app/lib/analyticsUtils/chartbeat/index.test.js
Labels: articles-current-epic, articles-features-stream

#3000 missing link
  README.md
Labels: Documentation, simorgh-core-stream

#3006 Add new test/merge process to project board doc
  docs/Project-Board-Guide.md
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2953 Footer copyright should be in english
  cypress/integration/pages/article/canonical.js
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/index.jsx
  src/app/containers/MediaPage/__snapshots__/index.test.jsx.snap
Labels: ws-frontpage-stream

#3009 Add punjabi navigation
  src/app/lib/config/services/punjabi.js
Labels: ws-frontpage-stream

#2851 Add timezone to services
  cypress/support/index.js
  package-lock.json
  package.json
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/ArticleTimestamp/index.test.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
  webpack.config.client.js
  webpack.config.js
Labels: high priority, ws-frontpage-stream

#3035 Thai tile icons
  public/thai/images/icons/icon-128x128.png
  public/thai/images/icons/icon-144x144.png
  public/thai/images/icons/icon-152x152.png
  public/thai/images/icons/icon-192x192.png
  public/thai/images/icons/icon-384x384.png
  public/thai/images/icons/icon-512x512.png
  public/thai/images/icons/icon-72x72.png
  public/thai/images/icons/icon-96x96.png
Labels: blocking, ws-fp-phase2, ws-frontpage-stream

#3036 Make Thai timestamps show in Thai
  src/app/lib/config/services/thai.js
Labels: ws-fp-phase2, ws-frontpage-stream

#3044 Add Thai navigation
  src/app/lib/config/services/thai.js
Labels: ws-frontpage-stream

#3055 Add nav bars to live radio page
  src/app/containers/Header/index.jsx
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/tigrinya.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#3082 Update assetsFilter to stop excluding part of vendor bundle
  src/server/assets/assetsFilter/index.js
  src/server/assets/assetsFilter/index.test.js
Labels: articles-features-stream, high priority, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#3030 Update all psammead dependencies
  package-lock.json
  package.json
  scripts/bundleSize.sh
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/containers/Brand/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/ChartbeatAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/Text.jsx
  src/app/containers/ConsentBanner/Banner/__snapshots__/Text.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/index.amp.jsx
  src/app/containers/ConsentBanner/Banner/index.canonical.jsx
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Fragment/__snapshots__/index.test.jsx.snap
  src/app/containers/Fragment/index.jsx
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPage/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/MediaIndicator/__snapshots__/index.test.jsx.snap
  src/app/lib/styledGrid/index.jsx
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream

#3047 Fix media data routing
  src/app/routes/getInitialData/mediapage/index.js
  src/app/routes/getInitialData/mediapage/index.test.js
  src/server/index.jsx
Labels: ws-media- LiveRadioV1, ws-media-stream

#3058 Speed up puppeteer and make it less flakey hopefully
  puppeteer/bundleRequests.test.js
Labels: simorgh-core-stream

#3039 Make Punjabi timestamps show in Punjabi.
  src/app/lib/config/services/punjabi.js
Labels: ws-fp-phase2, ws-frontpage-stream

#3010 Latest consent banner
  package-lock.json
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/index.amp.test.jsx
  src/app/containers/ConsentBanner/Banner/index.canonical.test.jsx
Labels: shared-components

#3081 Change to uppercase p
  src/app/containers/ATIAnalytics/params/frontpage/index.test.jsx
  src/app/contexts/RequestContext/index.test.jsx
Labels: simorgh-core-stream

#3052 Use correct propType for data payload
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ChartbeatAnalytics/index.jsx
  src/app/containers/PageHandlers/withData/index.jsx
  src/app/containers/PageHandlers/withPageWrapper/index.jsx
  src/app/models/propTypes/article/index.js
  src/app/models/propTypes/data/index.js
  src/app/models/propTypes/frontPage/index.js
  src/app/models/propTypes/inline/index.js
  src/app/models/propTypes/paragraph/index.js
Labels: articles-current-epic, articles-features-stream, simorgh-core-stream

#2843 Use correct Nassim fonts for Arabic, Pashto && Urdu services.
  package-lock.json
  package.json
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorPage/index.test.jsx
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/urdu.js
Labels: articles-current-epic, articles-features-stream, high priority

#3086 Updating Copyright Cypress test to be include BBC Copyright
  cypress/support/commands/pageTestFragment/articleBody.js
Labels: articles-features-stream, integration-testing

#2997 Changed the format of timestamps for story promos
  src/app/containers/StoryPromo/index.jsx
Labels: ws-frontpage-stream

#3045 Fixed date for timestamp story
  .storybook/config.js
  package-lock.json
  package.json
Labels: simorgh-core-stream

#3105 Change string to number
  src/app/containers/ArticleTimestamp/index.test.jsx
Labels: simorgh-core-stream

#3111 Fix react warning origins
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.test.jsx
Labels: simorgh-core-stream

#3115 add data/ to pack/ for building the RPM
  scripts/jenkinsProductionFiles.sh
Labels: ws-media- LiveRadioV1, ws-media-stream

#2946 Add PoC Media Player with placeholder
  .storybook/webpack.config.js
  data/news/articles/c3wmq4d1y3wo.json
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/containers/MediaPlayer/Metadata.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/amp/index.jsx
  src/app/containers/MediaPlayer/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/canonical/index.jsx
  src/app/containers/MediaPlayer/canonical/index.test.jsx
  src/app/containers/MediaPlayer/helpers/embedUrl.js
  src/app/containers/MediaPlayer/helpers/embedUrl.test.js
  src/app/containers/MediaPlayer/helpers/fixtureData.jsx
  src/app/containers/MediaPlayer/helpers/fixtures.js
  src/app/containers/MediaPlayer/helpers/metadata/index.js
  src/app/containers/MediaPlayer/helpers/metadata/index.test.js
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.stories.jsx
  src/app/containers/MediaPlayer/index.test.jsx
Labels: articles-av-epic, articles-features-stream

#3101 WS Fonts
  package-lock.json
  package.json
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/tigrinya.js
Labels: shared-components, ws-frontpage-stream, ws-media-stream

#2998 Fixed key prop warnings
  src/app/containers/Headings/index.test.jsx
Labels: bug, simorgh-core-stream

#3123 Add smoke test key to config, but dont use it yet
  cypress/integration/pages/article/amp.js
  cypress/integration/pages/article/canonical.js
  cypress/integration/pages/errorPages/index.js
  cypress/integration/pages/frontPage/amp.js
  cypress/integration/pages/frontPage/canonical.js
  cypress/integration/specialFeatures/cookieBanner.amp.js
  cypress/integration/specialFeatures/cookieBanner.canonical.js
  cypress/support/config/services.js
  puppeteer/bundleRequests.test.js
Labels: simorgh-core-stream

#3125 Missing frontpage object
  cypress/support/config/services.js
Labels: simorgh-core-stream

#3124 (Temporary fix) Change embed URL TLD for test env 🤕
  envConfig/test.env
Labels: articles-av-epic, articles-features-stream, high priority

#3083 Added footer links and labels for Thai
  src/app/lib/config/services/thai.js
Labels: ux, ws-fp-phase2, ws-frontpage-stream

#3088 Fixed react warnings
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.test.jsx
Labels: bug, simorgh-core-stream

#3109 Fixed react warnings
  src/app/containers/FrontPage/index.test.jsx
Labels: bug, simorgh-core-stream

#3032 Use latest WS SVGs
  src/app/containers/MediaPage/__snapshots__/index.test.jsx.snap
  src/app/contexts/ServiceContext/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/zhongwen.js
Labels: articles-current-epic, articles-features-stream, shared-components, ws-fp-phase2, ws-frontpage-stream

#3085 use the correct script sizes for thai & punjabi
  package-lock.json
  package.json
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/thai.js
Labels: ws-fp-phase2, ws-frontpage-stream

#3091 Add afaan-oromoo footer translations
  src/app/lib/config/services/afaanoromoo.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#3104 fix sw and manifest paths
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/zhongwen.js
Labels: articles-features-stream, infra-tooling-stream, simorgh-core-stream, ws-fp-phase2, ws-frontpage-stream, ws-media-stream

#3118 Enable consent/cookie banner for Thai
  src/app/lib/config/services/thai.js
Labels: high priority, ux, ws-fp-phase2, ws-frontpage-stream

#2971 Add analytics to live radio pages
  README.md
  data/indonesia/bbc_indonesian_radio/liveradio.json
  scripts/bundleSize.sh
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/params/media/index.jsx
  src/app/containers/ATIAnalytics/params/media/index.test.jsx
  src/app/containers/MediaPageMain/index.jsx
Labels: ws-media- LiveRadioV1, ws-media-stream

#3116 Fixed react warnings
  src/app/containers/Toggle/index.jsx
Labels: bug, simorgh-core-stream

#3120 Fixed react warnings
  src/app/containers/InlineLink/index.test.jsx
Labels: bug, simorgh-core-stream

#3153 Rmv terser from prod deps
  package-lock.json
  package.json
Labels: simorgh-core-stream

#3172 Fixed react warnings.
  src/app/containers/PageHandlers/withPageWrapper/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withPageWrapper/index.test.jsx
Labels: bug, simorgh-core-stream

#3106 Add chartbeat to frontpage
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/FrontPageMain/index.test.jsx
Labels: ws-frontpage-stream

#3179 Update github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: simorgh-core-stream

#3142 Non-Smoke Cypress cron jenkins pipeline
  Jenkinsfile-e2e
  Makefile
Labels: simorgh-core-stream

#3053 Cypress test iterator
  Jenkinsfile-e2e
  Makefile
  cypress.json
  cypress/integration/application/index.js
  cypress/integration/pages/article/amp.js
  cypress/integration/pages/article/canonical.js
  cypress/integration/pages/articles.js
  cypress/integration/pages/errorPage404.js
  cypress/integration/pages/errorPages/index.js
  cypress/integration/pages/frontPage.js
  cypress/integration/pages/frontPage/amp.js
  cypress/integration/pages/frontPage/canonical.js
  cypress/integration/pages/index.js
  cypress/support/bodyTestHelper.js
  cypress/support/commands/index.js
  cypress/support/commands/pageTestFragment/articleBody.js
  cypress/support/commands/pageTestFragment/metaData.js
  cypress/support/iterator.js
  cypress/support/limitEnvRuns.js
Labels: simorgh-core-stream

#3143 Refactor embedUrl to create base URL from origin
  .storybook/webpack.config.js
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/helpers/embedUrl.js
  src/app/containers/MediaPlayer/helpers/embedUrl.test.js
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.stories.jsx
Labels: articles-av-epic, articles-features-stream

#2791 Inline block support
  data/news/articles/c0000000035o.json
  data/news/articles/cv7yn5n25rno.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
  src/app/components/InlineSpan/__snapshots__/index.test.jsx.snap
  src/app/components/InlineSpan/index.jsx
  src/app/components/InlineSpan/index.test.jsx
  src/app/containers/InlineContainer/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineContainer/index.jsx
  src/app/containers/InlineContainer/index.test.jsx
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/index.jsx
  src/app/containers/Paragraph/index.test.jsx
  src/app/models/propTypes/inline/index.js
Labels: articles-current-epic, articles-features-stream

#3184 Fix jenkins cron e2e
  Jenkinsfile-e2e
Labels: simorgh-core-stream

#3177 Fixed react warnings, translations still needed however
  src/app/containers/MediaPage/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPage/index.test.jsx
Labels: bug, simorgh-core-stream

#3090 add live radio fixture data
  data/afaanoromoo/bbc_afaanoromoo_radio/liveradio.json
  data/amharic/bbc_amharic_radio/liveradio.json
  data/indonesia/bbc_indonesian_radio/liveradio.json
  data/korean/bbc_korean_radio/liveradio.json
  data/tigrinya/bbc_tigrinya_radio/liveradio.json
  src/app/containers/ATIAnalytics/params/media/index.test.jsx
  src/app/containers/MediaPageMain/index.jsx
  src/app/containers/MediaPageMain/index.test.jsx
  src/app/containers/Metadata/index.jsx
Labels: ws-media- LiveRadioV1, ws-media-stream

#3175 Yoruba timestamps again
  src/app/containers/StoryPromo/index.test.jsx
  src/app/lib/config/services/yoruba.js
Labels: bug, high priority, ws-fp-v1, ws-frontpage-stream

#3140 Fixed react warnings.
  src/app/containers/App/App.test.jsx
Labels: bug, simorgh-core-stream

#3141 Fixed react warnings.
  src/app/models/propTypes/general/index.test.js
Labels: bug, simorgh-core-stream

#3182 Fixed react warnings.
  src/app/containers/FrontPageSection/index.jsx
Labels: bug, simorgh-core-stream

#3185 Jest flakiness
  3rdPartyCypress/cypress/integration/errorPageNews.js
  cypress/integration/pages/errorPage404.js
  cypress/integration/specialFeatures/cookieBanner.amp.js
  cypress/integration/specialFeatures/cookieBanner.canonical.js
  cypress/support/iterator.js
  puppeteer/bundleRequests.test.js
Labels: infra-tooling-stream, simorgh-core-stream

#3181 Fixed the issues with footer links for Thai
  src/app/lib/config/services/thai.js
Labels: ux, ws-fp-phase2, ws-frontpage-stream

#3193 use correct build result value
  Jenkinsfile-e2e
Labels: simorgh-core-stream

#3173 Bump psammead-sitewide-links
  package-lock.json
  package.json
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPage/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withPageWrapper/__snapshots__/index.test.jsx.snap
Labels: ws-media- LiveRadioV1, ws-media-stream

#2954 Add media page to storybook
  package-lock.json
  package.json
  src/app/containers/MediaPage/index.stories.jsx
  src/app/containers/MediaPageMain/index.stories.jsx
Labels: ws-media-stream

#3121 update jest to explicitly check for prop
  src/app/containers/ATIAnalytics/index.test.jsx
Labels: Heracles, bug, simorgh-core-stream

#3197 manually set build results
  Jenkinsfile-e2e
Labels: simorgh-core-stream

#2961 suppress react test warnings
  src/app/containers/Image/index.test.jsx
  src/testHelpers/index.js
  src/testHelpers/setupTests.js
Labels: simorgh-core-stream

#2945 Use @bbc/psammead-amp-geo
  package-lock.json
  package.json
  src/app/containers/ConsentBanner/index.amp.jsx
  src/app/containers/MediaPage/__snapshots__/index.test.jsx.snap
Labels: shared-components

#3092 fix react warning: pass boolean, not string
  src/app/containers/PageHandlers/withError/index.jsx
  src/app/containers/PageHandlers/withError/index.test.jsx
Labels: simorgh-core-stream

#2612 don't hydrate on unknown routes
  src/client.js
  src/client.test.jsx
  src/server/index.jsx
Labels: bug, simorgh-core-stream

#3201 Un-parallelise the e2es
  Jenkinsfile-e2e
Labels: simorgh-core-stream

#3202 Update dev deps and rmv snyk
  package-lock.json
  package.json
Labels: simorgh-core-stream

#3204 Configure cypress timeouts in cypress config
  cypress/cypress.json
  cypress/integration/pages/errorPage404.js
  cypress/integration/specialFeatures/cookieBanner.amp.js
  cypress/integration/specialFeatures/cookieBanner.canonical.js
  cypress/support/iterator.js
Labels: infra-tooling-stream

#3208 Add david badge
  README.md
Labels: simorgh-core-stream

#3212 Discard builds
  Jenkinsfile
  Jenkinsfile-e2e
Labels: infra-tooling-stream, simorgh-core-stream

#3194 Add separator to formatDuration
  src/app/containers/StoryPromo/LinkContents/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/LinkContents/index.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/lib/utilities/describeDuration/index.js
  src/app/lib/utilities/describeDuration/index.test.js
  src/app/lib/utilities/formatDuration/index.js
  src/app/lib/utilities/formatDuration/index.test.js
Labels: ux, ws-frontpage-stream

#3248 Add eslint-disable
  puppeteer/bundleRequests.test.js
Labels: simorgh-core-stream

#3203 Update prod dep and test dep that packages prod code
  package-lock.json
  package.json
Labels: simorgh-core-stream

#3224 Suppress React warnings in src/app/containers/Text/index.test.jsx
  src/app/containers/Text/index.test.jsx
Labels: Heracles, bug, simorgh-core-stream

#3215 Update Persian article:author to be bbcnews
  src/app/lib/config/services/persian.js
Labels: articles-current-epic, articles-features-stream

#3217 Support GNU and BSD environments
  package.json
Labels: Heracles, simorgh-core-stream

#3247 Suppress React.Warning in src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
Labels: Heracles, bug, simorgh-core-stream

#3131 Pass locale correctly to Gregorian timestamps in Urdu
  cypress/integration/pages/articles.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/urdu.js
Labels: articles-current-epic, articles-features-stream

#3250 Fix React warnings: null exception in src/app/containers/Headings/index.test.jsx
  src/app/containers/Headings/index.test.jsx
Labels: Heracles, bug, simorgh-core-stream

#3126 Chartbeat author url bug
  src/app/containers/ChartbeatAnalytics/index.jsx
  src/app/containers/ChartbeatAnalytics/index.test.jsx
Labels: articles-current-epic, articles-features-stream, ws-frontpage-stream

#3048 Updated and removed redundant scripts
  .stylelintrc
  .travis.yml
  Makefile
  README.md
  package.json
  scripts/lighthouseRun.sh
  scripts/packagelockHttps.sh
Labels: Documentation, Iolaus, simorgh-core-stream

#3251 AV: Make placeholder optional
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/amp/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/amp/index.jsx
  src/app/containers/MediaPlayer/amp/index.test.jsx
  src/app/containers/MediaPlayer/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/canonical/index.jsx
  src/app/containers/MediaPlayer/canonical/index.test.jsx
  src/app/containers/MediaPlayer/helpers/placeholder.js
  src/app/containers/MediaPlayer/helpers/placeholder.test.js
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/MediaPlayer/placeholder/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/placeholder/index.jsx
  src/app/containers/MediaPlayer/placeholder/index.test.jsx
  src/app/containers/MediaPlayer/wrapper/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/wrapper/index.jsx
  src/app/containers/MediaPlayer/wrapper/index.test.jsx
  src/app/models/propTypes/index.js
Labels: articles-av-epic, articles-features-stream, ws-media-stream

#2991 Added all available and relevant producer id's for ATI custom variable
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/atiUrl/index.test.js
  src/app/containers/ATIAnalytics/params/article/index.jsx
  src/app/containers/ATIAnalytics/params/article/index.test.jsx
  src/app/containers/ATIAnalytics/params/frontpage/index.jsx
  src/app/containers/ATIAnalytics/params/frontpage/index.test.jsx
  src/app/containers/ATIAnalytics/params/media/index.jsx
  src/app/containers/ATIAnalytics/params/media/index.test.jsx
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/lib/analyticsUtils/index.js
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: articles-current-epic, articles-features-stream, ws-media-stream

#3294 Add missing uid prop
  src/app/containers/ChartbeatAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ChartbeatAnalytics/canonical/index.test.jsx
Labels: bug, simorgh-core-stream

#3284 Merge cypress jsons
  cypress.json
  cypress/cypress.json
Labels: infra-tooling-stream, simorgh-core-stream

#3122 Media page metadata and propTypes tweaks
  data/afaanoromoo/bbc_afaanoromoo_radio/liveradio.json
  data/amharic/bbc_amharic_radio/liveradio.json
  data/korean/bbc_korean_radio/liveradio.json
  data/persian/bbc_dari_radio/liveradio.json
  data/persian/bbc_persian_radio/liveradio.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
  src/app/containers/MediaPage/index.test.jsx
  src/app/containers/MediaPageMain/index.jsx
  src/app/containers/MediaPageMain/index.test.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/models/propTypes/data/index.js
  src/app/models/propTypes/mediaPage/content/aresBlock/index.js
  src/app/models/propTypes/mediaPage/content/index.js
  src/app/models/propTypes/mediaPage/content/version/index.js
  src/app/models/propTypes/mediaPage/index.js
  src/app/models/propTypes/metadata/index.js
  src/app/models/propTypes/promo/index.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#3267 mock the MediaPageMain to stop 500 snapshot
  src/app/containers/MediaPage/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPage/index.test.jsx
Labels: bug, ws-media- LiveRadioV1, ws-media-stream

#3309 make the renderBlock() better
  src/app/containers/MediaPageMain/index.jsx
Labels: ws-media- LiveRadioV1, ws-media-stream

#3304 Fixed react warnings
  src/app/containers/ArticleTimestamp/index.test.jsx
Labels: bug, simorgh-core-stream

#3305 Adding mobile viewport Cypress tests && fixing Thai top-story component
  cypress/integration/pages/frontPage.js
  data/thai/frontpage/index.json
  src/app/lib/utilities/preprocessor/rules/__snapshots__/topstories.test.js.snap
Labels: integration-testing, ws-frontpage-stream

#3299 Fixed react warnings
  src/app/containers/ChartbeatAnalytics/amp/index.jsx
  src/app/containers/ChartbeatAnalytics/amp/index.test.jsx
Labels: bug, simorgh-core-stream

#3249 Add missing ati destinations and logic
  src/app/contexts/RequestContext/getStatsDestination/index.js
  src/app/contexts/RequestContext/getStatsDestination/index.test.js
  src/app/lib/analyticsUtils/index.js
Labels: articles-current-epic, articles-features-stream

#3300 Fixed react warnings
  src/app/components/InlineSpan/__snapshots__/index.test.jsx.snap
  src/app/components/InlineSpan/index.test.jsx
Labels: bug, simorgh-core-stream

#3313 export smokeTest. add tests. use in cookiebanner
  cypress/integration/specialFeatures/cookieBanner.amp.js
  cypress/integration/specialFeatures/cookieBanner.canonical.js
  cypress/support/iterator.js
  cypress/support/shouldSmokeTest/index.js
  cypress/support/shouldSmokeTest/index.test.js
  src/testHelpers/jest-setup.js
Labels: bug, simorgh-core-stream, ws-media- LiveRadioV1, ws-media-stream

#3308 Korean indonesian footer translations
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/korean.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#3280 cypress config for all live radio services
  cypress/support/config/services.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#3320 Fix React warnings in src/app/containers/FrontPage/index.test.jsx
  src/app/containers/FrontPage/index.test.jsx
Labels: bug, simorgh-core-stream

#3328 Revert "Revert changes that seem to break the e2e pipeline"
  Jenkinsfile-e2e
Labels: infra-tooling-stream

#3331 Restore e2e config consistency with undefined liveRadio
  cypress/support/config/services.js
Labels: simorgh-core-stream

#3337 Increase e2e run freq
  Jenkinsfile-e2e
  cypress/support/config/services.js
Labels: high priority, infra-tooling-stream, simorgh-core-stream

#3315 Fix React warnings in src/app/containers/PageHandlers/withData/index.test.jsx
  src/app/containers/PageHandlers/withData/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withData/index.test.jsx
Labels: bug, simorgh-core-stream
