Repository bbc/simorgh, pull requests merged in 2019-10, with the labels that each got.

#4048 Add public/images and audio placedholder image
  public/images/audio-player-placeholder.png
Labels: ws-media- LiveRadioV1, ws-media-stream

#3999 Update Mundo, Brasil, Turkce, Cymru Fyw and Naidheachdan to use Reith fonts
  cypress/support/config/services.js
  package-lock.json
  package.json
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/turkce.js
Labels: articles-features-stream, articles-next-13

#3559 Scalable Event Tracking
  src/app/containers/ATIAnalytics/README.md
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/atiUrl/index.test.js
  src/app/containers/ATIAnalytics/beacon/index.js
  src/app/containers/ATIAnalytics/beacon/index.test.js
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/article/buildParams.js
  src/app/containers/ATIAnalytics/params/article/buildParams.test.js
  src/app/containers/ATIAnalytics/params/article/index.test.jsx
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.js
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/frontpage/index.jsx
  src/app/containers/ATIAnalytics/params/frontpage/index.test.jsx
  src/app/containers/ATIAnalytics/params/index.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/ATIAnalytics/params/radioPage/index.jsx
  src/app/containers/ATIAnalytics/params/radioPage/index.test.jsx
  src/app/containers/ATIAnalytics/params/radiopage/buildParams.js
  src/app/containers/ATIAnalytics/params/radiopage/buildParams.test.js
  src/app/containers/FrontPage/index.test.jsx
  src/app/containers/PageHandlers/withContexts.jsx
  src/app/contexts/EventContext/README.md
  src/app/contexts/EventContext/__snapshots__/index.test.jsx.snap
  src/app/contexts/EventContext/index.jsx
  src/app/contexts/EventContext/index.test.jsx
  src/app/contexts/EventContext/useHandlerMap/index.js
  src/app/contexts/EventContext/useHandlerMap/index.test.js
  src/app/contexts/EventContext/useWindowEvent/index.js
  src/app/contexts/EventContext/useWindowEvent/index.test.js
  src/app/lib/analyticsUtils/frontpage/index.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
Labels: shared-components, simorgh-core-stream, ws-frontpage-stream

#3945 Remove test helpers (major changes #5)
  package-lock.json
  package.json
  src/app/containers/ATIAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ATIAnalytics/canonical/index.test.jsx
  src/app/containers/App/__snapshots__/index.test.jsx.snap
  src/app/containers/App/index.test.jsx
Labels: Heracles, simorgh-core-stream

#4062 Fix cypress link tests
  cypress/integration/pages/testsForAllPages.js
Labels: simorgh-core-stream

#4061 Add Logging to simorgh to test upstream change
  src/server/index.jsx
Labels: simorgh-core-stream

#3982 Cps asset routing
  data/afrique/mediaAssetPage/48465371.json
  src/app/containers/Metadata/index.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/routes/getInitialData/cpsAsset/index.js
  src/app/routes/getInitialData/cpsAsset/index.test.js
  src/app/routes/index.js
  src/app/routes/index.test.js
  src/app/routes/regex/index.js
  src/app/routes/regex/index.test.js
  src/server/index.jsx
Labels: simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#3983 Up the e2e pipeline timeout period
  Jenkinsfile-e2e
  Jenkinsfile-e2e-test
Labels: simorgh-core-stream

#4049 Add placeholderSrc if AMP
  package-lock.json
  package.json
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
Labels: ws-media- LiveRadioV1, ws-media-stream

#4047 Add live radio to bbc a11y checks
  a11y.js
Labels: simorgh-core-stream, ws-media-stream

#4058 Remove test helpers (major changes #6)
  src/app/containers/Blocks/__snapshots__/index.test.jsx.snap
  src/app/containers/Blocks/index.test.jsx
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/index.test.jsx
  src/app/containers/MPulseBeacon/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/Heading/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/Paragraph/index.test.jsx
  src/app/lib/analyticsUtils/sendBeacon/index.test.js
  src/app/lib/utilities/preprocessor/index.test.js
  src/app/routes/getInitialData/utils/fetchData/index.test.js
  src/client.test.jsx
  src/server/utilities/logResponseTime/index.test.js
  src/testHelpers/index.js
  src/testHelpers/loggerMock.js
Labels: Heracles, simorgh-core-stream

#4070 radioPage not radiopage
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/params/index.js
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.js
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.test.js
Labels: bug, simorgh-core-stream, ws-media-stream

#4063 Bump timestamp container
  package-lock.json
  package.json
Labels: simorgh-core-stream, ws-frontpage-stream

#4046 Add E2E non-smoke test prompt to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: simorgh-core-stream

#3965 Passport home refactor
  src/app/containers/PageHandlers/withData/shouldRender/index.test.js
  src/app/lib/utilities/passport/index.js
Labels: simorgh-core-stream

#4074 Fix Afrique timestamp bug
  src/app/lib/config/services/afrique.js
Labels: bug, shared-components, simorgh-core-stream

#4059 Import moment locales to Indonesia and Vietnamese configs
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/vietnamese.js
Labels: articles-features-stream, articles-next-13, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#4076 Moment locale import fix
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/turkce.js
Labels: Heracles, shared-components, simorgh-core-stream, ws-frontpage-stream

#4073 Add cypress/fixtures to version control
  cypress/fixtures/.keep
Labels: articles-features-stream, simorgh-core-stream

#4081 rewrite metadata tests using react testing library
  src/app/containers/Metadata/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/index.test.jsx
Labels: simorgh-core-stream

#4079 Bump psammead media player for valid amp
  package-lock.json
  package.json
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
Labels: ws-media- LiveRadioV1, ws-media-stream

#4064 Enable the /scotland article e2e on test
  cypress/support/config/services.js
Labels: simorgh-core-stream

#4082 Use psammead-locales for News and Scotland
  package-lock.json
  package.json
  src/app/containers/StoryPromo/index.test.jsx
  src/app/lib/config/services/news.js
  src/app/lib/config/services/scotland.js
Labels: articles-features-stream, articles-next-13, ws-frontpage-stream

#4086 Fix scotland e2es
  cypress/integration/application/index.js
Labels: simorgh-core-stream

#4095 Fix Scotland e2es for live
  cypress/integration/application/index.js
Labels: simorgh-core-stream

#4104 Add icons for Cymru Fyw and Naidheachdan
  public/cymrufyw/images/icons/icon-128x128.png
  public/cymrufyw/images/icons/icon-144x144.png
  public/cymrufyw/images/icons/icon-152x152.png
  public/cymrufyw/images/icons/icon-192x192.png
  public/cymrufyw/images/icons/icon-384x384.png
  public/cymrufyw/images/icons/icon-512x512.png
  public/cymrufyw/images/icons/icon-72x72.png
  public/cymrufyw/images/icons/icon-96x96.png
  public/naidheachdan/images/icons/icon-128x128.png
  public/naidheachdan/images/icons/icon-144x144.png
  public/naidheachdan/images/icons/icon-152x152.png
  public/naidheachdan/images/icons/icon-192x192.png
  public/naidheachdan/images/icons/icon-384x384.png
  public/naidheachdan/images/icons/icon-512x512.png
  public/naidheachdan/images/icons/icon-72x72.png
  public/naidheachdan/images/icons/icon-96x96.png
Labels: articles-features-stream, articles-next-13

#4071 Rename mediaAssetPages to cpsAssets
  data/afaanoromoo/cpsAssets/oduu-49490954.json
  data/afrique/cpsAssets/48465371.json
  data/afrique/cpsAssets/monde-49500638.json
  data/afrique/featureIndex/48465371.json
  data/amharic/cpsAssets/news-49562667.json
  data/arabic/cpsAssets/media-49580542.json
  data/azeri/cpsAssets/region-49364777.json
  data/bengali/cpsAssets/news-49579870.json
  data/burmese/cpsAssets/media-49571787.json
  data/gahuza/cpsAssets/amakuru-49534170.json
  data/gujarati/cpsAssets/media-49502679.json
  data/hausa/cpsAssets/labarai-49513456.json
  data/hindi/cpsAssets/39414759.json
  data/hindi/cpsAssets/media-49583110.json
  data/igbo/cpsAssets/media-42986440.json
  data/indonesia/cpsAssets/media-49591990.json
  data/japanese/cpsAssets/video-23248670.json
  data/japanese/cpsAssets/video-49589128.json
  data/korean/cpsAssets/media-23248686.json
  data/korean/cpsAssets/media-49590387.json
  data/kyrgyz/cpsAssets/sapar-tv-48695523.json
  data/marathi/cpsAssets/43599597.json
  data/marathi/cpsAssets/india-48062804.json
  data/mundo/cpsAssets/noticias-49546078.json
  data/nepali/cpsAssets/news-49613544.json
  data/pashto/cpsAssets/afghanistan-49628873.json
  data/persian/cpsAssets/39120696.json
  data/persian/cpsAssets/world-49653162.json
  data/pidgin/cpsAssets/23248703.json
  data/pidgin/cpsAssets/tori-49450859.json
  data/portuguese/cpsAssets/geral-49602758.json
  data/punjabi/cpsAssets/international-49567825.json
  data/punjabi/cpsAssets/media-23248705.json
  data/russian/cpsAssets/media-49281069.json
  data/serbian/cpsAssets/srbija-49427344/cyr.json
  data/serbian/cpsAssets/srbija-49427344/lat.json
  data/sinhala/cpsAssets/23248970.json
  data/sinhala/cpsAssets/sri-lanka-49411205.json
  data/somali/cpsAssets/media-48870869.json
  data/swahili/cpsAssets/dira-tv-49602132.json
  data/tamil/cpsAssets/science-49626264.json
  data/telugu/cpsAssets/india-49647976.json
  data/thai/cpsAssets/international-49514085.json
  data/thai/cpsAssets/thailand-23248713.json
  data/thai/cpsAssets/thailand-49659092.json
  data/tigrinya/cpsAssets/news-49562338.json
  data/turkce/cpsAssets/haberler-dunya-49655644.json
  data/ukchina/cpsAssets/49375846/simp.json
  data/ukchina/cpsAssets/49375846/trad.json
  data/ukrainian/cpsAssets/media-49656852.json
  data/urdu/cpsAssets/pakistan-49644768.json
  data/uzbek/cpsAssets/sport-23248721.json
  data/uzbek/cpsAssets/uzbekistan-49192467.json
  data/vietnamese/cpsAssets/media-49614583.json
  data/yoruba/cpsAssets/media-42985961.json
  data/zhongwen/cpsAssets/chinese-news-49631219/simp.json
  data/zhongwen/cpsAssets/chinese-news-49631219/trad.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
  dataValidator/helpers/dataLoader/readScenario.js
  src/server/index.jsx
Labels: simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#4068 Bumped psammead-styles and integrating fonts override
  .storybook/config.js
  package-lock.json
  package.json
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/contexts/ToggleContext/__snapshots__/index.test.jsx.snap
  src/testHelpers/mockComponents.jsx
Labels: simorgh-core-stream

#4106 Update next 12 WS sites fixture data
  data/afaanoromoo/articles/c4g19kgl85ko.json
  data/afrique/articles/cz216x22106o.json
  data/azeri/articles/c5k08pqnzexo.json
  data/gahuza/articles/cey23zx8wx8o.json
  data/hausa/articles/c2nr6xqmnewo.json
  data/igbo/articles/cr1lw620ygjo.json
  data/indonesia/articles/c0q2zq8pzvzo.json
  data/pidgin/articles/cwl08rd38l6o.json
  data/somali/articles/cgn6emk3jm8o.json
  data/swahili/articles/czjqge2jwn2o.json
  data/vietnamese/articles/c3y59g5zm19o.json
  data/yoruba/articles/clw06m0nj8qo.json
Labels: articles-features-stream, articles-next-13

#4107 Enable /naidheachdan article tests on test
  cypress/support/config/services.js
Labels: simorgh-core-stream

#4085 3839 split data status
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/Article/index.test.jsx
  src/app/containers/Error/index.jsx
  src/app/containers/Error/index.test.jsx
  src/app/containers/FrontPage/index.test.jsx
  src/app/containers/PageHandlers/withContexts.jsx
  src/app/containers/PageHandlers/withContexts.test.jsx
  src/app/containers/PageHandlers/withData/index.jsx
  src/app/containers/PageHandlers/withData/index.test.jsx
  src/app/containers/PageHandlers/withData/shouldRender/index.js
  src/app/containers/PageHandlers/withPageWrapper/index.jsx
  src/app/containers/PageHandlers/withPageWrapper/index.test.jsx
  src/app/containers/RadioPage/index.test.jsx
  src/app/routes/index.js
  src/app/routes/index.test.js
Labels: simorgh-core-stream

#4116 Fix double notification of test alarms and send all failures to alarm…
  Jenkinsfile-e2e
  Jenkinsfile-e2e-test
Labels: simorgh-core-stream

#4109 Move trust project link
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: articles-features-stream, articles-next-13, bug, shared-components

#4072 Bump 3rd Party Deps
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
Labels: simorgh-core-stream

#4110 Fixture fixes
  data/afrique/articles/cz216x22106o.json
  data/igbo/articles/cr1lw620ygjo.json
Labels: articles-features-stream, articles-next-13

#4147 Fix embed endpoint on github storybook
  src/app/containers/MediaPlayer/helpers/embedUrl.js
  src/app/containers/MediaPlayer/helpers/embedUrl.test.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#4152 Add brands for Cymru Fyw and Naidheachdan
  package-lock.json
  package.json
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/naidheachdan.js
Labels: articles-features-stream, articles-next-13

#4149 Add data attributes to cookie banner
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/getDataAttribute.js
  src/app/containers/ConsentBanner/Banner/getDataAttribute.test.js
  src/app/containers/ConsentBanner/Banner/index.amp.jsx
  src/app/containers/ConsentBanner/Banner/index.canonical.jsx
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
Labels: ws-frontpage-stream

#4119 Add Cloud-Init as a speculate dependency
  package.json
Labels: infra-tooling-stream

#4083 Metadata refactor
  package.json
  src/app/components/LinkedData/__snapshots__/index.test.jsx.snap
  src/app/components/LinkedData/index.jsx
  src/app/components/LinkedData/index.test.jsx
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.jsx
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/ArticleMain/index.test.jsx
  src/app/containers/ArticleMain/utils.js
  src/app/containers/ArticleMain/utils.test.js
  src/app/containers/ArticleMetadata/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMetadata/index.jsx
  src/app/containers/ArticleMetadata/index.test.jsx
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/LinkedData/__snapshots__/index.test.jsx.snap
  src/app/containers/LinkedData/getAboutTagsContent.js
  src/app/containers/LinkedData/getAboutTagsContent.test.js
  src/app/containers/LinkedData/index.jsx
  src/app/containers/LinkedData/index.test.jsx
  src/app/containers/Metadata/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/Metadata/linkedDataAbout/index.test.js
  src/app/containers/RadioPageMain/index.jsx
Labels: simorgh-core-stream

#4117 Live radio image placeholder for AMP
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  public/images/amp_audio_placeholder.png
  public/images/audio-player-placeholder.png
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMetadata/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/testHelpers/jest-setup.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#4067 Article timestamp coverage
  src/app/containers/ArticleTimestamp/helpers.test.js
Labels: articles-current-epic, articles-features-stream, shared-components

#4173 Revert "Live radio image placeholder for AMP"
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  public/images/amp_audio_placeholder.png
  public/images/audio-player-placeholder.png
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMetadata/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/testHelpers/jest-setup.js
Labels: simorgh-core-stream, ws-media- LiveRadioV1, ws-media-stream

#4158 Add new fixtures for APUP + MTB
  data/arabic/articles/c1er5mjnznzo.json
  data/mundo/articles/ce42wzqr2mko.json
  data/pashto/articles/cyjmdl92z3ro.json
  data/persian/articles/cej3lzd5e0go.json
  data/portuguese/articles/cd61pm8gzmpo.json
  data/turkce/articles/c8q1ze59n25o.json
  data/urdu/articles/cwgq7rzv172o.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
Labels: articles-features-stream, articles-next-13

#4123 Remove the dial agent
  package.json
Labels: infra-tooling-stream

#4151 Bumping dependencies
  package-lock.json
  package.json
  src/app/containers/ChartbeatAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/lib/styledGrid/index.test.jsx
Labels: dependencies, simorgh-core-stream

#4167 Map page skeleton
  src/app/containers/CpsAssetPage/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPage/index.jsx
  src/app/containers/CpsAssetPage/index.test.jsx
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/routes/index.js
  src/app/routes/index.test.js
Labels: ws-media-asset-page-v1, ws-media-stream

#4177 Fix storybook by adding missing Reith Italic font
  .storybook/static/fonts/Reith/BBCReithSans_W_It.woff2
Labels: simorgh-core-stream

#4122 Implement Jalaali alternative calendar into Article Timestamps
  package-lock.json
  package.json
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
Labels: articles-current-epic, articles-features-stream, shared-components, ws-frontpage-stream

#4084 Error page - Move error code out of h1
  cypress/integration/application/index.js
  cypress/integration/pages/errorPage404/tests.js
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorPage/index.jsx
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
Labels: a11y-swarm, shared-components, ux

#4183 Fixing Front Page Story
  src/app/containers/FrontPage/index.stories.jsx
  src/app/containers/RadioPage/index.stories.jsx
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#4169 Remove dangerouslySetInnerHTML from RadioPageBlocks
  src/app/containers/RadioPageBlocks/Blocks/Unknown/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/Unknown/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/Unknown/index.test.jsx
  src/app/containers/RadioPageBlocks/index.jsx
  src/server/styles/index.test.jsx
Labels: investigation, simorgh-core-stream

#4199 Correct og image for Nepali
  src/app/lib/config/services/nepali.js
Labels: articles-features-stream, articles-next-13, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#4200 Correct brand images in three services
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/uzbek.js
Labels: articles-features-stream, articles-next-13, shared-components, ws-frontpage-stream, ws-media-stream

#4182 CPS asset page headers
  src/app/containers/CpsAssetPage/index.test.jsx
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
Labels: ws-media-asset-page-v1, ws-media-stream

#3894 Replace e2e timestamp format tests with unit tests
  cypress/integration/pages/articles/tests.js
  src/app/containers/ArticleTimestamp/timeFormatTests/README.md
  src/app/containers/ArticleTimestamp/timeFormatTests/expectedFormats.json
  src/app/containers/ArticleTimestamp/timeFormatTests/generateTimeFormats.js
  src/app/containers/ArticleTimestamp/timeFormatTests/generateTimeFormats.test.js
  src/app/containers/ArticleTimestamp/timeFormatTests/testUtils.js
  src/app/containers/ArticleTimestamp/timeFormatTests/timeFormat.test.js
Labels: articles-current-epic, articles-features-stream, shared-components, ws-frontpage-stream

#4172 delete child metadata component in container
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/helpers/__snapshots__/iconLinks.test.js.snap
  src/app/components/Metadata/helpers/iconLinks.test.js
  src/app/components/Metadata/index.jsx
  src/app/components/Metadata/index.test.jsx
  src/app/components/Metadata/propTypesCheck.js
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/utils.jsx
Labels: simorgh-core-stream

#4185 i18n articles routes
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/routes/getInitialData/article/index.js
  src/app/routes/getInitialData/article/index.test.js
  src/app/routes/getInitialData/cpsAsset/index.js
  src/app/routes/getInitialData/cpsAsset/index.test.js
  src/app/routes/getInitialData/frontpage/index.js
  src/app/routes/getInitialData/frontpage/index.test.js
  src/app/routes/getInitialData/radioPage/index.js
  src/app/routes/getInitialData/radioPage/index.test.js
  src/app/routes/getInitialData/utils/fetchData/index.js
  src/app/routes/getInitialData/utils/fetchData/index.test.js
  src/app/routes/regex/index.js
  src/app/routes/regex/index.test.js
  src/server/index.jsx
Labels: simorgh-core-stream

#4228 Optimisation: stop minifying the `server.js`
  webpack.config.server.js
Labels: Heracles, simorgh-core-stream

#4234 Pull in new SitewideLinks version with fix for IE11
  package-lock.json
  package.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
Labels: articles-features-stream, high priority, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#4189 Fix storybook knobs with timemachine test helper and config file
  .storybook/config.js
  .storybook/time-machine.js
  src/app/containers/ArticleTimestamp/index.stories.jsx
  src/app/containers/FrontPage/index.stories.jsx
  src/app/containers/FrontPageMain/index.stories.jsx
  src/app/containers/RadioPage/index.stories.jsx
  src/app/containers/RadioPageMain/index.stories.jsx
  src/app/lib/utilities/moment/index.stories.jsx
  src/testHelpers/withTimeMachine.jsx
Labels: simorgh-core-stream

#4238 E2e shared library
  Jenkinsfile-e2e
Labels: simorgh-core-stream

#4221 Update Cymru Fyw Article fixture
  data/cymrufyw/articles/c06p32z9x2mo.json
Labels: articles-features-stream, articles-next-13

#4241 Enable article e2es on Live for 13 services
  cypress/support/config/services.js
Labels: articles-features-stream, articles-next-13

#4181 Fix static asset path
  cypress/integration/pages/testsForAllPages.js
  envConfig/live.env
  envConfig/test.env
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMetadata/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/Metadata/utils.jsx
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/testHelpers/jest-setup.js
Labels: simorgh-core-stream

#4176 Use one line eslint opt-out for dangerouslySetInnerHTML usage
  src/app/components/IfAboveIE9Comment/index.jsx
  src/server/Document/component.jsx
Labels: investigation, simorgh-core-stream

#4186 schema.org metadata for Scotland
  src/app/containers/LinkedData/__snapshots__/index.test.jsx.snap
  src/app/containers/LinkedData/index.jsx
  src/app/containers/LinkedData/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: articles-features-stream, articles-next-13

#4226 Standardized article lighthouse a11y test
  package.json
  scripts/lighthouseRun.sh
Labels: articles-current-epic, articles-features-stream, simorgh-core-stream

#4254 Bump packages for new Jalaali calendar functionality
  package-lock.json
  package.json
  src/app/containers/ArticleTimestamp/timeFormatTests/expectedFormats.json
  src/app/lib/config/services/persian.js
Labels: articles-current-epic, articles-features-stream, ws-frontpage-stream

#4261 Update naidheachdan fixture
  data/naidheachdan/articles/c18q7nedn2ko.json
Labels: articles-features-stream, articles-next-13

#4197 Update configs for MBTCN and translations for Naidheachdan
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/turkce.js
Labels: articles-features-stream, articles-next-13

#4280 Fetch error handling refactor
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/routes/getInitialData/utils/fetchData/index.js
  src/app/routes/getInitialData/utils/fetchData/index.test.js
Labels: simorgh-core-stream

#4281 Squash map-api
  scripts/bundleSizeConfig.js
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.js
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/models/propTypes/cpsPage/index.js
  src/app/models/propTypes/data/index.js
Labels: ws-media-stream

#4292 Temporarily disable Lighthouse locally/on CI
  package.json
Labels: infra-tooling-stream, simorgh-core-stream

#4295 Live storybook font paths fix
  .storybook/config.js
Labels: simorgh-core-stream

#4288 Rename CpsPage to CpsAssetPage
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.js
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/models/propTypes/cpsAssetPage/index.js
  src/app/models/propTypes/data/index.js
Labels: ws-media-asset-page-v1, ws-media-stream

#4289 Rename MediaAssetPage to CpsAssetPage in server tests
  src/server/index.test.jsx
Labels: ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4301 Update jenkins file to trigger B/G build
  Jenkinsfile
Labels: infra-tooling-stream

#4230 Useful Links integration
  data/arabic/frontpage/index.json
  data/igbo/frontpage/index.json
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/FrontPageSection/UsefulLinks/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/UsefulLinks/index.jsx
  src/app/containers/FrontPageSection/UsefulLinks/index.test.jsx
  src/app/containers/FrontPageSection/UsefulLinks/usefulItems.js
  src/app/containers/FrontPageSection/index.jsx
  src/app/containers/FrontPageSection/index.stories.jsx
  src/app/containers/FrontPageSection/index.test.jsx
  src/app/lib/utilities/preprocessor/rules/__snapshots__/filterContentType.test.js.snap
  src/app/lib/utilities/preprocessor/rules/__snapshots__/topstories.test.js.snap
  src/app/lib/utilities/preprocessor/rules/filterContentType.js
Labels: ux, ws-fp-phase3, ws-frontpage-stream

#4175 Revert "Revert "Live radio image placeholder for AMP""
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  public/images/amp_audio_placeholder.png
  public/images/audio-player-placeholder.png
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/testHelpers/jest-setup.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#4333 patch vuln package whilst we wait for it to be updated
  package-lock.json
  package.json
Labels: simorgh-core-stream

#4302 Remove import storybook-chromatic (simorgh)
  .storybook/config.js
Labels: simorgh-core-stream

#4270 Articles routes
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/routes/getInitialData/article/index.js
  src/app/routes/getInitialData/article/index.test.js
  src/app/routes/getInitialData/cpsAsset/index.js
  src/app/routes/getInitialData/cpsAsset/index.test.js
  src/app/routes/getInitialData/frontpage/index.js
  src/app/routes/getInitialData/frontpage/index.test.js
  src/app/routes/getInitialData/radioPage/index.js
  src/app/routes/getInitialData/radioPage/index.test.js
  src/app/routes/getInitialData/utils/fetchData/index.js
  src/app/routes/getInitialData/utils/fetchData/index.test.js
  src/app/routes/regex/index.js
  src/app/routes/regex/index.test.js
  src/server/index.jsx
Labels: articles-features-stream, articles-rollout, simorgh-core-stream

#4282 Refactor of media player unit test
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/fixtureData.jsx
  src/app/containers/MediaPlayer/helpers/metadata/index.test.js
  src/app/containers/MediaPlayer/index.stories.jsx
  src/app/containers/MediaPlayer/index.test.jsx
Labels: articles-av-epic, articles-features-stream, ws-media-stream

#4304 Revert "Temporarily disable Lighthouse locally/on CI"
  package.json
Labels: infra-tooling-stream, simorgh-core-stream

#4263 Bump dependencies
  package-lock.json
  package.json
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
Labels: simorgh-core-stream

#4347 Added ReithSans_W_BdIt.woff2
  .storybook/static/fonts/Reith/BBCReithSans_W_BdIt.woff2
Labels: simorgh-core-stream

#4268 Add Cypress tests to verify that media blocks contain placeholder images
  cypress/integration/pages/articles/helpers.js
  cypress/integration/pages/articles/tests.js
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
Labels: articles-av-epic, articles-features-stream, integration-testing, ws-media-stream

#4240 Use psammead-rich-text-transforms; Bundle it seperately; Only load it on the client when required
  cypress/integration/pages/testsForAllPages.js
  cypress/support/config/services.js
  package-lock.json
  package.json
  puppeteer/rich-text-transforms.test.js
  scripts/bundleSizeConfig.js
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/paragraph/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/paragraph/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/utils/helpers.js
  src/app/models/propTypes/cpsAssetPage/index.js
  src/app/models/propTypes/frontPage/index.js
  src/app/models/propTypes/metadata/index.js
  src/app/models/propTypes/promo/index.js
  src/app/models/propTypes/relatedContent/index.js
  src/app/routes/getInitialData/cpsAsset/index.js
  src/app/routes/getInitialData/cpsAsset/index.test.js
  src/app/routes/getInitialData/utils/fetchData/index.js
  webpack.config.js
Labels: ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4355 Revert "Add Cypress tests to verify that media blocks contain placeholder images"
  cypress/integration/pages/articles/helpers.js
  cypress/integration/pages/articles/tests.js
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
Labels: articles-av-epic, articles-features-stream

#4278 Use localhost instead of localhost.bbc.com
  CONTRIBUTING.md
  README.md
  a11y.js
  cypress/support/config/envs.js
  envConfig/local.env
  package.json
  scripts/lighthouseConfig.test.js
  scripts/lighthouseRun.sh
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMetadata/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/helpers/embedUrl.test.js
  src/app/containers/Metadata/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.test.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/index.test.jsx
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/contexts/RequestContext/getOriginContext/index.test.js
  src/testHelpers/config.js
  src/testHelpers/jest-setup.js
  webpack.config.client.js
Labels: simorgh-core-stream

#4340 Remove references to Cosmos dial
  src/app/containers/Error/index.test.jsx
  src/app/containers/PageHandlers/withData/index.test.jsx
Labels: simorgh-core-stream

#4342 Update README with font-display explanation
  README.md
Labels: simorgh-core-stream

#4264 Update dependency check
  .codeclimate.yml
  package-lock.json
  package.json
  scripts/dependencyCheck.js
Labels: Heracles, simorgh-core-stream

#4303 Fix propTypes warnings on client side render
  src/app/containers/PageHandlers/withContexts.jsx
  src/app/containers/PageHandlers/withPageWrapper/index.jsx
  src/app/contexts/RequestContext/index.jsx
Labels: simorgh-core-stream

#4365 Conditionally load Resource Hints for font domains
  3rdPartyCypress/cypress/integration/worldServiceCoUkRedirect.js
  cypress/integration/application/index.js
  cypress/integration/pages/articles/tests.js
  cypress/integration/pages/errorPage404/tests.js
  cypress/integration/pages/frontPage/tests.js
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/testsForCanonicalOnly.js
  cypress/integration/pages/testsForAllPages.js
  cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
  cypress/integration/specialFeatures/cookieBanner/testsForCanonicalOnly.js
  dirAlias.js
  src/app/components/ResourceHints/__snapshots__/index.test.jsx.snap
  src/app/components/ResourceHints/index.jsx
  src/app/containers/ArticleTimestamp/index.stories.jsx
  src/app/containers/ArticleTimestamp/timeFormatTests/generateTimeFormats.js
  src/app/containers/ArticleTimestamp/timeFormatTests/generateTimeFormats.test.js
  src/app/containers/ArticleTimestamp/timeFormatTests/timeFormat.test.js
  src/app/containers/Brand/index.stories.jsx
  src/app/containers/Copyright/index.stories.jsx
  src/app/containers/Footer/index.stories.jsx
  src/app/containers/Header/index.stories.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/Navigation/index.stories.jsx
  src/app/contexts/ServiceContext/__mocks__/index.jsx
  src/app/contexts/ServiceContext/index.test.jsx
  src/app/lib/utilities/moment/index.stories.jsx
  src/app/routes/regex/index.test.js
  src/server/Document/index.jsx
  src/server/index.test.jsx
  src/server/utilities/getAssetOrigins/index.js
  src/server/utilities/getAssetOrigins/index.test.js
  src/server/utilities/serviceConfigs/index.js
  src/testHelpers/serviceConfigs.js
Labels: shared-components, simorgh-core-stream

#4363 Add Welsh translations
  src/app/lib/config/services/cymrufyw.js
Labels: articles-features-stream, articles-rollout

#4356 Fix reverted Cypress tests that verify media blocks contain placeholder images
  cypress/integration/pages/articles/helpers.js
  cypress/integration/pages/articles/tests.js
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
Labels: articles-av-epic, articles-features-stream, integration-testing

#4369 Update e2e cron jobs to not run individual spec files
  Jenkinsfile-e2e
  Jenkinsfile-e2e-test
Labels: infra-tooling-stream

#4380 Add a method to cancel the previous running builds of a given job
  Jenkinsfile
Labels: infra-tooling-stream

#4383 Missed a semicolon
  Jenkinsfile-e2e
Labels: infra-tooling-stream

#4384 Add test CPS STY & PGL assets
  data/igbo/cpsAssets/afirika-23252735.json
  data/igbo/cpsAssets/egwuregwu-23252841.json
  data/japanese/cpsAssets/world-23252833.json
  data/japanese/cpsAssets/world-23252856.json
  data/pidgin/cpsAssets/sport-23252855.json
  data/pidgin/cpsAssets/world-23252817.json
  data/thai/cpsAssets/international-23252825.json
  data/thai/cpsAssets/international-23252840.json
  data/yoruba/cpsAssets/afrika-23252769.json
  data/yoruba/cpsAssets/ere-idaraya-23252842.json
Labels: ws-sty-page-v1

#4290 Add blocks logic to CPS assets, rendering paragraphs
  cypress/integration/pages/mediaAssetPage/tests.js
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/containers/FrontPage/index.stories.jsx
  src/app/containers/FrontPageMain/index.test.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/lib/utilities/preprocessor/index.js
  src/app/lib/utilities/preprocessor/index.test.js
  src/app/routes/getInitialData/cpsAsset/index.js
  src/app/routes/getInitialData/cpsAsset/index.test.js
  src/app/routes/index.js
Labels: ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4364 CPS Media Block Transformer
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/media/fixtures.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/media/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/media/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.test.js
Labels: ws-media-asset-page-v1, ws-media-stream

#4309 CPS Asset Timestamps
  cypress/integration/pages/mediaAssetPage/tests.js
  package-lock.json
  package.json
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/timestampToMilliseconds/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/timestampToMilliseconds/index.test.js
  src/app/routes/getInitialData/cpsAsset/index.js
  src/app/routes/getInitialData/cpsAsset/index.test.js
Labels: ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4308 Add Headlines to CpsAsset
  cypress/integration/pages/mediaAssetPage/tests.js
  package-lock.json
  package.json
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addHeadlineBlock/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addHeadlineBlock/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/timestampToMilliseconds/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/timestampToMilliseconds/index.test.js
  src/app/routes/getInitialData/cpsAsset/index.js
  src/app/routes/getInitialData/cpsAsset/index.test.js
Labels: ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4294 cypress tests for navigation between pages
  cypress/integration/pages/articles/tests.js
  cypress/integration/pages/frontPage/tests.js
  cypress/support/config/services.js
  data/news/articles/cn7k01xp8kxo.json
Labels: simorgh-core-stream

#4401 Escape double quote marks in text values
  data/pidgin/cpsAssets/23248703.json
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/utils/helpers.js
Labels: ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4394 Add images to MAP and STY pages :)
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/image/fixture.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/image/helpers.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/image/helpers.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/image/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/image/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.js
Labels: ws-media-asset-page-v2, ws-media-stream, ws-sty-page-v1

#4412 Lock to previous cypress release, whilst there are problems with the …
  package.json
Labels: simorgh-core-stream

#4339 Av image metadata
  src/app/containers/MediaPlayer/Metadata.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/helpers/metadata/index.js
  src/app/containers/MediaPlayer/helpers/metadata/index.test.js
Labels: articles-av-epic, articles-features-stream

#4420 Remove redundant 'placeholder' prop and tests from Media Player
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/fixtureData.jsx
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/models/propTypes/index.js
Labels: articles-av-epic, articles-features-stream, ws-media-asset-page-v1, ws-media-stream

#4419 Fix prop type errors on MAP
  data/pidgin/cpsAssets/23248703.json
  package-lock.json
  package.json
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.test.js
Labels: ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4425 Bump rich-text-tranforms@1.1.1 to fix client side XML parsing bug
  package-lock.json
  package.json
Labels: ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4422 Fix failing media player caption tests
  cypress/integration/pages/articles/tests.js
Labels: articles-av-epic, articles-features-stream

#4404 Add iframe title attributes
  package-lock.json
  package.json
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/index.test.jsx
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-media-stream

#4370 Update ATI destination and tests for /scotland
  cypress/integration/pages/testsForAllAMPPages.js
  cypress/integration/pages/testsForAllCanonicalPages.js
  cypress/support/config/envs.js
  src/app/contexts/RequestContext/getStatsDestination/index.js
  src/app/contexts/RequestContext/getStatsDestination/index.test.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
Labels: articles-features-stream, articles-rollout

#4367 Storybook - Add all services to Moment Locales
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/zhongwen.js
  src/app/lib/utilities/moment/index.stories.jsx
Labels: ws-frontpage-stream

#4409 Update Russian and Kyrgyx fixtures
  data/kyrgyz/articles/c3xd4xg3rm9o.json
  data/russian/articles/ck7pz7re3zgo.json
  data/russian/frontpage/index.json
Labels: articles-features-stream, articles-rollout

#4385 Fix for "Console warning on latest: <html> cannot appear as a child of <div>"
  package-lock.json
  package.json
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.test.jsx
Labels: simorgh-core-stream

#4426 Mundo + Brasil translations
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/portuguese.js
Labels: articles-features-stream, articles-rollout, shared-components, ws-frontpage-stream

#4368 Add scripts to debug prod builds locally
  package.json
Labels: bug, investigation, simorgh-core-stream

#4459 Add console logs to debug cypress
  cypress/plugins/index.js
Labels: simorgh-core-stream

#4416 Bump psammead packages to latest
  package-lock.json
  package.json
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
Labels: articles-features-stream, articles-rollout, ws-frontpage-stream

#4454 Update Live Radio grid to match articles Grid
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/index.jsx
Labels: ws-media-stream

#4465 bump deps
  package-lock.json
  package.json
Labels: shared-components, simorgh-core-stream

#4468 Update dependencies
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#4460 Fix eslint for cypress
  cypress/plugins/index.js
Labels: simorgh-core-stream

#4358 fix: react-router-dom bump
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/App/App.jsx
  src/app/containers/App/index.test.jsx
Labels: simorgh-core-stream

#4464 Use updated site wide links
  package-lock.json
  package.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: shared-components

#4382 Russian and Kyrgyz config updates
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/russian.js
Labels: articles-features-stream, articles-rollout

#4470 Add Turkish translations
  src/app/lib/config/services/turkce.js
Labels: articles-features-stream, articles-rollout

#4489 E2E frequency and timeout change
  Jenkinsfile-e2e
  Jenkinsfile-e2e-test
Labels: infra-tooling-stream

#4411 Refactor amp script usage.
  .storybook/helpers/ampDecorator/index.jsx
  src/server/Document/component.jsx
Labels: simorgh-core-stream

#4492 Add live e2es for MBT
  cypress/support/config/services.js
Labels: articles-features-stream, articles-rollout

#4462 Removing duplicate tests
  cypress/integration/pages/testsForAllAMPPages.js
  cypress/integration/pages/testsForAllCanonicalPages.js
  cypress/support/commands/analytics.js
  cypress/support/config/envs.js
Labels: simorgh-core-stream

#4490 Cache cypress requests
  cypress/support/commands/index.js
Labels: simorgh-core-stream

#4453 Fix FIX assets, refactor getInitialData + preprocessorRules
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.test.jsx
  src/app/containers/RadioPageBlocks/index.test.jsx
  src/app/containers/RadioPageMain/index.test.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/lib/utilities/preprocessor/rules/radioPage/addIdsToBlocks.js
  src/app/routes/getInitialData/article/index.js
  src/app/routes/getInitialData/article/index.test.js
  src/app/routes/getInitialData/cpsAsset/index.js
  src/app/routes/getInitialData/cpsAsset/index.test.js
  src/app/routes/getInitialData/frontpage/index.js
  src/app/routes/getInitialData/frontpage/index.test.js
  src/app/routes/getInitialData/index.js
  src/app/routes/getInitialData/index.test.js
  src/app/routes/getInitialData/radioPage/index.js
  src/app/routes/getInitialData/radioPage/index.test.js
  src/app/routes/getInitialData/utils/fetchData/index.test.js
  src/app/routes/getInitialData/utils/getPreprocessorRules/index.js
  src/app/routes/getInitialData/utils/preprocessorRulesConfig/index.js
  src/app/routes/index.js
Labels: simorgh-core-stream, ws-media-stream

#4390 remove inputProvider and dirDecorator
  package-lock.json
  package.json
  src/app/containers/ArticleFigure/index.stories.jsx
  src/app/containers/Brand/index.stories.jsx
  src/app/containers/Copyright/index.stories.jsx
  src/app/containers/Footer/index.stories.jsx
  src/app/containers/Header/index.stories.jsx
  src/app/containers/MediaPlayer/index.stories.jsx
  src/app/containers/RadioPage/index.stories.jsx
  src/app/containers/RadioPageMain/index.stories.jsx
Labels: simorgh-core-stream

#4504 Revert "Cache cypress requests"
  cypress/support/commands/index.js
Labels: simorgh-core-stream
