Repository bbc/simorgh, pull requests merged in 2019-03, with the labels that each got.

#1365 Bump assets-webpack-plugin to avoid snyk vulnerability
  package-lock.json
  package.json
Labels: high priority, mergeable

#1355 Removing CSS tests from Cypress
  cypress/integration/footerSpec.js
  cypress/integration/headerSpec.js
  cypress/integration/newsBodySpec.js
  cypress/support/bodyTestHelper.js
Labels: integration-testing

#1360 Fix Error page view port
  src/app/containers/ErrorMain/index.jsx
Labels: mergeable, v1.0

#1363 Clean up missed console logs
  src/app/helpers/tests/loggerMock.js
  src/app/routes/getInitialData/index.js
  src/app/routes/getInitialData/index.test.js
  src/server/index.jsx
Labels: mergeable, v1.0

#1358 Making the Error Page Cypress tests more dynamic
  cypress/integration/errorPageNews.js
  cypress/integration/errorPagePersian.js
  cypress/support/bodyTestHelper.js
Labels: mergeable

#1366 Use correct data url on client
  src/app/routes/getInitialData/getBaseUrl.js
  src/app/routes/getInitialData/getBaseUrl.test.js
  src/app/routes/getInitialData/index.js
  src/app/routes/getInitialData/index.test.js
Labels: mergeable, v1.0

#1377 Adding Cypress tests for AMP metadata
  cypress/integration/metaNewsSpec.js
  cypress/integration/metaPersianSpec.js
  cypress/support/metaTestHelper.js
Labels: integration-testing

#1376 Change article wrapper widths
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorPage/index.jsx
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/index.jsx
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/index.jsx
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/index.jsx
  src/app/lib/layoutGrid.js
  src/app/lib/styledGrid.js
Labels: high priority

#1367 Heading fragment support
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/index.jsx
  src/app/containers/Headings/index.test.jsx
Labels: v1.0

#1393 Add manual testing doc with information about special characters
  docs/Manual-Testing.md
Labels: Documentation

#1390 Add grid fallback, primarily for IE 9, 10 & 11
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/lib/layoutGrid.js
Labels: v1.0

#1394 Bump Psammead components and use new fontface
  data/README.md
  data/test/news/articles/c0000000009o.json
  package-lock.json
  package.json
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorPage/index.jsx
  src/app/components/Timestamp/__snapshots__/index.test.jsx.snap
  src/app/components/Timestamp/index.jsx
  src/app/containers/Brand/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/Copyright/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineLink/__snapshots__/index.test.jsx.snap
  src/app/containers/Timestamp/__snapshots__/index.test.jsx.snap
  src/app/lib/__snapshots__/globalStyles.test.js.snap
  src/app/lib/globalStyles.js
Labels: high priority, v1.0

#1405 Add consent banner component
  src/app/components/ConsentBanner/__snapshots__/index.test.jsx.snap
  src/app/components/ConsentBanner/index.jsx
  src/app/components/ConsentBanner/index.stories.jsx
  src/app/components/ConsentBanner/index.test.jsx
Labels: Goal (11th - 15th), v1.0

#1412 Bump package lock and pin lighthouse-ci@1.3.1
  package-lock.json
  package.json
  src/app/lib/__snapshots__/globalStyles.test.js.snap
Labels: bug, high priority

#1424 Use live ares data on live
  envConfig/live.env
Labels: high priority, v1.0

#1425 Lock Cypress version to fix CI
  package.json
Labels: high priority

#1422 Add Canonical Consent Banner Logic
  package-lock.json
  package.json
  src/app/containers/ConsentBanner/CanonicalLogic/README.md
  src/app/containers/ConsentBanner/CanonicalLogic/cookieOvenUrl.js
  src/app/containers/ConsentBanner/CanonicalLogic/cookieOvenUrl.test.js
  src/app/containers/ConsentBanner/CanonicalLogic/index.js
  src/app/containers/ConsentBanner/CanonicalLogic/index.test.js
  src/app/containers/ConsentBanner/CanonicalLogic/setCookieOven.js
  src/app/containers/ConsentBanner/CanonicalLogic/setCookieOven.test.js
Labels: last week's goal

#1417 Update fixture data
  data/prod/news/articles/c85pqyj5m2ko.json
  data/prod/news/articles/c9rpqy7pmypo.json
  data/test/news/articles/c85pqyj5m2ko.json
  data/test/news/articles/c9rpqy7pmypo.json
  package.json
Labels: v1.0

#1437 Fix cypress tests on live
  cypress/integration/errorPagePersian.js
  cypress/integration/metaNewsSpec.js
  cypress/integration/metaPersianSpec.js
  cypress/integration/persianBodySpec.js
  cypress/integration/routingSpec.js
  cypress/support/skipLiveDescribe.js
  cypress/support/testData/services.js
Labels: high priority

#1428 Consent container banner
  cypress.json
  cypress/integration/cookieBanner.js
  cypress/support/bodyTestHelper.js
  cypress/support/metaTestHelper.js
  src/app/containers/Article/__snapshots__/index.test.jsx.snap
  src/app/containers/Article/index.jsx
  src/app/containers/ConsentBanner/Banner/Text.jsx
  src/app/containers/ConsentBanner/Banner/Text.test.jsx
  src/app/containers/ConsentBanner/Banner/__snapshots__/Text.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/index.jsx
  src/app/containers/ConsentBanner/Banner/index.test.jsx
  src/app/containers/ConsentBanner/__snapshots__/index.test.jsx.snap
  src/app/containers/ConsentBanner/index.canonical.jsx
  src/app/containers/ConsentBanner/index.canonical.test.jsx
  src/app/containers/ConsentBanner/index.jsx
  src/app/containers/ConsentBanner/index.test.jsx
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
  src/server/index.jsx
Labels: high priority

#1463 Resolve moderate vulnerabilities
  package-lock.json
  package.json
Labels: high priority

#1472 Move enzyme to dev-deps and add eslint disables
  package-lock.json
  package.json
  src/app/helpers/tests/jest-setup.js
Labels: v1.0

#1477 Expand platform context to have TLD and ORIGIN
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/App/index.jsx
  src/app/containers/Article/__snapshots__/index.test.jsx.snap
  src/app/containers/Article/index.jsx
  src/app/containers/Article/index.test.jsx
  src/app/containers/ConsentBanner/index.jsx
  src/app/containers/ConsentBanner/index.test.jsx
  src/app/containers/Figure/fixtureData.jsx
  src/app/containers/Figure/index.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/contexts/PlatformContext/__snapshots__/index.test.jsx.snap
  src/app/contexts/PlatformContext/index.jsx
  src/app/contexts/PlatformContext/index.test.jsx
  src/app/contexts/RequestContext/__snapshots__/index.test.jsx.snap
  src/app/contexts/RequestContext/getOriginContext.js
  src/app/contexts/RequestContext/getOriginContext.test.js
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
  src/app/helpers/tests/setLocationOrigin.js
  src/app/routes/getInitialData/index.test.js
  src/server/Document/index.jsx
  src/server/index.jsx
Labels: mergable, must, v1.0

#1481 Fix duplicate timestamp bug
  src/app/containers/Timestamp/index.jsx
Labels: high priority, must, v1.0

#1488 Update "Using environment builds locally"
  README.md
Labels: Documentation

#1420 Updates tests to point to Mozart
  cypress/integration/errorPagePersian.js
  cypress/integration/metaPersianSpec.js
  cypress/integration/persianBodySpec.js
  cypress/integration/statusSpec.js
  cypress/support/config.js
  cypress/support/describeForLocalOnly.js
  cypress/support/metaTestHelper.js
Labels: v1.0

#1480 Remove uglifyjs plugin
  package-lock.json
  package.json
Labels: bug, v1.0

#1499 Cookie banner messaging
  src/app/containers/ConsentBanner/Banner/Text.jsx
  src/app/containers/ConsentBanner/Banner/Text.test.jsx
  src/app/containers/ConsentBanner/Banner/__snapshots__/Text.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
Labels: must, v1.0

#1468 Polyfill IE11 IE10 and drop IE9 bundle support
  package-lock.json
  package.json
  src/app/components/IfAboveIE9Comment/__snapshots__/index.test.jsx.snap
  src/app/components/IfAboveIE9Comment/index.jsx
  src/app/components/IfAboveIE9Comment/index.test.jsx
  src/poly.js
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.jsx
  webpack.config.client.js
Labels: v1.0
