Repository bbc/simorgh, pull requests merged in 2019-09, with the labels that each got.

#2902 Properly handling error pages
  src/app/containers/Error/__snapshots__/index.test.jsx.snap
  src/app/containers/Error/index.jsx
  src/app/containers/Error/index.test.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/routes/getInitialData/utils/__snapshots__/getRouteProps.test.js.snap
  src/app/routes/getInitialData/utils/fetchData/index.js
  src/app/routes/getInitialData/utils/fetchData/index.test.js
  src/app/routes/getInitialData/utils/getBaseUrl/index.js
  src/app/routes/getInitialData/utils/getBaseUrl/index.test.js
  src/app/routes/getInitialData/utils/getRouteProps.js
  src/app/routes/getInitialData/utils/getRouteProps.test.js
  src/app/routes/getInitialData/utils/getRouteProps/index.js
  src/app/routes/getInitialData/utils/getRouteProps/index.test.js
  src/app/routes/getInitialData/utils/getRouteProps/routeFallbackParams/index.js
  src/app/routes/getInitialData/utils/getRouteProps/routeFallbackParams/index.test.js
  src/app/routes/index.js
  src/app/routes/index.test.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: simorgh-core-stream

#3459 Fixed react warning in FrontPageMain
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.test.jsx
Labels: bug, simorgh-core-stream

#3463 Add Amharic translations for 500 and 404 pages
  src/app/lib/config/services/amharic.js
Labels: ws-media-stream

#3339 Revert "Revert "Add missing ati destinations and logic""
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  cypress/integration/pages/frontPage/testsForAMPOnly.js
  cypress/integration/pages/frontPage/testsForCanonicalOnly.js
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/testsForCanonicalOnly.js
  cypress/integration/pages/testsForAllAMPPages.js
  cypress/integration/pages/testsForAllCanonicalPages.js
  cypress/support/config/envs.js
  cypress/support/config/services.js
  scripts/bundleSize.js
  scripts/bundleSize.test.js
  src/app/contexts/RequestContext/getStatsDestination/index.js
  src/app/contexts/RequestContext/getStatsDestination/index.test.js
  src/app/lib/analyticsUtils/index.js
Labels: articles-current-epic, articles-features-stream, high priority, ws-media- LiveRadioV1

#3307 Call mPulse bundle using UserContext
  .babelrc.js
  README.md
  dials.json
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  package-lock.json
  package.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/components/MPulseBeacon/__snapshots__/index.test.jsx.snap
  src/app/components/MPulseBeacon/index.jsx
  src/app/components/MPulseBeacon/index.test.jsx
  src/app/containers/App/App.jsx
  src/app/containers/App/index.jsx
  src/app/containers/Article/index.test.jsx
  src/app/containers/ConsentBanner/index.canonical.jsx
  src/app/containers/ConsentBanner/index.canonical.test.jsx
  src/app/containers/FrontPage/index.stories.jsx
  src/app/containers/FrontPage/index.test.jsx
  src/app/containers/MPulseBeacon/boomr.js
  src/app/containers/MPulseBeacon/index.jsx
  src/app/containers/MPulseBeacon/index.test.jsx
  src/app/containers/MediaPage/index.stories.jsx
  src/app/containers/MediaPage/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/PageHandlers/withContexts.jsx
  src/app/containers/PageHandlers/withContexts.test.jsx
  src/app/containers/PageHandlers/withPageWrapper/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withPageWrapper/index.test.jsx
  src/app/contexts/DialContext/__snapshots__/index.test.jsx.snap
  src/app/contexts/DialContext/index.jsx
  src/app/contexts/DialContext/index.test.jsx
  src/app/contexts/UserContext/cookies/index.js
  src/app/contexts/UserContext/cookies/index.test.js
  src/app/contexts/UserContext/index.jsx
  src/app/contexts/UserContext/index.test.jsx
  src/app/models/propTypes/data/index.js
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.jsx
  src/server/Document/component.test.jsx
  src/server/Document/index.jsx
  src/server/getDials/index.js
  src/server/getDials/index.test.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: high priority, simorgh-core-stream

#3379 Media page get data from Ares and stop serving fixture data
  scripts/jenkinsProductionFiles.sh
  src/app/routes/getInitialData/mediapage/index.js
  src/app/routes/getInitialData/mediapage/index.test.js
  src/server/index.jsx
Labels: ws-media- LiveRadioV1, ws-media-stream

#3518 Enable mPulse on TEST
  envConfig/local.env
  envConfig/test.env
  src/app/contexts/ToggleContext/__snapshots__/index.test.jsx.snap
  src/app/contexts/ToggleContext/index.test.jsx
  src/app/lib/config/toggles/index.js
Labels: simorgh-core-stream

#3318 Add webpack directory aliasing (config changes)
  .eslintrc.js
  jest.config.js
  package-lock.json
  package.json
  webpack.config.js
Labels: simorgh-core-stream

#3306 Fixed react warnings.
  src/app/containers/InlineContainer/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineContainer/index.jsx
  src/app/containers/InlineContainer/index.test.jsx
Labels: bug, simorgh-core-stream

#3523 Add boomr config
  src/app/containers/MPulseBeacon/boomr.js
Labels: simorgh-core-stream

#3525 Replace react warnings with errors
  src/testHelpers/setupTests.js
Labels: Heracles, simorgh-core-stream

#3471 refactor a test to not do a get request of itself
  cypress/integration/pages/articles/tests.js
Labels: simorgh-core-stream

#3445 Further distill the scripts
  .stylelintrc
  README.md
  package.json
  scripts/killApp.sh
Labels: simorgh-core-stream

#3537 Cypress tests for unknown routes
  cypress/integration/application/index.js
Labels: Iolaus, simorgh-core-stream

#3544 Add punjabi image assets
  public/punjabi/images/icons/icon-128x128.png
  public/punjabi/images/icons/icon-144x144.png
  public/punjabi/images/icons/icon-152x152.png
  public/punjabi/images/icons/icon-192x192.png
  public/punjabi/images/icons/icon-384x384.png
  public/punjabi/images/icons/icon-512x512.png
  public/punjabi/images/icons/icon-72x72.png
  public/punjabi/images/icons/icon-96x96.png
Labels: simorgh-core-stream, ws-frontpage-stream

#3545 Add Navigation translations for Punjabi
  src/app/lib/config/services/punjabi.js
Labels: high priority, simorgh-core-stream, ws-fp-phase2, ws-frontpage-stream

#3547 Remove toLowerCase that isnt needed
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/zhongwen.js
Labels: simorgh-core-stream

#3507 add /articles to AV embed URL
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/helpers/embedUrl.js
  src/app/containers/MediaPlayer/helpers/embedUrl.test.js
Labels: articles-av-epic, articles-features-stream

#3546 Cookie banner translations for Punjabi
  src/app/lib/config/services/punjabi.js
Labels: high priority, simorgh-core-stream, ws-fp-phase2, ws-frontpage-stream

#3457 New translations
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: articles-features-stream, shared-components, ws-frontpage-stream, ws-media-stream

#3444 Test DX improvements
  .gitignore
  cypress.json
  cypress/integration/123PlaygroundForTests/README.md
  cypress/integration/123PlaygroundForTests/index.js
  cypress/integration/123PlaygroundForTests/tests.js
  cypress/integration/123PlaygroundForTests/testsForAMPOnly.js
  cypress/integration/123PlaygroundForTests/testsForCanonicalOnly.js
  cypress/integration/README.md
Labels: integration-testing, simorgh-core-stream

#3456 Adding Cypress tests for Info Alsos in frontPage.js
  cypress/integration/pages/frontPage/tests.js
Labels: integration-testing, ws-frontpage-stream

#3550 Hide cookie banner when ckns_explicit = 2
  src/app/containers/ConsentBanner/CanonicalLogic/index.js
  src/app/containers/ConsentBanner/CanonicalLogic/index.test.js
Labels: Heracles, high priority, shared-components, simorgh-core-stream

#3558 Enable mpulse on live
  envConfig/live.env
  src/app/lib/config/toggles/index.js
Labels: simorgh-core-stream

#3549 Bump psammead packages
  package-lock.json
  package.json
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
Labels: Heracles, simorgh-core-stream, ws-frontpage-stream

#3543 Adds translated labels and links to Punjabi footer
  src/app/lib/config/services/punjabi.js
Labels: simorgh-core-stream, ws-fp-phase2

#3580 Switch to mobile view port when checking for a story promo
  cypress/integration/pages/frontPage/tests.js
Labels: simorgh-core-stream

#3589 delete travis slack integration
  .travis.yml
Labels: infra-tooling-stream

#3591 Top story desktop and mobile test.
  cypress/integration/pages/frontPage/tests.js
Labels: ws-frontpage-stream

#3583 Missing icons for arabic urdu pashto
  public/arabic/images/icons/icon-128x128.png
  public/arabic/images/icons/icon-144x144.png
  public/arabic/images/icons/icon-152x152.png
  public/arabic/images/icons/icon-192x192.png
  public/arabic/images/icons/icon-384x384.png
  public/arabic/images/icons/icon-512x512.png
  public/arabic/images/icons/icon-72x72.png
  public/arabic/images/icons/icon-96x96.png
  public/pashto/images/icons/icon-128x128.png
  public/pashto/images/icons/icon-144x144.png
  public/pashto/images/icons/icon-152x152.png
  public/pashto/images/icons/icon-192x192.png
  public/pashto/images/icons/icon-384x384.png
  public/pashto/images/icons/icon-512x512.png
  public/pashto/images/icons/icon-72x72.png
  public/pashto/images/icons/icon-96x96.png
  public/urdu/images/icons/icon-128x128.png
  public/urdu/images/icons/icon-144x144.png
  public/urdu/images/icons/icon-152x152.png
  public/urdu/images/icons/icon-192x192.png
  public/urdu/images/icons/icon-384x384.png
  public/urdu/images/icons/icon-512x512.png
  public/urdu/images/icons/icon-72x72.png
  public/urdu/images/icons/icon-96x96.png
Labels: articles-current-epic, articles-features-stream

#3599 Add missing link
  src/app/lib/config/services/punjabi.js
Labels: simorgh-core-stream

#3602 Story Promo List bump
  package-lock.json
  package.json
Labels: high priority, ws-frontpage-stream

#3596 Bumped @bbc/psammead packages
  package-lock.json
  package.json
Labels: simorgh-core-stream

#3600 Bumped non-BBC packages
  package-lock.json
  package.json
Labels: simorgh-core-stream

#3514 Add audio player to the live radio page
  cypress/integration/pages/liveRadio/tests.js
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/testsForCanonicalOnly.js
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/MediaPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageMain/index.jsx
  src/app/containers/MediaPageMain/index.test.jsx
  src/app/routes/getInitialData/mediapage/addIdsToBlocks.js
  src/app/routes/getInitialData/mediapage/index.js
  src/app/routes/getInitialData/mediapage/index.test.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#3615 Bump psammead-locales for Punjabi updated locale
  package-lock.json
  package.json
  src/app/lib/config/services/punjabi.js
Labels: ws-frontpage-stream

#3610 Bump storybook helper
  package-lock.json
  package.json
  src/app/containers/ArticleMain/index.stories.jsx
  src/app/containers/Brand/index.stories.jsx
  src/app/containers/Copyright/index.stories.jsx
  src/app/containers/Footer/index.stories.jsx
  src/app/containers/Header/index.stories.jsx
  src/app/containers/MediaPage/index.stories.jsx
  src/app/containers/MediaPageMain/index.stories.jsx
Labels: simorgh-core-stream

#3584 Temp disable index also test, until we have a less frgile soloution
  cypress/integration/pages/frontPage/tests.js
Labels: simorgh-core-stream

#3618 version bump for psammead-locales
  package-lock.json
  package.json
Labels: bug, high priority, ws-frontpage-stream

#3594 Refactor simorgh-e2e notifications into alarms channels
  Jenkinsfile-e2e
  Jenkinsfile-e2e-test
Labels: infra-tooling-stream

#3619 Update Thai metadata.
  src/app/lib/config/services/thai.js
Labels: high priority, ws-frontpage-stream

#3466 Add amp tests to server
  src/server/index.test.jsx
Labels: simorgh-core-stream, ws-frontpage-stream

#3631 Only run assertions on summary if it exists.
  cypress/integration/pages/frontPage/tests.js
Labels: ws-frontpage-stream

#3468 Pass `ar` locale to arabic gregorian timestamps
  cypress/integration/pages/articles/tests.js
  src/app/lib/config/services/arabic.js
Labels: articles-current-epic, articles-features-stream

#3652 Add Related Content to service configs
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/IndexAlsos/index.jsx
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-frontpage-stream

#3562 Testing the presence and formatting of the timestamp on the top story
  cypress/integration/pages/frontPage/tests.js
Labels: integration-testing, ws-frontpage-stream

#3670 Upgrade Node to 10.16.3
  .nvmrc
  Jenkinsfile
  Jenkinsfile-e2e
  Jenkinsfile-e2e-test
Labels: infra-tooling-stream

#3557 Dual timestamps for persian
  cypress/integration/pages/articles/tests.js
  package-lock.json
  package.json
  src/app/lib/config/services/persian.js
Labels: articles-current-epic, articles-features-stream

#3623 Service variants data
  data/serbian/articles/c805k05kr73o/cyr.json
  data/serbian/articles/c805k05kr73o/lat.json
  data/serbian/frontpage/cyr.json
  data/serbian/frontpage/index.json
  data/serbian/frontpage/lat.json
  data/ukchina/articles/c0e8weny66ko/simp.json
  data/ukchina/articles/c0e8weny66ko/trad.json
  data/ukchina/frontpage/index.json
  data/ukchina/frontpage/simp.json
  data/ukchina/frontpage/trad.json
  data/zhongwen/articles/c3xd4x9prgyo/simp.json
  data/zhongwen/articles/c3xd4x9prgyo/trad.json
  data/zhongwen/frontpage/index.json
  data/zhongwen/frontpage/simp.json
  data/zhongwen/frontpage/trad.json
Labels: simorgh-core-stream

#3678 Revert "Testing the presence and formatting of the timestamp on the top story"
  cypress/integration/pages/frontPage/tests.js
Labels: articles-features-stream, ws-frontpage-stream

#3657 Bumped non-BBC packages
  package-lock.json
  package.json
Labels: simorgh-core-stream

#3561 Add Audio contentType to whitelist
  data/pidgin/frontpage/index.json
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withData/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/MediaIndicator/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/MediaIndicator/index.jsx
  src/app/containers/StoryPromo/MediaIndicator/index.test.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/lib/utilities/preprocessor/rules/filterContentType.js
  src/app/lib/utilities/preprocessor/rules/filterContentType.test.js
Labels: ws-frontpage-stream

#3682 Set Punjabi e2e tests to run on LIVE
  cypress/support/config/services.js
Labels: ws-frontpage-stream

#3692 Removing Persian from serviceHasTimestamp config
  cypress/integration/pages/articles/tests.js
Labels: integration-testing

#3688 Add README info about running one Cypress spec
  README.md
Labels: articles-features-stream

#3664 Refactor the metadata tests
  src/app/containers/Metadata/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/index.test.jsx
Labels: simorgh-core-stream, ws-frontpage-stream, ws-media- LiveRadioV1, ws-media-stream

#3656 Bumped @bbc/psammead packages
  package-lock.json
  package.json
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
Labels: simorgh-core-stream

#3604 Bump everything else, except storybook-helpers
  package-lock.json
  package.json
Labels: high priority, simorgh-core-stream

#3360 Update README for non-eu cypress runs
  README.md
Labels: simorgh-core-stream

#3676 Build routing for Media Asset Pages
  data/igbo/mediaAssetPage/media-42986440.json
  data/pidgin/mediaAssetPage/tori-49450859.json
  data/punjabi/mediaAssetPage/international-49567825.json
  data/thai/mediaAssetPage/international-49514085.json
  data/yoruba/mediaAssetPage/media-42985961.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
  dataValidator/helpers/dataLoader/readScenario.js
  src/app/routes/regex/index.js
  src/app/routes/regex/index.test.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: ws-media-stream

#3695 Updating story promo and snapshot
  package-lock.json
  package.json
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
Labels: high priority, ws-frontpage-stream

#3704 Fix broken summary test
  cypress/integration/pages/frontPage/tests.js
Labels: simorgh-core-stream, ws-frontpage-stream

#3703 Fix offscreen text for Brand for azeri, japanese, kyrgyz, punjabi and thai
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/thai.js
Labels: bug, high priority, shared-components, ws-fp-phase2, ws-frontpage-stream

#3601 Add Video contentType to whitelist
  data/pidgin/frontpage/index.json
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withData/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/MediaIndicator/index.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/lib/utilities/preprocessor/rules/filterContentType.js
  src/app/lib/utilities/preprocessor/rules/filterContentType.test.js
Labels: ws-frontpage-stream

#3552 Dual calendar for Pashto locale
  src/app/lib/config/services/pashto.js
Labels: articles-current-epic, articles-features-stream

#3708 Remove test helpers (small changes)
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorPage/index.test.jsx
  src/app/components/IfAboveIE9Comment/__snapshots__/index.test.jsx.snap
  src/app/components/IfAboveIE9Comment/index.test.jsx
  src/app/components/InlineSpan/__snapshots__/index.test.jsx.snap
  src/app/components/InlineSpan/index.test.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/Article/index.test.jsx
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/index.test.jsx
  src/app/containers/InlineContainer/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineContainer/index.test.jsx
  src/app/containers/MediaPage/index.test.jsx
  src/app/contexts/RequestContext/getOriginContext/index.test.js
  src/app/contexts/ToggleContext/index.test.jsx
  src/app/lib/analyticsUtils/index.test.js
  src/app/lib/styledGrid/__snapshots__/index.test.jsx.snap
  src/app/lib/styledGrid/index.test.jsx
  src/app/lib/utilities/onClient/index.test.js
Labels: Heracles, simorgh-core-stream

#3681 Integrating MAP routing (amp and canonical) with Cypress tests
  cypress/integration/pages/mediaAssetPage/index.js
  cypress/integration/pages/mediaAssetPage/tests.js
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  cypress/support/config/services.js
  src/app/routes/getInitialData/mediaAssetPage/index.js
  src/app/routes/getInitialData/mediaAssetPage/index.test.js
  src/app/routes/index.js
  src/app/routes/regex/index.test.js
Labels: ws-media-stream

#3595 Feature content type
  data/pidgin/frontpage/index.json
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withData/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/lib/utilities/preprocessor/rules/filterContentType.js
  src/app/lib/utilities/preprocessor/rules/filterContentType.test.js
Labels: ws-frontpage-stream

#3716 Make the CPSindex optional for MAP routing
  data/ukchina/mediaAssetPage/49375846.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
  src/app/routes/regex/index.js
  src/app/routes/regex/index.test.js
Labels: ws-media-stream

#3693 Add Grid example to Storybook
  src/app/containers/ArticleMain/index.stories.jsx
  src/app/containers/FrontPage/index.stories.jsx
  src/app/containers/FrontPageMain/index.stories.jsx
Labels: grid, shared-components, ws-frontpage-stream

#3774 Adding tigrinya translations
  src/app/lib/config/services/tigrinya.js
Labels: ws-media-stream

#3802 Mv and fix broken e2e tests
  .travis.yml
  3rdPartyCypress/cypress/integration/errorPageNews.js
  Jenkinsfile-e2e-test
  Makefile
Labels: simorgh-core-stream

#3776 Remove test helpers (small changes #2)
  src/app/components/Metadata/helpers/__snapshots__/iconLinks.test.js.snap
  src/app/components/Metadata/helpers/iconLinks.test.js
  src/app/components/ResourceHints/__snapshots__/index.test.jsx.snap
  src/app/components/ResourceHints/index.test.jsx
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/index.test.jsx
  src/app/containers/PageHandlers/withError/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withError/index.test.jsx
  src/app/containers/PageHandlers/withPageWrapper/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withPageWrapper/index.test.jsx
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/index.test.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.test.jsx
Labels: Heracles, simorgh-core-stream

#3814 Remove test helpers (small changes #3)
  src/app/containers/ArticleTimestamp/index.test.jsx
  src/app/containers/Brand/__snapshots__/index.test.jsx.snap
  src/app/containers/Brand/index.test.jsx
  src/app/containers/ConsentBanner/Banner/Text.test.jsx
  src/app/containers/ConsentBanner/Banner/__snapshots__/Text.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/index.amp.test.jsx
  src/app/containers/ConsentBanner/Banner/index.canonical.test.jsx
  src/app/containers/ConsentBanner/index.test.jsx
  src/app/containers/Copyright/__snapshots__/index.test.jsx.snap
  src/app/containers/Copyright/index.test.jsx
  src/app/containers/Error/index.test.jsx
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/index.test.jsx
  src/app/containers/Fragment/__snapshots__/index.test.jsx.snap
  src/app/containers/Fragment/index.test.jsx
  src/app/containers/FrontPage/index.test.jsx
  src/app/containers/InlineLink/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineLink/index.test.jsx
Labels: Heracles, simorgh-core-stream

#3824 Write NFRs and combine with code standards
  docs/Code-Standards.md
Labels: simorgh-core-stream

#3832 Lightweight readmes for simorgh
  .github/CODE_OF_CONDUCT.md
  3rdPartyCypress/README.md
  CONTRIBUTING.md
  README.md
  cypress/README.md
  cypress/integration/README.md
  cypress/support/helpers/README.md
  dataValidator/README.md
  docs/Code-Standards.md
  docs/Project-Board-Guide.md
  puppeteer/README.md
  src/README.md
  src/app/components/README.md
  src/app/containers/README.md
  src/testHelpers/README.md
Labels: simorgh-core-stream

#3711 Remove test helpers (major changes)
  .babelrc.js
  package-lock.json
  package.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.test.jsx
  src/app/components/LinkedData/__snapshots__/index.test.jsx.snap
  src/app/components/LinkedData/index.test.jsx
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.test.jsx
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
Labels: Heracles, simorgh-core-stream

#3683 Disable mPulse beacon on local
  cypress/support/config/envs.js
  src/app/containers/ChartbeatAnalytics/__snapshots__/index.test.jsx.snap
  src/app/containers/ChartbeatAnalytics/index.test.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/Toggle/useToggle.jsx
  src/app/lib/config/toggles/index.js
Labels: simorgh-core-stream

#3780 mPulse - Set service and pagetype to window
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/article/index.test.jsx
  src/app/containers/ATIAnalytics/params/frontpage/index.test.jsx
  src/app/containers/ATIAnalytics/params/media/index.test.jsx
  src/app/containers/Article/index.test.jsx
  src/app/containers/ArticleFigure/fixtureData.jsx
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMain/index.test.jsx
  src/app/containers/ChartbeatAnalytics/index.test.jsx
  src/app/containers/ConsentBanner/Banner/Text.test.jsx
  src/app/containers/ConsentBanner/index.test.jsx
  src/app/containers/FrontPage/index.test.jsx
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.test.jsx
  src/app/containers/Header/index.test.jsx
  src/app/containers/ImageWithPlaceholder/fixtureData.jsx
  src/app/containers/MPulseBeacon/index.jsx
  src/app/containers/MPulseBeacon/index.test.jsx
  src/app/containers/MediaPage/index.test.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/PageHandlers/withContexts.jsx
  src/app/containers/PageHandlers/withContexts.test.jsx
  src/app/containers/PageHandlers/withPageWrapper/index.test.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
Labels: simorgh-core-stream

#3727 Add /scotland service
  cypress/integration/pages/testsForAllAMPPages.js
  cypress/integration/pages/testsForAllCanonicalPages.js
  cypress/support/config/envs.js
  cypress/support/config/services.js
  data/scotland/articles/czwj5l0n210o.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
  package-lock.json
  package.json
  public/scotland/manifest.json
  src/app/contexts/RequestContext/getStatsDestination/index.js
  src/app/contexts/RequestContext/getStatsDestination/index.test.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
  src/app/lib/config/services/index.js
  src/app/lib/config/services/loadableConfig.js
  src/app/lib/config/services/scotland.js
Labels: articles-features-stream, articles-next-epic, low priority

#3831 Make audio player height static
  package-lock.json
  package.json
  src/app/containers/MediaPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageMain/index.jsx
Labels: ws-media- LiveRadioV1, ws-media-stream

#3852 Correct broken link
  docs/Project-Board-Guide.md
Labels: Heracles, simorgh-core-stream

#2817 Add redirect tests as per spec
  3rdPartyCypress/cypress/integration/worldServiceCoUkRedirect.js
Labels: articles-features-stream, simorgh-core-stream

#3860 Allow dirAlias.js to be used on jenkins
  scripts/jenkinsProductionFiles.sh
Labels: high priority, simorgh-core-stream

#3861 The scotland service has just been added to simorgh but it should not…
  3rdPartyCypress/cypress/integration/worldServiceCoUkRedirect.js
Labels: simorgh-core-stream

#3775 Media Asset Page variant support
  cypress/support/config/services.js
  data/serbian/mediaAssetPage/srbija-49427344.json
  data/serbian/mediaAssetPage/srbija-49427344/cyr.json
  data/serbian/mediaAssetPage/srbija-49427344/lat.json
  data/ukchina/mediaAssetPage/49375846.json
  data/ukchina/mediaAssetPage/49375846/simp.json
  data/ukchina/mediaAssetPage/49375846/trad.json
  data/zhongwen/mediaAssetPage/chinese-news-49631219.json
  data/zhongwen/mediaAssetPage/chinese-news-49631219/simp.json
  data/zhongwen/mediaAssetPage/chinese-news-49631219/trad.json
  src/app/routes/getInitialData/mediaAssetPage/index.js
  src/app/routes/getInitialData/mediaAssetPage/index.test.js
  src/app/routes/regex/index.js
  src/app/routes/regex/index.test.js
  src/server/assets/fixture.json
  src/server/index.jsx
  src/server/index.test.jsx
Labels: simorgh-core-stream, ws-media-stream

#3857 Fix application unknown routes test failures on local
  cypress/integration/application/index.js
Labels: articles-features-stream, simorgh-core-stream

#3835 Fixes tigrinya and Amharic translations
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/tigrinya.js
Labels: ws-media-stream

#3833 Remove react helmet mock from metadata container
  src/app/containers/Metadata/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/index.test.jsx
Labels: simorgh-core-stream, ws-media-stream

#3847 Update relevant service config timezones to default to GMT
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/zhongwen.js
Labels: articles-current-epic, articles-features-stream

#3864 render readable snapshots for article main
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMain/index.test.jsx
Labels: simorgh-core-stream

#3808 Navigation direction prop
  package-lock.json
  src/app/containers/Navigation/index.jsx
  src/app/containers/Navigation/index.stories.jsx
Labels: ws-frontpage-stream

#3870 (quick fix) Fix client side navigation
  src/app/containers/PageHandlers/withContexts.jsx
Labels: high priority, simorgh-core-stream

#3742 Use global styles from psammead
  .storybook/config.js
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/Layouts/defaultPageWrapper.test.jsx
  src/app/lib/globalStyles/__snapshots__/index.test.jsx.snap
  src/app/lib/globalStyles/index.jsx
  src/app/lib/globalStyles/index.test.jsx
Labels: shared-components

#3836 add MAP URLs to local cypress non-smoke tests
  cypress/support/config/services.js
Labels: ws-media-stream

#3862 Report CC test coverage when running against latest branch
  Jenkinsfile
Labels: simorgh-core-stream

#3840 Move test service config
  3rdPartyCypress/cypress/integration/worldServiceCoUkRedirect.js
  cypress/integration/application/index.js
  cypress/integration/pages/articles/tests.js
  cypress/integration/pages/errorPage404/tests.js
  cypress/integration/pages/testsForAllPages.js
  cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
  cypress/integration/specialFeatures/cookieBanner/testsForCanonicalOnly.js
  src/app/containers/ArticleTimestamp/index.stories.jsx
  src/app/containers/Brand/index.stories.jsx
  src/app/containers/Copyright/index.stories.jsx
  src/app/containers/Footer/index.stories.jsx
  src/app/containers/Header/index.stories.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/Navigation/index.stories.jsx
  src/app/contexts/ServiceContext/__mocks__/index.jsx
  src/app/contexts/ServiceContext/index.test.jsx
  src/app/lib/config/services/index.js
  src/app/lib/utilities/moment/index.stories.jsx
  src/app/routes/regex/index.test.js
  src/testHelpers/serviceConfigs.js
Labels: simorgh-core-stream

#3842 Remove test helpers (major changes #2)
  src/app/containers/ArticleMain/index.test.jsx
  src/app/containers/StoryPromo/LinkContents/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/LinkContents/index.test.jsx
  src/app/containers/Text/__snapshots__/index.test.jsx.snap
  src/app/containers/Text/index.test.jsx
  src/app/containers/Toggle/__snapshots__/index.test.jsx.snap
  src/app/containers/Toggle/index.test.jsx
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.test.jsx
Labels: Heracles, simorgh-core-stream

#3778 add styles to player to fix width to 800px on desktop enabling volume slider
  src/app/containers/MediaPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageMain/index.jsx
Labels: ws-media- LiveRadioV1, ws-media-stream

#3858 Typography script update
  package-lock.json
  package.json
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: articles-features-stream, shared-components, ws-frontpage-stream, ws-media-stream

#3848 Ensure ws-downloads origin is in resource hints
  cypress/integration/pages/testsForAllPages.js
  src/server/assets/index.js
  src/server/assets/index.test.js
  src/server/index.test.jsx
Labels: performance, shared-components, simorgh-core-stream

#3875 Update configs for next 12 articles services
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
Labels: articles-features-stream, articles-next-epic

#3865 Dedupe common AMP script/element tests
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/frontPage/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/testsForAllAMPPages.js
  cypress/integration/pages/testsForAllCanonicalPages.js
Labels: articles-current-epic, articles-features-stream, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#3882 Cypress CI fix
  package.json
Labels: simorgh-core-stream

#3622 Move Canonical Chartbeat to UserContext
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMain/index.test.jsx
  src/app/containers/ChartbeatAnalytics/__snapshots__/index.test.jsx.snap
  src/app/containers/ChartbeatAnalytics/amp/index.jsx
  src/app/containers/ChartbeatAnalytics/amp/index.test.jsx
  src/app/containers/ChartbeatAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ChartbeatAnalytics/canonical/index.jsx
  src/app/containers/ChartbeatAnalytics/index.jsx
  src/app/containers/ChartbeatAnalytics/index.test.jsx
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/containers/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPage/index.test.jsx
  src/app/contexts/UserContext/Chartbeat/index.jsx
  src/app/contexts/UserContext/index.jsx
  src/app/contexts/UserContext/index.test.jsx
  src/app/models/propTypes/chartbeatAnalytics/index.js
Labels: POC, articles-features-stream

#3881 Correct description of default smoke state in README
  README.md
Labels: articles-features-stream, simorgh-core-stream

#3883 Use psammead test helper snapshots for front page and media page
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.test.jsx
  src/app/containers/MediaPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageMain/index.test.jsx
Labels: simorgh-core-stream

#3884 Use BBC Scotland SVG for scotland service pages
  package-lock.json
  package.json
  src/app/lib/config/services/scotland.js
Labels: articles-features-stream, articles-next-13, shared-components

#3821 Update translations for - Tigrinya, Urdu, Vietnamese and Yoruba
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
Labels: articles-features-stream, articles-next-13, ws-frontpage-stream

#3888 Add some nav items for /news
  src/app/lib/config/services/news.js
Labels: articles-features-stream, articles-next-13

#3817 Update translations for - Japanese, Azeri and Kyrgyz
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/kyrgyz.js
Labels: articles-features-stream, articles-next-13, high priority, ws-frontpage-stream

#3880 Fix double counting users
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/atiUrl/index.test.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
Labels: articles-features-stream, simorgh-core-stream

#3866 Add Fixuture data for MAP V1
  data/japanese/mediaAssetPage/video-23248670.json
  data/korean/mediaAssetPage/media-23248686.json
  data/pidgin/mediaAssetPage/23248703.json
  data/punjabi/mediaAssetPage/media-23248705.json
  data/sinhala/mediaAssetPage/23248970.json
  data/thai/mediaAssetPage/thailand-23248713.json
  data/uzbek/mediaAssetPage/sport-23248721.json
Labels: ws-media-asset-page-v1, ws-media-stream

#3892 Add space to cookie banner translation
  src/app/lib/config/services/korean.js
Labels: bug, ws-media-stream

#3738 Refactor MAP container to easily scale to new components
  scripts/bundleSizeConfig.js
  src/app/containers/MediaPageBlocks/Blocks/Heading/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageBlocks/Blocks/Heading/index.jsx
  src/app/containers/MediaPageBlocks/Blocks/Heading/index.test.jsx
  src/app/containers/MediaPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/MediaPageBlocks/Blocks/LiveRadio/index.test.jsx
  src/app/containers/MediaPageBlocks/Blocks/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageBlocks/Blocks/Paragraph/index.jsx
  src/app/containers/MediaPageBlocks/Blocks/Paragraph/index.test.jsx
  src/app/containers/MediaPageBlocks/Blocks/Unknown/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageBlocks/Blocks/Unknown/index.jsx
  src/app/containers/MediaPageBlocks/Blocks/Unknown/index.test.jsx
  src/app/containers/MediaPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageBlocks/index.jsx
  src/app/containers/MediaPageBlocks/index.test.jsx
  src/app/containers/MediaPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageMain/index.jsx
  src/app/containers/MediaPageMain/index.test.jsx
Labels: high priority, simorgh-core-stream, ws-media-stream

#3669 test for render document
  src/server/Document/index.test.jsx
Labels: simorgh-core-stream

#3587 Check for relatedItems before running IndexAlsos test
  cypress/integration/pages/frontPage/tests.js
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/IndexAlsos/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/IndexAlsos/index.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
Labels: ws-frontpage-stream

#3854 Remove test helpers (major changes #3)
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/PageHandlers/withContexts.test.jsx
  src/app/containers/PageHandlers/withData/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withData/index.test.jsx
  src/app/containers/PageHandlers/withLoading/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withLoading/index.test.jsx
  src/app/containers/StoryPromo/IndexAlsos/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/IndexAlsos/index.test.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/ServiceContext/__mocks__/index.jsx
  src/app/contexts/ToggleContext/index.jsx
Labels: Heracles, simorgh-core-stream

#3867 Add icons for /scotland
  public/scotland/images/icons/icon-128x128.png
  public/scotland/images/icons/icon-144x144.png
  public/scotland/images/icons/icon-152x152.png
  public/scotland/images/icons/icon-192x192.png
  public/scotland/images/icons/icon-384x384.png
  public/scotland/images/icons/icon-512x512.png
  public/scotland/images/icons/icon-72x72.png
  public/scotland/images/icons/icon-96x96.png
Labels: articles-features-stream, articles-next-13, low priority

#3841 Update translations - Afaan Oromoo, Afrique, Amharic, Arabic and Gahuza
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/gahuza.js
Labels: articles-features-stream, articles-next-13, shared-components, ws-fp-phase2, ws-frontpage-stream

#3823 Update translations for - Persian, Pidgin, Punjabi, Somali, Swahili and Thai
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/thai.js
Labels: articles-features-stream, articles-next-13, shared-components, ws-fp-phase2, ws-frontpage-stream

#3820 Bumped 3rd Party Dependencies
  package-lock.json
  package.json
Labels: simorgh-core-stream

#3929 Add a scotland poster image to images
  public/scotland/images/og/poster-1024x576.png
  src/app/lib/config/services/scotland.js
Labels: articles-features-stream, articles-next-13

#3830 Update translations for Hausa, Igbo, Indonesia, Korea, Pashto and Japanese services
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/IndexAlsos/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/pashto.js
Labels: articles-features-stream, articles-next-13, high priority, shared-components, ws-fp-phase2, ws-frontpage-stream

#3926 Add moment locales for Japanese, Kyrgyz and Azeri
  package-lock.json
  package.json
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/kyrgyz.js
Labels: high priority, ws-frontpage-stream

#3958 Updates handlebars dependancy due to high security vuln found by npm …
  package-lock.json
Labels: high priority, simorgh-core-stream

#3957 Remove duplicate test that was looking at the incorrect value
  cypress/integration/pages/testsForAllPages.js
Labels: simorgh-core-stream

#3773 fix: add passportHome override map #2574
  data/scotland/articles/czwj5l0n210o.json
  src/app/containers/PageHandlers/withData/index.jsx
  src/app/containers/PageHandlers/withData/index.test.jsx
  src/app/containers/PageHandlers/withData/shouldRender/index.js
  src/app/containers/PageHandlers/withData/shouldRender/index.test.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/scotland.js
  src/app/lib/utilities/getPassportHome/index.js
  src/app/lib/utilities/passport/index.js
  src/app/lib/utilities/passport/index.test.js
Labels: articles-features-stream, articles-next-13, simorgh-core-stream

#3960 Add the GPG doc to simorgh
  CONTRIBUTING.md
  README.md
  docs/Code-Standards.md
  docs/GPG-Signing-Guide.md
Labels: infra-tooling-stream

#3886 Remove test helpers (major changes #4)
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleFigure/index.test.jsx
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/index.test.jsx
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.test.jsx
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/index.test.jsx
  src/app/containers/ImageWithPlaceholder/__snapshots__/index.test.jsx.snap
  src/app/containers/ImageWithPlaceholder/index.test.jsx
  src/app/containers/StoryPromo/MediaIndicator/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/MediaIndicator/index.test.jsx
Labels: Heracles, simorgh-core-stream

#3967 fix: the passportHomesOverride does not matter when checking.
  src/app/lib/utilities/passport/index.js
  src/app/lib/utilities/passport/index.test.js
Labels: simorgh-core-stream

#3975 Disable afaanoromoo liveRadio e2e tests on test
  cypress/support/config/services.js
Labels: simorgh-core-stream, ws-media-stream

#3951 Add tabindex=-1
  cypress/integration/pages/testsForAllPages.js
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorPage/index.jsx
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/index.jsx
  src/app/containers/MediaPageBlocks/Blocks/Heading/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageBlocks/Blocks/Heading/index.jsx
  src/app/containers/MediaPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageMain/__snapshots__/index.test.jsx.snap
Labels: a11y, shared-components

#3974 Improve Mozart fallback error messages in e2es
  3rdPartyCypress/cypress/support/commands.js
  cypress/support/commands/application.js
  cypress/support/commands/index.js
Labels: articles-features-stream, simorgh-core-stream

#3939 Localhost and storybook AV support
  src/app/containers/MediaPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/MediaPageBlocks/Blocks/LiveRadio/index.test.jsx
  src/app/containers/MediaPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageBlocks/index.test.jsx
  src/app/containers/MediaPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageMain/index.stories.jsx
  src/app/containers/MediaPlayer/helpers/embedUrl.js
  src/app/containers/MediaPlayer/helpers/embedUrl.test.js
  src/app/containers/MediaPlayer/index.jsx
Labels: articles-av-epic, articles-features-stream, ws-media- LiveRadioV1, ws-media-stream

#3978 Live e2e tests - Azeri, Kyrgyz and Japanese
  cypress/support/config/services.js
Labels: blocked, high priority, ws-frontpage-stream

#3937 Validate that the new standardised Cypress testing article works for us
  cypress/integration/pages/articles/tests.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  cypress/support/config/services.js
  data/news/articles/cn7k01xp8kxo.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
Labels: articles-current-epic, articles-features-stream

#3873 ignore some storybook on Chromatic
  src/app/containers/ArticleFigure/index.stories.jsx
  src/app/containers/ArticleTimestamp/index.stories.jsx
  src/app/containers/Brand/index.stories.jsx
  src/app/containers/ConsentBanner/index.stories.jsx
  src/app/containers/Copyright/index.stories.jsx
  src/app/containers/Footer/index.stories.jsx
  src/app/containers/FrontPageSection/index.stories.jsx
  src/app/containers/Header/index.stories.jsx
  src/app/containers/Headings/index.stories.jsx
  src/app/containers/Image/index.stories.jsx
  src/app/containers/ImageWithPlaceholder/index.stories.jsx
  src/app/containers/InlineLink/index.stories.jsx
  src/app/containers/MediaPlayer/index.stories.jsx
  src/app/containers/Navigation/index.stories.jsx
  src/app/containers/StoryPromo/index.stories.jsx
Labels: simorgh-core-stream

#3990 Update cypress test for liveradio
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/testsForCanonicalOnly.js
Labels: bug, ws-media- LiveRadioV1, ws-media-stream

#3981 Fix afaanoromoo liveradio test e2e
  src/app/containers/MediaPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/MediaPageBlocks/Blocks/LiveRadio/index.test.jsx
  src/app/lib/config/services/afaanoromoo.js
Labels: bug, ws-media- LiveRadioV1, ws-media-stream

#3995 I forgot on the end of the embed URL
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#3987 Revert "Disable afaanoromoo liveRadio e2e tests on test"
  cypress/support/config/services.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#3994 Add STY fixture
  data/thai/mediaAssetPage/thailand-49659092.json
Labels: simorgh-core-stream

#3955 Add serviceLocalizedName for all services
  cypress/integration/pages/testsForAllPages.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/zhongwen.js
Labels: shared-components, ws-frontpage-stream

#4001 Remap bbc_oromo_radio externalId
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#4003 Fix Cypress E2Es liveradio - try 3
  cypress/integration/pages/liveRadio/helper.js
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/testsForCanonicalOnly.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#4006 Fix 3rd-party errorPage test failing due to config structure change
  3rdPartyCypress/cypress/integration/errorPageNews.js
Labels: simorgh-core-stream

#3954 Front Page section margin
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.jsx
Labels: ux, ws-frontpage-stream

#4005 Readme update so non-smoke tests will run on correct command
  README.md
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream

#3959 Use updated Pashto locale to introduce relative time support
  package-lock.json
  package.json
  src/app/lib/utilities/moment/index.stories.jsx
Labels: articles-current-epic, articles-features-stream
