Repository bbc/simorgh, pull requests merged in 2019-07, with the labels that each got.

#2175 Stop serving fixture data
  scripts/jenkinsProductionFiles.sh
  src/server/index.jsx
Labels: ws-frontpage-stream

#2164 Update contribution doc
  CONTRIBUTING.md
  docs/Project-Board-Guide.md
Labels: Documentation, simorgh-core-stream

#2183 Config consolidation
  cypress/README.md
  cypress/integration/ampSpec.js
  cypress/integration/atiSpec.js
  cypress/integration/cookieBanner.amp.js
  cypress/integration/cookieBanner.canonical.js
  cypress/integration/cookieBannerWS.js
  cypress/integration/dataSpec.js
  cypress/integration/errorPageNews.js
  cypress/integration/errorPagePersian.js
  cypress/integration/footerSpec.js
  cypress/integration/frontpageAmpSpec.js
  cypress/integration/frontpageLayoutSpec.js
  cypress/integration/headerSpec.js
  cypress/integration/metaNewsSpec.js
  cypress/integration/metaPersianSpec.js
  cypress/integration/newsBodySpec.js
  cypress/integration/persianBodySpec.js
  cypress/plugins/index.js
  cypress/support/config/envs.js
  cypress/support/config/services.js
  cypress/support/cookieConfig.js
  cypress/support/worldServices.js
Labels: integration-testing, simorgh-core-stream

#1872 Bundle splitting of service configs (do not merge on friday's)
  .babelrc
  .babelrc.js
  cypress/integration/atiSpec.js
  cypress/integration/frontpageLayoutSpec.js
  cypress/integration/metaNewsSpec.js
  cypress/integration/newsBodySpec.js
  cypress/integration/persianBodySpec.js
  cypress/integration/scriptSpec.js
  package-lock.json
  package.json
  puppeteer/bundleRequests.test.js
  scripts/bundleSize.sh
  src/app/containers/Metadata/index.test.jsx
  src/app/contexts/ServiceContext/__mocks__/index.jsx
  src/app/contexts/ServiceContext/__snapshots__/index.test.jsx.snap
  src/app/contexts/ServiceContext/index.jsx
  src/app/contexts/ServiceContext/index.test.jsx
  src/app/contexts/utils/createLoadableContext.jsx
  src/app/contexts/utils/createLoadableContext.test.jsx
  src/app/contexts/utils/fixtures/fooService.js
  src/app/contexts/utils/fixtures/index.js
  src/app/lib/config/services/default.js
  src/app/lib/config/services/index.js
  src/app/lib/config/services/loadableConfig.js
  src/app/routes/regex/index.js
  src/client.js
  src/client.test.jsx
  src/index.js
  src/poly.js
  src/server/Document/index.jsx
  src/server/assets/fixture.json
  src/server/assets/fixtureMissingKey.json
  src/server/assets/index.js
  src/server/assets/index.test.js
  src/server/index.test.jsx
  src/testHelpers/jest-setup.js
  webpack.config.client.js
  webpack.config.js
  webpack.config.server.js
Labels: articles-features-stream, high priority, simorgh-core-stream, ws-fp-v1, ws-frontpage-stream

#2199 Fix release issue with bundle splitting
  package.json
  scripts/jenkinsProductionFiles.sh
Labels: infra-tooling-stream, simorgh-core-stream, ws-frontpage-stream

#2176 add how to run on specific environment within UK
  cypress/README.md
Labels: Documentation, simorgh-core-stream

#2099 Psammead package bumps
  package-lock.json
  package.json
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
Labels: high priority, simorgh-core-stream, ws-fp-v1, ws-frontpage-stream

#1774 adding amp iframe for video
  src/app/containers/Video/index.jsx
Labels: articles-current-epic, articles-features-stream

#2218 Add Lighthouse, A11y & AMP test for frontpages
  a11y.js
  package.json
Labels: ws-fp-v1, ws-frontpage-stream

#2150 Add remaining meta tags to Metadata component
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/helpers/__snapshots__/iconLinks.test.js.snap
  src/app/components/Metadata/helpers/iconLinks.jsx
  src/app/components/Metadata/helpers/iconLinks.test.js
  src/app/components/Metadata/index.jsx
  src/app/components/Metadata/index.test.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#2208 Pull in media indicator to fix ie hover
  package-lock.json
  package.json
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#2172 Drop offscreen text in the media indicator - it exists elsewhere
  src/app/containers/StoryPromo/MediaIndicator.jsx
  src/app/containers/StoryPromo/__snapshots__/MediaIndicator.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
Labels: a11y, high priority, ws-fp-v1, ws-frontpage-stream

#2209 Use overtyped headline if available
  src/app/containers/StoryPromo/LinkContents.jsx
  src/app/containers/StoryPromo/LinkContents.test.jsx
  src/app/containers/StoryPromo/__snapshots__/LinkContents.test.jsx.snap
Labels: bug, ws-fp-v1, ws-frontpage-stream

#2238 Persian translations update
  data/test/persian/articles/c0000000026o.json
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineLink/__snapshots__/index.test.jsx.snap
  src/app/containers/Video/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/index.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
Labels: articles-features-stream, articles-next-epic

#2204 Bundle splitting of service configs
  .babelrc
  .babelrc.js
  cypress/integration/atiSpec.js
  cypress/integration/frontpageLayoutSpec.js
  cypress/integration/metaNewsSpec.js
  cypress/integration/newsBodySpec.js
  cypress/integration/persianBodySpec.js
  cypress/integration/scriptSpec.js
  package-lock.json
  package.json
  puppeteer/bundleRequests.test.js
  scripts/bundleSize.sh
  scripts/jenkinsProductionFiles.sh
  src/app/containers/Metadata/index.test.jsx
  src/app/contexts/ServiceContext/__mocks__/index.jsx
  src/app/contexts/ServiceContext/__snapshots__/index.test.jsx.snap
  src/app/contexts/ServiceContext/index.jsx
  src/app/contexts/ServiceContext/index.test.jsx
  src/app/contexts/utils/createLoadableContext.jsx
  src/app/contexts/utils/createLoadableContext.test.jsx
  src/app/contexts/utils/fixtures/fooService.js
  src/app/contexts/utils/fixtures/index.js
  src/app/lib/config/services/default.js
  src/app/lib/config/services/index.js
  src/app/lib/config/services/loadableConfig.js
  src/app/routes/regex/index.js
  src/client.js
  src/client.test.jsx
  src/index.js
  src/poly.js
  src/server/Document/index.jsx
  src/server/assets/assetsFilter/index.js
  src/server/assets/assetsFilter/index.test.js
  src/server/assets/fixture.json
  src/server/assets/fixtureMissingKey.json
  src/server/assets/index.js
  src/server/assets/index.test.js
  src/server/index.test.jsx
  src/testHelpers/jest-setup.js
  webpack.config.client.js
  webpack.config.js
  webpack.config.server.js
Labels: simorgh-core-stream, ws-fp-v1, ws-frontpage-stream

#2136 renderDocument() destruct props
  src/server/Document/index.jsx
  src/server/index.jsx
Labels: articles-features-stream, simorgh-core-stream

#2262 Refactor figure into ImageWithPlaceholder & Article Figure
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleFigure/fixtureData.jsx
  src/app/containers/ArticleFigure/index.jsx
  src/app/containers/ArticleFigure/index.stories.jsx
  src/app/containers/ArticleFigure/index.test.jsx
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/index.jsx
  src/app/containers/ImageWithPlaceholder/__snapshots__/index.test.jsx.snap
  src/app/containers/ImageWithPlaceholder/fixtureData.jsx
  src/app/containers/ImageWithPlaceholder/index.jsx
  src/app/containers/ImageWithPlaceholder/index.stories.jsx
  src/app/containers/ImageWithPlaceholder/index.test.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
Labels: articles-features-stream, high priority, ws-fp-v1, ws-frontpage-stream

#2205 update cypress readme
  cypress/README.md
Labels: Documentation, simorgh-core-stream

#2268 Fix dev experience js regex
  src/server/assets/assetsFilter/index.js
  src/server/assets/assetsFilter/index.test.js
Labels: articles-features-stream, high priority, simorgh-core-stream, ws-frontpage-stream

#2265 Add Current page translations
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
Labels: ws-fp-v1, ws-frontpage-stream

#2185 Refactor request context
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/containers/ATIAnalytics/ArticleAtiParams.test.jsx
  src/app/containers/ATIAnalytics/FrontPageAtiParams.test.jsx
  src/app/containers/ATIAnalytics/canonical/index.test.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ArticleFigure/fixtureData.jsx
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMain/index.test.jsx
  src/app/containers/ConsentBanner/Banner/Text.test.jsx
  src/app/containers/ConsentBanner/index.test.jsx
  src/app/containers/FrontPageSection/index.stories.jsx
  src/app/containers/ImageWithPlaceholder/fixtureData.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/containers/Video/__snapshots__/index.test.jsx.snap
  src/app/containers/Video/fixtureData.jsx
  src/app/containers/Video/index.test.jsx
  src/app/contexts/RequestContext/__snapshots__/index.test.jsx.snap
  src/app/contexts/RequestContext/getEnv/index.js
  src/app/contexts/RequestContext/getEnv/index.test.js
  src/app/contexts/RequestContext/getOriginContext/index.js
  src/app/contexts/RequestContext/getOriginContext/index.test.js
  src/app/contexts/RequestContext/getStatsDestination/index.js
  src/app/contexts/RequestContext/getStatsDestination/index.test.js
  src/app/contexts/RequestContext/getStatsPageIdentifier/index.js
  src/app/contexts/RequestContext/getStatsPageIdentifier/index.test.js
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
Labels: simorgh-core-stream, ws-frontpage-stream

#2269 re-instate npm audit
  .travis.yml
  Makefile
  package-lock.json
  package.json
Labels: infra-tooling-stream

#2267 bump-dependency in simorgh
  package-lock.json
  package.json
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
Labels: simorgh-core-stream, ws-frontpage-stream

#2274 Re-enable browser security in Cypress on Test and Live
  cypress.json
  cypress/plugins/index.js
  cypress/support/config/envs.js
Labels: high priority, infra-tooling-stream

#2292 Revert "Re-enable browser security in Cypress on Test and Live"
  cypress.json
  cypress/plugins/index.js
  cypress/support/config/envs.js
Labels: infra-tooling-stream

#2295 Uk e2es fix locally
  README.md
  cypress.json
  cypress/integration/cookieBanner.amp.js
  cypress/integration/cookieBanner.canonical.js
  cypress/plugins/index.js
  cypress/support/config/envs.js
Labels: integration-testing, simorgh-core-stream

#2283 Use DialContext for feature toggling AV
  dials.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/containers/App/App.jsx
  src/app/containers/App/index.jsx
  src/app/containers/ArticleMain/index.jsx
  src/server/Document/index.jsx
  src/server/index.jsx
Labels: articles-current-epic, articles-features-stream, high priority, simorgh-core-stream

#2284 Consolidate article Body tests into one file
  cypress/integration/articleBodySpec.js
  cypress/integration/newsBodySpec.js
  cypress/integration/persianBodySpec.js
Labels: articles-features-stream, integration-testing, simorgh-core-stream

#2105 Remove consent banner from simorgh
  .storybook/helpers/ampDecorator/__snapshots__/index.test.jsx.snap
  .storybook/helpers/ampDecorator/index.jsx
  package-lock.json
  package.json
  src/app/components/ConsentBanner/__snapshots__/index.test.jsx.snap
  src/app/components/ConsentBanner/index.jsx
  src/app/components/ConsentBanner/index.stories.jsx
  src/app/components/ConsentBanner/index.test.jsx
  src/app/containers/ConsentBanner/Banner/Text.jsx
  src/app/containers/ConsentBanner/Banner/__snapshots__/Text.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/index.amp.jsx
  src/app/containers/ConsentBanner/Banner/index.canonical.jsx
  src/app/containers/ConsentBanner/index.stories.jsx
Labels: simorgh-core-stream

#2271 Remove ghost from frontpages and rename
  src/app/components/ErrorPage/index.jsx
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/Image/index.stories.jsx
  src/app/containers/PageHandlers/__snapshots__/withLoading.test.jsx.snap
  src/app/containers/PageHandlers/withLoading.jsx
  src/app/lib/styledGrid/__snapshots__/index.test.jsx.snap
  src/app/lib/styledGrid/index.jsx
  src/app/lib/styledGrid/index.stories.jsx
  src/app/lib/styledGrid/index.test.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#2044 Use localhost.bbc.com instead of localhost
  .storybook/cypress.json
  README.md
  a11y.js
  cypress/support/config/envs.js
  docs/Creating-Components.md
  docs/Manual-Testing.md
  envConfig/local.env
  package.json
  scripts/lighthouseConfig.js
  scripts/lighthouseConfig.test.js
  src/app/containers/ConsentBanner/CanonicalLogic/cookieOvenUrl.test.js
  src/app/contexts/RequestContext/getEnv/index.test.js
  src/app/routes/getInitialData/utils/getBaseUrl.test.js
  src/index.js
  src/server/index.test.jsx
  webpack.config.client.js
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#2285 Chartbeat Utilities
  src/app/lib/analyticsUtils/chartbeat.js
  src/app/lib/analyticsUtils/chartbeat.test.js
Labels: articles-features-stream, articles-next-epic

#2345 Update Readme - Local Prod builds section
  README.md
Labels: simorgh-core-stream

#2291 update brand container storybook
  .storybook/addons.js
  package-lock.json
  package.json
  src/app/containers/Brand/index.stories.jsx
Labels: simorgh-core-stream

#2334 Av fixtures
  data/README.md
  data/news/articles/c3wmq4d1y3wo.json
  data/news/articles/cd4117egk3go.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
Labels: articles-current-epic, articles-features-stream

#2193 Fix invalid css
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/lib/layoutGrid/index.js
  src/app/lib/styledGrid/__snapshots__/index.test.jsx.snap
Labels: articles-features-stream, simorgh-core-stream

#2260 add direction rtl to footer container story
  src/app/containers/Footer/index.stories.jsx
Labels: simorgh-core-stream

#2331 Redirect all trailing slashes locally for consistency
  src/server/index.jsx
  src/server/index.test.jsx
Labels: articles-features-stream, ws-frontpage-stream

#2372 Update mediaIndicator and pass topStory prop
  package-lock.json
  package.json
  src/app/containers/StoryPromo/MediaIndicator.jsx
  src/app/containers/StoryPromo/__snapshots__/MediaIndicator.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
Labels: ws-frontpage-stream

#2409 Stage should use live env
  src/app/contexts/RequestContext/getEnv/index.js
  src/app/contexts/RequestContext/getEnv/index.test.js
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#2320 npm dedupe
  package-lock.json
Labels: simorgh-core-stream

#2151 Integrate AudioVideo
  .codeclimate.yml
  data/README.md
  data/news/articles/c0000000030o.json
  data/news/articles/c0000000031o.json
  data/news/articles/c0000000032o.json
  data/news/articles/c0000000033o.json
  data/news/articles/c0000000034o.json
  data/news/articles/c3wmq4d1y3wo.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
  scripts/bundleSize.sh
  src/app/components/AudioVideoHead/__snapshots__/index.test.jsx.snap
  src/app/components/AudioVideoHead/index.jsx
  src/app/components/AudioVideoHead/index.test.jsx
  src/app/components/Video/__snapshots__/index.test.jsx.snap
  src/app/components/Video/helpers/fixtures.js
  src/app/components/Video/index.jsx
  src/app/components/Video/index.stories.jsx
  src/app/components/Video/index.test.jsx
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/AudioVideo/Canonical.jsx
  src/app/containers/AudioVideo/Canonical.test.jsx
  src/app/containers/AudioVideo/__snapshots__/Canonical.test.jsx.snap
  src/app/containers/AudioVideo/__snapshots__/index.test.jsx.snap
  src/app/containers/AudioVideo/audioVideoMetadata.js
  src/app/containers/AudioVideo/audioVideoMetadata.test.js
  src/app/containers/AudioVideo/fixtureData.jsx
  src/app/containers/AudioVideo/helpers/fixtures.js
  src/app/containers/AudioVideo/index.jsx
  src/app/containers/AudioVideo/index.stories.jsx
  src/app/containers/AudioVideo/index.test.jsx
  src/app/containers/Video/index.jsx
  src/app/lib/utilities/audioVideo/generateAVSettings.js
  src/app/lib/utilities/audioVideo/generateAVSettings.test.js
  src/app/lib/utilities/audioVideo/helpers/fixtures.js
  src/app/lib/utilities/audioVideo/mediaPlayerSettings.js
  src/app/lib/utilities/audioVideo/mediaPlayerSettings.test.js
  src/app/lib/utilities/audioVideo/mediatorUrl.js
  src/app/lib/utilities/audioVideo/mediatorUrl.test.js
  src/app/models/propTypes/audioVideo/index.js
  src/app/models/propTypes/index.js
  src/app/models/propTypes/mainContent/index.js
Labels: articles-current-epic, articles-features-stream, high priority

#2378 Allow tree shaking, stop forcing everything to be CJS
  .babelrc.js
  package-lock.json
  package.json
  scripts/bundleSize.sh
  src/app/models/propTypes/frontPageGroup/index.js
Labels: simorgh-core-stream

#2343 Use live data on LIVE ws frontpages
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/routes/getInitialData/frontpage.js
  src/app/routes/getInitialData/frontpage.test.js
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#2373 Duplicate key prop
  src/app/containers/Caption/index.jsx
Labels: articles-current-epic, articles-features-stream

#2340 Add assertion tests on Frontpage
  src/app/containers/FrontPage/index.test.jsx
Labels: ws-frontpage-stream

#2427 Add old article team standards to code standards
  docs/Code-Standards.md
Labels: simorgh-core-stream

#2418 Revert inline link styling
  package-lock.json
  package.json
  scripts/bundleSize.sh
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineLink/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/index.jsx
Labels: articles-current-epic, articles-features-stream

#2342 Remove dependency on react-amphtml
  package-lock.json
  package.json
  scripts/bundleSize.sh
  src/app/containers/ConsentBanner/Banner/index.amp.jsx
  src/app/containers/ConsentBanner/Banner/index.amp.test.jsx
  src/app/containers/ConsentBanner/index.amp.jsx
  src/app/containers/ConsentBanner/index.amp.test.jsx
Labels: AMP, simorgh-core-stream, spike

#2420 pulls in latest a11y tweaks to media indicator
  package-lock.json
  package.json
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
Labels: a11y, ws-fp-v1, ws-frontpage-stream

#2411 babel package bumps
  package-lock.json
  package.json
Labels: dependencies, simorgh-core-stream

#2293 add story for header
  src/app/containers/Header/index.stories.jsx
Labels: simorgh-core-stream

#2308 add storybook for copyright container
  src/app/containers/Copyright/index.stories.jsx
Labels: simorgh-core-stream

#2461 Update fixture files for Igbo and Yoruba
  data/igbo/frontpage/index.json
  data/yoruba/frontpage/index.json
  src/app/lib/utilities/preprocessor/rules/__snapshots__/cpstypes.test.js.snap
  src/app/lib/utilities/preprocessor/rules/__snapshots__/topstories.test.js.snap
Labels: ws-frontpage-stream

#2452 Fix structured data errors
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#2135 Vary ATI domain depending on environment
  cypress/integration/atiSpec.js
  cypress/support/bodyTestHelper.js
  cypress/support/config/envs.js
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/containers/ATIAnalytics/ArticleAtiParams.jsx
  src/app/containers/ATIAnalytics/ArticleAtiParams.test.jsx
  src/app/containers/ATIAnalytics/FrontPageAtiParams.jsx
  src/app/containers/ATIAnalytics/FrontPageAtiParams.test.jsx
  src/app/containers/ATIAnalytics/amp/ampAnalyticsJson.test.js
  src/app/containers/ATIAnalytics/amp/index.jsx
  src/app/containers/ATIAnalytics/amp/index.test.jsx
  src/app/containers/ATIAnalytics/atiUrl.js
  src/app/containers/ATIAnalytics/atiUrl.test.js
  src/app/containers/ATIAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ATIAnalytics/canonical/index.jsx
  src/app/containers/ATIAnalytics/canonical/index.test.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
Labels: articles-current-epic, articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#2375 Add all service configs
  scripts/bundleSize.sh
  src/app/contexts/ServiceContext/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/index.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/loadableConfig.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/zhongwen.js
Labels: simorgh-core-stream

#2417 Canonical referral link
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/containers/ATIAnalytics/ArticleAtiParams.jsx
  src/app/containers/ATIAnalytics/ArticleAtiParams.test.jsx
  src/app/containers/ATIAnalytics/atiUrl.js
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/App/__snapshots__/App.test.jsx.snap
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/AudioVideo/__snapshots__/index.test.jsx.snap
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
  src/app/lib/analyticsUtils/index.js
  src/app/lib/utilities/usePrevious/index.js
  src/app/lib/utilities/usePrevious/index.test.jsx
Labels: articles-current-epic, articles-features-stream

#2496 React warnings fail tests
  jest.config.js
  package-lock.json
  package.json
  src/testHelpers/setupTests.js
Labels: simorgh-core-stream

#2487 Add front page fixtures
  data/afaanoromoo/frontpage/index.json
  data/afrique/frontpage/index.json
  data/amharic/frontpage/index.json
  data/arabic/frontpage/index.json
  data/azeri/frontpage/index.json
  data/bengali/frontpage/index.json
  data/burmese/frontpage/index.json
  data/gahuza/frontpage/index.json
  data/gujarati/frontpage/index.json
  data/hausa/frontpage/index.json
  data/hindi/frontpage/index.json
  data/indonesia/frontpage/index.json
  data/japanese/frontpage/index.json
  data/korean/frontpage/index.json
  data/kyrgyz/frontpage/index.json
  data/marathi/frontpage/index.json
  data/mundo/frontpage/index.json
  data/naidheachdan/frontpage/index.json
  data/nepali/frontpage/index.json
  data/newyddion/frontpage/index.json
  data/pashto/frontpage/index.json
  data/persian/frontpage/index.json
  data/portuguese/frontpage/index.json
  data/punjabi/frontpage/index.json
  data/russian/frontpage/index.json
  data/serbian/frontpage/index.json
  data/sinhala/frontpage/index.json
  data/somali/frontpage/index.json
  data/swahili/frontpage/index.json
  data/tamil/frontpage/index.json
  data/telugu/frontpage/index.json
  data/tigrinya/frontpage/index.json
  data/turkce/frontpage/index.json
  data/ukchina/frontpage/index.json
  data/ukrainian/frontpage/index.json
  data/urdu/frontpage/index.json
  data/uzbek/frontpage/index.json
  data/vietnamese/frontpage/index.json
  data/zhongwen/frontpage/index.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
Labels: simorgh-core-stream

#2495 Add hreflang to frontpages
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
Labels: ws-fp-v1, ws-frontpage-stream

#2457 Add translations for Igbo, Yoruba & Pidgin error pages
  src/app/containers/ErrorMain/index.stories.jsx
  src/app/containers/FrontPage/index.test.jsx
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
Labels: Error handling, shared-components, ws-frontpage-stream

#2491 Fix typo in Igbo cookie banner
  src/app/lib/config/services/igbo.js
Labels: bug, ws-fp-v1, ws-frontpage-stream

#2339 bbc-a11y intermittent failure
  Jenkinsfile
  Makefile
  package.json
  puppeteer/bundleRequests.test.js
Labels: infra-tooling-stream

#2544 Bump psammead dependencies
  package-lock.json
  package.json
  scripts/bundleSize.sh
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleFigure/fixtureData.jsx
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/Brand/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/index.jsx
  src/app/containers/Caption/index.test.jsx
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/index.amp.jsx
  src/app/containers/ConsentBanner/Banner/index.canonical.jsx
  src/app/containers/Copyright/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/index.jsx
  src/app/containers/Footer/index.test.jsx
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withPageWrapper.test.jsx.snap
  src/app/containers/StoryPromo/MediaIndicator.jsx
  src/app/containers/StoryPromo/MediaIndicator.test.jsx
  src/app/containers/StoryPromo/__snapshots__/MediaIndicator.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  webpack.config.client.js
Labels: simorgh-core-stream

#2504 tracking pixel doesnt push other elements downward
  cypress/integration/atiSpec.js
  src/app/containers/ATIAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ATIAnalytics/canonical/index.jsx
  src/app/containers/ATIAnalytics/canonical/index.test.jsx
Labels: bug, ws-frontpage-stream

#2533 Add dep checker and main entry to package.json
  package.json
Labels: simorgh-core-stream

#2562 Stop running NPM audit in CI
  .travis.yml
  Makefile
Labels: simorgh-core-stream

#2554 Remove unneeded route
  src/server/index.jsx
Labels: simorgh-core-stream

#2497 Run babel-jest to try to avoid jest failures in CI
  .babelrc.js
  package.json
Labels: infra-tooling-stream

#2564 update package-lock to fix audit vulns
  package-lock.json
Labels: simorgh-core-stream

#2541 restore article specific linked data
  cypress/integration/metaNewsSpec.js
  cypress/integration/metaPersianSpec.js
  src/app/components/LinkedData/__snapshots__/index.test.jsx.snap
  src/app/components/LinkedData/index.jsx
  src/app/components/LinkedData/index.test.jsx
Labels: articles-features-stream, bug, simorgh-core-stream, ws-frontpage-stream

#2534 Use React recommended minifier
  package-lock.json
  package.json
  webpack.config.client.js
Labels: simorgh-core-stream

#2416 Add speculative scenarios for new block types
  data/schema.yaml
  data/test/news/articles/c0000000030o.json
  data/test/news/articles/c0000000031o.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
Labels: simorgh-core-stream

#2553 Lint Cypress
  .eslintrc.js
  cypress/integration/metaNewsSpec.js
  cypress/integration/metaPersianSpec.js
  cypress/support/bodyTestHelper.js
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2490 Adds fixture data for many services' articles
  data/afaanoromoo/articles/c4g19kgl85ko.json
  data/afrique/articles/cz216x22106o.json
  data/amharic/articles/c3rykrrvy19o.json
  data/arabic/articles/c69dvq19k63o.json
  data/azeri/articles/c5k08pqnzexo.json
  data/bengali/articles/c6p3yp5zzmeo.json
  data/burmese/articles/c3w1kwwmm5yo.json
  data/cymrufyw/articles/c06p32z9x2mo.json
  data/gahuza/articles/cey23zx8wx8o.json
  data/gujarati/articles/cr5el5kw591o.json
  data/hausa/articles/c2nr6xqmnewo.json
  data/hindi/articles/c0469479x9xo.json
  data/igbo/articles/cr1lw620ygjo.json
  data/indonesia/articles/c0q2zq8pzvzo.json
  data/japanese/articles/c693w95w0mko.json
  data/korean/articles/cpv9kv2yzk6o.json
  data/kyrgyz/articles/c3xd4xg3rm9o.json
  data/marathi/articles/cp47g4myxz7o.json
  data/mundo/articles/c45965g63xno.json
  data/naidheachdan/articles/c18q7nedn2ko.json
  data/nepali/articles/cl90j9m3mn6o.json
  data/pashto/articles/cng0e8v85eko.json
  data/pidgin/articles/cwl08rd38l6o.json
  data/portuguese/articles/cerj3rk9mmyo.json
  data/punjabi/articles/c0l79lr39qyo.json
  data/russian/articles/ck7pz7re3zgo.json
  data/serbian/articles/c805k05kr73o/cyr.json
  data/serbian/articles/c805k05kr73o/lat.json
  data/sinhala/articles/c45w255zlexo.json
  data/somali/articles/cgn6emk3jm8o.json
  data/sport/articles/c1k48dxykddo.json
  data/swahili/articles/czjqge2jwn2o.json
  data/tamil/articles/cwl08ll3me8o.json
  data/telugu/articles/cq0y4008d4vo.json
  data/thai/articles/c3qxeqm7ldjo.json
  data/tigrinya/articles/c12g32eldk6o.json
  data/turkce/articles/cr2d32lwww2o.json
  data/ukchina/articles/c0e8weny66ko/simp.json
  data/ukchina/articles/c0e8weny66ko/trad.json
  data/ukrainian/articles/c0glz45kqz6o.json
  data/ukrainian/articles/cwe04e9zwrzo.json
  data/urdu/articles/cx621klkm1ro.json
  data/uzbek/articles/cdy81y9ml65o.json
  data/uzbek/articles/cxj3rjxm6r0o.json
  data/vietnamese/articles/c3y59g5zm19o.json
  data/yoruba/articles/clw06m0nj8qo.json
  data/zhongwen/articles/c3xd4x9prgyo/simp.json
  data/zhongwen/articles/c3xd4x9prgyo/trad.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
Labels: articles-current-epic, articles-features-stream

#2341 Feature toggles
  package-lock.json
  package.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/Layouts/defaultPageWrapper.test.jsx
  src/app/containers/Article/index.jsx
  src/app/containers/FrontPage/index.jsx
  src/app/containers/FrontPage/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/PageHandlers/__snapshots__/withPageWrapper.test.jsx.snap
  src/app/containers/PageHandlers/withContexts.jsx
  src/app/containers/PageHandlers/withContexts.test.jsx
  src/app/containers/Toggle/README.md
  src/app/containers/Toggle/__snapshots__/index.test.jsx.snap
  src/app/containers/Toggle/index.jsx
  src/app/containers/Toggle/index.test.jsx
  src/app/containers/Toggle/useToggle.jsx
  src/app/containers/Toggle/useToggle.test.jsx
  src/app/containers/Toggle/utils/isToggleEnabled.js
  src/app/containers/Toggle/utils/isToggleEnabled.test.js
  src/app/contexts/ToggleContext/__snapshots__/index.test.jsx.snap
  src/app/contexts/ToggleContext/index.jsx
  src/app/contexts/ToggleContext/index.test.jsx
  src/app/lib/config/toggles/index.js
  src/app/reducers/ToggleReducer/index.jsx
Labels: simorgh-core-stream

#2575 Fixing missing services
  data/cymrufyw/frontpage/index.json
  data/mundo/frontpage/index.json
  data/naidheachdan/frontpage/index.json
  data/news/frontpage/index.json
  data/thai/frontpage/index.json
  src/app/lib/utilities/preprocessor/rules/__snapshots__/topstories.test.js.snap
  src/server/index.jsx
Labels: simorgh-core-stream

#2568 Be specific about brand SVG we use
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/zhongwen.js
Labels: simorgh-core-stream

#2556 Log response times in simorgh
  src/server/index.jsx
  src/server/utilities/logResponseTime/index.js
  src/server/utilities/logResponseTime/index.test.js
Labels: infra-tooling-stream, simorgh-core-stream

#2603 Only run jest tests on changed files
  package.json
Labels: infra-tooling-stream, simorgh-core-stream

#2540 Consolidate meta news and persian test files
  cypress/integration/metaArticleSpec.js
  cypress/integration/metaNewsSpec.js
  cypress/integration/metaPersianSpec.js
  cypress/support/config/services.js
Labels: integration-testing, simorgh-core-stream

#2602 Add Ramda
  package-lock.json
  package.json
  scripts/bundleSize.sh
  src/app/containers/Article/index.jsx
  src/app/containers/AudioVideo/audioVideoMetadata.js
  src/app/containers/AudioVideo/index.jsx
  src/app/containers/Caption/index.jsx
  src/app/containers/FrontPage/index.jsx
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/FrontPageSection/index.jsx
  src/app/containers/InlineLink/index.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/PageHandlers/withData.jsx
  src/app/containers/StoryPromo/LinkContents.jsx
  src/app/containers/StoryPromo/MediaIndicator.jsx
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/lib/analyticsUtils/article.js
  src/app/lib/analyticsUtils/frontpage.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/utilities/audioVideo/generateAVSettings.js
  src/app/lib/utilities/audioVideo/mediaPlayerSettings.js
  src/app/lib/utilities/compose/index.js
  src/app/lib/utilities/compose/index.test.js
  src/app/lib/utilities/deepClone/index.js
  src/app/lib/utilities/deepClone/index.test.js
  src/app/lib/utilities/deepGet/index.js
  src/app/lib/utilities/deepGet/index.test.js
  src/app/lib/utilities/getPassportHome/index.js
  src/app/lib/utilities/preprocessor/rules/addIdsToBlocks.js
  src/app/lib/utilities/preprocessor/rules/blockPositioning.js
  src/app/lib/utilities/preprocessor/rules/blockPositioning.test.js
  src/app/lib/utilities/preprocessor/rules/cpstypes.js
  src/app/lib/utilities/preprocessor/rules/filterEmptyGroupItems.js
  src/app/lib/utilities/preprocessor/rules/timestamp.js
  src/app/lib/utilities/preprocessor/rules/timestamp.test.js
  src/app/lib/utilities/preprocessor/rules/topstories.js
  src/testHelpers/index.js
Labels: simorgh-core-stream

#2607 Error page font & lang attribute fix
  cypress/integration/errorPageNews.js
  src/app/components/ErrorPage/index.jsx
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/index.jsx
Labels: shared-components

#2611 Fix for spacing background colour
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/index.jsx
  src/app/lib/styledGrid/__snapshots__/index.test.jsx.snap
  src/app/lib/styledGrid/index.jsx
  src/app/lib/styledGrid/index.test.jsx
Labels: shared-components

#2608 Remove unnecessary cypress utilities
  cypress/integration/ampSpec.js
  cypress/integration/articleBodySpec.js
  cypress/integration/footerSpec.js
  cypress/integration/frontpageAmpSpec.js
  cypress/integration/headerSpec.js
  cypress/integration/metaArticleSpec.js
  cypress/integration/metaNewsSpec.js
  cypress/support/bodyTestHelper.js
  cypress/support/metaTestHelper.js
Labels: simorgh-core-stream

#2287 Fix metadata proptypes
  src/app/components/LinkedData/index.jsx
  src/app/components/Metadata/index.jsx
  src/app/components/Metadata/propTypesCheck.js
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/Metadata/index.jsx
  src/app/models/propTypes/article/index.js
  src/app/models/propTypes/frontPage/index.js
  src/app/models/propTypes/frontPageMetadata/index.js
  src/app/models/propTypes/metadata/index.js
  src/app/models/propTypes/promo/index.js
Labels: articles-features-stream, ws-frontpage-stream

#2621 Translate photogallery
  src/app/containers/AudioVideo/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-fp-phase2, ws-frontpage-stream

#2619 Article Storybook
  src/app/containers/ArticleMain/index.stories.jsx
Labels: simorgh-core-stream

#2327 Remove PropTypes in Production
  .babelrc.js
  .eslintrc.js
  package-lock.json
  package.json
  scripts/bundleSize.sh
  webpack.config.js
Labels: simorgh-core-stream

#2660 Updating the Simorgh tech overview
  docs/Simorgh-Overview.md
Labels: simorgh-core-stream

#2644 Refactor front page cypress helpers
  cypress/integration/frontpageLayoutSpec.js
  cypress/support/frontpageElements.js
Labels: Heracles, integration-testing, simorgh-core-stream

#2690 Revise cc yaml excludes
  .codeclimate.yml
Labels: simorgh-core-stream

#2645 put manifest and sw in one file
  cypress/integration/application/index.js
  cypress/integration/manifest.js
  cypress/integration/sw.js
Labels: Heracles, integration-testing, simorgh-core-stream

#2610 Use new tree shake deps
  package-lock.json
  package.json
  scripts/bundleSize.sh
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
Labels: simorgh-core-stream

#2696 add other services to cypress config
  cypress/support/config/services.js
Labels: simorgh-core-stream

#2626 Styled Components pure transpilation to aide dead code elimination
  .babelrc.js
Labels: simorgh-core-stream

#2658 Initial routes for media pod
  src/app/containers/MediaPage/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPage/index.jsx
  src/app/containers/MediaPage/index.test.jsx
  src/app/routes/getInitialData/mediapage/index.js
  src/app/routes/getInitialData/mediapage/index.test.js
  src/app/routes/index.js
  src/app/routes/regex/index.js
  src/server/index.jsx
Labels: ws-media-stream

#2640 Descriptive durations
  src/app/containers/StoryPromo/LinkContents/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/LinkContents/index.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/lib/utilities/describeDuration/index.js
  src/app/lib/utilities/describeDuration/index.test.js
Labels: ws-fp-phase2, ws-frontpage-stream

#2659 Add @babel/plugin-transform-runtime
  .babelrc.js
  package-lock.json
  package.json
  scripts/bundleSize.sh
Labels: simorgh-core-stream

#2714 Update error page lang to en-GB
  3rdPartyCypress/cypress/integration/errorPageNews.js
Labels: shared-components

#2705 Refactor header helper
  cypress/integration/articleBodySpec.js
  cypress/support/bodyTestHelper.js
Labels: simorgh-core-stream

#2620 provide privacy banner landmark
  cypress/integration/frontpageLayoutSpec.js
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/containers/Header/index.jsx
Labels: a11y, articles-current-epic, articles-features-stream, shared-components

#2727 use latest storybook helper
  package-lock.json
  package.json
Labels: Heracles, dependencies, simorgh-core-stream

#2425 Fix image and video captions to use Reith Sans Regular Italic.
  .storybook/config.js
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleFigure/fixtureData.jsx
  src/app/containers/ArticleFigure/index.jsx
  src/app/containers/ArticleFigure/index.stories.jsx
  src/app/containers/ArticleFigure/index.test.jsx
  src/app/containers/AudioVideo/helpers/fixtureData.jsx
  src/app/containers/AudioVideo/index.stories.jsx
  src/app/lib/globalStyles/__snapshots__/index.test.jsx.snap
  src/app/lib/globalStyles/index.jsx
  src/app/lib/globalStyles/index.test.jsx
Labels: articles-current-epic, articles-features-stream

#2609 Target test CD pipeline
  Jenkinsfile
Labels: infra-tooling-stream

#2706 Update configs for Arabic, Urdu and Pashto
  src/app/contexts/ServiceContext/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/urdu.js
Labels: articles-current-epic, articles-features-stream

#2715 Media page live translations
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#2708 Dynamically create media routes (radio and tv)
  src/app/routes/buildMediaRoutes/index.js
  src/app/routes/buildMediaRoutes/index.test.js
  src/app/routes/config/index.js
  src/app/routes/index.js
  src/app/routes/regex/index.js
  src/app/routes/regex/index.test.js
  src/server/index.jsx
Labels: ws-media- LiveRadioV1, ws-media-stream

#2693 Refactor footer helper into command
  cypress/integration/footerSpec.js
  cypress/support/bodyTestHelper.js
  cypress/support/commands.js
Labels: simorgh-core-stream

#2665 Chartbeat Integration with toggles
  cypress/integration/chartbeatSpec.js
  cypress/integration/scriptSpec.js
  puppeteer/bundleRequests.test.js
  scripts/bundleSize.sh
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/ChartbeatAnalytics/__snapshots__/index.test.jsx.snap
  src/app/containers/ChartbeatAnalytics/amp/index.jsx
  src/app/containers/ChartbeatAnalytics/amp/index.test.jsx
  src/app/containers/ChartbeatAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ChartbeatAnalytics/canonical/index.jsx
  src/app/containers/ChartbeatAnalytics/canonical/index.test.jsx
  src/app/containers/ChartbeatAnalytics/index.jsx
  src/app/containers/ChartbeatAnalytics/index.test.jsx
  src/app/contexts/ToggleContext/__snapshots__/index.test.jsx.snap
  src/app/lib/analyticsUtils/chartbeat/index.js
  src/app/lib/config/toggles/index.js
Labels: articles-current-epic, articles-features-stream

#2722 Remove Canonical AV implementation
  dials.json
  src/app/components/AudioVideoHead/__snapshots__/index.test.jsx.snap
  src/app/components/AudioVideoHead/index.jsx
  src/app/components/AudioVideoHead/index.test.jsx
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/AudioVideo/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/AudioVideo/Canonical/index.jsx
  src/app/containers/AudioVideo/Canonical/index.test.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/helpers/fixtureData.jsx
  src/app/containers/MediaPlayer/helpers/fixtures.js
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.stories.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/MediaPlayer/metadata/index.js
  src/app/containers/MediaPlayer/metadata/index.test.js
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/PageHandlers/withContexts.test.jsx
  src/app/contexts/ToggleContext/__snapshots__/index.test.jsx.snap
  src/app/lib/config/toggles/index.js
  src/app/lib/utilities/audioVideo/generateAVSettings/index.js
  src/app/lib/utilities/audioVideo/generateAVSettings/index.test.js
  src/app/lib/utilities/audioVideo/helpers/fixtures.js
  src/app/lib/utilities/audioVideo/mediaPlayerSettings/index.js
  src/app/lib/utilities/audioVideo/mediaPlayerSettings/index.test.js
  src/app/lib/utilities/audioVideo/mediatorUrl/index.js
  src/app/lib/utilities/audioVideo/mediatorUrl/index.test.js
  src/app/models/propTypes/index.js
  src/app/models/propTypes/mainContent/index.js
  src/app/models/propTypes/mediaPlayer/index.js
Labels: articles-av-epic, articles-features-stream

#2749 title and subtitle for liveradio from config translations
  src/app/containers/MediaPage/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPageMain/index.jsx
  src/app/containers/MediaPageMain/index.test.jsx
Labels: ws-media- LiveRadioV1, ws-media-stream

#2742 all service configs need langs
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
Labels: blocking, simorgh-core-stream, ws-frontpage-stream

#2778 Pin dependency-check package due to breaking changes
  package.json
Labels: simorgh-core-stream

#2624 Consolidate news error and persian error page
  cypress/integration/errorPageArticle.js
  cypress/integration/errorPageNews.js
  cypress/integration/errorPagePersian.js
  cypress/integration/scriptSpec.js
  cypress/support/bodyTestHelper.js
  cypress/support/config/services.js
  puppeteer/bundleRequests.test.js
Labels: Heracles, integration-testing, shared-components, simorgh-core-stream

#2736 Add `BBC` to copyright text for all services
  src/app/containers/MediaPage/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/zhongwen.js
Labels: shared-components, ws-frontpage-stream

#2707 Add support for deployment outside O.O.H time span
  Jenkinsfile
Labels: infra-tooling-stream

#2717 Demonstrate moment locales
  src/app/lib/utilities/moment/index.stories.jsx
Labels: ws-frontpage-stream

#2740 Revert "Revert "Chartbeat Integration with toggles""
  cypress/integration/chartbeatSpec.js
  cypress/integration/scriptSpec.js
  puppeteer/bundleRequests.test.js
  scripts/bundleSize.sh
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/ChartbeatAnalytics/__snapshots__/index.test.jsx.snap
  src/app/containers/ChartbeatAnalytics/amp/index.jsx
  src/app/containers/ChartbeatAnalytics/amp/index.test.jsx
  src/app/containers/ChartbeatAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ChartbeatAnalytics/canonical/index.jsx
  src/app/containers/ChartbeatAnalytics/canonical/index.test.jsx
  src/app/containers/ChartbeatAnalytics/index.jsx
  src/app/containers/ChartbeatAnalytics/index.test.jsx
  src/app/contexts/ToggleContext/__snapshots__/index.test.jsx.snap
  src/app/lib/analyticsUtils/chartbeat/index.js
  src/app/lib/config/toggles/index.js
Labels: articles-current-epic, articles-features-stream

#2795 add bbc_afaanoromoo_radio route and translations
  src/app/lib/config/services/afaanoromoo.js
  src/app/routes/config/index.js
Labels: ws-media- LiveRadioV1, ws-media-stream

#2755 Fix timestamp location at 1280px
  src/app/lib/styledGrid/__snapshots__/index.test.jsx.snap
  src/app/lib/styledGrid/index.jsx
Labels: articles-current-epic, articles-features-stream

#2547 Re-enable cookie banner tests for test env
  cypress/integration/cookieBannerWS.js
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#2780 hacky hack for timestamp bugginess
  src/app/containers/StoryPromo/index.jsx
Labels: bug, high priority, ws-frontpage-stream

#2734 Don't show images on FPs in no-js mode
  src/app/containers/ImageWithPlaceholder/__snapshots__/index.test.jsx.snap
  src/app/containers/ImageWithPlaceholder/fixtureData.jsx
  src/app/containers/ImageWithPlaceholder/index.jsx
  src/app/containers/ImageWithPlaceholder/index.test.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
Labels: ws-frontpage-stream

#2785 Storybook stories cleanup
  src/app/containers/ArticleFigure/index.stories.jsx
  src/app/containers/ArticleMain/index.stories.jsx
  src/app/containers/ArticleTimestamp/index.stories.jsx
  src/app/containers/Brand/index.stories.jsx
  src/app/containers/ConsentBanner/index.stories.jsx
  src/app/containers/Copyright/index.stories.jsx
  src/app/containers/ErrorMain/index.stories.jsx
  src/app/containers/Footer/index.stories.jsx
  src/app/containers/FrontPage/index.stories.jsx
  src/app/containers/FrontPageSection/index.stories.jsx
  src/app/containers/Header/index.stories.jsx
  src/app/containers/Headings/index.stories.jsx
  src/app/containers/Image/index.stories.jsx
  src/app/containers/ImageWithPlaceholder/index.stories.jsx
  src/app/containers/InlineLink/index.stories.jsx
  src/app/containers/MediaPlayer/index.stories.jsx
  src/app/containers/Navigation/index.stories.jsx
  src/app/containers/StoryPromo/index.stories.jsx
Labels: ws-frontpage-stream

#2716 Setup chromaticqa
  .storybook/.babelrc
  .storybook/config.js
  Jenkinsfile
  Makefile
  license-exceptions.json
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2792 Media Data Retrieval
  data/afaanoromoo/bbc_afaanoromo_radio/liveradio.json
  data/amharic/bbc_amharic_radio/liveradio.json
  data/indonesia/bbc_indonesian_radio/liveradio.json
  data/korean/bbc_korean_radio/liveradio.json
  data/tigrinya/bbc_tigrinya_radio/liveradio.json
  dataValidator/helpers/dataLoader/asyncValidateDir.js
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
  dataValidator/helpers/dataLoader/readScenario.js
  src/app/containers/MediaPageMain/index.jsx
  src/app/containers/MediaPageMain/index.test.jsx
  src/app/routes/buildMediaRoutes/index.js
  src/app/routes/buildMediaRoutes/index.test.js
  src/app/routes/getInitialData/mediapage/index.js
  src/app/routes/getInitialData/mediapage/index.test.js
  src/app/routes/regex/index.js
  src/server/index.jsx
Labels: ws-media-stream

#2819 Add libgconf
  .travis.yml
Labels: infra-tooling-stream

#2723 No italics in Arabic script fragments
  src/app/containers/Fragment/__snapshots__/index.test.jsx.snap
  src/app/containers/Fragment/index.jsx
  src/app/containers/Fragment/index.test.jsx
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
Labels: articles-current-epic, articles-features-stream

#2838 Reduce No. of stories in the pidgin fixture data
  data/pidgin/frontpage/index.json
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withData/__snapshots__/index.test.jsx.snap
Labels: simorgh-core-stream

#2798 Update cypress service config
  .codeclimate.yml
  cypress/integration/scriptSpec.js
  cypress/support/config/services.js
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2824 Build Static Assets in CI
  Jenkinsfile
Labels: infra-tooling-stream

#2807 Correct manifest and sw paths for APUPs in config
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/urdu.js
Labels: articles-current-epic, articles-features-stream

#2846 Only run error page 404 test on local for news
  cypress/support/config/services.js
Labels: simorgh-core-stream

#2751 Add PGL to CPS whitelist
  package-lock.json
  package.json
  src/app/containers/StoryPromo/MediaIndicator/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/MediaIndicator/index.jsx
  src/app/containers/StoryPromo/MediaIndicator/index.test.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/lib/utilities/preprocessor/rules/cpstypes.js
  src/app/lib/utilities/preprocessor/rules/cpstypes.test.js
Labels: ws-fp-phase2, ws-frontpage-stream
