Repository bbc/simorgh, pull requests merged in 2019-04, with the labels that each got.

#1516 Timestamp bug fix
  .storybook/cypress/integration/index.js
  cypress/screenshots/.keep
  cypress/support/index.js
  src/app/containers/Timestamp/index.jsx
  src/app/containers/Timestamp/index.stories.jsx
  src/app/containers/Timestamp/index.test.jsx
  src/app/dataValidator/rules/timestamp.js
  src/app/dataValidator/rules/timestamp.test.js
Labels: bug, high priority, v1.0

#1491 Create footer component in container and bump in new psammead styling
  package-lock.json
  package.json
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/index.jsx
Labels: must, v1.0

#1497 Add link to amphtml url
  cypress/integration/ampSpec.js
  cypress/integration/metaNewsSpec.js
  cypress/integration/metaPersianSpec.js
  cypress/screenshots/.keep
  cypress/support/metaTestHelper.js
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.jsx
  src/app/components/Metadata/index.test.jsx
  src/app/containers/Article/__snapshots__/index.test.jsx.snap
  src/app/containers/Article/fixtureData.js
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
Labels: must, v1.0

#1460 Update psammead dependencies
  package-lock.json
  package.json
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/containers/Brand/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineLink/__snapshots__/index.test.jsx.snap
Labels: high priority, must, v1.0

#1532 Fix cypress amp spec
  cypress/integration/ampSpec.js
Labels: high priority

#1537 Remove now deploy step from travis and now.json
  .travis.yml
  now.json
Labels: simorgh-core-stream

#1536 Add ATI Label Helpers
  src/app/containers/PageViewAnalytics/labelHelpers/article.js
  src/app/containers/PageViewAnalytics/labelHelpers/article.test.js
  src/app/containers/PageViewAnalytics/labelHelpers/index.js
  src/app/containers/PageViewAnalytics/labelHelpers/index.test.js
  src/app/contexts/RequestContext/getOriginContext.test.js
  src/app/helpers/onClient.js
  src/app/helpers/onClient.test.js
  src/app/helpers/tests/setLocationOrigin.js
  src/app/helpers/tests/setWindowValue.js
  src/app/routes/getInitialData/index.test.js
Labels: article-features-stream, high priority

#1581 Add SchemaOrg Metadata Entity
  cypress/integration/metaNewsSpec.js
  src/app/components/LinkedData/__snapshots__/index.test.jsx.snap
  src/app/components/LinkedData/index.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
Labels: article-features-stream

#1590 Add frontpage fixture data for initial 4
  data/prod/igbo/frontpage/index.json
  data/prod/pidgin/frontpage/index.json
  data/prod/thai/frontpage/index.json
  data/prod/yoruba/frontpage/index.json
  data/test/igbo/frontpage/index.json
  data/test/pidgin/frontpage/index.json
  data/test/thai/frontpage/index.json
  data/test/yoruba/frontpage/index.json
  src/app/dataValidator/helpers/dataLoader/asyncValidateDir.test.js
  src/app/dataValidator/helpers/dataLoader/readScenario.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/index.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/yoruba.js
  src/app/routes/index.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: ws-frontpage-stream

#1538 resolves #1338 - adds hreflang metadata
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.jsx
  src/app/components/Metadata/index.test.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
Labels: article-features-stream

#1597 Update js-yaml and jest to fix vulns
  .eslintrc.js
  .storybook/cypress/integration/index.js
  license-exceptions.json
  package-lock.json
  package.json
Labels: bug, high priority, infra-tooling-stream

#1522 Moment.js Timestamp
  package-lock.json
  package.json
  src/app/containers/README.md
  src/app/containers/Timestamp/helpers/testHelpers.js
  src/app/containers/Timestamp/index.jsx
  src/app/containers/Timestamp/index.test.jsx
  src/app/containers/Timestamp/relativeTimestamp.test.js
  src/app/containers/Timestamp/timestampUtilities.js
  src/app/containers/Timestamp/timestampUtilities.test.js
  webpack.config.client.js
Labels: article-features-stream

#1587 Stop cypress screenshots from being committed
  .gitignore
Labels: ws-frontpage-stream

#1585 multiple captions
  src/app/containers/Caption/index.jsx
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/Figure/fixtureData.jsx
  src/app/containers/Figure/index.stories.jsx
Labels: article-features-stream

#1605 Rmv snyk exceptions
  .snyk
Labels: simorgh-core-stream

#1596 Flatten top stories data
  src/app/dataValidator/rules/__snapshots__/topstories.test.js.snap
  src/app/dataValidator/rules/topstories.js
  src/app/dataValidator/rules/topstories.test.js
Labels: ws-frontpage-stream

#1582 Fix timezone bug in ATITime test
  src/app/containers/PageViewAnalytics/labelHelpers/index.test.js
Labels: articles-features-stream, bug, onward-journeys-stream, ws-frontpage-stream

#1632 add jquery as aduit-ci exceptions and use --low as per docs
  package.json
Labels: a11y, bug, high priority

#1549 Add abouts section to JSON-LD schema block
  data/prod/persian/articles/cyddjz5058wo.json
  data/test/persian/articles/cyddjz5058wo.json
  src/app/components/LinkedData/__snapshots__/index.test.jsx.snap
  src/app/components/LinkedData/index.jsx
  src/app/components/LinkedData/index.test.jsx
  src/app/containers/Article/__snapshots__/index.test.jsx.snap
  src/app/containers/Article/fixtureData.js
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/Metadata/linkedDataAbout.js
  src/app/containers/Metadata/linkedDataAbout.test.js
Labels: articles-features-stream

#1620 Move CI to simorgh from simorgh-infrastructure.
  .gitignore
  CONTRIBUTING.md
  Jenkinsfile
  package-lock.json
  scripts/jenkinsProductionFiles.sh
Labels: infra-tooling-stream, simorgh-core-stream

#1634 Add default labels to issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: simorgh-core-stream

#1584 Pass latin typography values to psammead components
  package-lock.json
  package.json
  src/app/components/ConsentBanner/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/components/Timestamp/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/index.jsx
  src/app/containers/Caption/index.test.jsx
  src/app/containers/ConsentBanner/Banner/__snapshots__/Text.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/index.jsx
  src/app/containers/Headings/index.test.jsx
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/index.jsx
  src/app/containers/Paragraph/index.test.jsx
  src/app/containers/Timestamp/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/yoruba.js
Labels: articles-features-stream, high priority

#1645 package-lock stablise to node 8.11.3 and npm 6.4.1
  package-lock.json
Labels: bug

#1633 Split up getInitalData to be more reusable
  src/app/routes/getInitialData/article.js
  src/app/routes/getInitialData/article.test.js
  src/app/routes/getInitialData/index.js
  src/app/routes/getInitialData/index.test.js
  src/app/routes/getInitialData/utils/fetchData.js
  src/app/routes/getInitialData/utils/fetchData.test.js
  src/app/routes/getInitialData/utils/getBaseUrl.js
  src/app/routes/getInitialData/utils/getBaseUrl.test.js
  src/app/routes/index.js
Labels: ws-frontpage-stream

#1619 one or two timestamps
  src/app/containers/Timestamp/__snapshots__/index.test.jsx.snap
  src/app/containers/Timestamp/index.jsx
  src/app/containers/Timestamp/index.test.jsx
Labels: articles-features-stream

#1644 Move pre-process rules out of dataValidator
  src/app/lib/utilities/preprocessor/index.js
  src/app/lib/utilities/preprocessor/index.test.js
  src/app/lib/utilities/preprocessor/rules/__snapshots__/topstories.test.js.snap
  src/app/lib/utilities/preprocessor/rules/timestamp.js
  src/app/lib/utilities/preprocessor/rules/timestamp.test.js
  src/app/lib/utilities/preprocessor/rules/topstories.js
  src/app/lib/utilities/preprocessor/rules/topstories.test.js
  src/app/routes/getInitialData/utils/fetchData.js
  src/app/routes/getInitialData/utils/fetchData.test.js
Labels: articles-features-stream, ws-frontpage-stream

#1627 Multiple paragraphs
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/index.jsx
  src/app/containers/Caption/index.test.jsx
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
Labels: articles-features-stream, high priority

#1646 Error Page passes script typography's properly
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorPage/index.jsx
  src/app/components/ErrorPage/index.test.jsx
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/index.jsx
Labels: articles-features-stream

#1653 Use timestamp component from psammead
  package-lock.json
  package.json
  src/app/components/Timestamp/README.md
  src/app/components/Timestamp/__snapshots__/index.test.jsx.snap
  src/app/components/Timestamp/index.jsx
  src/app/components/Timestamp/index.stories.jsx
  src/app/components/Timestamp/index.test.jsx
  src/app/containers/Timestamp/index.jsx
Labels: ws-frontpage-stream

#1655 Bump bbc a11y remove vuln exception
  package-lock.json
  package.json
Labels: a11y, high priority, simorgh-core-stream
