Repository bbc/simorgh, pull requests merged in 2019-01, with the labels that each got.

#1118 Fix failing 2019 date tests
  cypress/integration/footerSpec.js
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/index.jsx
  src/app/containers/Footer/index.test.jsx
Labels: bug, high priority, mergeable

#1119 Fixes wait-on in amp:validate script
  package.json
Labels: mergeable

#1111 Use Psammead Utilities
  cypress/support/bodyTestHelper.js
  package-lock.json
  package.json
  src/app/components/Document/index.jsx
  src/app/components/Figure/index.jsx
  src/app/components/Timestamp/index.jsx
  src/app/helpers/mediaQueries.js
  src/app/helpers/storybook/ampDecorator/index.jsx
  src/app/lib/constants/styles.js
  src/app/lib/constants/typography.js
  src/app/lib/layoutGrid.js
Labels: alpha-3

#1108 Use @bbc/psammead-figure component
  package-lock.json
  package.json
  src/app/components/Figure/__snapshots__/index.test.jsx.snap
  src/app/components/Figure/index.jsx
  src/app/components/Figure/index.test.jsx
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/Figure/index.jsx
Labels: mergeable

#1117 Removes Razzle from Simorgh
  .babelrc
  .env
  README.md
  cypress/integration/metaNewsSpec.js
  docs/Webpack.md
  package-lock.json
  package.json
  razzle.config.js
  src/app/helpers/tests/jest-setup.js
  src/app/lib/globalStyles.js
  src/app/routes/getInitialData/index.js
  src/app/routes/getInitialData/index.test.js
  src/server/assets/fixture.json
  src/server/assets/fixtureMissingKey.json
  src/server/assets/index.js
  src/server/assets/index.test.js
  src/server/index.jsx
  src/server/index.test.jsx
  webpack.config.client.js
  webpack.config.js
  webpack.config.server.js
Labels: mergeable

#1142 Fix latest with installing production dependencies
  Jenkinsfile
  Makefile
  package-lock.json
  package.json
  webpack.config.client.js
  webpack.config.server.js
Labels: high priority

#1130 Update to use latest dependencies
  package-lock.json
  package.json
  src/app/containers/Brand/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
Labels: alpha-3, mergeable

#1147 Webpack assets path
  package.json
  webpack.config.client.js
  webpack.config.js
  webpack.config.server.js
Labels: mergeable

#1145 npm audit in CI
  .travis.yml
  Makefile
  package-lock.json
  package.json
Labels: Goal (7th-11th), mergeable

#1143 Copy static files into build public folder
  package-lock.json
  package.json
  webpack.config.client.js
Labels: Goal (7th-11th), alpha-3, bug, mergeable

#1150 Update SC and make test dynamic
  package-lock.json
  package.json
  src/server/styles.test.jsx
Labels: bug, mergeable

#1153 Integrate amp img
  package-lock.json
  package.json
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/Figure/fixtureData.jsx
  src/app/containers/Figure/index.jsx
  src/app/containers/Figure/index.stories.jsx
  src/app/containers/Figure/index.test.jsx
Labels: AMP, Goal (7th-11th), alpha-3, high priority, mergeable

#1171 Adding a Cypress test for the amp-img
  cypress/integration/ampSpec.js
Labels: AMP, should

#1163 Make Lighthouse fail Travis
  lighthouse.js
  package-lock.json
  scripts/lighthouse/logResults.js
  scripts/lighthouse/logResults.test.js
Labels: mergeable

#1160 Fix for IE 11 Grid Layout - Body Content
  src/app/lib/layoutGrid.js
Labels: a11y, mergeable

#1164 Add Snyk to prepush
  .snyk
  package-lock.json
  package.json
Labels: Goal (7th-11th), build-pipeline, mergeable

#1173 Lower perf Lighthouse threshold, following Amp-img
  lighthouse.js
Labels: high priority, mergeable

#1155 Run Amp Validate on test
  Makefile
  package.json
Labels: AMP, Goal (7th-11th), alpha-3, mergeable

#1180 Use correct base path in webpack
  .env
  webpack.config.client.js
Labels: alpha-3, high priority, mergeable

#1190 Add https enforcer and update package lock
  package-lock.json
  package.json
Labels: alpha-3

#1188 Update timestamp & metadata containers to use lastPublished
  cypress/integration/newsBodySpec.js
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.jsx
  src/app/components/Metadata/index.test.jsx
  src/app/containers/Article/__snapshots__/index.test.jsx.snap
  src/app/containers/Article/fixtureData.js
  src/app/containers/Article/index.jsx
  src/app/containers/Metadata/index.jsx
Labels: mergeable

#1197 Update PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: mergeable

#1198 Run Lighthouse tests using lighthouse-ci
  Makefile
  lighthouse.js
  package-lock.json
  package.json
  scripts/lighthouse/README.md
  scripts/lighthouse/fixtures.js
  scripts/lighthouse/index.js
  scripts/lighthouse/index.test.js
  scripts/lighthouse/logResults.js
  scripts/lighthouse/logResults.test.js
  scripts/lighthouse/runLighthouse.js
  scripts/lighthouse/runLighthouse.test.js
Labels: mergeable

#1185 Build time variables namespaced
  src/app/routes/getInitialData/index.js
  src/clientEnvVars.js
  src/clientEnvVars.test.js
  webpack.config.client.js
Labels: alpha-3, bug, high priority

#1205 Low priority: Swap github references of BBC-News with bbc
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  Jenkinsfile
  README.md
  cypress/integration/newsBodySpec.js
  docs/Creating-Components.md
  docs/Spacing-Units.md
  docs/Webpack.md
  package.json
  src/app/containers/Article/index.jsx
  src/app/containers/Article/index.test.jsx
  src/app/dataValidator/README.md
  src/app/lib/README.md
  src/app/lib/globalStyles.js
  webpack.config.client.js
Labels: Documentation

#1204 Create multiple built bundles using different .env files
  .env
  .env.live
  .env.test
  .travis.yml
  Makefile
  README.md
  package.json
  src/server/env/index.js
  src/server/env/index.test.js
  src/server/index.jsx
  webpack.config.client.js
  webpack.config.js
Labels: Goal (21st-25th), high priority
