Repository bbc/simorgh, pull requests merged in 2019-05, with the labels that each got.

#1617 Refactor TimestampContainer.
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/ArticleTimestamp/helpers.js
  src/app/containers/ArticleTimestamp/helpers.test.js
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/ArticleTimestamp/index.stories.jsx
  src/app/containers/ArticleTimestamp/index.test.jsx
  src/app/containers/ArticleTimestamp/timeFormats.js
  src/app/containers/Timestamp/__snapshots__/index.test.jsx.snap
  src/app/containers/Timestamp/index.jsx
  src/app/containers/Timestamp/index.stories.jsx
  src/app/containers/Timestamp/index.test.jsx
  src/app/containers/Timestamp/relativeTimestamp.js
  src/app/containers/Timestamp/relativeTimestamp.test.js
  src/app/containers/Timestamp/timestampUtilities.js
  src/app/containers/Timestamp/timestampUtilities.test.js
Labels: articles-features-stream, ws-frontpage-stream

#1665 Fix Timestamp Snapshot tests
  src/app/containers/Timestamp/__snapshots__/index.test.jsx.snap
  src/app/containers/Timestamp/index.test.jsx
Labels: articles-features-stream, high priority

#1601 adding caption to video
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/index.jsx
  src/app/containers/Caption/index.test.jsx
  src/app/containers/Figure/fixtureData.jsx
  src/app/containers/Figure/index.jsx
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Video/__snapshots__/index.test.jsx.snap
  src/app/containers/Video/fixtureData.jsx
  src/app/containers/Video/index.jsx
  src/app/containers/Video/index.stories.jsx
  src/app/containers/Video/index.test.jsx
  src/app/lib/config/services/index.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
Labels: articles-features-stream

#1642 Import svg to services in config
  package-lock.json
  package.json
  src/app/containers/Brand/__snapshots__/index.test.jsx.snap
  src/app/containers/Brand/index.jsx
  src/app/containers/Brand/index.test.jsx
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/index.test.jsx
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/index.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/yoruba.js
Labels: ws-frontpage-stream

#1672 Use new persian svg
  package-lock.json
  package.json
  src/app/containers/Brand/index.stories.jsx
  src/app/lib/config/services/persian.js
Labels: ws-frontpage-stream

#1654 Update from beta version of react-router-config to latest public rele…
  package-lock.json
  package.json
Labels: simorgh-core-stream

#1640 Create Story Promo Container
  CHANGELOG.md
  package-lock.json
  package.json
  src/app/containers/StoryPromo/Figure.jsx
  src/app/containers/StoryPromo/Figure.test.jsx
  src/app/containers/StoryPromo/__snapshots__/Figure.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/models/propTypes/storyItem/index.js
Labels: ws-frontpage-stream

#1673 Refactor route matching
  cypress/integration/newsBodySpec.js
  cypress/integration/persianBodySpec.js
  cypress/support/bodyTestHelper.js
  cypress/support/metaTestHelper.js
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/App/index.jsx
  src/app/containers/Article/index.jsx
  src/app/containers/Article/index.test.jsx
  src/app/routes/getInitialData/article.js
  src/app/routes/getInitialData/article.test.js
  src/app/routes/getInitialData/utils/__snapshots__/getRouteProps.test.js.snap
  src/app/routes/getInitialData/utils/fetchData.js
  src/app/routes/getInitialData/utils/fetchData.test.js
  src/app/routes/getInitialData/utils/getRouteProps.js
  src/app/routes/getInitialData/utils/getRouteProps.test.js
  src/app/routes/loadInitialData/__snapshots__/index.test.js.snap
  src/app/routes/loadInitialData/index.js
  src/app/routes/loadInitialData/index.test.js
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.jsx
  src/server/Document/component.test.jsx
  src/server/Document/index.jsx
  src/server/index.jsx
  src/server/index.test.jsx
Labels: simorgh-core-stream

#1687 Remove changelog file
  CHANGELOG.md
Labels: Documentation, articles-features-stream, infra-tooling-stream, simorgh-core-stream, ws-frontpage-stream

#1691 Remove Lighthouse from Simorgh
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: infra-tooling-stream, simorgh-core-stream

#1615 webpack performance budget
  webpack.config.js
Labels: simorgh-core-stream

#1656 Refactor to use the useContext hook
  .eslintrc.js
  package-lock.json
  package.json
  src/app/containers/ConsentBanner/Banner/Text.jsx
  src/app/containers/ConsentBanner/Banner/index.amp.jsx
  src/app/containers/ConsentBanner/Banner/index.canonical.jsx
  src/app/containers/ConsentBanner/index.jsx
  src/app/containers/Copyright/index.jsx
  src/app/containers/Figure/index.jsx
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/index.jsx
  src/app/containers/Headings/index.test.jsx
  src/app/containers/InlineLink/index.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/StoryPromo/Figure.jsx
  src/app/containers/Timestamp/index.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
  src/app/contexts/ServiceContext/index.jsx
  src/app/contexts/ServiceContext/index.test.jsx
Labels: articles-features-stream, simorgh-core-stream

#1589 Hoc loading error states
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/containers/Article/__snapshots__/index.test.jsx.snap
  src/app/containers/Article/index.jsx
  src/app/containers/Article/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withData.test.jsx.snap
  src/app/containers/PageHandlers/__snapshots__/withError.test.jsx.snap
  src/app/containers/PageHandlers/__snapshots__/withLoading.test.jsx.snap
  src/app/containers/PageHandlers/__snapshots__/withPageWrapper.test.jsx.snap
  src/app/containers/PageHandlers/withData.jsx
  src/app/containers/PageHandlers/withData.test.jsx
  src/app/containers/PageHandlers/withError.jsx
  src/app/containers/PageHandlers/withError.test.jsx
  src/app/containers/PageHandlers/withLoading.jsx
  src/app/containers/PageHandlers/withLoading.test.jsx
  src/app/containers/PageHandlers/withPageWrapper.jsx
  src/app/containers/PageHandlers/withPageWrapper.test.jsx
  src/app/helpers/compose.js
  src/app/helpers/compose.test.js
Labels: high priority, simorgh-core-stream

#1696 Upgrade Simorgh to use Node 10
  .nvmrc
  Jenkinsfile
  README.md
  src/app/helpers/tests/setWindowValue.js
Labels: infra-tooling-stream, simorgh-core-stream

#1684 Add links to storybook in readme
  README.md
  docs/Creating-Components.md
Labels: simorgh-core-stream

#1695 Add AV fixtures to VideoContainer Storybook
  src/app/components/Video/__snapshots__/index.test.jsx.snap
  src/app/components/Video/index.jsx
  src/app/components/Video/index.stories.jsx
  src/app/components/Video/index.test.jsx
  src/app/containers/Video/__snapshots__/index.test.jsx.snap
  src/app/containers/Video/fixtureData.jsx
  src/app/containers/Video/helpers/fixtures.js
  src/app/containers/Video/index.jsx
  src/app/containers/Video/index.stories.jsx
  src/app/containers/Video/index.test.jsx
  src/app/models/propTypes/index.js
Labels: articles-current-epic, articles-features-stream

#1678 Add schema.org video metadata.
  src/app/containers/Video/__snapshots__/index.test.jsx.snap
  src/app/containers/Video/helpers/fixtures.js
  src/app/containers/Video/index.jsx
  src/app/containers/Video/videoMetadata.js
  src/app/containers/Video/videoMetadata.test.js
Labels: articles-current-epic, articles-features-stream

#1722 Build the storybook archive in Simorgh
  .gitignore
  Jenkinsfile
  Makefile
  package.json
Labels: infra-tooling-stream

#1721 Update the patch version of Node
  Jenkinsfile
Labels: infra-tooling-stream

#1723 Neil D's suggested readme changes
  README.md
Labels: simorgh-core-stream

#1725 Remove deprecated news/ fixture file cyddjz5058wo
  README.md
  data/prod/news/articles/cyddjz5058wo.json
  src/app/dataValidator/helpers/dataLoader/asyncValidateDir.test.js
Labels: articles-features-stream

#1715 Fix metadata
  cypress/integration/metaPersianSpec.js
  src/app/components/LinkedData/__snapshots__/index.test.jsx.snap
  src/app/components/LinkedData/index.jsx
  src/app/components/LinkedData/index.test.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/lib/config/services/persian.js
Labels: articles-features-stream, articles-next-epic, bug

#1692 Fix prop type errors
  data/test/news/articles/c0000000002o.json
  data/test/news/articles/c0000000003o.json
  data/test/news/articles/c0000000005o.json
  data/test/news/articles/c0000000006o.json
  data/test/news/articles/c0000000007o.json
  data/test/news/articles/c0000000008o.json
  data/test/news/articles/c0000000011o.json
  data/test/news/articles/c0000000014o.json
  data/test/news/articles/c0000000020o.json
  package-lock.json
  package.json
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/index.jsx
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/models/propTypes/mainContent/index.js
  src/app/models/propTypes/timestamp/index.js
Labels: articles-features-stream, bug

#1711 Add id & stats params to RequestContext
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/Layouts/defaultPageWrapper.test.jsx
  src/app/containers/App/App.jsx
  src/app/containers/ConsentBanner/Banner/__snapshots__/Text.test.jsx.snap
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/PageViewAnalytics/labelHelpers/index.js
  src/app/containers/PageViewAnalytics/labelHelpers/index.test.js
  src/app/containers/Video/__snapshots__/index.test.jsx.snap
  src/app/containers/Video/fixtureData.jsx
  src/app/contexts/RequestContext/__snapshots__/index.test.jsx.snap
  src/app/contexts/RequestContext/getStatsDestination.js
  src/app/contexts/RequestContext/getStatsDestination.test.js
  src/app/contexts/RequestContext/getStatsPageIdentifier.js
  src/app/contexts/RequestContext/getStatsPageIdentifier.test.js
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
  src/app/routes/getInitialData/utils/getRouteProps.js
Labels: articles-current-epic, articles-features-stream, simorgh-core-stream

#1728 Cleanup the stages in the Jenkins file
  Jenkinsfile
  Makefile
Labels: infra-tooling-stream

#1714 Remove the default global code owners
  .github/CODEOWNERS
Labels: simorgh-core-stream

#1700 Re-enable nocycle linting
  .eslintrc.js
  src/app/containers/InlineLink/index.jsx
  src/app/routes/index.js
  src/app/routes/regex/index.js
  src/app/routes/regex/index.test.js
  src/server/index.jsx
Labels: simorgh-core-stream

#1671 Adjust timestamp position if headline followed by image, video or audio
  src/app/lib/utilities/preprocessor/rules/timestamp.js
  src/app/lib/utilities/preprocessor/rules/timestamp.test.js
Labels: articles-current-epic, articles-features-stream

#1744 Remove all traces of NPM audit until the NPM audit service issues are…
  .travis.yml
  Makefile
  package-lock.json
  package.json
Labels: infra-tooling-stream

#1739 Storybook Proptypes fix
  src/app/containers/ConsentBanner/Banner/Text.test.jsx
  src/app/containers/ConsentBanner/Banner/__snapshots__/Text.test.jsx.snap
  src/app/containers/ConsentBanner/index.test.jsx
  src/app/containers/Figure/fixtureData.jsx
  src/app/containers/StoryPromo/Figure.test.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/containers/Video/__snapshots__/index.test.jsx.snap
  src/app/containers/Video/fixtureData.jsx
Labels: articles-features-stream, simorgh-core-stream

#1729 Create WS Front Page
  src/app/containers/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPage/index.jsx
  src/app/containers/FrontPage/index.stories.jsx
  src/app/containers/FrontPage/index.test.jsx
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/FrontPageMain/index.test.jsx
Labels: ws-frontpage-stream

#1747 Remove existing storybook.zip
  Jenkinsfile
Labels: bug, infra-tooling-stream

#1701 Pull in psammead-headings@2.0.0
  package-lock.json
  package.json
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/index.jsx
  src/app/containers/Headings/index.stories.jsx
  src/app/containers/Headings/index.test.jsx
  src/app/containers/Headings/testHelpers.js
  src/app/lib/utilities/idSanitiser.js
  src/app/lib/utilities/idSanitiser.test.js
Labels: articles-features-stream

#1746 Video props
  src/app/components/Video/__snapshots__/index.test.jsx.snap
  src/app/components/Video/index.jsx
  src/app/components/Video/index.stories.jsx
  src/app/components/Video/index.test.jsx
  src/app/containers/Video/__snapshots__/index.test.jsx.snap
  src/app/containers/Video/fixtureData.jsx
  src/app/containers/Video/index.jsx
  src/app/containers/Video/index.stories.jsx
  src/app/containers/Video/index.test.jsx
  src/app/models/propTypes/index.js
Labels: articles-current-epic, articles-features-stream, high priority

#1756 Add frontpage & frontpage/beta route with dummy content
  src/server/index.jsx
  src/server/index.test.jsx
Labels: simorgh-core-stream, ws-fp-v1, ws-frontpage-stream

#1703 Section container
  package-lock.json
  package.json
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.jsx
  src/app/containers/FrontPageSection/index.stories.jsx
  src/app/containers/FrontPageSection/index.test.jsx
  src/app/models/propTypes/frontPageGroup/index.js
Labels: ws-frontpage-stream

#1771 Upgrade Storybook to v5
  .storybook/config.js
  .storybook/cypress/integration/index.js
  license-exceptions.json
  package-lock.json
  package.json
  src/app/containers/Headings/index.stories.jsx
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#1780 Fix live E2E tests using getBlockByType func
  cypress/support/bodyTestHelper.js
Labels: bug, high priority, simorgh-core-stream

#1769 Add Link to Story Promo
  package-lock.json
  package.json
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.test.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#1779 Removed the npm snyk command from the pre-push husky script
  package.json
Labels: infra-tooling-stream

#1770 Filter empty group items
  src/app/lib/utilities/preprocessor/rules/filterEmptyGroupItems.js
  src/app/lib/utilities/preprocessor/rules/filterEmptyGroupItems.test.js
Labels: ws-fp-v1, ws-frontpage-stream

#1750 Upgrade to react 16.8.6 (current latest)
  package-lock.json
  package.json
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
Labels: simorgh-core-stream

#1766 Add rule to filter unwanted CPS types
  src/app/lib/utilities/preprocessor/rules/__snapshots__/cpstypes.test.js.snap
  src/app/lib/utilities/preprocessor/rules/cpstypes.js
  src/app/lib/utilities/preprocessor/rules/cpstypes.test.js
Labels: ws-fp-v1, ws-frontpage-stream

#1680 nested grid wrapper
  src/app/lib/README.md
  src/app/lib/__snapshots__/styledGrid.test.jsx.snap
  src/app/lib/layoutGrid.js
  src/app/lib/layoutGrid.test.js
  src/app/lib/styledGrid.js
  src/app/lib/styledGrid.jsx
  src/app/lib/styledGrid.stories.jsx
  src/app/lib/styledGrid.test.jsx
Labels: articles-current-epic, articles-features-stream, high priority

#1749 Remove the useBuiltins warning
  .babelrc
Labels: simorgh-core-stream, ws-frontpage-stream

#1796 Remove storybook.zip before starting SB build
  Jenkinsfile
Labels: infra-tooling-stream

#1734 Lazy-loading images
  cypress/integration/newsBodySpec.js
  cypress/integration/persianBodySpec.js
  package-lock.json
  package.json
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/Figure/fixtureData.jsx
  src/app/containers/Figure/index.jsx
  src/app/containers/Figure/index.test.jsx
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/index.jsx
Labels: articles-current-epic, articles-features-stream

#1737 Update Video Schema
  data/schema.yaml
  data/test/news/articles/c0000000003o.json
  data/test/news/articles/c0000000004o.json
  data/test/news/articles/c0000000005o.json
  data/test/news/articles/c0000000006o.json
  data/test/news/articles/c0000000009o.json
  data/test/news/articles/c0000000012o.json
  data/test/news/articles/c0000000013o.json
  data/test/news/articles/c0000000015o.json
  data/test/news/articles/c0000000016o.json
  data/test/news/articles/c0000000017o.json
  data/test/news/articles/c0000000018o.json
  data/test/news/articles/c0000000019o.json
  data/test/news/articles/c0000000022o.json
Labels: articles-current-epic, articles-features-stream

#1783 Populate Front Page container
  src/app/containers/FrontPage/index.jsx
  src/app/containers/FrontPage/index.stories.jsx
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.jsx
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
  src/app/models/propTypes/frontPage/index.js
  src/app/models/propTypes/frontPageMetadata/index.js
  src/app/models/propTypes/frontPageRelatedContent/index.js
  src/app/models/propTypes/frontPageSection/index.js
  src/app/models/propTypes/frontPageSite/index.js
  src/app/models/propTypes/storyItem/index.js
Labels: ws-fp-v1, ws-frontpage-stream

#1803 Add instructions to readme for accessing UK/Intl versions locally
  README.md
Labels: simorgh-core-stream

#1706 Fix e2e test for mozart failover
  cypress/integration/statusSpec.js
  cypress/support/metaTestHelper.js
  package-lock.json
Labels: infra-tooling-stream

#1815 Update test assets
  README.md
  a11y.js
  cypress/support/config.js
  data/prod/news/articles/c0g992jmmkko.json
  data/prod/news/articles/c6v11qzyv8po.json
  data/prod/persian/articles/c4vlle3q337o.json
  data/test/news/articles/c0000000020o.json
  data/test/news/articles/c0g992jmmkko.json
  data/test/news/articles/c6v11qzyv8po.json
  data/test/persian/articles/c4vlle3q337o.json
  package.json
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.test.jsx
  src/app/containers/Article/fixtureData.js
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineLink/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineLink/index.test.jsx
  src/app/containers/Metadata/index.test.jsx
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.test.jsx
  src/server/index.test.jsx
Labels: articles-features-stream, simorgh-core-stream

#1767 Refactor App container with hooks and remove loadInitialData
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/App/__snapshots__/App.test.jsx.snap
  src/app/routes/getInitialData/article.js
  src/app/routes/getInitialData/article.test.js
  src/app/routes/loadInitialData/index.js
  src/app/routes/loadInitialData/index.test.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: simorgh-core-stream

#1628 Implement cosmos dial for MPulse beacon
  a11y.js
  dials.json
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  package.json
  src/app/components/MPulseBeacon/__snapshots__/index.test.jsx.snap
  src/app/components/MPulseBeacon/index.jsx
  src/app/components/MPulseBeacon/index.test.jsx
  src/app/containers/MPulseBeacon/index.jsx
  src/app/containers/MPulseBeacon/index.test.jsx
  src/app/contexts/DialContext/__snapshots__/index.test.jsx.snap
  src/app/contexts/DialContext/index.jsx
  src/app/contexts/DialContext/index.test.jsx
  src/app/helpers/tests/mockComponents.jsx
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.jsx
  src/server/Document/component.test.jsx
  src/server/Document/index.jsx
  src/server/getDials/index.js
  src/server/getDials/index.test.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: simorgh-core-stream

#1797 Add uploadDate to Video schema.org
  src/app/containers/Video/__snapshots__/index.test.jsx.snap
  src/app/containers/Video/helpers/fixtures.js
  src/app/containers/Video/videoMetadata.js
  src/app/containers/Video/videoMetadata.test.js
Labels: articles-current-epic, articles-features-stream

#1795 Wait for server start before running tests
  package.json
Labels: infra-tooling-stream
