Repository bbc/simorgh, pull requests merged in 2019-12, with the labels that each got.

#4797 add variant compatiablity to story container
  package-lock.json
  package.json
  src/app/containers/Brand/index.stories.jsx
  src/app/containers/Copyright/index.stories.jsx
  src/app/containers/Header/index.stories.jsx
  src/app/containers/Navigation/index.stories.jsx
  src/app/contexts/ServiceContext/index.jsx
  src/app/lib/utilities/variantHandler/index.js
Labels: shared-components

#4801 Cypress Test - Making Sure Subtitles are Enabled
  cypress/integration/pages/articles/testsForCanonicalOnly.js
Labels: articles-features-stream, integration-testing

#4831 Add 9 live assets to e2es
  cypress/support/config/services.js
Labels: articles-features-stream, articles-rollout

#4827 Add new opengraph image for Japanese
  public/japanese/images/metadata/poster-1024x576.png
  src/app/lib/config/services/japanese.js
Labels: articles-features-stream, articles-rollout

#4800 Bump of psammead package versions
  package-lock.json
  package.json
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
Labels: articles-av-epic, articles-features-stream, articles-rollout, blocking

#4805 Create feature toggle for most read
  src/app/containers/MostRead/index.jsx
  src/app/containers/MostRead/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
Labels: most-read, shared-components

#4870 Update dev dependencies
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#4860 Enable articles for /archive
  cypress/support/config/services.js
  data/archive/articles/cqv9w00mgjpo.json
  public/archive/images/icons/icon-128x128.png
  public/archive/images/icons/icon-144x144.png
  public/archive/images/icons/icon-152x152.png
  public/archive/images/icons/icon-192x192.png
  public/archive/images/icons/icon-384x384.png
  public/archive/images/icons/icon-512x512.png
  public/archive/images/icons/icon-72x72.png
  public/archive/images/icons/icon-96x96.png
  public/archive/images/metadata/poster-1024x576.png
  public/archive/manifest.json
  src/app/containers/ArticleTimestamp/timeFormatTests/expectedFormats.json
  src/app/contexts/RequestContext/getStatsDestination/index.js
  src/app/contexts/RequestContext/getStatsDestination/index.test.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/loadableConfig.js
  src/server/utilities/serviceConfigs/index.js
Labels: articles-features-stream, articles-rollout

#4816 Implement schema.org for structured AV data
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/Metadata.jsx
  src/app/containers/MediaPlayer/Metadata.test.jsx
  src/app/containers/MediaPlayer/__snapshots__/Metadata.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/fixtureData.jsx
  src/app/containers/MediaPlayer/helpers/metadata/index.js
  src/app/containers/MediaPlayer/helpers/metadata/index.test.js
  src/app/containers/MediaPlayer/index.jsx
Labels: articles-av-epic, articles-features-stream, ws-media-stream

#4672 Event tracking fixes
  src/app/containers/ATIAnalytics/README.md
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/atiUrl/index.test.js
  src/app/containers/ATIAnalytics/beacon/index.js
  src/app/containers/ATIAnalytics/beacon/index.test.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
Labels: ws-frontpage-stream

#4879 Disable test/local e2e for archive articles until routing is done
  cypress/support/config/services.js
Labels: articles-features-stream, articles-rollout

#4869 Improve test coverage of CPS MAP blocks
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.test.jsx
Labels: ws-media-stream

#4874 change av embed url origin
  cypress/support/config/envs.js
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/helpers/embedUrl.js
  src/app/containers/MediaPlayer/helpers/embedUrl.test.js
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.test.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/index.test.jsx
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/index.test.jsx
Labels: articles-av-epic, articles-features-stream, ws-media-stream

#4882 Do not run e2e tests at 3am
  Jenkinsfile-e2e
  Jenkinsfile-e2e-local
  Jenkinsfile-e2e-test
Labels: infra-tooling-stream, simorgh-core-stream

#4820 Include method to set build metatadata
  Jenkinsfile
  Jenkinsfile-e2e
Labels: infra-tooling-stream

#4561 Manually set focus on content whenever user navigates
  src/app/containers/App/App.jsx
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/index.jsx
Labels: a11y-swarm, articles-features-stream, simorgh-core-stream

#4884 Revert "change av embed url origin"
  cypress/support/config/envs.js
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/helpers/embedUrl.js
  src/app/containers/MediaPlayer/helpers/embedUrl.test.js
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.test.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/index.test.jsx
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/index.test.jsx
Labels: articles-features-stream, ws-media-stream

#4887 Revert running live e2es against ref obtained from server
  Jenkinsfile-e2e
Labels: infra-tooling-stream, simorgh-core-stream

#4861 Correct AMP Chartbeat Config
  src/app/containers/ChartbeatAnalytics/amp/index.jsx
  src/app/containers/ChartbeatAnalytics/amp/index.test.jsx
  src/app/containers/ChartbeatAnalytics/index.jsx
Labels: articles-features-stream, chartbeat, simorgh-core-stream

#4888 Revert "Revert "change av embed url origin""
  cypress/support/config/envs.js
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/helpers/embedUrl.js
  src/app/containers/MediaPlayer/helpers/embedUrl.test.js
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.test.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/index.test.jsx
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/index.test.jsx
Labels: articles-av-epic, articles-features-stream

#4830 ATI Non-JS Tracking
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ATIAnalytics/canonical/index.jsx
  src/app/containers/ATIAnalytics/canonical/index.test.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/article/buildParams.js
  src/app/containers/ATIAnalytics/params/article/buildParams.test.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.js
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.js
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.test.js
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
Labels: simorgh-core-stream

#4898 Revert "ATI Non-JS Tracking"
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ATIAnalytics/canonical/index.jsx
  src/app/containers/ATIAnalytics/canonical/index.test.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/article/buildParams.js
  src/app/containers/ATIAnalytics/params/article/buildParams.test.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.js
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.js
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.test.js
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
Labels: simorgh-core-stream

#4644 Integrate Bulletin component
  cypress/integration/pages/frontPage/tests.js
  data/igbo/frontpage/index.json
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/Bulletin/__snapshots__/index.test.jsx.snap
  src/app/containers/Bulletin/index.jsx
  src/app/containers/Bulletin/index.stories.jsx
  src/app/containers/Bulletin/index.test.jsx
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.jsx
  src/app/containers/StoryPromo/IndexAlsos/index.test.jsx
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/lib/utilities/imageSrcHelpers/locator.js
  src/app/lib/utilities/imageSrcHelpers/locator.test.js
  src/app/lib/utilities/imageSrcHelpers/originCode.js
  src/app/lib/utilities/imageSrcHelpers/originCode.test.js
  src/app/lib/utilities/preprocessor/rules/__snapshots__/filterContentType.test.js.snap
  src/app/lib/utilities/preprocessor/rules/__snapshots__/topstories.test.js.snap
  src/app/lib/utilities/preprocessor/rules/filterContentType.js
  src/app/lib/utilities/preprocessor/rules/filterContentType.test.js
  src/app/models/propTypes/bulletin/index.js
Labels: high priority, ux, ws-frontpage-stream

#4895 Add translations for "Section" to be used by Nav component
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-frontpage-stream

#4894 Enable chartbeat on test and live
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
Labels: simorgh-core-stream

#4878 Update fixture and local/test E2E assets for Bttajk services
  cypress/support/config/services.js
  data/amharic/articles/czqverekrldo.json
  data/burmese/articles/cn0exdy1jzvo.json
  data/japanese/articles/cdd6p3r9g7jo.json
  data/korean/articles/c3mn1lvz65xo.json
  data/thai/articles/c442rl3md0eo.json
  data/tigrinya/articles/ck62z3rjwdeo.json
Labels: articles-features-stream, articles-rollout

#4871 Puppeteer MAP test timeout fix
  cypress/support/config/services.js
  package.json
Labels: simorgh-core-stream

#4880 🎉 Enable Media Player on Live
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
Labels: articles-features-stream

#4903 Enable live e2es for bttajk
  cypress/support/config/services.js
Labels: articles-features-stream, articles-rollout

#4804 Fix for Inline block doesn't render in captions
  data/news/articles/c2054qjjzjdo.json
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/index.jsx
  src/app/containers/Caption/index.test.jsx
  src/app/containers/Paragraph/index.jsx
Labels: articles-av-epic, articles-features-stream

#4904 Fix Bulletin e2e
  cypress/integration/pages/frontPage/tests.js
Labels: high priority, ws-fp-phase3, ws-frontpage-stream

#4907 Fix E2E failing on commit hash
  Jenkinsfile-e2e
Labels: infra-tooling-stream

#4926 Fix e2e default branch to make git ref logic work
  Jenkinsfile-e2e
Labels: infra-tooling-stream, simorgh-core-stream

#4929 Move Related Content to a complementary aside (a11y)
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
Labels: ws-media-stream

#4905 Package Bump to support Nepali numerals.
  package-lock.json
  package.json
  src/app/containers/ArticleTimestamp/timeFormatTests/expectedFormats.json
Labels: articles-features-stream

#4902 Fix sending background events
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/atiUrl/index.test.js
  src/app/containers/ATIAnalytics/beacon/index.test.js
Labels: ws-frontpage-stream

#4931 Bump packages
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
Labels: simorgh-core-stream

#4937 Update PR template as a reminder to add labels & assign project
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ws-media-stream

#4942 Bump dependencies to resolve serialize-javascript vulnerability
  package-lock.json
  package.json
Labels: infra-tooling-stream, simorgh-core-stream

#4927 Add Listen and Watch translations
  src/app/containers/Bulletin/__snapshots__/index.test.jsx.snap
  src/app/containers/Bulletin/index.stories.jsx
  src/app/containers/Bulletin/index.test.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
Labels: ws-frontpage-stream

#4928 Render bulleted-list items directly without the paragraph element
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/BulletedList/__snapshots__/index.test.jsx.snap
  src/app/containers/BulletedList/index.jsx
  src/app/containers/BulletedListItem/__snapshots__/index.test.jsx.snap
  src/app/containers/BulletedListItem/index.jsx
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsText/__snapshots__/index.test.jsx.snap
Labels: ws-media-stream

#4899 Revert "Revert "ATI Non-JS Tracking""
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ATIAnalytics/canonical/index.jsx
  src/app/containers/ATIAnalytics/canonical/index.test.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/article/buildParams.js
  src/app/containers/ATIAnalytics/params/article/buildParams.test.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.js
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.js
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.test.js
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/lib/analyticsUtils/index.js
Labels: simorgh-core-stream

#4936 Bulletin padding tweaks
  data/igbo/frontpage/index.json
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.jsx
  src/app/lib/utilities/preprocessor/rules/__snapshots__/filterContentType.test.js.snap
  src/app/lib/utilities/preprocessor/rules/__snapshots__/topstories.test.js.snap
Labels: ws-frontpage-stream

#4951 Use latest npm version
  .npmrc
  Jenkinsfile
Labels: infra-tooling-stream

#4941 Related content translation for russian and uzbek
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/uzbek.js
Labels: ws-media-stream

#4946 Added new styled grid item for article AV player
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMediaPlayer/index.jsx
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/lib/layoutGrid/index.js
  src/app/lib/layoutGrid/index.test.js
  src/app/lib/styledGrid/__snapshots__/index.test.jsx.snap
  src/app/lib/styledGrid/index.jsx
  src/app/lib/styledGrid/index.stories.jsx
  src/app/lib/styledGrid/index.test.jsx
Labels: articles-av-epic, articles-features-stream, ws-media-stream

#4952 Add a comment about the hidden attribute
  src/app/containers/Navigation/index.jsx
Labels: ws-frontpage-stream

#4938 Improve SEO discoverability for MAPS by including headline
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
Labels: ws-media-stream

#4955 Additional logging of url, path and data
  src/app/routes/getInitialData/index.js
  src/server/index.jsx
Labels: simorgh-core-stream, ws-media-stream

#4909 Improve SEO discoverability for author
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/containers/LinkedData/__snapshots__/index.test.jsx.snap
  src/app/containers/LinkedData/index.test.jsx
Labels: ws-media-stream

#4947 Update Media Player overview
  docs/Media-Player-Guide.md
Labels: articles-av-epic, articles-features-stream, simorgh-core-stream, ws-media-stream

#4953 Propose update to simorgh code owners
  .github/CODEOWNERS
Labels: infra-tooling-stream

#4965 Fix Burmese translations into unicode
  src/app/lib/config/services/burmese.js
Labels: articles-features-stream, articles-rollout

#4933 Improve SEO discoverability of datePublished
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
Labels: ws-media-stream

#4900 Allow live content to be displayed on test / stage environments
  src/server/index.jsx
  src/server/index.test.jsx
Labels: simorgh-core-stream, ws-media-stream

#4939 [DO NOT MERGE] Update MAP design
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/index.jsx
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
Labels: ws-media-stream

#4875 Ability to control the source of data (test or live) for all page types
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/routes/getInitialData/index.js
  src/app/routes/getInitialData/index.test.js
  src/server/index.jsx
Labels: simorgh-core-stream, ws-media-stream

#4872 Change isUK to isNotUK, and update logic to use BBC-Country header
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/App/__snapshots__/App.test.jsx.snap
  src/app/containers/App/index.jsx
  src/app/containers/App/index.test.jsx
  src/app/containers/ConsentBanner/Banner/Text.test.jsx
  src/app/containers/PageHandlers/withContexts.test.jsx
  src/app/contexts/RequestContext/getOriginContext/index.js
  src/app/contexts/RequestContext/getOriginContext/index.test.js
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
  src/app/contexts/RequestContext/isNotEEA/index.js
  src/app/contexts/RequestContext/isNotEEA/index.test.js
  src/app/contexts/RequestContext/isNotUK/index.js
  src/app/contexts/RequestContext/isNotUK/index.test.js
  src/server/Document/component.jsx
  src/server/Document/index.jsx
  src/server/Document/index.test.jsx
  src/server/index.jsx
  src/server/index.test.jsx
  src/server/utilities/constructCspHeader/index.js
  src/server/utilities/constructCspHeader/index.test.js
Labels: simorgh-core-stream

#4979 Add extra logging
  src/app/containers/Navigation/index.jsx
  src/app/contexts/RequestContext/index.jsx
Labels: simorgh-core-stream

#4981 Revert "Add extra logging"
  src/app/containers/Navigation/index.jsx
  src/app/contexts/RequestContext/index.jsx
Labels: simorgh-core-stream

#4969 Update nav translations
  scripts/bundleSizeConfig.js
  src/app/containers/Navigation/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-frontpage-stream

#4966 fix: how we check for updates to package-lock.json in latest
  scripts/dependencyUpdateCheck.sh
Labels: simorgh-core-stream

#4984 Ensure APP_ENV environment variable is reset after each test
  src/app/routes/getInitialData/index.test.js
Labels: ws-media-stream

#4968 Navigation: add unit tests and refactor AMP constants
  src/app/containers/Navigation/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/index.amp.jsx
  src/app/containers/Navigation/index.amp.test.jsx
  src/app/containers/Navigation/index.canonical.jsx
  src/app/containers/Navigation/index.canonical.test.jsx
  src/app/containers/Navigation/index.jsx
  src/app/containers/Navigation/index.test.jsx
  src/app/containers/Navigation/testHelpers.jsx
Labels: ws-frontpage-stream

#4975 Dev Dependency updates
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#4749 Cypress multiple variants tests
  cypress/integration/application/index.js
  cypress/integration/pages/articles/tests.js
  cypress/integration/pages/errorPage404/tests.js
  cypress/integration/pages/frontPage/tests.js
  cypress/integration/pages/mediaAssetPage/tests.js
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  cypress/integration/pages/testsForAllCanonicalPages.js
  cypress/integration/pages/testsForAllPages.js
  cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
  cypress/integration/specialFeatures/cookieBanner/testsForCanonicalOnly.js
  cypress/support/config/services.js
  puppeteer/bundleRequests.test.js
Labels: simorgh-core-stream

#4983 showNavBar refactor
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Header/index.jsx
  src/app/containers/Header/index.test.jsx
Labels: ws-media-stream

#4988 Update code owners
  .github/CODEOWNERS
Labels: infra-tooling-stream, simorgh-core-stream

#4991 Hide test link on MAPs
  puppeteer/rich-text-transforms.test.js
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
Labels: ws-media-stream
