Repository bbc/simorgh, pull requests merged in 2019-06, with the labels that each got.

#1838 Add the start of a simorgh overview doc for new starters
  docs/Simorgh-Overview.md
Labels: simorgh-core-stream

#1843 Fix test:storybook:ci failing on CI
  package.json
Labels: infra-tooling-stream

#1809 Add Lighthouse back to Simorgh to enable local lighthouse testing
  .gitignore
  .travis.yml
  license-exceptions.json
  package-lock.json
  package.json
  scripts/lighthouseBudget.js
  scripts/lighthouseBudget.test.js
Labels: infra-tooling-stream, simorgh-core-stream

#1824 route for explore page
  src/server/index.jsx
  src/server/index.test.jsx
Labels: onward-journeys-stream

#1683 Image srcset
  src/app/containers/Figure/index.jsx
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/helpers/ichefUrl.js
  src/app/containers/Image/helpers/srcSet.js
  src/app/containers/Image/helpers/srcSet.test.js
  src/app/containers/Image/index.jsx
  src/app/containers/Image/index.test.jsx
Labels: articles-current-epic, articles-features-stream

#1841 Fixing lazy-load test as it was being somewhat flakey
  cypress/integration/newsBodySpec.js
Labels: articles-features-stream

#1851 Don't require ID; it's not expected in front pages
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/contexts/RequestContext/index.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#1804 Dynamic font per service
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/lib/__snapshots__/globalStyles.test.js.snap
  src/app/lib/__snapshots__/globalStyles.test.jsx.snap
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/index.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/globalStyles.js
  src/app/lib/globalStyles.jsx
  src/app/lib/globalStyles.test.js
  src/app/lib/globalStyles.test.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#1825 Add condition to the Front Page Section container
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.jsx
  src/app/containers/FrontPageSection/index.test.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#1848 Add default image and alt text to service configs
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
Labels: ws-fp-v1, ws-frontpage-stream

#1839 Remove tag predicates with no tags
  data/test/news/articles/c0000000001o.json
  data/test/news/articles/c0000000002o.json
  data/test/news/articles/c0000000003o.json
  data/test/news/articles/c0000000004o.json
  data/test/news/articles/c0000000005o.json
  data/test/news/articles/c0000000006o.json
  data/test/news/articles/c0000000007o.json
  data/test/news/articles/c0000000009o.json
  data/test/news/articles/c0000000010o.json
  data/test/news/articles/c0000000011o.json
  data/test/news/articles/c0000000012o.json
  data/test/news/articles/c0000000013o.json
  data/test/news/articles/c0000000014o.json
  data/test/news/articles/c0000000015o.json
  data/test/news/articles/c0000000016o.json
  data/test/news/articles/c0000000017o.json
  data/test/news/articles/c0000000018o.json
  data/test/news/articles/c0000000019o.json
  data/test/news/articles/c0000000020o.json
  data/test/news/articles/c0000000021o.json
  data/test/news/articles/c0000000022o.json
  data/test/news/articles/c0000000024o.json
  data/test/persian/articles/c0000000026o.json
  src/app/dataValidator/helpers/validators/validateNode.test.js
Labels: articles-features-stream, low priority

#1844 Update README to aid local development for WS sites
  README.md
Labels: Documentation, ws-frontpage-stream

#1860 Revert "route for explore page"
  src/server/index.jsx
  src/server/index.test.jsx
Labels: onward-journeys-stream

#1854 Manifest images json
  cypress/integration/manifest.js
  public/igbo/images/icons/icon-128x128.png
  public/igbo/images/icons/icon-144x144.png
  public/igbo/images/icons/icon-152x152.png
  public/igbo/images/icons/icon-192x192.png
  public/igbo/images/icons/icon-384x384.png
  public/igbo/images/icons/icon-512x512.png
  public/igbo/images/icons/icon-72x72.png
  public/igbo/images/icons/icon-96x96.png
  public/igbo/manifest.json
  public/pidgin/images/icons/icon-128x128.png
  public/pidgin/images/icons/icon-144x144.png
  public/pidgin/images/icons/icon-152x152.png
  public/pidgin/images/icons/icon-192x192.png
  public/pidgin/images/icons/icon-384x384.png
  public/pidgin/images/icons/icon-512x512.png
  public/pidgin/images/icons/icon-72x72.png
  public/pidgin/images/icons/icon-96x96.png
  public/pidgin/manifest.json
  public/yoruba/images/icons/icon-128x128.png
  public/yoruba/images/icons/icon-144x144.png
  public/yoruba/images/icons/icon-152x152.png
  public/yoruba/images/icons/icon-192x192.png
  public/yoruba/images/icons/icon-384x384.png
  public/yoruba/images/icons/icon-512x512.png
  public/yoruba/images/icons/icon-72x72.png
  public/yoruba/images/icons/icon-96x96.png
  public/yoruba/manifest.json
Labels: ws-fp-v1, ws-frontpage-stream

#1870 Only run Manifest tests for WS locally
  cypress/integration/manifest.js
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#1847 Upgrade cypress 3.3.0
  package-lock.json
  package.json
Labels: simorgh-core-stream

#1877 Persian isnt routed on live yet - manifest
  cypress/integration/manifest.js
Labels: ws-fp-v1, ws-frontpage-stream

#1878 Stop redirection causing flaking unit tests
  src/server/index.jsx
Labels: simorgh-core-stream, ws-fp-v1, ws-frontpage-stream

#1882 Increase lazyload Cypress scroll duration
  cypress/integration/newsBodySpec.js
Labels: blocking, cypress, high priority, simorgh-core-stream

#1858 Pass all required props to RequestContextProvider in FrontPageSection storybook
  src/app/containers/FrontPageSection/index.stories.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#1898 Revert `react-amphtml` `^3.1.1` => `3.0.1` to fix IE11 JS
  package-lock.json
  package.json
Labels: simorgh-core-stream

#1713 Refactor client js to use getRouteProps
  src/client.js
  src/client.test.jsx
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.jsx
Labels: simorgh-core-stream

#1914 Update deepGet to gracefully handle being passed non-object
  package-lock.json
  src/app/helpers/json/deepGet.js
  src/app/helpers/json/deepGet.test.js
Labels: articles-current-epic, articles-features-stream, blocking

#1862 Use psammead timestamp container
  package-lock.json
  package.json
  src/app/containers/ArticleTimestamp/helpers.js
  src/app/containers/ArticleTimestamp/helpers.test.js
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/ArticleTimestamp/index.stories.jsx
  src/app/containers/ArticleTimestamp/index.test.jsx
  src/app/containers/ArticleTimestamp/testHelpers.js
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/containers/Timestamp/__snapshots__/index.test.jsx.snap
  src/app/containers/Timestamp/index.jsx
  src/app/containers/Timestamp/index.stories.jsx
  src/app/containers/Timestamp/index.test.jsx
  src/app/containers/Timestamp/relativeTimestamp.js
  src/app/containers/Timestamp/relativeTimestamp.test.js
  src/app/containers/Timestamp/timestampUtilities.js
  src/app/containers/Timestamp/timestampUtilities.test.js
Labels: ws-fp-v1, ws-frontpage-stream

#1917 deepGet: don't clobber falsy values with null
  src/app/helpers/json/deepGet.js
  src/app/helpers/json/deepGet.test.js
Labels: articles-features-stream, bug, simorgh-core-stream, ws-frontpage-stream

#1888 Add translations for Persian, Igbo, Yoruba and Pidgin cookie banners
  cypress/integration/cookieBannerWS.js
  cypress/support/bodyTestHelper.js
  cypress/support/cookieConfig.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
Labels: articles-current-epic, articles-features-stream, high priority, ws-frontpage-stream

#1938 Wrap World Service cypress tests so only run on local env
  cypress/integration/cookieBannerWS.js
Labels: articles-features-stream, high priority

#1864 LazyLoad if block index is greater than 3
  cypress/integration/newsBodySpec.js
  src/app/containers/Blocks/index.jsx
  src/app/containers/Figure/index.stories.jsx
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/index.jsx
  src/app/containers/Image/index.test.jsx
  src/app/helpers/pageAnchor.js
  src/app/helpers/pageAnchor.test.js
  src/app/lib/utilities/preprocessor/index.js
  src/app/lib/utilities/preprocessor/rules/blockPositioning.js
  src/app/lib/utilities/preprocessor/rules/blockPositioning.test.js
  src/app/models/propTypes/image/index.js
Labels: articles-current-epic, articles-features-stream

#1915 Add new Persian test scenario
  data/schema.yaml
  data/test/persian/articles/c19v65z3lg5o.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
  src/app/models/propTypes/inline/index.js
  src/app/models/propTypes/paragraph/index.js
Labels: articles-features-stream, articles-next-epic

#1946 Immediate patch for cypress:ci failure
  package.json
Labels: infra-tooling-stream

#1944 More robust way of testing lazyloading functionality
  cypress/integration/newsBodySpec.js
  cypress/integration/persianBodySpec.js
Labels: articles-features-stream, high priority

#1869 WS Frontpage - Add visually hidden h1
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/FrontPageMain/index.test.jsx
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#1852 Make footer dynamic
  package-lock.json
  package.json
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/index.jsx
  src/app/containers/Footer/index.stories.jsx
  src/app/containers/Footer/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withPageWrapper.test.jsx.snap
  src/app/containers/PageHandlers/withPageWrapper.test.jsx
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/index.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/yoruba.js
Labels: ws-fp-v1, ws-frontpage-stream

#1927 Log join-us link on the console in production.
  src/app/lib/joinUsTemplate.js
  src/client.js
Labels: Good first issue, simorgh-core-stream, ws-frontpage-stream

#1781 Resolve failing codeclimate reporting
  .travis.yml
  CONTRIBUTING.md
Labels: infra-tooling-stream

#1960 Less concurrency in travis, notifications on push only
  .travis.yml
Labels: infra-tooling-stream

#1941 Tidy files pt. 2
  src/app/containers/Article/index.jsx
  src/app/containers/Caption/index.jsx
  src/app/containers/FrontPage/index.jsx
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/FrontPageSection/index.jsx
  src/app/containers/Image/index.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/PageHandlers/withData.jsx
  src/app/containers/PageViewAnalytics/labelHelpers/article.js
  src/app/containers/PageViewAnalytics/labelHelpers/index.js
  src/app/containers/PageViewAnalytics/labelHelpers/index.test.js
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/containers/Video/index.jsx
  src/app/containers/Video/videoMetadata.js
  src/app/contexts/RequestContext/getOriginContext.test.js
  src/app/helpers/README.md
  src/app/lib/README.md
  src/app/lib/utilities/blockHandlers/index.js
  src/app/lib/utilities/compose/index.js
  src/app/lib/utilities/compose/index.test.js
  src/app/lib/utilities/deepClone/index.js
  src/app/lib/utilities/deepClone/index.test.js
  src/app/lib/utilities/deepGet/index.js
  src/app/lib/utilities/deepGet/index.test.js
  src/app/lib/utilities/idSanitiser/index.js
  src/app/lib/utilities/idSanitiser/index.test.js
  src/app/lib/utilities/onClient/index.js
  src/app/lib/utilities/onClient/index.test.js
  src/app/lib/utilities/pageAnchor/index.js
  src/app/lib/utilities/pageAnchor/index.test.js
  src/app/lib/utilities/preprocessor/index.test.js
  src/app/lib/utilities/preprocessor/rules/blockPositioning.js
  src/app/lib/utilities/preprocessor/rules/blockPositioning.test.js
  src/app/lib/utilities/preprocessor/rules/cpstypes.js
  src/app/lib/utilities/preprocessor/rules/filterEmptyGroupItems.js
  src/app/lib/utilities/preprocessor/rules/timestamp.js
  src/app/lib/utilities/preprocessor/rules/timestamp.test.js
  src/app/lib/utilities/preprocessor/rules/topstories.js
  src/app/routes/getInitialData/article.js
  src/app/routes/getInitialData/article.test.js
  src/app/routes/getInitialData/utils/fetchData.test.js
  src/client.test.jsx
  src/testHelpers/index.js
  src/testHelpers/loggerMock.js
  src/testHelpers/setWindowValue.js
Labels: high priority, simorgh-core-stream

#1962 Run Travis on PRs only if a fork and always fail fast
  .travis.yml
Labels: infra-tooling-stream

#1957 Upgrade Node.js to 10.16.0 & npm to 6.9.0
  .npmrc
  .nvmrc
  Jenkinsfile
  package-lock.json
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
Labels: infra-tooling-stream

#1956 E2e env limits
  cypress/integration/cookieBannerWS.js
  cypress/integration/errorPagePersian.js
  cypress/integration/manifest.js
  cypress/integration/metaPersianSpec.js
  cypress/integration/persianBodySpec.js
  cypress/support/describeForLocalOnly.js
  cypress/support/limitEnvRuns.js
Labels: articles-features-stream, simorgh-core-stream

#1831 Refactor story promo to use existing figure
  src/app/containers/Figure/fixtureData.jsx
  src/app/containers/Figure/index.jsx
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/index.jsx
  src/app/containers/StoryPromo/Figure.jsx
  src/app/containers/StoryPromo/Figure.test.jsx
  src/app/containers/StoryPromo/__snapshots__/Figure.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#1965 Route ws service workers
  cypress/integration/sw.js
  src/app/routes/regex/index.js
  src/app/routes/regex/index.test.js
  src/server/index.jsx
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#1970 Fix SW cypress test
  cypress/integration/sw.js
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#1942 Route manifest.json files per service
  cypress/integration/manifest.js
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/containers/Manifest/index.jsx
  src/app/containers/Manifest/index.test.jsx
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
  src/app/routes/regex/index.js
  src/app/routes/regex/index.test.js
  src/server/index.jsx
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#1651 ATI
  cypress/integration/ampSpec.js
  cypress/integration/atiSpec.js
  cypress/support/bodyTestHelper.js
  cypress/support/config.js
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/containers/ATIAnalytics/ArticleAtiParams.jsx
  src/app/containers/ATIAnalytics/ArticleAtiParams.test.jsx
  src/app/containers/ATIAnalytics/amp/ampAnalyticsJson.js
  src/app/containers/ATIAnalytics/amp/ampAnalyticsJson.test.js
  src/app/containers/ATIAnalytics/amp/index.jsx
  src/app/containers/ATIAnalytics/amp/index.test.jsx
  src/app/containers/ATIAnalytics/atiUrl.js
  src/app/containers/ATIAnalytics/atiUrl.test.js
  src/app/containers/ATIAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ATIAnalytics/canonical/index.jsx
  src/app/containers/ATIAnalytics/canonical/index.test.jsx
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/ArticleMain/index.test.jsx
  src/app/containers/ConsentBanner/Banner/Text.test.jsx
  src/app/containers/ConsentBanner/index.test.jsx
  src/app/containers/FrontPageSection/index.stories.jsx
  src/app/containers/PageViewAnalytics/labelHelpers/index.js
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/Video/__snapshots__/index.test.jsx.snap
  src/app/containers/Video/fixtureData.jsx
  src/app/contexts/RequestContext/__snapshots__/index.test.jsx.snap
  src/app/contexts/RequestContext/getEnv.js
  src/app/contexts/RequestContext/getEnv.test.js
  src/app/contexts/RequestContext/getOriginContext.js
  src/app/contexts/RequestContext/getOriginContext.test.js
  src/app/contexts/RequestContext/getStatsPageIdentifier.js
  src/app/contexts/RequestContext/getStatsPageIdentifier.test.js
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
  src/app/lib/analyticsUtils/article.js
  src/app/lib/analyticsUtils/article.test.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
  src/app/lib/analyticsUtils/sendBeacon.js
  src/app/lib/analyticsUtils/sendBeacon.test.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/index.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
  src/app/models/propTypes/article/index.js
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.jsx
Labels: articles-current-epic, articles-features-stream, high priority, simorgh-core-stream

#1861 Visually displayed copyright lang attribute
  package-lock.json
  src/app/containers/Copyright/__snapshots__/index.test.jsx.snap
  src/app/containers/Copyright/index.jsx
  src/app/containers/Copyright/index.test.jsx
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
Labels: articles-current-epic, articles-features-stream

#1925 New frontpage e2e
  cypress/integration/frontpageAmpSpec.js
  cypress/integration/frontpageLayoutSpec.js
  cypress/support/frontpageElements.js
  cypress/support/worldServices.js
Labels: integration-testing, ws-fp-v1, ws-frontpage-stream

#1953 Pull in new version of @bbc/psammead-copyright
  package-lock.json
  package.json
  src/app/containers/Copyright/__snapshots__/index.test.jsx.snap
  src/app/containers/Copyright/index.jsx
  src/app/containers/Copyright/index.test.jsx
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/index.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
Labels: articles-current-epic, articles-features-stream

#1810 Route WS Frontpages in simorgh
  cypress/integration/frontpageAmpSpec.js
  cypress/integration/frontpageLayoutSpec.js
  cypress/support/frontpageElements.js
  cypress/support/worldServices.js
  src/app/routes/getInitialData/frontpage.js
  src/app/routes/getInitialData/frontpage.test.js
  src/app/routes/index.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#1981 Remove Ross as a code owner in Simorgh
  .github/CODEOWNERS
Labels: simorgh-core-stream

#1994 Make Frontpage E2Es run only locally
  cypress/integration/frontpageLayoutSpec.js
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#1879 adds a preprocessor rule to add IDs to block data
  package.json
  src/app/components/ErrorPage/index.jsx
  src/app/containers/Blocks/index.jsx
  src/app/lib/utilities/deepClone/index.test.js
  src/app/lib/utilities/preprocessor/index.js
  src/app/lib/utilities/preprocessor/rules/addIdsToBlocks.js
  src/app/lib/utilities/preprocessor/rules/addIdsToBlocks.test.js
  src/app/routes/getInitialData/article.js
  src/app/routes/getInitialData/article.test.js
Labels: simorgh-core-stream

#1983 Do fixture data release hop
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/routes/getInitialData/frontpage.js
  src/app/routes/getInitialData/frontpage.test.js
  src/server/index.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#1997 Upload fixture data onto the box for frontpage launch
  scripts/jenkinsProductionFiles.sh
Labels: infra-tooling-stream, ws-fp-v1, ws-frontpage-stream

#1918 Add media indicator to promo
  package-lock.json
  package.json
  src/app/containers/StoryPromo/LinkContents.jsx
  src/app/containers/StoryPromo/LinkContents.test.jsx
  src/app/containers/StoryPromo/MediaIndicator.jsx
  src/app/containers/StoryPromo/MediaIndicator.test.jsx
  src/app/containers/StoryPromo/__snapshots__/LinkContents.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/MediaIndicator.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/utilities/formatDuration.js
  src/app/lib/utilities/formatDuration.test.js
Labels: ws-fp-v1, ws-frontpage-stream

#2028 Increase the bundle entry point size limit
  webpack.config.js
Labels: simorgh-core-stream

#1945 Canonicals are wrong
  cypress/integration/ampSpec.js
  cypress/integration/metaNewsSpec.js
  cypress/integration/metaPersianSpec.js
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
Labels: articles-current-epic, articles-features-stream

#1974 Update storybook
  license-exceptions.json
  package-lock.json
  package.json
Labels: bug, simorgh-core-stream

#1901 Surface articles only on the correct home
  src/app/containers/PageHandlers/__snapshots__/withData.test.jsx.snap
  src/app/containers/PageHandlers/withData.jsx
  src/app/containers/PageHandlers/withData.test.jsx
  src/app/lib/utilities/getPassportHome/index.js
  src/app/lib/utilities/getPassportHome/index.test.js
Labels: articles-current-epic, articles-features-stream

#2024 Add dir attribute to html tag
  cypress/integration/ampSpec.js
  cypress/integration/errorPageNews.js
  cypress/integration/errorPagePersian.js
  cypress/integration/metaNewsSpec.js
  cypress/integration/metaPersianSpec.js
  cypress/support/bodyTestHelper.js
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.jsx
  src/app/components/Metadata/index.test.jsx
  src/app/containers/ErrorMain/index.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
Labels: articles-features-stream, articles-next-epic

#2023 Folderise simorgh app lib
  src/app/lib/globalStyles/__snapshots__/index.test.jsx.snap
  src/app/lib/globalStyles/index.jsx
  src/app/lib/globalStyles/index.test.jsx
  src/app/lib/layoutGrid/index.js
  src/app/lib/layoutGrid/index.test.js
  src/app/lib/styledGrid/__snapshots__/index.test.jsx.snap
  src/app/lib/styledGrid/index.jsx
  src/app/lib/styledGrid/index.stories.jsx
  src/app/lib/styledGrid/index.test.jsx
Labels: articles-features-stream, simorgh-core-stream

#2037 Use tests data on frontpage test
  envConfig/test.env
Labels: ws-fp-v1, ws-frontpage-stream

#2016 Add skip to content target to Front Page
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/FrontPageMain/index.test.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#1988 use srcset in ws fontpages
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/imageSrcHelpers/locator.js
  src/app/containers/StoryPromo/imageSrcHelpers/locator.test.js
  src/app/containers/StoryPromo/imageSrcHelpers/originCode.js
  src/app/containers/StoryPromo/imageSrcHelpers/originCode.test.js
  src/app/containers/StoryPromo/index.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#2041 Temp disable bbc-a11y on Jenkins
  Makefile
  package.json
Labels: infra-tooling-stream

#2038 Change domain endings when running e2e from the UK
  README.md
  cypress.json
  cypress/plugins/index.js
  cypress/support/config.js
  package-lock.json
Labels: infra-tooling-stream

#1884 fix timezone issues in ArticleTimestamp tests
  src/app/containers/ArticleTimestamp/index.test.jsx
  src/app/containers/ArticleTimestamp/testHelpers.js
Labels: articles-features-stream, bug, simorgh-core-stream

#1906 Refactor Metadata Container
  cypress/integration/frontpageAmpSpec.js
  data/prod/igbo/frontpage/index.json
  data/prod/pidgin/frontpage/index.json
  data/prod/yoruba/frontpage/index.json
  data/test/igbo/frontpage/index.json
  data/test/pidgin/frontpage/index.json
  data/test/yoruba/frontpage/index.json
  src/app/components/LinkedData/__snapshots__/index.test.jsx.snap
  src/app/components/LinkedData/index.jsx
  src/app/components/LinkedData/index.test.jsx
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.jsx
  src/app/components/Metadata/index.test.jsx
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/FrontPageMain/index.test.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withData.test.jsx.snap
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/utilities/preprocessor/rules/__snapshots__/cpstypes.test.js.snap
  src/app/lib/utilities/preprocessor/rules/__snapshots__/topstories.test.js.snap
  src/app/models/propTypes/metadata/index.js
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#1982 Make pageType dynamic per route
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/Layouts/defaultPageWrapper.test.jsx
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/PageHandlers/withPageWrapper.test.jsx
  src/app/routes/index.js
Labels: articles-features-stream, ws-fp-v1, ws-frontpage-stream

#2040 Fix proptype warning in story promo
  src/app/containers/StoryPromo/index.jsx
Labels: ws-frontpage-stream

#2031 dependency updates
  package-lock.json
  package.json
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#2045 Increase speed of CI prod tests
  .travis.yml
  cypress/support/index.js
  package-lock.json
  package.json
Labels: infra-tooling-stream

#2017 Fixture data with nested components
  data/README.md
  data/test/news/articles/c0000000029o.json
  dataValidator/helpers/dataLoader/asyncValidateDir.test.js
Labels: articles-current-epic, articles-features-stream

#2068 Use Stage data on live simorgh
  envConfig/live.env
Labels: ws-fp-v1, ws-frontpage-stream

#2000 Integrate top story to front page section
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.jsx
  src/app/containers/StoryPromo/index.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#2069 Remove the unnecessary npm version force in Travis
  .travis.yml
Labels: infra-tooling-stream

#2087 Test response code enhancements
  cypress/README.md
  cypress/integration/ampSpec.js
  cypress/integration/dataSpec.js
  cypress/integration/errorPageNews.js
  cypress/integration/errorPagePersian.js
  cypress/integration/frontpageAmpSpec.js
  cypress/integration/manifest.js
  cypress/integration/sw.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/support/metaTestHelper.js
Labels: integration-testing, simorgh-core-stream

#1989 Add Popout Grid to Timestamp
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withLoading.test.jsx.snap
  src/app/lib/layoutGrid/index.js
  src/app/lib/styledGrid/__snapshots__/index.test.jsx.snap
  src/app/lib/styledGrid/index.jsx
  src/app/lib/styledGrid/index.stories.jsx
  src/app/lib/styledGrid/index.test.jsx
Labels: articles-current-epic, articles-features-stream

#1798 Render video & audio
  README.md
  package-lock.json
  src/app/components/Video/__snapshots__/index.test.jsx.snap
  src/app/components/Video/index.jsx
  src/app/components/Video/index.stories.jsx
  src/app/components/Video/index.test.jsx
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/index.jsx
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/Figure/fixtureData.jsx
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/index.jsx
  src/app/containers/Video/__snapshots__/index.test.jsx.snap
  src/app/containers/Video/fixtureData.jsx
  src/app/containers/Video/helpers/fixtures.js
  src/app/containers/Video/helpers/mediatorUrl.js
  src/app/containers/Video/helpers/mediatorUrl.test.js
  src/app/containers/Video/index.jsx
  src/app/containers/Video/index.stories.jsx
  src/app/containers/Video/index.test.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
  src/app/models/propTypes/index.js
Labels: articles-current-epic, articles-features-stream, high priority

#1876 Update brand container to use latest psammead-brand version
  cypress/integration/frontpageLayoutSpec.js
  package-lock.json
  package.json
  src/app/containers/Brand/__snapshots__/index.test.jsx.snap
  src/app/containers/Brand/index.jsx
  src/app/containers/Brand/index.stories.jsx
  src/app/containers/Brand/index.test.jsx
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/index.jsx
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/index.jsx
  src/app/containers/Header/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withPageWrapper.test.jsx.snap
  src/app/containers/PageHandlers/withPageWrapper.test.jsx
  src/app/containers/Video/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/news.js
Labels: ws-fp-v1, ws-frontpage-stream

#2088 Dont lazyload top story
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.jsx
  src/app/containers/FrontPageSection/index.test.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#2021 Hide 1st section header in WS front pages when width <600px
  package-lock.json
  package.json
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.jsx
  src/app/containers/FrontPageSection/index.test.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#2034 aria-label for external links
  src/app/containers/Figure/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineLink/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineLink/index.jsx
  src/app/containers/InlineLink/index.stories.jsx
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
Labels: a11y, articles-current-epic, articles-features-stream

#2083 Pass locale to psammead timestamp container
  package-lock.json
  package.json
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/ArticleTimestamp/index.stories.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/containers/Video/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
  webpack.config.client.js
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#2121 Rmv status check tests and overwrites the visit() command to test there's not Mozart fallback
  cypress/integration/statusSpec.js
  cypress/support/commands.js
  cypress/support/metaTestHelper.js
Labels: integration-testing, simorgh-core-stream

#2140 Stop e2es of 3rd parties
  .travis.yml
  3rdPartyCypress/cypress.json
  3rdPartyCypress/cypress/fixtures/.keep
  3rdPartyCypress/cypress/integration/errorPageNews.js
  3rdPartyCypress/cypress/plugins/.keep
  3rdPartyCypress/cypress/support/index.js
  cypress/integration/errorPageNews.js
  package.json
Labels: infra-tooling-stream, integration-testing, simorgh-core-stream

#2086 add code standard wiki for simorgh
  docs/Code-Standards.md
  src/app/components/README.md
  src/app/containers/README.md
Labels: Documentation, simorgh-core-stream

#2101 Adds ATI to ws frontpages
  cypress/integration/atiSpec.js
  src/app/containers/ATIAnalytics/ArticleAtiParams.jsx
  src/app/containers/ATIAnalytics/ArticleAtiParams.test.jsx
  src/app/containers/ATIAnalytics/FrontPageAtiParams.jsx
  src/app/containers/ATIAnalytics/FrontPageAtiParams.test.jsx
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.jsx
  src/app/lib/analyticsUtils/article.js
  src/app/lib/analyticsUtils/article.test.js
  src/app/lib/analyticsUtils/frontpage.js
  src/app/lib/analyticsUtils/frontpage.test.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#2146 Rename brand container props
  src/app/containers/Brand/index.jsx
  src/app/containers/Footer/index.jsx
  src/app/containers/Header/index.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#2067 Use new service worker routing
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/containers/ServiceWorker/index.jsx
  src/app/containers/ServiceWorker/index.test.jsx
  src/app/containers/Video/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
  src/client.js
  src/client.test.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#2130 Unit test to Front Page Main
  src/app/containers/FrontPageMain/index.test.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#2134 Stats for Video & Audio
  src/app/components/Video/__snapshots__/index.test.jsx.snap
  src/app/components/Video/helpers/fixtures.js
  src/app/components/Video/index.jsx
  src/app/components/Video/index.stories.jsx
  src/app/components/Video/index.test.jsx
  src/app/containers/Video/index.jsx
  src/app/containers/Video/index.stories.jsx
  src/app/models/propTypes/index.js
Labels: articles-current-epic, articles-features-stream, high priority

#2042 Fix pidgin media indictor issue
  src/app/containers/StoryPromo/MediaIndicator.jsx
  src/app/containers/StoryPromo/MediaIndicator.test.jsx
  src/app/containers/StoryPromo/__snapshots__/MediaIndicator.test.jsx.snap
Labels: ws-fp-v1, ws-frontpage-stream

#2152 remove merge process on PR checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: simorgh-core-stream

#2137 Add Navigation to WS Front Page
  cypress/integration/frontpageLayoutSpec.js
  package-lock.json
  package.json
  src/app/containers/FrontPage/index.stories.jsx
  src/app/containers/Header/index.jsx
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/index.jsx
  src/app/containers/Navigation/index.stories.jsx
  src/app/containers/Navigation/index.test.jsx
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#2104 Eslint package bumps
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2030 Fade Images in Articles
  package-lock.json
  package.json
  src/app/containers/Figure/index.jsx
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/index.jsx
Labels: articles-current-epic, articles-features-stream

#2084 Dependabot PRs - Tranche 1
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2165 Supplement docs and old CR feedback
  3rdPartyCypress/README.md
  3rdPartyCypress/cypress/integration/errorPageNews.js
  cypress/README.md
  cypress/integration/errorPageNews.js
Labels: integration-testing, simorgh-core-stream

#2180 Fix react-amphtml to older working version
  package-lock.json
  package.json
Labels: high priority, simorgh-core-stream

#2179 Update the README with the correct node information
  README.md
Labels: infra-tooling-stream
