Repository bbc/simorgh, pull requests merged in 2019-02, with the labels that each got.

#1231 Set up env vars on app entry
  docs/Developer-Help.md
  src/index.js
  src/server/env/index.js
  src/server/env/index.test.js
  src/server/index.jsx
  src/server/index.test.jsx
  webpack.config.client.js
  webpack.config.js
Labels: alpha-3, high priority, mergeable

#1233 Use dashes in env stamped file names to fix test coverage
  .env
  .env.live
  .env.test
  package.json
  webpack.config.client.js
Labels: bug, mergeable

#1212 Route service worker per env
  cypress/integration/statusSpec.js
  cypress/support/metaTestHelper.js
  src/app/routes/index.js
  src/server/index.jsx
  webpack.config.server.js
Labels: alpha-3, mergeable

#1243 fixes hot module reloading
  webpack.config.client.js
Labels: mergeable

#1206 Logging in application
  .env
  .env.live
  .env.test
  .gitignore
  .storybook/webpack.config.js
  package-lock.json
  package.json
  src/app/containers/Article/index.jsx
  src/app/helpers/logger.node.js
  src/app/helpers/logger.node.test.js
  src/app/helpers/logger.web.js
  src/app/helpers/logger.web.test.js
  src/app/routes/getInitialData/index.js
  src/index.js
  src/server/assets/index.js
  src/server/assets/index.test.js
  src/server/index.jsx
  webpack.config.client.js
  webpack.config.js
Labels: Goal (4th - 8th), high priority, mergeable

#1246 Remove .env switching logic
  .env
  .travis.yml
  Makefile
  README.md
  docs/Developer-Help.md
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  package.json
  src/app/helpers/tests/jest-setup.js
  src/index.js
  src/server/env/index.js
  src/server/env/index.test.js
  src/server/index.test.jsx
  webpack.config.client.js
Labels: alpha-3

#1236 Adding Dynamic Tests
  cypress/integration/newsBodySpec.js
  cypress/integration/persianBodySpec.js
  cypress/support/bodyTestHelper.js
Labels: high priority, integration-testing

#1240 Remove appShell as we dont have one
  package.json
  webpack.config.client.js
Labels: alpha-3

#1287 Bump Snyk due to npm audit alert
  package-lock.json
  package.json
Labels: high priority

#1293 Fix Handlebars vulnerability
  package-lock.json
Labels: alpha-3

#1270 Remove react-universal-app and copy across
  package-lock.json
  package.json
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/App/__snapshots__/App.test.jsx.snap
  src/app/containers/App/__snapshots__/index.test.jsx.snap
  src/app/containers/App/index.jsx
  src/app/containers/App/index.test.jsx
  src/app/helpers/tests/jest-setup.js
  src/app/routes/loadInitialData/__snapshots__/index.test.js.snap
  src/app/routes/loadInitialData/index.js
  src/app/routes/loadInitialData/index.test.js
  src/client.js
  src/client.test.jsx
  src/server/index.jsx
  src/server/index.test.jsx
Labels: alpha-3

#1294 Point live at local and add live assets
  data/prod/news/articles/cpzk9lkk2p7o.json
  data/prod/news/articles/cxvxrj9yvppo.json
  data/prod/persian/articles/c5ml5n7w4m3o.json
  envConfig/live.env
  src/app/dataValidator/helpers/dataLoader/asyncValidateDir.test.js
Labels: alpha-3, high priority

#1285 Minimal service worker
  package-lock.json
  package.json
  public/sw.js
  src/client.js
  src/client.test.jsx
  src/server/index.jsx
  webpack.config.client.js
Labels: Goal (11th-15th), alpha-3

#1286 Adding param application_branch to Jenkins job
  Jenkinsfile
Labels: alpha-3, mergeable

#1307 Whitelist Jest vulnerability
  audit-ci.json
  package.json
Labels: high priority

#1292 Make Cypress Tests Environment Agnostic
  cypress.json
  cypress/integration/ampSpec.js
  cypress/integration/dataSpec.js
  cypress/integration/footerSpec.js
  cypress/integration/headerSpec.js
  cypress/integration/metaNewsSpec.js
  cypress/integration/metaPersianSpec.js
  cypress/integration/newsBodySpec.js
  cypress/integration/persianBodySpec.js
  cypress/plugins/index.js
  cypress/support/config.js
  package.json
Labels: Goal (18th-22nd), alpha-3, high priority

#1296 Remove Oat Wrapper
  package-lock.json
  package.json
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/index.jsx
  src/app/lib/styledGrid.js
Labels: v1.0

#1334 Adding Cypress tests to test the canonical URL
  cypress/integration/metaNewsSpec.js
  cypress/integration/metaPersianSpec.js
  cypress/support/metaTestHelper.js
Labels: integration-testing

#1332 Tidy metadata
  src/app/components/Document/__snapshots__/index.test.jsx.snap
  src/app/components/Document/index.jsx
  src/app/components/Metadata/__snapshots__/index.test.jsx.snap
  src/app/components/Metadata/index.jsx
  src/app/components/Metadata/index.test.jsx
  src/app/components/ResourceHints/__snapshots__/index.test.jsx.snap
  src/app/components/ResourceHints/index.jsx
  src/app/components/ResourceHints/index.test.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/lib/config/services/index.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
Labels: mergeable

#1344 Adding Cypress tests to test the metadata found within the JSON data
  cypress/integration/metaNewsSpec.js
  cypress/support/metaTestHelper.js
Labels: integration-testing

#1333 Restructure document
  package-lock.json
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.jsx
  src/server/Document/component.test.jsx
  src/server/Document/index.jsx
  src/server/index.jsx
  src/server/index.test.jsx
Labels: mergeable

#1353 Adding Cypress tests for Error Page
  cypress/integration/errorPage.js
  cypress/support/config.js
Labels: integration-testing

#1295 Error page
  cypress/integration/errorPage.js
  cypress/support/config.js
  package-lock.json
  package.json
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorPage/index.jsx
  src/app/components/ErrorPage/index.test.jsx
  src/app/components/Timestamp/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/index.jsx
  src/app/containers/ErrorMain/index.stories.jsx
  src/app/containers/ErrorMain/index.test.jsx
  src/app/containers/Timestamp/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
Labels: Goal (25th-1st), alpha-3
