Repository bbc/simorgh, pull requests merged in 2019-11, with the labels that each got.

#4505 Maybe fix pup timeouts
  puppeteer/rich-text-transforms.test.js
Labels: simorgh-core-stream

#4495 Add subheadline converter rule for CPS assets
  data/igbo/cpsAssets/afirika-23252735.json
  data/pidgin/cpsAssets/23248703.json
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/subheadline/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/subheadline/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/utils/helpers.js
Labels: ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4506 Fix MAP non-smoke e2es
  cypress/integration/pages/mediaAssetPage/tests.js
  data/somali/cpsAssets/media-48870869.json
  data/ukrainian/cpsAssets/media-49656852.json
Labels: ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4502 Remove moment stories from chromatic
  src/app/lib/utilities/moment/index.stories.jsx
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream

#4378 Rm react-test-renderer
  package.json
  src/app/containers/ATIAnalytics/canonical/index.test.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ChartbeatAnalytics/__snapshots__/index.test.jsx.snap
  src/app/containers/ChartbeatAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ChartbeatAnalytics/canonical/index.test.jsx
  src/app/containers/ChartbeatAnalytics/index.test.jsx
Labels: simorgh-core-stream

#4512 Fix cypress for MAPs
  cypress/support/config/services.js
Labels: ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4475 Render Useful Links with assetType PRO
  cypress/integration/pages/frontPage/tests.js
  src/app/lib/utilities/preprocessor/rules/filterContentType.js
Labels: high priority, simorgh-core-stream, ws-frontpage-stream

#4466 add polyfills to dev server
  webpack.config.client.js
Labels: simorgh-core-stream

#4388 Integrate Media Player 2.0.2 (with Play Button)
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
Labels: articles-av-epic, articles-features-stream, ux, ws-media-stream

#4424 Refactor MediaPlayer and add CpsAssetMediaPlayer
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMediaPlayer/index.jsx
  src/app/containers/ArticleMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/index.jsx
  src/app/containers/CpsAssetMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/fixtureData.jsx
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.test.jsx
Labels: articles-features-stream, ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4519 Fix MAP e2es
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
Labels: ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4481 Change navigation links from CPS indexes to WS topics
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/yoruba.js
Labels: ws-frontpage-stream

#4516 Dev dependency updates v2
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#4494 Render the CSP Header in Simorgh
  package-lock.json
  package.json
  src/server/index.jsx
  src/server/utilities/constructCspHeader/index.js
  src/server/utilities/constructCspHeader/index.test.js
Labels: infra-tooling-stream, simorgh-core-stream

#4522 remove japanese rugby nav item
  src/app/lib/config/services/japanese.js
Labels: shared-components, simorgh-core-stream

#4513 HMNBSTTGP configs
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
Labels: articles-features-stream, articles-rollout

#4552 Fix Punjabi navigation link
  src/app/lib/config/services/punjabi.js
Labels: high priority, ws-frontpage-stream

#4554 Fix handlebars DoS vuln
  package-lock.json
Labels: simorgh-core-stream

#4515 Navigation translations for simple/traditional scripts
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-frontpage-stream

#4518 Add brand name to ATI page title
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
Labels: ws-media-asset-page-v1, ws-media-stream

#4556 Bump dependencies
  package-lock.json
  package.json
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
Labels: Heracles, dependabot, simorgh-core-stream

#4560 modified local routes for cymru and naidheachdan article pages
  cypress/support/config/services.js
Labels: simorgh-core-stream

#4559 Use latest version of NPM and Node.js
  .npmrc
  .nvmrc
  Jenkinsfile
  Jenkinsfile-e2e
  Jenkinsfile-e2e-local
  Jenkinsfile-e2e-test
Labels: Heracles, infra-tooling-stream, simorgh-core-stream

#4568 Allow branch override on e2e pipelines
  Jenkinsfile-e2e
  Jenkinsfile-e2e-local
  Jenkinsfile-e2e-test
Labels: infra-tooling-stream

#4577 Update bbc-a11y package
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#4352 Add Cypress test to check Media Player is playing after user triggers playback
  cypress/integration/pages/articles/testsForCanonicalOnly.js
Labels: articles-av-epic, articles-features-stream, integration-testing, ws-media-stream

#4503 added routes for 404 and 500 error pages
  cypress/integration/pages/errorPage404/tests.js
  cypress/support/config/envs.js
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/Error/index.jsx
  src/app/routes/getInitialData/utils/getRouteProps/index.js
  src/app/routes/index.js
  src/app/routes/regex/index.js
Labels: shared-components

#4510 Create CPS to Optimo list preprocessor
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/list/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/list/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/paragraph/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/utils/helpers.js
Labels: ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4589 Remove dataValidator directory since it is no longer used
  .eslintrc.js
  README.md
  dataValidator/README.md
  dataValidator/helpers/dataLoader/asyncValidateDir.js
  dataValidator/helpers/dataLoader/readScenario.js
  dataValidator/helpers/dataLoader/readScenario.test.js
  dataValidator/helpers/interpretSchema/getAllSchemas.js
  dataValidator/helpers/interpretSchema/getRefNameList.js
  dataValidator/helpers/interpretSchema/getSchemaByName.js
  dataValidator/helpers/interpretSchema/getSchemaByName.test.js
  dataValidator/helpers/interpretSchema/propertyNeedsValidating.js
  dataValidator/helpers/interpretSchema/propertyNeedsValidating.test.js
  dataValidator/helpers/interpretSchema/referencesSchemaDefinition.js
  dataValidator/helpers/validators/validateData.js
  dataValidator/helpers/validators/validateData.test.js
  dataValidator/helpers/validators/validateEnum.js
  dataValidator/helpers/validators/validateEnum.test.js
  dataValidator/helpers/validators/validateNode.js
  dataValidator/helpers/validators/validateNode.test.js
  dataValidator/helpers/validators/validateOneOf.js
  dataValidator/helpers/validators/validateOneOf.test.js
  dataValidator/helpers/validators/validateRequired.js
  dataValidator/helpers/validators/validateRequired.test.js
  dataValidator/helpers/validators/validateType.js
  dataValidator/helpers/validators/validateType.test.js
  dataValidator/index.js
  dataValidator/index.test.js
  dataValidator/invalidScenario.json
  dataValidator/utilities/countScenarios.js
  dataValidator/utilities/messaging.js
  dataValidator/utilities/messaging.test.js
Labels: shared-components, simorgh-core-stream

#4362 Add `srcset` to Media Player placeholder image(Simorgh)
  package-lock.json
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/index.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.stories.jsx
  src/app/containers/StoryPromo/index.jsx
  src/app/lib/utilities/srcSet/ichefUrl.js
  src/app/lib/utilities/srcSet/index.js
  src/app/lib/utilities/srcSet/index.test.js
  src/app/lib/utilities/srcSet/placeholder.js
  src/app/lib/utilities/srcSet/placeholder.test.js
Labels: articles-av-epic, articles-features-stream

#4584 add most read fixture data
  data/afaanoromoo/mostRead/index.json
  data/afrique/mostRead/index.json
  data/amharic/mostRead/index.json
  data/arabic/mostRead/index.json
  data/azeri/mostRead/index.json
  data/bengali/mostRead/index.json
  data/burmese/mostRead/index.json
  data/gahuza/mostRead/index.json
  data/gujarati/mostRead/index.json
  data/hausa/mostRead/index.json
  data/hindi/mostRead/index.json
  data/igbo/mostRead/index.json
  data/indonesia/mostRead/index.json
  data/japanese/mostRead/index.json
  data/korean/mostRead/index.json
  data/kyrgyz/mostRead/index.json
  data/marathi/mostRead/index.json
  data/mundo/mostRead/index.json
  data/nepali/mostRead/index.json
  data/news/most/read.json
  data/news/mostRead/index.json
  data/pashto/mostRead/index.json
  data/persian/most/read.json
  data/persian/mostRead/index.json
  data/pidgin/most/read.json
  data/pidgin/mostRead/index.json
  data/portuguese/mostRead/index.json
  data/punjabi/mostRead/index.json
  data/russian/mostRead/index.json
  data/serbian/mostRead/cyr.json
  data/serbian/mostRead/lat.json
  data/sinhala/mostRead/index.json
  data/somali/mostRead/index.json
  data/sport/mostRead/index.json
  data/swahili/mostRead/index.json
  data/tamil/mostRead/index.json
  data/telugu/mostRead/index.json
  data/thai/mostRead/index.json
  data/tigrinya/mostRead/index.json
  data/turkce/mostRead/index.json
  data/ukchina/mostRead/simp.json
  data/ukchina/mostRead/trad.json
  data/ukrainian/mostRead/index.json
  data/urdu/mostRead/index.json
  data/uzbek/mostRead/index.json
  data/vietnamese/mostRead/index.json
  data/yoruba/mostRead/index.json
  data/zhongwen/mostRead/simp.json
  data/zhongwen/mostRead/trad.json
Labels: shared-components

#4564 Update fixtures
  data/bengali/articles/c6p3yp5zzmeo.json
  data/gujarati/articles/cr5el5kw591o.json
  data/hindi/articles/c0469479x9xo.json
  data/marathi/articles/cp47g4myxz7o.json
  data/nepali/articles/cl90j9m3mn6o.json
  data/punjabi/articles/c0l79lr39qyo.json
  data/sinhala/articles/c45w255zlexo.json
  data/tamil/articles/cwl08ll3me8o.json
  data/telugu/articles/cq0y4008d4vo.json
Labels: articles-features-stream, articles-rollout

#4563 Refactor ichef builder
  src/app/containers/Image/index.jsx
  src/app/containers/MediaPlayer/index.jsx
  src/app/lib/utilities/ichefURL/index.js
  src/app/lib/utilities/ichefURL/index.test.js
  src/app/lib/utilities/srcSet/index.js
  src/app/lib/utilities/srcSet/index.test.js
Labels: articles-av-epic, articles-features-stream, shared-components

#4550 Respect allowDateStamp in CPS Page
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
Labels: ws-media-asset-page-v2, ws-media-stream

#4591 Disable media amp tests
  cypress/support/helpers/runTestsForPage.js
Labels: ws-media-stream

#4525 Add Cypress test to check Play Button's visibility and duration
  cypress/integration/pages/articles/testsForCanonicalOnly.js
Labels: articles-features-stream, integration-testing

#4581 Add AV Documentation
  docs/Media-Player-Guide.md
Labels: articles-av-epic, articles-features-stream

#4599 Skip cookie banner tests for live radio and MAP AMP pages
  cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
Labels: ws-media-stream

#4598 Remove flakey puppeteer tests 2
  package.json
Labels: simorgh-core-stream

#4592 Add Local route for Most Read json
  src/app/routes/regex/index.js
  src/app/routes/regex/index.test.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: most-read, shared-components

#4601 Disable Chartbeat on test
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
Labels: articles-features-stream, simorgh-core-stream

#4602 Run chartbeat e2e's if the chartbeat app toggle is enabled
  cypress/integration/pages/articles/testsForCanonicalOnly.js
Labels: chartbeat, simorgh-core-stream

#4600 Changing Pidgin Media Page URL in config (in Cypress test)
  cypress/support/config/services.js
Labels: integration-testing, ws-media-asset-page-v1, ws-media-stream

#4632 Run Chartbeat e2es on AMP dependent on toggle
  cypress/integration/pages/articles/testsForAMPOnly.js
Labels: simorgh-core-stream

#4583 Add guidance to Media player(simorgh)
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.jsx
Labels: articles-av-epic, articles-features-stream

#4565 Clean up regex to allow inline link logic
  src/app/containers/InlineLink/index.jsx
  src/app/routes/buildRadioAndTvRoutes/index.js
  src/app/routes/buildRadioAndTvRoutes/index.test.js
  src/app/routes/config/index.js
  src/app/routes/index.js
  src/app/routes/index.test.js
  src/app/routes/regex/index.js
  src/app/routes/regex/index.test.js
  src/app/routes/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/regex/utils/index.js
  src/app/routes/regex/utils/index.test.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: ws-media-asset-page-v1, ws-media-stream, ws-sty-page-v1

#4582 MAP fauxHeadline and visuallyHiddenHeadline logic
  scripts/bundleSizeConfig.js
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/FauxHeadline/__snapshots__/index.test.jsx.snap
  src/app/containers/FauxHeadline/index.jsx
  src/app/containers/FauxHeadline/index.stories.jsx
  src/app/containers/FauxHeadline/index.test.jsx
  src/app/containers/VisuallyHiddenHeadline/__snapshots__/index.test.jsx.snap
  src/app/containers/VisuallyHiddenHeadline/index.jsx
  src/app/containers/VisuallyHiddenHeadline/index.stories.jsx
  src/app/containers/VisuallyHiddenHeadline/index.test.jsx
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addHeadlineBlock/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addHeadlineBlock/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addHeadlineBlock/models/index.js
  src/app/lib/utilities/preprocessor/rules/timestamp.js
  src/app/lib/utilities/preprocessor/rules/timestamp.test.js
Labels: ws-media-asset-page-v1, ws-media-stream

#4578 Live Stream Transformer 🤖
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/version/fixtures.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/version/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/version/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.test.js
Labels: ws-media-asset-page-v2, ws-media-stream

#4639 Swallow AMP same-origin console errors in e2es
  cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
  cypress/support/helpers/runTestsForPage.js
  cypress/support/index.js
Labels: articles-features-stream, simorgh-core-stream, ws-media-stream

#4628 Bump dependencies
  package-lock.json
  package.json
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FauxHeadline/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/Heading/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/lib/utilities/preprocessor/rules/radioPage/addIdsToBlocks.js
Labels: Heracles, dependabot, simorgh-core-stream

#4572 Update convertToOptimoBlocks preprocessor rules to use optimo blocks
  src/app/containers/ArticleFigure/fixtureData.jsx
  src/app/containers/Blocks/index.test.jsx
  src/app/containers/Caption/index.test.jsx
  src/app/containers/FauxHeadline/index.test.jsx
  src/app/containers/Headings/index.test.jsx
  src/app/containers/Image/index.test.jsx
  src/app/containers/MediaPlayer/fixtureData.jsx
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addHeadlineBlock/models/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/image/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/image/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/list/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/subheadline/index.js
  src/app/models/blocks/index.js
  src/app/models/blocks/index.test.js
Labels: ws-media-asset-page-v1, ws-media-stream

#4635 Refactored so that the logger doesn't auto create a dir upon import
  src/app/lib/logger.node.js
  src/app/lib/logger.node.test.js
Labels: infra-tooling-stream

#4637 Add mostRead utility to check if data is fresh and lastUpdated < 60days
  src/app/containers/MostRead/utilities/index.js
  src/app/containers/MostRead/utilities/index.test.js
Labels: most-read, shared-components

#4590 Check that the Guidance message is visible if set to true within ARES
  cypress/integration/pages/articles/testsForCanonicalOnly.js
Labels: articles-av-epic, articles-features-stream, integration-testing

#4656 create GitHub action to run Simorgh CI steps
  .github/workflows/simorgh_ci.yml
Labels: simorgh-core-stream

#4662 Disable fallback checks for local e2es
  cypress/support/commands/index.js
  cypress/support/config/envs.js
Labels: simorgh-core-stream

#4567 Service Variant - Respect the cookie (Client)
  package.json
  src/app/containers/Article/__snapshots__/index.test.jsx.snap
  src/app/containers/Article/index.jsx
  src/app/containers/Article/index.test.jsx
  src/app/containers/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPage/index.jsx
  src/app/containers/FrontPage/index.stories.jsx
  src/app/containers/FrontPage/index.test.jsx
  src/app/containers/PageHandlers/withVariant/getVariantRedirectUrl/index.js
  src/app/containers/PageHandlers/withVariant/getVariantRedirectUrl/index.test.js
  src/app/containers/PageHandlers/withVariant/index.jsx
  src/app/containers/PageHandlers/withVariant/index.test.jsx
  src/app/contexts/UserContext/cookies/index.js
  src/app/contexts/UserContext/cookies/index.test.js
  src/app/lib/utilities/variantHandler/index.js
  src/app/models/propTypes/variants/index.js
Labels: simorgh-core-stream

#4641 Add Streaming Block to MAP
  data/thai/cpsAssets/thailand-23248713.json
  data/uzbek/cpsAssets/sport-23248721.json
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addHeadlineBlock/index.js
Labels: ws-media-asset-page-v2, ws-media-stream

#4649 Ensure Error page regex includes variant as a parameter
  src/app/routes/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/regex/utils/index.js
Labels: Error handling, shared-components, simorgh-core-stream

#4669 Add Related Content to MAP / CPS Page
  data/pidgin/cpsAssets/23248703.json
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
Labels: ws-media-asset-page-v2, ws-media-stream

#4678 Fix MAP E2Es (Live Streams)
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
Labels: ws-media-stream

#4679 Update `handlebars` to fix vulns
  package-lock.json
Labels: articles-features-stream

#4650 Add figure HTML to media player && padding to the bottom of the media player
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  data/news/articles/cjn0qpz3jjvo.json
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.jsx
Labels: articles-av-epic, articles-features-stream, bug

#4682 Revert "Add figure HTML to media player && padding to the bottom of the media player"
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  data/news/articles/cjn0qpz3jjvo.json
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.jsx
Labels: articles-av-epic, articles-features-stream

#4546 Cypress tests multiple variants
  .env
  cypress/integration/application/index.js
  cypress/integration/pages/articles/tests.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  cypress/integration/pages/errorPage404/tests.js
  cypress/integration/pages/frontPage/tests.js
  cypress/integration/pages/testsForAllCanonicalPages.js
  cypress/integration/pages/testsForAllPages.js
  cypress/support/config/services.js
  puppeteer/bundleRequests.test.js
Labels: simorgh-core-stream

#4683 Revert "Cypress tests multiple variants "
  .env
  cypress/integration/application/index.js
  cypress/integration/pages/articles/tests.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  cypress/integration/pages/errorPage404/tests.js
  cypress/integration/pages/frontPage/tests.js
  cypress/integration/pages/testsForAllCanonicalPages.js
  cypress/integration/pages/testsForAllPages.js
  cypress/support/config/services.js
  puppeteer/bundleRequests.test.js
Labels: simorgh-core-stream

#4658 Change Action name
  .github/workflows/simorgh_ci.yml
Labels: simorgh-core-stream

#4702 Enable live e2es for Russian and Kyrgyz
  cypress/support/config/services.js
Labels: articles-features-stream, articles-rollout

#4709 Update codeowners
  .github/CODEOWNERS
Labels: simorgh-core-stream

#4704 Add figure HTML to media player && padding to the bottom of the media player
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  data/news/articles/cjn0qpz3jjvo.json
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.jsx
Labels: articles-av-epic, articles-features-stream

#4721 Disable frontPage tests for naidheachdan and cymrufyw
  cypress/support/config/services.js
Labels: simorgh-core-stream, ws-frontpage-stream

#4705 Bump dependencies
  package-lock.json
  package.json
Labels: dependabot, simorgh-core-stream

#4712 Bump react dependencies
  package.json
Labels: Heracles, dependabot, simorgh-core-stream

#4629 added footer and top nav links test
  cypress/integration/pages/testsForAllPages.js
Labels: simorgh-core-stream

#4729 Bump dependencies
  package-lock.json
  package.json
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
Labels: dependabot, simorgh-core-stream

#4587 Update useful links cypress tests
  cypress/integration/pages/frontPage/tests.js
  src/app/containers/FrontPageSection/UsefulLinks/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/UsefulLinks/index.jsx
  src/app/lib/utilities/preprocessor/rules/filterContentType.js
  src/app/lib/utilities/preprocessor/rules/filterContentType.test.js
Labels: ws-frontpage-stream

#4732 Update handlebars to fix high severity vulns
  package-lock.json
Labels: simorgh-core-stream

#4674 Use BrowserRouter in frontPage Storybook
  src/app/containers/FrontPage/index.stories.jsx
Labels: simorgh-core-stream

#4703 Adjust timestamp helper tests
  src/app/containers/ArticleTimestamp/helpers.test.js
Labels: articles-features-stream, bug

#4728 Map stage env to the test environment
  cypress/support/config/envs.js
  cypress/support/config/services.js
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/Toggle/useToggle.jsx
  src/app/lib/config/toggles/index.js
Labels: infra-tooling-stream

#4726 Refactor imageWithPlaceholder e2e
  cypress/integration/pages/articles/testsForCanonicalOnly.js
Labels: articles-av-epic, articles-features-stream, integration-testing

#4730 CPS Specal Characters
  cypress/integration/pages/mediaAssetPage/tests.js
  data/pidgin/cpsAssets/23248703.json
  scripts/bundleSizeConfig.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/paragraph/helpers.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/paragraph/helpers.test.js
Labels: ws-media-asset-page-v1, ws-media-asset-page-v2, ws-media-stream

#4677 Translations for services
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: articles-features-stream, articles-rollout, shared-components

#4723 Use referrer for chartbeat
  src/app/containers/ChartbeatAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ChartbeatAnalytics/canonical/index.test.jsx
  src/app/containers/ChartbeatAnalytics/index.jsx
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
Labels: articles-features-stream, simorgh-core-stream

#4754 Remove unused var from pipeline files
  Jenkinsfile-e2e
  Jenkinsfile-e2e-local
  Jenkinsfile-e2e-test
Labels: infra-tooling-stream

#4748 StoryPromo: Use Placeholder Image if no image provided
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
Labels: ws-frontpage-stream, ws-media-stream

#4675 chore: use cross-env in npm scripts
  package-lock.json
  package.json
Labels: simorgh-core-stream

#4757 Revert "chore: use cross-env in npm scripts"
  package-lock.json
  package.json
Labels: simorgh-core-stream

#4756 Fix MAP E2Es
  cypress/integration/pages/mediaAssetPage/tests.js
  cypress/support/config/services.js
  data/thai/cpsAssets/23122810.json
  data/thai/cpsAssets/international-49514085.json
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.test.jsx
Labels: ws-media-stream

#4786 Fix CPS Related Content URLs for non-live environments
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
Labels: ws-media-asset-page-v2, ws-media-stream

#4790 added `withVariant` documentation block
  README.md
Labels: simorgh-core-stream

#4787 Readme testing update
  README.md
Labels: simorgh-core-stream

#4793 Prevent Chartbeat Re-initialisation between article navigations
  src/app/containers/ChartbeatAnalytics/canonical/index.jsx
  src/app/containers/ChartbeatAnalytics/canonical/index.test.jsx
Labels: chartbeat, simorgh-core-stream

#4799 Bttajk
  src/app/containers/Metadata/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
Labels: articles-features-stream, articles-rollout

#4741 Fix for AV UX duration
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/StoryPromo/LinkContents/index.jsx
  src/app/containers/StoryPromo/MediaIndicator/index.jsx
  src/app/lib/utilities/formatDuration/index.js
  src/app/lib/utilities/formatDuration/index.test.js
Labels: articles-av-epic, articles-features-stream, ux

#4747 AV: Add "Duration" to durationSpoken text
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.jsx
Labels: articles-av-epic, articles-features-stream

#4630 create most read canonical container
  .storybook/static/data/afaanoromoo/mostRead/index.json
  .storybook/static/data/afrique/mostRead/index.json
  .storybook/static/data/amharic/mostRead/index.json
  .storybook/static/data/arabic/mostRead/index.json
  .storybook/static/data/azeri/mostRead/index.json
  .storybook/static/data/bengali/mostRead/index.json
  .storybook/static/data/burmese/mostRead/index.json
  .storybook/static/data/gahuza/mostRead/index.json
  .storybook/static/data/gujarati/mostRead/index.json
  .storybook/static/data/hausa/mostRead/index.json
  .storybook/static/data/hindi/mostRead/index.json
  .storybook/static/data/igbo/mostRead/index.json
  .storybook/static/data/indonesia/mostRead/index.json
  .storybook/static/data/japanese/mostRead/index.json
  .storybook/static/data/korean/mostRead/index.json
  .storybook/static/data/kyrgyz/mostRead/index.json
  .storybook/static/data/marathi/mostRead/index.json
  .storybook/static/data/mundo/mostRead/index.json
  .storybook/static/data/nepali/mostRead/index.json
  .storybook/static/data/news/mostRead/index.json
  .storybook/static/data/pashto/mostRead/index.json
  .storybook/static/data/persian/mostRead/index.json
  .storybook/static/data/pidgin/mostRead/index.json
  .storybook/static/data/portuguese/mostRead/index.json
  .storybook/static/data/punjabi/mostRead/index.json
  .storybook/static/data/russian/mostRead/index.json
  .storybook/static/data/serbian/mostRead/cyr.json
  .storybook/static/data/serbian/mostRead/lat.json
  .storybook/static/data/sinhala/mostRead/index.json
  .storybook/static/data/somali/mostRead/index.json
  .storybook/static/data/swahili/mostRead/index.json
  .storybook/static/data/tamil/mostRead/index.json
  .storybook/static/data/telugu/mostRead/index.json
  .storybook/static/data/thai/mostRead/index.json
  .storybook/static/data/tigrinya/mostRead/index.json
  .storybook/static/data/turkce/mostRead/index.json
  .storybook/static/data/ukchina/mostRead/simp.json
  .storybook/static/data/ukchina/mostRead/trad.json
  .storybook/static/data/ukrainian/mostRead/index.json
  .storybook/static/data/urdu/mostRead/index.json
  .storybook/static/data/uzbek/mostRead/index.json
  .storybook/static/data/vietnamese/mostRead/index.json
  .storybook/static/data/yoruba/mostRead/index.json
  .storybook/static/data/zhongwen/mostRead/simp.json
  .storybook/static/data/zhongwen/mostRead/trad.json
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/index.jsx
  src/app/containers/MostRead/index.stories.jsx
  src/app/containers/MostRead/index.test.jsx
Labels: most-read, shared-components

#4806 Reduce CPS E2Es
  cypress/support/config/services.js
  data/igbo/cpsAssets/media-23256786.json
  data/yoruba/cpsAssets/media-23256797
Labels: ws-media-stream

#4812 ATI enhancement
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/article/buildParams.test.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.test.js
  src/app/containers/RadioPageMain/index.test.jsx
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
Labels: simorgh-core-stream

#4823 Remove Igbo, Pidgin, Yoruba MAPs from E2E test config
  cypress/support/config/services.js
Labels: ws-media-stream

#4765 Render Numbered List as Bulleted Lists
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsText/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsText/index.jsx
  src/app/containers/CpsText/index.test.jsx
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.test.js
Labels: a11y, a11y-swarm, blocked, ws-media-asset-page-v2, ws-media-stream

#4828 Add JSON extension to yoruba fixture
  data/yoruba/cpsAssets/media-23256797.json
Labels: ws-media-stream

#4715 fix: default variant redirects for amp
  src/server/Document/index.jsx
  src/server/Document/index.test.jsx
  src/server/index.jsx
Labels: simorgh-core-stream

#4809 Update placeholder image URLs for CPS AMP pages
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/media/fixtures.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/media/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/version/fixtures.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/version/index.js
Labels: ws-media-stream
