Repository bbc/simorgh, pull requests merged in 2020-12, with the labels that each got.

#8506 Navigation updates Mundo, Gujarati, Hausa, Japanese and Serbian
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/serbian.js
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team

#8300 Refactoring 3rd party cypress tests
  .github/workflows/simorgh-e2e-tests.yml
  3rdPartyCypress/cypress/integration/dataEndpoints.js
  3rdPartyCypress/cypress/integration/errorPageNews.js
  3rdPartyCypress/cypress/integration/prerollAds/config.js
  3rdPartyCypress/cypress/integration/prerollAds/index.js
  3rdPartyCypress/cypress/integration/worldServiceCoUkRedirect.js
  cypress.json
  cypress/integration/specialFeatures/prerollAds/config.js
  cypress/integration/specialFeatures/prerollAds/index.js
  package.json
Labels: cross-team

#8515 Remove use of Enzyme from the ChartbeatAnalytics container
  src/app/containers/ChartbeatAnalytics/index.test.jsx
Labels: cross-team, ws-engage

#8516 Remove use of Enzyme from the ServiceWorker container
  src/app/containers/ServiceWorker/index.test.jsx
Labels: cross-team, ws-engage

#8517 Remove use of Enzyme from the Manifest container
  src/app/containers/Manifest/index.test.jsx
Labels: cross-team

#8520 Use ARTICLE_PAGE string constant pageType throughout codebase
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/App/App.test.jsx
  src/app/containers/ArticleFigure/fixtureData.jsx
  src/app/containers/ArticleMediaPlayer/index.test.jsx
  src/app/containers/ArticleMetadata/index.test.jsx
  src/app/containers/ChartbeatAnalytics/index.test.jsx
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/containers/ComscoreAnalytics/index.test.jsx
  src/app/containers/ConsentBanner/Banner/Text.test.jsx
  src/app/containers/ConsentBanner/index.stories.jsx
  src/app/containers/ConsentBanner/index.test.jsx
  src/app/containers/CpsMetadata/index.test.jsx
  src/app/containers/FrontPageStoryRows/index.stories.jsx
  src/app/containers/Header/index.jsx
  src/app/containers/Header/index.test.jsx
  src/app/containers/LinkedData/index.test.jsx
  src/app/containers/MediaPlayer/fixtureData.jsx
  src/app/containers/MediaPlayer/index.stories.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/MostRead/index.stories.jsx
  src/app/containers/Navigation/index.test.jsx
  src/app/containers/PageHandlers/withContexts.test.jsx
  src/app/containers/PageHandlers/withPageWrapper/index.test.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/contexts/RequestContext/getStatsPageIdentifier/index.js
  src/app/contexts/RequestContext/getStatsPageIdentifier/index.test.js
  src/app/contexts/RequestContext/index.jsx
  src/app/lib/analyticsUtils/indexPage/index.test.js
  src/app/pages/ArticlePage/index.stories.jsx
  src/app/pages/ArticlePage/index.test.jsx
  src/app/routes/article/getInitialData/index.test.js
Labels: cross-team, ws-engage

#8519 Csr for radio schedules
  data/afrique/bbc_afrique_radio/schedule.json
  data/afrique/bbc_afrique_radio/w172x6djbb3rg44.json
  package-lock.json
  package.json
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/index.test.jsx
Labels: ws-media

#8527 Prevent test report being sent for forks or Simorgh
  .github/workflows/simorgh-unit-tests.yml
Labels: cross-team

#8529 Updates to navigaton for Mundo and four India sites
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team

#8532 Add some api context details to cps asset data fetches
  src/app/routes/cpsAsset/getInitialData/index.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
  src/app/routes/utils/fetchPageData/index.js
Labels: cross-team

#8555 Update CSP headers to add new google adservice country codes
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ads, security

#8556 Decrease primary data timeout
  src/app/lib/utilities/getFetchTimeouts/index.js
  src/app/routes/utils/fetchPageData/index.test.js
Labels: cross-team

#8387 Relocate getUrlHelpers
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MostRead/index.jsx
  src/app/containers/MostRead/index.test.jsx
  src/app/containers/RadioSchedule/index.jsx
  src/app/containers/RadioSchedule/index.stories.jsx
  src/app/lib/utilities/getUrlHelpers/getEmbedUrl/index.js
  src/app/lib/utilities/getUrlHelpers/getEmbedUrl/index.test.js
  src/app/lib/utilities/getUrlHelpers/getMostReadUrls/index.js
  src/app/lib/utilities/getUrlHelpers/getMostReadUrls/index.test.js
  src/app/lib/utilities/getUrlHelpers/getMostWatchedUrl/index.js
  src/app/lib/utilities/getUrlHelpers/getMostWatchedUrl/index.test.js
  src/app/lib/utilities/getUrlHelpers/getRadioSchedulesUrls/index.jsx
  src/app/lib/utilities/getUrlHelpers/getRadioSchedulesUrls/index.test.jsx
  src/app/lib/utilities/getUrlHelpers/getRecommendationsUrl/index.js
  src/app/lib/utilities/getUrlHelpers/getRecommendationsUrl/index.test.js
  src/app/lib/utilities/getUrlHelpers/getSecondaryColumnUrl/index.js
  src/app/lib/utilities/getUrlHelpers/getSecondaryColumnUrl/index.test.js
  src/app/lib/utilities/getUrlHelpers/index.js
  src/app/pages/FrontPage/index.stories.jsx
  src/app/pages/IdxPage/testHelpers/index.jsx
  src/app/pages/LiveRadioPage/LiveRadioPage.jsx
  src/app/pages/MostReadPage/index.stories.jsx
  src/app/pages/OnDemandRadioPage/OnDemandRadioPage.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/OnDemandTvPage.jsx
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
  src/app/routes/mostRead/getInitialData/index.js
  src/app/routes/mostWatched/getInitialData/index.js
  src/app/routes/utils/withRadioSchedule/index.js
Labels: ws-engage

#8557 add aria-labelledby to landmark region
  src/app/containers/RecentAudioEpisodes/index.jsx
  src/app/containers/RecentVideoEpisodes/index.jsx
Labels: ws-media

#8559 Remove empty span from recent audio
  src/app/containers/RecentAudioEpisodes/index.jsx
Labels: ws-media

#8560 Temp remove ads pre-loading
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/Canonical/index.test.jsx
Labels: ads, ws-engage

#8248 Add sameSite & secure attribute to cookies
  src/app/containers/ConsentBanner/CanonicalLogic/index.js
  src/app/contexts/UserContext/cookies/index.js
  src/app/contexts/UserContext/cookies/index.test.js
  src/app/lib/utilities/setCookie/index.jsx
  src/app/lib/utilities/setCookie/index.test.jsx
Labels: cross-team

#8561 Use ReleaseDateTimestamp for recent episodes
  data/pashto/bbc_pashto_radio/w3ct0lz1.json
  data/pashto/bbc_pashto_tv/tv_programmes/w13xttn4.json
  data/somali/bbc_somali_tv/tv_programmes/w13xttqt.json
  src/app/containers/RecentAudioEpisodes/index.jsx
  src/app/routes/onDemandRadio/getInitialData/index.test.js
  src/app/routes/onDemandTV/getInitialData/index.test.js
  src/app/routes/utils/processRecentEpisodes/index.jsx
  src/app/routes/utils/processRecentEpisodes/index.test.jsx
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
Labels: ws-media

#8525 Use FRONT_PAGE string constant pageType throughout codebase
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/ATIAnalytics/params/indexPage/buildParams.test.js
  src/app/containers/Ad/Amp/index.test.jsx
  src/app/containers/Ad/index.test.jsx
  src/app/containers/Bulletin/index.stories.jsx
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/containers/FrontPageStoryRows/index.test.jsx
  src/app/containers/Header/index.jsx
  src/app/containers/Header/index.stories.jsx
  src/app/containers/Header/index.test.jsx
  src/app/containers/ImageWithPlaceholder/fixtureData.jsx
  src/app/containers/IndexPageSection/index.stories.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/MostRead/index.test.jsx
  src/app/containers/Navigation/index.stories.jsx
  src/app/containers/PageHandlers/withContexts.test.jsx
  src/app/containers/RadioSchedule/Canonical/index.test.jsx
  src/app/containers/RadioSchedule/index.stories.jsx
  src/app/containers/RadioSchedule/utilities/testHelpers.jsx
  src/app/contexts/RequestContext/getStatsPageIdentifier/index.js
  src/app/contexts/RequestContext/getStatsPageIdentifier/index.test.js
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
  src/app/lib/analyticsUtils/indexPage/index.js
  src/app/lib/analyticsUtils/indexPage/index.test.js
  src/app/pages/FrontPage/index.stories.jsx
  src/app/pages/FrontPage/index.test.jsx
  src/app/routes/home/getInitialData/index.test.js
  src/app/routes/index.test.jsx
  src/server/index.test.jsx
Labels: cross-team, ws-engage

#8565 Update psammead-brand to latest to fix horizontal scrolling bug
  package-lock.json
  package.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
Labels: bug, cross-team, ws-engage

#8566 bump psammead episode list
  package-lock.json
  package.json
  src/app/containers/RecentVideoEpisodes/index.jsx
Labels: ws-media

#8562 use psammead timestamp in recent audio episodes
  package-lock.json
  package.json
  src/app/containers/RecentAudioEpisodes/index.jsx
  src/app/containers/RecentVideoEpisodes/index.jsx
Labels: a11y, ws-media

#8526 Use MEDIA_PAGE string constant pageType throughout codebase
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/AVPlayer/index.test.jsx
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/containers/Header/index.test.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/OnDemandImage/index.test.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/pages/LiveRadioPage/index.stories.jsx
  src/app/pages/LiveRadioPage/index.test.jsx
  src/app/pages/OnDemandRadioPage/index.stories.jsx
  src/app/pages/OnDemandRadioPage/index.test.jsx
  src/app/pages/OnDemandTvPage/index.stories.jsx
  src/app/pages/OnDemandTvPage/index.test.jsx
  src/app/routes/liveRadio/getInitialData/index.test.js
  src/app/routes/onDemandRadio/getInitialData/index.test.js
  src/app/routes/onDemandTV/getInitialData/index.test.js
  src/server/index.test.jsx
Labels: cross-team, ws-engage

#8460 Bump storybook to patch highlight.js
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  .storybook/webpack.config.js
  package-lock.json
  package.json
  src/app/components/Grid/index.stories.jsx
  src/app/containers/ArticleFigure/index.stories.jsx
  src/app/containers/ArticleTimestamp/index.stories.jsx
  src/app/containers/Brand/index.stories.jsx
  src/app/containers/Bulletin/index.stories.jsx
  src/app/containers/Byline/index.stories.jsx
  src/app/containers/ConsentBanner/index.stories.jsx
  src/app/containers/Copyright/index.stories.jsx
  src/app/containers/CpsAssetMediaPlayer/index.stories.jsx
  src/app/containers/CpsFeaturesAnalysis/index.stories.jsx
  src/app/containers/CpsRecommendations/index.stories.jsx
  src/app/containers/CpsRelatedContent/index.stories.jsx
  src/app/containers/CpsTopStories/index.stories.jsx
  src/app/containers/FauxHeadline/index.stories.jsx
  src/app/containers/Footer/index.stories.jsx
  src/app/containers/FrontPageStoryRows/index.stories.jsx
  src/app/containers/Header/index.stories.jsx
  src/app/containers/Headings/index.stories.jsx
  src/app/containers/Image/index.stories.jsx
  src/app/containers/ImageWithPlaceholder/index.stories.jsx
  src/app/containers/IndexHeading/index.stories.jsx
  src/app/containers/IndexPageSection/index.stories.jsx
  src/app/containers/InlineLink/index.stories.jsx
  src/app/containers/MediaPlayer/index.stories.jsx
  src/app/containers/MostRead/index.stories.jsx
  src/app/containers/MostWatched/index.stories.jsx
  src/app/containers/Navigation/index.stories.jsx
  src/app/containers/RadioSchedule/index.stories.jsx
  src/app/containers/SocialEmbed/index.stories.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/VisuallyHiddenHeadline/index.stories.jsx
  src/app/pages/ArticlePage/index.stories.jsx
  src/app/pages/ErrorPage/index.stories.jsx
  src/app/pages/FeatureIdxPage/index.stories.jsx
  src/app/pages/FrontPage/index.stories.jsx
  src/app/pages/IdxPage/index.stories.jsx
  src/app/pages/LiveRadioPage/index.stories.jsx
  src/app/pages/MediaAssetPage/index.stories.jsx
  src/app/pages/MostReadPage/index.stories.jsx
  src/app/pages/OnDemandRadioPage/index.stories.jsx
  src/app/pages/OnDemandTvPage/index.stories.jsx
  src/app/pages/PhotoGalleryPage/index.stories.jsx
  src/app/pages/StoryPage/index.stories.jsx
Labels: cross-team, security

#8573 Bump storybook and path highlight.js
  package-lock.json
  package.json
Labels: security

#8563 Fix GridPrimaryColumn width on Firefox above 1007px
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: cross-team

#8593 Update CSP list for ads
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ads, security

#8595 add visually hidden comma between title and desc
  src/app/containers/RecentVideoEpisodes/index.jsx
Labels: a11y, ws-media

#8592 move recent episodes out of main landmark element
  src/app/pages/OnDemandRadioPage/OnDemandRadioPage.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/OnDemandTvPage.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
Labels: a11y, ws-media

#8598 bump @bbc/psammead-episode-list
  package-lock.json
  package.json
Labels: ws-media

#8568 Use MOST_WATCHED_PAGE and MOST_READ_PAGE string constant pageType throughout codebase
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/containers/CpsOnwardJourney/index.jsx
  src/app/containers/StoryPromo/utilities/index.js
  src/app/containers/StoryPromo/utilities/index.test.js
  src/app/contexts/RequestContext/index.jsx
  src/app/pages/MostReadPage/index.stories.jsx
  src/app/pages/MostReadPage/index.test.jsx
  src/app/pages/MostWatchedPage/index.test.jsx
  src/app/routes/mostRead/getInitialData/index.test.js
  src/app/routes/mostWatched/getInitialData/index.test.js
Labels: cross-team, ws-engage

#8602 Change Recent TV episodes Timestamp wrapping element
  src/app/containers/RecentVideoEpisodes/index.jsx
Labels: Recent Episodes TV, a11y

#8606 Add more adservice CSP domains
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: security

#8599 Updates to navigaton for Japanese and three Nigerian sites
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/yoruba.js
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
Labels: cross-team

#8604 Recent Episodes Integration Tests
  data/gahuza/bbc_gahuza_radio/w172x7rkcj6v0vz.json
  data/indonesia/bbc_indonesian_radio/w172x6r5000f38s.json
  data/indonesia/bbc_indonesian_radio/w172xh267fpn19l.json
  data/pashto/bbc_pashto_radio/p0340yr4.json
  data/pashto/bbc_pashto_radio/w172x8nvf4bchz5.json
  src/integration/pages/onDemandRadioPage/commonRecentEpisodesTests.js
  src/integration/pages/onDemandRadioPage/crossPlatformTests.js
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
Labels: ws-media

#8512 Remove use of Enzyme from the Image container
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/index.test.jsx
Labels: cross-team, ws-engage

#8603 construct recent episode url in component
  data/zhongwen/bbc_cantonese_radio/p0340tsy.json
  src/app/containers/RecentAudioEpisodes/fixtures.js
  src/app/containers/RecentAudioEpisodes/index.jsx
  src/app/containers/RecentAudioEpisodes/index.test.jsx
  src/app/containers/RecentVideoEpisodes/index.jsx
  src/app/containers/RecentVideoEpisodes/index.test.jsx
  src/app/pages/OnDemandRadioPage/OnDemandRadioPage.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/OnDemandTvPage.jsx
  src/app/routes/onDemandTV/getInitialData/index.js
  src/app/routes/utils/processRecentEpisodes/index.jsx
  src/app/routes/utils/processRecentEpisodes/index.test.jsx
Labels: ws-media

#8610 Add font awesome to the csp allow list
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: security, ws-engage

#8608 Use INDEX_PAGE string constant pageType throughout codebase
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/ATIAnalytics/params/indexPage/buildParams.test.js
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/containers/Header/index.test.jsx
  src/app/containers/StoryPromo/helpers/fixtureData.js
  src/app/contexts/RequestContext/index.jsx
  src/app/lib/analyticsUtils/indexPage/index.js
  src/app/lib/analyticsUtils/indexPage/index.test.js
  src/app/pages/IdxPage/testHelpers/index.jsx
  src/app/routes/idx/getInitialData/index.js
  src/app/routes/idx/getInitialData/index.test.js
Labels: cross-team, ws-engage

#8601 Adds support for promo images from Optimo
  data/kyrgyz/articles/c41p9ll9n0po.json
  src/app/containers/ArticleMetadata/index.jsx
  src/app/containers/ArticleMetadata/index.test.jsx
  src/app/containers/LinkedData/index.jsx
  src/app/models/propTypes/promo/index.js
  src/app/pages/ArticlePage/ArticlePage.jsx
  src/app/pages/ArticlePage/index.test.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: optimo, ws-engage

#8611 Locator changes for radio recent episodes E2Es
  cypress/integration/pages/onDemandRadio/tests.js
  cypress/support/config/settings.js
  data/zhongwen/bbc_cantonese_radio/w172xf3r5x8hw4v.json
  data/zhongwen/bbc_cantonese_radio/w172xn6l7ng41qb.json
Labels: Recent Episodes Radio, cypress, ws-media

#8569 Use string constant pageType for FIX and ERROR pages
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/indexPage/buildParams.test.js
  src/app/containers/Ad/MPU.test.jsx
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/contexts/RequestContext/index.jsx
  src/app/lib/analyticsUtils/indexPage/index.js
  src/app/pages/FeatureIdxPage/index.stories.jsx
  src/app/pages/FeatureIdxPage/index.test.jsx
  src/app/routes/cpsAsset/index.jsx
  src/app/routes/getInitialData.test.jsx
  src/app/routes/index.test.jsx
  src/app/routes/utils/fetchPageData/utils/getRouteProps/index.test.js
Labels: cross-team, ws-engage

#8612 remove enzyme from ArticleFigure tests
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleFigure/index.test.jsx
Labels: cross-team, technical-work

#8613 remove enzyme from ArticleTimestamp tests
  src/app/containers/ArticleTimestamp/index.test.jsx
Labels: cross-team, technical-work
