Repository bbc/simorgh, pull requests merged in 2020-08, with the labels that each got.

#7340 Update social embed translations
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/yoruba.js
Labels: ws-engage

#7369 Update Apple Touch Icon integration test snapshots
  src/integration/pages/articles/news/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/news/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team

#7296 Bump Psammead packages
  package-lock.json
Labels: ws-engage

#7364 Update CSP Header with Comscore links
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: AMP, ads, ws-home

#7386 Integration tests for schedules on live radio
  data/sinhala/bbc_sinhala_radio/liveradio.json
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/index.jsx
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/amharic/amp.test.js
  src/integration/pages/liveRadio/amharic/canonical.test.js
  src/integration/pages/liveRadio/ampTests.js
  src/integration/pages/liveRadio/canonicalTests.js
  src/integration/pages/liveRadio/sinhala/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/sinhala/amp.test.js
  src/integration/pages/liveRadio/sinhala/canonical.test.js
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
Labels: integration-testing, live-radio, radio-schedules

#7395 Update CSP headers
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-engage

#7383 Adjust Recommendations layout for IE11
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/index.jsx
Labels: Recommendations, stories-STYs, ws-engage

#7354 Add legacy ad script with module/nomodule pattern
  src/app/containers/Ad/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/Canonical/index.test.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.test.jsx
Labels: ads, ws-home

#7399 Remove PNGs from public build again to reudce static asset upload time
  Jenkinsfile
Labels: cross-team

#7351 Reduce log output in CI by setting the log level
  .travis.yml
  Jenkinsfile
  buildspecs/buildspec-ci-branch.yml
  codebuild/e2e_buildspec.yml
  src/app/lib/logger.node.test.js
Labels: cross-team

#7376 Adding schedules to bbc_persian_radio and bbc_nepali_radio
  src/app/lib/config/services/nepali.js
  src/app/pages/LiveRadioPage/index.jsx
  src/app/routes/liveRadio/getInitialData/index.js
  src/app/routes/liveRadio/getInitialData/index.test.js
Labels: ws-media

#7350 Making use of new psammead-media-player loading placeholder on MAPs
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/CpsAssetMediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/index.jsx
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/canonicalTests.js
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
Labels: MAP, ws-media

#7353 include pre-processor refactor
  dirAlias.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/__snapshots__/index.test.js.snap
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/ampMetadataExtractor/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/ampMetadataExtractor/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/buildIncludeUrl/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/buildIncludeUrl/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/fetchMarkup/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/fetchMarkup/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/getImageBlock/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/getImageBlock/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/includeClassifier/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/includeClassifier/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/isAmpSupported.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/isAmpSupported.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/utils/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/utils/index.test.js
Labels: stories-STYs, ws-engage

#7392 New function to detect Marketing campign type
  src/app/lib/analyticsUtils/analytics.const.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
Labels: cross-team, ws-engage

#7348 Ukrainian lang override metadata and ATI unit tests
  data/ukrainian/cpsAssets/features-russian-53477115.json
  data/ukrainian/cpsAssets/news-53561143.json
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/Metadata/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/index.test.jsx
  src/app/contexts/ServiceContext/__mocks__/index.jsx
Labels: stories-STYs, ukrainian-STYs, ws-engage

#7396 STY Recommendations UX fixes
  scripts/bundleSizeConfig.js
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/index.jsx
  src/app/containers/CpsRecommendations/index.test.jsx
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: Recommendations, cross-team, stories-STYs, ws-engage

#7428 Updating toggles for more control of radio schedules release
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
  src/app/pages/LiveRadioPage/index.jsx
Labels: ws-media

#7432 Putting Hausa and Korean Radio Schedules live
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
Labels: ws-media

#7431 Add missing recommendations skip link translations
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/turkce.js
Labels: Recommendations, stories-STYs, ws-engage

#7430 Dep updates
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
Labels: cross-team

#7435 Updating liveradio fixtures and schedules
  data/afaanoromoo/bbc_afaanoromoo_radio/liveradio.json
  data/afaanoromoo/bbc_oromo_radio/schedule.json
  data/nepali/bbc_nepali_radio/liveradio.json
  data/nepali/bbc_nepali_radio/schedule.json
Labels: ws-media

#7434 Dep update round 2
  license-exceptions.json
  package-lock.json
  package.json
Labels: dependencies

#7400 Updating Live Radio tests to use test data
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/fixtureData/afrique.json
  src/app/pages/LiveRadioPage/fixtureData/amharic.json
  src/app/pages/LiveRadioPage/fixtureData/gahuza.json
  src/app/pages/LiveRadioPage/fixtureData/indonesia.json
  src/app/pages/LiveRadioPage/index.test.jsx
Labels: ws-media

#7249 Fetch remote toggles on the server, and update on client navigation in App.jsx.
  a11y.js
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  package-lock.json
  package.json
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/App/__snapshots__/App.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/index.stories.jsx
  src/app/containers/Header/index.stories.jsx
  src/app/containers/MostRead/index.stories.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/PageHandlers/withContexts.jsx
  src/app/containers/PageHandlers/withContexts.test.jsx
  src/app/containers/RadioSchedule/index.stories.jsx
  src/app/contexts/ToggleContext/index.jsx
  src/app/contexts/ToggleContext/index.test.jsx
  src/app/hooks/useToggle/README.md
  src/app/hooks/useToggle/index.test.jsx
  src/app/hooks/useToggle/useToggle.test.jsx
  src/app/lib/logger.const.js
  src/app/lib/utilities/getToggles/index.js
  src/app/lib/utilities/getToggles/index.test.js
  src/app/lib/utilities/getToggles/withCache.js
  src/app/lib/utilities/getToggles/withCache.test.js
  src/app/pages/ArticlePage/index.stories.jsx
  src/app/pages/ArticlePage/index.test.jsx
  src/app/pages/FrontPage/index.test.jsx
  src/app/pages/IdxPage/testHelpers/index.jsx
  src/app/pages/LiveRadioPage/index.test.jsx
  src/app/pages/MediaAssetPage/index.stories.jsx
  src/app/pages/MostReadPage/index.test.jsx
  src/app/pages/OnDemandRadioPage/index.test.jsx
  src/app/pages/OnDemandTvPage/index.test.jsx
  src/app/pages/StoryPage/index.test.jsx
  src/app/routes/index.test.jsx
  src/integration/pages/frontPage/crossPlatformTests.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: ads, cross-team, ws-home

#7441 Fixing Persian duration translation
  src/app/lib/config/services/persian.js
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
Labels: ws-media

#7436 Putting radio schedules live on more services
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
  src/app/pages/LiveRadioPage/index.test.jsx
Labels: ws-media

#7352 Assign 'lang="uk"' to STY secondary column components with a language override
  src/app/containers/Footer/index.jsx
  src/app/containers/Footer/index.test.jsx
  src/app/containers/Header/index.jsx
  src/app/containers/Header/index.test.jsx
  src/app/lib/config/services/ukrainian.js
  src/app/pages/StoryPage/index.jsx
  src/app/pages/StoryPage/index.test.jsx
Labels: ukrainian-STYs, ws-engage

#7438 Live Radio Schedule e2es (and some associated query string url parsing)
  cypress/integration/pages/liveRadio/helper.js
  cypress/integration/pages/liveRadio/tests.js
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/testsForCanonicalOnly.js
  cypress/support/config/settings.js
  cypress/support/helpers/getAmpUrl/index.js
  cypress/support/helpers/getAmpUrl/index.test.js
  cypress/support/helpers/getDataUrl/index.js
  cypress/support/helpers/getDataUrl/index.test.js
  cypress/support/helpers/runTestsForPage.js
  src/app/containers/RadioSchedule/utilities/evaluateScheduleData.js
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.js
Labels: cypress, live-radio, radio-schedules, ws-media

#7427 render radio schedule on OD radio pages
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
  src/app/pages/OnDemandRadioPage/fixtureData/korean.json
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/pages/OnDemandRadioPage/index.test.jsx
  src/app/routes/liveRadio/getInitialData/index.js
  src/app/routes/liveRadio/getInitialData/index.test.js
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/utils/getRadioService/index.js
  src/app/routes/utils/getRadioService/index.test.js
  src/app/routes/utils/hasRadioSchedule/index.js
  src/app/routes/utils/hasRadioSchedule/index.test.js
  src/integration/common/index.js
  src/integration/common/radioSchedule.js
  src/integration/pages/liveRadio/canonicalTests.js
  src/integration/pages/liveRadio/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/gahuza/amp.test.js
  src/integration/pages/liveRadio/gahuza/canonical.test.js
  src/integration/pages/onDemandRadioPage/canonicalTests.js
  src/integration/pages/onDemandRadioPage/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/gahuza/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/gahuza/amp.test.js
  src/integration/pages/onDemandRadioPage/gahuza/canonical.test.js
Labels: ws-media

#7448 integration test improvements for schedules
  src/integration/common/radioSchedule.js
  src/integration/pages/liveRadio/ampTests.js
  src/integration/pages/liveRadio/canonicalTests.js
  src/integration/pages/onDemandRadioPage/ampTests.js
  src/integration/pages/onDemandRadioPage/canonicalTests.js
Labels: ws-media

#7443 Add toggling and service config data for most watched component
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
Labels: most-watched, ws-media

#6961 Use AMP Geo to hide AMP ads
  package-lock.json
  package.json
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/index.test.jsx
  src/integration/pages/articles/news/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.jsx
Labels: ads, ws-home

#7433 Simorgh Local Toggle for AMP ads
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Amp/index.test.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.test.jsx
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
Labels: ads, ws-home

#7461 Remove left/right padding from CpsAssetMediaPlayer below 600px
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/index.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: MAP, ux, ws-media

#7463 Remove OD radio tests from canonical/amp gahuza live radio snapshots
  src/integration/pages/liveRadio/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/gahuza/__snapshots__/amp.test.js.snap
Labels: integration-testing

#7466 toggle radio schedule off for these service on OD radio pages
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/tigrinya.js
Labels: ws-media

#7462 Run expired episode tests against recently added Gahuza fixture
  src/integration/pages/onDemandRadioPage/gahuza.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/gahuza.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/gahuza.expired/amp.test.js
  src/integration/pages/onDemandRadioPage/gahuza.expired/canonical.test.js
  src/integration/pages/onDemandRadioPage/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/gahuza/__snapshots__/canonical.test.js.snap
Labels: integration-testing, ws-media

#7446 Remove `ads-debug=true` cookie
  src/app/containers/Ad/Canonical/CanonicalAdBootstrapJs.jsx
  src/app/containers/Ad/Canonical/__snapshots__/CanonicalAdBootstrapJs.test.jsx.snap
Labels: ads, ws-home

#7465 enable radio schedule on OD radio pages
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
Labels: ws-media

#7429 ATI marketing utils
  src/app/lib/analyticsUtils/analytics.const.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
Labels: ws-engage

#7464 Use isMapContent prop to display related content at full width on MAPs
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/index.jsx
Labels: most-watched, ws-media

#7474 Add MAINTAINERS.md file
  MAINTAINERS.md
Labels: Documentation, cross-team

#7471 force version 1.21.0 of prismjs to fix security vulnerability
  package-lock.json
  package.json
Labels: cross-team

#7391 Add Canonical comscore
  cypress/integration/pages/testsForAllCanonicalPages.js
  cypress/support/commands/analytics.js
  excludeFromPublicBuild.txt
  public/static/js/comscore/CHANGELOG.md
  public/static/js/comscore/README.md
  public/static/js/comscore/main-1.0.js
  puppeteer/bundleRequests.test.js
  src/app/containers/ComscoreAnalytics/Amp/index.test.jsx
  src/app/containers/ComscoreAnalytics/Canonical/index.jsx
  src/app/containers/ComscoreAnalytics/Canonical/index.test.jsx
  src/app/containers/ComscoreAnalytics/__snapshots__/index.test.jsx.snap
  src/app/containers/ComscoreAnalytics/index.jsx
  src/app/containers/ComscoreAnalytics/index.test.jsx
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/server/local/index.js
Labels: analytics, ws-home

#7481 Dependency bumps
  package-lock.json
  package.json
Labels: cross-team, dependencies, ws-engage

#7485 Add bbc.com to test CSP connect-src
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ads, ws-home

#7205 Add showAdsBasedOnLocation prop to request Context
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/Canonical/index.test.jsx
  src/app/containers/Ad/index.test.jsx
  src/app/containers/App/App.jsx
  src/app/containers/App/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/PageHandlers/withContexts.jsx
  src/app/containers/PageHandlers/withContexts.test.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
  src/app/pages/FrontPage/FrontPage.jsx
  src/app/pages/FrontPage/index.test.jsx
  src/server/index.jsx
Labels: ads, ws-home

#7487 Checking data exists before rendering schedules
  data/bengali/bbc_bangla_radio/schedule.json
  src/app/pages/LiveRadioPage/LiveRadioPage.jsx
Labels: ws-media

#7455 update dependencies
  package-lock.json
  package.json
  src/app/containers/ArticleFigure/fixtureData.jsx
  src/app/containers/ArticleFigure/index.jsx
  src/app/containers/Blocks/index.jsx
  src/app/containers/Caption/index.jsx
  src/app/containers/ImageWithPlaceholder/fixtureData.jsx
  src/app/containers/MediaPlayer/fixtureData.jsx
  src/app/pages/LiveRadioPage/LiveRadioPage.jsx
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/testHelpers/mockComponents.jsx
Labels: cross-team

#7488 Add static.files.bbci.co.uk to test CSP connect-src
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ads, ws-home

#7493 Taking a little bit of ego out of the codebase
  data/pidgin/cpsAssets/23248703.json
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/fixtureData.json
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
Labels: MAP

#7299 Revert "Revert "Remove hasAds from service configs""
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Canonical/CanonicalAdBootstrapJs.test.jsx
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
  src/app/pages/FrontPage/FrontPage.jsx
  src/app/pages/FrontPage/index.test.jsx
Labels: ads, ws-home

#7491 Putting schedules on remaining services for Live Radio
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
Labels: ws-media

#7490 Enable radio schedule for OD radio for Bengali, Afaan Oromoo, Burmese, Amharic, Nepali, Tigrinya
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/tigrinya.js
Labels: ws-media

#7437 Remove HTTP/insecure Instagram origin from CSP header
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-engage

#7492 [Do Not Merge] Enable fetching of remote toggles on live
  package-lock.json
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
Labels: cross-team, ws-engage

#7458 Fix word wrap issue - Story Promo
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: bug, ws-engage

#7496 Update content expired translation for Afaanoromo
  src/app/lib/config/services/afaanoromoo.js
Labels: ws-media

#7499 Live E2Es for OD Radio schedule services enabled
  cypress/support/config/settings.js
Labels: OD-radio, cypress, ws-media

#7521 pin lodash dep to v4.17.20 because of security vuln in v4.17.19
  package-lock.json
  package.json
Labels: cross-team

#7515 exit in tests script with error code if tests fail
  src/integration/utils/runTests/index.js
Labels: ws-media

#7489 Add doc for rendering Ads
  docs/Rendering-Ads.md
Labels: Documentation, ads, ws-home

#7472 Show placeholder when no legacy block id
  data/persian/legacyAssets/afghanistan/2013/04/130429_l42_vid_afgh_corruption.json
  src/app/containers/MediaPlayer/fixtureData.jsx
  src/app/containers/MediaPlayer/helpers/logMissingMediaId.js
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.test.jsx
Labels: ws-media

#7480 Update Canonical Ads Container to match UX specifications
  package-lock.json
  package.json
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.jsx
  src/app/containers/Ad/utilities/adSlotStyles.js
  src/app/pages/FrontPage/FrontPage.jsx
Labels: ads, high-priority, ux, ws-home

#7525 Add pageType to radio schedules logging
  src/app/routes/home/getInitialData/index.js
  src/app/routes/idx/getInitialData/index.js
  src/app/routes/liveRadio/getInitialData/index.js
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/utils/withRadioSchedule/index.js
Labels: ws-media

#7486 resolve ukrainian in russian secondary column translations and datetime locale
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsTopStories/index.jsx
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/Canonical/index.test.jsx
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/contexts/ServiceContext/index.test.jsx
  src/app/lib/config/services/ukrainian.js
Labels: ukrainian-STYs, ws-engage

#7528 Padding issue for media message
  src/app/containers/MediaPlayer/index.jsx
Labels: ws-media

#7539 Update release info
  cypress/support/config/settings.js
  data/turkce/cpsAssets/haberler-dunya-53818547.json
  docs/Simorgh-Release-Info.md
  scripts/releaseInfo/launchDates.js
Labels: stories-STYs, ws-engage

#7546 fix lint errors & bumps eslint-plugin-react to 7.20.6
  package-lock.json
  package.json
  src/app/containers/CpsFeaturesAnalysis/index.stories.jsx
  src/app/containers/CpsRelatedContent/index.stories.jsx
  src/app/containers/CpsTopStories/index.stories.jsx
  src/app/lib/utilities/episodeAvailability/withMediaError/index.jsx
Labels: cross-team

#7541 Add notes about rendering ads on Windows a11y laptops
  docs/Rendering-Ads.md
Labels: ads, ws-home

#7549 Add translations to service config for Includes
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: includes, stories-STYs, ws-engage

#7523 Don't render ad slots on Opera Mini Extreme mode
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Header/index.jsx
  src/app/containers/Navigation/index.canonical.jsx
  src/app/hooks/useMediaQuery/index.jsx
  src/app/hooks/useMediaQuery/index.test.jsx
  src/app/hooks/useOperaMiniDetection/index.jsx
  src/app/hooks/useOperaMiniDetection/index.test.jsx
Labels: ads, ws-home

#7537 Canonical Ads UX fixes
  src/app/containers/Ad/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/utilities/adSlotStyles.js
  src/app/pages/FrontPage/FrontPage.jsx
Labels: ads, ws-home

#7571 CSP additions for Ads
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ads, ws-home

#7338 Fixing structured data errors on TC2 MAPs
  src/app/containers/MediaPlayer/fixtureData.jsx
  src/app/containers/MediaPlayer/helpers/metadata/index.js
  src/app/containers/MediaPlayer/helpers/metadata/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/legacyMedia/fixtures.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/legacyMedia/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/legacyMedia/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.test.js
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
Labels: ws-media

#7572 Removing memo for live radio
  src/app/routes/liveRadio/index.js
Labels: ws-media

#7574 Ads CSP addition
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ads, ws-home

#7540 Update psammead-media-player version to incorporate media-message changes
  package-lock.json
  package.json
  src/app/lib/utilities/episodeAvailability/ErrorMessage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
Labels: MAP, a11y, ws-media

#7573 Change logging as function does not log missing versionId
  src/app/containers/MediaPlayer/fixtureData.jsx
  src/app/containers/MediaPlayer/helpers/logMissingMediaId/index.js
  src/app/containers/MediaPlayer/helpers/logMissingMediaId/index.test.js
  src/app/containers/MediaPlayer/index.test.jsx
Labels: ws-media

#7484 Added xto field for campagin marketing string
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/atiUrl/index.test.js
  src/app/containers/ATIAnalytics/index.test.jsx
Labels: cross-team

#7570 remove local toggle config for live radio schedules
  package-lock.json
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
  src/app/pages/LiveRadioPage/LiveRadioPage.jsx
  src/app/routes/getInitialData.test.jsx
  src/app/routes/index.test.jsx
  src/app/routes/liveRadio/getInitialData/index.js
  src/app/routes/liveRadio/getInitialData/index.test.js
  src/server/index.jsx
Labels: ws-media

#7501 mock bundle report function. use virtual for files that might not exist
  scripts/bundleSize/__mocks__/pageTypeBundleExtractor.js
  scripts/bundleSize/bundleSize.test.js
  scripts/bundleSize/getBundleData.test.js
  scripts/bundleSize/pageTypeBundleExtractor.test.js
Labels: cross-team

#7596 withMediaError component should run before withData
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/pages/OnDemandTvPage/index.jsx
Labels: ws-media

#7565 Use translations in Include container
  src/app/containers/Include/index.jsx
Labels: high-priority, includes, stories-STYs, ws-engage

#7587 Ads integration test
  src/integration/integrationTestEnvironment.js
  src/integration/pages/frontPage/arabic/canonical.test.js
  src/integration/pages/frontPage/canonicalTests.js
  src/integration/utils/fetchDom.js
  src/integration/utils/fetchDom.test.js
Labels: ads, ws-home

#7569 Most watched component on MAPs
  data/pidgin/mostWatched/index.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/CpsOnwardJourney/index.jsx
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/utilities/processMostRead.js
  src/app/containers/MostWatched/index.jsx
  src/app/containers/MostWatched/index.stories.jsx
  src/app/containers/MostWatched/index.test.jsx
  src/app/containers/StoryPromo/MediaIndicator/index.jsx
  src/app/containers/StoryPromo/MediaIndicator/index.test.jsx
  src/app/lib/config/toggles/README.md
  src/app/lib/logger.const.js
  src/app/lib/utilities/filterPopularStaleData/index.js
  src/app/lib/utilities/filterPopularStaleData/index.test.js
  src/app/lib/utilities/filterPopularStaleData/isDataStale.js
  src/app/lib/utilities/filterPopularStaleData/isDataStale.test.js
  src/app/lib/utilities/getMostWatchedUrl/index.js
  src/app/lib/utilities/getMostWatchedUrl/index.test.js
  src/app/pages/MediaAssetPage/MediaAssetPage.jsx
  src/app/pages/MediaAssetPage/index.test.jsx
  src/app/routes/cpsAsset/getInitialData/index.js
  src/app/routes/cpsAsset/getInitialData/processMostWatched/index.js
  src/app/routes/cpsAsset/getInitialData/processMostWatched/index.test.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.test.js
  src/app/routes/index.test.jsx
  src/app/routes/utils/regex/index.js
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/server/local/constructDataFilePath/index.js
  src/server/local/constructDataFilePath/index.test.js
  src/server/local/index.js
Labels: a11y, most-watched, ws-media

#7599 enables ATI marketing campaign on live
  src/app/containers/ATIAnalytics/atiUrl/index.js
Labels: ws-engage

#7597 Dependency Updates
  package-lock.json
  package.json
Labels: cross-team, dependencies

#7577 update release info for ukrainian story pages
  cypress/support/config/settings.js
  data/ukrainian/cpsAssets/23340963.json
  docs/Simorgh-Release-Info.md
  scripts/releaseInfo/launchDates.js
Labels: ws-engage

#7526 optionally render skip link in oj container
  src/app/containers/CpsOnwardJourney/index.jsx
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/index.jsx
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
Labels: Recommendations, a11y, ws-engage

#7616 Add cypress test to check include scripts load
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
  cypress/support/config/settings.js
Labels: ws-engage

#7620 Enable media player captions
  data/japanese/cpsAssets/53746645.json
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.jsx
  src/app/pages/MediaAssetPage/MediaAssetPage.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/media/fixtures.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/media/index.js
Labels: cross-team, ws-engage

#7631 Fix Cypress Tests - Add vj patterns to acceptable scripts
  cypress/integration/pages/testsForAllCanonicalPages.js
Labels: cross-team

#7617 Update ws/av-embeds endpoints in Cypress
  cypress/integration/pages/articles/helpers.js
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/helper.js
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/helpers.js
  cypress/support/config/envs.js
  cypress/support/helpers/onDemandRadioTv.js
Labels: cypress, ws-media

#7632 Add new fixture data with flourish include and update csp to support …
  data/azeri/cpsAssets/azerbaijan-51876428.json
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-engage

#7635 Remove Obsolete Snapshots
  src/integration/README.md
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
Labels: cross-team

#7637 remove cypress tests covered by integration
  cypress/integration/pages/testsForAllCanonicalPages.js
Labels: cross-team

#7623 Add `media-src` support to CSP and allow https://news.files.bbci.co.uk
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: cross-team

#7586 Delete mediaPlayer toggle
  cypress/integration/pages/articles/tests.js
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  src/app/containers/ArticleMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetMediaPlayer/index.test.jsx
  src/app/containers/MediaPlayer/fixtureData.jsx
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/hooks/useToggle/README.md
  src/app/lib/config/toggles/README.md
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/index.stories.jsx
  src/app/pages/MediaAssetPage/index.test.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.test.jsx
Labels: ws-media

#7611 Delete logMediaPlayerStatus toggle
  src/app/containers/MediaPlayer/helpers/logEmbedSourceStatus/index.js
  src/app/containers/MediaPlayer/helpers/logEmbedSourceStatus/index.test.js
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.test.jsx
Labels: ws-media

#7605 Ensure bbc-a11y command runs against media asset pages
  a11y.js
Labels: ws-media

#7645 Removing logMediaPlayerStatus toggle as it is no longer used
  src/app/lib/config/toggles/README.md
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/const.js
  src/app/lib/config/toggles/liveConfig.js
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
Labels: ws-media

#7638 Comscore update
  src/app/containers/ComscoreAnalytics/Canonical/index.jsx
  src/app/containers/ComscoreAnalytics/Canonical/index.test.jsx
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
Labels: analytics, ws-home

#7636 Allow passing of an image to LinkedData, and get the branded image
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/containers/CpsMetadata/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsMetadata/index.jsx
  src/app/containers/CpsMetadata/index.test.jsx
  src/app/containers/CpsMetadata/utils/getBrandedImage/index.js
  src/app/containers/LinkedData/index.jsx
  src/app/lib/utilities/getBrandedImage/index.js
  src/app/lib/utilities/getBrandedImage/index.test.js
  src/app/pages/MediaAssetPage/MediaAssetPage.jsx
  src/app/pages/MediaAssetPage/index.test.jsx
  src/app/pages/PhotoGalleryPage/PhotoGalleryPage.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/index.test.jsx
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.test.jsx
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team, ws-engage

#7601 Add local data for Most watched for all world services
  data/afaanoromoo/mostWatched/index.json
  data/afrique/mostWatched/index.json
  data/amharic/mostWatched/index.json
  data/arabic/mostWatched/index.json
  data/azeri/mostWatched/index.json
  data/bengali/mostWatched/index.json
  data/burmese/mostWatched/index.json
  data/gahuza/mostWatched/index.json
  data/gujarati/mostWatched/index.json
  data/hausa/mostWatched/index.json
  data/hindi/mostWatched/index.json
  data/igbo/mostWatched/index.json
  data/indonesia/mostWatched/index.json
  data/japanese/mostWatched/index.json
  data/korean/mostWatched/index.json
  data/kyrgyz/mostWatched/index.json
  data/marathi/mostWatched/index.json
  data/mundo/mostWatched/index.json
  data/nepali/mostWatched/index.json
  data/pashto/mostWatched/index.json
  data/persian/mostWatched/index.json
  data/portuguese/mostWatched/index.json
  data/punjabi/mostWatched/index.json
  data/russian/mostWatched/index.json
  data/serbian/mostWatched/cyr.json
  data/serbian/mostWatched/lat.json
  data/sinhala/mostWatched/index.json
  data/somali/mostWatched/index.json
  data/swahili/mostWatched/index.json
  data/tamil/mostWatched/index.json
  data/telugu/mostWatched/index.json
  data/thai/mostWatched/index.json
  data/tigrinya/mostWatched/index.json
  data/turkce/mostWatched/index.json
  data/ukchina/mostWatched/simp.json
  data/ukchina/mostWatched/trad.json
  data/ukrainian/mostWatched/index.json
  data/urdu/mostWatched/index.json
  data/uzbek/mostWatched/index.json
  data/vietnamese/mostWatched/index.json
  data/yoruba/mostWatched/index.json
  data/zhongwen/mostWatched/simp.json
  data/zhongwen/mostWatched/trad.json
Labels: most-watched, ws-media

#7615 Remove local toggle config od radio
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
  src/app/pages/OnDemandRadioPage/OnDemandRadioPage.jsx
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/utils/hasRadioSchedule/index.js
  src/app/routes/utils/hasRadioSchedule/index.test.js
Labels: ws-media

#7646 Remove !important qualifier for audio on AMP
  src/app/pages/LiveRadioPage/LiveRadioPage.jsx
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/OnDemandRadioPage.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
Labels: ws-media

#7581 Polling removed from endpoints on canonical
  a11y.js
  cypress/integration/pages/articles/helpers.js
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/helper.js
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/helpers.js
  cypress/support/config/envs.js
  cypress/support/helpers/onDemandRadioTv.js
  src/app/containers/AVPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/AVPlayer/index.test.jsx
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/LinkedData/__snapshots__/index.test.jsx.snap
  src/app/containers/LinkedData/index.test.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/lib/utilities/getEmbedUrl/index.js
  src/app/lib/utilities/getEmbedUrl/index.test.js
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/index.test.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.test.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/articles/scotland/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: av-embeds, cross-team, smp, ws-media
