Repository bbc/simorgh, pull requests merged in 2020-10, with the labels that each got.

#7947 Most Watched Page E2Es
  cypress/integration/pages/mostWatchedPage/index.js
  cypress/integration/pages/mostWatchedPage/tests.js
  cypress/integration/pages/mostWatchedPage/testsForAMPOnly.js
  cypress/integration/pages/mostWatchedPage/testsForCanonicalOnly.js
  cypress/support/config/settings.js
Labels: cypress, most-watched, ws-media

#7954 Respect renderer_env=live for most watched data
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/lib/utilities/getMostWatchedUrl/index.js
  src/app/lib/utilities/getMostWatchedUrl/index.test.js
  src/app/routes/cpsAsset/getInitialData/index.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.test.js
  src/app/routes/mostWatched/getInitialData/index.js
  src/app/routes/utils/fetchPageData/index.js
  src/app/routes/utils/fetchPageData/index.test.js
Labels: most-watched, ws-media

#7529 Cypress test - Changes to url override adding (future episode check removed)
  cypress/integration/pages/onDemandRadio/index.js
  cypress/integration/pages/onDemandRadio/tests.js
  cypress/integration/pages/onDemandRadio/testsForAMPOnly.js
  cypress/integration/pages/onDemandRadio/testsForCanonicalOnly.js
  cypress/integration/pages/onDemandTV/index.js
  cypress/integration/pages/onDemandTV/tests.js
  cypress/support/config/settings.js
  cypress/support/helpers/onDemandRadioTv.js
  cypress/support/helpers/visitPage.js
Labels: ws-media

#7959 Improve fetchPageData logging capability
  scripts/bundleSize/bundleSizeConfig.js
  src/app/routes/utils/fetchPageData/index.js
  src/app/routes/utils/fetchPageData/index.test.js
Labels: ws-engage

#7825 refactor App.jsx client side routing functionality
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/App/__snapshots__/App.test.jsx.snap
  src/app/containers/App/index.jsx
  src/app/containers/App/index.test.jsx
  src/app/containers/PageHandlers/withLoading/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withLoading/index.jsx
  src/app/containers/PageHandlers/withLoading/index.test.jsx
  src/app/routes/utils/fetchPageData/utils/getRouteProps/index.js
  src/app/routes/utils/fetchPageData/utils/getRouteProps/index.test.js
  src/server/index.jsx
  src/server/index.test.jsx
  src/server/utilities/cspHeader/index.js
Labels: cross-team, ws-media

#7964 Adds more CSP headers for Ads
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ads, cross-team, ws-engage

#7886 Automated tests for Feature Index Pages
  a11y.js
  cypress/support/config/settings.js
  scripts/ampHtmlValidator/index.js
  scripts/ampHtmlValidator/index.test.js
Labels: ws-engage

#7967 Log assetUri in getAdditionalPageData fetches
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
Labels: ws-engage

#7951 Remove debug log statement from server
  src/server/index.jsx
Labels: ws-engage

#7948 Display Android App Install Banner for Arabic
  public/arabic/manifest.json
Labels: ws-engage

#7955 Update Afrique, Arabic and Azeri navigation
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/canonical.test.js.snap
Labels: BAU, ws-engage

#7941 Add Charbeat config values for Feature Index page
  .env
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
Labels: ws-engage

#8022 Update Serbian navigation
  src/app/lib/config/services/serbian.js
Labels: BAU, ws-engage

#8023 Add static.bbci.co.uk to the CSP headers
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-engage

#7950 Display Android App Install Banner for Russian
  public/russian/manifest.json
Labels: ws-engage

#7882 Feature Index integration tests
  src/integration/common/index.js
  src/integration/common/sections.js
  src/integration/common/storyPromo.js
  src/integration/pages/featureIdxPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/afrique/amp.test.js
  src/integration/pages/featureIdxPage/afrique/canonical.test.js
  src/integration/pages/featureIdxPage/ampTests.js
  src/integration/pages/featureIdxPage/canonicalTests.js
  src/integration/pages/featureIdxPage/crossPlatformTests.js
  src/integration/pages/frontPage/crossPlatformTests.js
  src/integration/pages/idxPage/crossPlatformTests.js
Labels: ws-engage

#7949 Display Android App Install Banner for Mundo
  public/mundo/manifest.json
Labels: ws-engage

#7962 Create codeql-analysis.yml for automated code scanning on PRs
  .github/workflows/codeql-analysis.yml
Labels: cross-team

#8021 E2Es on TEST for Most Watched Page Batch 2
  cypress/support/config/settings.js
Labels: cypress, most-watched, ws-media

#7874 Lazyload social embeds
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
  cypress/support/config/settings.js
  data/portuguese/cpsAssets/brasil-54196636.json
  src/app/containers/SocialEmbed/index.jsx
  src/app/containers/SocialEmbed/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/storyPage/canonicalTests.js
  src/integration/pages/storyPage/crossPlatformTests.js
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: performance, ws-engage

#8030 Most Watched Page Live E2Es
  cypress/support/config/settings.js
Labels: cypress, most-watched, ws-media

#8033 Adding Most Watched pages to bbcA11y run
  a11y.js
Labels: ws-media

#8037 Bump Minor and Patch Dependencies
  license-exceptions.json
  package-lock.json
  package.json
Labels: cross-team, dependencies

#8035 Use dot notation for access object key
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
  src/app/containers/SocialEmbed/__snapshots__/index.test.jsx.snap
  src/app/containers/SocialEmbed/index.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: ws-engage

#8032 Fix malformed seo urls
  src/app/contexts/RequestContext/getMetaUrls/index.js
  src/app/contexts/RequestContext/getMetaUrls/index.test.js
Labels: bug, ws-engage

#7960 Flatten sections without straplines into sections with straplines
  data/persian/afghanistan/index.json
  data/urdu/cpsAssets/science-51314202.json
  src/app/containers/IndexPageSection/index.jsx
  src/app/containers/IndexPageSection/index.test.jsx
  src/app/containers/IndexPageSection/utilities/filterAllowedItems.jsx
  src/app/containers/IndexPageSection/utilities/filterAllowedItems.test.jsx
  src/app/containers/IndexPageSection/utilities/storyRowsSplitter.jsx
  src/app/containers/IndexPageSection/utilities/storyRowsSplitter.test.jsx
  src/app/pages/FeatureIdxPage/FeatureIdxPage.jsx
  src/app/pages/FeatureIdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FeatureIdxPage/flattenGroups.js
  src/app/pages/FeatureIdxPage/flattenGroups.test.js
  src/app/pages/FeatureIdxPage/index.test.jsx
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
Labels: ws-engage

#8027 Fix integration tests for page with multiple sections
  data/urdu/cpsAssets/science-51314202.json
  src/integration/pages/featureIdxPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/urdu/amp.test.js
  src/integration/pages/featureIdxPage/urdu/canonical.test.js
Labels: ws-engage

#8019 Implement Ads on FIX pages
  src/app/containers/Ad/MPU.jsx
  src/app/containers/Ad/MPU.test.jsx
  src/app/containers/Ad/__snapshots__/MPU.test.jsx.snap
  src/app/lib/__snapshots__/styles.const.test.js.snap
  src/app/lib/styles.const.js
  src/app/lib/styles.const.test.js
  src/app/pages/FeatureIdxPage/FeatureIdxPage.jsx
  src/app/pages/FeatureIdxPage/index.test.jsx
  src/app/pages/FrontPage/FrontPage.jsx
Labels: feature-index, ws-engage

#8050 add updateMinorPatch script
  package.json
Labels: cross-team

#8048 Enabled live E2Es for Most Watched batch 3
  cypress/support/config/settings.js
Labels: ws-media

#7969 Retry requests on embed endpoint on OD Radio and TV brand pages with 'retryOnStatusCodeFailure: true'
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/testsForCanonicalOnly.js
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  cypress/integration/pages/onDemandRadio/tests.js
  cypress/integration/pages/onDemandTV/tests.js
  cypress/support/commands/application.js
Labels: OD-TV, OD-radio, cross-team, cypress, ws-media

#8055 Delete .env file
  .env
  .gitignore
Labels: cross-team

#8097 Update Hindi nav
  src/app/lib/config/services/hindi.js
Labels: ws-engage

#8059 Always display MPU ads below the first section on FIX Pages
  src/app/pages/FeatureIdxPage/FeatureIdxPage.jsx
  src/app/pages/FeatureIdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FeatureIdxPage/index.test.jsx
Labels: feature-index, ws-engage

#8099 Enabled Most Watched test E2Es Ukchina, Tigrinya, Ukrainian
  cypress/support/config/settings.js
Labels: cypress, most-watched, ws-media

#8061 Enrich all the tweets!
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
  cypress/support/config/settings.js
  data/russian/cpsAssets/features-54391793.json
  src/app/containers/SocialEmbed/enrichTweet.jsx
  src/app/containers/SocialEmbed/enrichTweet.test.jsx
  src/app/containers/SocialEmbed/index.jsx
Labels: high-priority, ws-engage

#8101 Increase promos in first section - Feature Index pages
  src/app/containers/IndexPageSection/utilities/filterAllowedItems.jsx
  src/app/containers/IndexPageSection/utilities/filterAllowedItems.test.jsx
Labels: ws-engage

#8102 Live E2Es Most Watched UKChina Tigrinya Ukrainian
  cypress/support/config/settings.js
Labels: cypress, most-watched, ws-media

#8054 Update ATI for Feature index pages
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/indexPage/buildParams.test.js
  src/app/lib/analyticsUtils/indexPage/index.js
  src/integration/pages/featureIdxPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/canonical.test.js.snap
Labels: ws-engage

#8058 remove the hausa frequencies link from the schedule
  src/app/lib/config/services/hausa.js
Labels: ws-media

#8116 Add US Election to Persian nav
  src/app/lib/config/services/persian.js
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
Labels: ws-engage

#7619 replace service config with iSite toggles config for front page radio schedules
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/testsForCanonicalOnly.js
  cypress/integration/pages/onDemandRadio/testsForCanonicalOnly.js
  cypress/support/helpers/getEmbedUrl.js
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/toggles/README.md
  src/app/pages/FrontPage/FrontPage.jsx
  src/app/routes/home/getInitialData/index.js
  src/app/routes/home/getInitialData/index.test.js
Labels: ws-media

#8060 add 8px more spacing to heading for < 400px wide devices
  src/app/pages/MostWatchedPage/MostWatchedPage.jsx
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
Labels: ws-media

#8117 Reduced Most Watched E2Es, Persian & Amharic remain
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  cypress/support/config/settings.js
Labels: cypress, most-watched, ws-media

#8119 Changed Story Page Twitter Embed test to accept > 2 tweet embeds in view
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
Labels: cross-team, cypress

#8115 Add fallback 'topStoriesTitle' if the top section h2 is empty for the 1st section - Feature Index Page
  src/app/containers/IndexPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexPageSection/index.jsx
  src/app/containers/IndexPageSection/index.test.jsx
  src/app/pages/FeatureIdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/canonical.test.js.snap
Labels: feature-index, ws-engage

#8121 Update isomorphic-fetch and patch selfsigned
  package-lock.json
  package.json
Labels: cross-team, security

#8122 Ensure we use correct prismjs version
  package-lock.json
Labels: security

#7778 E2E test for Ads on STY Page & Front Pages
  cypress/integration/pages/featureIndexPage/testsForAMPOnly.js
  cypress/integration/pages/featureIndexPage/testsForCanonicalOnly.js
  cypress/integration/pages/frontPage/testsForAMPOnly.js
  cypress/integration/pages/frontPage/testsForCanonicalOnly.js
  cypress/integration/pages/storyPage/testsForAMPOnly.js
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
  cypress/support/helpers/adsTests/testsForAMPOnly.js
  cypress/support/helpers/adsTests/testsForCanonicalOnly.js
  data/pashto/cpsAssets/columns-54029178.json
  src/app/lib/config/toggles/README.md
Labels: ws-engage

#8109 [US Election] US election banner integration
  data/arabic/election/us2020/results/oembed.json
  data/hindi/election/us2020/results/oembed.json
  data/mundo/election/us2020/results/oembed.json
  data/persian/election/us2020/results/oembed.json
  data/portuguese/election/us2020/results/oembed.json
  data/russian/election/us2020/results/oembed.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/components/FrontPageSection/index.jsx
  src/app/containers/USElectionBanner/__snapshots__/index.test.jsx.snap
  src/app/containers/USElectionBanner/index.jsx
  src/app/containers/USElectionBanner/index.test.jsx
  src/app/pages/FrontPage/FrontPage.jsx
  src/app/routes/home/getInitialData/index.js
  src/app/routes/home/getInitialData/index.test.js
  src/server/local/index.js
  src/server/local/index.test.js
Labels: ws-engage

#8179 fix idt2 include test following idt2 republish
  data/gahuza/cpsAssets/23313911.json
  src/integration/pages/storyPage/ampIncludeTests.js
  src/integration/pages/storyPage/canonicalIncludeTests.js
  src/integration/pages/storyPage/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/gahuza/__snapshots__/canonical.test.js.snap
Labels: cross-team

#8120 Introduce Upstream fetch timeouts
  src/app/lib/utilities/getFetchTimeouts/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/fetchMarkup/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/fetchMarkup/index.test.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
  src/app/routes/utils/fetchPageData/index.js
  src/app/routes/utils/fetchPageData/index.test.js
Labels: cross-team, technical-work

#8178 [US Election] Do not render banner when on AMP
  src/app/containers/USElectionBanner/index.jsx
  src/app/containers/USElectionBanner/index.test.jsx
Labels: ws-engage

#8177 Include web-vitals package
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  package-lock.json
  package.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/containers/WebVitals/index.jsx
  src/app/containers/WebVitals/index.test.jsx
Labels: cross-team, performance

#8185 Update CSP list for web-vitals monitoring
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-engage

#8181 Emotion - Fix e2es
  cypress/integration/pages/articles/tests.js
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  cypress/integration/pages/errorPage404/tests.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  cypress/integration/pages/mostWatchedPage/tests.js
  cypress/integration/pages/onDemandRadio/tests.js
  cypress/integration/pages/testsForAllPages.js
  cypress/integration/specialFeatures/utilities/scriptSwitchingJourneyActions/index.js
  src/app/components/ErrorMain/index.jsx
  src/app/containers/CpsRecommendations/RecommendationsPromo/index.jsx
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/index.jsx
  src/app/containers/OnDemandImage/index.jsx
Labels: cross-team, technical-work

#8188 Somali nav change to remove TC2 FIX link
  src/app/lib/config/services/somali.js
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
Labels: ws-engage

#8190 Emotion Unit Test Updates - Pages Directory
  src/app/pages/OnDemandTvPage/index.test.jsx
Labels: cross-team, technical-work

#8193 Emotion unit test fixes - lib snapshots (excl grid)
  src/app/lib/utilities/episodeAvailability/ErrorMessage/__snapshots__/index.test.jsx.snap
Labels: cross-team, technical-work

#8189 Emotion unit test fixes - Containers (with some snapshots)
  src/app/containers/Ad/Amp/__snapshots__/AdSlot.test.jsx.snap
  src/app/containers/Ad/__snapshots__/MPU.test.jsx.snap
  src/app/containers/BulletedListItem/__snapshots__/index.test.jsx.snap
  src/app/containers/ComscoreAnalytics/__snapshots__/index.test.jsx.snap
  src/app/containers/ConsentBanner/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsFeaturesAnalysis/index.test.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/containers/CpsTopStories/index.test.jsx
  src/app/containers/Fragment/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/amp/__snapshots__/Idt2Amp.test.jsx.snap
  src/app/containers/IndexHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexPageSection/index.test.jsx
  src/app/containers/InlineLink/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/Canonical/__snapshots__/LastUpdated.test.jsx.snap
  src/app/containers/MostRead/section.test.jsx
  src/app/containers/OnDemandHeading/index.test.jsx
  src/app/containers/OnDemandParagraph/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withData/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withError/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withPageWrapper/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/LinkContents/__snapshots__/index.test.jsx.snap
  src/app/containers/VisuallyHiddenHeadline/__snapshots__/index.test.jsx.snap
Labels: cross-team, technical-work

#8191 Emotion SSR tests
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.test.jsx
  src/server/Document/index.test.jsx
Labels: cross-team, technical-work

#8192 Override sampleRate with toggles value
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/containers/WebVitals/index.jsx
  src/app/containers/WebVitals/index.test.jsx
Labels: ws-engage

#8173 Remove top stories check in E2E ads tests
  cypress/support/helpers/adsTests/testsForCanonicalOnly.js
Labels: ws-engage

#8198 Int tests flag only run tests
  package.json
  src/integration/README.md
  src/integration/utils/runTests/index.js
Labels: cross-team

#8183 Cypress test for the US Election Banner on the Front Page
  cypress/integration/pages/frontPage/testsForCanonicalOnly.js
  cypress/support/config/settings.js
  src/app/containers/USElectionBanner/__snapshots__/index.test.jsx.snap
  src/app/containers/USElectionBanner/index.jsx
Labels: cypress, ws-engage, ws-front-page-layout

#8196 Add GH Actions for unit and integration tests
  .github/workflows/cancel-previous-runs.yml
  .github/workflows/simorgh-e2e-tests.yml
  .github/workflows/simorgh-integration-tests.yml
  .github/workflows/simorgh-misc-checks.yml
  .github/workflows/simorgh-unit-tests.yml
Labels: technical-work

#8186 Loosen the regex for TC2 legacy assets
  src/app/routes/index.js
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
  src/server/index.jsx
  src/server/local/constructDataFilePath/index.js
  src/server/local/constructDataFilePath/index.test.js
  src/server/local/index.js
  src/server/local/index.test.js
Labels: cross-team

#8195 Update bengali nav to add us election
  src/app/lib/config/services/bengali.js
Labels: cross-team

#8245 Remove travis config and travis build badge
  .travis.yml
  README.md
Labels: cross-team

#8246 Fix most-watched .json path within routes unit tests
  src/app/routes/cpsAsset/getInitialData/index.test.js
  src/app/routes/index.test.jsx
Labels: cross-team

#8244 Emotion – Server tests
  src/server/index.test.jsx
Labels: cross-team, technical-work

#8249 Resolve 404 issue for assets ending in 'amp'
  src/app/routes/utils/fetchPageData/index.js
  src/app/routes/utils/fetchPageData/index.test.js
  src/app/routes/utils/fetchPageData/utils/getUrl/index.js
  src/app/routes/utils/fetchPageData/utils/getUrl/index.test.js
Labels: cross-team

#8252 Update integration test because IDT2 include has been updated
  src/integration/pages/storyPage/canonicalIncludeTests.js
  src/integration/pages/storyPage/gahuza/__snapshots__/canonical.test.js.snap
Labels: ws-engage

#8255 Emotion - Resolve failing AMP validation
  src/app/containers/App/App.jsx
  src/server/Document/component.jsx
  src/server/Document/index.jsx
Labels: cross-team, technical-work

#8251 update nav for Pashto, Persian, Brasil,Turkce, Ukrainian and Uzbek
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/uzbek.js
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
Labels: ws-engage

#8175 Enable E2Es for FIX pages on Test & Live
  cypress/support/config/settings.js
Labels: ws-engage

#8256 [PKG Bump] Update the web-vitals package
  package-lock.json
  package.json
Labels: cross-team

#8199 add missing IDT2 font csp directives
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: bug, ws-engage

#8259 Add new static.files domain used for elctions and other static assets…
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-engage

#8263 fix grid wrapper's width not filling 100%
  src/app/components/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/components/Grid/index.jsx
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsOnwardJourney/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withLoading/__snapshots__/index.test.jsx.snap
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/LiveRadioPage.jsx
  src/app/pages/MediaAssetPage/MediaAssetPage.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/OnDemandRadioPage.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
Labels: cross-team

#8264 use flex grow in defaultPageWrapper instead of every page component
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/components/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorMain/index.jsx
  src/app/components/PageLayout/IndexMain.jsx
  src/app/lib/utilities/darkMode/index.jsx
  src/app/pages/ArticlePage/ArticlePage.jsx
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/LiveRadioPage.jsx
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/OnDemandRadioPage.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/OnDemandTvPage.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/PhotoGalleryPage.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.jsx
Labels: cross-team

#8266 Revert "use % unit instead of vh"
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.jsx
Labels: cross-team

#8268 Chromatic actions
  .github/workflows/simorgh-misc-checks.yml
Labels: cross-team

#8267 Add action to run amp validation
  .github/workflows/simorgh-amp-a11y-validation.yml
Labels: cross-team

#8270 More action stuff
  .github/workflows/simorgh-amp-lighthouse-a11y-tests.yml
  .github/workflows/simorgh-misc-checks.yml
Labels: cross-team

#8262 update hindi contact link
  src/app/lib/config/services/hindi.js
Labels: ws-engage

#8271 Run Cypress 3rd party tests via GitHub actions
  .github/workflows/simorgh-e2e-tests.yml
Labels: cross-team

#8273 Update the Simorgh News nav
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/news.js
  src/integration/pages/articles/news/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/news/__snapshots__/canonical.test.js.snap
Labels: ws-engage

#8265 Emotion - layout fixes following testing
  src/app/containers/CpsOnwardJourney/index.jsx
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/FauxHeadline/index.jsx
  src/app/containers/MostWatched/index.jsx
  src/app/containers/OnDemandHeading/StyledRadioHeadingContainer.jsx
  src/app/pages/MediaAssetPage/MediaAssetPage.jsx
  src/app/pages/PhotoGalleryPage/PhotoGalleryPage.jsx
  src/app/pages/StoryPage/StoryPage.jsx
Labels: cross-team

#8278 Remove erroneous IncludeGrid component
  src/app/containers/Include/amp/VjAmp.jsx
  src/app/containers/Include/amp/__snapshots__/VjAmp.test.jsx.snap
Labels: bug, ws-engage
