Repository bbc/simorgh, pull requests merged in 2020-09, with the labels that each got.

#7698 Add csp headers for iFrame on canonical media pages
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-media

#7649 Use the ImagePlaceholder component on OnDemand radio
  src/app/containers/ImageWithPlaceholder/__snapshots__/index.test.jsx.snap
  src/app/containers/ImageWithPlaceholder/index.jsx
  src/app/containers/OnDemandImage/__snapshots__/index.test.jsx.snap
  src/app/containers/OnDemandImage/index.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
Labels: OD-radio, cross-team, ws-media

#7703 Updating integration snapshots
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
Labels: ws-media

#7686 bump psammead dependencies
  package-lock.json
  package.json
Labels: cross-team, dependencies, ws-engage

#7702 Update OD TV bundle test var
  scripts/bundleSize/getBundleData.test.js
Labels: ws-media

#7701 Rename mostWatched toggle to mostPopularMedia and change value type to number
  src/app/routes/cpsAsset/getInitialData/processMostWatched/index.js
  src/app/routes/cpsAsset/getInitialData/processMostWatched/index.test.js
Labels: most-watched, ws-media

#7693 toggles using fixtures and alias
  .gitignore
  cypress/README.md
  cypress/support/commands/index.js
  cypress/support/commands/toggles.js
  cypress/support/config/envs.js
Labels: cross-team

#7712 handle test error and exit with code 1 to fail CI
  src/integration/utils/runTests/index.js
Labels: cross-team

#7582 STY Ads
  scripts/bundleSize/bundleSizeConfig.js
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.test.jsx
  src/app/routes/cpsAsset/getInitialData/addMpuBlock/index.js
  src/app/routes/cpsAsset/getInitialData/addMpuBlock/index.test.js
  src/app/routes/cpsAsset/getInitialData/helpers/index.js
  src/app/routes/cpsAsset/getInitialData/index.js
  src/integration/pages/storyPage/canonicalTests.js
  src/integration/pages/storyPage/mundo/canonical.test.js
Labels: POC, ads, ws-engage

#7588 Africa Eye programme fixture data
  data/worldservice/tv/africa_eye/p06sypsq.json
  data/worldservice/tv/africa_eye/p0704qym.json
  data/worldservice/tv/africa_eye/p0706n42.json
  data/worldservice/tv/africa_eye/p07073qv.json
  data/worldservice/tv/africa_eye/p070751x.json
  data/worldservice/tv/africa_eye/p0707w39.json
  data/worldservice/tv/africa_eye/p079x0ql.json
  data/worldservice/tv/africa_eye/p07b12ql.json
  data/worldservice/tv/africa_eye/p07b7j6m.json
  data/worldservice/tv/africa_eye/p07gc1xd.json
  data/worldservice/tv/africa_eye/p07gc458.json
  data/worldservice/tv/africa_eye/p07grf73.json
  data/worldservice/tv/africa_eye/p07qtpbc.json
  data/worldservice/tv/africa_eye/p07v3ydx.json
  data/worldservice/tv/africa_eye/p080cd6z.json
  data/worldservice/tv/africa_eye/p08104fl.json
  data/worldservice/tv/africa_eye/p08h00x4.json
  data/worldservice/tv/africa_eye/p08jbbg.json
  data/worldservice/tv/africa_eye/p08kmrgq.json
  data/worldservice/tv/africa_eye/p08lzs95.json
  data/worldservice/tv/africa_eye/p08n8hh4.json
  data/worldservice/tv/africa_eye/w13xttpn.json
  src/app/routes/utils/regex/index.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
  src/server/local/constructDataFilePath/index.js
  src/server/local/constructDataFilePath/index.test.js
  src/server/local/index.js
Labels: ws-media

#7718 Updating toggles README
  src/app/lib/config/toggles/README.md
Labels: cross-team

#7720 Relax regex for legacy TC2 assets
  data/ukchina/legacyAssets/simp/uk_education/tianshu/091124_tianshu_iv_cityvc2.json
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
Labels: cross-team

#7722 BAU: Nepali translation update
  src/app/containers/ArticleTimestamp/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/nepali.js
Labels: ws-engage

#7706 Update integration tests for Related Content
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsOnwardJourney/index.jsx
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/crossPlatformTests.js
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
Labels: ws-media

#7719 bump dependencies without breaking changes
  package-lock.json
  package.json
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleFigure/index.test.jsx
  src/app/containers/Bulletin/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/RecommendationsPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/RecommendationsPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/ImageWithPlaceholder/__snapshots__/index.test.jsx.snap
  src/app/containers/ImageWithPlaceholder/index.test.jsx
  src/app/containers/Include/amp/VjAmp.jsx
  src/app/containers/IndexPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: cross-team, dependencies, ws-engage

#7750 psammead dependency bumps
  package-lock.json
  package.json
Labels: ws-engage

#7752 Improve Render Speed for CPS Assets
  data/persian/legacyAssets/iran/2009/09/090920_bd_pp_ir88_timeline_election.json
  src/app/routes/cpsAsset/getInitialData/addBylineBlock/index.js
  src/app/routes/cpsAsset/getInitialData/addBylineBlock/index.test.js
  src/app/routes/cpsAsset/getInitialData/addHeadlineBlock/index.js
  src/app/routes/cpsAsset/getInitialData/addHeadlineBlock/index.test.js
  src/app/routes/cpsAsset/getInitialData/addMpuBlock/index.js
  src/app/routes/cpsAsset/getInitialData/addRecommendationsBlock/index.js
  src/app/routes/cpsAsset/getInitialData/addSummaryBlock/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.js
  src/app/routes/utils/jsonClone/index.js
  src/app/routes/utils/jsonClone/index.test.js
  src/app/routes/utils/sharedDataTransformers/applyBlockPositioning/index.js
  src/app/routes/utils/sharedDataTransformers/augmentWithTimestamp/index.js
Labels: cross-team

#7721 Ensure front page path does not match legacy asset path
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
Labels: cross-team

#7751 psammead dependency bumps
  package-lock.json
  package.json
  src/app/containers/BulletedList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsText/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: cross-team, dependencies, ws-engage

#7633 add adcampaign to canonical bootstrap
  data/mundo/cpsAssets/noticias-internacional-51266689.json
  src/app/containers/Ad/Canonical/CanonicalAdBootstrapJs.jsx
  src/app/containers/Ad/Canonical/CanonicalAdBootstrapJs.test.jsx
  src/app/containers/Ad/Canonical/__snapshots__/CanonicalAdBootstrapJs.test.jsx.snap
  src/app/containers/Ad/Canonical/index.jsx
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.test.jsx
  src/integration/pages/storyPage/canonicalTests.js
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: ws-engage

#7695 Reserve Space for AMP Ads & Apply UX Specifications
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/utilities/adSlotStyles.js
Labels: ads, ws-home

#7771 Enable STY Ads on Live
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/index.test.jsx
Labels: ads, ws-engage

#7776 Remove lodash from forced resolutions
  package-lock.json
  package.json
Labels: cross-team, dependencies

#7791 Temporarily allowlist node-fetch vulnerability pending fix
  audit-ci.json
  package-lock.json
  package.json
Labels: cross-team, dependencies, high-priority, technical-work

#7786 Update translation for Ukrainian timestamp
  src/app/lib/config/services/ukrainian.js
Labels: ws-engage

#7753 Implement apple-itunes-app meta tag for services with iTunesAppID
  src/app/containers/ArticleMetadata/index.test.jsx
  src/app/containers/CpsMetadata/index.test.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/Metadata/utils.jsx
  src/app/containers/Metadata/utils.test.jsx
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/russian.js
  src/integration/common/SEO.js
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: ws-engage

#7754 Bump dependencies
  package-lock.json
  package.json
Labels: cross-team, dependencies, ws-engage

#7687 Announce media type for most watched items when using screen readers
  src/app/containers/StoryPromo/LinkContents/index.jsx
  src/app/containers/StoryPromo/MediaIndicator/index.jsx
  src/app/containers/StoryPromo/utilities/index.js
  src/app/containers/StoryPromo/utilities/index.test.js
Labels: a11y, most-watched, ws-media

#7796 Reinstate prismjs in package-lock.json
  package-lock.json
Labels: cross-team, dependencies

#7700 Moving shared OD/Live radio styling to one place
  src/app/containers/AVPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/AVPlayer/index.jsx
  src/app/containers/AVPlayer/index.test.jsx
  src/app/pages/LiveRadioPage/LiveRadioPage.jsx
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/OnDemandRadioPage.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/OnDemandTvPage.jsx
Labels: ws-media

#7794 Dependency Updates 2020-09-11
  package-lock.json
  package.json
Labels: dependencies

#7810 Add feature toggle for testing asyncAds
  src/app/containers/Ad/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.jsx
  src/app/containers/Ad/index.test.jsx
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
Labels: ads, ws-engage

#7820 Remove logger duplication
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
Labels: cross-team

#7773 Unit tests for local server
  src/server/local/index.js
  src/server/local/index.test.js
Labels: cross-team

#7770 Address 'Superfluous trailing arguments' security warnings
  cypress/integration/pages/onDemandTV/index.js
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.js
  src/app/lib/analyticsUtils/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/includeClassifier/index.js
  src/server/utilities/cspHeader/index.js
Labels: cross-team, security

#7823 Remove empty file
  cypress/integration/pages/onDemandTV/index.js
  cypress/integration/pages/onDemandTV/testsForAMPOnly.js
Labels: ws-media

#7821 Remove headline check
  src/app/containers/StoryPromo/index.jsx
Labels: cross-team

#7833 Remove temp feature toggle for async ads
  package-lock.json
  src/app/containers/Ad/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/index.jsx
  src/app/containers/Ad/index.test.jsx
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
Labels: ads, ws-engage

#7688 Setup most watched page furniture
  scripts/bundleSize/__mocks__/pageTypeBundleExtractor.js
  scripts/bundleSize/bundleSize.test.js
  scripts/bundleSize/bundleSizeConfig.js
  scripts/bundleSize/pages.js
  src/app/contexts/RequestContext/index.jsx
  src/app/pages/MostWatchedPage/MostWatchedPage.jsx
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/index.jsx
  src/app/pages/MostWatchedPage/index.test.jsx
  src/app/pages/index.js
  src/app/routes/index.js
  src/app/routes/index.test.jsx
  src/app/routes/mostWatched/getInitialData/index.js
  src/app/routes/mostWatched/getInitialData/index.test.js
  src/app/routes/mostWatched/index.js
  src/app/routes/utils/regex/index.js
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
Labels: most-watched, ws-media

#7723 Use single winston logger to prevent MaxListenersExceededWarning messages in the console
  src/app/lib/logger.node.js
  src/server/index.jsx
Labels: cross-team

#7832 Force node-forge to secure version and remove semver from prismjs
  package-lock.json
  package.json
Labels: cross-team, dependencies

#7840 Don't run `npm-force-resolutions` on `npm ci`
  package.json
Labels: cross-team, technical-work

#7822 Do not display the BBC News iTunes app banner on AMP
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/Metadata/utils.jsx
  src/app/containers/Metadata/utils.test.jsx
  src/integration/common/SEO.canonical.js
  src/integration/common/SEO.js
  src/integration/common/index.js
  src/integration/pages/articles/canonicalTests.js
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/canonicalTests.js
  src/integration/pages/idxPage/canonicalTests.js
  src/integration/pages/liveRadio/canonicalTests.js
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/canonicalTests.js
  src/integration/pages/mostReadPage/canonicalTests.js
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/canonicalTests.js
  src/integration/pages/onDemandTVPage/canonicalTests.js
  src/integration/pages/photoGalleryPage/canonicalTests.js
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/canonicalTests.js
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
Labels: ws-engage

#7790 Bump Psammead media player and add correct bottom padding to Figure
  package-lock.json
  package.json
  src/app/containers/AVPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/AVPlayer/index.jsx
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/index.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/OnDemandTvPage.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: cross-team, ws-engage

#7838 Allow debug logs on the test environment
  envConfig/test.env
Labels: ws-engage

#7831 Adding FIX pages to Simorgh Release Info for local environments
  docs/Simorgh-Release-Info.md
  scripts/releaseInfo/index.js
  scripts/releaseInfo/launchDates.js
Labels: ws-engage

#7829 Cypress config for FIX Pages
  cypress/integration/pages/featureIndexPage/index.js
  cypress/integration/pages/featureIndexPage/tests.js
  cypress/integration/pages/featureIndexPage/testsForAMPOnly.js
  cypress/integration/pages/featureIndexPage/testsForCanonicalOnly.js
  cypress/support/config/settings.js
  docs/Simorgh-Release-Info.md
  scripts/releaseInfo/index.js
  scripts/releaseInfo/launchDates.js
Labels: ws-engage

#7836 Add new FIX data for testing
  data/afaanoromoo/cpsAssets/sport-23125110.json
  data/amharic/cpsAssets/23119145.json
  data/arabic/cpsAssets/magazine-54029177.json
  data/azeri/cpsAssets/azerbaijan-44208475.json
  data/bengali/cpsAssets/53988070.json
  data/burmese/cpsAssets/burma-50522534.json
  data/gahuza/cpsAssets/52551839.json
  data/gujarati/cpsAssets/india-53920818.json
  data/hausa/cpsAssets/labarai-52299135.json
  data/hindi/cpsAssets/india-53901953.json
  data/igbo/cpsAssets/media-23160433.json
  data/indonesia/cpsAssets/laporan-khusus-53760712.json
  data/japanese/cpsAssets/53969845.json
  data/korean/cpsAssets/features-44652556.json
  data/kyrgyz/cpsAssets/magazine-54071664.json
  data/marathi/cpsAssets/india-53901688.json
  data/mundo/cpsAssets/noticias-internacional-53826365.json
  data/nepali/cpsAssets/media-54029171.json
  data/pashto/cpsAssets/pashto/columns-54029178.json
  data/persian/cpsAssets/science-52004647.json
  data/pidgin/cpsAssets/tori-23133559.json
  data/portuguese/cpsAssets/geral-51774675.json
  data/punjabi/cpsAssets/india-53963142.json
  data/russian/cpsAssets/media-52418005.json
  data/serbian/cpsAssets/cyr/srbija-52197807.json
  data/serbian/cpsAssets/lat/srbija-52197807.json
  data/sinhala/cpsAssets/51727586.json
  data/somali/cpsAssets/war-53203408.json
  data/swahili/cpsAssets/habari-53516858.json
  data/tamil/cpsAssets/india-53903714.json
  data/telugu/cpsAssets/india-53944227.json
  data/thai/cpsAssets/international-48101964.json
  data/tigrinya/cpsAssets/23124146.json
  data/turkce/cpsAssets/haberler-dunya-51801130.json
  data/ukchina/cpsAssets/simp/cluster_uk_election_2105.json
  data/ukchina/cpsAssets/trad/cluster_uk_election_2105.json
  data/ukrainian/cpsAssets/53725237.json
  data/ukrainian/cpsAssets/ukraine-in-russian-23087735.json
  data/urdu/cpsAssets/world-53692225.json
  data/uzbek/cpsAssets/52149619.json
  data/vietnamese/cpsAssets/magazine-54029179.json
  data/yoruba/cpsAssets/media-23159686.json
  data/zhongwen/cpsAssets/simp/world-54113945.json
  data/zhongwen/cpsAssets/trad/world-54113945.json
Labels: ws-engage

#7839 Updates and adds Japanese and Gahuza navigation links
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/japanese.js
  src/integration/pages/liveRadio/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/canonical.test.js.snap
Labels: BAU, ws-engage

#7849 modify swahili nav
  src/app/lib/config/services/swahili.js
Labels: ws-engage

#7841 Update node 12
  .npmrc
  .nvmrc
  Jenkinsfile
Labels: cross-team, ws-media

#7870 Dependency Updates 2020-09-21
  package-lock.json
  package.json
Labels: dependencies

#7039 Update Code of Conduct to Version 2.0 of Contributor Covenant
  .github/CODE_OF_CONDUCT.md
Labels: Documentation, cross-team

#7854 Don't encode ref parameter
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/lib/analyticsUtils/index.js
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/gahuza.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
Labels: ws-engage

#7877 Remove encoding amp
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/gahuza.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
Labels: cross-team

#7850 Add tests for CpsOnwardJourney
  src/app/containers/CpsOnwardJourney/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsOnwardJourney/index.test.jsx
Labels: cross-team, technical-work

#7845 Address 'Superfluous trailing arguments' security warnings in integration tests
  src/integration/pages/onDemandRadioPage/indonesia.expired/amp.test.js
  src/integration/pages/onDemandRadioPage/indonesia.expired/canonical.test.js
  src/integration/pages/onDemandRadioPage/pashto.expired/amp.test.js
  src/integration/pages/onDemandRadioPage/pashto.expired/canonical.test.js
  src/integration/pages/onDemandTVPage/pashto.expired/amp.test.js
  src/integration/pages/onDemandTVPage/pashto/amp.test.js
  src/integration/pages/onDemandTVPage/somali/amp.test.js
Labels: cross-team

#7887 Mundo nav changes for elections
  src/app/lib/config/services/mundo.js
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: BAU, ws-engage

#7895 Add ATI Analytics to the Most Watched pages
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/params/mostWatchedPage/buildParams.js
  src/app/containers/ATIAnalytics/params/mostWatchedPage/buildParams.test.js
  src/app/pages/MostWatchedPage/MostWatchedPage.jsx
Labels: ws-media

#7885 Chartbeat for Most Watched pages
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/params/mostWatchedPage/buildParams.js
  src/app/containers/ATIAnalytics/params/mostWatchedPage/buildParams.test.js
  src/app/containers/ChartbeatAnalytics/index.jsx
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/pages/MostWatchedPage/MostWatchedPage.jsx
Labels: most-watched, ws-media

#7884 Add SEO and Metadata to Most Watched page
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/params/mostWatchedPage/buildParams.js
  src/app/containers/ATIAnalytics/params/mostWatchedPage/buildParams.test.js
  src/app/containers/ChartbeatAnalytics/index.jsx
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/pages/MostWatchedPage/MostWatchedPage.jsx
Labels: most-watched, ws-media

#7888 Update Russian navigation
  src/app/lib/config/services/russian.js
Labels: BAU, ws-engage

#7889 Update Thai navigation
  src/app/lib/config/services/thai.js
Labels: BAU, ws-engage

#7880 Initial data fetch for Most Watched Page
  data/afaanoromoo/mostWatched/index.json
  data/afrique/mostWatched/index.json
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/params/mostWatchedPage/buildParams.js
  src/app/containers/ATIAnalytics/params/mostWatchedPage/buildParams.test.js
  src/app/containers/ChartbeatAnalytics/index.jsx
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/containers/CpsOnwardJourney/index.jsx
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/index.jsx
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/index.test.jsx
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/MostWatched/index.jsx
  src/app/containers/MostWatched/index.test.jsx
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/utilities/index.js
  src/app/containers/StoryPromo/utilities/index.test.js
  src/app/pages/MediaAssetPage/MediaAssetPage.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/MostWatchedPage.jsx
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/index.test.jsx
  src/app/routes/cpsAsset/getInitialData/index.js
  src/app/routes/mostWatched/getInitialData/index.js
  src/app/routes/mostWatched/getInitialData/index.test.js
  src/app/routes/utils/processMostWatched/index.js
  src/app/routes/utils/processMostWatched/index.test.js
Labels: most-watched, ws-media

#7891 Update Mundo contact footer link
  src/app/lib/config/services/mundo.js
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: BAU, ws-engage

#7894 Adding data-e2e attribute to Story Promo component to facilitate easier automated testing
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/RecommendationsPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/RecommendationsPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: ws-engage

#7906 Add riddle.com to frameSrc CSP
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-engage

#7905 Most Watched Page AMP
  src/app/containers/MostWatched/index.jsx
  src/app/containers/MostWatched/index.test.jsx
  src/app/pages/MediaAssetPage/MediaAssetPage.jsx
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/index.test.jsx
Labels: ws-media

#7904 Only display iOS app banner on STY and MAP pages for Arabic, Mundo & Russian
  src/app/containers/CpsMetadata/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsMetadata/index.jsx
  src/app/containers/CpsMetadata/index.test.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/Metadata/utils.jsx
  src/app/containers/Metadata/utils.test.jsx
  src/app/pages/MediaAssetPage/MediaAssetPage.jsx
  src/app/pages/StoryPage/StoryPage.jsx
  src/integration/common/SEO.canonical.js
  src/integration/common/appleItunesAppBanner.js
  src/integration/common/index.js
  src/integration/pages/articles/canonicalTests.js
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/canonicalTests.js
  src/integration/pages/idxPage/canonicalTests.js
  src/integration/pages/liveRadio/canonicalTests.js
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/canonical.test.js
  src/integration/pages/mediaAssetPage/canonicalTests.js
  src/integration/pages/mostReadPage/canonicalTests.js
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/canonicalTests.js
  src/integration/pages/onDemandTVPage/canonicalTests.js
  src/integration/pages/onDemandTVPage/pashto.expired/canonical.test.js
  src/integration/pages/onDemandTVPage/pashto/canonical.test.js
  src/integration/pages/onDemandTVPage/somali/canonical.test.js
  src/integration/pages/photoGalleryPage/canonicalTests.js
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/canonicalTests.js
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/canonical.test.js
Labels: ws-engage

#7909 Translation updates
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/thai.js
Labels: ws-engage

#7856 Create a Feature Index page
  data/afrique/cpsAssets/48465371.json
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/IndexPageSection/index.jsx
  src/app/pages/FeatureIdxPage/FeatureIdxPage.jsx
  src/app/pages/FeatureIdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FeatureIdxPage/index.jsx
  src/app/pages/FeatureIdxPage/index.stories.jsx
  src/app/pages/FeatureIdxPage/index.test.jsx
  src/app/pages/index.js
  src/app/routes/cpsAsset/index.jsx
Labels: ws-engage

#7846 Add urls to local - featureIndexPage
  cypress/support/config/settings.js
  docs/Simorgh-Release-Info.md
Labels: ws-engage

#7938 Bump gel-foundations to update Thai font size
  package-lock.json
  package.json
Labels: BAU, ux, ws-engage

#7918 Update release info & launch dates for STY pages
  cypress/support/config/settings.js
  docs/Simorgh-Release-Info.md
  scripts/releaseInfo/launchDates.js
Labels: ws-engage

#7848 E2E for Most Watched Component on MAPs
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  cypress/support/commands/toggles.js
  cypress/support/config/envs.js
  cypress/support/config/settings.js
Labels: most-watched, ws-media

#7873 Delete unnecessary cypress tests
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  cypress/integration/pages/frontPage/testsForAMPOnly.js
  cypress/integration/pages/frontPage/testsForCanonicalOnly.js
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/testsForAllAMPPages.js
  cypress/integration/pages/testsForAllCanonicalPages.js
  cypress/integration/pages/testsForAllPages.js
  cypress/support/commands/analytics.js
Labels: ws-engage

#7942 Fix CpsOnwardJourney a11y attributes for most watched
  src/app/containers/CpsOnwardJourney/index.jsx
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
Labels: a11y, ws-media

#7881 Migrate deleted Cypress tests to Integration
  src/integration/common/SEO.amp.js
  src/integration/common/image.js
  src/integration/common/index.js
  src/integration/common/timestamp.js
  src/integration/pages/articles/crossPlatformTests.js
  src/integration/pages/articles/news/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/news/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/ampTests.js
  src/integration/pages/frontPage/crossPlatformTests.js
  src/integration/pages/idxPage/ampTests.js
  src/integration/pages/idxPage/crossPlatformTests.js
  src/integration/pages/liveRadio/ampTests.js
  src/integration/pages/liveRadio/crossPlatformTests.js
  src/integration/pages/mediaAssetPage/ampTests.js
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/crossPlatformTests.js
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/ampTests.js
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/ampTests.js
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/ampTests.js
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/crossPlatformTests.js
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/ampTests.js
  src/integration/pages/storyPage/canonicalTests.js
  src/integration/pages/storyPage/crossPlatformTests.js
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: ws-engage

#7911 Display Android App Install Banner for Hindi
  public/hindi/manifest.json
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-engage

#7843 Delete apple_itunes_app feature toggle
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/Metadata/utils.jsx
  src/app/containers/Metadata/utils.test.jsx
Labels: ws-engage

#7943 Integration tests for Most Watched Page
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/amp.test.js
  src/integration/pages/mostWatchedPage/afrique/canonical.test.js
  src/integration/pages/mostWatchedPage/ampTests.js
  src/integration/pages/mostWatchedPage/canonicalTests.js
  src/integration/pages/mostWatchedPage/crossPlatformTests.js
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/amp.test.js
  src/integration/pages/mostWatchedPage/urdu/canonical.test.js
Labels: most-watched, ws-media

#7937 Announce 'Listen' for audio format media story promos
  src/app/containers/StoryPromo/LinkContents/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/LinkContents/index.jsx
  src/app/containers/StoryPromo/LinkContents/index.test.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/pages/FeatureIdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/canonical.test.js.snap
Labels: a11y, cross-team, ws-media
