Repository bbc/simorgh, pull requests merged in 2020-07, with the labels that each got.

#7083 docs: fixed small errors
  README.md
Labels: Documentation

#7007 Render VJ AMP iframe
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/containers/Include/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/amp/VjAmp.jsx
  src/app/containers/Include/amp/VjAmp.test.jsx
  src/app/containers/Include/amp/__snapshots__/VjAmp.test.jsx.snap
  src/app/containers/Include/index.jsx
  src/app/containers/Include/index.test.jsx
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/ampMetadataExtractor.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/ampMetadataExtractor.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/ampSrcBuilder.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/ampSrcBuilder.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
Labels: a11y-swarm, includes, ux, ws-stories

#7082 Adjust display based on screen size for OD TV
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.jsx
Labels: ws-media-stream

#6965 Add cookie-oven domain to resource hint origins
  src/server/index.test.jsx
  src/server/utilities/getAssetOrigins/index.js
  src/server/utilities/getAssetOrigins/index.test.js
Labels: ws-home, ws-media-stream, ws-stories

#7061 Bump dependencies
  package-lock.json
  package.json
  src/app/containers/SocialEmbed/__snapshots__/index.test.jsx.snap
Labels: ws-home, ws-media-stream, ws-stories

#7034 Update ukraine_in_russian integration tests
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/amp.test.js
  src/integration/pages/idxPage/ukraine_in_russian/canonical.test.js
  src/integration/pages/idxPage/ukraine_in_russian/footer.js
  src/integration/pages/idxPage/ukraine_in_russian/header.js
Labels: IDX, ws-home

#7040 added escape-goat for escaping hmtl char entities
  package-lock.json
  package.json
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/getImageBlock.js
Labels: includes, ws-engage

#7093 Adding word-break for wrapping longer radio titles
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/index.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
Labels: ws-media-stream

#7079 TV / Radio Episode Availability check
  data/afrique/bbc_afrique_tv/tv/w3ct05mp.json
  src/app/lib/utilities/episodeAvailability/index.js
  src/app/lib/utilities/episodeAvailability/index.test.js
Labels: ws-media-stream

#7085 Update Project-Board-Guide.md
  docs/Project-Board-Guide.md
Labels: Documentation

#7096 Remove morph resolved registry from package-lock
  package-lock.json
Labels: ws-engage, ws-media-stream

#7099 Spacing between player and header for OD TV
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.jsx
Labels: ws-media-stream

#7055 Release info for On Demand Radio Batch 1
  cypress/support/config/settings.js
  docs/Simorgh-Release-Info.md
  scripts/releaseInfo/index.js
  scripts/releaseInfo/launchDates.js
Labels: ws-media-stream

#7094 Moving OD Radio over to new AVPlayer
  src/app/pages/OnDemandRadioPage/index.jsx
Labels: ws-media-stream

#7095 Fix related content translation for Ukrainian idx
  src/app/lib/config/services/russian.js
Labels: IDX, ws-home

#6994 adds recommendations container
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/index.jsx
  src/app/containers/CpsRecommendations/index.test.jsx
  src/app/containers/CpsRecommendations/utils.js
  src/app/containers/CpsRecommendations/utils.test.js
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/toggles/index.js
  src/app/pages/StoryPage/fixtureData/recommendations.ltr.json
  src/app/pages/StoryPage/fixtureData/recommendations.rtl.json
  src/app/pages/StoryPage/index.jsx
  src/app/routes/cpsAsset/getInitialData/index.js
Labels: Recommendations, ws-engage

#7110 Temporarily allowlist lodash vulnerability pending fix
  audit-ci.json
  package.json
Labels: ws-engage, ws-home, ws-media-stream

#7107 Ensure we don't try to fetch radio schedule on ukrainian idx
  src/app/routes/idx/getInitialData/index.js
  src/app/routes/idx/getInitialData/index.test.js
Labels: IDX, high-priority, ws-home

#7104 Test E2Es for Batch 2 of OD Radio
  cypress/support/config/settings.js
Labels: cypress, ws-media-ondemandRadio, ws-media-stream

#7091 Enable Cypress tests to run on the live ukrainian/ukraine_in_russian
  cypress/support/config/settings.js
Labels: IDX, ws-home

#7113 Use correct "BBC" in ukrainian config
  src/app/lib/config/services/ukrainian.js
Labels: IDX, ws-home

#7115 Live E2Es On Demand Radio Batch 2
  cypress/support/config/settings.js
Labels: cypress, ws-media-ondemandRadio, ws-media-stream

#7114 Adding LiveRadio tests for AVPlayer
  src/app/containers/AVPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/AVPlayer/index.test.jsx
Labels: ws-media-stream

#7108 Move Live Radio over to the new AVPlayer component
  src/app/pages/LiveRadioPage/index.jsx
Labels: ws-media-stream

#7121 update snapshots for ukrainian idx integration tests
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
Labels: ws-engage, ws-home, ws-media-stream

#7118 Update release info
  cypress/support/config/settings.js
  data/afaanoromoo/cpsAssets/oduu-53268428.json
  data/amharic/cpsAssets/news-53260525.json
  data/azeri/cpsAssets/international-53242449.json
  data/burmese/cpsAssets/world-53250349.json
  data/gujarati/cpsAssets/international-53214116.json
  data/korean/cpsAssets/features-53146758.json
  data/pidgin/cpsAssets/international-53251686.json
  data/somali/cpsAssets/53266542.json
  data/swahili/cpsAssets/habari-53264596.json
  data/tigrinya/cpsAssets/53247266.json
  data/uzbek/cpsAssets/uzbekistan-53263099.json
  docs/Simorgh-Release-Info.md
  scripts/releaseInfo/launchDates.js
Labels: Documentation, ws-engage

#7100 Bump latest dependencies
  package-lock.json
  package.json
  src/app/containers/ArticleTimestamp/timeFormatTests/expectedFormats.json
Labels: ws-engage, ws-media-stream

#7116 Update release info doc
  docs/Simorgh-Release-Info.md
  scripts/releaseInfo/index.js
  scripts/releaseInfo/launchDates.js
Labels: ws-home

#7125 Deleting old AudioPlayer component
  src/app/containers/AudioPlayer/index.jsx
  src/app/containers/AudioPlayer/index.test.jsx
Labels: ws-media-stream

#7127 Update hidden h1 to single line to improve VoiceOver announcement
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.jsx
  src/app/pages/OnDemandTvPage/index.test.jsx
Labels: OD-TV, a11y, ws-media-stream

#7126 Add on demand tv to a11y tests
  a11y.js
Labels: OD-TV, a11y, ws-media-stream

#7089 On Demand Radio Release Info for batch #2
  docs/Simorgh-Release-Info.md
  scripts/releaseInfo/launchDates.js
Labels: ws-media-stream

#7105 Fix logic for when on demand radio episodes are expired in E2Es
  cypress/integration/pages/onDemandRadio/helpers.js
Labels: ws-media-stream

#6967 Preroll Ads E2Es
  3rdPartyCypress/cypress.json
  3rdPartyCypress/cypress/integration/prerollAds/config.js
  3rdPartyCypress/cypress/integration/prerollAds/index.js
  3rdPartyCypress/cypress/integration/worldServiceCoUkRedirect.js
  3rdPartyCypress/cypress/support/commands.js
  package.json
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
Labels: ws-media-stream

#7037 [2nd try] Reuse Jenkins node and only install/build once
  Jenkinsfile
  Makefile
  package.json
Labels: ws-engage, ws-home, ws-media-stream

#7150 Set puppeteer version to 4.0.1
  package.json
Labels: ws-engage, ws-home, ws-media-stream

#7023 Add Comscore tracking
  src/app/containers/ComscoreAnalytics/Amp/index.jsx
  src/app/containers/ComscoreAnalytics/__snapshots__/index.test.jsx.snap
  src/app/containers/ComscoreAnalytics/index.jsx
  src/app/containers/ComscoreAnalytics/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
  src/app/pages/ArticlePage/index.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/index.jsx
  src/app/pages/IdxPage/index.jsx
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/index.jsx
  src/app/pages/MediaAssetPage/index.jsx
  src/app/pages/MostReadPage/index.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/pages/OnDemandTvPage/index.jsx
  src/app/pages/PhotoGalleryPage/index.jsx
  src/app/pages/StoryPage/index.jsx
Labels: ads, ws-home

#7152 6775 update logging format issue
  src/app/lib/logger.node.js
Labels: ws-engage

#7157 OD Radio Batch 3 Test E2Es
  cypress/integration/pages/onDemandRadio/helpers.js
  cypress/integration/pages/onDemandRadio/testsForAMPOnly.js
  cypress/integration/pages/onDemandRadio/testsForCanonicalOnly.js
  cypress/support/config/settings.js
Labels: OD-radio, cypress, ws-media-stream

#7148 Fix on demand radio Amp player position
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/index.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
Labels: AMP, OD-radio, bug, ux, ws-media-stream

#7147 added margin to story page bottom
  package-lock.json
  package.json
  src/app/containers/AVPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.jsx
Labels: ws-engage

#7134 Cookie banner E2Es - run tests for reduced list of services
  cypress.json
  cypress/integration/specialFeatures/cookieBanner/index.js
  cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
  cypress/integration/specialFeatures/cookieBanner/testsForCanonicalOnly.js
  cypress/support/config/settings.js
Labels: ws-media-stream

#7131 Conditionally load live/test gnl bootstrap file
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/Canonical/index.test.jsx
Labels: ws-home

#7165 Live E2Es batch 3 OD Radio
  cypress/support/config/settings.js
Labels: OD-radio, cypress, ws-media-stream

#7160 Add MPU Ad for amp and canonical
  src/app/containers/Ad/Amp/AdSlot.test.jsx
  src/app/containers/Ad/Amp/__snapshots__/AdSlot.test.jsx.snap
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.test.jsx
  src/app/containers/Ad/Canonical/AdSlot.jsx
  src/app/containers/Ad/Canonical/AdSlot.test.jsx
  src/app/containers/Ad/Canonical/__snapshots__/AdSlot.test.jsx.snap
  src/app/containers/Ad/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/Canonical/index.test.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.jsx
  src/app/containers/Ad/index.test.jsx
  src/app/pages/FrontPage/index.jsx
Labels: ads, ws-home

#7174 Fix locale property of timestamp for OD radio
  data/zhongwen/bbc_cantonese_radio/w172xf3r5x8hw4v.json
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/index.jsx
  src/app/pages/OnDemandRadioPage/index.test.jsx
  src/app/pages/OnDemandTvPage/index.jsx
Labels: OD-TV, OD-radio, bug, ws-media-stream

#7081 Add canAdvertise prop to request Context
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/Canonical/index.test.jsx
  src/app/containers/Ad/index.test.jsx
  src/app/containers/App/App.jsx
  src/app/containers/App/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/PageHandlers/withContexts.jsx
  src/app/containers/PageHandlers/withContexts.test.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
  src/app/pages/FrontPage/index.jsx
  src/app/pages/FrontPage/index.test.jsx
  src/server/index.jsx
  src/server/utilities/canAdvertise/index.js
  src/server/utilities/canAdvertise/index.test.js
Labels: ads, ws-home

#7189 Revert "Add canAdvertise prop to request Context"
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/Canonical/index.test.jsx
  src/app/containers/Ad/index.test.jsx
  src/app/containers/App/App.jsx
  src/app/containers/App/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/PageHandlers/withContexts.jsx
  src/app/containers/PageHandlers/withContexts.test.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
  src/app/pages/FrontPage/index.jsx
  src/app/pages/FrontPage/index.test.jsx
  src/server/index.jsx
  src/server/utilities/canAdvertise/index.js
  src/server/utilities/canAdvertise/index.test.js
Labels: ws-home

#7181 Use shortHeadline as the source for og:title and twitter:title for CPS assets
  src/app/containers/CpsMetadata/index.jsx
  src/app/containers/CpsMetadata/index.test.jsx
  src/app/containers/Metadata/index.jsx
  src/app/pages/MediaAssetPage/index.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/index.jsx
  src/app/pages/StoryPage/index.jsx
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
Labels: stories-STYs, ws-engage, ws-media-stream

#7183 Remove escape-goat package
  package-lock.json
  package.json
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/getImageBlock.js
  src/app/routes/utils/htmlUnescape/index.js
  src/app/routes/utils/htmlUnescape/index.test.js
Labels: bug, ws-engage

#7184 Live E2E OD TV Somali and Pashto
  cypress/support/config/settings.js
Labels: OD-TV, cypress, ws-media-stream

#7168 Adds index identifier for Includes
  scripts/bundleSizeConfig.js
  src/app/containers/Include/canonical/Idt2/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/canonical/Idt2/index.jsx
  src/app/containers/Include/canonical/Idt2/index.test.jsx
  src/app/containers/Include/canonical/index.jsx
  src/app/containers/Include/canonical/index.test.jsx
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/fixtures.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.test.js
  src/integration/pages/storyPage/gahuza/__snapshots__/canonical.test.js.snap
Labels: includes, stories-STYs, ws-engage

#7191 Add AMP iFrame script to VJ Amp Include
  src/app/containers/Include/amp/VjAmp.jsx
  src/app/containers/Include/amp/VjAmp.test.jsx
Labels: includes, ws-engage

#7192 Update Russian translation
  src/app/lib/config/services/russian.js
Labels: ws-engage

#7187 Disable Pidgin ads
  src/app/lib/config/services/pidgin.js
  src/app/pages/FrontPage/index.test.jsx
Labels: ads, ws-home

#7111 Buildspec for running PR checks on CodeBuild
  buildspecs/buildspec-ci-pr.yml
Labels: ws-engage, ws-media

#7207 OD TV test E2Es batch 2 except Ukrainian
  cypress/support/config/settings.js
Labels: OD-TV, cypress, ws-media

#7211 Bump psammead-locales and related packages
  package-lock.json
  package.json
  src/app/containers/ArticleTimestamp/timeFormatTests/expectedFormats.json
Labels: ws-engage, ws-media

#6852 handle data fetch and transformation errors and show relevant error page
  src/app/containers/PageHandlers/withError/index.jsx
  src/app/containers/PageHandlers/withError/index.test.jsx
  src/app/routes/article/getInitialData/index.js
  src/app/routes/cpsAsset/getInitialData/index.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
  src/app/routes/getInitialData.test.jsx
  src/app/routes/home/getInitialData/index.js
  src/app/routes/idx/getInitialData/index.js
  src/app/routes/liveRadio/getInitialData/index.js
  src/app/routes/mostRead/getInitialData/index.js
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/onDemandTV/getInitialData/index.js
  src/app/routes/utils/fetchPageData/index.js
  src/app/routes/utils/fetchPageData/index.test.js
  src/app/routes/utils/fetchPageData/utils/getErrorStatusCode.js
  src/app/routes/utils/fetchPageData/utils/statusCodes.js
Labels: OD-radio, ws-media

#7078 remove bbc-a11y iframe exceptions
  a11y.js
  package-lock.json
  package.json
Labels: ws-media

#7210 Rename CodeBuild buildspec for CI checks
  buildspecs/buildspec-ci-branch.yml
Labels: ws-engage, ws-media

#7196 On Demand Radio Batch 3 & On Demand TV Batch 1 - release info
  docs/Simorgh-Release-Info.md
  scripts/releaseInfo/index.js
  scripts/releaseInfo/launchDates.js
Labels: ws-media

#7217 Live e2es and test e2e for ukrainian
  cypress/support/config/settings.js
Labels: OD-TV, cypress, ws-media

#7170 Add word-break to large breakpoints
  data/burmese/cpsAssets/53204574.json
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/index.jsx
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: bug, stories-STYs, ws-engage

#7213 Bump psammead story-promo-list
  package-lock.json
  package.json
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexPageSection/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: ws-engage

#7171 Show More button in VJ Includes on Amp
  a11y.js
  data/mundo/cpsAssets/23263889.json
  scripts/bundleSizeConfig.js
  src/app/containers/Include/amp/VjAmp.jsx
  src/app/containers/Include/amp/__snapshots__/VjAmp.test.jsx.snap
Labels: a11y, a11y-swarm, includes, ux, ws-engage

#7237 Revert: Set puppeteer version to 4.0.1
  package.json
Labels: technical-work, ws-engage, ws-home, ws-media

#7216 Add missing csp entries for includes on live
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: bug, ws-engage

#7058 Setup custom CW metrics using AWS EMF
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  package-lock.json
  package.json
  src/server/index.jsx
  src/server/index.test.jsx
  src/server/utilities/customMetrics/index.js
  src/server/utilities/customMetrics/index.test.js
  src/server/utilities/customMetrics/metrics.const.js
  src/server/utilities/onEnvironment/index.js
  src/server/utilities/onEnvironment/index.test.js
Labels: ws-engage, ws-media

#7244 Add directory paths to jsconfig.json
  jsconfig.json
Labels: technical-work

#7230 Bump psammead packages
  package-lock.json
  package.json
Labels: ws-engage, ws-media

#7179 Add 'news.test.files.bbci.co.uk' to non live csp
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-engage

#7224 Update release page
  cypress/support/config/settings.js
  docs/Simorgh-Release-Info.md
  scripts/releaseInfo/launchDates.js
Labels: ws-engage

#7025 Hide AMP and Canonical Ads from screen readers and tab order
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/utilities/getAdsAriaLabel.js
  src/app/containers/Ad/utilities/getAdsAriaLabel.test.js
  src/app/pages/FrontPage/index.jsx
Labels: ads, ws-home

#7219 Adding pageType as a parameter to fetchPageData
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/pages/FrontPage/index.test.jsx
  src/app/pages/LiveRadioPage/index.test.jsx
  src/app/pages/MediaAssetPage/index.test.jsx
  src/app/pages/OnDemandRadioPage/index.test.jsx
  src/app/pages/OnDemandTvPage/index.test.jsx
  src/app/pages/PhotoGalleryPage/index.test.jsx
  src/app/pages/StoryPage/index.test.jsx
  src/app/routes/article/getInitialData/index.js
  src/app/routes/article/getInitialData/index.test.js
  src/app/routes/cpsAsset/getInitialData/index.js
  src/app/routes/cpsAsset/getInitialData/index.test.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
  src/app/routes/getInitialData.test.jsx
  src/app/routes/home/getInitialData/index.js
  src/app/routes/home/getInitialData/index.test.js
  src/app/routes/idx/getInitialData/index.js
  src/app/routes/idx/getInitialData/index.test.js
  src/app/routes/index.test.jsx
  src/app/routes/liveRadio/getInitialData/index.js
  src/app/routes/liveRadio/getInitialData/index.test.js
  src/app/routes/mostRead/getInitialData/index.js
  src/app/routes/mostRead/getInitialData/index.test.js
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/onDemandRadio/getInitialData/index.test.js
  src/app/routes/onDemandTV/getInitialData/index.js
  src/app/routes/onDemandTV/getInitialData/index.test.js
  src/app/routes/utils/fetchPageData/index.js
  src/app/routes/utils/fetchPageData/index.test.js
  src/server/index.jsx
Labels: ws-media

#7274 Test E2Es for Persian TV
  cypress/support/config/settings.js
Labels: OD-TV, cypress, ws-media

#7253 Add translations for recommendation title
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/turkce.js
Labels: Recommendations, ws-engage

#7280 Stop running tests on merge to latest
  Jenkinsfile
Labels: technical-work

#7220 Remove hasAds from service configs
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
  src/app/pages/FrontPage/index.jsx
  src/app/pages/FrontPage/index.test.jsx
Labels: ads, ws-home

#7251 Move Chromatic and Code Climate to Codebuild
  Jenkinsfile
  buildspecs/buildspec-ci-branch.yml
Labels: cross-team

#7277 Use page language code to select service language override
  src/app/containers/PageHandlers/withContexts.jsx
  src/app/contexts/ServiceContext/index.jsx
  src/app/contexts/ServiceContext/index.test.jsx
  src/app/lib/utilities/langHandler/index.js
  src/app/lib/utilities/langHandler/index.test.js
Labels: high-priority, ukrainian-STYs, ws-engage

#7180 Show Embed Error on AMP version of Includes
  data/mundo/cpsAssets/23263889.json
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/Include/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/canonical/index.jsx
  src/app/containers/Include/index.jsx
  src/app/containers/Include/index.test.jsx
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/fixtures.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/includeClassifier.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/includeClassifier.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/isAmpSupported.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/isAmpSupported.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.test.js
Labels: a11y-swarm, includes, stories-STYs, ws-engage

#7292 Bump @bbc/psammead-assets
  package-lock.json
  package.json
Labels: ws-engage, ws-home, ws-media

#7294 Revert "Remove hasAds from service configs"
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
  src/app/pages/FrontPage/index.jsx
  src/app/pages/FrontPage/index.test.jsx
Labels: cross-team

#7283 Disable Russian MAP URLs on Test
  cypress/support/config/settings.js
Labels: ws-media

#7284 Update footer links - Japanese
  src/app/lib/config/services/japanese.js
Labels: ws-engage

#7225 use OJ container for recommendations
  scripts/bundleSizeConfig.js
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsOnwardJourney/index.jsx
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/index.jsx
  src/app/containers/CpsRecommendations/index.stories.jsx
  src/app/containers/CpsRecommendations/index.test.jsx
  src/app/containers/CpsRecommendations/utils.js
  src/app/containers/CpsRecommendations/utils.test.js
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/index.jsx
  src/app/pages/StoryPage/fixtureData/recommendations.ltr.json
  src/app/pages/StoryPage/fixtureData/recommendations.rtl.json
  src/app/pages/StoryPage/index.jsx
Labels: Recommendations, a11y, ux, ws-engage

#7231 STY Fetch from Recommendations endpoint
  data/arabic/recommendations/index.json
  data/hindi/recommendations/index.json
  data/mundo/recommendations/index.json
  data/portuguese/recommendations/index.json
  data/turkce/recommendations/index.json
  src/app/containers/CpsRecommendations/index.test.jsx
  src/app/lib/utilities/getRecommendationsUrl/index.js
  src/app/lib/utilities/getRecommendationsUrl/index.test.js
  src/app/pages/StoryPage/index.jsx
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.test.js
  src/app/routes/cpsAsset/utils/getAssetUri.js
  src/app/routes/cpsAsset/utils/getAssetUri.test.js
  src/app/routes/cpsAsset/utils/hasRecommendations.js
  src/app/routes/cpsAsset/utils/hasRecommendations.test.js
  src/app/routes/index.test.jsx
  src/app/routes/utils/regex/index.js
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: Recommendations, stories-STYs, ws-engage

#7295 Update player padding on video player pages
  src/app/containers/FauxHeadline/__snapshots__/index.test.jsx.snap
  src/app/containers/FauxHeadline/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/index.jsx
  src/app/pages/MediaAssetPage/MediaMessage/index.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.jsx
Labels: ws-media

#7293 Update wording in PULL_REQUEST_TEMPLATE.md to reflect new label for cross team work
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cross-team, process-work

#7266 Updating Storybook fixture data to mirror Live Radio Page
  src/app/pages/LiveRadioPage/fixtureData/afaanoromoo.json
  src/app/pages/LiveRadioPage/fixtureData/amharic.json
  src/app/pages/LiveRadioPage/fixtureData/indonesia.json
  src/app/pages/LiveRadioPage/fixtureData/korean.json
  src/app/pages/LiveRadioPage/fixtureData/tigrinya.json
Labels: ws-media

#7297 Enable ads for zhongwen trad
  src/app/lib/config/services/zhongwen.js
Labels: ads, ws-home

#7276 Live E2Es Persian OD TV
  cypress/support/config/settings.js
Labels: OD-TV, cypress, ws-media

#7252 Support for renderer_env=test for VJ AMP
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/includeClassifier.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
  src/app/routes/utils/fetchPageData/utils/getRouteProps/index.js
  src/app/routes/utils/fetchPageData/utils/getRouteProps/index.test.js
  src/app/routes/utils/fetchPageData/utils/getRouteProps/routeFallbackParams/index.test.js
  src/app/routes/utils/isAmpPath/index.js
  src/app/routes/utils/isAmpPath/index.test.js
Labels: bug, includes, stories-STYs, ws-engage

#7301 Use page language code AND service to select service language override
  cypress/support/config/settings.js
  data/russian/cpsAssets/23219699.json
  src/app/containers/PageHandlers/withContexts.jsx
  src/app/contexts/ServiceContext/index.jsx
  src/app/contexts/ServiceContext/index.test.jsx
  src/app/lib/utilities/langHandler/index.js
  src/app/lib/utilities/langHandler/index.test.js
Labels: high-priority, ukrainian-STYs, ws-engage

#7305 Implement updated Psammead module to remove the bottom border beneath the top nav
  package-lock.json
  package.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
Labels: ux

#7308 Disable e2e's for Live Russian STYs
  cypress/support/config/settings.js
Labels: ws-engage

#7286 Add more hreflangs
  src/app/containers/ArticleMetadata/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/zhongwen.js
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
Labels: cross-team, ws-engage

#7212 Live Radio radio schedule
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/toggles/index.js
  src/app/pages/LiveRadioPage/index.jsx
  src/app/pages/LiveRadioPage/index.test.jsx
  src/app/routes/liveRadio/getInitialData/index.js
  src/app/routes/liveRadio/getInitialData/index.test.js
Labels: ws-media

#7310 Add cache control to the manifest.json response header
  src/server/index.jsx
  src/server/index.test.jsx
Labels: ws-engage

#7279 Server Refactor - move local server setup to separate file
  src/server/index.jsx
  src/server/local/constructDataFilePath/index.js
  src/server/local/constructDataFilePath/index.test.js
  src/server/local/index.js
Labels: cross-team, technical-work

#7322 Enables STY Recommendations on test
  src/app/lib/config/toggles/index.js
Labels: Recommendations, ws-engage

#7304 Fix blurry Story promo images at higher resolutions
  src/app/containers/StoryPromo/index.jsx
Labels: ws-media

#7302 added skip link for recommendations
  package.json
  src/app/components/SkipLinkWrapper/index.jsx
  src/app/components/SkipLinkWrapper/index.test.jsx
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/index.jsx
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/turkce.js
Labels: a11y, ws-engage

#7206 [DO NOT MERGE] TV Cinema Mode - Live
  src/app/lib/config/toggles/index.js
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.test.jsx
Labels: blocked, ws-media

#7223 Adhoc Cypress test project
  AdHocCypress/README.md
  AdHocCypress/cypress.json
  AdHocCypress/cypress/plugins/index.js
  AdHocCypress/cypress/support/commands.js
  AdHocCypress/cypress/support/index.js
  package.json
Labels: cross-team

#7320 prevent summary rendering in secondary column at medium gel widths
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/index.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: bug, ux, ws-engage

#7343 Removing schedules for Gahuza's Live Radio page
  src/app/lib/config/services/gahuza.js
Labels: ws-media

#7317 Make index alsos which are promo assets work
  data/persian/frontpage/index.json
  src/app/containers/StoryPromo/IndexAlsos/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/IndexAlsos/index.jsx
  src/app/containers/StoryPromo/IndexAlsos/index.test.jsx
  src/app/containers/StoryPromo/IndexAlsos/relatedItems.js
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.test.jsx
Labels: ws-engage

#7347 Test E2Es for Russian MAPs with redirect
  cypress/support/config/settings.js
Labels: MAP, cypress, ws-media

#7337 Send custom cloudwatch metrics on AReS 404 response
  src/app/lib/statusCodes.const.js
  src/app/routes/utils/fetchPageData/index.js
  src/app/routes/utils/fetchPageData/index.test.js
  src/app/routes/utils/fetchPageData/utils/getErrorStatusCode.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: cross-team, technical-work

#7222 Skeleton adhoc tests for legacy MAP media playback
  AdHocCypress/cypress/integration/topcat2MediaPlayback/config.js
  AdHocCypress/cypress/integration/topcat2MediaPlayback/index.js
  AdHocCypress/cypress/support/utilities/getDataUrl/index.js
  AdHocCypress/cypress/support/utilities/getDataUrl/index.test.js
Labels: ws-media

#7345 override html 'lang' attribute with computed 'lang' override in service config
  data/ukrainian/cpsAssets/news-russian-23333960.json
  src/app/pages/StoryPage/index.jsx
Labels: a11y, ws-engage

#7312 Separate toggles into 1 file per environment
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/README.md
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/const.js
  src/app/lib/config/toggles/index.js
  src/app/lib/config/toggles/index.test.js
  src/app/lib/config/toggles/liveConfig.js
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
Labels: cross-team, technical-work

#7342 onEnvironment can now accept an array of values
  src/server/utilities/customMetrics/index.js
  src/server/utilities/onEnvironment/index.js
  src/server/utilities/onEnvironment/index.test.js
Labels: cross-team

#7356 [DO NOT MERGE] Live Russian MAP E2Es (a URL to redirect and a TC2)
  cypress/support/config/settings.js
Labels: MAP, cypress, ws-media

#7355 Separate out padding for OD TV and Radio Heading
  data/indonesia/bbc_indonesian_radio/w13xtt0s.json
  src/app/containers/OnDemandHeading/StyledRadioHeadingContainer.jsx
  src/app/containers/OnDemandHeading/StyledTvHeadingContainer.jsx
  src/app/containers/OnDemandHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/OnDemandHeading/index.jsx
  src/app/containers/OnDemandHeading/index.test.jsx
  src/app/containers/OnDemandImage/__snapshots__/index.test.jsx.snap
  src/app/containers/OnDemandImage/index.jsx
  src/app/containers/OnDemandImage/index.test.jsx
  src/app/containers/OnDemandParagraph/__snapshots__/index.test.jsx.snap
  src/app/containers/OnDemandParagraph/index.jsx
  src/app/containers/OnDemandParagraph/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/Heading/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/Heading/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/Heading/index.test.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.jsx
Labels: ws-media

#7368 Enable CW metrics on live
  src/server/utilities/customMetrics/index.js
  src/server/utilities/customMetrics/index.test.js
Labels: cross-team, technical-work

#7365 Jest environment improvements
  package-lock.json
  package.json
  src/app/containers/Ad/Amp/AdSlot.test.jsx
  src/app/containers/Ad/Amp/index.test.jsx
  src/app/containers/Ad/Canonical/CanonicalAdBootstrapJs.test.jsx
  src/app/containers/Ad/Canonical/index.test.jsx
  src/app/containers/App/index.test.jsx
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/Fragment/index.test.jsx
  src/app/containers/Header/ScriptLink/index.test.jsx
  src/app/containers/Header/index.test.jsx
  src/app/containers/Include/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/amp/__snapshots__/VjAmp.test.jsx.snap
  src/app/containers/Include/canonical/Idt2/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/MostRead/index.test.jsx
  src/app/containers/MostRead/label.test.jsx
  src/app/containers/MostRead/section.test.jsx
  src/app/containers/Navigation/index.amp.test.jsx
  src/app/containers/Navigation/index.canonical.test.jsx
  src/app/containers/RadioSchedule/Canonical/index.test.jsx
  src/app/containers/RadioSchedule/index.test.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/contexts/ToggleContext/index.test.jsx
  src/app/hooks/useToggle/index.test.jsx
  src/app/hooks/useToggle/useToggle.test.jsx
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/MediaMessage/index.test.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/index.test.jsx
  src/app/pages/MostReadPage/index.test.jsx
  src/app/pages/OnDemandRadioPage/index.test.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.test.jsx
  src/app/pages/PhotoGalleryPage/index.test.jsx
  src/app/pages/StoryPage/index.test.jsx
  src/app/routes/index.test.jsx
  src/testHelpers/setupTests.js
Labels: cross-team, technical-work, ws-engage
