Repository bbc/simorgh, pull requests merged in 2020-05, with the labels that each got.

#6348 Most-read size reduction for STY pages
  package-lock.json
  package.json
  scripts/simorghPages.js
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/index.jsx
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.jsx
Labels: most-read, stories-STYs, ws-home, ws-stories

#6368 Whitelisting yargs-parser
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#6365 Add link to code reviews guide
  .github/CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/Code-Standards.md
  docs/GPG-Signing-Guide.md
  docs/Project-Board-Guide.md
Labels: ws-home, ws-media-stream, ws-stories

#6364 Log child build variables and show Cosmos version
  Jenkinsfile
Labels: ws-home, ws-media-stream, ws-stories

#6373 [Tech Debt] Replace deprecated waitForElement() with waitFor()
  src/app/contexts/ServiceContext/index.test.jsx
  src/app/contexts/utils/withContext/index.test.jsx
  src/app/pages/ArticlePage/index.test.jsx
  src/app/pages/FrontPage/index.test.jsx
Labels: tech-debt

#6372 [Tech Debt] Replace deprecated wait() with waitFor()
  package-lock.json
  src/app/containers/RadioSchedule/Canonical/index.test.jsx
  src/app/containers/RadioSchedule/index.test.jsx
  src/app/pages/FrontPage/index.test.jsx
Labels: tech-debt

#6355 Dont render include in amp page
  src/app/containers/Include/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/index.jsx
  src/app/containers/Include/index.test.jsx
Labels: ws-stories

#6385 add metadata to most read pageData
  src/app/routes/mostRead/getInitialData/index.js
Labels: most-read, ws-home

#6357 Log embed source status code in media player
  package-lock.json
  src/app/containers/MediaPlayer/helpers/logEmbedSourceStatus/index.js
  src/app/containers/MediaPlayer/helpers/logEmbedSourceStatus/index.test.js
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
  src/app/lib/logger.const.js
Labels: ares-v2, ws-media-stream

#6284 Arabic and hausa translation updates
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.canonical.test.jsx.snap
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/hausa.js
Labels: ws-home

#6398 Skipping canonical e2e script switching test
  cypress/integration/specialFeatures/scriptSwitching/testsForCanonicalOnly.js
Labels: cypress, high-priority

#6389 Log correct routing info in server log when visiting a live radio / on demand radio page
  src/app/routes/liveRadio/getInitialData/index.js
  src/app/routes/liveRadio/getInitialData/index.test.js
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/onDemandRadio/getInitialData/index.test.js
  src/server/index.jsx
Labels: ws-media-stream

#6410 Add external_vpid to supported CPS block types
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.js
Labels: ws-media-stream

#6361 Update Social Embed related CSP directives
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: social-embeds, stories-STYs, ws-stories

#6390 Default image for cps media
  src/app/lib/logger.const.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/media/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/media/index.test.js
Labels: ws-media-stream, ws-stories

#6411 Social embed amp validation fix
  package-lock.json
  package.json
  src/app/containers/SocialEmbed/__snapshots__/index.test.jsx.snap
  src/app/containers/SocialEmbed/index.jsx
Labels: ws-stories

#6436 Disable 27 services on test E2Es
  cypress/support/config/settings.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#6342 Allow StoryPromo headline tag to render without h3 tag
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/index.test.jsx
Labels: ws-home, ws-media-stream, ws-stories

#6395 StoryPromo - log missing media
  scripts/bundleSizeConfig.js
  src/app/containers/StoryPromo/helpers/fixtureData.js
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/lib/logger.const.js
  src/app/lib/utilities/logging/index.js
  src/app/routes/cpsAsset/getInitialData/processUnavailableMedia/index.js
  src/app/routes/cpsAsset/getInitialData/processUnavailableMedia/index.test.js
Labels: ares-v2, ws-home, ws-media-stream, ws-stories

#6424 toggle on social embeds and includes
  src/app/lib/config/toggles/index.js
Labels: ws-stories

#6438 Revert query string removal
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
Labels: ws-stories

#6450 Stabilise MAP E2Es
  3rdPartyCypress/cypress/support/commands.js
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
Labels: ws-media-stream

#6370 Add ati to most read page
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/params/index.js
  src/app/containers/ATIAnalytics/params/mostReadPage/buildParams.js
  src/app/containers/ATIAnalytics/params/mostReadPage/buildParams.test.js
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
Labels: most-read, ws-home

#6462 Removing additional logic for player-episode
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.js
  src/app/containers/ChartbeatAnalytics/utils/index.js
Labels: ws-media-ondemandRadio, ws-media-stream

#6347 Load RequireJs for IDT1 and VJ Includes Only
  data/mundo/cpsAssets/23263889.json
  src/app/containers/Include/index.jsx
  src/app/containers/Include/index.test.jsx
Labels: ws-stories

#6316 AMP Ads GDPR personalisation
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Amp/index.test.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.jsx
  src/app/containers/Ad/index.test.jsx
  src/app/containers/ConsentBanner/index.amp.jsx
  src/integration/pages/articles/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persianTc2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
Labels: ads, ws-home

#6338 Modify getInitialData method to fetch extra data required to render a…
  src/app/pages/StoryPage/index.jsx
  src/app/pages/StoryPage/index.test.jsx
  src/app/routes/cpsAsset/getInitialData/index.js
  src/app/routes/cpsAsset/getInitialData/index.test.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.test.js
  src/app/routes/cpsAsset/utils/getAssetType.js
  src/app/routes/cpsAsset/utils/getAssetType.test.js
  src/app/routes/index.test.jsx
Labels: stories-STYs, ws-stories

#6445 Add standardised test assets
  data/arabic/cpsAssets/23298105.json
  data/ukchina/cpsAssets/simp/23298231.json
  data/ukchina/cpsAssets/trad/23298231.json
Labels: stories-STYs, ws-stories

#6466 add more valid vj include types
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
Labels: stories-STYs, ws-stories

#6465 Update thing types
  src/app/containers/LinkedData/getAboutTagsContent.js
  src/app/containers/LinkedData/getAboutTagsContent.test.js
Labels: ws-stories

#6397 Use detokenised duration in Simorgh for radio schedule
  package-lock.json
  package.json
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/index.jsx
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.js
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.test.js
  src/app/containers/RadioSchedule/utilities/radioScheduleShape.js
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/urdu.js
Labels: radio-schedules, ws-home

#6469 Update navigation items
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
Labels: ws-home

#6412 Add additional ref value to ATI calls
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/atiUrl/index.test.js
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/article/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
Labels: high-priority, ws-home

#6439 Dependency updates
  package-lock.json
  package.json
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#6473 Implement new STY secondary column endpoint
  data/igbo/secondaryColumn/index.json
  data/kyrgyz/secondaryColumn/index.json
  data/mundo/secondaryColumn/index.json
  data/pidgin/secondaryColumn/index.json
  data/zhongwen/secondaryColumn/trad.json
  src/app/lib/utilities/getSecondaryColumnUrl/index.js
  src/app/lib/utilities/getSecondaryColumnUrl/index.test.js
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.jsx
  src/app/pages/StoryPage/index.test.jsx
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.test.js
  src/app/routes/utils/regex/index.js
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: ws-stories

#6426 Replace waitFor(() => {}) with act()
  src/app/pages/FrontPage/index.test.jsx
Labels: tech-debt, ws-home, ws-media-stream, ws-stories

#6486 Updating webpack-dev-server and removing whitelist
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#6496 Update log levels for external_vpid errors
  src/app/lib/utilities/logging/index.js
  src/app/routes/cpsAsset/getInitialData/processUnavailableMedia/index.test.js
Labels: ws-media-stream

#6463 Create A11y-ready OD Radio heading component
  src/app/containers/RadioPageBlocks/Blocks/Datestamp/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/Datestamp/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/Datestamp/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/index.test.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
Labels: a11y, ux, ws-media-ondemandRadio, ws-media-stream

#6490 Use live includes endpoint on test
  envConfig/test.env
Labels: includes, ws-stories

#6494 Update liveradio fixtures
  data/afaanoromoo/bbc_afaanoromoo_radio/liveradio.json
  data/afrique/bbc_afrique_radio/liveradio.json
  data/amharic/bbc_amharic_radio/liveradio.json
  data/arabic/bbc_arabic_radio/liveradio.json
  data/bengali/bbc_bangla_radio/liveradio.json
  data/burmese/bbc_burmese_radio/liveradio.json
  data/gahuza/bbc_gahuza_radio/liveradio.json
  data/hausa/bbc_hausa_radio/liveradio.json
  data/hindi/bbc_hindi_radio/liveradio.json
  data/indonesia/bbc_indonesian_radio/liveradio.json
  data/korean/bbc_korean_radio/liveradio.json
  data/kyrgyz/bbc_kyrgyz_radio/liveradio.json
  data/nepali/bbc_nepali_radio/liveradio.json
  data/pashto/bbc_pashto_radio/liveradio.json
  data/persian/bbc_dari_radio/liveradio.json
  data/persian/bbc_persian_radio/liveradio.json
  data/sinhala/bbc_sinhala_radio/liveradio.json
  data/somali/bbc_somali_radio/liveradio.json
  data/swahili/bbc_swahili_radio/liveradio.json
  data/tamil/bbc_tamil_radio/liveradio.json
  data/tigrinya/bbc_tigrinya_radio/liveradio.json
  data/urdu/bbc_urdu_radio/liveradio.json
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
Labels: ws-media-stream

#6461 Structured data for On Demand Radio page episodes
  scripts/bundleSizeConfig.js
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/AudioObject.jsx
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/AudioObject.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/__snapshots__/AudioObject.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/index.test.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/fixtureData/indonesia.json
  src/app/pages/OnDemandRadioPage/fixtureData/pashto.json
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/media/index.js
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/onDemandRadio/getInitialData/index.test.js
  src/app/routes/utils/getPlaceholderImageUrl/index.js
  src/app/routes/utils/getPlaceholderImageUrl/index.test.js
Labels: ws-media-ondemandRadio, ws-media-stream

#6441 Most read page for amp
  src/app/containers/MostRead/index.jsx
  src/app/containers/MostRead/index.test.jsx
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/index.jsx
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
  src/integration/pages/mostReadPage/ampTests.js
  src/integration/pages/mostReadPage/canonicalTests.js
  src/integration/pages/mostReadPage/crossPlatformTests.js
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/amp.test.js
  src/integration/pages/mostReadPage/mundo/canonical.test.js
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/amp.test.js
  src/integration/pages/mostReadPage/vietnamese/canonical.test.js
Labels: most-read, ws-home

#6467 Update most read to handle Optimo articles in data
  .storybook/static/data/kyrgyz/mostRead/index.json
  data/kyrgyz/mostRead/index.json
  scripts/bundleSizeConfig.js
  src/app/containers/MostRead/Canonical/index.test.jsx
  src/app/containers/MostRead/utilities/mostReadShape.js
  src/app/containers/MostRead/utilities/processMostRead.js
  src/app/containers/MostRead/utilities/processMostRead.test.js
  src/app/containers/MostRead/utilities/testHelpers.jsx
  src/app/lib/logger.const.js
Labels: high-priority, most-read, ws-home

#6514 Fix merge conflict within on-demand audio by renaming imageUrl -> thumbnailImageUrl
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/AudioObject.jsx
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/AudioObject.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/index.test.jsx
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/onDemandRadio/getInitialData/index.test.js
Labels: ws-media-stream

#6518 Remove MAP E2E
  cypress/support/config/settings.js
Labels: ws-home, ws-media-stream, ws-stories

#6393 Psammead grid for onward journeys
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsOnwardJourney/index.jsx
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/index.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/index.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.jsx
Labels: high-priority, ws-stories

#6006 Integration tests for On Demand Radio Pages
  data/indonesia/bbc_indonesian_radio/w172x6r5000f38s.json
  data/pashto/bbc_pashto_radio/w172x8nvf4bchz5.json
  src/integration/common/SEO.js
  src/integration/common/analytics.canonical.js
  src/integration/pages/articles/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persianTc2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/ampTests.js
  src/integration/pages/onDemandRadioEpisode/canonicalTests.js
  src/integration/pages/onDemandRadioEpisode/commonEpisodeTests.js
  src/integration/pages/onDemandRadioEpisode/crossPlatformTests.js
  src/integration/pages/onDemandRadioEpisode/expiredEpisodeTests.js
  src/integration/pages/onDemandRadioEpisode/indonesia.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia.expired/amp.test.js
  src/integration/pages/onDemandRadioEpisode/indonesia.expired/canonical.test.js
  src/integration/pages/onDemandRadioEpisode/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia/amp.test.js
  src/integration/pages/onDemandRadioEpisode/indonesia/canonical.test.js
  src/integration/pages/onDemandRadioEpisode/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto.expired/amp.test.js
  src/integration/pages/onDemandRadioEpisode/pashto.expired/canonical.test.js
  src/integration/pages/onDemandRadioEpisode/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto/amp.test.js
  src/integration/pages/onDemandRadioEpisode/pashto/canonical.test.js
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: ws-media-ondemandRadio, ws-media-stream

#6522 Updating snapshots for pashto expired on demand radio episode
  package.json
  src/integration/pages/onDemandRadioEpisode/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto.expired/__snapshots__/canonical.test.js.snap
Labels: ws-media-stream

#6343 Create Canonical Ad Container
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.jsx
  src/app/containers/Ad/index.test.jsx
  src/app/contexts/ToggleContext/index.test.jsx
Labels: ads, ws-home

#6504 Replace waitForDomChange with waitFor
  package-lock.json
  package.json
  src/app/containers/ArticleMetadata/index.test.jsx
  src/app/containers/CpsMetadata/index.test.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/pages/ArticlePage/index.test.jsx
  src/app/pages/MediaAssetPage/index.test.jsx
Labels: ws-home, ws-media-stream, ws-stories

#6530 Updating asset from V1 to V2
  data/afaanoromoo/bbc_afaanoromoo_radio/w3cszx1y.json
  data/afrique/bbc_afrique_radio/w172x601yx5z2n1.json
  data/amharic/bbc_amharic_radio/w3csz5r9.json
  data/arabic/bbc_arabic_radio/w3ct01yb.json
  data/bengali/bbc_bangla_radio/w172x0562jxntqx.json
  data/burmese/bbc_burmese_radio/w3csz62h.json
  data/gahuza/bbc_gahuza_radio/w172x7rkcj6v0vz.json
  data/hausa/bbc_hausa_radio/w3cszrwm.json
  data/indonesia/bbc_indonesian_radio/w172x6r5000f38s.json
  data/indonesia/bbc_indonesian_radio/w172xh267fpn19l.json
  data/korean/bbc_korean_radio/w3ct0kn5.json
  data/kyrgyz/bbc_kyrgyz_radio/w3cszwmc.json
  data/nepali/bbc_nepali_radio/w172x83pnptp1s8.json
  data/pashto/bbc_pashto_radio/w172x8nvf4bchz5.json
  data/persian/bbc_dari_radio/w3csz7mf.json
  data/persian/bbc_persian_radio/w172x32355t5635.json
  data/sinhala/bbc_sinhala_radio/w172x8zn8th1lwb.json
  data/somali/bbc_somali_radio/w172x90wfxd2qh4.json
  data/swahili/bbc_swahili_radio/w172x94ky63591m.json
  data/tamil/bbc_tamil_radio/w172x966tn9jwmh.json
  data/tigrinya/bbc_tigrinya_radio/w3cszzz1.json
  data/urdu/bbc_urdu_radio/w172x9dx052c8sr.json
  data/uzbek/bbc_uzbek_radio/w172x9f9qjcq3lm.json
Labels: ws-media-ondemandRadio, ws-media-stream

#6517 Includes, resolve P2 a11y bug - page-level horizontal scrollbar
  data/gahuza/cpsAssets/23299713.json
  src/app/containers/Include/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/index.jsx
Labels: a11y, bug, includes, ws-stories

#6492 Dependency updates
  package-lock.json
  package.json
  src/integration/pages/onDemandRadioEpisode/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto.expired/__snapshots__/canonical.test.js.snap
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#6544 Updating pashto asset again
  data/pashto/bbc_pashto_radio/w172x8nvf4bchz5.json
  src/integration/pages/onDemandRadioEpisode/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto.expired/__snapshots__/canonical.test.js.snap
Labels: high-priority

#6508 Add fixture data for STY secondary column
  data/afaanoromoo/secondaryColumn/index.json
  data/afrique/secondaryColumn/index.json
  data/amharic/secondaryColumn/index.json
  data/arabic/secondaryColumn/index.json
  data/azeri/secondaryColumn/index.json
  data/bengali/secondaryColumn/index.json
  data/burmese/secondaryColumn/index.json
  data/gahuza/secondaryColumn/index.json
  data/gujarati/secondaryColumn/index.json
  data/hausa/secondaryColumn/index.json
  data/hindi/secondaryColumn/index.json
  data/indonesia/secondaryColumn/index.json
  data/japanese/secondaryColumn/index.json
  data/korean/secondaryColumn/index.json
  data/marathi/secondaryColumn/index.json
  data/nepali/secondaryColumn/index.json
  data/pashto/secondaryColumn/index.json
  data/persian/secondaryColumn/index.json
  data/portuguese/secondaryColumn/index.json
  data/punjabi/secondaryColumn/index.json
  data/russian/secondaryColumn/index.json
  data/serbian/secondaryColumn/cyr.json
  data/serbian/secondaryColumn/lat.json
  data/sinhala/secondaryColumn/index.json
  data/somali/secondaryColumn/index.json
  data/swahili/secondaryColumn/index.json
  data/tamil/secondaryColumn/index.json
  data/telugu/secondaryColumn/index.json
  data/thai/secondaryColumn/index.json
  data/tigrinya/secondaryColumn/index.json
  data/turkce/secondaryColumn/index.json
  data/ukchina/secondaryColumn/simp.json
  data/ukchina/secondaryColumn/trad.json
  data/ukrainian/secondaryColumn/index.json
  data/urdu/secondaryColumn/index.json
  data/uzbek/secondaryColumn/index.json
  data/vietnamese/secondaryColumn/index.json
  data/yoruba/secondaryColumn/index.json
  data/zhongwen/secondaryColumn/simp.json
Labels: stories-STYs, ws-stories

#6481 add lunar-light background to amp ads container
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/index.jsx
  src/app/pages/FrontPage/index.test.jsx
Labels: ads, ws-home

#6513 Enable a11y test on most read page
  a11y.js
  cypress/support/config/settings.js
Labels: most-read, ws-home

#6471 Display audio episode image for OD radio page
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/OnDemandImage/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/OnDemandImage/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/OnDemandImage/index.test.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/fixtureData/indonesia.json
  src/app/pages/OnDemandRadioPage/fixtureData/pashto.json
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/onDemandRadio/getInitialData/index.test.js
Labels: a11y, ws-media-ondemandRadio, ws-media-stream

#6547 Updated Pashto fixture data OD-episode image
  data/pashto/bbc_pashto_radio/w3ct0lz1.json
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/fixtureData/pashto.json
  src/app/routes/onDemandRadio/getInitialData/index.test.js
  src/integration/pages/onDemandRadioEpisode/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto/__snapshots__/canonical.test.js.snap
Labels: ux, ws-media-ondemandRadio, ws-media-stream

#6483 Update tests for STY features
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsFeaturesAnalysis/index.test.jsx
  src/app/containers/CpsTopStories/index.jsx
  src/app/containers/CpsTopStories/index.test.jsx
  src/app/containers/MostRead/index.test.jsx
  src/app/pages/StoryPage/fixtureData/mundo.json
  src/app/pages/StoryPage/fixtureData/persian.json
Labels: stories-STYs, ws-stories

#6502 Amp Ad Breakpoint fix
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
Labels: ads, bug, ws-home

#6505 Disable SMP status logging
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
Labels: ws-media-stream

#6549 Update Most Read Optimo logic and fixture
  data/kyrgyz/mostRead/index.json
  src/app/containers/MostRead/utilities/processMostRead.js
  src/app/containers/MostRead/utilities/processMostRead.test.js
Labels: most-read, ws-home

#6556 run inline scripts in integration tests for window.SIMORGH_DATA
  src/integration/common/analytics.canonical.js
  src/integration/pages/articles/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persianTc2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/utils/fetchDom.js
Labels: ws-home, ws-media-stream

#6548 Update footer links for Sinhala, Nepali and UkChina
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/ukchina.js
Labels: ws-home

#6550 On Demand Radio Brand Simorgh routing
  data/indonesia/bbc_indonesian_radio/w13xtt0s.json
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
Labels: ws-media-ondemandRadio, ws-media-stream

#6506 Create IDX Skeleton Page
  src/app/contexts/RequestContext/index.jsx
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/index.jsx
  src/app/pages/IdxPage/index.stories.jsx
  src/app/pages/IdxPage/index.test.jsx
  src/app/pages/index.js
  src/app/routes/idx/index.js
  src/app/routes/index.js
  src/app/routes/utils/regex/index.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
Labels: IDX, ws-home

#6564 Splitting up radio and tv regexes
  src/app/routes/onDemandRadio/index.js
  src/app/routes/utils/regex/index.js
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
  src/server/index.jsx
Labels: ws-media-ondemandRadio, ws-media-stream

#6567 Add Pashto fixture data for Radio Brand
  data/pashto/bbc_pashto_radio/p0340yr4.json
Labels: ws-media-ondemandRadio, ws-media-stream

#6427 Adds missing csp directives for VJ includes
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: includes, stories-STYs, ws-stories

#6391 Run BBC-a11y against STY assets
  a11y.js
  cypress/support/config/settings.js
Labels: stories-STYs, ws-stories

#6552 Dependency update
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#6585 Temporarily whitelist markdown-to-jsx from audit-ci
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#6578 Adding integration tests for Radio Brand page
  src/integration/pages/onDemandRadioEpisode/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashtoBrand/amp.test.js
  src/integration/pages/onDemandRadioEpisode/pashtoBrand/canonical.test.js
Labels: ws-media-ondemandRadio, ws-media-stream

#6590 OD & Live radio UX text fixes
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/index.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
Labels: ux, ws-media- LiveRadioV1, ws-media-ondemandRadio, ws-media-stream

#6576 Bump @bbc/psammead-social-embed
  package-lock.json
  package.json
  src/app/containers/SocialEmbed/__snapshots__/index.test.jsx.snap
  src/app/containers/SocialEmbed/index.test.jsx
Labels: bug, social-embeds, stories-STYs, ws-stories

#6561 update sizes attribute to reflect the image size in the browser correctly
  src/app/containers/RadioPageBlocks/Blocks/OnDemandImage/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/OnDemandImage/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/OnDemandImage/index.test.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
Labels: ws-media-stream

#6560 Ensure CSP violations are reported
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-stories

#6592 OD radio styling of BrandTitle to match a11y guidelines
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/index.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
Labels: a11y, ws-media-ondemandRadio, ws-media-stream

#6575 Bump psammead-timestamp-container version to 4.0.0 & radio-schedule to 3.0.5
  package-lock.json
  package.json
Labels: ws-media-ondemandRadio, ws-media-stream

#6565 Re-enable script switching E2E tests
  cypress/integration/specialFeatures/scriptSwitching/testsForCanonicalOnly.js
Labels: ws-media-stream

#6562 Front Page: Add integration tests and remove these from Cypress
  cypress/integration/pages/frontPage/tests.js
  src/integration/README.md
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/crossPlatformTests.js
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
Labels: ws-home

#6571 OnDemand TV Page Routing
  data/afrique/bbc_afrique_tv/w13xttmz.json
  data/pashto/bbc_pashto_tv/w13xttn4.json
  src/app/pages/OnDemandTvPage/fixtureData/afrique.json
  src/app/pages/OnDemandTvPage/fixtureData/pashto.json
  src/app/pages/OnDemandTvPage/index.jsx
  src/app/pages/OnDemandTvPage/index.stories.jsx
  src/app/pages/OnDemandTvPage/index.test.jsx
  src/app/pages/index.js
  src/app/routes/index.js
  src/app/routes/index.test.jsx
  src/app/routes/onDemandTV/getInitialData/index.js
  src/app/routes/onDemandTV/getInitialData/index.test.js
  src/app/routes/onDemandTV/index.js
  src/app/routes/utils/regex/index.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: ws-media-onDemandTV, ws-media-stream

#6588 Reinstate Mozart fallback checks for smoke e2es
  3rdPartyCypress/cypress/support/commands.js
  cypress/support/commands/application.js
Labels: ws-home, ws-media-stream, ws-stories

#6595 Do not display timestamp for Story Promos with type 'Guide'
  src/app/containers/StoryPromo/helpers/fixtureData.js
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
Labels: ws-home

#6566 Fix include overflow
  src/app/containers/Include/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/index.jsx
Labels: ws-stories

#6511 Update most read logging for data fetching
  scripts/bundleSizeConfig.js
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/Canonical/index.test.jsx
  src/app/containers/MostRead/index.test.jsx
  src/app/containers/MostRead/utilities/processMostRead.js
  src/app/containers/MostRead/utilities/processMostRead.test.js
  src/app/lib/logger.const.js
  src/testHelpers/loggerMock.js
Labels: most-read, ws-home

#6574 Hide BBC placeholder blocks when an image has loaded
  cypress/integration/pages/articles/tests.js
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/ImageWithPlaceholder/__snapshots__/index.test.jsx.snap
  src/app/containers/ImageWithPlaceholder/index.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: ws-stories

#6620 Add translations
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/yoruba.js
Labels: stories-STYs, ws-stories

#6589 Add local route to Simorgh for IDX data
  data/persian/afghanistan/index.json
  data/ukrainian/ukraine_in_russian/index.json
  src/app/routes/utils/regex/index.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: IDX, ws-home

#6622 Front Page: Add integration tests and remove these from Cypress - Part 2
  cypress/integration/pages/frontPage/tests.js
  src/integration/pages/frontPage/ampTests.js
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/canonicalTests.js
  src/integration/pages/frontPage/crossPlatformTests.js
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/crossPlatformTests.js
  src/integration/pages/mostReadPage/crossPlatformTests.js
  src/integration/pages/storyPage/crossPlatformTests.js
Labels: ws-home

#6488 Display AMP Ads "Advertisement" label
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Amp/index.test.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
Labels: ads, ws-home

#6607 Use title translations
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsFeaturesAnalysis/index.test.jsx
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/index.jsx
  src/app/containers/CpsTopStories/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: high-priority, stories-STYs, ws-stories

#6603 Add items to CSP
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-stories

#6640 Create amp validator tool to improve amp validation process
  a11y.js
  cypress/support/helpers/getPageUrls.js
  package.json
  scripts/ampHtmlValidator/cli.js
  scripts/ampHtmlValidator/index.js
  scripts/ampHtmlValidator/index.test.js
  scripts/dependencyCheck.js
Labels: ws-home, ws-media-stream, ws-stories

#6667 Enable PGL E2E assets on all envs
  cypress/support/config/settings.js
Labels: stories-pgl, ws-stories

#6656 Enable the STY e2e's on localhost and test and enable smoke testing f…
  cypress/integration/specialFeatures/scriptSwitching/testsForCanonicalOnly.js
  cypress/support/config/settings.js
  data/gahuza/cpsAssets/23307435.json
  data/ukchina/cpsAssets/simp/23307454.json
  data/ukchina/cpsAssets/trad/23307454.json
  data/ukchina/secondaryColumn/simp.json
Labels: stories-STYs, ws-stories

#6610 Add OD-radio episode hero image integration test
  src/integration/pages/onDemandRadioEpisode/commonEpisodeTests.js
  src/integration/pages/onDemandRadioEpisode/indonesia.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia.expired/amp.test.js
  src/integration/pages/onDemandRadioEpisode/indonesia.expired/canonical.test.js
  src/integration/pages/onDemandRadioEpisode/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto.expired/amp.test.js
  src/integration/pages/onDemandRadioEpisode/pashto.expired/canonical.test.js
  src/integration/pages/onDemandRadioEpisode/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashtoBrand/__snapshots__/canonical.test.js.snap
Labels: ws-media-ondemandRadio, ws-media-stream

#6543 Suppress rendering of secondary column
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.jsx
  src/app/pages/StoryPage/index.stories.jsx
  src/app/pages/StoryPage/index.test.jsx
Labels: bug, stories-STYs, ux, ws-stories

#6671 Fix TravisCI config
  .travis.yml
Labels: tech-debt

#6371 Cypress test for Most read pagetype
  cypress/integration/pages/mostReadPage/index.js
  cypress/integration/pages/mostReadPage/tests.js
  cypress/integration/pages/mostReadPage/testsForAMPOnly.js
  cypress/integration/pages/mostReadPage/testsForCanonicalOnly.js
  cypress/integration/pages/testsForAllPages.js
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/index.jsx
Labels: most-read, ws-home

#6456 Add GNL Canonical Ad Implementation
  src/app/containers/Ad/Canonical/AdSlot.jsx
  src/app/containers/Ad/Canonical/AdSlot.test.jsx
  src/app/containers/Ad/Canonical/CanonicalAdBootstrapJs.jsx
  src/app/containers/Ad/Canonical/CanonicalAdBootstrapJs.test.jsx
  src/app/containers/Ad/Canonical/__snapshots__/AdSlot.test.jsx.snap
  src/app/containers/Ad/Canonical/__snapshots__/CanonicalAdBootstrapJs.test.jsx.snap
  src/app/containers/Ad/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/Canonical/index.test.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.test.jsx
  src/app/pages/FrontPage/index.jsx
  src/app/pages/FrontPage/index.test.jsx
  src/app/routes/index.test.jsx
Labels: ads, ws-home

#6676 Disabled live radio e2es for 18 services
  cypress/support/config/settings.js
Labels: cypress, ws-media- LiveRadioV1, ws-media-stream

#6685 Update Release Info
  docs/Simorgh-Release-Info.md
Labels: Documentation, stories-STYs, ws-stories

#6695 Remove Canonical Ads
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.jsx
Labels: ads, bug, ws-home

#6681 Update some translations for UK China
  src/app/lib/config/services/ukchina.js
Labels: ws-stories

#6686 Post Live: Enable Live E2Es for Ukchina and Gahuza
  cypress/support/config/settings.js
Labels: ws-stories

#6693 Adding Episode information to TV Page
  data/pashto/bbc_pashto_tv/w13xttn4.json
  src/app/pages/OnDemandTvPage/index.jsx
  src/app/pages/OnDemandTvPage/index.test.jsx
  src/app/routes/onDemandTV/getInitialData/index.js
  src/app/routes/onDemandTV/getInitialData/index.test.js
Labels: ws-media-onDemandTV, ws-media-stream

#6692 ATI Analytics Refactor for both OD Radio and TV
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/params/index.js
  src/app/containers/ATIAnalytics/params/tvRadioPage/buildParams.js
  src/app/containers/ATIAnalytics/params/tvRadioPage/buildParams.test.js
  src/app/pages/OnDemandTvPage/index.jsx
  src/app/routes/onDemandTV/getInitialData/index.js
Labels: ws-media-onDemandTV, ws-media-stream

#6646 Dependency updates
  package-lock.json
  package.json
  src/app/containers/BulletedList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsText/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  webpack.config.client.js
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#6708 Translation updates for Nepali, Vietnamese, and Thai
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/vietnamese.js
Labels: ws-home, ws-stories

#6677 Moving chromatic to its own Jenkins stage
  Jenkinsfile
  Makefile
Labels: tech-debt, ws-home, ws-media-stream, ws-stories

#6680 Update most read page log
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/utilities/processMostRead.js
  src/app/containers/MostRead/utilities/processMostRead.test.js
Labels: ws-home

#6593 encode x6 and x5 on canonical
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/article/buildParams.test.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/ATIAnalytics/params/mostReadPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/tvRadioPage/buildParams.test.js
Labels: ws-home

#6691 Update release info
  cypress/support/config/settings.js
  docs/Simorgh-Release-Info.md
  scripts/simorghLaunchDates.js
  scripts/simorghPages.js
Labels: ws-home

#6699 Update Most Read Page Grid column (Group 5)
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/index.jsx
Labels: most-read, ux, ws-home
