Repository bbc/simorgh, pull requests merged in 2020-04, with the labels that each got.

#5585 Code Reviews guide
  docs/Code-Reviews.md
Labels: ws-home, ws-media-stream, ws-stories

#6024 Social embeds - translations
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: social-embeds, ws-stories

#6027 Create service toggle for radio-schedules on front-pages
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/urdu.js
  src/app/pages/FrontPage/index.jsx
Labels: radio-schedules, ws-home

#6042 Navigation updates for Nepali & Indonesia
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/nepali.js
Labels: ws-home

#6023 Russian and Hindi config updates
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/russian.js
Labels: ws-home

#6065 Arabic translation updates
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/arabic.js
  src/app/pages/FrontPage/index.stories.jsx
Labels: ws-home

#6069 Update Russian trust project link
  src/app/lib/config/services/russian.js
Labels: ws-home

#6040 Remove list wrapper from CPSRelatedContent when it has a single item
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsRelatedContent/index.stories.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: a11y, bug, ws-media-stream, ws-stories

#6071 Suppress timestamp on LIV promos
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
Labels: high-priority, ws-home

#6046 Remove list wrapper from FeatureAnalysis when it has a single item
  src/app/containers/FeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/FeaturesAnalysis/index.jsx
  src/app/containers/FeaturesAnalysis/index.stories.jsx
  src/app/containers/FeaturesAnalysis/index.test.jsx
Labels: a11y, bug, ws-media-stream, ws-stories

#6077 Move Social Embed translations into the correct block
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
Labels: social-embeds, stories-STYs, ws-stories

#6076 Update russian live label
  src/app/lib/config/services/russian.js
Labels: ws-home

#6058 Remove penultimate story promo list border
  package-lock.json
  package.json
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/FeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/index.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/articlePage/__snapshots__/pidgin.test.js.snap
Labels: ws-home

#5180 Move Simorgh pages from wiki to docs
  .codeclimate.yml
  README.md
  cypress/integration/README.md
  cypress/support/config/services.js
  cypress/support/config/settings.js
  cypress/support/helpers/runTestsForPage.js
  docs/Simorgh-Release-Info.md
  scripts/simorghLaunchDates.js
  scripts/simorghPages.js
Labels: ws-media-stream

#6018 Standarise logging
  scripts/bundleSizeConfig.js
  src/app/contexts/RequestContext/getOriginContext/index.js
  src/app/lib/README.md
  src/app/lib/logger.const.js
  src/app/lib/logger.node.js
  src/app/lib/logger.node.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.js
  src/app/routes/cpsAsset/getInitialData/processUnavailableMedia/index.js
  src/app/routes/utils/fetchPageData/index.js
  src/app/routes/utils/fetchPageData/index.test.js
  src/index.js
  src/server/index.jsx
  src/server/utilities/logResponseTime/index.js
  src/server/utilities/logResponseTime/index.test.js
Labels: ws-home, ws-media-stream, ws-stories

#6084 Update Burmese LIVE translation
  src/app/lib/config/services/burmese.js
Labels: ws-home

#6019 [DNM] Escape '<' in JSON strings
  scripts/bundleSizeConfig.js
  src/app/containers/LinkedData/index.jsx
  src/app/lib/utilities/serialiseForScript/index.js
  src/app/lib/utilities/serialiseForScript/index.test.js
  src/server/Document/component.jsx
Labels: stories-STYs, ws-home, ws-media-stream, ws-stories

#5913 feat: add top stories
  scripts/simorghPages.js
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/index.jsx
  src/app/containers/CpsTopStories/index.stories.jsx
  src/app/containers/CpsTopStories/index.test.jsx
  src/app/containers/FrontPageStoryRows/index.jsx
  src/app/containers/StoryPromo/index.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.jsx
  src/app/pages/StoryPage/topStories.json
  src/app/pages/StoryPage/topStoriesRtl.json
  src/integration/pages/articlePage/__snapshots__/pidgin.test.js.snap
Labels: a11y-swarm, ws-home, ws-stories

#6087 Fix related content tests on MAP pages
  cypress/integration/pages/mediaAssetPage/tests.js
Labels: ws-media-stream

#6091 E2E URLs in local and test for Afrique, Portuguese/Brasil, Mundo and Japanese
  cypress/support/config/settings.js
  data/afrique/cpsAssets/region-23278969.json
  data/afrique/legacyAssets/nos_emissions/2016/06/160622_tc2_testmap1.json
  data/mundo/cpsAssets/media-23283126.json
  data/mundo/legacyAssets/noticias/2016/04/160427_tc2_testmap1.json
  data/portuguese/cpsAssets/media-23282671.json
  data/portuguese/legacyAssets/revista/2016/05/160506_tc2_map_0605.json
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#6053 Update Content Security Policy Header & use in localhost
  src/server/index.jsx
  src/server/utilities/constructCspHeader/index.js
  src/server/utilities/constructCspHeader/index.test.js
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-home

#6034 repurpose live radio block to serve OD episodes
  scripts/bundleSizeConfig.js
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/index.jsx
  src/app/lib/config/services/afaanoromoo.js
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/pages/OnDemandRadioPage/index.test.jsx
  src/app/pages/RadioPage/__snapshots__/index.test.jsx.snap
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/integration/pages/liveRadioPage/__snapshots__/amharic.test.js.snap
  src/integration/pages/liveRadioPage/__snapshots__/korean.test.js.snap
Labels: ws-media-stream

#6092 Fix Live TV Bulletin story in Storybook
  data/igbo/frontpage/index.json
  src/app/routes/home/getInitialData/filterUnknownContentTypes/__snapshots__/index.test.js.snap
  src/app/routes/home/getInitialData/squashTopStories/__snapshots__/index.test.js.snap
Labels: ws-home

#6098 Update Persian navigation
  src/app/lib/config/services/persian.js
Labels: ws-home

#6096 Story Promo Timestamp update - enable dual calendars
  data/pashto/cpsAssets/columns-52106293.json
  data/persian/cpsAssets/arts-52166891.json
  scripts/bundleSizeConfig.js
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
Labels: ws-home, ws-media-stream, ws-stories

#5997 Update package-lock to remove minimist vulnerability
  package-lock.json
  package.json
  src/app/containers/Bulletin/__snapshots__/index.test.jsx.snap
  src/app/containers/Bulletin/index.test.jsx
  src/app/contexts/EventContext/__snapshots__/index.test.jsx.snap
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#6103 Pull in latest radio schedule version
  package-lock.json
  package.json
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
Labels: high-priority, radio-schedules, ws-home

#6111 [DO NOT MERGE] Added live CPS and TC2 asset URLS to Afrique, Portuguese/Brasil/, Mundo and Japanese.
  cypress/support/config/settings.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#6127 pass service to embed url
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/index.jsx
  src/app/pages/OnDemandRadioPage/index.test.jsx
Labels: ws-media-stream

#6126 Add spacing below on-demand radio player for expired episode message
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/index.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/RadioPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/liveRadioPage/__snapshots__/amharic.test.js.snap
  src/integration/pages/liveRadioPage/__snapshots__/korean.test.js.snap
Labels: ws-media-stream

#5971 Integration tests for frontpage
  .env
  src/integration/common/a11y.js
  src/integration/pages/articlePage/mundo.test.js
  src/integration/pages/articlePage/pidgin.test.js
  src/integration/pages/frontPage/__snapshots__/arabic.test.js.snap
  src/integration/pages/frontPage/__snapshots__/pidgin.test.js.snap
  src/integration/pages/frontPage/arabic.test.js
  src/integration/pages/frontPage/pidgin.test.js
  src/integration/pages/frontPage/user.amp.js
  src/integration/pages/frontPage/user.canonical.js
  src/integration/pages/liveRadioPage/amharic.test.js
  src/integration/pages/liveRadioPage/korean.test.js
Labels: ws-home

#5739 Adds MostRead to STY's second column
  package-lock.json
  package.json
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/index.jsx
  src/app/containers/MostRead/index.stories.jsx
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/index.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.jsx
  src/app/pages/StoryPage/index.stories.jsx
  src/integration/pages/articlePage/__snapshots__/pidgin.test.js.snap
Labels: most-read, stories-STYs, ws-home, ws-stories

#6104 Add radio schedules position to service config
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/pages/FrontPage/index.jsx
Labels: radio-schedules, ws-home

#6083 Remove x_candy_override from related content links
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/articlePage/__snapshots__/pidgin.test.js.snap
Labels: ws-home, ws-media-stream, ws-stories

#6132 use localised no js error message in audio player
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/index.jsx
  src/integration/pages/liveRadioPage/__snapshots__/amharic.test.js.snap
  src/integration/pages/liveRadioPage/__snapshots__/korean.test.js.snap
Labels: ws-media-stream

#6113 Removes encoding/decoding logic and references include fetch url to test
  data/mundo/cpsAssets/23263889.json
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  scripts/bundleSizeConfig.js
  src/app/containers/Include/index.jsx
  src/app/containers/Include/index.test.jsx
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
Labels: includes, ws-stories, ws-sty-page-v1

#6110 Related content in main fix
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.jsx
  src/integration/pages/articlePage/__snapshots__/pidgin.test.js.snap
Labels: ws-stories

#6153 add link to CSP maintenance doc
  src/server/utilities/cspHeader/index.js
Labels: ws-home, ws-media-stream, ws-stories

#6106 Story page RTL
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/pages/StoryPage/fixtureData/mundo.json
  src/app/pages/StoryPage/fixtureData/persian.json
  src/app/pages/StoryPage/index.jsx
  src/app/pages/StoryPage/index.stories.jsx
  src/integration/pages/articlePage/__snapshots__/pidgin.test.js.snap
Labels: ws-stories

#6172 Use morph_env override to ensure live data is available on test for OD radio
  src/app/lib/utilities/getEmbedUrl/index.js
  src/app/lib/utilities/getEmbedUrl/index.test.js
Labels: ws-media-ondemandRadio, ws-media-stream

#6178 Fix Storybook Moment stories for RTL services to have correct direction
  src/app/lib/utilities/moment/index.stories.jsx
Labels: ws-home

#6079 Amp access toggle for ads
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Amp/index.test.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.jsx
  src/app/containers/Ad/index.test.jsx
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/zhongwen.js
  src/integration/pages/frontPage/__snapshots__/arabic.test.js.snap
  src/integration/pages/frontPage/__snapshots__/pidgin.test.js.snap
Labels: AMP, ads, ws-home

#6174 Urls ukchina serbian zhongwen test
  cypress/support/config/settings.js
  data/serbian/cpsAssets/cyr/23279016.json
  data/serbian/cpsAssets/lat/23279016.json
  data/ukchina/cpsAssets/simp/23279012.json
  data/ukchina/cpsAssets/trad/23279012.json
  data/ukchina/legacyAssets/simp/multimedia/2016/11/161104_tc2_testmap1.json
  data/ukchina/legacyAssets/trad/multimedia/2016/11/161104_tc2_testmap1.json
  data/zhongwen/cpsAssets/simp/uk-23283128.json
  data/zhongwen/cpsAssets/trad/uk-23283128.json
  data/zhongwen/legacyAssets/simp/multimedia/2016/11/161107_tc2_testmap1.json
  data/zhongwen/legacyAssets/trad/multimedia/2016/11/161107_tc2_testmap1.json
  src/app/lib/utilities/getEmbedUrl/index.js
  src/app/lib/utilities/getEmbedUrl/index.test.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#6171 Updated getInitialData to accept an object of path/service
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/routes/article/getInitialData/index.js
  src/app/routes/article/getInitialData/index.test.js
  src/app/routes/cpsAsset/getInitialData/index.js
  src/app/routes/cpsAsset/getInitialData/index.test.js
  src/app/routes/error/getInitialData/index.js
  src/app/routes/error/getInitialData/index.test.js
  src/app/routes/home/getInitialData/index.js
  src/app/routes/home/getInitialData/index.test.js
  src/app/routes/index.test.jsx
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/onDemandRadio/getInitialData/index.test.js
  src/app/routes/radio/getInitialData/index.js
  src/app/routes/radio/getInitialData/index.test.js
  src/server/index.jsx
Labels: most-read, radio-schedules, ws-home

#5880 MAP integration tests
  package.json
  src/integration/common/a11y.js
  src/integration/common/index.js
  src/integration/common/snapshot.js
  src/integration/pages/articlePage/__snapshots__/mundo.test.js.snap
  src/integration/pages/articlePage/__snapshots__/pidgin.test.js.snap
  src/integration/pages/articlePage/mundo.test.js
  src/integration/pages/articlePage/pidgin.test.js
  src/integration/pages/frontPage/__snapshots__/arabic.test.js.snap
  src/integration/pages/frontPage/__snapshots__/pidgin.test.js.snap
  src/integration/pages/frontPage/arabic.test.js
  src/integration/pages/frontPage/pidgin.test.js
  src/integration/pages/liveRadioPage/__snapshots__/amharic.test.js.snap
  src/integration/pages/liveRadioPage/__snapshots__/korean.test.js.snap
  src/integration/pages/liveRadioPage/amharic.test.js
  src/integration/pages/liveRadioPage/korean.test.js
  src/integration/pages/liveRadioPage/user.amp.js
  src/integration/pages/liveRadioPage/user.canonical.js
  src/integration/pages/mediaAssetPage/__snapshots__/persian.tc2.test.js.snap
  src/integration/pages/mediaAssetPage/__snapshots__/persian.test.js.snap
  src/integration/pages/mediaAssetPage/__snapshots__/pidgin.test.js.snap
  src/integration/pages/mediaAssetPage/a11y.amp.js
  src/integration/pages/mediaAssetPage/a11y.canonical.js
  src/integration/pages/mediaAssetPage/persian.tc2.test.js
  src/integration/pages/mediaAssetPage/persian.test.js
  src/integration/pages/mediaAssetPage/pidgin.test.js
  src/integration/pages/mediaAssetPage/user.amp.js
  src/integration/pages/mediaAssetPage/user.canonical.js
  src/integration/pages/mediaAssetPage/user.js
Labels: ws-media-stream

#6186 Remove query string
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
Labels: includes, ws-stories

#6048 a11y integration test for live radio pages
  src/integration/pages/liveRadioPage/__snapshots__/amharic.test.js.snap
  src/integration/pages/liveRadioPage/__snapshots__/korean.test.js.snap
  src/integration/pages/liveRadioPage/a11y.amp.js
  src/integration/pages/liveRadioPage/a11y.canonical.js
  src/integration/pages/liveRadioPage/amharic.test.js
  src/integration/pages/liveRadioPage/korean.test.js
Labels: ws-media-stream

#6107 Translation updates for Marathi, Swahili, Igbo, Japanese, Somali, Afrique, Arabic, and Korean
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/integration/common/footer.js
  src/integration/pages/articlePage/mundo.test.js
  src/integration/pages/articlePage/pidgin.test.js
  src/integration/pages/frontPage/__snapshots__/arabic.test.js.snap
  src/integration/pages/frontPage/arabic.test.js
  src/integration/pages/frontPage/pidgin.test.js
  src/integration/pages/liveRadioPage/__snapshots__/korean.test.js.snap
  src/integration/pages/liveRadioPage/amharic.test.js
  src/integration/pages/liveRadioPage/korean.test.js
  src/integration/pages/mediaAssetPage/persian.tc2.test.js
  src/integration/pages/mediaAssetPage/persian.test.js
  src/integration/pages/mediaAssetPage/pidgin.test.js
Labels: ws-home

#5983 Social Embeds - STY Integration
  data/igbo/cpsAssets/afirika-23252735.json
  data/mundo/cpsAssets/23263889.json
  data/mundo/cpsAssets/embeds-23263889.json
  data/mundo/cpsAssets/noticias-internacional-51266689.json
  data/pidgin/cpsAssets/world-23252817.json
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/SocialEmbed/__snapshots__/index.test.jsx.snap
  src/app/containers/SocialEmbed/fixtures.js
  src/app/containers/SocialEmbed/index.jsx
  src/app/containers/SocialEmbed/index.stories.jsx
  src/app/containers/SocialEmbed/index.test.jsx
  src/app/containers/SocialEmbed/testHelper.jsx
  src/app/containers/SocialEmbed/translations.js
  src/app/containers/SocialEmbed/translations.test.js
  src/app/lib/config/toggles/index.js
  src/app/models/propTypes/socialEmbed/index.js
  src/app/pages/StoryPage/index.jsx
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/socialEmbed/fixtures.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/socialEmbed/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/socialEmbed/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.js
  src/integration/pages/mediaAssetPage/__snapshots__/pidgin.test.js.snap
Labels: a11y-swarm, social-embeds, stories-STYs, ws-stories

#6179 change datetime format for specific datetime locales
  src/app/containers/ArticleTimestamp/helpers.js
  src/app/containers/ArticleTimestamp/helpers.test.js
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/ArticleTimestamp/timeFormatTests/expectedFormats.json
  src/app/containers/ArticleTimestamp/timeFormatTests/generateTimeFormats.js
  src/app/containers/ArticleTimestamp/timeFormatTests/testUtils.js
  src/app/containers/ArticleTimestamp/timeFormats.js
Labels: ws-media-stream, ws-stories

#6191 Test URLs and fixture data added for Hindi and Arabic
  cypress/support/config/settings.js
  data/arabic/cpsAssets/world-23278971.json
  data/arabic/legacyAssets/worldnews/2015/11/151120_t_arabic_av.json
  data/hindi/cpsAssets/23201477.json
  data/hindi/legacyAssets/sport/2016/08/160822_tc2_testmap1.json
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#6147 Update to Node v12.16.2 and npm 6.14.4
  .npmrc
  .nvmrc
  Jenkinsfile
Labels: ws-home, ws-media-stream, ws-stories

#6199 retry strategy for dom fetch in integration tests
  package-lock.json
  package.json
  src/integration/render.js
  src/integration/render.test.js
Labels: ws-media-stream

#6189 Audio player layout fixes
  a11y.js
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/index.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/pages/RadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/RadioPage/index.jsx
  src/integration/pages/liveRadioPage/__snapshots__/amharic.test.js.snap
  src/integration/pages/liveRadioPage/__snapshots__/korean.test.js.snap
Labels: ws-media-stream

#6211 Removes unnecessary secondary column component placeholder
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.jsx
Labels: ws-stories

#6212 fix audio player edge alignment for RTL langs also
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/index.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/pages/RadioPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/liveRadioPage/__snapshots__/amharic.test.js.snap
  src/integration/pages/liveRadioPage/__snapshots__/korean.test.js.snap
Labels: ws-media-stream

#6128 Update dependencies
  package-lock.json
  package.json
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/frontPage/__snapshots__/arabic.test.js.snap
  src/integration/pages/frontPage/__snapshots__/pidgin.test.js.snap
  src/integration/pages/mediaAssetPage/__snapshots__/pidgin.test.js.snap
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#5976 Upgrade to the latest version of Cypress
  cypress/integration/specialFeatures/cookieBanner/testsForCanonicalOnly.js
  docs/Code-Reviews.md
  package-lock.json
  package.json
Labels: cypress, ws-home, ws-media-stream, ws-stories

#6144 Story integration tests
  src/integration/pages/storyPage/__snapshots__/mundo.test.js.snap
  src/integration/pages/storyPage/mundo.test.js
  src/integration/pages/storyPage/user.amp.js
  src/integration/pages/storyPage/user.canonical.js
Labels: ws-stories

#6187 update react helmet
  package-lock.json
  package.json
  src/app/containers/ChartbeatAnalytics/canonical/index.jsx
  src/app/containers/LinkedData/index.jsx
  src/app/containers/Manifest/index.jsx
  src/app/containers/Manifest/index.test.jsx
  src/app/containers/MediaPlayer/Metadata.jsx
  src/app/containers/Metadata/index.jsx
  src/app/pages/ErrorPage/index.jsx
Labels: bug, ws-home, ws-media-stream, ws-stories

#6218 Ensure integration tests run before pushing to branch
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#6170 Add missing fb:pages metadata tag to all pages
  src/app/containers/ArticleMetadata/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsMetadata/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/RadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/common/SEO.js
  src/integration/pages/articlePage/__snapshots__/mundo.test.js.snap
  src/integration/pages/articlePage/__snapshots__/pidgin.test.js.snap
  src/integration/pages/articlePage/mundo.test.js
  src/integration/pages/articlePage/pidgin.test.js
  src/integration/pages/frontPage/__snapshots__/arabic.test.js.snap
  src/integration/pages/frontPage/__snapshots__/pidgin.test.js.snap
  src/integration/pages/frontPage/arabic.test.js
  src/integration/pages/frontPage/pidgin.test.js
  src/integration/pages/liveRadioPage/__snapshots__/amharic.test.js.snap
  src/integration/pages/liveRadioPage/__snapshots__/korean.test.js.snap
  src/integration/pages/liveRadioPage/amharic.test.js
  src/integration/pages/liveRadioPage/korean.test.js
  src/integration/pages/mediaAssetPage/__snapshots__/persian.tc2.test.js.snap
  src/integration/pages/mediaAssetPage/__snapshots__/persian.test.js.snap
  src/integration/pages/mediaAssetPage/__snapshots__/pidgin.test.js.snap
  src/integration/pages/mediaAssetPage/persian.tc2.test.js
  src/integration/pages/mediaAssetPage/persian.test.js
  src/integration/pages/mediaAssetPage/pidgin.test.js
  src/integration/pages/storyPage/__snapshots__/mundo.test.js.snap
  src/integration/pages/storyPage/mundo.test.js
Labels: ws-home, ws-media-stream, ws-stories

#6221 position footer at bottom of page for OD and live radio
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/pages/RadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/RadioPage/index.jsx
  src/integration/pages/liveRadioPage/__snapshots__/amharic.test.js.snap
  src/integration/pages/liveRadioPage/__snapshots__/korean.test.js.snap
Labels: ws-media-stream

#6223 Changed Tigrinya cookie title within config/services to match cypress' assertion
  src/app/lib/config/services/tigrinya.js
Labels: ws-home, ws-media-stream, ws-stories

#6207 LiveRadio Refactor Regarding Ares Response
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.js
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.test.js
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/containers/RadioPageBlocks/index.test.jsx
  src/app/models/propTypes/data/index.js
  src/app/models/propTypes/liveRadioPage/content/aresBlock/index.js
  src/app/models/propTypes/liveRadioPage/content/index.js
  src/app/models/propTypes/liveRadioPage/content/version/index.js
  src/app/models/propTypes/liveRadioPage/index.js
  src/app/models/propTypes/radioPage/index.js
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/index.jsx
  src/app/pages/LiveRadioPage/index.stories.jsx
  src/app/pages/LiveRadioPage/index.test.jsx
  src/app/pages/index.js
  src/app/routes/index.js
  src/app/routes/liveRadio/getInitialData/addIdsToBlocks.js
  src/app/routes/liveRadio/getInitialData/index.js
  src/app/routes/liveRadio/getInitialData/index.test.js
  src/app/routes/liveRadio/index.js
  src/app/routes/radio/getInitialData/index.js
  src/integration/pages/liveRadioPage/__snapshots__/amharic.test.js.snap
  src/integration/pages/liveRadioPage/__snapshots__/korean.test.js.snap
Labels: ws-media-stream

#6213 Overtyped headlines for Index Alsos
  src/app/containers/StoryPromo/IndexAlsos/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/IndexAlsos/index.jsx
  src/app/containers/StoryPromo/IndexAlsos/index.test.jsx
  src/app/containers/StoryPromo/IndexAlsos/relatedItems.js
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
Labels: ws-home

#6188 Overtyped summaries in promos
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/helpers/fixtureData.js
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
Labels: ws-home

#6152 Constrain story page max-width
  .env
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.jsx
  src/integration/pages/storyPage/__snapshots__/mundo.test.js.snap
Labels: ux, ws-home, ws-media-stream, ws-stories

#6208 Update Frontpage Radio Schedule Positions
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/pages/FrontPage/index.jsx
Labels: radio-schedules, ws-home

#6209 Update Content Security Policy for Social Embeds
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: social-embeds, stories-STYs, ws-home, ws-media-stream, ws-stories

#6238 Adding ATI Analytics for onDemand Radio
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.js
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.test.js
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/routes/onDemandRadio/getInitialData/index.js
Labels: ws-media-ondemandRadio, ws-media-stream

#6151 Update Hausa navigation
  src/app/lib/config/services/hausa.js
Labels: ws-home

#6120 Navigation links updates
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/ukrainian.js
  src/integration/pages/mediaAssetPage/__snapshots__/persian.tc2.test.js.snap
  src/integration/pages/mediaAssetPage/__snapshots__/persian.test.js.snap
Labels: ws-home

#6216 Allow multiple text blocks and /'s before the date in legacy asset regex
  data/ukchina/legacyAssets/simp/elt/english_now/2015/09/150903_todays_phrase_as_quick_as_a_flash.json
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
Labels: ws-stories

#6253 Update pageData for radio Storybook
  src/app/pages/LiveRadioPage/fixtureData/afaanoromoo.json
  src/app/pages/LiveRadioPage/fixtureData/amharic.json
  src/app/pages/LiveRadioPage/fixtureData/indonesia.json
  src/app/pages/LiveRadioPage/fixtureData/korean.json
  src/app/pages/LiveRadioPage/fixtureData/tigrinya.json
  src/app/pages/LiveRadioPage/index.stories.jsx
  src/app/pages/OnDemandRadioPage/fixtureData/indonesia.json
  src/app/pages/OnDemandRadioPage/fixtureData/pashto.json
  src/app/pages/OnDemandRadioPage/index.stories.jsx
Labels: ws-media-stream

#6215 Use live data on test for radio pages
  src/app/containers/RadioPageBlocks/Blocks/AudioPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/lib/utilities/getEmbedUrl/index.js
  src/app/lib/utilities/getEmbedUrl/index.test.js
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.test.jsx
  src/app/routes/liveRadio/getInitialData/index.js
  src/app/routes/liveRadio/getInitialData/index.test.js
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/onDemandRadio/getInitialData/index.test.js
  src/app/routes/utils/overrideRendererOnTest/index.js
  src/app/routes/utils/overrideRendererOnTest/index.test.js
  src/integration/pages/liveRadioPage/__snapshots__/amharic.test.js.snap
  src/integration/pages/liveRadioPage/__snapshots__/korean.test.js.snap
  src/integration/pages/liveRadioPage/amharic.test.js
  src/integration/pages/liveRadioPage/korean.test.js
Labels: ws-media-liveRadioV2, ws-media-ondemandRadio, ws-media-stream

#6210 Top Promo image lazy loading
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/frontPage/__snapshots__/pidgin.test.js.snap
Labels: ws-home

#6193 Update Persian (and Japanese) translations
  data/pashto/cpsAssets/23289748.json
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/punjabi.js
  src/app/pages/ErrorPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/mediaAssetPage/__snapshots__/persian.tc2.test.js.snap
  src/integration/pages/mediaAssetPage/__snapshots__/persian.test.js.snap
  src/integration/pages/mediaAssetPage/persian.tc2.test.js
  src/integration/pages/mediaAssetPage/persian.test.js
Labels: high-priority, ws-home

#6192 Add amp-ad JS script to Simorgh
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/arabic.js
  src/integration/pages/frontPage/__snapshots__/arabic.test.js.snap
  src/integration/pages/frontPage/__snapshots__/pidgin.test.js.snap
Labels: ads, ws-home

#6265 Adding Chartbeat to onDemand radio, updating values for liveRadio
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
  src/integration/pages/liveRadioPage/__snapshots__/amharic.test.js.snap
  src/integration/pages/liveRadioPage/__snapshots__/korean.test.js.snap
Labels: ws-media-ondemandRadio, ws-media-stream

#6260 Add flag for rendering OJ recommendations in service config
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: stories-STYs, ws-stories

#6142 Fetch radio schedules data on server
  scripts/bundleSizeConfig.js
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/index.jsx
  src/app/containers/RadioSchedule/Canonical/index.test.jsx
  src/app/containers/RadioSchedule/index.jsx
  src/app/containers/RadioSchedule/index.test.jsx
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.js
  src/app/containers/RadioSchedule/utilities/radioScheduleShape.js
  src/app/containers/RadioSchedule/utilities/testHelpers.jsx
  src/app/lib/logger.const.js
  src/app/lib/utilities/getRadioSchedulesUrls/index.jsx
  src/app/lib/utilities/getRadioSchedulesUrls/index.test.jsx
  src/app/pages/FrontPage/index.jsx
  src/app/pages/FrontPage/index.test.jsx
  src/app/routes/home/getInitialData/index.js
  src/app/routes/home/getInitialData/index.test.js
  src/app/routes/index.test.jsx
  src/app/routes/utils/getConfig/index.js
  src/app/routes/utils/getConfig/index.test.js
  src/app/routes/utils/withRadioSchedule/index.js
  src/app/routes/utils/withRadioSchedule/index.test.js
  src/integration/pages/articlePage/__snapshots__/mundo.test.js.snap
  src/integration/pages/articlePage/__snapshots__/pidgin.test.js.snap
  src/integration/pages/frontPage/__snapshots__/arabic.test.js.snap
  src/integration/pages/frontPage/__snapshots__/pidgin.test.js.snap
  src/integration/pages/frontPage/arabic.test.js
  src/integration/pages/frontPage/pidgin.test.js
  src/integration/pages/frontPage/user.canonical.js
  src/integration/pages/mediaAssetPage/__snapshots__/persian.tc2.test.js.snap
  src/integration/pages/mediaAssetPage/__snapshots__/persian.test.js.snap
  src/integration/pages/mediaAssetPage/__snapshots__/pidgin.test.js.snap
  src/integration/pages/storyPage/__snapshots__/mundo.test.js.snap
  src/server/index.jsx
Labels: high-priority, radio-schedules, ws-home

#6244 Adding local URLs to Cypress settings for on demand radio episode pages
  cypress/support/config/settings.js
Labels: ws-media-ondemandRadio, ws-media-stream

#6197 Keep build dirs and artifacts for 3 days to reduce disk utilisation
  Jenkinsfile
Labels: ws-home, ws-media-stream, ws-stories

#6261 [Do not merge until Thursday AM] - Toggle radio schedules on live
  src/app/lib/config/toggles/index.js
Labels: radio-schedules, ws-home

#6270 Hausa, Pashto, Arabic, Somali Translation Updates
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/somali.js
Labels: high-priority, radio-schedules, ws-home

#6268 Use latest radio schedule
  package-lock.json
  package.json
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
Labels: high-priority, radio-schedules, ws-home

#6248 Fix long headlines overflowing on Opera Mini Extreme Mode
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: ws-home

#6271 Enabled MAP tests for all current services
  cypress/support/config/settings.js
Labels: cypress, ws-media-asset-page-v1, ws-media-map-variants, ws-media-stream

#6281 Pashto translation updates
  src/app/lib/config/services/pashto.js
Labels: ws-home, ws-stories

#6279 Radio schedule error logging
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.js
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.test.js
  src/app/containers/RadioSchedule/utilities/radioScheduleShape.js
  src/app/lib/logger.const.js
Labels: radio-schedules, ws-home

#6274 Kill zombie server after running integration tests
  package.json
Labels: ws-media-stream

#6285 Remove TC2 audio clips on local tests
  cypress/support/config/settings.js
  data/swahili/legacyAssets/michezo/2016/07/160712_tc2_testmap1.json
  scripts/bundleSizeConfig.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#6283 Recommendations preprocessor rule
  src/app/routes/cpsAsset/getInitialData/addBylineBlock/index.js
  src/app/routes/cpsAsset/getInitialData/addRecommendationsBlock/index.js
  src/app/routes/cpsAsset/getInitialData/addRecommendationsBlock/index.test.js
  src/app/routes/cpsAsset/getInitialData/addSummaryBlock/index.js
  src/app/routes/cpsAsset/getInitialData/helpers/index.js
  src/app/routes/cpsAsset/getInitialData/helpers/index.test.js
  src/app/routes/cpsAsset/getInitialData/index.js
Labels: ws-stories

#6254 encode x5 and x6 values for ATI
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/article/buildParams.test.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/ATIAnalytics/params/radioPage/buildParams.test.js
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
Labels: ws-home

#6251 Updating dependencies
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#6294 Better handle the logging of revoked/expired media (external_vpid)
  src/app/lib/logger.const.js
  src/app/pages/MediaAssetPage/MediaMessage/index.test.jsx
  src/app/routes/cpsAsset/getInitialData/processUnavailableMedia/index.js
  src/app/routes/cpsAsset/getInitialData/processUnavailableMedia/index.test.js
Labels: ares-v2, ws-media-stream

#6175 Add most read page and refactor container
  scripts/bundleSizeConfig.js
  src/app/containers/App/App.test.jsx
  src/app/containers/ChartbeatAnalytics/index.jsx
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/Canonical/index.test.jsx
  src/app/containers/MostRead/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/index.jsx
  src/app/containers/MostRead/index.test.jsx
  src/app/containers/MostRead/utilities/mostReadShape.js
  src/app/containers/MostRead/utilities/processMostRead.js
  src/app/containers/MostRead/utilities/processMostRead.test.js
  src/app/containers/MostRead/utilities/testHelpers.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/lib/utilities/getMostReadUrls/index.js
  src/app/lib/utilities/getMostReadUrls/index.test.js
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/ArticlePage/index.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/index.jsx
  src/app/pages/FrontPage/index.stories.jsx
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/index.jsx
  src/app/pages/MostReadPage/index.stories.jsx
  src/app/pages/MostReadPage/index.test.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.jsx
  src/app/pages/index.js
  src/app/routes/index.js
  src/app/routes/mostRead/getInitialData/index.js
  src/app/routes/mostRead/getInitialData/index.test.js
  src/app/routes/mostRead/index.js
  src/app/routes/utils/pageTypes.js
  src/app/routes/utils/regex/index.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
Labels: most-read, ws-home

#6319 Use semanticGroupName to define Radio Schedule position
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/pages/FrontPage/index.jsx
Labels: ws-home

#6108 Updating Simorgh Release Info with launch dates for Front Pages & PGLs
  docs/Simorgh-Release-Info.md
  scripts/simorghLaunchDates.js
  scripts/simorghPages.js
Labels: ws-home, ws-stories

#6315 Updating dependencies
  package-lock.json
  package.json
  src/app/containers/ArticleTimestamp/timeFormatTests/expectedFormats.json
Labels: dependencies, high-priority, ws-home, ws-media-stream, ws-stories

#6293 Update Indonesia metadata
  data/indonesia/frontpage/index.json
Labels: ws-home

#6292 Enable most read for news
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/news.js
Labels: most-read, ws-home

#6320 Replace and unify unreliable Article page AV Player tests
  cypress/integration/pages/articles/helpers.js
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
Labels: bug, ws-stories

#6296 MAP E2Es
  cypress/integration/pages/mediaAssetPage/helpers.js
  cypress/integration/pages/mediaAssetPage/tests.js
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  cypress/support/config/envs.js
Labels: ares-v2, cypress, high-priority, ws-media-stream

#6287 Update Ads toggle to take GeoIP into consideration
  src/app/contexts/ToggleContext/index.jsx
  src/app/contexts/ToggleContext/index.test.jsx
  src/app/contexts/ToggleContext/reducer.jsx
  src/app/hooks/useToggle/index.test.jsx
  src/app/hooks/useToggle/useToggle.test.jsx
Labels: ads, ws-home

#6328 add null check to virtualReferrer
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
Labels: bug, high-priority, ws-home

#6313 Bump Story Promo and remove extended Link styles
  package-lock.json
  package.json
  src/app/containers/Bulletin/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
Labels: ws-home

#6299 Update Arabic nav
  src/app/lib/config/services/arabic.js
Labels: ws-home

#6332 Add assetType when logging unsupported block type in CPS asset
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.test.js
Labels: ws-home, ws-media-stream, ws-stories

#6345 Add Kyrgyz Social Embed focussed test asset
  data/kyrgyz/cpsAssets/23292889.json
Labels: blocking, social-embeds, stories-STYs, ws-stories

#6331 Release Info Update: Test / Live URLs for PGLs & local URLs for STY
  cypress/support/config/settings.js
  docs/Simorgh-Release-Info.md
Labels: ws-media-stream, ws-stories

#6051 E2E script switching user journey
  cypress.json
  cypress/integration/specialFeatures/cookieBanner/testsForCanonicalOnly.js
  cypress/integration/specialFeatures/scriptSwitching/index.js
  cypress/integration/specialFeatures/scriptSwitching/testsForAMPOnly.js
  cypress/integration/specialFeatures/scriptSwitching/testsForCanonicalOnly.js
  cypress/integration/specialFeatures/utilities/cookiePrivacyBanner/index.js
  cypress/integration/specialFeatures/utilities/scriptSwitchingJourneyActions/index.js
  cypress/integration/specialFeatures/utilities/scriptSwitchingJourneyAssertions/index.js
  cypress/support/helpers/runTestsForPage.js
  cypress/support/helpers/visitPage.js
  data/serbian/cpsAssets/cyr/srbija-23278974.json
  data/serbian/cpsAssets/lat/srbija-23278974.json
Labels: cypress, ws-media-asset-page-v1, ws-media-map-variants, ws-media-stream

#6330 Pass lang attribute to bulletin
  package-lock.json
  package.json
  src/app/containers/Bulletin/__snapshots__/index.test.jsx.snap
  src/app/containers/Bulletin/index.jsx
  src/app/containers/Bulletin/index.test.jsx
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
Labels: ws-home

#6280 Added Top Stories and Features Analysis heading translations for all services
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-stories

#6360 Social Embed - bug fixes
  src/app/containers/SocialEmbed/index.jsx
  src/app/models/propTypes/socialEmbed/index.js
Labels: blocking, social-embeds, ws-stories
