Repository bbc/simorgh, pull requests merged in 2020-03, with the labels that each got.

#5691 Reducing bundle size and removing duplicate dependencies
  package-lock.json
  scripts/bundleSizeConfig.js
  webpack.config.client.js
Labels: ws-home

#5639 Update translation variable name for clarity
  src/app/containers/Navigation/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-home

#5728 refactor front page composition
  src/app/pages/FrontPage/index.jsx
  src/app/pages/FrontPage/index.stories.jsx
  src/app/pages/FrontPage/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/index.js
  src/app/routes/cpsAsset/index.js
  src/app/routes/home/index.js
Labels: ws-media-stream

#5713 Thai test URL changed to page without stream
  cypress/support/config/services.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5732 Add data attribute to Most Read
  cypress/integration/pages/frontPage/testsForCanonicalOnly.js
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/__snapshots__/index.test.jsx.snap
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
Labels: ws-home

#5738 Fix most read bugs
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/ArticlePage/index.jsx
Labels: bug, most-read, ws-home

#5740 Remove Most Read e2e test
  cypress/integration/pages/frontPage/testsForCanonicalOnly.js
Labels: ws-home

#5747 Update urdu translations
  src/app/lib/config/services/urdu.js
Labels: high-priority, ws-home

#5742 Chartbeat domains fix for LIVE env (Turkce, Indonesia, Portuguese)
  src/app/containers/ChartbeatAnalytics/index.jsx
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: high-priority, ws-home

#5695 Cypress env paths
  a11y.js
  cypress/integration/application/index.js
  cypress/integration/pages/articles/tests.js
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  cypress/integration/pages/errorPage404/getErrorPath.js
  cypress/integration/pages/errorPage404/tests.js
  cypress/integration/pages/errorPage404/testsForAMPOnly.js
  cypress/integration/pages/errorPage404/testsForCanonicalOnly.js
  cypress/integration/pages/frontPage/tests.js
  cypress/integration/pages/frontPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/tests.js
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  cypress/integration/pages/photoGalleryPage/tests.js
  cypress/integration/pages/storyPage/tests.js
  cypress/integration/pages/testsForAllAMPPages.js
  cypress/integration/pages/testsForAllPages.js
  cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
  cypress/integration/specialFeatures/cookieBanner/testsForCanonicalOnly.js
  cypress/support/config/services.js
  cypress/support/helpers/getAppEnv.js
  cypress/support/helpers/getPaths.js
  cypress/support/helpers/runTestsForPage.js
  cypress/support/helpers/serviceHasPageType.js
  puppeteer/bundleRequests.test.js
  puppeteer/rich-text-transforms.test.js
Labels: ws-media-stream

#5734 [Do not merge] Enable e2e for urdu, vietnamese and turkce
  cypress/support/config/services.js
Labels: ws-home

#5666 Temp disable 404 link tests as they often take upwards of 40s
  cypress/integration/pages/testsForAllPages.js
Labels: ws-stories

#5755 Fixture data for MAPs in local/test environments with playable media
  cypress/support/config/services.js
  data/azeri/cpsAssets/azerbaijan-23257464.json
  data/azeri/cpsAssets/region-49364777.json
  data/gahuza/cpsAssets/amakuru-23257470.json
  data/gahuza/cpsAssets/amakuru-49534170.json
  data/kyrgyz/cpsAssets/media-23257484.json
  data/kyrgyz/cpsAssets/sapar-tv-48695523.json
  data/persian/cpsAssets/iran-23231114.json
  data/persian/cpsAssets/world-49653162.json
  data/vietnamese/cpsAssets/23222411.json
  data/vietnamese/cpsAssets/media-49614583.json
Labels: ws-media-stream

#5757 Logging for flaky Test E2Es
  cypress/integration/pages/testsForAllPages.js
Labels: ws-media-stream

#5759 Bump most read
  package-lock.json
  package.json
  src/app/containers/MostRead/__snapshots__/index.test.jsx.snap
Labels: most-read, ws-home

#5702 Translations for gahuza marathi burmese
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/marathi.js
Labels: ws-home

#5529 Do not show lastPublished timestamp when firstPublished date is the same and not today
  .env
  cypress/integration/pages/articles/tests.js
  cypress/integration/pages/testsForAllPages.js
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/ArticleTimestamp/index.test.jsx
  src/app/containers/ArticleTimestamp/shouldDisplayLastUpdatedTimestamp.js
  src/app/containers/ArticleTimestamp/shouldDisplayLastUpdatedTimestamp.test.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
Labels: ws-media-stream

#5756 Translate live label
  package-lock.json
  package.json
  src/app/containers/Bulletin/__snapshots__/index.test.jsx.snap
  src/app/containers/Bulletin/index.jsx
  src/app/containers/Bulletin/index.test.jsx
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/lib/config/services/afaanoromoo.js
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
Labels: high-priority, ws-home

#5771 Update Gahuza translations
  src/app/lib/config/services/gahuza.js
Labels: ws-home

#5752 Legacy Media playing for MAPS
  package-lock.json
  package.json
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/index.jsx
  src/app/containers/CpsAssetMediaPlayer/index.test.jsx
  src/app/containers/MediaPlayer/helpers/metadata/index.js
  src/app/containers/MediaPlayer/index.jsx
  src/app/lib/utilities/getEmbedUrl/index.test.js
  src/app/lib/utilities/srcSet/index.js
  src/app/pages/MediaAssetPage/index.jsx
  src/app/pages/MediaAssetPage/index.test.jsx
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/legacyMedia/fixtures.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/legacyMedia/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/legacyMedia/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.test.js
Labels: ws-media-stream

#5768 Add Test URLs for burmese somali bengali urdu indonesia nepali pashto turkce tamil swahili hausa, skip related content test for legacy maps
  cypress/integration/pages/mediaAssetPage/tests.js
  cypress/support/config/services.js
  src/app/lib/config/services/gahuza.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5778 Add CPS and TC2 Live URLs burmese somali bengali urdu indonesia nepali pashto turkce tamil swahili hausa
  cypress/support/config/services.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5781 Add logging to diagnose E2E failures
  cypress/integration/pages/testsForAllPages.js
  src/app/contexts/RequestContext/getOriginContext/index.js
Labels: ws-media-stream

#5770 Remove footer copyright e2es
  cypress/integration/pages/testsForAllPages.js
  src/app/containers/Footer/index.test.jsx
Labels: high-priority, ws-home, ws-media-stream, ws-stories

#5780 Add radio frequencies
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/RadioSchedule/index.jsx
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: radio-schedules, ws-home

#5676 Include Script link and set cookie to remember preference
  package-lock.json
  package.json
  src/app/containers/Brand/index.jsx
  src/app/containers/Brand/index.test.jsx
  src/app/containers/Header/ScriptLink/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/ScriptLink/index.jsx
  src/app/containers/Header/ScriptLink/index.test.jsx
  src/app/containers/Header/index.jsx
  src/app/containers/Header/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/PageHandlers/withVariant/getVariantRedirectUrl/index.test.js
  src/app/contexts/UserContext/cookies/index.js
  src/app/contexts/UserContext/cookies/index.test.js
  src/app/contexts/UserContext/index.jsx
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/zhongwen.js
  src/app/lib/utilities/variantHandler/index.js
Labels: high-priority, ux, ws-home

#5785 Temporarily disable E2Es for TC2 MAP pages
  cypress/support/config/services.js
Labels: ws-media-stream

#5658 Remove global time override in storybook config
  .storybook/config.js
  .storybook/time-machine.js
  src/testHelpers/withTimeMachine.jsx
Labels: bug, radio-schedules, ws-home

#5727 Make frontpage sections full width with GHOST background-color
  package-lock.json
  package.json
  src/app/components/Grid/index.jsx
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.jsx
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/index.jsx
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/index.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: radio-schedules, ws-home

#5775 Fixed isLegacyAsset within mediaAssetPage e2e
  cypress/integration/pages/mediaAssetPage/tests.js
Labels: ws-media-asset-page-v2, ws-media-stream

#5772 Update mega AV STY asset
  data/mundo/cpsAssets/23268432.json
Labels: ws-stories

#5783 Local maps cypress
  cypress/support/config/services.js
  data/bengali/cpsAssets/media-23269006.json
  data/bengali/cpsAssets/news-49579870.json
  data/bengali/legacyAssets/multimedia/2016/08/160801_baghdad_rashid_street_100yrs_video.json
  data/bengali/legacyAssets/multimedia/2016/08/160803_tc2_testmap1.json
  data/burmese/cpsAssets/media-23269011.json
  data/burmese/cpsAssets/media-49571787.json
  data/burmese/legacyAssets/multimedia/2016/01/160108_korean_cook.json
  data/burmese/legacyAssets/sport/2016/08/160811_tc2_testmap1.json
  data/gahuza/legacyAssets/amakuru/2016/02/160215_map_amakuru_test1.json
  data/hausa/cpsAssets/23269030.json
  data/hausa/cpsAssets/labarai-49513456.json
  data/hausa/legacyAssets/multimedia/2012/07/120712_click.json
  data/hausa/legacyAssets/multimedia/2016/07/160714_tc2_audiomap.json
  data/hausa/legacyAssets/video/2015/12/151217_test_long.json
  data/indonesia/cpsAssets/media-23269037.json
  data/indonesia/cpsAssets/media-49591990.json
  data/indonesia/legacyAssets/bahasa_inggris/2016/08/160817_video_inggris.json
  data/indonesia/legacyAssets/olahraga/2016/10/161003_tc2_videomap1.json
  data/nepali/cpsAssets/media-23269034.json
  data/nepali/cpsAssets/news-49613544.json
  data/nepali/legacyAssets/multimedia/2013/08/130806_boudhavideo.json
  data/nepali/legacyAssets/multimedia/2016/07/160725_tc2_testmap1.json
  data/pashto/cpsAssets/afghanistan-49628873.json
  data/pashto/cpsAssets/media-23257523.json
  data/pashto/legacyAssets/multimedia/2012/09/120928_naghma_video.json
  data/sinhala/legacyAssets/multimedia/2016/03/160323_si_test_audio_map.json
  data/somali/cpsAssets/hayadeed-23269042.json
  data/somali/cpsAssets/media-48870869.json
  data/somali/legacyAssets/maqal_iyo_muuqaal/2016/06/160628_tc2_testmap1.json
  data/swahili/cpsAssets/dira-tv-49602132.json
  data/swahili/cpsAssets/media-23268999.json
  data/swahili/legacyAssets/michezo/2016/07/160713_tc2_testmap2.json
  data/tamil/cpsAssets/india-23268994.json
  data/tamil/cpsAssets/science-49626264.json
  data/tamil/legacyAssets/global/2016/08/160822_tc2_testmap1.json
  data/turkce/cpsAssets/haberler-dunya-49655644.json
  data/turkce/cpsAssets/media-23268997.json
  data/turkce/legacyAssets/multimedya/2016/05/160524_tc2_testmap1.json
  data/urdu/cpsAssets/pakistan-49644768.json
  data/urdu/cpsAssets/world-23268929.json
  data/urdu/legacyAssets/sport/2016/09/160902_tc2_testmap2.json
Labels: ws-media-stream

#5801 Update Ukrainian translations
  src/app/lib/config/services/ukrainian.js
Labels: ws-home

#5811 Update acorn version to 7.1.1 to address security vulnerability
  package-lock.json
  package.json
Labels: high-priority, ws-home, ws-media-stream, ws-stories, ws-team

#5812 update radioSchedule config with placeholders for header and frequencies link text
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
Labels: radio-schedules, ws-home

#5786 Update image srcset for Promos
  src/app/containers/Bulletin/index.jsx
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
Labels: bug, ws-home

#5821 Fix security vulnerability
  package-lock.json
Labels: high-priority, security, ws-home, ws-media-stream, ws-stories

#5817 Gahuza, Urdu, Swahili, Tamil - MAPs failing on Test E2Es
  cypress/support/config/services.js
Labels: ws-media-stream

#5813 Update Ukrainian nav
  src/app/lib/config/services/ukrainian.js
Labels: ws-home

#5779 Enable most read for: Russian, Ukrainian, Zhongwen, Serbian, UkChina
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/zhongwen.js
Labels: most-read, ws-home

#5655 Display Program Cards in correct order for Radio Schedules
  .storybook/static/data/arabic/bbc_arabic_radio/radioschedule.json
  .storybook/static/data/gahuza/bbc_gahuza_radio/radioschedule.json
  .storybook/static/data/hausa/bbc_hausa_radio/radioschedule.json
  .storybook/static/data/korean/bbc_korean_radio/radioschedule.json
  .storybook/static/data/pashto/bbc_pashto_radio/radioschedule.json
  .storybook/static/data/persian/bbc_persian_radio/radioschedule.json
  .storybook/static/data/somali/bbc_somali_radio/radioschedule.json
  .storybook/static/data/urdu/bbc_urdu_radio/radioschedule.json
  data/arabic/bbc_arabic_radio/radioschedule.json
  package-lock.json
  package.json
  src/app/containers/ArticleTimestamp/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/Canonical/__snapshots__/LastUpdated.test.jsx.snap
  src/app/containers/RadioSchedule/index.jsx
  src/app/containers/RadioSchedule/index.stories.jsx
  src/app/containers/RadioSchedule/index.test.jsx
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
Labels: radio-schedules, ws-home

#5818 Update Serbian and UK China configs
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/ukchina.js
Labels: ws-home

#5798 Fix error in live stream schema
  scripts/bundleSizeConfig.js
  src/app/containers/CpsAssetMediaPlayer/index.jsx
  src/app/containers/MediaPlayer/fixtureData.jsx
  src/app/containers/MediaPlayer/helpers/metadata/index.js
  src/app/containers/MediaPlayer/helpers/metadata/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/version/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.js
Labels: ws-media-asset-page-v2

#5807 Handle incorrect path when generating script link href
  src/app/containers/Header/ScriptLink/index.jsx
  src/app/containers/Header/ScriptLink/index.test.jsx
Labels: ws-home

#5805 Error logging improvement
  src/app/routes/utils/fetchPageData/index.js
  src/app/routes/utils/fetchPageData/index.test.js
  src/index.js
  src/server/index.jsx
Labels: ws-home, ws-media-stream, ws-stories, ws-team

#5828 Increase media play timeout to 20 seconds
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
Labels: ws-media-stream

#5792 Add toggles for script link and variant cookie
  scripts/bundleSizeConfig.js
  src/app/containers/Header/ScriptLink/index.jsx
  src/app/containers/Header/ScriptLink/index.test.jsx
  src/app/containers/Header/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
Labels: high-priority, ws-home

#5829 Update trust links for Serbian, UK China and Ukrainian
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
Labels: ws-home

#5806 Adding fixture data for OnDemand Radio
  data/afaanoromoo/bbc_afaanoromoo_radio/w3cszx1y.json
  data/afrique/bbc_afrique_radio/w172x601yx5z2n1.json
  data/amharic/bbc_amharic_radio/w3csz5r9.json
  data/arabic/bbc_arabic_radio/w3ct01yb.json
  data/bengali/bbc_bangla_radio/w172x0562jxntqx.json
  data/burmese/bbc_burmese_radio/w3csz62h.json
  data/gahuza/bbc_gahuza_radio/w172x7rkcj6v0vz.json
  data/hausa/bbc_hausa_radio/w3cszrwm.json
  data/korean/bbc_korean_radio/w3cszwcg.json
  data/kyrgyz/bbc_kyrgyz_radio/w3cszwmc.json
  data/nepali/bbc_nepali_radio/w172x83pnptp1s8.json
  data/persian/bbc_dari_radio/w3csz7mf.json
  data/persian/bbc_persian_radio/w172x32355t5635.json
  data/sinhala/bbc_sinhala_radio/w172x8zn8th1lwb.json
  data/somali/bbc_somali_radio/w172x90wfxd2qh4.json
  data/swahili/bbc_swahili_radio/w172x94ky63591m.json
  data/tamil/bbc_tamil_radio/w172x966tn9jwmh.json
  data/tigrinya/bbc_tigrinya_radio/w3cszzz1.json
  data/urdu/bbc_urdu_radio/w172x9dx052c8sr.json
  data/uzbek/bbc_uzbek_radio/w172x9f9qjcq3lm.json
Labels: ws-media-stream

#5748 Add background color to document
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorPage/index.jsx
  src/app/components/Grid/index.jsx
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/index.stories.jsx
  src/app/containers/PageHandlers/withLoading/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withLoading/index.jsx
  src/app/lib/styledGrid/__snapshots__/index.test.jsx.snap
  src/app/lib/styledGrid/index.jsx
  src/app/lib/styledGrid/index.stories.jsx
  src/app/lib/styledGrid/index.test.jsx
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/ArticlePage/index.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/index.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/index.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/index.jsx
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.jsx
Labels: ux, ws-home, ws-media-stream, ws-stories

#5836 remove /news links and updated burmese translation
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/nepali.js
Labels: high-priority, ws-home

#5845 Fix most read bug on IE
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
Labels: most-read, ws-home

#5689 Add CCPA links to configs
  package-lock.json
  package.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-stories

#5841 Social embeds fixture
  data/mundo/cpsAssets/embeds-23263889.json
Labels: ws-stories

#5850 Fix most read on article ie
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
Labels: high-priority, most-read, ws-home

#5847 Reduce number of MAP E2E tests
  a11y.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  cypress/support/config/services.js
  cypress/support/helpers/getPaths.js
  cypress/support/helpers/runTestsForPage.js
Labels: ws-media-stream

#5839 Fix images on non-retina
  src/app/containers/Bulletin/index.jsx
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
Labels: ws-home

#5872 Smoke Test Failure: Make AMP ATI test more robust
  cypress/support/commands/analytics.js
Labels: ws-media-stream

#5874 Update script link - padding changes
  package-lock.json
  package.json
  src/app/containers/Header/ScriptLink/__snapshots__/index.test.jsx.snap
Labels: ws-home

#5873 Add preprocessor rules for VJ/IDT2 content
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.js
Labels: ws-stories

#5876 Local and Test E2Es now run on a live stream page (Swahili)
  cypress/support/config/services.js
  data/swahili/cpsAssets/media-23268999.json
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5760 Display RadioSchedules on Simorgh Frontpage
  .storybook/static/data/arabic/bbc_arabic_radio/schedule.json
  .storybook/static/data/gahuza/bbc_gahuza_radio/schedule.json
  .storybook/static/data/hausa/bbc_hausa_radio/schedule.json
  .storybook/static/data/korean/bbc_korean_radio/schedule.json
  .storybook/static/data/pashto/bbc_pashto_radio/schedule.json
  .storybook/static/data/persian/bbc_dari_radio/schedule.json
  .storybook/static/data/persian/bbc_persian_radio/schedule.json
  .storybook/static/data/somali/bbc_somali_radio/schedule.json
  .storybook/static/data/urdu/bbc_urdu_radio/schedule.json
  data/arabic/bbc_arabic_radio/schedule.json
  data/gahuza/bbc_gahuza_radio/schedule.json
  data/hausa/bbc_hausa_radio/schedule.json
  data/korean/bbc_korean_radio/schedule.json
  data/pashto/bbc_pashto_radio/schedule.json
  data/persian/bbc_dari_radio/schedule.json
  data/persian/bbc_persian_radio/schedule.json
  data/somali/bbc_somali_radio/schedule.json
  data/urdu/bbc_urdu_radio/schedule.json
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/index.jsx
  src/app/containers/RadioSchedule/Canonical/index.test.jsx
  src/app/containers/RadioSchedule/index.jsx
  src/app/containers/RadioSchedule/index.stories.jsx
  src/app/containers/RadioSchedule/index.test.jsx
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.js
  src/app/containers/RadioSchedule/utilities/testHelpers.jsx
  src/app/pages/FrontPage/index.jsx
  src/server/index.test.jsx
Labels: radio-schedules, ws-home

#5848 Ensure most recent logs always in app.log
  src/app/lib/logger.node.js
  src/app/lib/logger.node.test.js
Labels: ws-home, ws-media-stream, ws-stories

#5879 Live URLs added for live stream MAP and audio clip for Persian
  cypress/support/config/services.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5870 Update domain for script cookie to match PAL domain
  src/app/containers/ConsentBanner/CanonicalLogic/index.js
  src/app/contexts/UserContext/cookies/index.js
  src/app/contexts/UserContext/cookies/index.test.js
  src/app/lib/utilities/setCookie/index.jsx
  src/app/lib/utilities/setCookie/index.test.jsx
Labels: ws-home

#5887 Updated Amharic live label translation
  src/app/lib/config/services/amharic.js
Labels: ws-home

#5885 Update serbian homepage translation in cyrillic
  src/app/lib/config/services/serbian.js
Labels: ws-home

#5429 Test refactoring
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.test.jsx
Labels: ws-media-stream

#5865 Toggle radio-schedules ON in test
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
Labels: radio-schedules, ws-home

#5804 Skeleton OnDemand Radio Episode page
  data/indonesia/bbc_indonesian_radio/w172x6r5000f38s.json
  data/pashto/bbc_pashto_radio/w172x8nvf4bchz5.json
  scripts/bundleSizeConfig.js
  src/app/containers/RadioPageBlocks/Blocks/OnDemandRadio/index.jsx
  src/app/containers/RadioPageBlocks/index.jsx
  src/app/models/propTypes/data/index.js
  src/app/models/propTypes/onDemandRadioPage/content/index.js
  src/app/models/propTypes/onDemandRadioPage/content/version/index.js
  src/app/models/propTypes/onDemandRadioPage/index.js
  src/app/models/propTypes/promo/index.js
  src/app/models/propTypes/radioPage/content/version/index.js
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/pages/OnDemandRadioPage/index.stories.jsx
  src/app/pages/OnDemandRadioPage/index.test.jsx
  src/app/pages/index.js
  src/app/routes/index.js
  src/app/routes/index.test.jsx
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/onDemandRadio/getInitialData/index.test.js
  src/app/routes/onDemandRadio/index.js
  src/app/routes/radio/index.js
  src/app/routes/utils/regex/index.js
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
Labels: ws-media-stream

#5892 Removed Swahili test MAP URL
  cypress/support/config/services.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5835 Add leaderboard ad on Front Page (AMP)
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Amp/index.test.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.jsx
  src/app/containers/Ad/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
  src/app/lib/config/toggles/index.js
  src/app/pages/FrontPage/index.jsx
Labels: ads, ws-home

#5896 add missing Simp link for ‘Ad Choices/ Do not sell my info’ in Footer
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-home

#5889 Manually update dependencies + fix vulnerability
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
Labels: high-priority, ws-home, ws-media-stream, ws-stories

#5898 Fix serbian topic link
  src/app/lib/config/services/serbian.js
Labels: high-priority, ws-home

#5908 Chartbeat for liveRadio
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/testsForCanonicalOnly.js
Labels: ws-media-stream

#5891 IDT1 Preprocessor Rules
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
Labels: stories-STYs, ws-stories

#5910 Adding Chartbeat tests for Canonical and AMP MAPs
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  cypress/support/commands/analytics.js
Labels: ws-media-stream

#5909 Bump psammead-navigation to 6.0.6
  package-lock.json
  package.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
Labels: ws-home

#5901 Update Trust Project metadata URLs for services with localised versions
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/RadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: ws-home

#5911 Fix failing AMP Validation for TC2 MAPs
  cypress/support/config/services.js
  package.json
  public/images/media_placeholder.png
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/legacyMedia/fixtures.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/legacyMedia/index.js
Labels: ws-media-stream

#5914 Added fixture data for variant services
  data/serbian/cpsAssets/cyr/srbija-51667308.json
  data/serbian/cpsAssets/lat/srbija-51667308.json
  data/ukchina/cpsAssets/simp/51726400.json
  data/ukchina/cpsAssets/trad/51726400.json
  data/ukrainian/cpsAssets/media-40962249.json
  data/ukrainian/cpsAssets/media-51746432.json
  data/ukrainian/legacyAssets/multimedia_russian/2014/03/140301_ru_n_crimea_parliament_seizure.json
  data/uzbek/cpsAssets/lotin-44512908.json
  data/uzbek/cpsAssets/media-49799366.json
  data/uzbek/legacyAssets/lotin/2016/04/160427_latin_video_girl_8.json
Labels: ws-media-map-variants, ws-media-stream

#5929 Use 'timeOnServer' instead of client time for Radio Schedules
  src/app/containers/RadioSchedule/Canonical/index.jsx
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.js
  src/app/containers/RadioSchedule/utilities/testHelpers.jsx
Labels: radio-schedules, ws-home

#5931 Disabled swahili map urls on test
  cypress/support/config/services.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5714 refactor error page composition
  src/app/components/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorMain/index.jsx
  src/app/components/ErrorMain/index.test.jsx
  src/app/containers/App/App.jsx
  src/app/containers/PageHandlers/withData/index.jsx
  src/app/containers/PageHandlers/withData/index.test.jsx
  src/app/containers/PageHandlers/withError/index.jsx
  src/app/containers/PageHandlers/withError/index.test.jsx
  src/app/pages/Error/__snapshots__/index.test.jsx.snap
  src/app/pages/Error/index.jsx
  src/app/pages/Error/index.test.jsx
  src/app/pages/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/pages/ErrorPage/index.jsx
  src/app/pages/ErrorPage/index.stories.jsx
  src/app/pages/ErrorPage/index.test.jsx
  src/app/pages/index.js
  src/app/routes/cpsAsset/index.js
  src/app/routes/error/getInitialData/index.js
  src/app/routes/error/getInitialData/index.test.js
  src/app/routes/error/index.js
  src/app/routes/error404/index.js
  src/app/routes/errorNoRouteMatch/index.js
  src/app/routes/index.js
  src/app/routes/index.test.jsx
Labels: ws-media-stream

#5852 Display Error when media is absent on MAPs
  scripts/bundleSizeConfig.js
  src/app/lib/logger.const.js
  src/app/pages/MediaAssetPage/MediaMessage/index.jsx
  src/app/pages/MediaAssetPage/index.jsx
  src/app/pages/MediaAssetPage/index.test.jsx
  src/app/routes/cpsAsset/getInitialData/addHeadlineBlock/index.js
  src/app/routes/cpsAsset/getInitialData/index.js
  src/app/routes/cpsAsset/getInitialData/index.test.js
  src/app/routes/cpsAsset/getInitialData/processUnavailableMedia/index.js
  src/app/routes/cpsAsset/getInitialData/processUnavailableMedia/index.test.js
Labels: ws-media-stream

#5920 Ability to play media on canonical for CPS and legacy MAPs
  cypress/integration/pages/mediaAssetPage/helpers.js
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
Labels: cypress, ws-media-stream

#5904 Remove mozart fallback checks from E2Es
  3rdPartyCypress/cypress/support/commands.js
  cypress/support/commands/application.js
Labels: cypress, ws-home, ws-media-stream, ws-stories

#5934 On demand radio titles and summary
  src/app/containers/RadioPageBlocks/Blocks/OnDemandRadio/index.jsx
  src/app/models/propTypes/onDemandRadioPage/content/index.js
  src/app/models/propTypes/onDemandRadioPage/content/version/index.js
  src/app/models/propTypes/onDemandRadioPage/index.js
  src/app/models/propTypes/promo/index.js
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/pages/OnDemandRadioPage/index.test.jsx
  src/app/routes/index.test.jsx
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/onDemandRadio/getInitialData/index.test.js
Labels: ws-media-stream

#5907 Radio Schedules - Always show in Storybook
  .storybook/static/data/afrique/bbc_afrique_radio/schedule.json
  .storybook/static/data/arabic/bbc_arabic_radio/schedule.json
  .storybook/static/data/gahuza/bbc_gahuza_radio/schedule.json
  .storybook/static/data/hausa/bbc_hausa_radio/schedule.json
  .storybook/static/data/korean/bbc_korean_radio/schedule.json
  .storybook/static/data/pashto/bbc_pashto_radio/schedule.json
  .storybook/static/data/persian/bbc_dari_radio/schedule.json
  .storybook/static/data/persian/bbc_persian_radio/schedule.json
  .storybook/static/data/somali/bbc_somali_radio/schedule.json
  .storybook/static/data/swahili/bbc_swahili_radio/schedule.json
  .storybook/static/data/urdu/bbc_urdu_radio/schedule.json
  .storybook/time-machine.js
  data/afrique/bbc_afrique_radio/schedule.json
  data/arabic/bbc_arabic_radio/schedule.json
  data/gahuza/bbc_gahuza_radio/schedule.json
  data/hausa/bbc_hausa_radio/schedule.json
  data/korean/bbc_korean_radio/schedule.json
  data/pashto/bbc_pashto_radio/schedule.json
  data/persian/bbc_dari_radio/schedule.json
  data/persian/bbc_persian_radio/schedule.json
  data/somali/bbc_somali_radio/schedule.json
  data/swahili/bbc_swahili_radio/schedule.json
  data/urdu/bbc_urdu_radio/schedule.json
  package.json
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/index.jsx
  src/app/containers/RadioSchedule/index.stories.jsx
  src/testHelpers/withTimeMachine.jsx
Labels: radio-schedules, ws-home, ws-media-stream, ws-stories

#5855 Enable Live RadioSchedule data on Test env
  src/app/containers/RadioSchedule/index.jsx
  src/app/containers/RadioSchedule/index.stories.jsx
  src/app/containers/RadioSchedule/utilities/testHelpers.jsx
  src/app/lib/utilities/getRadioSchedulesUrls/index.jsx
  src/app/lib/utilities/getRadioSchedulesUrls/index.test.jsx
  src/app/pages/FrontPage/index.test.jsx
Labels: high-priority, radio-schedules, ws-home

#5954 Radio Schedules Header and Link translations
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
Labels: ws-home

#5893 Change radio schedule background color to Lunar
  package-lock.json
  package.json
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/index.jsx
Labels: radio-schedules, ws-home

#5963 Update Somali caption translations
  src/app/lib/config/services/somali.js
Labels: ws-stories

#5967 Update Gujarati translations
  src/app/lib/config/services/gujarati.js
Labels: ws-home

#5930 Update psammead packages and timestamp tests
  package-lock.json
  package.json
  src/app/containers/ArticleTimestamp/timeFormatTests/expectedFormats.json
Labels: ws-home

#5957 Radio Schedules: Fix Programme Link
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.js
Labels: high-priority, radio-schedules, ws-home

#5965 Fix font style for Radio Frequency Link
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/index.jsx
Labels: high-priority, radio-schedules, ws-home

#5970 Update Mundo and Hindi translations
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/mundo.js
Labels: ws-home

#5973 Add commas to Serbian translations
  src/app/lib/config/services/serbian.js
Labels: ws-stories

#5949 Fixing Chapter and Page for MAPs ATI
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.js
  src/app/routes/cpsAsset/getInitialData/addAnalyticsCounterName/index.js
Labels: ws-media-stream

#5982 Disable Pidgin MAP smoke tests in Test / Live environments
  cypress/support/config/services.js
Labels: ws-media-stream

#5986 Added Uzbek and Ukrainian test and local MAP URLs
  cypress/support/config/services.js
  data/ukrainian/cpsAssets/other-news-23279018.json
  data/ukrainian/cpsAssets/world-23087423.json
  data/ukrainian/legacyAssets/entertainment/2016/10/161025_tc2_testmap1.json
  data/uzbek/cpsAssets/23279019.json
  data/uzbek/cpsAssets/world-23053613.json
  data/uzbek/legacyAssets/multimedia/2016/06/160610_tc2_testmap1.json
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5751 Add Features & Analysis to Secondary Columns
  scripts/bundleSizeConfig.js
  src/app/containers/FeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/FeaturesAnalysis/index.jsx
  src/app/containers/FeaturesAnalysis/index.stories.jsx
  src/app/containers/FeaturesAnalysis/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/featuresAnalysis.json
  src/app/pages/StoryPage/featuresAnalysisRtl.json
  src/app/pages/StoryPage/index.jsx
Labels: a11y-swarm, ws-stories

#5995 Update Russian translations
  src/app/lib/config/services/russian.js
Labels: ws-home

#5992 Live E2E URLs Uzbek and Ukrainian
  cypress/support/config/services.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5978 Update radio schedules
  package-lock.json
  package.json
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/index.jsx
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.js
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: radio-schedules, ws-home

#5962 Script link - Remove visually hidden text
  package-lock.json
  package.json
  src/app/containers/Header/ScriptLink/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/ScriptLink/index.jsx
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-home

#5974 Additional tests for processRadioSchedules
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.js
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.test.js
Labels: radio-schedules, ws-home

#5979 Add missing useEffect dependencies - Radio Schedules
  src/app/containers/RadioSchedule/Canonical/index.jsx
Labels: bug, radio-schedules, ws-home

#6001 Remove the 'should play media' MAP / Live Radio tests as they are unstable and causing test failures
  cypress/integration/pages/liveRadio/helper.js
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/testsForCanonicalOnly.js
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
Labels: cypress, ws-media-stream

#6004 Update Portuguese translations
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/zhongwen.js
Labels: high-priority, ws-home

#5877 Remove all audio and photogalleries from the navigations
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-home

#5993 Zhongwen config updates
  src/app/lib/config/services/zhongwen.js
Labels: high-priority, ws-home

#5968 add radio schedules fixture data to storybook
  .storybook/static/data/afaanoromoo/bbc_oromo_radio/schedule.json
  .storybook/static/data/afrique/bbc_afrique_radio/schedule.json
  .storybook/static/data/amharic/bbc_amharic_radio/schedule.json
  .storybook/static/data/arabic/bbc_arabic_radio/schedule.json
  .storybook/static/data/bengali/bbc_bangla_radio/schedule.json
  .storybook/static/data/burmese/bbc_burmese_radio/schedule.json
  .storybook/static/data/gahuza/bbc_gahuza_radio/schedule.json
  .storybook/static/data/hausa/bbc_hausa_radio/schedule.json
  .storybook/static/data/indonesia/bbc_indonesian_radio/schedule.json
  .storybook/static/data/korean/bbc_korean_radio/schedule.json
  .storybook/static/data/pashto/bbc_pashto_radio/schedule.json
  .storybook/static/data/persian/bbc_dari_radio/schedule.json
  .storybook/static/data/persian/bbc_persian_radio/schedule.json
  .storybook/static/data/somali/bbc_somali_radio/schedule.json
  .storybook/static/data/swahili/bbc_swahili_radio/schedule.json
  .storybook/static/data/tigrinya/bbc_tigrinya_radio/schedule.json
  .storybook/static/data/urdu/bbc_urdu_radio/schedule.json
  data/afaanoromoo/bbc_oromo_radio/schedule.json
  data/afrique/bbc_afrique_radio/schedule.json
  data/amharic/bbc_amharic_radio/schedule.json
  data/arabic/bbc_arabic_radio/schedule.json
  data/bengali/bbc_bangla_radio/schedule.json
  data/burmese/bbc_burmese_radio/schedule.json
  data/gahuza/bbc_gahuza_radio/schedule.json
  data/hausa/bbc_hausa_radio/schedule.json
  data/indonesia/bbc_indonesian_radio/schedule.json
  data/korean/bbc_korean_radio/schedule.json
  data/pashto/bbc_pashto_radio/schedule.json
  data/persian/bbc_dari_radio/schedule.json
  data/persian/bbc_persian_radio/schedule.json
  data/somali/bbc_somali_radio/schedule.json
  data/swahili/bbc_swahili_radio/schedule.json
  data/tigrinya/bbc_tigrinya_radio/schedule.json
  data/urdu/bbc_urdu_radio/schedule.json
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/index.stories.jsx
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/urdu.js
Labels: radio-schedules, ws-home

#6020 Now showing multimedia as chapter type for ATI legacy MAPS
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.js
Labels: ws-media-stream

#6028 Navigation link updates for Sinhala & Russian
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/sinhala.js
Labels: ws-home

#5764 faster integration tests
  data/pidgin/cpsAssets/tori-51745682.json
  jest.config.js
  package-lock.json
  package.json
  scripts/dependencyCheck.js
  src/integration/.eslintrc
  src/integration/README.md
  src/integration/common/SEO.js
  src/integration/common/a11y.js
  src/integration/common/analytics.amp.js
  src/integration/common/analytics.canonical.js
  src/integration/common/core.amp.js
  src/integration/common/core.canonical.js
  src/integration/common/footer.js
  src/integration/common/header.js
  src/integration/common/index.js
  src/integration/common/performance.js
  src/integration/common/snapshot.js
  src/integration/integrationTestEnvironment.js
  src/integration/pages/articlePage/__snapshots__/mundo.test.js.snap
  src/integration/pages/articlePage/__snapshots__/pidgin.test.js.snap
  src/integration/pages/articlePage/mundo.test.js
  src/integration/pages/articlePage/pidgin.test.js
  src/integration/pages/articlePage/user.amp.js
  src/integration/pages/articlePage/user.canonical.js
  src/integration/pages/liveRadioPage/__snapshots__/amharic.test.js.snap
  src/integration/pages/liveRadioPage/__snapshots__/korean.test.js.snap
  src/integration/pages/liveRadioPage/amharic.test.js
  src/integration/pages/liveRadioPage/korean.test.js
  src/integration/pages/liveRadioPage/user.amp.js
  src/integration/pages/liveRadioPage/user.canonical.js
  src/integration/pages/liveRadioPage/user.js
  src/integration/render.js
  src/testHelpers/setupTests.js
Labels: ws-media-stream

#5894 Includes container with fetch on SSR
  src/app/containers/Include/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/index.jsx
  src/app/containers/Include/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
  src/app/pages/StoryPage/index.jsx
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
Labels: stories-STYs, ws-stories

#5994 Opera mini extreme saving mode - skip to content link showing
  src/app/containers/Header/index.jsx
Labels: ws-home

#6003 Stop radio frequencies link covering entire page
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/index.jsx
Labels: radio-schedules, ws-home

#6033 Ensure site on stage domain has 'env' value of 'test'
  src/app/contexts/RequestContext/getEnv/index.js
  src/app/contexts/RequestContext/getEnv/index.test.js
Labels: bug, ws-home

#6044 Mundo config updates
  src/app/lib/config/services/mundo.js
  src/integration/pages/articlePage/__snapshots__/mundo.test.js.snap
  src/integration/pages/articlePage/mundo.test.js
Labels: ws-home

#5999 Use new Live Label component
  package.json
  src/app/containers/Bulletin/index.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
Labels: ws-home
