Repository bbc/simorgh, pull requests merged in 2020-02, with the labels that each got.

#5332 Navigation change for Indian Sportswoman of the Year
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
Labels: ws-home

#5336 Fix flakey unit tests
  data/pidgin/frontpage/index-light.json
  package.json
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.test.jsx
  webpack.config.client.js
  webpack.config.js
Labels: performance, ws-home, ws-media-stream, ws-stories

#5323 Also output JUnit reports for Cypress tests
  .gitignore
  cypress/reporter-config.json
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#5373 Increase e2e timeout to 6 hours and reduce the run frequency to every…
  Jenkinsfile-e2e
  Jenkinsfile-e2e-local
  Jenkinsfile-e2e-test
Labels: ws-stories

#5331 Correcting SectionLabel margins below 1008px to match designs
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/pages/CpsMap/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsMap/index.jsx
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsPgl/index.jsx
  src/app/pages/CpsSty/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsSty/index.jsx
Labels: ux, ws-media-asset-page-v2, ws-media-stream

#5376 Added test E2Es for Arabic, Hindi, Persian (not dari) and Urdu live radio
  cypress/support/config/services.js
Labels: cypress, ws-media- LiveRadioV1, ws-media-stream

#5379 update cypress helper getBrandedImage
  cypress/support/helpers/getBrandedImage.js
Labels: ws-media-stream

#5380 Fix propType errors in ArticleMetadata
  src/app/containers/ArticleMetadata/index.jsx
Labels: ws-stories

#5226 Adds e2e's for PGL pages
  cypress/integration/pages/mediaAssetPage/tests.js
  cypress/integration/pages/photoGalleryPage/index.js
  cypress/integration/pages/photoGalleryPage/tests.js
  cypress/integration/pages/photoGalleryPage/testsForAMPOnly.js
  cypress/integration/pages/photoGalleryPage/testsForCanonicalOnly.js
  cypress/integration/pages/testsForAllPages.js
  cypress/support/config/services.js
Labels: stories-pgl, ws-media-stream, ws-stories

#5375 Allow cypress to run against multiple paths per page type
  cypress/integration/pages/liveRadio/tests.js
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/testsForCanonicalOnly.js
  cypress/integration/pages/testsForAllPages.js
  cypress/support/config/services.js
  cypress/support/helpers/runTestsForPage.js
Labels: ws-media-stream

#5334 Update Indonesia navigation
  src/app/lib/config/services/indonesia.js
Labels: ws-home

#5333 Fix padding above AV player on MAPs on screens less than 400 px wide
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/index.jsx
  src/app/pages/CpsMap/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsSty/__snapshots__/index.test.jsx.snap
Labels: ws-media-stream

#5382 forEach page paths in cookie banner
  cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
  cypress/integration/specialFeatures/cookieBanner/testsForCanonicalOnly.js
Labels: ws-media-stream

#5378 Add STY local assets
  data/mundo/cpsAssets/23263889.json
  data/mundo/cpsAssets/noticias-internacional-51266689.json
  src/app/pages/CpsSty/fixtureData.json
  src/app/pages/CpsSty/index.stories.jsx
Labels: ws-stories, ws-sty-page-v1

#5372 Bumping dependencies
  package-lock.json
  package.json
  src/server/Document/__snapshots__/component.test.jsx.snap
Labels: ws-home, ws-media-stream, ws-stories

#5383 [DO NOT MERGE] Live E2Es for Arabic, Hindi, Persian, Persian Dari and Urdu added
  cypress/support/config/services.js
Labels: cypress, ws-media- LiveRadioV1, ws-media-stream

#5371 Bumping BBC Dependencies
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#5387 Add Watch/Listen translations
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/sinhala.js
Labels: ws-home

#5381 Output JUnit reports for Jest tests
  jest.config.js
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#5389 Added data for Uzbek liveradio and configured the URL to run on all E2Es
  cypress/support/config/services.js
  data/uzbek/bbc_uzbek_radio/liveradio.json
Labels: cypress, ws-media- LiveRadioV1, ws-media-stream

#5346 Adding No-JS fallback for Media pages
  package-lock.json
  package.json
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsMap/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsSty/__snapshots__/index.test.jsx.snap
Labels: ws-media-stream

#5398 Fix oops in Archive manifest
  public/archive/manifest.json
Labels: articles-rollout, ws-stories

#5286 [DO NOT MERGE] Live e2e tests for Nepali, Afaanoromoo, Amharic, Bengali, Sinhala, and Tigrinya
  cypress/support/config/services.js
Labels: ws-home

#5335 Simplify BBC Tamil site navigation.
  src/app/lib/config/services/tamil.js
Labels: ws-home

#5403 Fixing E2Es for PGLs & MAPs - services with variants
  cypress/integration/pages/testsForAllPages.js
  cypress/support/config/services.js
  cypress/support/helpers/getBrandedImage.js
Labels: ws-home, ws-media-stream, ws-stories

#5397 Display error when AV stream has expired
  data/pidgin/cpsAssets/media-23256549.json
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/CpsAssetMediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/media/fixtures.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/media/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/version/fixtures.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/version/index.js
  src/app/pages/CpsMap/index.test.jsx
Labels: ws-media-stream

#5404 E2Es for MAPs Thai, Punjabi, Afaan Oromo, Amharic, Tigrinya, Marathi, Gujarati, Korean on test and local
  cypress/support/config/services.js
  data/afaanoromoo/cpsAssets/23149891.json
  data/amharic/cpsAssets/news-23263266.json
  data/gujarati/cpsAssets/other-news-23130286.json
  data/marathi/cpsAssets/media-23127353.json
  data/telugu/cpsAssets/international-23263261.json
  data/tigrinya/cpsAssets/news-23263262.json
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5406 Downgrading cypress to 3.8.1
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#5396 Fix crash when bullet point has no content
  src/app/containers/Fragment/index.jsx
  src/app/containers/Fragment/index.test.jsx
Labels: ws-media-stream

#5414 Fix nav link in Tamil
  src/app/lib/config/services/tamil.js
Labels: ws-home

#5413 Update Tigrinya translations
  src/app/lib/config/services/tigrinya.js
Labels: ws-home, ws-media-stream, ws-stories

#5420 Adding translation for No-JS Message
  src/app/containers/MediaPlayer/index.jsx
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/ukchina.js
Labels: ws-media-stream

#5425 Fixes E2Es for PGLs
  cypress/integration/pages/testsForAllPages.js
  cypress/support/config/services.js
Labels: high-priority, ws-home, ws-media-stream, ws-stories

#5394 Update Scotland ATI destination
  src/app/contexts/RequestContext/getStatsDestination/index.js
  src/app/contexts/RequestContext/getStatsDestination/index.test.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
Labels: articles-rollout, ws-stories

#5415 Update STY fixture
  data/mundo/cpsAssets/23263889.json
Labels: ws-stories

#5400 Improve test coverage related to CPS subheadings
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/subheadline/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/subheadline/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.test.js
Labels: ws-stories

#5419 [DO NOT MERGE] Enables E2Es on live for MAPS Thai, Punjabi, Afaan Oromoo, Amharic, Tigrinya, Marathi, Telugu, Gujarati, Korean
  cypress/support/config/services.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5426 Update last updated prefix translation
  src/app/containers/MostRead/Canonical/LastUpdated.test.jsx
  src/app/containers/MostRead/Canonical/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
Labels: most-read, ws-home

#5428 update most read static url for storybook
  src/app/containers/MostRead/index.stories.jsx
Labels: most-read, ws-home

#5431 Legacy map fixtures
  data/afrique/cpsAssets/nos_emissions/2014/11/141111_porno_vengeur_ouganda.json
  data/arabic/cpsAssets/multimedia/2014/05/140515_kenia_children_sex_trade.json
  data/azeri/cpsAssets/multimedia/2012/09/120919_georgia_prison_video.json
  data/bengali/cpsAssets/multimedia/2016/08/160801_baghdad_rashid_street_100yrs_video.json
  data/burmese/cpsAssets/multimedia/2016/01/160108_korean_cook.json
  data/gahuza/cpsAssets/video/2015/12/151201_100womenburundi.json
  data/hausa/cpsAssets/multimedia/2012/07/120712_click.json
  data/hindi/cpsAssets/multimedia/2015/07/150703_jharkhand_maoist_fake_surrender_sr.json
  data/indonesia/cpsAssets/bahasa_inggris/2016/08/160817_video_inggris.json
  data/kyrgyz/cpsAssets/entertainment/2014/07/140725_egypt_tentmaking.json
  data/mundo/cpsAssets/video_fotos/2016/05/160502_video_apnea_record_rubridge_nezolandes_amv.json
  data/nepali/cpsAssets/multimedia/2013/08/130806_boudhavideo.json
  data/pashto/cpsAssets/multimedia/2012/09/120928_naghma_video.json
  data/persian/cpsAssets/arts/2011/08/110802_doublage_sherlock_promo.json
  data/portuguese/cpsAssets/noticias/2016/03/160307_andes_vivos_tg.json
  data/russian/cpsAssets/multimedia/2016/05/160505_v_diving_record.json
  data/sinhala/cpsAssets/sri_lanka/2014/01/140120_disabled_soldiers_pay_292.json
  data/somali/cpsAssets/maqal_iyo_muuqaal/2012/07/120731_olympicvideo.json
  data/swahili/cpsAssets/medianuai/2013/04/130419_lead_posoning.json
  data/tamil/cpsAssets/global/2014/07/140713_animalsvideo.json
  data/turkce/cpsAssets/multimedya/2016/02/160216_vid_genclerde_depresyon.json
  data/ukchina/cpsAssets/trad/multimedia/2015/11/151120_video_100w_london_chinese_entrepreneurs.json
  data/ukrainian/cpsAssets/multimedia/2014/05/140508_biggest_dinosaur_found_ag.json
  data/urdu/cpsAssets/multimedia/2014/11/141104_hindu_riaz_kq.json
  data/uzbek/cpsAssets/multimedia/2013/12/131221_sectarian_war_bowen.json
  data/vietnamese/cpsAssets/multimedia/2015/04/150428_david_wheat_interview.json
  data/zhongwen/cpsAssets/simp/multimedia/2016/05/160511_vid_cultural_revolution_explainer.json
Labels: ws-media-stream

#5434 update last updated in most read
  src/app/containers/MostRead/Canonical/LastUpdated.jsx
  src/app/containers/MostRead/Canonical/LastUpdated.test.jsx
  src/app/containers/MostRead/Canonical/__snapshots__/LastUpdated.test.jsx.snap
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/__snapshots__/index.test.jsx.snap
Labels: most-read, ws-home

#5422 Content expired translations
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
  src/app/pages/CpsMap/index.test.jsx
Labels: ws-media-stream

#5441 Add indexImage to STY test data
  data/igbo/cpsAssets/afirika-23252735.json
  data/mundo/cpsAssets/23263889.json
  data/pidgin/cpsAssets/world-23252817.json
  src/app/pages/CpsSty/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsSty/fixtureData.json
Labels: stories-STYs, ws-stories

#5438 Update link to radioschedule.json to fix online storybook
  src/app/containers/RadioSchedule/index.stories.jsx
Labels: ws-home

#5446 Added space between word and link text for Uzbek live radio
  src/app/lib/config/services/uzbek.js
Labels: ws-media-stream

#5440 Improve error logging in getInitialData
  src/app/routes/getInitialData/index.js
  src/app/routes/getInitialData/index.test.js
Labels: ws-media-stream

#5408 Adds Byline block
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addBylineBlock/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addBylineBlock/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addSummaryBlock/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/helpers/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/helpers/index.test.js
  src/app/routes/getInitialData/utils/preprocessorRulesConfig/index.js
Labels: ws-media-asset-page-v2, ws-stories

#5451 Fixes map left alignment bug
  src/app/pages/CpsMap/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsMap/index.jsx
Labels: ws-media-stream

#5485 replace compose with pipe
  src/app/lib/utilities/preprocessor/rules/addIdsToBlocks.js
  src/app/lib/utilities/preprocessor/rules/addIdsToItems.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/timestampToMilliseconds/index.js
  src/app/pages/Article/index.jsx
  src/app/pages/CpsMap/index.jsx
  src/app/pages/CpsPgl/index.jsx
  src/app/pages/CpsSty/index.jsx
  src/app/pages/Error/index.jsx
  src/app/pages/FrontPage/index.jsx
  src/app/pages/RadioPage/index.jsx
Labels: ws-media-stream

#5487 Use node v12.15.0 & npm 6.13.7
  .npmrc
  .nvmrc
Labels: ws-home, ws-media-stream, ws-stories

#5479 Add missing metadata for schema.org
  src/app/pages/CpsSty/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsSty/categoryMap/index.js
  src/app/pages/CpsSty/categoryMap/index.test.js
  src/app/pages/CpsSty/index.jsx
Labels: stories-STYs, ws-stories

#5495 fix vulnerability
  package-lock.json
Labels: high-priority, ws-home

#5488 split routes index into smaller modules
  src/app/routes/article/index.js
  src/app/routes/cpsAsset/index.js
  src/app/routes/error200/index.js
  src/app/routes/error404/index.js
  src/app/routes/home/index.js
  src/app/routes/index.js
  src/app/routes/radio/index.js
Labels: ws-media-stream

#5501 Add new/updated Indonesian translations
  src/app/lib/config/services/indonesia.js
Labels: ws-home, ws-media-stream, ws-stories

#5504 Updated STY fixture for bold italic and media content
  src/app/pages/CpsSty/fixtureData.json
Labels: stories-STYs, ws-stories

#5505 Updated fixture data for PGL story
  src/app/pages/CpsPgl/fixtureData.json
Labels: stories-pgl, ws-stories

#5478 Add Podcast Promo Link
  data/pidgin/frontpage/index.json
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/lib/utilities/preprocessor/rules/filterContentType.js
  src/app/lib/utilities/preprocessor/rules/filterContentType.test.js
Labels: ux, ws-home

#5502 Bumping dependencies
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#5437 Add most read on front pages
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/FrontPageMain/index.test.jsx
  src/app/containers/MostRead/Canonical/LastUpdated.jsx
  src/app/containers/MostRead/Canonical/LastUpdated.test.jsx
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/index.jsx
  src/app/containers/MostRead/index.stories.jsx
  src/app/containers/MostRead/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
  src/app/lib/config/toggles/index.js
  src/app/routes/regex/index.js
  src/app/routes/regex/index.test.js
  src/server/index.test.jsx
Labels: most-read, ws-home

#5494 ATI for STY pages
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsPgl/index.test.jsx
  src/app/pages/CpsSty/__snapshots__/index.test.jsx.snap
Labels: stories-STYs, stories-pgl, ws-stories

#5291 Legacy TC2 asset support in local dev & test environments
  data/hausa/legacyAssets/multimedia/2012/07/120712_click.json
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/fixtureData.json
  src/app/pages/MediaAssetPage/index.jsx
  src/app/pages/MediaAssetPage/index.stories.jsx
  src/app/pages/MediaAssetPage/index.test.jsx
  src/app/routes/README.md
  src/app/routes/cpsAsset/index.js
  src/app/routes/index.js
  src/app/routes/index.test.js
  src/app/routes/legacyCpsAsset/index.js
  src/app/routes/regex/index.js
  src/app/routes/regex/index.test.js
  src/app/routes/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/regex/utils/index.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: ws-home, ws-media-stream, ws-stories

#5530 Updating psammead-media-player version and snapshots
  package-lock.json
  package.json
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
Labels: ws-media-stream

#5532 Change CPSRelatedContent html to section with role of region
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsSty/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/index.test.jsx
Labels: stories-pgl, ws-media-stream, ws-stories

#5503 rename getInitialData to fetchPageData
  README.md
  src/app/containers/App/App.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/containers/FrontPageMain/index.test.jsx
  src/app/containers/RadioPageBlocks/index.test.jsx
  src/app/containers/RadioPageMain/index.test.jsx
  src/app/pages/CpsPgl/index.test.jsx
  src/app/pages/CpsSty/index.test.jsx
  src/app/pages/MediaAssetPage/index.test.jsx
  src/app/routes/article/index.js
  src/app/routes/cpsAsset/index.js
  src/app/routes/fetchPageData/index.js
  src/app/routes/fetchPageData/index.test.js
  src/app/routes/fetchPageData/utils/getBaseUrl/index.js
  src/app/routes/fetchPageData/utils/getBaseUrl/index.test.js
  src/app/routes/fetchPageData/utils/getPreprocessorRules/index.js
  src/app/routes/fetchPageData/utils/getRouteProps/index.js
  src/app/routes/fetchPageData/utils/getRouteProps/index.test.js
  src/app/routes/fetchPageData/utils/getRouteProps/routeFallbackParams/index.js
  src/app/routes/fetchPageData/utils/getRouteProps/routeFallbackParams/index.test.js
  src/app/routes/fetchPageData/utils/preprocessorRulesConfig/index.js
  src/app/routes/home/index.js
  src/app/routes/radio/index.js
  src/client.test.jsx
  src/server/index.jsx
  src/server/index.test.jsx
  src/server/utilities/constructCspHeader/index.js
Labels: ws-media-stream

#5527 Fix broken story for useful links
  src/app/containers/FrontPageSection/index.stories.jsx
Labels: ws-home

#5499 Update Trust Project Links for Burmese, Hindi, and Tamil
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/tamil.js
Labels: ws-home

#5510 Fixture data for Legacy MAPs in local dev environment
  data/afrique/legacyAssets/nos_emissions/2014/11/141111_porno_vengeur_ouganda.json
  data/arabic/legacyAssets/multimedia/2014/05/140515_kenia_children_sex_trade.json
  data/azeri/legacyAssets/multimedia/2012/09/120919_georgia_prison_video.json
  data/bengali/legacyAssets/multimedia/2016/08/160801_baghdad_rashid_street_100yrs_video.json
  data/burmese/legacyAssets/multimedia/2016/01/160108_korean_cook.json
  data/gahuza/legacyAssets/video/2015/12/151201_100womenburundi.json
  data/hindi/legacyAssets/multimedia/2015/07/150703_jharkhand_maoist_fake_surrender_sr.json
  data/indonesia/legacyAssets/bahasa_inggris/2016/08/160817_video_inggris.json
  data/kyrgyz/legacyAssets/entertainment/2014/07/140725_egypt_tentmaking.json
  data/mundo/legacyAssets/video_fotos/2016/05/160502_video_apnea_record_rubridge_nezolandes_amv.json
  data/nepali/legacyAssets/multimedia/2013/08/130806_boudhavideo.json
  data/pashto/legacyAssets/multimedia/2012/09/120928_naghma_video.json
  data/persian/legacyAssets/arts/2011/08/110802_doublage_sherlock_promo.json
  data/portuguese/legacyAssets/noticias/2016/03/160307_andes_vivos_tg.json
  data/russian/legacyAssets/multimedia/2016/05/160505_v_diving_record.json
  data/sinhala/legacyAssets/sri_lanka/2014/01/140120_disabled_soldiers_pay_292.json
  data/somali/legacyAssets/maqal_iyo_muuqaal/2012/07/120731_olympicvideo.json
  data/swahili/legacyAssets/medianuai/2013/04/130419_lead_posoning.json
  data/tamil/legacyAssets/global/2014/07/140713_animalsvideo.json
  data/turkce/legacyAssets/multimedya/2016/02/160216_vid_genclerde_depresyon.json
  data/ukchina/legacyAssets/trad/multimedia/2015/11/151120_video_100w_london_chinese_entrepreneurs.json
  data/ukrainian/legacyAssets/multimedia/2014/05/140508_biggest_dinosaur_found_ag.json
  data/urdu/legacyAssets/multimedia/2014/11/141104_hindu_riaz_kq.json
  data/uzbek/legacyAssets/multimedia/2013/12/131221_sectarian_war_bowen.json
  data/vietnamese/legacyAssets/multimedia/2015/04/150428_david_wheat_interview.json
  data/zhongwen/legacyAssets/simp/multimedia/2016/05/160511_vid_cultural_revolution_explainer.json
Labels: ws-media-stream

#5513 make bbc-a11y run PGL pages
  a11y.js
Labels: stories-pgl, ws-stories

#5486 Most Read: Add service toggle
  src/app/containers/MostRead/Canonical/index.test.jsx
  src/app/containers/MostRead/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/index.jsx
  src/app/containers/MostRead/index.test.jsx
  src/app/containers/MostRead/utilities/testHelpers.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: most-read, ws-home

#5551 Front Page Main&Page Storybook - add serbian cyrillic and latin variants
  src/app/containers/FrontPageMain/index.stories.jsx
  src/app/pages/FrontPage/index.stories.jsx
Labels: ws-home

#5550 Add new codebuild buildspec.yml files for the e2es and moves the exis…
  Jenkinsfile-e2e
  Jenkinsfile-e2e-local
  Jenkinsfile-e2e-test
  codebuild/e2e_buildspec.yml
Labels: infra-tooling-stream, ws-stories

#5524 Bump path-to-regexp
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/InlineLink/index.jsx
  src/app/containers/PageHandlers/withVariant/getVariantRedirectUrl/index.js
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#5565 Renamed CPS page containers
  cypress/integration/pages/testsForAllPages.js
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/LinkedData/__snapshots__/index.test.jsx.snap
  src/app/containers/LinkedData/index.test.jsx
  src/app/pages/PhotoGallery/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGallery/fixtureData.json
  src/app/pages/PhotoGallery/index.jsx
  src/app/pages/PhotoGallery/index.stories.jsx
  src/app/pages/PhotoGallery/index.test.jsx
  src/app/pages/Story/__snapshots__/index.test.jsx.snap
  src/app/pages/Story/categoryMap/index.js
  src/app/pages/Story/categoryMap/index.test.js
  src/app/pages/Story/fixtureData.json
  src/app/pages/Story/index.jsx
  src/app/pages/Story/index.stories.jsx
  src/app/pages/Story/index.test.jsx
  src/app/routes/README.md
  src/app/routes/cpsAsset/index.js
  src/app/routes/index.test.js
Labels: stories-STYs, stories-pgl, tech-debt, ws-stories

#5512 Add Byline to STY pages
  package-lock.json
  package.json
  src/app/containers/Byline/__snapshots__/index.test.jsx.snap
  src/app/containers/Byline/index.jsx
  src/app/containers/Byline/index.stories.jsx
  src/app/containers/Byline/index.test.jsx
  src/app/models/propTypes/byline/index.js
  src/app/pages/Story/__snapshots__/index.test.jsx.snap
  src/app/pages/Story/index.jsx
Labels: ws-stories, ws-sty-page-v1

#5554 No CSS timestamp fix
  src/app/containers/ArticleTimestamp/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/ArticleTimestamp/index.test.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGallery/__snapshots__/index.test.jsx.snap
Labels: a11y, stories-STYs, stories-pgl, ws-home, ws-media-stream, ws-stories

#5602 Updated STY asset to include related content
  data/mundo/cpsAssets/23263889.json
  src/app/pages/Story/fixtureData.json
Labels: stories-STYs, ws-stories

#5596 Legacy MAP cypress tests
  cypress/integration/pages/mediaAssetPage/tests.js
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  cypress/integration/pages/testsForAllPages.js
  cypress/support/config/services.js
Labels: cypress, ws-media-stream

#5545 Legacy Media Placeholder Block
  data/gahuza/legacyAssets/video/2016/01/160108_australia_fire_video.json
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addAnalyticsCounterName/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addAnalyticsCounterName/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addHeadlineBlock/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/index.js
  src/app/pages/MediaAssetPage/MediaMessage/index.jsx
  src/app/pages/MediaAssetPage/MediaMessage/index.test.jsx
  src/app/pages/MediaAssetPage/index.jsx
  src/app/pages/MediaAssetPage/index.test.jsx
  src/app/routes/fetchPageData/utils/preprocessorRulesConfig/index.js
Labels: ws-media-stream

#5604 Update most read timestamps and remove FrontPageMain snapshot
  .storybook/static/data/pidgin/mostRead/index.json
  .storybook/static/data/somali/mostRead/index.json
  data/pidgin/mostRead/index.json
  data/somali/mostRead/index.json
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.test.jsx
Labels: most-read, ws-home

#5574 Live e2e tests - Burmese and Gahuza
  cypress/support/config/services.js
Labels: ws-home

#5614 Changed URLs to be the same for test and local for TC2 MAPs
  cypress/support/config/services.js
  data/azeri/legacyAssets/multimedia/2015/08/150804_azeri_test.json
  data/gahuza/legacyAssets/video/2015/12/151217_test_long.json
  data/kyrgyz/legacyAssets/multimedia/2015/03/150330_map_test.json
  data/pashto/legacyAssets/world/2016/09/160921_tc2_testmap1.json
  data/persian/legacyAssets/iran/2016/09/160907_tc2_testmap1.json
  data/vietnamese/legacyAssets/sport/2016/09/160922_tc2_testmap2.json
Labels: cypress, ws-media-stream

#5612 FrontPageMain snapshot restore
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.test.jsx
Labels: most-read, ws-home

#5544 Replace preprocessor with pipe for page data
  scripts/bundleSizeConfig.js
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/containers/FrontPageMain/index.test.jsx
  src/app/containers/RadioPageBlocks/index.test.jsx
  src/app/containers/RadioPageMain/index.test.jsx
  src/app/lib/utilities/preprocessor/index.js
  src/app/lib/utilities/preprocessor/index.test.js
  src/app/pages/FrontPage/index.stories.jsx
  src/app/pages/MediaAssetPage/index.test.jsx
  src/app/pages/PhotoGallery/index.test.jsx
  src/app/pages/Story/index.test.jsx
  src/app/routes/article/getInitialData.js
  src/app/routes/article/getInitialData.test.js
  src/app/routes/article/index.js
  src/app/routes/cpsAsset/getInitialData.js
  src/app/routes/cpsAsset/getInitialData.test.js
  src/app/routes/cpsAsset/index.js
  src/app/routes/fetchPageData/index.js
  src/app/routes/fetchPageData/index.test.js
  src/app/routes/fetchPageData/utils/getPreprocessorRules/index.js
  src/app/routes/home/getInitialData.js
  src/app/routes/home/getInitialData.test.js
  src/app/routes/home/index.js
  src/app/routes/radio/getInitialData.js
  src/app/routes/radio/getInitialData.test.js
  src/app/routes/radio/index.js
Labels: ws-media-stream

#5569 Refactor Most Read unit tests to use testing-library/react
  src/app/containers/MostRead/Canonical/index.test.jsx
  src/app/containers/MostRead/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/index.test.jsx
  src/app/containers/MostRead/utilities/testHelpers.jsx
Labels: most-read, ws-home

#5613 Initial work for ATI Analytics
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/lib/analyticsUtils/index.js
  src/app/pages/MediaAssetPage/index.jsx
Labels: ws-media-stream

#5589 Group dependabot updates - non-BBC
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#5632 Toggle on Nav for Optimo Articles
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
Labels: ws-home, ws-stories

#5610 Fix for full viewport of 375px for potrait images
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleFigure/index.jsx
  src/app/pages/PhotoGallery/__snapshots__/index.test.jsx.snap
Labels: bug, stories-pgl, ws-stories

#5633 added fixture data for pgl pagetype
  data/gujarati/cpsAssets/india-47512764.json
Labels: stories-pgl, ws-stories

#5492 Legacy MAP paragraph text containing the <link> tag is not rendered correctly
  cypress/integration/pages/mediaAssetPage/tests.js
  scripts/bundleSizeConfig.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/paragraph/helpers.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/paragraph/helpers.test.js
Labels: ws-media-stream

#5586 Turn chartbeat back on in test
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
Labels: ws-home

#5584 Added enableGridWrapper prop to give an option to enable GhostGrid in CpsRelatedContent
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/pages/MediaAssetPage/index.jsx
  src/app/pages/PhotoGallery/index.jsx
  src/app/pages/Story/__snapshots__/index.test.jsx.snap
Labels: stories-STYs, ws-media-stream, ws-stories

#5184 Cypress test for playing media on MAP and live radio pages
  cypress/integration/pages/liveRadio/testsForCanonicalOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
Labels: ws-media-stream

#5641 Update mundo navigation for Hay festival location
  src/app/lib/config/services/mundo.js
Labels: ws-home

#5592 Bump packages (including most read)
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/components/Grid/__snapshots__/index.test.jsx.snap
  src/app/components/Grid/index.jsx
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleTimestamp/__snapshots__/index.test.jsx.snap
  src/app/containers/BulletedList/__snapshots__/index.test.jsx.snap
  src/app/containers/Byline/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsText/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FauxHeadline/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/FrontPageSection/UsefulLinks/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/UsefulLinks/index.jsx
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/PageHandlers/withLoading/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Text/__snapshots__/index.test.jsx.snap
  src/app/lib/config/toggles/index.js
  src/app/lib/styledGrid/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGallery/__snapshots__/index.test.jsx.snap
  src/app/pages/Story/__snapshots__/index.test.jsx.snap
  webpack.config.client.js
Labels: high-priority, most-read, ws-home

#5653 update CSP header
  src/server/utilities/constructCspHeader/index.js
  src/server/utilities/constructCspHeader/index.test.js
Labels: ws-home

#5629 Add Simorgh server time to initial data
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/App/__snapshots__/App.test.jsx.snap
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/PageHandlers/withContexts.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
  src/server/index.jsx
Labels: radio-schedules, ws-home

#5139 New Desktop Layout
  data/igbo/frontpage/index.json
  data/persian/frontpage/index.json
  data/urdu/frontpage/index.json
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/components/Grid/__snapshots__/index.test.jsx.snap
  src/app/components/Grid/index.jsx
  src/app/components/Grid/index.stories.jsx
  src/app/components/Grid/index.test.jsx
  src/app/containers/Bulletin/__snapshots__/index.test.jsx.snap
  src/app/containers/Bulletin/index.jsx
  src/app/containers/Bulletin/index.stories.jsx
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.jsx
  src/app/containers/FrontPageSection/index.test.jsx
  src/app/containers/FrontPageSection/utilities/filterAllowedItems.jsx
  src/app/containers/FrontPageSection/utilities/filterAllowedItems.test.jsx
  src/app/containers/FrontPageSection/utilities/rowDetails.jsx
  src/app/containers/FrontPageSection/utilities/rowDetails.test.jsx
  src/app/containers/FrontPageSection/utilities/storyRowsSplitter.jsx
  src/app/containers/FrontPageSection/utilities/storyRowsSplitter.test.jsx
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/index.jsx
  src/app/containers/FrontPageStoryRows/index.stories.jsx
  src/app/containers/FrontPageStoryRows/index.test.jsx
  src/app/containers/FrontPageStoryRows/storyColumns.jsx
  src/app/containers/FrontPageStoryRows/testHelpers.js
  src/app/containers/MostRead/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/StoryPromo/IndexAlsos/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/IndexAlsos/index.jsx
  src/app/containers/StoryPromo/LinkContents/index.jsx
  src/app/containers/StoryPromo/MediaIndicator/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/MediaIndicator/index.jsx
  src/app/containers/StoryPromo/MediaIndicator/index.test.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/lib/utilities/getStoryPromoInfo/index.jsx
  src/app/lib/utilities/getStoryPromoInfo/index.test.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGallery/__snapshots__/index.test.jsx.snap
  src/app/pages/Story/__snapshots__/index.test.jsx.snap
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/media/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/version/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.js
  src/app/routes/home/getInitialData/filterUnknownContentTypes/__snapshots__/index.test.js.snap
  src/app/routes/home/getInitialData/squashTopStories/__snapshots__/index.test.js.snap
  src/app/routes/utils/fetchPageData/utils/getBaseUrl/index.js
Labels: ws-front-page-layout, ws-home

#5673 E2E fix for TV bulletin on front pages
  cypress/integration/pages/frontPage/tests.js
Labels: high-priority, ws-home

#5672 Related content layout update - Groups 4 & 5
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsRelatedContent/index.stories.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGallery/__snapshots__/index.test.jsx.snap
  src/app/pages/Story/__snapshots__/index.test.jsx.snap
Labels: high-priority, ws-home, ws-media-stream, ws-stories

#5664 [Do Not Merge] Enabling frontpage e2e for Indonesia
  cypress/support/config/services.js
Labels: ws-home

#5540 Implement Chartbeat for MAPs and Live Radio Pages
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/index.jsx
  src/app/containers/RadioPageMain/index.stories.jsx
  src/app/containers/RadioPageMain/index.test.jsx
  src/app/pages/MediaAssetPage/index.jsx
Labels: ws-media-stream

#5678 fix feature index pages. if transformers fail then fallback to json
  src/app/routes/cpsAsset/getInitialData/index.js
Labels: ws-home, ws-media-stream

#5671 Mega AV fixtures for STY
  data/mundo/cpsAssets/23268432.json
Labels: stories-STYs, ws-stories

#5682 improve tests for routes
  src/app/routes/cpsAsset/index.js
  src/app/routes/index.js
  src/app/routes/index.test.js
  src/app/routes/index.test.jsx
  src/app/routes/legacyCpsAsset/index.js
Labels: ws-media-stream

#5693 Remove bulletin e2e tests
  cypress/integration/pages/frontPage/tests.js
Labels: high-priority, ws-home

#5623 Add MostRead to articles
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/ArticleMain/index.stories.jsx
  src/app/containers/ArticleMain/index.test.jsx
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/index.jsx
  src/app/containers/MostRead/index.stories.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
Labels: most-read, ws-home

#5697 updated mundo fixtures with includes
  data/mundo/cpsAssets/23263889.json
Labels: stories-STYs, ws-stories

#5662 Remove FrontPageMain and move logic to /pages
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/FrontPageMain/index.stories.jsx
  src/app/containers/FrontPageMain/index.test.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/index.jsx
  src/app/pages/FrontPage/index.stories.jsx
  src/app/pages/FrontPage/index.test.jsx
Labels: container-cleanup, ws-home

#5685 refactor radio page composition
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/index.jsx
  src/app/containers/RadioPageMain/index.stories.jsx
  src/app/containers/RadioPageMain/index.test.jsx
  src/app/pages/RadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/RadioPage/index.jsx
  src/app/pages/RadioPage/index.stories.jsx
  src/app/pages/RadioPage/index.test.jsx
  src/app/pages/index.js
  src/app/routes/radio/index.js
Labels: ws-media-stream

#5680 Toggle most read on TEST and STAGE and LIVE
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
Labels: most-read, ws-home

#5675 Enables live E2Es for TC2 MAPs Azeri Persian Kyrgyz Gahuza Sinhala Vietnamese
  cypress/support/config/services.js
Labels: cypress, ws-media-stream

#5417 [DNM] STY Second Column
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/index.jsx
  src/app/pages/PhotoGallery/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGallery/index.jsx
  src/app/pages/Story/__snapshots__/index.test.jsx.snap
  src/app/pages/Story/index.jsx
Labels: stories-STYs, ux, ws-stories, ws-sty-page-v1

#5705 Remove stage env from cypress config
  cypress/support/config/envs.js
Labels: integration-testing, ws-home, ws-media-stream, ws-stories

#5538 e2e tests for most read
  cypress/integration/pages/frontPage/testsForCanonicalOnly.js
Labels: most-read, ws-home

#5716 Update turkish trust link
  src/app/lib/config/services/turkce.js
Labels: ws-home

#5634 Use correct current page state
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/index.jsx
  src/app/containers/Navigation/index.test.jsx
  src/app/pages/FrontPage/index.stories.jsx
Labels: stories-pgl, ux, ws-home

#5710 refactor article page composition
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ArticleMetadata/index.test.jsx
  src/app/containers/CpsMetadata/index.test.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/PageHandlers/withData/index.test.jsx
  src/app/lib/utilities/parseAssetData/index.test.js
  src/app/pages/Article/__snapshots__/index.test.jsx.snap
  src/app/pages/Article/index.jsx
  src/app/pages/Article/index.test.jsx
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/ArticlePage/fixtureData.js
  src/app/pages/ArticlePage/index.jsx
  src/app/pages/ArticlePage/index.stories.jsx
  src/app/pages/ArticlePage/index.test.jsx
  src/app/pages/index.js
  src/app/routes/article/index.js
Labels: ws-media-stream

#5711 refactor CPS page composition
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/pages/MediaAssetPage/index.jsx
  src/app/pages/MediaAssetPage/index.stories.jsx
  src/app/pages/MediaAssetPage/index.test.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/fixtureData.json
  src/app/pages/PhotoGalleryPage/index.jsx
  src/app/pages/PhotoGalleryPage/index.stories.jsx
  src/app/pages/PhotoGalleryPage/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/categoryMap/index.js
  src/app/pages/StoryPage/categoryMap/index.test.js
  src/app/pages/StoryPage/fixtureData.json
  src/app/pages/StoryPage/index.jsx
  src/app/pages/StoryPage/index.stories.jsx
  src/app/pages/StoryPage/index.test.jsx
  src/app/pages/index.js
  src/app/routes/cpsAsset/index.js
Labels: ws-media-stream
