Repository bbc/simorgh, pull requests merged in 2020-11, with the labels that each got.

#8277 GitHub action to create a tag and release when pushing to latest
  .github/workflows/simorgh-create-github-release.yml
Labels: cross-team

#8301 Remove unused buildspec and add cc test reporting from GH actions
  .github/workflows/simorgh-unit-tests.yml
  buildspecs/buildspec-ci-branch.yml
Labels: cross-team

#8298 Use merge commit as release notes for release created by GitHub actions
  .github/workflows/simorgh-create-github-release.yml
Labels: cross-team

#8299 gh action to deploy storybook to gh pages
  .github/workflows/simorgh-deploy-storybook.yml
Labels: cross-team

#8275 Replace storybook-chromatic with chromatic because UI tests failing when using emotion
  license-exceptions.json
  package-lock.json
  package.json
Labels: cross-team

#8328 Disable Jenkins reporters
  package.json
Labels: ws-engage

#8332 temporarily remove bundle min/max size
  webpack.config.client.js
Labels: cross-team

#8337 Use tilde instead of caret for package semver restraint
  package-lock.json
  package.json
Labels: ws-engage

#8341 Reinstate package.json with pinned webpack dependencies
  package-lock.json
  package.json
Labels: ws-engage

#8307 Render inLine block inside the Headline/Subheadline block
  data/news/articles/crkxdvxzwxko.json
  src/app/containers/Headings/index.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: cross-team, optimo, ws-engage

#8345 Fix storybook deploy
  .github/workflows/simorgh-deploy-storybook.yml
Labels: cross-team

#8250 [DO NOT MERGE]: Actioning code review feedback: Tidy up amp regex code
  src/app/contexts/RequestContext/getMetaUrls/index.js
  src/app/lib/regex.const.js
  src/app/routes/utils/fetchPageData/utils/getRouteProps/fallbackServiceParam/index.js
  src/app/routes/utils/fetchPageData/utils/getRouteProps/fallbackServiceParam/index.test.js
  src/app/routes/utils/fetchPageData/utils/getRouteProps/index.js
  src/app/routes/utils/fetchPageData/utils/getRouteProps/index.test.js
  src/app/routes/utils/fetchPageData/utils/getRouteProps/routeFallbackParams/index.js
  src/app/routes/utils/fetchPageData/utils/getRouteProps/routeFallbackParams/index.test.js
  src/app/routes/utils/fetchPageData/utils/getUrl/index.js
  src/app/routes/utils/isAmpPath/index.js
Labels: ws-engage

#8347 Remove any steps that do not run on the latest branch i.e. pr checks
  Jenkinsfile
Labels: cross-team, technical-work

#8308 Release Notes: Use head_commit to get the merge commit message
  .github/workflows/simorgh-create-github-release.yml
Labels: cross-team

#8302 GitHub Action: Run puppeteer tests as part of PR checks
  .github/workflows/simorgh-local-server-tests.yml
Labels: technical-work, ws-engage

#8351 Brand skip link fix for no css
  package-lock.json
  package.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
Labels: a11y, cross-team, ws-engage

#8349 Remove storybook generation from Jenkins pipeline
  Jenkinsfile
Labels: cross-team

#8362 Try running all required actions
  .github/workflows/cancel-previous-runs.yml
  .github/workflows/simorgh-e2e-tests.yml
  .github/workflows/simorgh-integration-tests.yml
  .github/workflows/simorgh-local-server-tests.yml
  .github/workflows/simorgh-misc-checks.yml
  .github/workflows/simorgh-unit-tests.yml
Labels: cross-team

#8359 Fix global styles leaking between services and leading to a lot of duplication
  src/server/Document/index.jsx
Labels: technical-work

#8357 Fixing the jenkins build file - stage must include steps
  Jenkinsfile
Labels: cross-team, high-priority

#8363 Update Russian Hindi Chinese navs to remove elex and deprecated links
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/zhongwen.js
Labels: cross-team

#8391 enable code climate setup on branch push
  .github/workflows/simorgh-misc-checks.yml
  .github/workflows/simorgh-unit-tests.yml
Labels: cross-team

#8329 Lighthouse ci config files
  lighthouse/.dockerignore
  lighthouse/Dockerfile
  lighthouse/lighthouserc.js
Labels: cross-team

#8394 Add GIT_SHA & GIT_BRANCH env variables
  .github/workflows/simorgh-unit-tests.yml
Labels: technical-work

#8389 Nav updates ar az bn ky sw ur
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/urdu.js
  src/integration/pages/featureIdxPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
Labels: cross-team

#8352 Social embed layout shifting fix
  src/app/containers/SocialEmbed/__snapshots__/index.test.jsx.snap
  src/app/containers/SocialEmbed/index.jsx
Labels: ws-engage

#8365 Gahuza navigation update
  src/app/lib/config/services/gahuza.js
  src/integration/pages/liveRadio/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/canonical.test.js.snap
Labels: cross-team

#8405 Replace waitFor function with act
  src/app/contexts/ServiceContext/index.test.jsx
Labels: cross-team, ws-engage

#7957 Enable granular chunks
  docs/JavaScript-Bundling-Strategy.md
  package-lock.json
  package.json
  puppeteer/bundleRequests.test.js
  scripts/bundleSize/__mocks__/pageTypeBundleExtractor.js
  scripts/bundleSize/bundleSize.test.js
  scripts/bundleSize/bundleSizeConfig.js
  scripts/bundleSize/getBundleData.js
  scripts/bundleSize/getBundleData.test.js
  scripts/bundleSize/index.js
  scripts/bundleSize/pageTypeBundleExtractor.test.js
  scripts/bundleSize/pages.js
  scripts/bundleSize/sortByBundlesTotalAscending.js
  src/app/containers/Footer/index.test.jsx
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/index.js
  src/integration/common/core.canonical.js
  webpack.config.client.js
Labels: blocked, cross-team

#8406 Dependency Updates
  package-lock.json
  package.json
Labels: cross-team, dependencies

#8415 Dependency Updates - Psammead components in Simorgh
  package-lock.json
  package.json
Labels: cross-team, dependencies

#8358 Add preload scripts for Ad assets
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/Canonical/index.test.jsx
Labels: ws-engage

#8408 Simorgh off Jenkins
  cypress/support/config/envs.js
  envConfig/live.env
  envConfig/test.env
  public/afaanoromoo/manifest.json
  public/afrique/manifest.json
  public/amharic/manifest.json
  public/arabic/manifest.json
  public/archive/manifest.json
  public/azeri/manifest.json
  public/bengali/manifest.json
  public/burmese/manifest.json
  public/cymrufyw/manifest.json
  public/gahuza/manifest.json
  public/gujarati/manifest.json
  public/hausa/manifest.json
  public/hindi/manifest.json
  public/igbo/manifest.json
  public/indonesia/manifest.json
  public/japanese/manifest.json
  public/korean/manifest.json
  public/kyrgyz/manifest.json
  public/marathi/manifest.json
  public/mundo/manifest.json
  public/naidheachdan/manifest.json
  public/nepali/manifest.json
  public/news/manifest.json
  public/pashto/manifest.json
  public/persian/manifest.json
  public/pidgin/manifest.json
  public/portuguese/manifest.json
  public/punjabi/manifest.json
  public/russian/manifest.json
  public/scotland/manifest.json
  public/serbian/manifest.json
  public/sinhala/manifest.json
  public/somali/manifest.json
  public/swahili/manifest.json
  public/tamil/manifest.json
  public/telugu/manifest.json
  public/thai/manifest.json
  public/tigrinya/manifest.json
  public/turkce/manifest.json
  public/ukchina/manifest.json
  public/ukrainian/manifest.json
  public/urdu/manifest.json
  public/uzbek/manifest.json
  public/vietnamese/manifest.json
  public/yoruba/manifest.json
  public/zhongwen/manifest.json
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: cross-team

#8437 Update OD Radio and OD TV Cypress Episode URLs (test and live)
  cypress/support/config/settings.js
Labels: cypress, ws-media

#8438 Add new GNL flagpoles to connectSrc
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-engage

#8439 Fix social embed lazy load
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
  cypress/support/config/settings.js
  data/russian/cpsAssets/news-55041160.json
  package-lock.json
  package.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/SocialEmbed/enrichTweet.jsx
  src/app/containers/SocialEmbed/enrichTweet.test.jsx
  src/app/containers/SocialEmbed/index.jsx
Labels: ws-engage

#8462 Navigation updates for Burmese and others
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/vietnamese.js
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
Labels: cross-team

#8454 E2Es permit embed URLs to be served from fallback
  3rdPartyCypress/cypress/integration/dataEndpoints.js
  3rdPartyCypress/cypress/support/commands.js
  cypress/integration/application/index.js
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  cypress/integration/pages/errorPage404/tests.js
  cypress/integration/pages/errorPage404/testsForAMPOnly.js
  cypress/integration/pages/errorPage404/testsForCanonicalOnly.js
  cypress/integration/pages/liveRadio/testsForAMPOnly.js
  cypress/integration/pages/liveRadio/testsForCanonicalOnly.js
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  cypress/integration/pages/onDemandRadio/tests.js
  cypress/integration/pages/onDemandTV/tests.js
  cypress/support/commands/application.js
  cypress/support/helpers/visitPage.js
Labels: ws-media

#8453 Remove enrichTweet component relying on updated psammead-social-embed…
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
  cypress/support/config/settings.js
  data/russian/cpsAssets/news-55041160.json
  src/app/containers/SocialEmbed/enrichTweet.jsx
  src/app/containers/SocialEmbed/enrichTweet.test.jsx
  src/app/containers/SocialEmbed/index.jsx
Labels: ws-engage

#8456 Add/remove and use pageType constants in routes
  src/app/routes/article/index.js
  src/app/routes/error/index.js
  src/app/routes/errorNoRouteMatch/index.js
  src/app/routes/home/index.js
  src/app/routes/idx/index.js
  src/app/routes/liveRadio/index.js
  src/app/routes/mostRead/index.js
  src/app/routes/mostWatched/index.js
  src/app/routes/onDemandRadio/index.js
  src/app/routes/onDemandTV/index.js
  src/app/routes/utils/pageTypes.js
Labels: cross-team, ws-engage

#8440 Output console errors only
  src/app/lib/logger.web.js
  src/app/lib/logger.web.test.js
Labels: ws-engage

#8503 Russian and Turkce configs: Amend a few public facing strings
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/turkce.js
Labels: cross-team

#8457 Clean Up Simorgh Elections banner implementation
  cypress/integration/pages/frontPage/testsForCanonicalOnly.js
  src/app/containers/USElectionBanner/__snapshots__/index.test.jsx.snap
  src/app/containers/USElectionBanner/index.jsx
  src/app/containers/USElectionBanner/index.test.jsx
  src/app/pages/FrontPage/FrontPage.jsx
  src/app/routes/home/getInitialData/index.js
  src/app/routes/home/getInitialData/index.test.js
  src/server/local/index.js
  src/server/local/index.test.js
Labels: ws-engage

#8451 Start adding new Ads CSP domains
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: security, ws-engage
