Repository bbc/simorgh, pull requests merged in 2020-01, with the labels that each got.

#4990 Cypress test for AMP navigation toggling
  cypress/integration/pages/testsForAllAMPPages.js
  scripts/bundleSizeConfig.js
Labels: ws-frontpage-stream

#5024 update new year snapshots
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
Labels: shared-components

#5025 Dev Dep Updates
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#4815 Added test for ready state on SMP on MAP
  cypress/integration/pages/mediaAssetPage/helpers.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#4992 Map amp 200 status check
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5027 Update Marathi navigation
  src/app/lib/config/services/marathi.js
Labels: ws-frontpage-stream

#5028 Revert "Added test for ready state on SMP on MAP"
  cypress/integration/pages/mediaAssetPage/helpers.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
Labels: ws-media-stream

#4987 chore: log headers
  src/server/index.jsx
Labels: simorgh-core-stream

#4985 If override exists, use a different endpoint for AV embeds.
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/helpers/embedUrl.js
  src/app/containers/MediaPlayer/helpers/embedUrl.test.js
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.test.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/index.test.jsx
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/index.test.jsx
  src/app/lib/utilities/envHelper/index.js
  src/app/lib/utilities/envHelper/index.test.js
  src/app/lib/utilities/rendererEnvHelper/index.js
  src/app/lib/utilities/rendererEnvHelper/index.test.js
  src/app/lib/utilities/urlParser/index.js
  src/app/lib/utilities/urlParser/index.test.js
  src/app/routes/getInitialData/index.js
  src/testHelpers/assertions.js
  src/testHelpers/renderWithRouter.js
Labels: articles-features-stream, ws-media-stream

#5041 Revert "If override exists, use a different endpoint for AV embeds."
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/helpers/embedUrl.js
  src/app/containers/MediaPlayer/helpers/embedUrl.test.js
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.test.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/index.test.jsx
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/index.test.jsx
  src/app/lib/utilities/envHelper/index.js
  src/app/lib/utilities/envHelper/index.test.js
  src/app/lib/utilities/rendererEnvHelper/index.js
  src/app/lib/utilities/rendererEnvHelper/index.test.js
  src/app/lib/utilities/urlParser/index.js
  src/app/lib/utilities/urlParser/index.test.js
  src/app/routes/getInitialData/index.js
  src/testHelpers/assertions.js
  src/testHelpers/renderWithRouter.js
Labels: ws-media-stream

#5042 Tests navigation through first Related Content link - forward and back
  cypress/integration/pages/mediaAssetPage/tests.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5039 Update /news nav items
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/news.js
Labels: articles-features-stream, articles-rollout

#5049 Bumping dev dependencies
  package-lock.json
  package.json
Labels: Heracles, articles-features-stream

#5045 Update Ukrainian and Uzbek configs and translations
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/uzbek.js
Labels: articles-features-stream, articles-rollout

#5051 Use service name in e2e
  cypress/integration/pages/testsForAllAMPPages.js
Labels: ws-frontpage-stream

#4901 Use psammead-grid on frontPageMain
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/components/Grid/README.md
  src/app/components/Grid/__snapshots__/index.test.jsx.snap
  src/app/components/Grid/index.jsx
  src/app/components/Grid/index.stories.jsx
  src/app/components/Grid/index.test.jsx
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.jsx
Labels: grid, ws-frontpage-stream

#4948 Use Brand with Script Link component on services with variants
  cypress/integration/pages/testsForAllPages.js
  package-lock.json
  package.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/Layouts/defaultPageWrapper.test.jsx
  src/app/containers/Brand/__snapshots__/index.test.jsx.snap
  src/app/containers/Brand/index.jsx
  src/app/containers/Brand/index.test.jsx
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/index.test.jsx
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/contexts/ServiceContext/index.jsx
  src/app/contexts/UserContext/cookies/index.js
  src/app/contexts/UserContext/cookies/index.test.js
  src/app/contexts/UserContext/index.jsx
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/zhongwen.js
  src/app/lib/utilities/variantHandler/index.js
  src/app/lib/utilities/variantHandler/index.test.js
Labels: ws-home

#5046 Revert "Tests navigation through first Related Content link - forward and back"
  cypress/integration/pages/mediaAssetPage/tests.js
Labels: ws-media-stream

#5048 Bumping dependencies
  package-lock.json
  package.json
Labels: Heracles, ws-stories

#4932 Improve no-js support
  package-lock.json
  package.json
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.jsx
Labels: a11y-swarm, blocked, ux, ws-stories

#5067 Removed service URLs that have variants as these tests fail
  cypress/support/config/services.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5047 Move page containers to new pages dir and create new cps containers
  data/pidgin/cpsAssets/sport-23252855.json
  data/pidgin/cpsAssets/world-23252817.json
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ArticleMain/index.test.jsx
  src/app/containers/ArticleMain/utils.test.js
  src/app/containers/ArticleMetadata/index.test.jsx
  src/app/containers/CpsAssetPage/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/PageHandlers/withData/index.test.jsx
  src/app/containers/RadioPage/index.jsx
  src/app/pages/Article/__snapshots__/index.test.jsx.snap
  src/app/pages/Article/fixtureData.js
  src/app/pages/Article/index.jsx
  src/app/pages/Article/index.test.jsx
  src/app/pages/CpsMap/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsMap/index.jsx
  src/app/pages/CpsMap/index.test.jsx
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsPgl/index.jsx
  src/app/pages/CpsPgl/index.test.jsx
  src/app/pages/CpsSty/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsSty/index.jsx
  src/app/pages/CpsSty/index.test.jsx
  src/app/pages/Error/__snapshots__/index.test.jsx.snap
  src/app/pages/Error/index.jsx
  src/app/pages/Error/index.test.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/index.jsx
  src/app/pages/FrontPage/index.stories.jsx
  src/app/pages/FrontPage/index.test.jsx
  src/app/pages/RadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/RadioPage/index.jsx
  src/app/pages/RadioPage/index.stories.jsx
  src/app/pages/RadioPage/index.test.jsx
  src/app/routes/getInitialData/utils/getPreprocessorRules/index.js
  src/app/routes/index.js
  src/app/routes/index.test.js
  src/app/routes/pageTypes.js
Labels: ws-stories

#5077 Update readme around adding new pages to simorgh
  README.md
Labels: ws-stories

#5058 Add new fixture for Ukrainian and change test asset
  cypress/support/config/services.js
  data/ukrainian/articles/cp4l2mrejvdo.json
Labels: articles-rollout, ws-stories

#5057 Integrate canonical navigation animation
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/index.amp.jsx
  src/app/containers/Navigation/index.amp.test.jsx
  src/app/containers/Navigation/index.canonical.jsx
  src/app/containers/Navigation/index.canonical.test.jsx
  src/app/containers/Navigation/index.jsx
  src/app/containers/Navigation/testHelpers.jsx
Labels: ws-home

#5073 Tests related content first list item renders href with correct assetURI
  cypress/integration/pages/mediaAssetPage/tests.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5061 Use Psammead Grid for Error pages & Radio pages
  scripts/bundleSizeConfig.js
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorPage/index.jsx
  src/app/components/ErrorPage/index.test.jsx
  src/app/components/Grid/index.jsx
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ErrorMain/index.jsx
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/index.jsx
Labels: grid, ws-home

#5079 Bump locale deps
  package-lock.json
  package.json
Labels: ws-home

#5084 Update uzbek menu
  src/app/lib/config/services/uzbek.js
Labels: ws-home

#5082 Changed config so that URLS for Igbo, Pidgin and Yoruba run on test
  cypress/support/config/services.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5044 If renderer_env override exists, use a different endpoint for AV embeds
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  package-lock.json
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/index.test.jsx
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/fixtureData.jsx
  src/app/containers/MediaPlayer/helpers/embedUrl.js
  src/app/containers/MediaPlayer/helpers/embedUrl.test.js
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/MediaPlayer/index.stories.jsx
  src/app/containers/MediaPlayer/index.test.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.test.jsx
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/index.test.jsx
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/index.stories.jsx
  src/app/containers/RadioPageMain/index.test.jsx
  src/app/lib/utilities/getEmbedUrl/index.js
  src/app/lib/utilities/getEmbedUrl/index.test.js
  src/app/lib/utilities/isLive/index.js
  src/app/lib/utilities/isLive/index.test.js
  src/app/lib/utilities/urlParser/index.js
  src/app/lib/utilities/urlParser/index.test.js
  src/app/pages/RadioPage/index.stories.jsx
  src/app/routes/getInitialData/index.js
Labels: ws-media-stream

#5088 Fix See All translation in Uzbek
  src/app/lib/config/services/uzbek.js
Labels: ws-home

#4455 Skip Additional Rendering
  src/app/containers/App/App.jsx
  src/app/containers/App/App.test.jsx
Labels: bug, high priority, simorgh-core-stream, ws-home

#5072 Spacing of map timestamp
  .env
  src/app/containers/ArticleTimestamp/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/ArticleTimestamp/index.test.jsx
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
Labels: ws-media-stream

#5036 DONT MERGE UNTIL WED - Enable LIVE e2es for Telugu Marathi Gujarati Tamil Uzbek
  cypress/support/config/services.js
Labels: ws-home

#5115 Update psammead-bulleted-list version
  package-lock.json
  package.json
  src/app/containers/BulletedList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsText/__snapshots__/index.test.jsx.snap
Labels: ws-media-stream

#5120 Add Uzbek translations
  src/app/lib/config/services/uzbek.js
Labels: high priority, ws-home

#5056 Retry Mozart fallback errors in e2es
  cypress/integration/pages/errorPage404/tests.js
  cypress/support/commands/application.js
  cypress/support/commands/index.js
  cypress/support/helpers/runTestsForPage.js
Labels: simorgh-core-stream, ws-home, ws-media-stream, ws-stories

#5087 Integrate changes for scrollable navigation
  package-lock.json
  package.json
  src/app/containers/Navigation/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/Navigation/index.amp.jsx
  src/app/containers/Navigation/index.canonical.jsx
  src/app/lib/utilities/useMediaQuery/index.jsx
  src/app/lib/utilities/useMediaQuery/index.test.jsx
Labels: ws-home

#4977 AV: e2e tests for AMP
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/articles/testsForCanonicalOnly.js
Labels: articles-av-epic, integration-testing, ws-stories

#5119 Enable Live Radio E2Es for Afrique, Bengali, Burmese, Gahuza, Swahili
  cypress/support/config/services.js
Labels: ws-media-stream

#5129 Fixing MAP Headline breakpoint spacing
  scripts/bundleSizeConfig.js
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/FauxHeadline/__snapshots__/index.test.jsx.snap
  src/app/containers/FauxHeadline/index.jsx
Labels: ws-media-asset-page-v1, ws-media-stream

#5130 Update Tamil cookie banner with the updated text
  src/app/lib/config/services/tamil.js
Labels: ws-home

#5138 E2Es live for nepali sinhala tamil pashto
  cypress/support/config/services.js
Labels: cypress, ws-media- LiveRadioV1, ws-media-liveRadioV2, ws-media-stream

#5089 #5065 Both timestamps displayed on CPS Maps pages
  data/igbo/cpsAssets/afirika-23252735.json
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/ArticleTimestamp/index.test.jsx
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
Labels: ws-media-stream

#5127 Fix Special Characters within XML tags
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/paragraph/helpers.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/paragraph/helpers.test.js
Labels: ws-media-stream

#5083 Internal Links Transformer
  scripts/bundleSizeConfig.js
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/inputFixture.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/outputFixture.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/paragraph/helpers.js
  src/app/routes/getInitialData/utils/preprocessorRulesConfig/index.js
Labels: ws-media-stream

#5148 Fix failing Cypress test for timestamp
  cypress/integration/pages/mediaAssetPage/tests.js
Labels: ws-media-stream

#5146 5060 radio schedule config
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-home

#5140 Add radio schedules fixture data
  data/arabic/bbc_arabic_radio/radioschedule.json
  data/gahuza/bbc_gahuza_radio/radioschedule.json
  data/hausa/bbc_hausa_radio/radioschedule.json
  data/korean/bbc_korean_radio/radioschedule.json
  data/pashto/bbc_pashto_radio/radioschedule.json
  data/persian/bbc_dari_radio/radioschedule.json
  data/persian/bbc_persian_radio/radioschedule.json
  data/somali/bbc_somali_radio/radioschedule.json
  data/urdu/bbc_urdu_radio/radioschedule.json
Labels: radio-schedules, ws-home

#5123 Update TrustProject links in service config
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/uzbek.js
Labels: ws-home

#5145 Config change to run Krygyz live radio E2Es on live
  cypress/support/config/services.js
Labels: cypress, ws-media- LiveRadioV1, ws-media-stream

#5151 Removed Thai URL from Cypress test config
  cypress/support/config/services.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5152 Standardise MAP Timestamps
  package-lock.json
  package.json
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/timestampToMilliseconds/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/timestampToMilliseconds/index.test.js
Labels: ws-media-stream

#5143 Fix internal link chevrons
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/outputFixture.js
Labels: ws-media-stream

#5043 Pass isAmp to the RequestContext
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ChartbeatAnalytics/index.jsx
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/containers/ConsentBanner/index.jsx
  src/app/containers/ImageWithPlaceholder/index.jsx
  src/app/containers/MediaPlayer/index.jsx
  src/app/containers/Metadata/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/index.test.jsx
  src/app/containers/RadioPageBlocks/index.test.jsx
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
  src/app/contexts/UserContext/Chartbeat/index.jsx
Labels: ws-home

#5160 Cypress test checks ready state of SMP player
  cypress/integration/pages/mediaAssetPage/helpers.js
  cypress/integration/pages/mediaAssetPage/tests.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5163 Ensure nav remains visible when screen width changes
  src/app/containers/Navigation/index.canonical.jsx
  src/app/lib/utilities/useMediaQuery/index.jsx
  src/app/lib/utilities/useMediaQuery/index.test.jsx
Labels: bug, ws-home

#5162 Update eslint-plugin-import
  .eslintrc.js
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#5164 [DO NOT MERGE] Added E2E live URLs for Pidgin, Yoruba, Igbo
  cypress/support/config/services.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5142 Dependency updates - all dependabot PRs combined
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#5168 Add 41 new PGL assets
  data/afaanoromoo/cpsAssets/oduu-41217768.json
  data/afrique/cpsAssets/region-39269126.json
  data/amharic/cpsAssets/42743191.json
  data/arabic/cpsAssets/art-and-culture-38260491.json
  data/azeri/cpsAssets/azerbaijan-44208474.json
  data/bengali/cpsAssets/news-38827173.json
  data/burmese/cpsAssets/media-47680015.json
  data/gahuza/cpsAssets/amakuru-43894701.json
  data/gujarati/cpsAssets/international-41345658.json
  data/hausa/cpsAssets/labarai-39326441.json
  data/hindi/cpsAssets/india-50198153.json
  data/igbo/cpsAssets/afirika-49666505.json
  data/igbo/cpsAssets/egwuregwu-23252841.json
  data/indonesia/cpsAssets/indonesia-41635759.json
  data/japanese/cpsAssets/features-and-analysis-42786589.json
  data/japanese/cpsAssets/world-23252856.json
  data/korean/cpsAssets/features-41397333.json
  data/kyrgyz/cpsAssets/world-40847556.json
  data/marathi/cpsAssets/india-42894522.json
  data/mundo/cpsAssets/deportes-36935058.json
  data/nepali/cpsAssets/news-50627370.json
  data/pashto/cpsAssets/arts-and-literature-50230813.json
  data/persian/cpsAssets/magazine-49281981.json
  data/pidgin/cpsAssets/tori-49221071.json
  data/portuguese/cpsAssets/geral-40302633.json
  data/punjabi/cpsAssets/india-42928885.json
  data/russian/cpsAssets/features-45782775.json
  data/serbian/cpsAssets/srbija-46748932/lat.json
  data/sinhala/cpsAssets/world-37657374.json
  data/somali/cpsAssets/war-45947544.json
  data/swahili/cpsAssets/habari-48185450.json
  data/tamil/cpsAssets/global-47758688.json
  data/telugu/cpsAssets/india-42321552.json
  data/thai/cpsAssets/international-23252840.json
  data/thai/cpsAssets/thailand-49950038.json
  data/tigrinya/cpsAssets/news-49944566.json
  data/turkce/cpsAssets/haberler-dunya-50924340.json
  data/ukchina/cpsAssets/cool-britannia-38434549/trad.json
  data/ukrainian/cpsAssets/features-41278900.json
  data/urdu/cpsAssets/pakistan-48242478.json
  data/uzbek/cpsAssets/central-asia-46716844.json
  data/vietnamese/cpsAssets/world-48605529.json
  data/yoruba/cpsAssets/ere-idaraya-23252842.json
  data/yoruba/cpsAssets/media-50970014.json
  data/zhongwen/cpsAssets/chinese-news-49065935/trad.json
Labels: ws-stories

#5171 FIx ampersand issue for MAPs
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/index.test.js
Labels: ws-media-stream

#5147 tidy up internal link transformer
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/index.js
Labels: ws-media-stream

#5172 Disable e2e tests for front pages which are no longer available on test
  cypress/support/config/services.js
Labels: ws-home, ws-stories

#5176 Removing inline link test for test env
  cypress/integration/pages/articles/tests.js
Labels: ws-stories

#5153 Render summary on a PGL
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addSummaryBlock/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addSummaryBlock/index.test.js
  src/app/routes/getInitialData/utils/preprocessorRulesConfig/index.js
Labels: stories-pgl, ws-stories

#5178 Update navigation version
  package-lock.json
  package.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/index.canonical.test.jsx
Labels: ws-home

#5157 Add E2E test for script link and mobile menu
  cypress/integration/pages/testsForAllAMPPages.js
  cypress/integration/pages/testsForAllPages.js
  src/app/containers/Brand/index.test.jsx
  src/app/containers/Navigation/index.test.jsx
Labels: ws-home

#5181 Uzbek articles route has been disabled in Mozart for the test env
  cypress/support/config/services.js
Labels: ws-stories

#5165 Add local route for radio schedule
  src/app/routes/regex/index.test.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: radio-schedules, ws-home

#5215 Translation & navigation updates
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/uzbek.js
Labels: ws-home

#5075 Improve SEO discoverability of dateModified for MAPs
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
Labels: ws-media-stream

#5124 Simplify shouldRenderLiveData
  src/app/lib/utilities/getEmbedUrl/index.js
Labels: ws-media-stream

#5223 Ignore failing a11y test
  a11y.js
Labels: ws-home

#5141 White space below footer fix
  README.md
  src/app/components/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/components/ErrorPage/index.jsx
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMain/index.jsx
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/index.jsx
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.jsx
Labels: ws-stories

#5074 APP_ENV environment variable consolidation
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/contexts/RequestContext/getOriginContext/index.js
  src/app/contexts/RequestContext/getOriginContext/index.test.js
  src/app/lib/utilities/getEmbedUrl/index.test.js
  src/app/lib/utilities/isLive/index.test.js
  src/app/routes/getInitialData/index.js
  src/app/routes/getInitialData/index.test.js
  src/server/Document/index.jsx
  src/server/Document/index.test.jsx
  src/server/index.jsx
  webpack.config.client.js
Labels: ws-media-stream

#5166 Remove CpsAssetPageMain, move logic to /pages
  dirAlias.js
  src/app/containers/CpsAssetPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetPageMain/index.jsx
  src/app/containers/CpsAssetPageMain/index.test.jsx
  src/app/pages/CpsMap/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsMap/index.jsx
  src/app/pages/CpsMap/index.test.jsx
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsPgl/index.jsx
  src/app/pages/CpsPgl/index.test.jsx
  src/app/pages/CpsSty/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsSty/index.jsx
  src/app/pages/CpsSty/index.test.jsx
Labels: container-cleanup, ws-media-stream, ws-stories

#5243 Merge pull request #5243 from bbc/HerRoyalMajestysEnglishOnly
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: ws-home, ws-stories

#5225 Add RadioScheduleContainer
  .storybook/static/data/arabic/bbc_arabic_radio/radioschedule.json
  .storybook/static/data/gahuza/bbc_gahuza_radio/radioschedule.json
  .storybook/static/data/hausa/bbc_hausa_radio/radioschedule.json
  .storybook/static/data/korean/bbc_korean_radio/radioschedule.json
  .storybook/static/data/pashto/bbc_pashto_radio/radioschedule.json
  .storybook/static/data/persian/bbc_dari_radio/radioschedule.json
  .storybook/static/data/persian/bbc_persian_radio/radioschedule.json
  .storybook/static/data/somali/bbc_somali_radio/radioschedule.json
  .storybook/static/data/urdu/bbc_urdu_radio/radioschedule.json
  src/app/containers/RadioSchedule/index.jsx
  src/app/containers/RadioSchedule/index.stories.jsx
  src/app/containers/RadioSchedule/index.test.jsx
Labels: radio-schedules, ws-home

#5244 Add Radio Schedule toggles
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
Labels: radio-schedules, ws-home

#5246 Move ArticleMain utils to common utils
  src/app/containers/ArticleMain/index.jsx
  src/app/lib/utilities/parseAssetData/index.js
  src/app/lib/utilities/parseAssetData/index.test.js
  src/app/pages/CpsMap/index.jsx
  src/app/pages/CpsPgl/index.jsx
  src/app/pages/CpsSty/index.jsx
Labels: tech-debt, ws-stories

#5217 Group dependabot PRs - #5185 to #5208
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/Brand/__snapshots__/index.test.jsx.snap
  src/app/containers/Bulletin/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/LiveRadio/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/IndexAlsos/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/MediaIndicator/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsMap/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsSty/__snapshots__/index.test.jsx.snap
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#5249 Create and use new 'pages' alias
  dirAlias.js
  jsconfig.json
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ArticleMain/index.test.jsx
  src/app/containers/ArticleMetadata/index.test.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/PageHandlers/withData/index.test.jsx
  src/app/lib/utilities/parseAssetData/index.test.js
  src/app/routes/index.js
  src/app/routes/index.test.js
Labels: tech-debt, ws-stories

#5238 Add description and About Tags to PGL Linked Data
  src/app/containers/LinkedData/__snapshots__/index.test.jsx.snap
  src/app/containers/LinkedData/index.jsx
  src/app/containers/LinkedData/index.test.jsx
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsPgl/index.jsx
  src/app/pages/CpsPgl/index.test.jsx
Labels: stories-pgl, ws-stories

#5231 Set privacy policy domain
  src/app/containers/ConsentBanner/CanonicalLogic/index.js
  src/app/containers/ConsentBanner/CanonicalLogic/index.test.js
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/testHelpers/jest-setup.js
Labels: ws-media-asset-page-v2, ws-media-stream

#5250 5248 MAP timestamp popping out
  src/app/pages/CpsMap/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsMap/index.jsx
  src/app/pages/CpsMap/index.test.jsx
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsPgl/index.jsx
  src/app/pages/CpsSty/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsSty/index.jsx
Labels: ws-media-stream

#5252 Enable E2Es for Nepali, Afaanoromoo, Amharic, Bengali, Sinhala, and Tigrinya
  cypress/support/config/services.js
Labels: ws-home

#5279 fix for sendCanonicalChartbeatBeacon is not a function
  src/app/containers/ArticleMain/index.stories.jsx
  src/app/containers/FrontPageMain/index.stories.jsx
Labels: bug, ws-home, ws-stories

#5285 Enable e2es for Archive and Ukrainian Articles
  cypress/integration/application/index.js
  cypress/support/config/services.js
Labels: articles-rollout

#5288 Update "why you can trust the BBC" link URLs
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
Labels: ws-media-stream

#5253 Add MAP pages to Storybook
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/fixtures.js
  src/app/containers/CpsAssetMediaPlayer/index.stories.jsx
  src/app/containers/CpsAssetMediaPlayer/index.test.jsx
  src/app/pages/CpsMap/fixtureData.json
  src/app/pages/CpsMap/index.stories.jsx
Labels: ws-media-stream

#5289 Group all dependabot PRs bumping Psammead packages
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#5299 Fix Thai stream ExternalId and id in fixture data
  cypress/support/config/services.js
  data/thai/cpsAssets/thailand-23248713.json
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#5282 added new viewport for few tests
  cypress/integration/pages/frontPage/tests.js
Labels: ws-front-page-layout, ws-home

#5300 Add https://cdn.ampproject.org to CSP connect-src directive
  src/server/utilities/constructCspHeader/index.js
  src/server/utilities/constructCspHeader/index.test.js
Labels: ws-home

#5220 Improve Shareability of MAP pages on Social Media
  cypress/integration/pages/testsForAllPages.js
  cypress/support/helpers/getBrandedImage.js
  src/app/containers/CpsMetadata/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsMetadata/index.jsx
  src/app/containers/CpsMetadata/index.test.jsx
  src/app/containers/CpsMetadata/utils/getBrandedImage/index.js
  src/app/containers/CpsMetadata/utils/getBrandedImage/index.test.js
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/pages/CpsMap/index.jsx
  src/app/pages/CpsMap/index.test.jsx
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsPgl/index.jsx
  src/app/pages/CpsSty/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsSty/index.jsx
Labels: ws-media-stream, ws-stories

#5297 Split translations for services with variants
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-home, ws-media-stream, ws-stories

#5306 Added Hausa and Somali to run on local and test E2Es
  cypress/support/config/services.js
Labels: cypress, ws-media- LiveRadioV1, ws-media-stream

#5307 Use "property" attribute on facebook's "og:" meta tags
  cypress/integration/pages/testsForAllPages.js
  src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMetadata/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsMetadata/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsMetadata/index.test.jsx
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/__snapshots__/index.test.jsx.snap
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/RadioPageMain/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsMap/index.test.jsx
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsSty/__snapshots__/index.test.jsx.snap
Labels: ws-media-stream, ws-stories

#5278 Merge row logic into desktop layout PR
  data/igbo/frontpage/index.json
  scripts/bundleSizeConfig.js
  src/app/containers/FrontPageMain/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageMain/index.jsx
  src/app/containers/FrontPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageSection/index.jsx
  src/app/containers/FrontPageSection/index.test.jsx
  src/app/containers/FrontPageSection/utilities/rowDetails.jsx
  src/app/containers/FrontPageSection/utilities/rowDetails.test.jsx
  src/app/containers/FrontPageSection/utilities/storySplitter.jsx
  src/app/containers/FrontPageSection/utilities/storySplitter.test.jsx
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/index.jsx
  src/app/containers/FrontPageStoryRows/index.stories.jsx
  src/app/containers/FrontPageStoryRows/index.test.jsx
  src/app/containers/FrontPageStoryRows/testHelpers.js
  src/app/containers/StoryPromo/index.jsx
  src/app/lib/utilities/preprocessor/rules/__snapshots__/filterContentType.test.js.snap
  src/app/lib/utilities/preprocessor/rules/__snapshots__/topstories.test.js.snap
Labels: ws-front-page-layout, ws-home

#5233 feat: render analytics for pgl page types #5230
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsPgl/fixtureData.json
Labels: ws-stories

#5309 Update trust project links for services
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/sinhala.js
Labels: ws-home

#5290 Group Dependabot PRs - non-Psammead packages updates
  package-lock.json
  package.json
  src/app/contexts/EventContext/__snapshots__/index.test.jsx.snap
Labels: ws-home, ws-media-stream, ws-stories

#5317 Fix spacing at the end of bulleted lists
  src/app/containers/BulletedList/__snapshots__/index.test.jsx.snap
  src/app/containers/BulletedList/index.jsx
  src/app/containers/CpsText/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsMap/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsSty/__snapshots__/index.test.jsx.snap
Labels: ws-media-stream

#5324 Disable original MAP E2Es on test
  cypress/support/config/services.js
Labels: ws-media-stream

#5320 Enable Hausa & Somali Live Radio E2Es
  cypress/support/config/services.js
Labels: ws-media-stream

#5312 Adds PGL and STY pages to storybook
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/pages/CpsPgl/fixtureData.json
  src/app/pages/CpsPgl/index.stories.jsx
  src/app/pages/CpsSty/fixtureData.json
  src/app/pages/CpsSty/index.stories.jsx
Labels: stories-pgl, ws-stories

#5337 Removing archive from cypress testing
  cypress/integration/application/index.js
  cypress/support/config/services.js
Labels: ws-stories

#5275 Implement config and toggles to hide radio schedule
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/RadioSchedule/index.jsx
  src/app/containers/RadioSchedule/index.stories.jsx
  src/app/containers/RadioSchedule/index.test.jsx
  src/app/lib/config/toggles/index.js
Labels: radio-schedules, ws-home

#5343 Disable /archive e2e tests entirely
  cypress/support/config/services.js
Labels: ws-stories

#5345 revert media player no js translation changes
  add-no-translations.js
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
Labels: ws-media-stream

#5329 No js translations
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-media-stream

#5318 `cpsOnlyOnwardJourney` pre-processor rule
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/cpsOnlyOnwardJourneys/fixtures/pglSomeCpsOnwardJourneys/expectedSeeAlsoGroup.json
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/cpsOnlyOnwardJourneys/fixtures/pglSomeCpsOnwardJourneys/fullAsset.json
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/cpsOnlyOnwardJourneys/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/cpsOnlyOnwardJourneys/index.test.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/timestampToMilliseconds/index.js
  src/app/lib/utilities/preprocessor/rules/cpsAssetPage/timestampToMilliseconds/index.test.js
  src/app/pages/CpsPgl/__snapshots__/index.test.jsx.snap
  src/app/pages/CpsPgl/index.test.jsx
  src/app/routes/getInitialData/utils/preprocessorRulesConfig/index.js
Labels: ws-stories
