Repository bbc/simorgh, pull requests merged in 2020-06, with the labels that each got.

#6728 Revert "encode x6 and x5 on canonical"
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/article/buildParams.test.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/ATIAnalytics/params/mostReadPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/tvRadioPage/buildParams.test.js
Labels: ws-home

#6725 Run bbc-a11y against IDX pages
  a11y.js
  cypress/support/config/settings.js
Labels: IDX, ws-home

#6531 Adding a11y tests for on demand radio episode pages
  a11y.js
  package.json
Labels: ws-media-ondemandRadio, ws-media-stream

#6354 Adding base integration tests for PGLs
  src/integration/pages/photoGalleryPage/ampTests.js
  src/integration/pages/photoGalleryPage/canonicalTests.js
  src/integration/pages/photoGalleryPage/crossPlatformTests.js
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/amp.test.js
  src/integration/pages/photoGalleryPage/mundo/canonical.test.js
Labels: cypress, ws-stories

#6701 Adding Chartbeat to OD TV Pages
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/pages/LiveRadioPage/fixtureData/afaanoromoo.json
  src/app/pages/LiveRadioPage/fixtureData/amharic.json
  src/app/pages/LiveRadioPage/fixtureData/indonesia.json
  src/app/pages/LiveRadioPage/fixtureData/korean.json
  src/app/pages/LiveRadioPage/fixtureData/tigrinya.json
  src/app/pages/OnDemandTvPage/index.jsx
  src/app/routes/liveRadio/getInitialData/index.js
  src/app/routes/onDemandTV/getInitialData/index.js
Labels: ws-media-onDemandTV, ws-media-stream

#6732 Remove STY byline e2e
  cypress/integration/pages/storyPage/tests.js
Labels: cypress, stories-STYs, ws-stories

#6524 E2Es for On Demand Radio Brand page
  a11y.js
  cypress/integration/pages/onDemandRadio/helpers.js
  cypress/integration/pages/onDemandRadio/index.js
  cypress/integration/pages/onDemandRadio/tests.js
  cypress/integration/pages/onDemandRadio/testsForAMPOnly.js
  cypress/integration/pages/onDemandRadio/testsForCanonicalOnly.js
  cypress/integration/specialFeatures/utilities/onDemandRadioJourneyActions/index.js
  cypress/support/config/settings.js
  cypress/support/helpers/getPaths.js
  cypress/support/helpers/getPaths/index.js
  cypress/support/helpers/getPaths/index.test.js
  scripts/ampHtmlValidator/index.js
Labels: cypress, weekly-goal, ws-media-ondemandRadio, ws-media-stream

#6743 Temporarily disable indonesian & pashto on demand radio E2Es
  cypress/support/config/settings.js
Labels: cypress, ws-media-stream

#6478 Remove geoiplookup from toggles endpoint
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Amp/index.test.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/contexts/ToggleContext/index.test.jsx
  src/app/contexts/ToggleContext/reducer.jsx
  src/app/contexts/ToggleContext/utils/constructTogglesEndpoint/index.js
  src/app/contexts/ToggleContext/utils/constructTogglesEndpoint/index.test.js
  src/app/hooks/useToggle/index.test.jsx
  src/app/hooks/useToggle/useToggle.test.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
Labels: ads, ws-media-stream, ws-stories

#6710 Adding Video Player for OD TV
  data/pashto/bbc_pashto_tv/w172xcldhhrdqgb.json
  src/app/pages/OnDemandTvPage/VideoPlayer/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/VideoPlayer/index.jsx
  src/app/pages/OnDemandTvPage/VideoPlayer/index.test.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.jsx
  src/app/pages/OnDemandTvPage/index.test.jsx
  src/app/routes/onDemandTV/getInitialData/index.js
Labels: ws-media-onDemandTV, ws-media-stream

#6714 Add routing regex for OD TV Episodes
  data/pashto/bbc_pashto_tv/tv/w172xcldhhrhmcf.json
  data/pashto/bbc_pashto_tv/tv_programmes/w13xttn4.json
  src/app/pages/OnDemandTvPage/index.test.jsx
  src/app/routes/index.test.jsx
  src/app/routes/onDemandTV/getInitialData/index.test.js
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: ws-media-onDemandTV, ws-media-stream

#6625 Added upgrade-insecure-requests CSP directive
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: includes, security, stories-STYs, ws-home, ws-media-stream, ws-stories

#6736 Dependency Updates
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#6761 Reduce number of MAP E2E services enabled
  cypress/support/config/settings.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#6749 Remove fixed deps from audit allowlist
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#6727 Fix logging for includes
  src/app/lib/logger.const.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
Labels: stories-STYs, ws-stories

#6707 Migrate header tests
  cypress/integration/pages/testsForAllPages.js
  src/integration/common/header.js
  src/integration/pages/articles/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persianTc2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persianTc2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: ws-home, ws-media-stream, ws-stories

#6750 Update Bengali and Swahili links
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/swahili.js
Labels: ws-home

#6690 Re-enable Canonical Ads with e2e fixes
  src/app/containers/Ad/Canonical/AdSlot.jsx
  src/app/containers/Ad/Canonical/AdSlot.test.jsx
  src/app/containers/Ad/Canonical/CanonicalAdBootstrapJs.jsx
  src/app/containers/Ad/Canonical/__snapshots__/CanonicalAdBootstrapJs.test.jsx.snap
  src/app/containers/Ad/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/Canonical/index.test.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.jsx
  src/app/containers/Ad/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/zhongwen.js
  src/app/lib/config/toggles/index.js
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/index.jsx
  src/app/pages/FrontPage/index.test.jsx
Labels: ads, ws-home

#6764 live radio int tests tidy up
  src/integration/common/index.js
  src/integration/common/mainHeading.js
  src/integration/pages/liveRadio/amharic/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/amharic/amp.test.js
  src/integration/pages/liveRadio/amharic/canonical.test.js
  src/integration/pages/liveRadio/ampTests.js
  src/integration/pages/liveRadio/canonicalTests.js
  src/integration/pages/liveRadio/crossPlatformTests.js
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/amp.test.js
  src/integration/pages/liveRadio/korean/canonical.test.js
Labels: ws-media-stream

#6300 MAP integration test improvements
  data/arabic/legacyAssets/multimedia/2014/05/140515_kenia_children_sex_trade.json
  package.json
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsOnwardJourney/index.jsx
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/common/analytics.amp.js
  src/integration/common/mediaPlayerEmbed.js
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/ampTests.js
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/amp.test.js
  src/integration/pages/mediaAssetPage/arabicTC2/canonical.test.js
  src/integration/pages/mediaAssetPage/crossPlatformTests.js
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/amp.test.js
  src/integration/pages/mediaAssetPage/persian/canonical.test.js
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashtoBrand/__snapshots__/canonical.test.js.snap
Labels: ws-media-stream

#6700 a11y - Add Visually Hidden Headline to On-Demand TV
  package-lock.json
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/index.test.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.jsx
  src/app/pages/OnDemandTvPage/index.test.jsx
Labels: ws-media-onDemandTV, ws-media-stream

#6711 bump most read (to fix UI bug)
  .storybook/static/data/ukchina/mostRead/trad.json
  data/zhongwen/mostRead/simp.json
  package-lock.json
  package.json
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/index.stories.jsx
Labels: most-read, ux, ws-home

#6664 Move the timestamp on STYs
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/routes/utils/sharedDataTransformers/augmentWithTimestamp/index.js
  src/app/routes/utils/sharedDataTransformers/augmentWithTimestamp/index.test.js
  src/integration/pages/storyPage/ampTests.js
  src/integration/pages/storyPage/canonicalTests.js
  src/integration/pages/storyPage/crossPlatformTests.js
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: stories-STYs, ux, ws-stories

#6606 Refactor - remove live radio block mapping logic
  src/app/containers/RadioPageBlocks/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/index.jsx
  src/app/containers/RadioPageBlocks/index.test.jsx
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/index.jsx
  src/app/routes/liveRadio/getInitialData/addIdsToBlocks.js
  src/app/routes/liveRadio/getInitialData/index.js
  src/app/routes/liveRadio/getInitialData/index.test.js
Labels: tech-debt, ws-media-stream

#6778 Catch AMP Analytics error in cypress tests
  cypress/support/index.js
Labels: ws-home, ws-media-stream, ws-stories

#6663 Display Most Read on /persian/afghanistan IDX page
  package-lock.json
  src/app/containers/MostRead/index.jsx
  src/app/containers/MostRead/label.jsx
  src/app/containers/MostRead/label.test.jsx
  src/app/containers/MostRead/section.jsx
  src/app/containers/MostRead/section.test.jsx
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/ukrainian.js
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/ArticlePage/index.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/index.jsx
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/index.jsx
  src/app/pages/IdxPage/index.stories.jsx
  src/app/pages/IdxPage/index.test.jsx
  src/app/pages/IdxPage/testHelpers/index.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: IDX, ws-home

#6747 Add Chartbeat analytics to Story Pages
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.jsx
  src/app/pages/StoryPage/index.test.jsx
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
Labels: stories-STYs, ws-stories

#6643 Rename OnDemand Radio integration tests folder
  src/integration/pages/onDemandRadioEpisode/indonesia.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioEpisode/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/ampTests.js
  src/integration/pages/onDemandRadioPage/canonicalTests.js
  src/integration/pages/onDemandRadioPage/commonEpisodeTests.js
  src/integration/pages/onDemandRadioPage/crossPlatformTests.js
  src/integration/pages/onDemandRadioPage/expiredEpisodeTests.js
  src/integration/pages/onDemandRadioPage/indonesia.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia.expired/amp.test.js
  src/integration/pages/onDemandRadioPage/indonesia.expired/canonical.test.js
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/amp.test.js
  src/integration/pages/onDemandRadioPage/indonesia/canonical.test.js
  src/integration/pages/onDemandRadioPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto.expired/amp.test.js
  src/integration/pages/onDemandRadioPage/pashto.expired/canonical.test.js
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/amp.test.js
  src/integration/pages/onDemandRadioPage/pashto/canonical.test.js
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/amp.test.js
  src/integration/pages/onDemandRadioPage/pashtoBrand/canonical.test.js
Labels: weekly-goal, ws-media-ondemandRadio, ws-media-stream

#6771 Move episode availability logic to getInitialData
  src/app/pages/OnDemandTvPage/VideoPlayer/index.jsx
  src/app/pages/OnDemandTvPage/index.jsx
  src/app/routes/onDemandTV/getInitialData/index.js
  src/app/routes/onDemandTV/getInitialData/index.test.js
Labels: ws-media-onDemandTV, ws-media-stream

#6793 Remove padding when screen is smaller than 1008px
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
Labels: ws-media-ondemandRadio, ws-media-stream

#6786 Re-enabled E2E OD Radio brand URLs, added episode URLs
  cypress/support/config/settings.js
Labels: cypress, ws-media-ondemandRadio, ws-media-stream

#6712 Adding Linked Data to OD TV Pages
  src/app/pages/OnDemandTvPage/index.jsx
Labels: ws-media-onDemandTV, ws-media-stream

#6794 Translation fix for Pashto
  src/app/lib/config/services/pashto.js
Labels: ws-stories

#6768 Disable services to reduce e2e run time
  cypress/support/config/settings.js
Labels: ws-stories

#6752 Revert "Revert "encode x6 and x5 on canonical""
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/article/buildParams.test.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/ATIAnalytics/params/mostReadPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/tvRadioPage/buildParams.test.js
Labels: analytics, ws-home

#6683 Add Metadata and LinkedData to IDX pages
  src/app/pages/IdxPage/index.jsx
Labels: IDX, ws-home

#6755 Adding Padding to OD TV Page
  src/app/pages/OnDemandTvPage/VideoPlayer/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/VideoPlayer/index.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.jsx
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: ws-media-onDemandTV, ws-media-stream

#6757 Enable Live and Test STY E2Es for batch two services
  cypress/support/config/settings.js
  data/sinhala/cpsAssets/23225618.json
Labels: ws-stories

#6726 Add Radio Schedule to /persian/afghanistan IDX page
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/ukrainian.js
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/index.jsx
  src/app/pages/IdxPage/index.stories.jsx
  src/app/pages/IdxPage/index.test.jsx
  src/app/pages/IdxPage/testHelpers/index.jsx
  src/app/routes/idx/getInitialData/index.js
  src/app/routes/utils/withRadioSchedule/index.js
Labels: IDX, ws-home

#6805 improve int test dev experience
  package-lock.json
  package.json
  src/integration/README.md
  src/integration/common/core.canonical.js
  src/integration/utils/runTests/index.js
Labels: ws-media-stream

#6783 Update CSP advice
  src/server/utilities/cspHeader/index.js
Labels: ws-home, ws-media-stream, ws-stories

#6810 Updating OD Radio Styling
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/OnDemandImage/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/OnDemandImage/index.jsx
  src/app/containers/RadioPageBlocks/Blocks/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioPageBlocks/Blocks/Paragraph/index.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
Labels: ws-media-ondemandRadio, ws-media-stream

#6809 Bump rich text transforms package
  data/pashto/cpsAssets/world-52924930.json
  package-lock.json
  package.json
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/paragraph/index.test.js
Labels: high-priority, stories-STYs, ws-stories

#6826 Amend Sinhala live e2e STY asset
  cypress/support/config/settings.js
Labels: stories-STYs, ws-stories

#6813 Fix Carto includes CSP error
  data/pashto/cpsAssets/afghanistan-52562598.json
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: high-priority, stories-STYs, ws-stories

#6788 Update Release Info
  data/sinhala/cpsAssets/23164225.json
  docs/Simorgh-Release-Info.md
  scripts/simorghLaunchDates.js
Labels: Documentation, stories-STYs, ws-stories

#6830 Passport control csp
  package-lock.json
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: stories-STYs, ws-stories

#6828 increase most read fresh data threshold to 60mintues
  src/app/containers/MostRead/utilities/index.js
  src/app/containers/MostRead/utilities/index.test.js
  src/app/containers/MostRead/utilities/processMostRead.js
  src/app/containers/MostRead/utilities/processMostRead.test.js
Labels: most-read, ws-home

#6777 add include_rendered and social_embed_renedered loggers
  src/app/containers/Include/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/index.jsx
  src/app/containers/Include/index.test.jsx
  src/app/containers/SocialEmbed/index.jsx
  src/app/containers/SocialEmbed/index.test.jsx
  src/app/lib/logger.const.js
Labels: ws-stories

#6834 Dependency updates
  package-lock.json
  package.json
  scripts/bundleSizeConfig.js
  src/app/containers/Byline/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#6844 enabled e2es for live od radio indonesia and pashto
  cypress/support/config/settings.js
Labels: cypress, ws-media-ondemandRadio, ws-media-stream

#6855 Update most read stale data log
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/utilities/processMostRead.js
  src/app/containers/MostRead/utilities/processMostRead.test.js
Labels: most-read, ws-home

#6831 Update most read page heading to be doublePica
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/index.jsx
Labels: most-read, ux, ws-home

#6853 Add videoObject to On Demand TV
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/pages/OnDemandTvPage/VideoPlayer/index.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.jsx
Labels: ws-media-ondemandRadio, ws-media-stream

#6803 E2e frontpage tests run on fewer services
  cypress/integration/pages/frontPage/tests.js
  cypress/support/config/settings.js
Labels: ws-home

#6758 Propogates renderer_env to WS Includes endpoint
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.js
  src/app/routes/cpsAsset/getInitialData/index.js
  src/app/routes/utils/overrideRendererOnTest/index.js
  src/app/routes/utils/overrideRendererOnTest/index.test.js
Labels: includes, stories-STYs, ws-stories

#6857 disabled live e2es od radio indonesia pashto
  cypress/support/config/settings.js
Labels: cypress, ws-media-ondemandRadio, ws-media-stream

#6748 Add CPS page grid
  src/app/components/Grid/__snapshots__/index.test.jsx.snap
  src/app/components/Grid/index.jsx
  src/app/components/Grid/index.stories.jsx
  src/app/components/Grid/index.test.jsx
Labels: ws-media-stream, ws-stories

#6782 Collect ATI and Chartbeat analytics for IDX page
  scripts/bundleSizeConfig.js
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.js
  src/app/containers/ATIAnalytics/params/frontpage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/ATIAnalytics/params/indexPage/buildParams.js
  src/app/containers/ATIAnalytics/params/indexPage/buildParams.test.js
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/lib/analyticsUtils/indexPage/index.js
  src/app/lib/analyticsUtils/indexPage/index.test.js
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/index.jsx
  src/app/pages/IdxPage/index.test.jsx
  src/app/pages/IdxPage/testHelpers/index.jsx
Labels: IDX, ws-home

#6860 Frontpage tests fix
  cypress/integration/pages/frontPage/tests.js
  cypress/support/config/settings.js
Labels: ws-home

#6868 Create Security.md
  SECURITY.md
Labels: Documentation, security

#6282 Integration test improvements
  src/integration/common/SEO.js
  src/integration/common/footer.js
  src/integration/common/header.js
  src/integration/pages/articles/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: ws-media-stream

#6858 Use IndexHeading component on Most Read page
  package-lock.json
  package.json
  src/app/containers/IndexHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexHeading/index.jsx
  src/app/containers/IndexHeading/index.test.jsx
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/index.jsx
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/index.jsx
Labels: most-read, ws-home

#6847 Render "Guide" Story Promos as divs instead of headings
  src/app/containers/StoryPromo/helpers/fixtureData.js
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/index.test.jsx
Labels: ws-home

#6864 Rename FrontPageSection to IndexPageSection
  src/app/containers/IndexPageSection/UsefulLinks/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexPageSection/UsefulLinks/index.jsx
  src/app/containers/IndexPageSection/UsefulLinks/index.test.jsx
  src/app/containers/IndexPageSection/UsefulLinks/usefulItems.js
  src/app/containers/IndexPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexPageSection/index.jsx
  src/app/containers/IndexPageSection/index.stories.jsx
  src/app/containers/IndexPageSection/index.test.jsx
  src/app/containers/IndexPageSection/utilities/filterAllowedItems.jsx
  src/app/containers/IndexPageSection/utilities/filterAllowedItems.test.jsx
  src/app/containers/IndexPageSection/utilities/rowDetails.jsx
  src/app/containers/IndexPageSection/utilities/rowDetails.test.jsx
  src/app/containers/IndexPageSection/utilities/storyRowsSplitter.jsx
  src/app/containers/IndexPageSection/utilities/storyRowsSplitter.test.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/index.jsx
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/index.jsx
Labels: ws-home

#6733 Adding Integration Tests for OD TV
  data/pashto/bbc_pashto_tv/tv/w172xcldhhrhmcf.json
  data/pashto/bbc_pashto_tv/w172xcldhhrdqgb.json
  data/somali/bbc_somali_tv/tv_programmes/w13xttqt.json
  src/integration/pages/onDemandTVPage/ampTests.js
  src/integration/pages/onDemandTVPage/canonicalTests.js
  src/integration/pages/onDemandTVPage/commonEpisodeTests.js
  src/integration/pages/onDemandTVPage/crossPlatformTests.js
  src/integration/pages/onDemandTVPage/expiredEpisodeTests.js
  src/integration/pages/onDemandTVPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto.expired/amp.test.js
  src/integration/pages/onDemandTVPage/pashto.expired/canonical.test.js
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/amp.test.js
  src/integration/pages/onDemandTVPage/pashto/canonical.test.js
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/amp.test.js
  src/integration/pages/onDemandTVPage/somali/canonical.test.js
Labels: ws-media-onDemandTV, ws-media-stream

#6884 On Demand TV - Moving styling and page type values out of videoPlayer
  src/app/pages/OnDemandTvPage/VideoPlayer/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/VideoPlayer/index.jsx
  src/app/pages/OnDemandTvPage/VideoPlayer/index.test.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.jsx
Labels: ws-media-onDemandTV, ws-media-stream

#6905 Fix issue with toggling ads "On"
  src/app/containers/Ad/Canonical/CanonicalAdBootstrapJs.jsx
  src/app/containers/Ad/Canonical/__snapshots__/CanonicalAdBootstrapJs.test.jsx.snap
  src/app/containers/Ad/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.jsx
  src/app/pages/FrontPage/index.jsx
  src/app/pages/FrontPage/index.test.jsx
Labels: ads, bug, ws-home

#6802 IdxPage Integration Tests
  src/integration/pages/idxPage/ampTests.js
  src/integration/pages/idxPage/canonicalTests.js
  src/integration/pages/idxPage/crossPlatformTests.js
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/amp.test.js
  src/integration/pages/idxPage/persian_afghanistan/canonical.test.js
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/amp.test.js
  src/integration/pages/idxPage/ukraine_in_russian/canonical.test.js
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
Labels: IDX, ws-home

#6901 Fix linked data properties for Google SEO
  src/app/containers/LinkedData/__snapshots__/index.test.jsx.snap
  src/app/containers/LinkedData/index.jsx
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
Labels: ws-media-stream

#6890 Remove styling from AudioPlayer component
  src/app/containers/AudioPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/AudioPlayer/index.jsx
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/index.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
Labels: ws-media-ondemandRadio, ws-media-stream

#6908 Update OD TV snapshots
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
Labels: ws-media-onDemandTV, ws-media-stream

#6480 Linkey tests
  .gitignore
  package-lock.json
  package.json
  scripts/linkeySetup.js
  scripts/linkeyTest.js
Labels: ws-home, ws-media-stream, ws-stories

#6912 Remove cypress footer tests covered by integration
  cypress/integration/pages/testsForAllPages.js
Labels: ws-home, ws-media-stream, ws-stories

#6829 Update Canonical Ad placeholder behaviour
  src/app/containers/Ad/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.jsx
Labels: ads, bug, ws-home

#6672 Amp include container for IDT2
  data/gahuza/cpsAssets/23299713.json
  data/mundo/cpsAssets/23263889.json
  src/app/containers/Include/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/amp/Idt2Amp.jsx
  src/app/containers/Include/amp/Idt2Amp.test.jsx
  src/app/containers/Include/amp/__snapshots__/Idt2Amp.test.jsx.snap
  src/app/containers/Include/canonical/index.jsx
  src/app/containers/Include/canonical/index.test.jsx
  src/app/containers/Include/index.jsx
  src/app/containers/Include/index.test.jsx
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/getImageBlock.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/getImageBlock.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
  src/integration/pages/storyPage/ampIncludeTests.js
  src/integration/pages/storyPage/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/gahuza/amp.test.js
Labels: AMP, a11y-swarm, blocking, includes, stories-STYs, ws-stories

#6875 Update Section Label to use correct colour in secondary column
  package-lock.json
  package.json
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: ux, ws-stories

#6907 Add csp urls for ads
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ads, high-priority, ws-home

#6933 Revert "Add csp urls for ads"
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ads, ws-home

#6487 E2E tests for Pre-roll Ads on MAPs
  cypress/integration/specialFeatures/mediaPlayerPreRollAds/index.js
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/toggles/index.js
Labels: ads, ws-media-asset-page-v1, ws-media-stream

#6935 Remove `X` variant CSP headers
  package-lock.json
  src/server/utilities/cspHeader/index.js
Labels: ws-home, ws-media-stream, ws-stories

#6874 OD Radio variant Simorgh routing
  data/zhongwen/bbc_cantonese_radio/w172xf3r5x8hw4v.json
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
Labels: ws-media-ondemandRadio, ws-media-stream

#6927 add lang prop to radio schedule section
  src/app/containers/RadioSchedule/Canonical/index.jsx
  src/app/containers/RadioSchedule/Canonical/index.test.jsx
  src/app/containers/RadioSchedule/index.jsx
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/index.jsx
Labels: IDX, high-priority, ws-home

#6943 remove unstable preroll e2es
  cypress/integration/specialFeatures/mediaPlayerPreRollAds/index.js
Labels: ws-media-stream

#6902 Refactor Front Page integration tests
  src/integration/pages/frontPage/ampTests.js
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/canonicalTests.js
  src/integration/pages/frontPage/crossPlatformTests.js
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
Labels: ws-home

#6903 Fix for single CPS related content sizing
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: stories-STYs, ux, ws-media-stream, ws-stories

#6942 Fix amp csp when renderer_env is specified
  src/app/routes/utils/fetchPageData/utils/getRouteProps/routeFallbackParams/index.js
  src/app/routes/utils/fetchPageData/utils/getRouteProps/routeFallbackParams/index.test.js
Labels: bug, ws-home, ws-media-stream, ws-stories

#6865 Refactor most read page margin layout
  src/app/components/PageLayout/IndexMain.jsx
  src/app/containers/IndexHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexHeading/index.jsx
  src/app/containers/IndexHeading/index.test.jsx
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/label.jsx
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/index.jsx
Labels: most-read, ws-home

#6925 Removed cypress cookie translation tests
  cypress/integration/pages/testsForAllPages.js
Labels: ws-home, ws-media-stream, ws-stories

#6940 Cypress config for On Demand TV
  cypress/support/config/settings.js
Labels: cypress, ws-media-stream

#6924 Override width for STY page primary content grid
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.jsx
Labels: grid, stories-STYs, ws-stories

#6958 Add syndication brand images
  public/afaanoromoo/images/syndication/brand-40xn.png
  public/afrique/images/syndication/brand-40xn.png
  public/amharic/images/syndication/brand-40xn.png
  public/arabic/images/syndication/brand-40xn.png
  public/azeri/images/syndication/brand-40xn.png
  public/bengali/images/syndication/brand-40xn.png
  public/burmese/images/syndication/brand-40xn.png
  public/gahuza/images/syndication/brand-40xn.png
  public/gujarati/images/syndication/brand-40xn.png
  public/hausa/images/syndication/brand-40xn.png
  public/hindi/images/syndication/brand-40xn.png
  public/igbo/images/syndication/brand-40xn.png
  public/indonesia/images/syndication/brand-40xn.png
  public/korean/images/syndication/brand-40xn.png
  public/kyrgyz/images/syndication/brand-40xn.png
  public/marathi/images/syndication/brand-40xn.png
  public/mundo/images/syndication/brand-40xn.png
  public/nepali/images/syndication/brand-40xn.png
  public/pashto/images/syndication/brand-40xn.png
  public/persian/images/syndication/brand-40xn.png
  public/pidgin/images/syndication/brand-40xn.png
  public/portuguese/images/syndication/brand-40xn.png
  public/punjabi/images/syndication/brand-40xn.png
  public/russian/images/syndication/brand-40xn.png
  public/serbian/images/syndication/brand-40xn.png
  public/sinhala/images/syndication/brand-40xn.png
  public/somali/images/syndication/brand-40xn.png
  public/swahili/images/syndication/brand-40xn.png
  public/tamil/images/syndication/brand-40xn.png
  public/telugu/images/syndication/brand-40xn.png
  public/thai/images/syndication/brand-40xn.png
  public/tigrinya/images/syndication/brand-40xn.png
  public/turkce/images/syndication/brand-40xn.png
  public/ukrainian/images/syndication/brand-40xn.png
  public/urdu/images/syndication/brand-40xn.png
  public/uzbek/images/syndication/brand-40xn.png
  public/vietnamese/images/syndication/brand-40xn.png
  public/yoruba/images/syndication/brand-40xn.png
  public/zhongwen/images/syndication/brand-40xn.png
Labels: ws-stories

#6941 Update radio schedule unit tests
  src/app/containers/RadioSchedule/Canonical/index.test.jsx
Labels: radio-schedules, tech-debt, ws-home

#6872 Fix tests and stories for IDX page
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/index.test.jsx
  src/app/pages/IdxPage/testHelpers/index.jsx
Labels: IDX, ws-home

#6952 Update ATI thinglabels (x13) to use new Ares field
  data/gahuza/cpsAssets/amakuru-43894701.json
  data/persian/articles/c4vlle3q337o.json
  data/pidgin/cpsAssets/tori-49450859.json
  src/app/containers/ATIAnalytics/params/article/buildParams.js
  src/app/containers/ATIAnalytics/params/article/buildParams.test.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/lib/utilities/parseAssetData/index.test.js
  src/app/pages/ArticlePage/fixtureData.js
  src/app/pages/PhotoGalleryPage/fixtureData.json
  src/app/pages/StoryPage/fixtureData/mundo.json
Labels: analytics, ws-media-stream, ws-stories

#6963 Reduce On Demand TV Media Summary to span 5 columns
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.jsx
  src/integration/pages/storyPage/gahuza/__snapshots__/amp.test.js.snap
Labels: bug, ws-media-onDemandTV, ws-media-stream

#6969 Add Space between Title and Date when CSS Disabled
  src/app/containers/RadioPageBlocks/Blocks/OnDemandHeading/index.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
Labels: ws-media-stream

#6873 Update pre-processor logic for VJ Amp includes
  scripts/bundleSizeConfig.js
  src/app/lib/logger.const.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/ampSrcBuilder.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/ampSrcBuilder.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/includeClassifier.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/includeClassifier.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.test.js
  src/integration/pages/articles/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: includes, ws-stories

#6915 Update toggle service endpoints
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Amp/index.test.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.test.jsx
  src/app/contexts/ToggleContext/index.test.jsx
  src/app/contexts/ToggleContext/utils/constructTogglesEndpoint/index.js
  src/app/contexts/ToggleContext/utils/constructTogglesEndpoint/index.test.js
  src/app/hooks/useToggle/index.test.jsx
  src/app/hooks/useToggle/useToggle.test.jsx
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ads, ws-home

#6977 Update OD TV grid items to remove margin for larger screens
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.jsx
Labels: ws-media-stream

#6986 Enabled Arabic and Hindi MAP E2Es on test
  cypress/support/config/settings.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#6974 Replaced deprecated toBeEmpty with toBeEmptyDOMElement
  src/app/containers/RadioSchedule/Canonical/index.test.jsx
Labels: tech-debt, ws-home, ws-media-stream, ws-stories

#6987 Clear up ws_cleanup Jenkins workspace directories
  Jenkinsfile
Labels: ws-home, ws-media-stream, ws-stories

#6975 Check service ads
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/zhongwen.js
Labels: ads, ws-home

#6913 Add clustering support to start one instance of simorgh application
  src/app/lib/logger.const.js
  src/index.js
  src/startServer.js
  src/startServer.test.js
Labels: infra-tooling-stream

#6973 Move VideoPlayer out of OD TV, Rename 'AVPlayer'
  src/app/containers/AVPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/AVPlayer/index.jsx
  src/app/containers/AVPlayer/index.test.jsx
  src/app/pages/OnDemandTvPage/index.jsx
Labels: ws-media-stream

#6966 add urls to csp header for ads
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ads, high-priority, ws-home

#6938 Enable cypress tests to run on the live persian/afghanistan page
  cypress/support/config/settings.js
Labels: IDX, ws-home

#6972 Render fallback for Canonical IDT2 Includes containing disallowed scripts
  data/gahuza/cpsAssets/23313911.json
  scripts/bundleSizeConfig.js
  src/app/containers/Include/canonical/Idt2/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/canonical/Idt2/index.jsx
  src/app/containers/Include/canonical/Idt2/index.test.jsx
  src/app/containers/Include/canonical/index.jsx
  src/app/containers/Include/index.jsx
  src/app/containers/Include/index.test.jsx
  src/integration/integrationTestEnvironment.js
  src/integration/pages/storyPage/ampIncludeTests.js
  src/integration/pages/storyPage/canonicalIncludeTests.js
  src/integration/pages/storyPage/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/gahuza/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/gahuza/amp.test.js
  src/integration/pages/storyPage/gahuza/canonical.test.js
  src/integration/utils/fetchDom.js
Labels: includes, stories-STYs, ws-stories

#6991 Added URLs and enabled for Hindi Arabic Ukchina Serbian Zhongwen
  cypress/support/config/settings.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#6984 Resolve spacing between Top Stories headline and promo items
  package-lock.json
  package.json
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
Labels: ux, ws-stories

#6931 Amp Ad refactor and MPU
  src/app/containers/Ad/Amp/AdSlot.jsx
  src/app/containers/Ad/Amp/AdSlot.test.jsx
  src/app/containers/Ad/Amp/__snapshots__/AdSlot.test.jsx.snap
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Amp/index.test.jsx
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/Canonical/index.test.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/index.jsx
Labels: ads, ws-home

#6970 Shared episode availability logic & logging for OD radio & OD TV
  .env
  data/pashto/bbc_pashto_radio/w172xjclrg44dgj.json
  src/app/lib/logger.const.js
  src/app/lib/utilities/episodeAvailability/index.js
  src/app/lib/utilities/episodeAvailability/index.test.js
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/pages/OnDemandRadioPage/index.test.jsx
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/onDemandRadio/getInitialData/index.test.js
  src/app/routes/onDemandRadio/getInitialData/logInitialData/index.js
  src/app/routes/onDemandRadio/getInitialData/logInitialData/index.test.js
Labels: ws-media-stream

#6968 Add suffix flag
  src/app/containers/ArticleTimestamp/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleTimestamp/index.jsx
  src/app/containers/ArticleTimestamp/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: stories-STYs, ws-stories

#7011 Fix typo preventing Canonical IDT2 horizontal charts from rendering as a fallback
  src/app/containers/Include/canonical/Idt2/index.jsx
Labels: bug, high-priority, includes, ws-stories

#6937 Update Audio Player to not contain page type logic
  data/afaanoromoo/bbc_afaanoromoo_radio/w13xttnw.json
  src/app/containers/AudioPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/AudioPlayer/index.jsx
  src/app/containers/AudioPlayer/index.test.jsx
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/index.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/pages/OnDemandRadioPage/index.test.jsx
Labels: tech-debt, ws-media-stream

#7012 Cypress tests altered for Russian redirect
  cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  cypress/integration/pages/testsForAllPages.js
  cypress/support/config/settings.js
Labels: cypress, ws-media-asset-page-v1, ws-media-stream

#7017 Update Psammead Media Version
  package-lock.json
  package.json
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
Labels: ws-media-stream

#6976 Add On Demand TV To Amp Validation Tests
  scripts/ampHtmlValidator/index.js
  scripts/ampHtmlValidator/index.test.js
Labels: ws-media-stream

#7030 Naming changes for TV/Radio Media Player Refactor
  src/app/containers/AVPlayer/index.jsx
  src/app/containers/AVPlayer/index.test.jsx
  src/app/containers/AudioPlayer/index.jsx
  src/app/pages/LiveRadioPage/index.jsx
  src/app/pages/OnDemandRadioPage/index.jsx
  src/app/pages/OnDemandTvPage/index.jsx
Labels: ws-media-stream

#7031 Adding default skin prop to AVPlayer
  src/app/containers/AVPlayer/index.jsx
Labels: ws-media-stream

#7028 Update OD TV Tests
  src/app/containers/AVPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/AVPlayer/index.test.jsx
Labels: ws-media-stream

#7013 Update data-slot for AMP Ads
  src/app/containers/Ad/Amp/AdSlot.jsx
  src/app/containers/Ad/Amp/AdSlot.test.jsx
  src/app/containers/Ad/Amp/__snapshots__/AdSlot.test.jsx.snap
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
Labels: ads, ws-home

#6856 remove cypress tests that are covered by integration tests: seo & metadata
  cypress/integration/pages/testsForAllPages.js
  src/integration/common/SEO.js
  src/integration/pages/articles/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: ws-home, ws-media-stream, ws-stories

#6916 make nav text and url snapshots easier to read
  src/integration/common/footer.js
  src/integration/common/header.js
  src/integration/pages/articles/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/amharic/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: tech-debt, ws-media-stream

#7035 update adUnit on test for AMP
  src/app/containers/Ad/Amp/AdSlot.jsx
  src/app/containers/Ad/Amp/AdSlot.test.jsx
  src/app/containers/Ad/Amp/__snapshots__/AdSlot.test.jsx.snap
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
Labels: ads, ws-home

#7014 Fix most read page white space at bottom bug
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/index.jsx
Labels: bug, most-read, ws-home

#6423 add sameSite and secure attribute to cookies
  src/app/containers/ConsentBanner/CanonicalLogic/index.js
  src/app/contexts/UserContext/cookies/index.js
  src/app/contexts/UserContext/cookies/index.test.js
  src/app/lib/utilities/setCookie/index.jsx
  src/app/lib/utilities/setCookie/index.test.jsx
Labels: high-priority, ws-home, ws-media-stream, ws-stories

#7057 Enable Hausa test URLs for E2Es
  cypress/support/config/settings.js
Labels: cypress, ws-media-ondemandRadio, ws-media-stream

#7054 Update AvPlayer tests to include OD Radio
  src/app/containers/AVPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/AVPlayer/index.test.jsx
Labels: ws-media-stream

#7063 Add Top Stories translation for Ukrainian
  src/app/lib/config/services/ukrainian.js
Labels: stories-STYs, ws-home, ws-stories

#7052 Reduce margin for OD TV mobile
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.jsx
Labels: ws-media-stream

#7065 Revert "add sameSite and secure attribute to cookies"
  src/app/containers/ConsentBanner/CanonicalLogic/index.js
  src/app/contexts/UserContext/cookies/index.js
  src/app/contexts/UserContext/cookies/index.test.js
  src/app/lib/utilities/setCookie/index.jsx
  src/app/lib/utilities/setCookie/index.test.jsx
Labels: ws-home

#7070 Live E2Es for Indonesia, Pashto and Hausa OD Radio enabled
  cypress/support/config/settings.js
Labels: cypress, ws-media-ondemandRadio, ws-media-stream

#6904 Add ukraine_in_russian service config
  cypress/integration/specialFeatures/scriptSwitching/index.js
  cypress/support/config/settings.js
  scripts/bundleSizeConfig.js
  src/app/containers/ArticleTimestamp/timeFormatTests/expectedFormats.json
  src/app/containers/Footer/index.jsx
  src/app/containers/Footer/index.test.jsx
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/index.jsx
  src/app/containers/Header/index.test.jsx
  src/app/containers/PageHandlers/withContexts.jsx
  src/app/contexts/ServiceContext/index.jsx
  src/app/contexts/ServiceContext/index.test.jsx
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/utilities/langHandler/index.js
  src/app/lib/utilities/langHandler/index.test.js
  src/app/models/propTypes/variants/index.js
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/index.jsx
  src/app/pages/IdxPage/index.test.jsx
  src/app/pages/IdxPage/testHelpers/index.jsx
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
Labels: IDX, high-priority, ws-home
