Repository bbc/simorgh, pull requests merged in 2021-08, with the labels that each got.

#9283 Support bulleted lists on optimo articles
  data/arabic/articles/cm41q1925n0o.json
  data/pidgin/articles/c61mlel0zm4o.json
  src/app/containers/Text/__snapshots__/index.test.jsx.snap
  src/app/containers/Text/index.jsx
  src/app/containers/Text/index.test.jsx
Labels: cross-team

#9281 Create Gist Component
  package.json
  src/app/containers/BulletedList/index.jsx
  src/app/containers/CpsText/index.jsx
  src/app/containers/Gist/__snapshots__/index.test.jsx.snap
  src/app/containers/Gist/fixtures.js
  src/app/containers/Gist/index.jsx
  src/app/containers/Gist/index.stories.jsx
  src/app/containers/Gist/index.test.jsx
  src/app/pages/ArticlePage/ArticlePage.jsx
  yarn.lock
Labels: optimo

#9262 Update social embeds to not include index in skip link when only one exists
  src/app/containers/SocialEmbed/Cps/index.jsx
  src/app/containers/SocialEmbed/common/translations.js
  src/app/containers/SocialEmbed/index.jsx
  src/app/containers/SocialEmbed/index.test.jsx
  src/app/routes/utils/sharedDataTransformers/addIndexesToEmbeds/index.js
  src/app/routes/utils/sharedDataTransformers/addIndexesToEmbeds/index.test.js
Labels: bug, cross-team

#9255 Webpack v5
  .storybook/main.js
  package.json
  puppeteer/bundleRequests.test.js
  scripts/bundleSize/bundleSizeConfig.js
  scripts/bundleSize/getBundleData.js
  scripts/bundleSize/pageTypeBundleExtractor.js
  scripts/bundleSize/pageTypeBundleExtractor.test.js
  src/integration/common/core.canonical.js
  webpack.config.client.js
  webpack.config.js
  webpack.config.server.js
  yarn.lock
Labels: cross-team, technical-work

#9302 Adds translations for gist component in service config
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/newsround.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/sport.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: cross-team, optimo

#9296 Dependency upgrades
  package.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Brand/__snapshots__/index.test.jsx.snap
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  yarn.lock
Labels: technical-work

#9304 Hide most read when none exist
  data/arabic/articles/cl5m3453w36o.json
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/Canonical/index.test.jsx
  src/app/pages/ArticlePage/index.test.jsx
Labels: cross-team

#9294 Update Chromatic parameters to not enable Media Player in AMP
  src/app/components/MediaPlayer/index.stories.jsx
  src/app/containers/MediaPlayer/index.stories.jsx
Labels: cross-team

#9316 Make lazy load Instagram embed test less unreliable
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
Labels: cross-team

#9324 Fixes lack of gap between skip to content link and header CSS
  data/pidgin/cpsAssets/58228654.json
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/index.jsx
Labels: a11y, cross-team
