Repository bbc/simorgh, pull requests merged in 2021-02, with the labels that each got.

#8819 Make use of latest Podcast Promo version (fixing image resizing bug)
  package-lock.json
  package.json
  src/app/containers/PodcastPromo/__snapshots__/index.test.jsx.snap
Labels: ws-media

#8817 Add functionality to not install the SW
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/containers/ServiceWorker/index.jsx
  src/app/containers/ServiceWorker/index.test.jsx
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/news.js
Labels: ws-articles

#8814 Update service config with consent banner translations
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/newsround.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/sport.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-articles

#8830 pin immer again
  package-lock.json
Labels: cross-team

#8808 Exclude major bumps for BBC psammead packages
  renovate.json
  renovate.md
Labels: cross-team

#8824 add 'podcasts' to page identifier for ATI
  src/app/routes/podcast/getInitialData/index.js
  src/app/routes/podcast/getInitialData/index.test.js
Labels: ws-media

#8831 cache node_modules in github actions
  .github/workflows/simorgh-deploy-storybook.yml
  .github/workflows/simorgh-integration-tests.yml
  .github/workflows/simorgh-local-server-tests.yml
  .github/workflows/simorgh-misc-checks.yml
  .github/workflows/simorgh-unit-tests.yml
Labels: cross-team

#8843 Disable tests for Scotland on test env
  cypress/support/config/settings.js
Labels: ws-articles

#8797 Refactor getInitialData on OD Radio and Podcast pages to reduce repetition
  src/app/pages/OnDemandAudioPage/index.test.jsx
  src/app/routes/onDemandAudio/getInitialData/index.js
  src/app/routes/onDemandAudio/getInitialData/index.test.js
  src/app/routes/onDemandRadio/getInitialData/index.js
  src/app/routes/onDemandRadio/index.js
  src/app/routes/podcast/getInitialData/index.test.js
  src/app/routes/podcast/index.js
Labels: ws-media

#8825 Changes to make tests shared between OD Radio and podcasts work. Renamed 'radio' to 'audio' where shared
  a11y.js
  cypress/integration/pages/onDemandAudio/index.js
  cypress/integration/pages/onDemandAudio/tests.js
  cypress/integration/pages/onDemandAudio/testsForAMPOnly.js
  cypress/integration/pages/onDemandAudio/testsForCanonicalOnly.js
  cypress/integration/pages/onDemandRadio/testsForCanonicalOnly.js
  cypress/support/config/settings.js
  scripts/ampHtmlValidator/index.js
Labels: OD-radio, cypress, podcasts, ws-media

#8860 Update wording for GPG recommendation
  CONTRIBUTING.md
Labels: cross-team

#8867 Remove Sinhala OD-radio and live radio tests from cypress settings
  cypress/support/config/settings.js
Labels: ws-media

#8868 Update cps asset regex
  data/cymrufyw/cpsAssets/etholiad-2017-39407507.json
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
Labels: ws-articles

#8827 Canonical Consent Banner
  package-lock.json
  package.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/Text.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
Labels: a11y-swarm, ux, ws-articles

#8847 Omit related content section where items not supported
  data/sport/cpsAssets/football/55790817.json
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/routes/cpsAsset/getInitialData/cpsOnlyOnwardJourneys/fixtures/sport.json
  src/app/routes/cpsAsset/getInitialData/cpsOnlyOnwardJourneys/index.js
  src/app/routes/cpsAsset/getInitialData/cpsOnlyOnwardJourneys/index.test.js
Labels: cross-team

#8870 Amp Consent Translation Fixes
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/yoruba.js
Labels: ws-articles

#8835 Image placeholder canonical transparency fix
  data/news/cpsAssets/uk-55808266.json
  src/app/containers/ImageWithPlaceholder/index.jsx
Labels: cross-team

#8845 Create A11y-Testing-Cross-Device.md
  docs/A11y-Testing-Cross-Device.md
Labels: Documentation, a11y, cross-team

#8833 replace npm scripts commands with yarn
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/simorgh-e2e-tests.yml
  .github/workflows/simorgh-misc-checks.yml
  AdHocCypress/README.md
  CONTRIBUTING.md
  README.md
  cypress/integration/README.md
  docs/JavaScript-Bundling-Strategy.md
  docs/Rendering-Ads.md
  package.json
  src/integration/README.md
  src/integration/utils/runTests/index.js
  src/server/utilities/cspHeader/index.js
  webpack.config.server.js
Labels: cross-team

#8846 Update "Most Watched" label for BBCTurkce
  src/app/lib/config/services/turkce.js
Labels: cross-team

#8832 Include episode title on radio and podcast pages
  data/arabic/podcasts/p02pc9qc/p08wtg4d.json
  data/pashto/bbc_pashto_radio/w3ct0lz1.json
  src/app/containers/OnDemandFooterTimestamp/index.jsx
  src/app/containers/OnDemandFooterTimestamp/index.test.jsx
  src/app/containers/OnDemandHeading/StyledRadioHeadingContainer.jsx
  src/app/containers/OnDemandHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/OnDemandHeading/index.jsx
  src/app/containers/OnDemandParagraph/__snapshots__/index.test.jsx.snap
  src/app/containers/OnDemandParagraph/index.jsx
  src/app/containers/OnDemandTvFooterTimestamp/index.jsx
  src/app/pages/OnDemandAudioPage/OnDemandAudioPage.jsx
  src/app/pages/OnDemandAudioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandAudioPage/index.test.jsx
  src/app/pages/OnDemandTvPage/OnDemandTvPage.jsx
  src/app/routes/onDemandAudio/getInitialData/index.js
  src/app/routes/onDemandAudio/getInitialData/index.test.js
Labels: ws-media

#8834 Show Image from 360px and up on OD Radio Pages
  cypress/integration/pages/onDemandAudio/tests.js
  src/app/containers/OnDemandImage/__snapshots__/index.test.jsx.snap
  src/app/containers/OnDemandImage/index.jsx
  src/app/pages/OnDemandAudioPage/OnDemandAudioPage.jsx
  src/app/pages/OnDemandAudioPage/__snapshots__/index.test.jsx.snap
Labels: ws-media

#8888 Revert debugging
  package-lock.json
  package.json
  scripts/bundleSize/bundleSizeConfig.js
  src/client.js
  webpack.config.client.js
  webpack.config.js
Labels: cross-team, high-priority

#8871 Podcast URLs in E2E config , and fixture data - test and local
  cypress/support/config/settings.js
  data/burmese/podcasts/p02pc9lh.json
  data/burmese/podcasts/p02pc9lh/p0967thw.json
  data/gahuza/podcasts/p07yh8hb.json
  data/gahuza/podcasts/p07yh8hb/p094vs2n.json
  data/hausa/podcasts/p08mlgcb.json
  data/hausa/podcasts/p08mlgcb/p095k3hd.json
  data/hindi/podcasts/p0552909.json
  data/hindi/podcasts/p0552909/p0964mwl.json
  data/indonesia/podcasts/p02pc9v6.json
  data/indonesia/podcasts/p02pc9v6/p096mj9z.json
  data/nepali/podcasts/p02pc9w3.json
  data/nepali/podcasts/p02pc9w3/p086v2bv.json
  data/persian/podcasts/p02pc9wf.json
  data/persian/podcasts/p02pc9wf/p095lyj1.json
  data/russian/podcasts/p05607v8.json
  data/russian/podcasts/p05607v8/p06xlzvx.json
  data/zhongwen/podcasts/p02pc9xp.json
  data/zhongwen/podcasts/p02pc9xp/p0968qrl.json
Labels: ws-media

#8762 Migrate to yarn for installing dependencies
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/simorgh-deploy-storybook.yml
  .github/workflows/simorgh-e2e-tests.yml
  .github/workflows/simorgh-integration-tests.yml
  .github/workflows/simorgh-local-server-tests.yml
  .github/workflows/simorgh-misc-checks.yml
  .github/workflows/simorgh-unit-tests.yml
  .npmrc
  .yarnrc
  AdHocCypress/README.md
  CONTRIBUTING.md
  README.md
  RENOVATE.md
  codebuild/e2e_buildspec.yml
  cypress/integration/README.md
  docs/JavaScript-Bundling-Strategy.md
  docs/Rendering-Ads.md
  package-lock.json
  package.json
  scripts/check-package-manager.js
  scripts/dependencyUpdateCheck.sh
  scripts/enforceVersions.sh
  scripts/packagelockHttps.sh
  src/integration/README.md
  src/integration/utils/runTests/index.js
  src/server/utilities/cspHeader/index.js
  webpack.config.js
  webpack.config.server.js
  yarn.lock
Labels: cross-team, ws-media

#8894 OD Audio - Provide OpenGraph Image
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/pages/OnDemandAudioPage/OnDemandAudioPage.jsx
  src/integration/pages/onDemandAudioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
Labels: ws-media

#8880 Add missing translation for marathi
  src/app/lib/config/services/marathi.js
Labels: ws-media

#8908 Allow list electron vulnerability
  audit-ci.json
Labels: high-priority, security

#8905 Set custom user-agent when fetching data
  src/app/routes/utils/fetchPageData/index.js
  src/app/routes/utils/fetchPageData/index.test.js
Labels: cross-team

#8876 Amp consent int test
  cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
  cypress/integration/specialFeatures/cookieBanner/testsForCanonicalOnly.js
  cypress/integration/specialFeatures/scriptSwitching/testsForCanonicalOnly.js
  cypress/integration/specialFeatures/utilities/cookiePrivacyBanner/index.js
  cypress/support/config/settings.js
  src/app/lib/config/services/persian.js
Labels: ws-articles

#8912 Radio schedule ordering
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.js
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.test.js
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
Labels: ws-media

#8893 Added live urls for podcasts release 1
  cypress/support/config/settings.js
Labels: cypress, podcasts, ws-media

#8913 Adding translation for 'Listen live'
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
Labels: ws-media

#8874 Update Simorgh to use a11y-compliant episode list border styling
  data/afrique/bbc_afrique_tv/tv/w3ct05n6.json
  package.json
  src/app/containers/RecentAudioEpisodes/index.jsx
  src/app/containers/RecentVideoEpisodes/index.jsx
  yarn.lock
Labels: Recent Episodes Radio, Recent Episodes TV, ws-media

#8902 Added 3x retry to flakey recent episodes audio pages test
  cypress/integration/pages/onDemandAudio/tests.js
Labels: OD-radio, Recent Episodes Radio, cypress, podcasts, ws-media

#8907 Somali navigation update
  src/app/lib/config/services/somali.js
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
Labels: cross-team
