Repository bbc/simorgh, pull requests merged in 2021-04, with the labels that each got.

#9024 Update Mundo, Persian and Thai navs to remove us elections, add coronavirus
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/thai.js
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team

#9025 Add google safeframe to connectSrc in csp
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: ws-articles

#9027 force resolve color-string 1.5.5 to patch security vuln
  package.json
  yarn.lock
Labels: cross-team

#9010 Use amp-geo to correctly determine a user's location
  package.json
  src/app/components/AmpGeo/__snapshots__/index.test.jsx.snap
  src/app/components/AmpGeo/index.jsx
  src/app/components/AmpGeo/index.test.jsx
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ConsentBanner/index.amp.jsx
  src/app/lib/analyticsUtils/getAmpDestination/index.js
  src/app/lib/analyticsUtils/getAmpDestination/index.test.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
  src/integration/pages/articles/news/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/gahuza.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/server/Document/component.jsx
  yarn.lock
Labels: AMP, bug, cross-team, high-priority, ws-articles

#9014 Move Psammead Media Components into Simorgh
  docs/Media-Player-Guide.md
  package.json
  src/app/components/MediaPlayer/Amp/__snapshots__/index.test.jsx.snap
  src/app/components/MediaPlayer/Amp/index.jsx
  src/app/components/MediaPlayer/Amp/index.test.jsx
  src/app/components/MediaPlayer/Canonical/__snapshots__/index.test.jsx.snap
  src/app/components/MediaPlayer/Canonical/index.jsx
  src/app/components/MediaPlayer/Canonical/index.test.jsx
  src/app/components/MediaPlayer/Guidance/__snapshots__/index.test.jsx.snap
  src/app/components/MediaPlayer/Guidance/index.jsx
  src/app/components/MediaPlayer/Guidance/index.test.jsx
  src/app/components/MediaPlayer/Message/__snapshots__/index.test.jsx.snap
  src/app/components/MediaPlayer/Message/index.jsx
  src/app/components/MediaPlayer/Message/index.test.jsx
  src/app/components/MediaPlayer/Placeholder/__snapshots__/index.test.jsx.snap
  src/app/components/MediaPlayer/Placeholder/index.jsx
  src/app/components/MediaPlayer/Placeholder/index.test.jsx
  src/app/components/MediaPlayer/README.md
  src/app/components/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/components/MediaPlayer/index.jsx
  src/app/components/MediaPlayer/index.stories.jsx
  src/app/components/MediaPlayer/index.test.jsx
  src/app/containers/AVPlayer/index.jsx
  src/app/containers/MediaPlayer/index.jsx
  src/app/lib/utilities/episodeAvailability/ErrorMessage/index.jsx
  src/app/pages/MediaAssetPage/MediaMessage/index.jsx
  yarn.lock
Labels: ws-media

#9003 Reduce the amount of URLs Amp consent banner E2Es run on
  cypress/support/config/settings.js
Labels: amp consent, cross-team, cypress

#9038 Use cy.intercept to change fundingchoices_cmp to false and prevent CMP appearing
  cypress/fixtures/flagpoles/ngas.json
  cypress/support/helpers/visitPage.js
Labels: cross-team, cypress

#9042 Correct ATI url on .com AMP pages
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
Labels: AMP, cross-team, high-priority

#9049 Update third party links for Podcast pages
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/arabic.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/hindi.js
Labels: ws-media

#9029 Removes Large Page Snapshot Tests
  src/app/pages/FeatureIdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FeatureIdxPage/index.test.jsx
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/index.test.jsx
Labels: cross-team, ws-articles

#9050 [DNM] add keepalive timeout
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/startServer.js
Labels: cross-team

#9036 Audio placeholder
  src/app/components/MediaPlayer/AudioLoader/__snapshots__/index.test.jsx.snap
  src/app/components/MediaPlayer/AudioLoader/index.jsx
  src/app/components/MediaPlayer/AudioLoader/index.test.jsx
  src/app/components/MediaPlayer/Canonical/index.jsx
  src/app/components/MediaPlayer/index.jsx
  src/app/containers/AVPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/AVPlayer/index.jsx
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandAudioPage/__snapshots__/index.test.jsx.snap
Labels: ws-media

#9062 AMP Image Placeholder Transparency Fix
  src/app/containers/ImageWithPlaceholder/fixtureData.jsx
  src/app/containers/ImageWithPlaceholder/index.jsx
  src/app/containers/ImageWithPlaceholder/index.test.jsx
  src/app/pages/OnDemandAudioPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
Labels: bug, cross-team

#9077 Fix amp validator
  scripts/ampHtmlValidator/index.js
Labels: AMP, cross-team
