Repository bbc/simorgh, pull requests merged in 2021-11, with the labels that each got.

#9615 Skip Podcast Promo test until ready
  cypress/integration/pages/storyPage/tests.js
Labels: cypress, cross-team

#9620 Update Ukrainian and Thai navs
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/ukrainian.js
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
Labels: cross-team

#9594 Fixes RadioSchedule component issue with commas being read out on screen readers
  data/persian/bbc_persian_radio/p0340vyx.json
  src/app/components/RadioSchedule/ProgramCard/__snapshots__/index.test.jsx.snap
  src/app/components/RadioSchedule/ScheduleItemHeader/index.jsx
  src/app/components/RadioSchedule/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
Labels: bug, a11y, cross-team

#9342 upgrade js-cookie to v3
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
Labels: cross-team

#9582 fix [Media Performance] Embed URLs incur unnecessary redirect
  cypress/support/config/envs.js
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/lib/utilities/getUrlHelpers/getEmbedUrl/index.js
  src/app/lib/utilities/getUrlHelpers/getEmbedUrl/index.test.js
  src/app/lib/utilities/getUrlHelpers/getMostWatchedUrl/index.js
  src/app/lib/utilities/getUrlHelpers/getMostWatchedUrl/index.test.js
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/index.test.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandAudioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandAudioPage/index.test.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/articles/scotland/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
Labels: bug, performance

#9542 AMP Optimizer Integration SSR
  .yarn/cache/@ampproject-toolbox-core-npm-2.8.0-e89d25e09d-a8054cc8bf.zip
  .yarn/cache/@ampproject-toolbox-optimizer-npm-2.8.3-9029ca31b0-51b6a6d778.zip
  .yarn/cache/@ampproject-toolbox-runtime-version-npm-2.8.0-fe86b927d4-ff2088c18f.zip
  .yarn/cache/@ampproject-toolbox-script-csp-npm-2.8.0-08f9a6ed12-61574e37e2.zip
  .yarn/cache/@ampproject-toolbox-validator-rules-npm-2.8.0-54390c15b5-f26277f3d8.zip
  .yarn/cache/abort-controller-npm-3.0.0-2f3a9a2bcb-170bdba9b4.zip
  .yarn/cache/caniuse-lite-npm-1.0.30001272-e89c95f6f8-5a08fc35ae.zip
  .yarn/cache/cross-fetch-npm-3.1.2-e4f5b4e92e-7625e8c236.zip
  .yarn/cache/cssnano-preset-simple-npm-2.0.0-c13de3f8d0-57cdca9d96.zip
  .yarn/cache/cssnano-simple-npm-2.0.0-fada602158-9efc3ab4c3.zip
  .yarn/cache/dom-serializer-npm-1.2.0-b95c2521b9-231212b309.zip
  .yarn/cache/domhandler-npm-4.0.0-dbb18bd84d-810f3e575e.zip
  .yarn/cache/domutils-npm-2.5.0-a9dde00331-9198c1d2b1.zip
  .yarn/cache/event-target-shim-npm-5.0.1-cb48709025-1ffe3bb22a.zip
  .yarn/cache/htmlparser2-npm-6.0.1-c42fd7e87d-2e270122d1.zip
  .yarn/cache/nanoid-npm-3.1.30-58cf6fe7ec-276d0d4b0c.zip
  .yarn/cache/normalize-html-whitespace-npm-1.0.0-6c5b20a97a-84d1ac7990.zip
  .yarn/cache/postcss-npm-8.2.13-9a7a8d26c4-1f4a4d85c2.zip
  .yarn/cache/postcss-npm-8.3.11-ded5d923bd-1a230553d7.zip
  .yarn/cache/postcss-safe-parser-npm-5.0.2-0d30a118ed-b786eca091.zip
  .yarn/cache/terser-npm-5.5.1-6fc0e0b56a-82c1bbb917.zip
  data/persian/articles/cej3lzd5e0go.json
  package.json
  src/integration/pages/articles/news/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/server/index.jsx
  src/server/index.test.jsx
  yarn.lock
Labels: cross-team

#9622 Disables color-contrast rule in axe a11y
  cypress/support/helpers/checkA11y.js
Labels: a11y, cypress, cross-team

#9638 remove swagger-cli package and schema validation script
  data/schema.yaml
  package.json
Labels: dependencies, cross-team

#9639 Removes unused swagger-cli dependancy
  .yarn/cache/@apidevtools-json-schema-ref-parser-npm-9.0.9-cda77aa4ae-b21f6bdd37.zip
  .yarn/cache/@apidevtools-openapi-schemas-npm-2.1.0-5401d2b368-4a8f64935b.zip
  .yarn/cache/@apidevtools-swagger-cli-npm-4.0.4-25d5c443ec-653730283c.zip
  .yarn/cache/@apidevtools-swagger-methods-npm-3.0.2-2f505abefb-d06b1ac5c1.zip
  .yarn/cache/@apidevtools-swagger-parser-npm-10.0.3-9e554f93c2-580a86d4c2.zip
  .yarn/cache/@jsdevtools-ono-npm-7.1.3-cb2313543b-2297fcd472.zip
  .yarn/cache/lodash.get-npm-4.4.2-7bda64ed87-e403047ddb.zip
  .yarn/cache/swagger-cli-npm-4.0.4-8108218d0e-6e98774cd1.zip
  .yarn/cache/validator-npm-13.6.0-2ca88b50f3-1f9f813228.zip
  .yarn/cache/z-schema-npm-5.0.1-845f9fd977-9e825d3c42.zip
  package.json
  yarn.lock
Labels: cross-team

#9633 Revert "Revert "AMP Optimizer Integration SSR""
  .yarn/cache/@ampproject-toolbox-core-npm-2.8.0-e89d25e09d-a8054cc8bf.zip
  .yarn/cache/@ampproject-toolbox-optimizer-npm-2.8.3-9029ca31b0-51b6a6d778.zip
  .yarn/cache/@ampproject-toolbox-runtime-version-npm-2.8.0-fe86b927d4-ff2088c18f.zip
  .yarn/cache/@ampproject-toolbox-script-csp-npm-2.8.0-08f9a6ed12-61574e37e2.zip
  .yarn/cache/@ampproject-toolbox-validator-rules-npm-2.8.0-54390c15b5-f26277f3d8.zip
  .yarn/cache/abort-controller-npm-3.0.0-2f3a9a2bcb-170bdba9b4.zip
  .yarn/cache/caniuse-lite-npm-1.0.30001272-e89c95f6f8-5a08fc35ae.zip
  .yarn/cache/cross-fetch-npm-3.1.2-e4f5b4e92e-7625e8c236.zip
  .yarn/cache/cssnano-preset-simple-npm-2.0.0-c13de3f8d0-57cdca9d96.zip
  .yarn/cache/cssnano-simple-npm-2.0.0-fada602158-9efc3ab4c3.zip
  .yarn/cache/dom-serializer-npm-1.2.0-b95c2521b9-231212b309.zip
  .yarn/cache/domhandler-npm-4.0.0-dbb18bd84d-810f3e575e.zip
  .yarn/cache/domutils-npm-2.5.0-a9dde00331-9198c1d2b1.zip
  .yarn/cache/event-target-shim-npm-5.0.1-cb48709025-1ffe3bb22a.zip
  .yarn/cache/htmlparser2-npm-6.0.1-c42fd7e87d-2e270122d1.zip
  .yarn/cache/nanoid-npm-3.1.30-58cf6fe7ec-276d0d4b0c.zip
  .yarn/cache/normalize-html-whitespace-npm-1.0.0-6c5b20a97a-84d1ac7990.zip
  .yarn/cache/postcss-npm-8.2.13-9a7a8d26c4-1f4a4d85c2.zip
  .yarn/cache/postcss-npm-8.3.11-ded5d923bd-1a230553d7.zip
  .yarn/cache/postcss-safe-parser-npm-5.0.2-0d30a118ed-b786eca091.zip
  .yarn/cache/terser-npm-5.5.1-6fc0e0b56a-82c1bbb917.zip
  data/persian/articles/cej3lzd5e0go.json
  package.json
  src/integration/pages/articles/news/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/server/index.jsx
  src/server/index.test.jsx
  yarn.lock
Labels: AMP, cross-team

#9640 render loadable preload links
  src/server/Document/component.jsx
  src/server/Document/index.jsx
  src/server/Document/index.test.jsx
  src/server/index.test.jsx
Labels: technical-work, cross-team

#9648 remove cookie mocks from UserContext/cookies tests
  src/app/contexts/UserContext/cookies/index.test.js
Labels: technical-work, cross-team

#9621 Remove isLive toggle
  src/app/containers/PodcastPromo/Inline.jsx
  src/app/containers/PodcastPromo/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/routes/cpsAsset/getInitialData/index.js
Labels: ux, cross-team

#9655 add crossorigin=anonymous to preload links
  src/server/Document/index.jsx
Labels: performance, cross-team

#9663 Removes yarn cache check for offline install test
  scripts/installNodeModules.sh
Labels: cross-team

#9665 Revert "Removes yarn cache check for offline install test"
  scripts/installNodeModules.sh
Labels: cross-team

#9642 Update Turkish and Ukrainian nav
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukrainian.js
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
Labels: cross-team

#9660 fix ODTV Heading spacing
  src/app/containers/OnDemandHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/OnDemandHeading/index.jsx
  src/app/pages/OnDemandAudioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
Labels: bug, ux, cross-team

#9632 Remove figure element in MediaPlayer
  data/thai/cpsAssets/23463609.json
  data/thai/cpsAssets/international-59121888.json
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
Labels: bug, a11y

#9671 Update Marathi podcast third party links
  data/marathi/podcasts/p0b1s4nm.json
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/marathi.js
Labels: Good first issue

#9675 Localise English strings in Burmese podcast promo string
  src/app/lib/config/services/burmese.js
Labels: cross-team

#9678 Update podcast external links for Arabic and Marathi
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/arabic.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/marathi.js
Labels: cross-team

#9676 fix TalkBack reading comma
  src/app/containers/EpisodeList/RecentVideoEpisodes/__snapshots__/index.test.jsx.snap
  src/app/containers/EpisodeList/RecentVideoEpisodes/index.jsx
  src/app/containers/EpisodeList/RecentVideoEpisodes/index.test.jsx
Labels: bug, a11y

#9687 Update inline promo for podcast brand - BBC Arabic
  src/app/lib/config/services/arabic.js
Labels: cross-team

#9693 Fixing transitive dependency versions
  .yarn/cache/ansi-html-https-21a4c9346e-05e7fdc947.zip
  .yarn/cache/ansi-html-npm-0.0.7-962845f6a8-9b839ce996.zip
  .yarn/cache/json-schema-npm-0.2.3-018ee3dfc9-bbc2070988.zip
  .yarn/cache/json-schema-npm-0.4.0-e776313070-66389434c3.zip
  license-exceptions.json
  package.json
  yarn.lock
Labels: cross-team

#9690 Fix WSOJ spacing for Gel_Group_1
  src/app/containers/CpsRecommendations/RecommendationsPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/RecommendationsPromo/index.jsx
  src/app/containers/CpsRecommendations/RecommendationsPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
Labels: bug, ux, cross-team

#9619 Fix nested spans bug on TalkBack on RadioSchedule
  src/app/components/RadioSchedule/ProgramCard/__snapshots__/index.test.jsx.snap
  src/app/components/RadioSchedule/ProgramCard/index.jsx
  src/app/components/RadioSchedule/ScheduleItemHeader/index.jsx
  src/app/components/RadioSchedule/__snapshots__/index.test.jsx.snap
  src/app/components/RadioSchedule/index.jsx
  src/app/components/RadioSchedule/testHelpers/helper.jsx
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
Labels: a11y, cross-team

#9692 report more page types web vitals
  src/app/Layouts/defaultPageWrapper.jsx
  src/app/containers/WebVitals/index.jsx
  src/app/containers/WebVitals/index.test.jsx
  src/app/containers/WebVitals/pageTypes.js
Labels: performance

#9711 Adding additional external platforms to BBC Marathi podcasts
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/marathi.js
Labels: cross-team

#9598 Fix TalkBack incorrectly reading out spans on StoryPromo content
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/index.jsx
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/index.jsx
  src/app/containers/IndexPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexPageSection/index.jsx
  src/app/containers/StoryPromo/LinkContents/index.jsx
  src/app/containers/StoryPromo/LinkContents/index.test.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: a11y, a11y-swarm, cross-team
