Repository bbc/simorgh, pull requests merged in 2021-01, with the labels that each got.

#8657 Update unit test snapshots because..... 2020
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/integration/pages/articles/news/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/news/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team

#8658 Bump wait-on and pin axios
  package-lock.json
  package.json
Labels: cross-team, security

#8615 remove enzyme from ChartbeatAnalytics
  src/app/containers/ChartbeatAnalytics/canonical/index.test.jsx
Labels: cross-team, technical-work

#8619 Updated OD Radio fixture data to include recent episodes data
  cypress/integration/pages/onDemandRadio/tests.js
  cypress/support/config/settings.js
  data/afaanoromoo/bbc_afaanoromoo_radio/w3cszx1y.json
  data/amharic/bbc_amharic_radio/w3csz5r9.json
  data/arabic/bbc_arabic_radio/w3ct01yb.json
  data/bengali/bbc_bangla_radio/w172x0562jxntqx.json
  data/burmese/bbc_burmese_radio/w3csz62h.json
  data/gahuza/bbc_gahuza_radio/w172x7rkcj6v0vz.json
  data/hausa/bbc_hausa_radio/w3cszrwm.json
  data/korean/bbc_korean_radio/w3ct0kn5.json
  data/kyrgyz/bbc_kyrgyz_radio/w3cszwmc.json
  data/nepali/bbc_nepali_radio/w172x83pnptp1s8.json
  data/persian/bbc_dari_radio/w3csz7mf.json
  data/persian/bbc_persian_radio/w172x32355t5635.json
  data/sinhala/bbc_sinhala_radio/w172x8zn8th1lwb.json
  data/somali/bbc_somali_radio/w172x90wfxd2qh4.json
  data/swahili/bbc_swahili_radio/w172x94ky63591m.json
  data/tamil/bbc_tamil_radio/w172x966tn9jwmh.json
  data/tigrinya/bbc_tigrinya_radio/w3cszzz1.json
  data/urdu/bbc_urdu_radio/w172x9dx052c8sr.json
  data/uzbek/bbc_uzbek_radio/w172x9f9qjcq3lm.json
  data/zhongwen/bbc_cantonese_radio/w172xf3r5x8hw4v.json
Labels: Recent Episodes Radio, cypress, ws-media

#8656 Replace BBC domains with wild cards and add new domain lists file
  data/news/cpsAssets/business-55345826.json
  src/server/utilities/cspHeader/domainLists.js
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: cross-team

#8659 remove enzyme from Heading tests
  src/app/containers/Headings/index.test.jsx
Labels: cross-team, technical-work

#8567 Remove simorgh jenkinsfile and redundant scripts
  Jenkinsfile
  Makefile
  package.json
  scripts/jenkinsProductionFiles.sh
  scripts/signBuild.js
  scripts/signSimorghArchive.sh
Labels: cross-team

#8661 remove enzyme from VisuallyHiddenHeadline
  src/app/containers/VisuallyHiddenHeadline/index.test.jsx
Labels: cross-team, technical-work

#8660 remove enzyme from ImageWithPlaceholder
  src/app/containers/ImageWithPlaceholder/__snapshots__/index.test.jsx.snap
  src/app/containers/ImageWithPlaceholder/fixtureData.jsx
  src/app/containers/ImageWithPlaceholder/index.test.jsx
Labels: cross-team, technical-work

#8662 Updates to navigation for Ukrainian, Oromo and Amharic
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/ukrainian.js
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
Labels: cross-team

#8614 Remove enzyme ati analytics
  src/app/containers/ATIAnalytics/canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/ATIAnalytics/canonical/index.test.jsx
  src/integration/common/analytics.canonical.js
Labels: cross-team, technical-work

#8616 Use string constant pageType for STY, PGL and MAP pages
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/containers/Byline/index.stories.jsx
  src/app/containers/Byline/index.test.jsx
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/containers/CpsAssetMediaPlayer/index.stories.jsx
  src/app/containers/CpsAssetMediaPlayer/index.test.jsx
  src/app/containers/CpsFeaturesAnalysis/index.stories.jsx
  src/app/containers/CpsFeaturesAnalysis/index.test.jsx
  src/app/containers/CpsRecommendations/index.stories.jsx
  src/app/containers/CpsRecommendations/index.test.jsx
  src/app/containers/CpsRelatedContent/index.stories.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/containers/CpsTopStories/index.stories.jsx
  src/app/containers/CpsTopStories/index.test.jsx
  src/app/containers/Header/index.test.jsx
  src/app/containers/Include/index.test.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/MostWatched/index.stories.jsx
  src/app/containers/MostWatched/index.test.jsx
  src/app/containers/SocialEmbed/testHelper.jsx
  src/app/containers/StoryPromo/IndexAlsos/index.jsx
  src/app/containers/StoryPromo/LinkContents/index.test.jsx
  src/app/containers/StoryPromo/MediaIndicator/index.test.jsx
  src/app/containers/StoryPromo/helpers/fixtureData.js
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.stories.jsx
  src/app/containers/StoryPromo/utilities/index.js
  src/app/containers/StoryPromo/utilities/index.test.js
  src/app/contexts/RequestContext/index.jsx
  src/app/pages/MediaAssetPage/index.stories.jsx
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/index.stories.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.stories.jsx
  src/app/routes/cpsAsset/getInitialData/addBylineBlock/index.js
  src/app/routes/cpsAsset/getInitialData/addHeadlineBlock/index.js
  src/app/routes/cpsAsset/getInitialData/addHeadlineBlock/index.test.js
  src/app/routes/cpsAsset/getInitialData/addMpuBlock/index.js
  src/app/routes/cpsAsset/getInitialData/addRecommendationsBlock/index.js
  src/app/routes/cpsAsset/getInitialData/addSummaryBlock/index.js
  src/app/routes/cpsAsset/getInitialData/addSummaryBlock/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.test.js
  src/app/routes/cpsAsset/getInitialData/index.test.js
  src/app/routes/cpsAsset/utils/getAssetType.test.js
  src/app/routes/utils/sharedDataTransformers/filterUnknownContentTypes/index.test.js
Labels: cross-team, ws-articles

#8618 Bring non-alpha version of psammead-episode-list into Simorgh
  package-lock.json
  package.json
Labels: dependencies, ws-media

#8673 Reinstate Cypress CI script
  package.json
Labels: cross-team

#8607 Switch out img for amp-img on amp
  package-lock.json
  package.json
  src/app/containers/RecentVideoEpisodes/index.jsx
  src/app/containers/RecentVideoEpisodes/index.test.jsx
Labels: ws-media

#8663 remove enzyme from usePrevious
  src/app/containers/App/App.jsx
  src/app/lib/utilities/usePrevious/index.js
  src/app/lib/utilities/usePrevious/index.test.jsx
Labels: cross-team, technical-work

#8665 Complete removal of enzyme
  CONTRIBUTING.md
  docs/Code-Standards.md
  jest.config.js
  package-lock.json
  package.json
  src/app/containers/ArticleFigure/index.test.jsx
  src/testHelpers/jest-setup.js
Labels: cross-team, technical-work

#8617 Update captions
  package-lock.json
  package.json
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/__snapshots__/index.test.jsx.snap
  src/app/containers/Caption/index.jsx
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: Weekly goal, ws-articles

#8681 Integrate psammead-grid and update snapshots
  package-lock.json
  package.json
  src/app/components/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/components/Grid/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleTimestamp/__snapshots__/index.test.jsx.snap
  src/app/containers/BulletedList/__snapshots__/index.test.jsx.snap
  src/app/containers/Byline/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsOnwardJourney/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/RecommendationsPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/RecommendationsPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsText/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/FauxHeadline/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/__snapshots__/index.test.jsx.snap
  src/app/containers/Include/amp/__snapshots__/Idt2Amp.test.jsx.snap
  src/app/containers/Include/amp/__snapshots__/VjAmp.test.jsx.snap
  src/app/containers/Include/canonical/Idt2/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/PageHandlers/withLoading/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/SocialEmbed/__snapshots__/index.test.jsx.snap
  src/app/containers/Text/__snapshots__/index.test.jsx.snap
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FeatureIdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FrontPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: cross-team

#8675 Upgrade psammead test helpers
  package-lock.json
  package.json
  src/app/containers/Footer/index.test.jsx
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: cross-team, technical-work

#8679 remove async snapshot use
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/index.test.jsx
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/index.test.jsx
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/index.test.jsx
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/index.test.jsx
  src/app/pages/OnDemandRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandRadioPage/index.test.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.test.jsx
Labels: cross-team, technical-work

#8632 Data-e2e locators for On Demand TV
  cypress/integration/pages/onDemandRadio/tests.js
  cypress/integration/pages/onDemandTV/tests.js
  src/app/containers/RecentVideoEpisodes/index.jsx
Labels: OD-TV, cypress, ws-media

#8609 Use Episode Title when available on TV pages
  data/afrique/bbc_afrique_tv/tv/w3ct05n6.json
  src/app/containers/OnDemandHeading/index.jsx
  src/app/containers/OnDemandHeading/index.test.jsx
  src/app/containers/OnDemandTvFooterTimestamp/index.jsx
  src/app/containers/OnDemandTvFooterTimestamp/index.test.jsx
  src/app/pages/OnDemandTvPage/OnDemandTvPage.jsx
  src/app/routes/onDemandTV/getInitialData/index.js
  src/app/routes/onDemandTV/getInitialData/index.test.js
Labels: ws-media

#8634 Updated fixture data for OD TV
  cypress/integration/pages/onDemandTV/tests.js
  cypress/support/config/settings.js
  data/burmese/bbc_burmese_tv/tv/w172xbmg65lczy0.json
  data/gujarati/bbc_gujarati_tv/tv_programmes/w13xttqr.json
  data/hausa/bbc_hausa_tv/tv/w172xcg0kg6vph8.json
  data/hindi/bbc_hindi_tv/tv_programmes/w13xttlw.json
  data/kyrgyz/bbc_kyrgyz_tv/tv/w172xcgmgcj9864.json
  data/pashto/bbc_pashto_tv/tv/w172xcldhhrhmcf.json
  data/persian/bbc_persian_tv/tv_programmes/w13xttnr.json
  data/swahili/bbc_swahili_tv/tv/w172xcqnsxfj1bk.json
  data/tamil/bbc_tamil_tv/tv_programmes/w13xttmy.json
  data/telugu/bbc_telugu_tv/tv_programmes/w13xttld.json
  data/ukrainian/bbc_ukrainian_tv/tv/w172xct4hclz27g.json
  data/urdu/bbc_urdu_tv/tv/w172xctrrk6t25t.json
  data/uzbek/bbc_uzbek_tv/tv_programmes/w13xttqv.json
Labels: ws-media

#8684 Exclude Asset from Amp Validation Testing
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
  scripts/ampHtmlValidator/index.js
Labels: ws-articles

#8685 Fix Korean CPS articleTimestamp format issue
  data/korean/cpsAssets/international-55570242.json
  src/app/lib/config/services/korean.js
Labels: ws-articles

#8686 Revert "Reinstate Cypress CI script"
  package.json
Labels: cross-team

#8640 Integration tests for OD TV Recent Episodes
  src/app/containers/RecentVideoEpisodes/index.jsx
  src/integration/common/index.js
  src/integration/common/recentEpisodes.js
  src/integration/pages/onDemandRadioPage/crossPlatformTests.js
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandRadioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/crossPlatformTests.js
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
Labels: ws-media

#8697 Update Russian Related content translation
  src/app/contexts/ServiceContext/index.test.jsx
  src/app/lib/config/services/russian.js
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
Labels: cross-team

#8700 Pin Consent Banner to bottom of viewport
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/index.canonical.jsx
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
Labels: ws-articles

#8706 Unpin various dependencies
  package-lock.json
  package.json
Labels: cross-team

#8711 Reconfigure dependabot to only allow security updates
  .github/dependabot.yml
Labels: cross-team

#8701 add renovate config
  renovate.json
Labels: cross-team, technical-work

#8715 Remove dependabot config
  .github/dependabot.yml
Labels: cross-team

#8687 Update chromaui action
  .github/workflows/simorgh-e2e-tests.yml
  .github/workflows/simorgh-integration-tests.yml
  .github/workflows/simorgh-local-server-tests.yml
  .github/workflows/simorgh-misc-checks.yml
  .github/workflows/simorgh-unit-tests.yml
Labels: cross-team

#8639 Add pre-player placeholder to OD TV pages
  src/app/containers/AVPlayer/index.jsx
  src/app/pages/OnDemandTvPage/OnDemandTvPage.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/integration/common/index.js
  src/integration/common/mediaPlaceholder.js
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/canonicalTests.js
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/mediaPlaceholderTests.js
  src/integration/pages/onDemandTVPage/pashto/canonical.test.js
  src/integration/pages/onDemandTVPage/somali/canonical.test.js
Labels: ws-media

#8716 Add base config as basis for our config
  renovate.json
Labels: cross-team

#8717 remove schedule
  renovate.json
Labels: cross-team

#8676 upgrade to react 17
  package-lock.json
  package.json
  src/app/pages/LiveRadioPage/index.test.jsx
Labels: cross-team, technical-work

#8704 Add images & manifests for PS AMP services
  public/newsround/images/icons/icon-128x128.png
  public/newsround/images/icons/icon-144x144.png
  public/newsround/images/icons/icon-152x152.png
  public/newsround/images/icons/icon-180x180.png
  public/newsround/images/icons/icon-192x192.png
  public/newsround/images/icons/icon-384x384.png
  public/newsround/images/icons/icon-512x512.png
  public/newsround/images/icons/icon-72x72.png
  public/newsround/images/icons/icon-96x96.png
  public/newsround/images/metadata/poster-1024x576.png
  public/newsround/manifest.json
  public/sport/images/icons/icon-128x128.png
  public/sport/images/icons/icon-144x144.png
  public/sport/images/icons/icon-152x152.png
  public/sport/images/icons/icon-180x180.png
  public/sport/images/icons/icon-192x192.png
  public/sport/images/icons/icon-384x384.png
  public/sport/images/icons/icon-512x512.png
  public/sport/images/icons/icon-72x72.png
  public/sport/images/icons/icon-96x96.png
  public/sport/images/metadata/poster-1024x576.png
  public/sport/manifest.json
Labels: ws-articles

#8721 Fix consent banner
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.canonical.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/index.canonical.jsx
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
Labels: ws-articles

#8729 Update to psammead-nav 9
  package-lock.json
  package.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/__snapshots__/index.test.jsx.snap
  src/app/containers/Navigation/index.amp.jsx
  src/app/containers/Navigation/index.amp.test.jsx
  src/app/containers/Navigation/index.canonical.jsx
  src/app/containers/Navigation/index.canonical.test.jsx
  src/app/containers/Navigation/index.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-articles

#8743 Adding fixture data for PS AMP STY and CSP
  data/cymrufyw/cpsAssets/53403042.json
  data/cymrufyw/cpsAssets/55702465.json
  data/naidheachdan/cpsAssets/55704298.json
  data/news/cpsAssets/science-environment-55699262.json
  data/newsround/cpsAssets/55701600.json
  data/sport/cpsAssets/55692438.json
  data/sport/legacyAssets/cricket/55703958.json
  data/sport/legacyAssets/football/55699252.json
Labels: ws-articles

#8740 Update to Persian navigation to remove US election link
  src/app/lib/config/services/persian.js
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
Labels: cross-team

#8744 Add Sport and Newsround service configs
  src/app/lib/config/services/loadableConfig.js
  src/app/lib/config/services/newsround.js
  src/app/lib/config/services/sport.js
Labels: ws-articles

#8752 Auto accept chromaticqa latest
  .github/workflows/simorgh-misc-checks.yml
Labels: cross-team, technical-work

#8760 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: Documentation, cross-team

#8709 Fix hot module replacement on dev server
  package.json
Labels: cross-team

#8571 Show Podcast promo on Russian STY pages
  package-lock.json
  package.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/PodcastPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/PodcastPromo/index.jsx
  src/app/containers/PodcastPromo/index.test.jsx
  src/app/lib/config/services/russian.js
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/index.test.jsx
Labels: ws-media

#8672 Exclude Byline Block from STY page with missing title or name
  src/app/containers/Byline/index.jsx
  src/app/containers/Byline/index.test.jsx
  src/app/models/propTypes/byline/index.js
  src/app/routes/cpsAsset/getInitialData/addBylineBlock/index.js
Labels: stories-STYs, technical-work, ws-articles

#8763 [PS AMP] Add fixture data for secondary column data
  data/cymrufyw/secondaryColumn/index.json
  data/naidheachdan/secondaryColumn/index.json
  data/news/secondaryColumn/index.json
  data/newsround/secondaryColumn/index.json
  data/sport/secondaryColumn/index.json
Labels: ws-articles

#8765 Exclude webpack and @loadable from group dependency prs
  renovate.json
Labels: cross-team

#8773 Group minor and patch updates for webpack and loadable
  renovate.json
Labels: cross-team

#8777 Simorgh encode JS bundle URL's
  src/server/Document/index.jsx
  src/server/utilities/encodeChunkUri/index.js
  src/server/utilities/encodeChunkUri/index.test.js
Labels: cross-team

#8780 force immer version
  package-lock.json
  package.json
Labels: cross-team

#8772 Add recent episodes translation for Gujarati
  src/app/lib/config/services/gujarati.js
Labels: ws-media

#8655 Filter radio schedules by valid programs
  cypress/integration/pages/liveRadio/testsForCanonicalOnly.js
  cypress/integration/pages/onDemandRadio/testsForCanonicalOnly.js
  src/app/containers/RadioSchedule/utilities/evaluateScheduleData.js
  src/app/containers/RadioSchedule/utilities/evaluateScheduleData.test.js
  src/app/containers/RadioSchedule/utilities/processRadioSchedule.js
Labels: ws-media

#8795 Temporarily skip failing VJ Include E2E test
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
Labels: bug, cypress, high-priority, includes, ws-articles

#8796 Upgrade podcast promo with ie11 fix
  package-lock.json
  package.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/PodcastPromo/__snapshots__/index.test.jsx.snap
Labels: ws-media

#8799 experiment to check include has been initialised with shadow dom
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
Labels: ws-articles

#8803 Create renovate.md
  renovate.md
Labels: cross-team

#8794 Allow bylines on CSP pages
  src/app/routes/cpsAsset/getInitialData/addBylineBlock/index.js
  src/app/routes/cpsAsset/getInitialData/addBylineBlock/index.test.js
Labels: ws-articles

#8804 Silence error from include test
  cypress/support/index.js
Labels: ws-articles

#8805 Enable AV for cymrufyw
  src/app/containers/CpsAssetMediaPlayer/index.jsx
  src/app/containers/CpsAssetMediaPlayer/utils/getAssetUri/index.js
  src/app/containers/CpsAssetMediaPlayer/utils/getAssetUri/index.test.js
Labels: ws-articles

#8671 Add a preload tag that applies only to the lead image
  src/app/containers/ArticleFigure/index.jsx
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/index.jsx
  src/app/containers/Image/index.test.jsx
  src/app/containers/ImageWithPlaceholder/fixtureData.jsx
  src/app/containers/ImageWithPlaceholder/index.jsx
  src/app/containers/ImageWithPlaceholder/index.test.jsx
  src/app/lib/config/toggles/README.md
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/const.js
  src/app/lib/config/toggles/liveConfig.js
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/canonicalTests.js
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: ws-articles

#8776 ATI bits for PS AMP
  data/news/cpsAssets/uk-england-birmingham-55722084.json
  data/pidgin/cpsAssets/tori-49450859.json
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.js
  src/app/contexts/RequestContext/getStatsDestination/index.js
  src/app/contexts/RequestContext/getStatsDestination/index.test.js
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
Labels: ws-articles

#8818 Adapt Chartbeat for Podcasts
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
Labels: podcasts, ws-media
