Repository bbc/simorgh, pull requests merged in 2021-12, with the labels that each got.

#9718 use index if available for promo id
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsRelatedContent/RelatedContentPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/index.jsx
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/index.jsx
  src/app/containers/IndexPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/containers/StoryPromo/utilities/index.js
  src/app/containers/StoryPromo/utilities/index.test.js
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: a11y

#9720 Added more Optimo article URLs for testing
  cypress/support/config/settings.js
Labels: cypress, cross-team, optimo

#9571 Fix TalkBack incorrectly reading links in nested spans on Podcast page
  data/portuguese/podcasts/p07r3r3t.json
  src/app/containers/EpisodeList/Link.jsx
  src/app/containers/EpisodeList/RecentAudioEpisodes/__snapshots__/index.test.jsx.snap
  src/app/containers/EpisodeList/RecentAudioEpisodes/index.jsx
  src/app/containers/EpisodeList/RecentVideoEpisodes/__snapshots__/index.test.jsx.snap
  src/app/containers/EpisodeList/RecentVideoEpisodes/index.jsx
  src/app/containers/PodcastExternalLinks/__snapshots__/index.test.jsx.snap
  src/app/containers/PodcastExternalLinks/index.jsx
  src/app/containers/PodcastExternalLinks/index.test.jsx
Labels: bug, a11y, cross-team
