Repository bbc/simorgh, pull requests merged in 2021-09, with the labels that each got.

#9378 replace arabic podcast promo image
  src/app/lib/config/services/arabic.js
Labels: cross-team

#9373 Fix bugs in unit tests
  src/app/components/MediaPlayer/Amp/index.test.jsx
  src/app/components/MediaPlayer/AudioLoader/index.test.jsx
  src/app/components/MediaPlayer/Canonical/index.test.jsx
  src/app/components/MediaPlayer/index.stories.jsx
  src/app/components/MediaPlayer/index.test.jsx
  src/app/components/RadioSchedule/ProgramCard/index.test.jsx
  src/app/containers/Ad/index.test.jsx
  src/app/containers/App/App.test.jsx
  src/app/containers/CpsRecommendations/RecommendationsPromoList/index.jsx
  src/app/containers/Header/ScriptLink/index.test.jsx
  src/app/containers/MostRead/Canonical/index.test.jsx
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/index.test.jsx
  src/app/containers/RadioSchedule/index.test.jsx
  src/app/containers/StoryPromo/IndexAlsos/index.jsx
  src/app/containers/StoryPromo/IndexAlsos/index.test.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/pages/ArticlePage/index.test.jsx
  src/app/pages/MostWatchedPage/index.test.jsx
  src/testHelpers/mockComponents.jsx
  src/testHelpers/setupTests.js
Labels: bug, cross-team

#9362 Webpack dev server v4 upgrade
  .yarn/cache/@types-http-proxy-npm-1.17.7-b5168c95b4-88f9c75ca6.zip
  .yarn/cache/@types-retry-npm-0.12.1-05f3303aac-5f46b25560.zip
  .yarn/cache/ansi-regex-npm-6.0.0-549f99883f-7e86b75c21.zip
  .yarn/cache/async-limiter-npm-1.0.1-7e6819bcdb-2b849695b4.zip
  .yarn/cache/cliui-npm-5.0.0-885b5f48ee-0bb8779efe.zip
  .yarn/cache/default-gateway-npm-4.2.0-f6bdd83987-1f5be76547.zip
  .yarn/cache/default-gateway-npm-6.0.3-d8d9292176-126f8273ec.zip
  .yarn/cache/define-lazy-prop-npm-2.0.0-bba0cd91a7-0115fdb065.zip
  .yarn/cache/del-npm-4.1.1-8bc04567c6-521f7da44b.zip
  .yarn/cache/del-npm-6.0.0-fb1f14b406-5742891627.zip
  .yarn/cache/eventsource-npm-1.1.0-6a04120a6b-78338b7e75.zip
  .yarn/cache/globby-npm-6.1.0-590bfb2681-18109d6b9d.zip
  .yarn/cache/html-entities-npm-2.3.2-366c4c257a-522d8d202d.zip
  .yarn/cache/http-proxy-middleware-npm-0.19.1-ba4e5c6109-64df043841.zip
  .yarn/cache/http-proxy-middleware-npm-2.0.1-d5d4a98393-0de65bc664.zip
  .yarn/cache/import-local-npm-2.0.0-9cfca832bf-b846925248.zip
  .yarn/cache/internal-ip-npm-4.3.0-721bfbef82-c970433c84.zip
  .yarn/cache/internal-ip-npm-6.2.0-d967d911cf-6d08299c05.zip
  .yarn/cache/ip-regex-npm-2.1.0-7eb0f6c4ab-331d95052a.zip
  .yarn/cache/ip-regex-npm-4.3.0-4ac12c6be9-7ff904b891.zip
  .yarn/cache/ipaddr.js-npm-2.0.1-04e97280d7-dd194a394a.zip
  .yarn/cache/is-ip-npm-3.1.0-7b8bc9330c-da2c2b2824.zip
  .yarn/cache/is-path-in-cwd-npm-2.1.0-2a2ca98522-6b01b3f8c9.zip
  .yarn/cache/is-path-inside-npm-2.1.0-f943552e7a-6ca34dbd84.zip
  .yarn/cache/is-plain-obj-npm-3.0.0-a5ae411d5a-a6ebdf8e12.zip
  .yarn/cache/json3-npm-3.3.3-be4baec3f1-55eda204a4.zip
  .yarn/cache/killable-npm-1.0.1-bf69803651-911a85c6e3.zip
  .yarn/cache/loglevel-npm-1.7.1-46e39bd115-715a4ae69a.zip
  .yarn/cache/open-npm-8.2.1-f135ffeb36-fcde005918.zip
  .yarn/cache/opn-npm-5.5.0-9a97e03147-35b677b5a1.zip
  .yarn/cache/original-npm-1.0.2-2250635ba0-8dca9311da.zip
  .yarn/cache/p-retry-npm-3.0.1-1abc743ac9-702efc63fc.zip
  .yarn/cache/p-retry-npm-4.6.1-1a06a28faf-e6d540413b.zip
  .yarn/cache/path-is-inside-npm-1.0.2-7dd0711668-0b5b6c92d3.zip
  .yarn/cache/pinkie-npm-2.0.4-cffce4fb09-b12b10afea.zip
  .yarn/cache/pinkie-promise-npm-2.0.1-095439b8c5-b53a4a2e73.zip
  .yarn/cache/resolve-cwd-npm-2.0.0-cce7da6fd4-e7c16880c4.zip
  .yarn/cache/resolve-from-npm-3.0.0-0bff35697e-fff9819254.zip
  .yarn/cache/sockjs-client-npm-1.5.2-457b4f1fdd-b3c3966ca8.zip
  .yarn/cache/strip-ansi-npm-7.0.0-bbcea1587b-b79ca61372.zip
  .yarn/cache/webpack-dev-middleware-npm-5.0.0-bb15eafbfb-e5bf56a299.zip
  .yarn/cache/webpack-dev-server-npm-3.11.2-02bc129ea9-d2bfa2e9a3.zip
  .yarn/cache/webpack-dev-server-npm-4.0.0-f2b466e492-abf88fb940.zip
  .yarn/cache/wrap-ansi-npm-5.1.0-293b407c18-9b48c86222.zip
  .yarn/cache/ws-npm-6.2.2-ca62a10fa0-aec3154ec5.zip
  .yarn/cache/ws-npm-8.2.1-93dae97f6f-22906903c7.zip
  .yarn/cache/yargs-npm-13.3.2-1588f5dd4c-75c13e837e.zip
  .yarn/cache/yargs-parser-npm-13.1.2-546b639909-c8bb6f44d3.zip
  package.json
  webpack.config.client.js
  webpack.config.js
  yarn.lock
Labels: technical-work, cross-team

#9391 Gahuza mundo nav updates
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/mundo.js
  src/integration/pages/liveRadio/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team

#9382 Episode list tracking
  src/app/containers/EpisodeList/RecentAudioEpisodes/index.jsx
  src/app/containers/EpisodeList/RecentAudioEpisodes/index.stories.jsx
  src/app/containers/EpisodeList/RecentAudioEpisodes/index.test.jsx
Labels: cross-team

#9398 e2e assert ckns cookie value is either 1 or 2
  cypress/integration/specialFeatures/cookieBanner/testsForCanonicalOnly.js
Labels: cross-team

#9381 add axe-core a11y cypress tests for all pages
  .github/workflows/simorgh-local-server-tests.yml
  .yarn/cache/cypress-axe-npm-0.13.0-88bb0af6dd-52879b6b7a.zip
  cypress/integration/pages/testsForAllPages.js
  cypress/plugins/index.js
  cypress/support/helpers/checkA11y.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: cross-team

#9401 fix e2e ckns cookie assertion
  cypress/integration/specialFeatures/cookieBanner/testsForCanonicalOnly.js
Labels: cross-team

#9407 disable iframe-title a11y check
  cypress/support/helpers/checkA11y.js
Labels: a11y, cross-team

#9416 exclude amps-ad elements from axe core checks
  cypress/support/helpers/checkA11y.js
Labels: a11y

#9386 Amp validation duplication image placeholder fix
  .yarn/cache/@bbc-psammead-image-placeholder-npm-3.2.2-9e33ff83d8-796e120bd0.zip
  .yarn/cache/@bbc-psammead-image-placeholder-npm-3.4.0-94ea0a26bf-244c43cde5.zip
  package.json
  src/app/components/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/Bulletin/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/RecommendationsPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/RecommendationsPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/EpisodeList/RecentVideoEpisodes/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/ImageWithPlaceholder/__snapshots__/index.test.jsx.snap
  src/app/containers/ImageWithPlaceholder/index.jsx
  src/app/containers/IndexPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/OnDemandImage/__snapshots__/index.test.jsx.snap
  src/app/containers/PodcastPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandAudioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  yarn.lock
Labels: cross-team

#9417 Adds a 1s wait after every change to the privacy or cookie values to allow time for update before assertion
  cypress/integration/specialFeatures/cookieBanner/testsForCanonicalOnly.js
Labels: cypress, cross-team

#9419 change live yoruba url no duplicate heading
  cypress/support/config/settings.js
Labels: a11y, cypress, stories-STYs

#9379 Add external link translations
  src/app/containers/InlineLink/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: cross-team

#9423 Set CMP cookie to prevent pop up
  cypress/integration/pages/testsForAllPages.js
  cypress/support/helpers/visitPage.js
Labels: cypress, cross-team

#9432 Update Japanese nav to remove olympics
  src/app/lib/config/services/japanese.js
Labels: cross-team

#9404 Add conditional render and media type to fix story promo link text
  src/app/containers/CpsRecommendations/RecommendationsPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/RecommendationsPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/LinkContents/index.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
Labels: a11y, cross-team

#9441 Updating third party links for Persian and Arabic Podcast pages
  data/arabic/podcasts/p09w8yvk.json
  data/persian/podcasts/p09v5lgp.json
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/arabic.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/persian.js
Labels: cross-team

#9434 Add new font bengali sinhala tamil
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/tamil.js
  src/app/lib/utilities/isTest/index.js
  src/app/lib/utilities/isTest/index.test.js
Labels: high-priority, cross-team

#9445 Fixes font script switching
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/sinhala.js
Labels: cross-team

#9355 Fix podcast page design
  src/app/containers/OnDemandFooterTimestamp/index.jsx
  src/app/containers/OnDemandHeading/StyledRadioHeadingContainer.jsx
  src/app/containers/OnDemandHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/OnDemandHeading/index.jsx
  src/app/containers/OnDemandParagraph/__snapshots__/index.test.jsx.snap
  src/app/containers/OnDemandParagraph/index.jsx
  src/app/pages/OnDemandAudioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
Labels: ux, cross-team

#9436 Add sizes attribute to image component in Story, Photo Gallery, Article and Media Asset pages
  src/app/containers/ArticleFigure/index.jsx
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/index.jsx
  src/app/containers/Image/index.test.jsx
  src/app/containers/ImageWithPlaceholder/index.jsx
  src/app/pages/ArticlePage/ArticlePage.jsx
  src/app/pages/MediaAssetPage/MediaAssetPage.jsx
  src/app/pages/PhotoGalleryPage/PhotoGalleryPage.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/articles/news/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team

#9392 Bug fix for externalLinkText
  src/app/containers/PodcastExternalLinks/__snapshots__/index.test.jsx.snap
  src/app/containers/PodcastExternalLinks/index.jsx
Labels: a11y, a11y-swarm, cross-team

#9449 remove the fade animation from lazy loaded article, STY, PGL and MAP images
  src/app/containers/Image/__snapshots__/index.test.jsx.snap
  src/app/containers/Image/index.jsx
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/articles/news/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team

#9400 Gnadtech 2349 2
  src/app/containers/NielsenAnalytics/Amp/index.jsx
  src/app/containers/NielsenAnalytics/Amp/index.test.jsx
  src/app/containers/NielsenAnalytics/__snapshots__/index.test.jsx.snap
  src/app/containers/NielsenAnalytics/index.jsx
  src/app/containers/NielsenAnalytics/index.test.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/contexts/RequestContext/index.jsx
  src/app/contexts/RequestContext/index.test.jsx
  src/app/lib/config/toggles/README.md
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
  src/app/pages/ArticlePage/ArticlePage.jsx
  src/app/pages/StoryPage/StoryPage.jsx
Labels: cross-team

#9437 Resolve spacing between secondary column components
  src/app/containers/PodcastPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/PodcastPromo/index.jsx
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: Good first issue, ws-articles, ux

#9457 Remove Cypress promise exception handler
  cypress/support/index.js
Labels: cypress, technical-work, cross-team

#9453 Updates podcastPromo Config for Arabic, Burmese, Gahuza, Hindi, Indonesian, Marathi and Persian services
  data/arabic/cpsAssets/middleeast-58677609.json
  data/arabic/podcasts/p09m6x31.json
  data/gahuza/cpsAssets/amakuru-58660901.json
  data/gahuza/podcasts/p07yjlmf.json
  data/indonesia/cpsAssets/dunia-58476696.json
  data/indonesia/podcasts/p09wtj1j.json
  data/marathi/cpsAssets/international-58706494.json
  data/persian/podcasts/p071q6yg.json
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/persian.js
Labels: cross-team

#9452 Prevent full page re-renders on URL hash changes
  README.md
  src/app/containers/InlineLink/index.jsx
  src/app/containers/PageHandlers/withHashChangeHandler/index.jsx
  src/app/containers/PageHandlers/withHashChangeHandler/index.test.js
  src/app/containers/PageHandlers/withHashChangeHandler/index.test.jsx
  src/app/containers/PageHandlers/withHashChangeHandler/isHashChangeOnSamePath.js
  src/app/containers/PageHandlers/withVariant/index.jsx
  src/app/containers/PageHandlers/withVariant/index.test.jsx
  src/app/pages/ArticlePage/ArticlePage.jsx
  src/app/pages/ArticlePage/index.test.jsx
  src/app/pages/utils/applyBasicPageHandlers.js
  src/app/routes/cpsAsset/index.jsx
  src/app/routes/utils/pageIsSame/index.js
  src/app/routes/utils/pageIsSame/index.test.js
Labels: cross-team

#9461 Use SIMORGH_APP_ENV value for CSP header injection
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: bug, technical-work, cross-team

#9467 Removes Iskoola Pota, Latha, Shonar Bangla fonts from Simorgh
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/tamil.js
Labels: cross-team

#9471 pin web-vitals to 1.1.1
  package.json
  yarn.lock
Labels: cross-team

#9473 Prevent web-vitals upgrade from Renovate
  renovate.json
Labels: technical-work, cross-team
