Repository bbc/simorgh, pull requests merged in 2021-06, with the labels that each got.

#9153 force resolve web-vitals 1.1.1
  package.json
  yarn.lock
Labels: bug, cross-team

#9143 Move podcast wrapper to podcast promo component
  src/app/containers/PodcastPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/PodcastPromo/index.jsx
  src/app/pages/StoryPage/StoryPage.jsx
Labels: podcasts

#9159 remove cookie and localstorage deletion between snapshots
  .storybook/helpers/clearAppStorage.js
  .storybook/preview.js
Labels: cross-team

#9145 Use view tracker multi element fix
  package.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/hooks/useViewTracker/index.jsx
  src/app/hooks/useViewTracker/index.test.jsx
  yarn.lock
Labels: cross-team

#9157 Cypress - Catching specific uncaught exception: application error front page Arabic AMP
  cypress/integration/pages/frontPage/tests.js
  yarn.lock
Labels: ads, cross-team, cypress

#9158 Remove flakey amp validator unit test
  scripts/ampHtmlValidator/index.test.js
Labels: AMP, cross-team

#9164 force lazy images to load in chromatic
  .storybook/preview.js
Labels: cross-team

#9173 Add utility function to check if most read is enabled for the service
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
  src/app/routes/cpsAsset/utils/hasMostRead.js
  src/app/routes/cpsAsset/utils/hasMostRead.test.js
Labels: most-read

#9132 Related content tracking
  src/app/components/Grid/index.jsx
  src/app/containers/CpsOnwardJourney/index.jsx
  src/app/containers/CpsRelatedContent/RelatedContentPromo/index.jsx
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/index.jsx
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/hooks/useClickTrackerHandler/index.jsx
  src/app/hooks/useClickTrackerHandler/index.test.jsx
  src/app/hooks/useTrackingToggle/index.jsx
  src/app/hooks/useTrackingToggle/index.test.jsx
  src/app/hooks/useViewTracker/index.jsx
Labels: cross-team

#9177 remove vuln package resolutions that have been patched
  package.json
  yarn.lock
Labels: cross-team

#9165 Fix chromatic consent banner diffs
  src/app/containers/ConsentBanner/CanonicalLogic/index.js
Labels: cross-team

#9160 Features analysis tracking
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsFeaturesAnalysis/index.test.jsx
Labels: cross-team

#9181 Update ye olde test urls
  cypress/integration/specialFeatures/prerollAds/config.js
  cypress/support/config/settings.js
Labels: cross-team, cypress

#9175 Copy psammead-most-read into Simorgh
  package.json
  src/app/containers/MostRead/Canonical/Item/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/Canonical/Item/index.jsx
  src/app/containers/MostRead/Canonical/Item/index.test.jsx
  src/app/containers/MostRead/Canonical/List/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/Canonical/List/index.jsx
  src/app/containers/MostRead/Canonical/List/index.test.jsx
  src/app/containers/MostRead/Canonical/Rank/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/Canonical/Rank/index.jsx
  src/app/containers/MostRead/Canonical/Rank/index.test.jsx
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/utilities/gridProps.js
  src/app/containers/MostRead/utilities/index.jsx
  src/app/containers/MostRead/utilities/rankMinWidth.js
  yarn.lock
Labels: cross-team

#9187 add recommended tools docs
  .github/CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/Code-Standards.md
  docs/GPG-Signing-Guide.md
  docs/Project-Board-Guide.md
  docs/Recommended-Tools.md
Labels: cross-team

#9190 Add spacing on article timestamp v2
  src/app/components/Grid/index.jsx
  src/app/containers/ArticleTimestamp/__snapshots__/index.test.jsx.snap
Labels: cross-team

#9171 Recommendations click tracking
  data/mundo/cpsAssets/noticias-56669604.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/beacon/index.js
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsFeaturesAnalysis/index.test.jsx
  src/app/containers/CpsRecommendations/RecommendationsPromo/index.jsx
  src/app/containers/CpsRecommendations/RecommendationsPromoList/getEventTrackingData.js
  src/app/containers/CpsRecommendations/RecommendationsPromoList/getEventTrackingData.test.js
  src/app/containers/CpsRecommendations/RecommendationsPromoList/index.jsx
  src/app/containers/CpsRecommendations/RecommendationsPromoList/index.test.jsx
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/index.jsx
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/containers/CpsTopStories/index.jsx
  src/app/containers/IndexPageSection/utilities/filterAllowedItems.jsx
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/useCombinedClickTrackerHandler.js
  src/app/hooks/useClickTrackerHandler/README.md
  src/app/hooks/useClickTrackerHandler/index.jsx
  src/app/hooks/useClickTrackerHandler/index.test.jsx
  src/app/hooks/useViewTracker/README.md
  src/app/hooks/useViewTracker/index.jsx
  src/app/hooks/useViewTracker/index.test.jsx
  src/app/lib/utilities/getStoryPromoInfo/index.jsx
  src/app/lib/utilities/getStoryPromoInfo/index.test.jsx
Labels: cross-team

#9166 [DNM] Sport Tables
  data/sport/legacyAssets/cricket/20256774.json
  data/sport/legacyAssets/cricket/54646061.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/CpsTable/CpsTableCell/index.jsx
  src/app/containers/CpsTable/CpsTableRow/index.jsx
  src/app/containers/CpsTable/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTable/fixtures.js
  src/app/containers/CpsTable/index.jsx
  src/app/containers/CpsTable/index.stories.jsx
  src/app/containers/CpsTable/index.test.jsx
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/table/fixtures.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/table/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/table/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.js
Labels: cross-team

#9200 Add Apple Podcast link to new podcast page
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/arabic.js
Labels: BAU, podcasts

#9195 Mitigate toggle service DOS risk
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
Labels: cross-team, security

#9199 Pedram/zindexfix
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/containers/Brand/__snapshots__/index.test.jsx.snap
  src/app/containers/Brand/index.jsx
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
  src/app/containers/Header/__snapshots__/index.test.jsx.snap
Labels: cross-team

#9206 Upgrade prismjs to version 1.24.0
  package.json
  yarn.lock
Labels: cross-team

#9139 Most read tracking
  src/app/containers/MostRead/Canonical/Item/index.jsx
  src/app/containers/MostRead/Canonical/Item/index.test.jsx
  src/app/containers/MostRead/Canonical/List/index.test.jsx
  src/app/containers/MostRead/Canonical/index.jsx
  src/app/containers/MostRead/Canonical/index.test.jsx
  src/app/containers/MostRead/index.jsx
  src/app/containers/MostRead/utilities/index.jsx
Labels: cross-team
