Repository bbc/simorgh, pull requests merged in 2021-03, with the labels that each got.

#8718 AMP and Canonical Consent Banner updates - base
  cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
  cypress/integration/specialFeatures/cookieBanner/testsForCanonicalOnly.js
  cypress/integration/specialFeatures/scriptSwitching/testsForCanonicalOnly.js
  cypress/integration/specialFeatures/utilities/cookiePrivacyBanner/index.js
  cypress/support/config/settings.js
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/cookie.amp.jsx
  src/app/containers/ConsentBanner/Banner/index.amp.jsx
  src/app/containers/ConsentBanner/Banner/index.canonical.jsx
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/newsround.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/sport.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: AMP, amp consent, ux, ws-articles

#8875 Update README.md
  README.md
Labels: Documentation, cross-team

#8916 Update <link> static assets to use the new domain
  README.md
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/Metadata/utils.jsx
  src/integration/pages/articles/news/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/news/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team

#8927 Fix service value in radio schedule data request for Persian podcasts
  src/app/routes/utils/getRadioService/index.js
  src/app/routes/utils/getRadioService/index.test.js
Labels: podcasts, ws-media

#8924 A11y - Remove alt text from podcasts
  src/app/containers/OnDemandImage/index.jsx
  src/app/containers/OnDemandImage/index.test.jsx
  src/app/pages/OnDemandAudioPage/OnDemandAudioPage.jsx
  src/app/routes/onDemandAudio/getInitialData/index.js
Labels: ws-media

#8933 Add Listen Next translation
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
Labels: ws-media

#8935 Fixed amp cookie banner test problem, added Mundo URLS on live and test
  cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
  cypress/integration/specialFeatures/utilities/cookiePrivacyBanner/index.js
  cypress/support/config/settings.js
Labels: AMP, cross-team, cypress

#8926 Prevent article timestamp from appearing next to a video
  src/app/routes/utils/sharedDataTransformers/augmentWithTimestamp/index.js
Labels: cross-team

#8925 Temp disable secondary data fetching for newsround
  src/app/routes/cpsAsset/getInitialData/index.js
Labels: ws-articles

#8921 Create podcast links context using loadable components
  src/app/containers/PodcastExternalLinks/Link.jsx
  src/app/containers/PodcastExternalLinks/__snapshots__/index.test.jsx.snap
  src/app/containers/PodcastExternalLinks/index.jsx
  src/app/containers/PodcastExternalLinks/index.stories.jsx
  src/app/containers/PodcastExternalLinks/index.test.jsx
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/zhongwen.js
  src/app/lib/logger.const.js
  src/app/pages/OnDemandAudioPage/OnDemandAudioPage.jsx
  src/app/pages/OnDemandAudioPage/index.test.jsx
  src/app/routes/onDemandAudio/getInitialData/index.js
  src/app/routes/onDemandAudio/getInitialData/index.test.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/arabic.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/burmese.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/gahuza.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/hausa.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/hindi.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/index.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/index.test.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/indonesia.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/marathi.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/nepali.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/persian.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/portuguese.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/russian.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/zhongwen.js
Labels: ws-media

#8917 Translations for Psammead RadioSchedule
  package.json
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/index.jsx
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  yarn.lock
Labels: ws-media

#8879 Migrate psammead-episode-list to Simorgh
  package.json
  src/app/containers/EpisodeList/DateTimeDuration.jsx
  src/app/containers/EpisodeList/Description.jsx
  src/app/containers/EpisodeList/Episode.jsx
  src/app/containers/EpisodeList/Image.jsx
  src/app/containers/EpisodeList/Link.jsx
  src/app/containers/EpisodeList/MediaIndicator.jsx
  src/app/containers/EpisodeList/RecentAudioEpisodes/__snapshots__/index.test.jsx.snap
  src/app/containers/EpisodeList/RecentAudioEpisodes/fixtures.js
  src/app/containers/EpisodeList/RecentAudioEpisodes/index.jsx
  src/app/containers/EpisodeList/RecentAudioEpisodes/index.stories.jsx
  src/app/containers/EpisodeList/RecentAudioEpisodes/index.test.jsx
  src/app/containers/EpisodeList/RecentVideoEpisodes/__snapshots__/index.test.jsx.snap
  src/app/containers/EpisodeList/RecentVideoEpisodes/fixtures.js
  src/app/containers/EpisodeList/RecentVideoEpisodes/index.jsx
  src/app/containers/EpisodeList/RecentVideoEpisodes/index.stories.jsx
  src/app/containers/EpisodeList/RecentVideoEpisodes/index.test.jsx
  src/app/containers/EpisodeList/Title.jsx
  src/app/containers/EpisodeList/helpers.jsx
  src/app/containers/EpisodeList/index.jsx
  src/app/containers/RecentVideoEpisodes/fixtures.js
  src/app/containers/RecentVideoEpisodes/index.test.jsx
  src/app/pages/OnDemandAudioPage/OnDemandAudioPage.jsx
  src/app/pages/OnDemandTvPage/OnDemandTvPage.jsx
  yarn.lock
Labels: cross-team, technical-work

#8950 Fix russian podcast third party links
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/russian.js
Labels: ws-media

#8941 Enable Amp ads on live
  package.json
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Amp/index.test.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
  src/app/pages/FeatureIdxPage/__snapshots__/index.test.jsx.snap
  yarn.lock
Labels: ws-articles

#8955 Improve a11y compliance for podcast external links
  src/app/containers/EpisodeList/RecentAudioEpisodes/__snapshots__/index.test.jsx.snap
  src/app/containers/EpisodeList/RecentAudioEpisodes/index.jsx
  src/app/containers/EpisodeList/RecentVideoEpisodes/__snapshots__/index.test.jsx.snap
  src/app/containers/EpisodeList/RecentVideoEpisodes/index.jsx
  src/app/containers/PodcastExternalLinks/Link.jsx
  src/app/containers/PodcastExternalLinks/__snapshots__/index.test.jsx.snap
  src/app/containers/PodcastExternalLinks/index.jsx
  src/app/containers/PodcastExternalLinks/index.test.jsx
  src/app/pages/OnDemandAudioPage/OnDemandAudioPage.jsx
Labels: ws-media

#8959 Copy news amp consent config to archive as it was missing
  src/app/lib/config/services/archive.js
Labels: bug

#8965 Explicitly use land and className props instead of spreading
  src/app/containers/ConsentBanner/Banner/cookie.amp.jsx
Labels: cross-team, ws-articles

#8968 Adjust ad data slots for ps and ws, add new attribute and update tests
  src/app/containers/Ad/Amp/AdSlot.jsx
  src/app/containers/Ad/Amp/AdSlot.test.jsx
  src/app/containers/Ad/Amp/__snapshots__/AdSlot.test.jsx.snap
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/pages/FeatureIdxPage/__snapshots__/index.test.jsx.snap
Labels: cross-team, ws-articles

#8972 role="text" for broken text using assistive tech
  src/app/containers/PodcastExternalLinks/__snapshots__/index.test.jsx.snap
  src/app/containers/PodcastExternalLinks/index.jsx
Labels: podcasts, ws-media

#8973 Log OD Audio Recent Episodes front-end/JSON E2E differences
  cypress/integration/pages/onDemandAudio/tests.js
Labels: OD-radio, cypress

#8963 Move Podcast Promo into Simorgh
  package.json
  src/app/containers/PodcastPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/PodcastPromo/components/__snapshots__/index.test.jsx.snap
  src/app/containers/PodcastPromo/components/card-content.jsx
  src/app/containers/PodcastPromo/components/card-description.jsx
  src/app/containers/PodcastPromo/components/card-episodes-text.jsx
  src/app/containers/PodcastPromo/components/card-image-wrapper.jsx
  src/app/containers/PodcastPromo/components/card-link.jsx
  src/app/containers/PodcastPromo/components/card-title.jsx
  src/app/containers/PodcastPromo/components/card.jsx
  src/app/containers/PodcastPromo/components/index.jsx
  src/app/containers/PodcastPromo/components/index.test.jsx
  src/app/containers/PodcastPromo/components/title.jsx
  src/app/containers/PodcastPromo/index.jsx
  src/app/containers/PodcastPromo/index.stories.jsx
  yarn.lock
Labels: ws-media

#8962 Tweak AMP Consent Banner styles
  src/app/containers/ConsentBanner/Banner/__snapshots__/index.amp.test.jsx.snap
  src/app/containers/ConsentBanner/Banner/cookie.amp.jsx
Labels: amp consent, ux, ws-articles

#8958 Search and destroy all non compliant greys (Radio Recent Episodes border)
  src/app/containers/EpisodeList/DateTimeDuration.jsx
  src/app/containers/EpisodeList/RecentAudioEpisodes/__snapshots__/index.test.jsx.snap
  src/app/containers/EpisodeList/RecentAudioEpisodes/index.test.jsx
Labels: ux, ws-media

#8969 Revert "Temp disable secondary data fetching for newsround"
  cypress/support/config/settings.js
  data/newsround/cpsAssets/56331357.json
  src/app/routes/cpsAsset/getInitialData/index.js
Labels: ws-articles

#8992 Disable newsround tests on test and live
  cypress/support/config/settings.js
Labels: ws-articles

#8987 Tell google about the .co.uk URL for Sport AMP
  src/app/containers/ArticleTimestamp/timeFormatTests/expectedFormats.json
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/server/utilities/serviceConfigs/index.js
Labels: ws-articles

#8991 Add missing Listen Next translation
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-media

#8977 Enable e2e's for News Sport Newsround AMP
  cypress/support/config/settings.js
  cypress/support/helpers/runTestsForPage.js
  data/news/cpsAssets/technology-56294493.json
  data/news/cpsAssets/uk-56342465.json
  data/sport/cpsAssets/football/55790817.json
  data/sport/legacyAssets/golf/56318994.json
  data/sport/legacyAssets/rugby-union/56359986.json
Labels: ws-articles

#8995 Listen Live translations for radio schedule
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/zhongwen.js
Labels: ws-media

#8994 get storybook security patches. remove immer resolution
  package.json
  yarn.lock
Labels: cross-team

#8999 Retries added to fix frequent flakes on AMP consent banner
  cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
Labels: amp consent, cross-team, cypress

#9005 Do not run manifest and service worker tests for Amp only PS services
  cypress/integration/application/index.js
  cypress/support/helpers/ampOnlyServices.js
  cypress/support/helpers/runTestsForPage.js
Labels: cross-team, cypress

#9006 [Experiment] Removed retries on amp banner tests
  cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
Labels: amp consent, cross-team, cypress

#9002 Adding missing Marathi podcast translation
  src/app/lib/config/services/marathi.js
Labels: ws-media

#8923 Canonical focus management
  src/app/containers/Brand/index.jsx
  src/app/containers/ConsentBanner/Banner/index.canonical.jsx
  src/app/containers/ConsentBanner/Banner/index.canonical.test.jsx
  src/app/containers/ConsentBanner/a11y.canonical.test.jsx
  src/app/containers/ConsentBanner/index.canonical.jsx
  src/app/containers/ConsentBanner/index.canonical.test.jsx
  src/app/containers/ConsentBanner/index.jsx
  src/app/containers/Header/index.jsx
  src/app/containers/Header/index.test.jsx
Labels: a11y, ws-articles

#9008 Retries put back in for amp consent banner tests
  cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
Labels: amp consent, cross-team, cypress

#9015 Add Marathi and Portuguese podcast URLs to E2Es all environments
  cypress/support/config/settings.js
  data/marathi/podcasts/p09431p4.json
  data/marathi/podcasts/p09431p4/p09bplch.json
  data/portuguese/podcasts/p07r3r3t.json
  data/portuguese/podcasts/p07r3r3t/p083x9gr.json
Labels: cypress, podcasts, ws-media

#9012 force resolve package versions
  package.json
  yarn.lock
Labels: cross-team, ws-media

#9018 Fix PS Story Page tests
  cypress/integration/pages/storyPage/tests.js
  cypress/support/config/settings.js
Labels: cross-team, cypress

#8961 Reduced number of services running onDemandAudio E2Es
  cypress/support/config/settings.js
Labels: OD-radio, Recent Episodes Radio, blocked, cypress, podcasts, ws-media

#9011 Adds lang to podcast external links
  src/app/containers/PodcastExternalLinks/__snapshots__/index.test.jsx.snap
  src/app/containers/PodcastExternalLinks/index.jsx
  src/app/containers/PodcastExternalLinks/index.test.jsx
Labels: ws-media

#9021 On Demand Audio E2Es - Added wait before reload to allow cache to warm for retry on fail
  cypress/integration/pages/onDemandAudio/tests.js
Labels: Recent Episodes Radio, cross-team, cypress
