Repository bbc/simorgh, pull requests merged in 2021-05, with the labels that each got.

#9075 Re-enable inline link testing
  cypress/integration/pages/articles/tests.js
  cypress/support/config/settings.js
Labels: cross-team, optimo, technical-work, ws-articles

#9088 License exception added (TV4)
  license-exceptions.json
Labels: cross-team

#9089 Adds a reference for the local network configuration docs
  README.md
Labels: Documentation, cross-team

#9087 Cy.log to terminal on failure
  cypress/integration/pages/onDemandAudio/tests.js
  cypress/plugins/index.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: OD-radio, cross-team, cypress

#9093 force resolve transitive dependencies
  package.json
  yarn.lock
Labels: cross-team

#9083 Link to repo use guidelines from issue/PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cross-team

#9095 Migrate husky v4 to v6
  .husky/.gitignore
  .husky/post-merge
  .husky/pre-commit
  .husky/pre-push
  package.json
  yarn.lock
Labels: cross-team

#9072 Click tracking hook
  package.json
  src/app/hooks/useClickTracker/README.md
  src/app/hooks/useClickTracker/clickTypes.js
  src/app/hooks/useClickTracker/fixtureData/tori-51745682.json
  src/app/hooks/useClickTracker/index.jsx
  src/app/hooks/useClickTracker/index.test.jsx
  yarn.lock
Labels: cross-team

#9104 Update 3rd party non-major dependencies
  package.json
  scripts/bundleSize/bundleSizeConfig.js
  yarn.lock
Labels: cross-team, dependencies

#9108 Added +/- 1 tolerance in E2Es for Recent Episodes component
  cypress/integration/pages/onDemandAudio/tests.js
Labels: OD-radio, cross-team, cypress

#9114 fixes ATI s2/producerId not working for most services for event tracking
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/beacon/index.js
  src/app/contexts/EventTrackingContext/index.jsx
  src/app/contexts/EventTrackingContext/index.test.jsx
  src/app/hooks/useClickTrackerHandler/index.jsx
  src/app/hooks/useViewTracker/index.jsx
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
Labels: cross-team

#9115 fixes event tracking in top stories that have only 1 item
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/index.jsx
Labels: cross-team

#9113 add mostWatched ATI param functions to event tracking
  src/app/containers/ATIAnalytics/params/index.js
Labels: cross-team

#9116 Disable News service canonical tests on cookie banner
  cypress/integration/specialFeatures/cookieBanner/index.js
Labels: cross-team, cypress

#9112 Add '?site=test' query to front page AMP URLs in E2Es to prevent repeating application error
  cypress/support/helpers/runTestsForPage.js
Labels: ads, cross-team, cypress

#9118 add font preloads to storybook preview-head.html
  .storybook/buildFontPreloads.js
  .storybook/buildFontPreloads.test.js
  .storybook/preview-head.html
  .storybook/preview.js
  package.json
  yarn.lock
Labels: cross-team

#9124 fix chromatic consent banner snapshots
  .storybook/helpers/clearAppStorage.js
  .storybook/preview.js
  src/app/components/MediaPlayer/index.stories.jsx
  src/app/pages/LiveRadioPage/index.stories.jsx
  src/app/pages/OnDemandAudioPage/index.stories.jsx
Labels: cross-team

#9134 force resolve browserslist v4.16.5
  package.json
  yarn.lock
Labels: cross-team

#9133 force resolve multicast-dns v7.2.3
  package.json
  yarn.lock
Labels: cross-team

#9131 Add kyrgyz podcast translation
  src/app/lib/config/services/kyrgyz.js
Labels: podcasts
