Repository bbc/simorgh, pull requests merged in 2021-07, with the labels that each got.

#9215 Reserve additional 16px to prevent advert content shift
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/utilities/adSlotStyles.js
Labels: ads, cross-team

#9219 Add Ukrainian external links to podcast page
  data/ukrainian/podcasts/p09jsy3h.json
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/index.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/ukrainian.js
Labels: podcasts

#9222 upgrade babel packages
  license-exceptions.json
  package.json
  yarn.lock
Labels: cross-team

#9192 Synchronously re-render images that fail to load
  src/app/containers/ImageWithPlaceholder/index.jsx
  src/app/containers/ImageWithPlaceholder/index.test.jsx
Labels: cross-team

#9237 External Links for Russian Podcast
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/russian.js
Labels: BAU

#9238 Deploy topic tags to live
  package.json
  src/app/containers/RelatedTopics/__snapshots__/index.test.jsx.snap
  src/app/containers/RelatedTopics/index.jsx
  src/app/containers/RelatedTopics/index.test.jsx
  src/app/pages/ArticlePage/ArticlePage.jsx
  src/app/pages/MediaAssetPage/MediaAssetPage.jsx
  src/app/pages/PhotoGalleryPage/PhotoGalleryPage.jsx
  src/app/pages/StoryPage/StoryPage.jsx
  yarn.lock
Labels: cross-team

#9245 Dont render topic tags on sport
  src/app/pages/ArticlePage/ArticlePage.jsx
  src/app/pages/MediaAssetPage/MediaAssetPage.jsx
  src/app/pages/PhotoGalleryPage/PhotoGalleryPage.jsx
  src/app/pages/StoryPage/StoryPage.jsx
Labels: cross-team, high-priority

#9202 Add Most Read tests and print to console if no records
  cypress/integration/pages/mostReadPage/index.js
  cypress/integration/pages/mostReadPage/tests.js
  cypress/integration/pages/mostReadPage/testsForCanonicalOnly.js
  cypress/integration/pages/mostWatchedPage/tests.js
  cypress/support/config/settings.js
Labels: cypress, most-read, most-watched

#9216 Add index to social embeds
  data/mundo/articles/c20myn5q195o.json
  data/mundo/cpsAssets/noticias-america-latina-51518716.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/SocialEmbed/Cps/__snapshots__/index.test.jsx.snap
  src/app/containers/SocialEmbed/Cps/index.jsx
  src/app/containers/SocialEmbed/Cps/index.test.jsx
  src/app/containers/SocialEmbed/__snapshots__/index.test.jsx.snap
  src/app/containers/SocialEmbed/common/fixtures.js
  src/app/containers/SocialEmbed/common/testHelper.jsx
  src/app/containers/SocialEmbed/index.jsx
  src/app/containers/SocialEmbed/index.stories.jsx
  src/app/containers/SocialEmbed/index.test.jsx
  src/app/lib/config/toggles/README.md
  src/app/lib/config/toggles/__snapshots__/index.test.js.snap
  src/app/lib/config/toggles/liveConfig.js
  src/app/lib/config/toggles/localConfig.js
  src/app/lib/config/toggles/testConfig.js
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/routes/article/getInitialData/index.js
  src/app/routes/utils/sharedDataTransformers/addIndexesToEmbeds/index.js
  src/app/routes/utils/sharedDataTransformers/addIndexesToEmbeds/index.test.js
  src/app/routes/utils/sharedDataTransformers/index.js
Labels: cross-team

#9250 Adds fix for Russian Castbox podcast service link - Russian to English
  data/russian/podcasts/p05607v8.json
  data/russian/podcasts/p09nx6zm.json
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/russian.js
Labels: cross-team

#9248 Add topics path exception for cymrufyw
  src/app/containers/RelatedTopics/index.jsx
  src/app/containers/RelatedTopics/index.test.jsx
  src/app/lib/config/services/cymrufyw.js
Labels: cross-team

#9249 Increase tap target on footer links
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/app/components/Footer/Link/index.jsx
  src/app/containers/Footer/__snapshots__/index.test.jsx.snap
Labels: Refinement Needed, bug, ux, ws-articles

#9256 Change skip social embed id
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
Labels: cross-team, cypress

#9203 Cypress tests for Sports Tables
  cypress/integration/pages/storyPage/testsForAMPOnly.js
  cypress/support/config/settings.js
Labels: cypress

#9234 Adds gaelic/Naidheachdan translation to top stories & features analysis title in AMP
  data/naidheachdan/cpsAssets/57747079.json
  src/app/lib/config/services/naidheachdan.js
Labels: cross-team

#9265 Disable idt2 integration tests
  src/integration/pages/storyPage/canonicalIncludeTests.js
Labels: high-priority

#9260 Topic tags Cypress test
  cypress/integration/pages/testsForAllPages.js
Labels: cross-team, cypress

#9267 Remove added query 'site=test' from front page amp
  cypress/support/helpers/runTestsForPage.js
Labels: cross-team, cypress

#9268 Bump Babel
  package.json
  yarn.lock
Labels: dependencies

#9277 Disable newsround topic tags
  data/newsround/cpsAssets/23212028.json
  src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/newsround.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/sport.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
  src/app/pages/ArticlePage/ArticlePage.jsx
  src/app/pages/MediaAssetPage/MediaAssetPage.jsx
  src/app/pages/PhotoGalleryPage/PhotoGalleryPage.jsx
  src/app/pages/StoryPage/StoryPage.jsx
Labels: cross-team
