Repository bbc/simorgh, pull requests merged in 2022-06, with the labels that each got.

#10132 Clean up hindi experiment
  src/app/containers/CpsRecommendations/index.jsx
Labels: optimizely, ws-london

#10134 Fix topics page test - data structure different for cps and optimo articles
  cypress/integration/pages/topicPage/tests.js
Labels: cypress, ws-glasgow

#10142 Update Arabic and Hindi podcast promos
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/hindi.js
Labels: cross-team

#10143 Re-add ads rendering to Article pages on Test
  src/server/index.jsx
Labels: cross-team

#10146 Removes Confusing and Unnecessary Routes Utilities dirAlias
  dirAlias.js
  src/app/routes/article/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/getImageBlock/index.js
  src/app/routes/error/index.js
  src/app/routes/errorNoRouteMatch/index.js
  src/app/routes/home/index.js
  src/app/routes/idx/index.js
  src/app/routes/liveRadio/index.js
  src/app/routes/mostRead/index.js
  src/app/routes/mostWatched/index.js
  src/app/routes/onDemandRadio/index.js
  src/app/routes/onDemandTV/index.js
  src/app/routes/podcast/index.js
  src/app/routes/topic/index.js
Labels: cross-team

#10147 Revert Articles page adverts override
  src/server/index.jsx
Labels: cross-team

#10144 [WSTEAM1-21] - Ads style changes to Live + AMP
  src/app/containers/Ad/Amp/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/Amp/index.jsx
  src/app/containers/Ad/Canonical/index.jsx
  src/app/containers/Ad/__snapshots__/index.test.jsx.snap
  src/app/containers/Ad/utilities/adSlotStyles.js
Labels: ads

#10154 Revert "[WSTEAM1-55] - Article page `allowAdvertising` flag (#10150)"
  data/kyrgyz/articles/c88ld5g4xxxo.json
  src/app/pages/ArticlePage/ArticlePage.jsx
  src/app/pages/ArticlePage/fixtureData.js
  src/app/pages/ArticlePage/index.test.jsx
  src/app/routes/article/getInitialData/addMpuBlock/index.js
  src/app/routes/article/getInitialData/addMpuBlock/index.test.js
Labels: ads, optimo

#10157 [WSTEAM1-55] - Allow editorial ads toggle on Test for Optimo articles
  data/kyrgyz/articles/c88ld5g4xxxo.json
  src/app/pages/ArticlePage/ArticlePage.jsx
  src/app/routes/article/getInitialData/addMpuBlock/index.js
  src/app/routes/article/getInitialData/addMpuBlock/index.test.js
Labels: ads, optimo

#10158 WSTEAM1-89 Chameleon colour changes for article pages
  src/app/components/ErrorMain/__snapshots__/index.test.jsx.snap
  src/app/components/FrostedGlassPromo/__snapshots__/index.test.jsx.snap
  src/app/components/RadioSchedule/StartTime/__snapshots__/index.test.jsx.snap
  src/app/components/RadioSchedule/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleTimestamp/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsOnwardJourney/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/RecommendationsPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/RecommendationsPromo/index.jsx
  src/app/containers/CpsRecommendations/RecommendationsPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTable/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/EpisodeList/RecentAudioEpisodes/__snapshots__/index.test.jsx.snap
  src/app/containers/EpisodeList/RecentVideoEpisodes/__snapshots__/index.test.jsx.snap
  src/app/containers/FauxHeadline/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/Headings/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexPageSection/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/Canonical/Item/__snapshots__/index.test.jsx.snap
  src/app/containers/MostRead/Canonical/__snapshots__/LastUpdated.test.jsx.snap
  src/app/containers/OnDemandHeading/__snapshots__/index.test.jsx.snap
  src/app/containers/OnDemandParagraph/__snapshots__/index.test.jsx.snap
  src/app/containers/Paragraph/__snapshots__/index.test.jsx.snap
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/containers/RelatedTopics/__snapshots__/index.test.jsx.snap
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/Text/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead-grid/src/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead-headings/src/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead-headings/src/index.jsx
  src/app/legacy/psammead-paragraph/src/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead-paragraph/src/index.jsx
  src/app/legacy/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead-section-label/src/index.jsx
  src/app/legacy/psammead-section-label/src/titles.jsx
  src/app/legacy/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead-timestamp/src/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead-timestamp/src/index.jsx
  src/app/pages/ArticlePage/__snapshots__/index.test.jsx.snap
  src/app/pages/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostReadPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandAudioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/PhotoGalleryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: cross-team, ws-london

#10124 [WSTEAM1-10] - Experiment: 004_brasil_recommendations_experiment
  README.md
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/CpsRecommendations/RecommendationsPromoList/index.jsx
  src/app/containers/PageHandlers/withOptimizelyProvider/index.jsx
  src/app/lib/config/optimizely/index.js
  src/app/lib/utilities/getUrlHelpers/getRecommendationsUrl/index.js
  src/app/lib/utilities/getUrlHelpers/getRecommendationsUrl/index.test.js
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/index.test.jsx
  src/app/routes/cpsAsset/getInitialData/index.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.test.js
  webpack.config.client.js
Labels: Recommendations, optimizely, ws-london
