Repository bbc/simorgh, pull requests merged in 2022-04, with the labels that each got.

#10010 Topic page style updates
  src/app/components/Promo/image.jsx
  src/app/components/Promo/index.jsx
  src/app/pages/TopicPage/TopicGrid/index.jsx
  src/app/pages/TopicPage/TopicPage.jsx
Labels: ws-glasgow

#9937 Pagination Front End - Part 1
  src/app/lib/utilities/findNClosestIndicies/index.js
  src/app/lib/utilities/findNClosestIndicies/index.test.js
  src/app/pages/TopicPage/Pagination/buildBlocks.js
  src/app/pages/TopicPage/Pagination/buildBlocks.test.js
  src/app/pages/TopicPage/Pagination/icons.jsx
  src/app/pages/TopicPage/Pagination/index.jsx
  src/app/pages/TopicPage/Pagination/index.test.jsx
  src/app/pages/TopicPage/Pagination/pagination.stories.jsx
  src/app/pages/TopicPage/TopicPage.jsx
  src/app/pages/TopicPage/index.stories.jsx
  src/app/routes/topic/getInitialData/index.js
Labels: ws-glasgow

#10018 Add new Test article route regex
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
Labels: ws-london

#10024 Update Arabic and Turkish nav
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/turkce.js
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
Labels: cross-team

#10026 Adds total bytes to bundle analyser table column
  scripts/bundleSize/bundleSize.test.js
  scripts/bundleSize/getBundleData.js
  scripts/bundleSize/getBundleData.test.js
  scripts/bundleSize/index.js
Labels: ws-london

#10027 Add third party links to Hindi Din Bhar podcast
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/hindi.js
Labels: cross-team

#10021 [Do not merge] Pagination - Updated Design
  src/app/pages/TopicPage/Pagination/buildBlocks.js
  src/app/pages/TopicPage/Pagination/buildBlocks.test.js
  src/app/pages/TopicPage/Pagination/icons.jsx
  src/app/pages/TopicPage/Pagination/index.jsx
  src/app/pages/TopicPage/Pagination/index.test.jsx
Labels: ws-glasgow

#10023 High Impact Promo AMP Fix
  src/app/components/FrostedGlassPromo/FrostedGlassPanel.jsx
  src/app/components/FrostedGlassPromo/__snapshots__/index.test.jsx.snap
  src/app/components/FrostedGlassPromo/index.jsx
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsFeaturesAnalysis/index.test.jsx
Labels: ws-london

#9988 Remove skip on optimizely hindi experiment tests
  src/app/pages/StoryPage/index.test.jsx
Labels: ws-london

#10033 High Impact Promo Style Changes
  src/app/components/FrostedGlassPromo/FrostedGlassPanel.jsx
  src/app/components/FrostedGlassPromo/TimestampFooter.jsx
  src/app/components/FrostedGlassPromo/__snapshots__/index.test.jsx.snap
  src/app/components/FrostedGlassPromo/index.jsx
  src/app/components/FrostedGlassPromo/withData.jsx
Labels: ws-london

#10038 pass page param to bff in topic getinitialdata
  src/app/routes/topic/getInitialData/index.js
  src/app/routes/topic/getInitialData/index.test.js
  src/server/index.jsx
Labels: cross-team, ws-glasgow

#10039 make rel=amphtml link optional for page types
  src/app/containers/Metadata/index.jsx
  src/app/containers/Metadata/index.test.jsx
  src/app/containers/Metadata/utils.jsx
  src/app/pages/TopicPage/TopicPage.jsx
Labels: ws-glasgow

#10028 Update disclaimer to make it more accessible
  src/app/containers/Disclaimer/index.jsx
  src/app/containers/Disclaimer/index.stories.jsx
  src/app/containers/Disclaimer/index.test.jsx
  src/app/lib/config/services/russian.js
Labels: a11y, ws-london

#10042 High Impact Promo More Styling Adjustments
  src/app/components/FrostedGlassPromo/__snapshots__/index.test.jsx.snap
  src/app/components/FrostedGlassPromo/index.jsx
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: ws-london

#10041 Security vulnerability: Add async to resolutions
  .yarn/cache/async-npm-2.6.3-2de4150248-5e5561ff8f.zip
  package.json
  yarn.lock
Labels: security, cross-team

#10035 High impact promo go Live tidy up
  src/app/containers/CpsFeaturesAnalysis/fixtures.json
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsFeaturesAnalysis/index.stories.jsx
  src/app/containers/CpsFeaturesAnalysis/index.test.jsx
Labels: ws-london

#10046 Removes Release Tag Workflow
  .github/workflows/simorgh-create-github-release.yml
Labels: cross-team

#10050 Topic Page - All Translations
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
  src/app/pages/TopicPage/Pagination/index.jsx
Labels: ws-glasgow

#10037 External links and podcast promo for urdu & Hindi, Indonesia podcast promo update
  data/hindi/podcasts/p0c0530h.json
  data/urdu/podcasts/p0c04t7w.json
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/urdu.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/hindi.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/index.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/urdu.js
Labels: Good first issue

#10057 Topic Page - A11y Updates
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/pages/TopicPage/Pagination/index.jsx
Labels: ws-glasgow

#10055 Topic Pagination - Update Ellipsis Logic
  src/app/pages/TopicPage/Pagination/buildBlocks.js
  src/app/pages/TopicPage/Pagination/buildBlocks.test.js
  src/app/pages/TopicPage/Pagination/index.jsx
Labels: ws-glasgow

#10058 Set cache header
  src/server/index.jsx
  src/server/index.test.jsx
Labels: cross-team

#10047 High impact promo - Tablet grid layout
  src/app/components/FrostedGlassPromo/FrostedGlassPanel.jsx
  src/app/components/FrostedGlassPromo/__snapshots__/index.test.jsx.snap
  src/app/components/FrostedGlassPromo/index.jsx
  src/app/containers/CpsFeaturesAnalysis/fixtures.json
  src/app/containers/CpsFeaturesAnalysis/fixturesRtl.json
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsFeaturesAnalysis/index.stories.jsx
  src/app/containers/CpsFeaturesAnalysis/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: ws-london

#10056 Change Arabic's radio module header add external link to Urdu podcast
  src/app/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/lib/config/services/arabic.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/urdu.js
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
Labels: cross-team

#10054 Use system colours when using high contrast on PC
  src/app/pages/TopicPage/Pagination/index.jsx
Labels: a11y, ws-glasgow

#10060 support `new_topics` and `topics` routes
  src/app/routes/topic/index.js
  src/app/routes/utils/regex/index.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
Labels: ws-glasgow

#10062 Remove Optimizely logic for Hindi experiment
  src/app/components/ExperimentalEOJ/Promo/index.jsx
  src/app/components/ExperimentalEOJ/Promo/index.test.jsx
  src/app/components/ExperimentalEOJ/PromoList/index.jsx
  src/app/components/ExperimentalEOJ/helpers/fixtureData.js
  src/app/components/ExperimentalEOJ/index.jsx
  src/app/components/ExperimentalEOJ/index.stories.jsx
  src/app/components/ExperimentalEOJ/index.test.jsx
  src/app/containers/CpsRecommendations/RecommendationsPromoList/index.jsx
  src/app/containers/CpsRecommendations/SplitRecommendations/index.jsx
  src/app/containers/CpsRecommendations/SplitRecommendations/index.test.jsx
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/index.test.jsx
  src/app/routes/cpsAsset/getInitialData/addExperimentPlaceholderBlocks/index.js
  src/app/routes/cpsAsset/getInitialData/addExperimentPlaceholderBlocks/index.test.js
  src/app/routes/cpsAsset/getInitialData/index.js
Labels: optimizely, ws-london

#10063 Increase Tamil Most Read to 10
  src/app/lib/config/services/tamil.js
Labels: cross-team

#10066 chore: clean up data-hero
  src/app/containers/ImageWithPlaceholder/index.jsx
Labels: AMP, performance, ws-london

#10049 Add Most Read container to WS AMP (STY & article)
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/storyPage/testsForAMPOnly.js
  src/app/containers/MostRead/Amp/index.jsx
  src/app/containers/MostRead/Amp/index.test.jsx
  src/app/containers/MostRead/Canonical/Rank/index.jsx
  src/app/containers/MostRead/index.jsx
  src/app/containers/MostRead/index.test.jsx
  src/app/containers/MostRead/utilities/generateCPSHash.js
  src/app/containers/MostRead/utilities/generateCPSHash.test.js
  webpack.config.client.js
Labels: AMP, most-read, a11y-swarm, optimo, ws-london

#10069 Frosted Glass panel Lazy-loading
  src/app/components/FrostedGlassPromo/__snapshots__/index.test.jsx.snap
  src/app/components/FrostedGlassPromo/index.jsx
  src/app/components/FrostedGlassPromo/index.test.jsx
Labels: ws-london

#10072 Fix height of placeholder for high impact promo
  src/app/components/FrostedGlassPromo/FrostedGlassPanel.jsx
  src/app/components/FrostedGlassPromo/__snapshots__/index.test.jsx.snap
  src/app/components/FrostedGlassPromo/index.jsx
Labels: ws-london

#10071 Add condition to skip testing for sport and newsround service
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/storyPage/testsForAMPOnly.js
Labels: cypress, most-read

#10075 fix error with no content in live topics
  src/app/pages/TopicPage/TopicGrid/index.jsx
Labels: ws-glasgow
