Repository bbc/simorgh, pull requests merged in 2022-11, with the labels that each got.

#10384 NEWSWORLDSERVICE-1579 Adds new script for BFF_PATH detection and secret.env removal
  README.md
  package.json
  scripts/checkSecretEnvVariables.sh
Labels: technical-work

#10391 Add external links to Flora Carita podcast
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/indonesia.js
Labels: cross-team

#10402 Temporary patch/fix for Winston log deleted file descriptors
  .yarn/cache/winston-npm-3.7.2-5336ad5eff-f1f1a860d2.zip
  .yarn/cache/winston-npm-3.8.2-2035e9cac4-f7b901798b.zip
  .yarn/cache/winston-patch-745d73b4ce-29e1caa1c2.zip
  package.json
  patches/winston-file-descriptor.patch
  yarn.lock
Labels: technical-work

#10412 Remove elections tag from Brasil navigation
  src/app/lib/config/services/portuguese.ts
Labels: cross-team

#10405 Tests recommendations have images and title on every item (a bug that was fixed before)
  cypress/integration/pages/storyPage/tests.js
  cypress/support/config/settings.js
  cypress/support/helpers/runTestsForPage.js
Labels: cypress, Recommendations

#10417 Add Nepali election link to nav and updates for Ru Hi podcasts
  src/app/lib/config/services/hindi.ts
  src/app/lib/config/services/nepali.ts
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/russian.js
Labels: cross-team

#10416 Change apache license checker to `bbc/license-checker`
  .github/workflows/simorgh-misc-checks.yml
  .yarn/cache/@bbc-apache2-license-checker-npm-1.1.4-a1a1940cce-bc999b87dc.zip
  .yarn/cache/ansi-regex-npm-0.2.1-47771068a7-ce95ac031f.zip
  .yarn/cache/ansi-styles-npm-1.1.0-17dfaaf500-4f01de400e.zip
  .yarn/cache/chalk-npm-0.5.1-d4bf63a6e8-33eb9cf922.zip
  .yarn/cache/debuglog-npm-1.0.1-c553c84ea5-970679f2eb.zip
  .yarn/cache/has-ansi-npm-0.1.0-fe216ea97a-8eb68a066b.zip
  .yarn/cache/license-checker-npm-8.0.4-960a3aeb2d-192284d049.zip
  .yarn/cache/mkdirp-npm-0.3.5-73c410be57-5b7db0f7db.zip
  .yarn/cache/nopt-npm-2.2.1-00ee0d9eba-d4856b6035.zip
  .yarn/cache/npm-normalize-package-bin-npm-1.0.1-2cf38a5d95-ae7f15155a.zip
  .yarn/cache/read-installed-npm-4.0.3-10a38d88c6-44429cd208.zip
  .yarn/cache/read-package-json-npm-2.1.2-145139bcf5-56a2642851.zip
  .yarn/cache/readdir-scoped-modules-npm-1.1.0-651d6882ac-6d9f334e40.zip
  .yarn/cache/slide-npm-1.1.6-14e4650dea-5768635d22.zip
  .yarn/cache/strip-ansi-npm-0.3.0-c8917db171-c154768b85.zip
  .yarn/cache/supports-color-npm-0.2.0-b6e7d48cdb-7ec93a9241.zip
  .yarn/cache/treeify-npm-1.1.0-abf9292333-aa00dded22.zip
  .yarn/cache/util-extend-npm-1.0.3-410555399f-da57f399b3.zip
  CONTRIBUTING.md
  license-exceptions.json
  package.json
  yarn.lock
Labels: Do not merge
