Repository bbc/simorgh, pull requests merged in 2022-02, with the labels that each got.

#9827 Fix podcast position due to CPS providing xml
  src/app/routes/cpsAsset/getInitialData/insertPodcastPromo/index.js
  src/app/routes/cpsAsset/getInitialData/insertPodcastPromo/index.test.js
Labels: bug

#9824 Prevents Optimizely from sending events if variation key is null
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsFeaturesAnalysis/index.test.jsx
Labels: optimizely

#9834 Check Optimizely variation for page_view event
  src/app/containers/OptimizelyPageViewTracking/index.jsx
  src/app/containers/OptimizelyPageViewTracking/index.test.jsx
Labels: optimizely

#9829 Updates language variant to regex matching for topics
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
  src/server/local/index.js
Labels: cross-team, ws-glasgow

#9850 a11y violation fix for duplicate ID in top stories / features sections
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsTopStories/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsTopStories/index.jsx
  src/app/containers/StoryPromo/index.jsx
  src/app/containers/StoryPromo/index.test.jsx
  src/app/containers/StoryPromo/utilities/index.js
  src/app/containers/StoryPromo/utilities/index.test.js
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: cross-team

#9837 Optimizely Custom Click and View Attributes
  data/mundo/secondaryColumn/index.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/hooks/useClickTrackerHandler/index.jsx
  src/app/hooks/useClickTrackerHandler/index.test.jsx
  src/app/hooks/useViewTracker/index.jsx
  src/app/hooks/useViewTracker/index.test.jsx
Labels: optimizely, ws-london

#9857 Optimizely prelive changes
  src/app/containers/PageHandlers/withOptimizelyProvider/index.jsx
Labels: optimizely, ws-london

#9838 Add tracking to editorial onward journey
  src/app/components/ScrollablePromo/Promo/index.jsx
  src/app/components/ScrollablePromo/PromoList/index.jsx
  src/app/components/ScrollablePromo/__snapshots__/index.test.jsx.snap
  src/app/components/ScrollablePromo/fixtures.js
  src/app/components/ScrollablePromo/index.jsx
  src/app/components/ScrollablePromo/index.stories.jsx
  src/app/components/ScrollablePromo/index.test.jsx
  src/app/routes/article/getInitialData/index.js
  src/app/routes/utils/isListWithLink/index.js
  src/app/routes/utils/isListWithLink/index.test.js
Labels: ws-london

#9862 Fix event tracking on client side navigation
  src/app/lib/utilities/getToggles/index.js
  src/app/lib/utilities/getToggles/index.test.js
Labels: bug, ws-london

#9881 Update Russian nav to add Ukraine crisis item
  src/app/lib/config/services/russian.js
Labels: cross-team

#9877 Add experimental blocks to `pageData`
  data/hindi/cpsAssets/india-60426858.json
  src/app/lib/config/optimizely/experimentIds.js
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/routes/cpsAsset/getInitialData/addExperimentPlaceholderBlocks/index.js
  src/app/routes/cpsAsset/getInitialData/addExperimentPlaceholderBlocks/index.test.js
  src/app/routes/cpsAsset/getInitialData/index.js
Labels: ws-london

#9889 Topics - Responsive Images & WebP
  src/app/components/Promo/image.jsx
  src/app/pages/TopicPage/TopicGrid/index.stories.jsx
  src/app/pages/TopicPage/fixtures.js
Labels: ws-glasgow

#9906 Update Ukrainian and serbian nav bar to add Russia-Ukraine war topic
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/ukrainian.js
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
Labels: cross-team
