Repository bbc/simorgh, pull requests merged in 2022-03, with the labels that each got.

#9908 `url-parse` package update
  .yarn/cache/url-parse-npm-1.5.10-64fa2bcd6d-fbdba6b1d8.zip
  .yarn/cache/url-parse-npm-1.5.8-082ecb5a56-6f9e852809.zip
  package.json
  yarn.lock
Labels: cross-team

#9901 Adds ATI Tracking to Topics Page
  src/app/containers/ATIAnalytics/index.jsx
  src/app/containers/ATIAnalytics/params/index.js
  src/app/containers/ATIAnalytics/params/topicPage/buildParams.js
  src/app/containers/ATIAnalytics/params/topicPage/buildParams.test.js
  src/app/contexts/EventTrackingContext/index.jsx
  src/app/pages/TopicPage/TopicPage.jsx
  src/app/routes/topic/getInitialData/index.js
Labels: ws-glasgow

#9896 Update Live labels for Pashto and Nepali
  data/nepali/frontpage/index.json
  data/pashto/frontpage/index.json
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/pashto.js
Labels: cross-team

#9911 Update Persian nav to include Ukraine crisis link and update live badges for Nepali and Pidgin
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
Labels: cross-team

#9907 Temporarily catch ads errors
  cypress.json
  cypress/support/helpers/visitPage.js
Labels: cypress, ads, cross-team

#9898 Fix - new URL for news amp topic tag test
  cypress/integration/pages/frontPage/tests.js
  cypress/integration/pages/storyPage/tests.js
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
  cypress/integration/pages/testsForAllPages.js
  cypress/support/helpers/topicTagsTest.js
Labels: cypress, cross-team

#9915 fix for e2es - new url for failing topic tag test
  cypress/integration/pages/storyPage/tests.js
Labels: cypress, cross-team

#9917 Use relative URLs for media players
  cypress/support/config/envs.js
  src/app/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/index.jsx
  src/app/lib/utilities/getUrlHelpers/getEmbedUrl/index.js
  src/app/lib/utilities/getUrlHelpers/getEmbedUrl/index.test.js
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/index.test.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandAudioPage/OnDemandAudioPage.jsx
  src/app/pages/OnDemandAudioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandAudioPage/index.test.jsx
  src/app/pages/OnDemandTvPage/OnDemandTvPage.jsx
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: cross-team

#9924 fix tests failing on iframe
  cypress/integration/pages/articles/testsForCanonicalOnly.js
  cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
  cypress/integration/pages/onDemandAudio/tests.js
  cypress/integration/pages/onDemandTV/tests.js
Labels: cypress, cross-team, av-embeds

#9891 Add experiment blocks to `pageData`
  data/hindi/cpsAssets/india-60426858.json
  data/mundo/cpsAssets/23263889.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/lib/config/optimizely/index.js
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/routes/cpsAsset/getInitialData/addExperimentPlaceholderBlocks/index.js
  src/app/routes/cpsAsset/getInitialData/addExperimentPlaceholderBlocks/index.test.js
  src/app/routes/cpsAsset/getInitialData/index.js
Labels: optimizely, ws-london

#9923 Use disclaimer to promote the Russian Apps
  src/app/containers/Disclaimer/index.jsx
  src/app/containers/Disclaimer/index.stories.jsx
  src/app/containers/Disclaimer/index.test.jsx
  src/app/lib/config/services/russian.js
  src/app/pages/ArticlePage/ArticlePage.jsx
Labels: a11y, high-priority, a11y-swarm

#9922 Onward Journey Link Updates
  data/russian/cpsAssets/media-47937790.json
  data/russian/cpsAssets/news-60643006.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/ArticleFigure/__snapshots__/index.test.jsx.snap
  src/app/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/containers/IndexPageSection/index.jsx
  src/app/containers/IndexPageSection/utilities/filterAllowedItems.test.jsx
  src/app/containers/InlineLink/__snapshots__/index.test.jsx.snap
  src/app/containers/InlineLink/index.jsx
  src/app/containers/PodcastPromo/__snapshots__/index.test.jsx.snap
  src/app/containers/PodcastPromo/shared.js
  src/app/containers/PodcastPromo/shared.test.js
  src/app/containers/RelatedTopics/__snapshots__/index.test.jsx.snap
  src/app/containers/RelatedTopics/index.jsx
  src/app/containers/RelatedTopics/index.test.jsx
  src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/lib/utilities/getStoryPromoInfo/index.jsx
  src/app/lib/utilities/getStoryPromoInfo/index.test.jsx
  src/app/lib/utilities/makeRelativeUrlPath/index.js
  src/app/lib/utilities/makeRelativeUrlPath/index.test.js
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
Labels: high-priority

#9876 fix placeholder button should be on the left of the media-player.
  src/app/components/MediaPlayer/Placeholder/__snapshots__/index.test.jsx.snap
  src/app/components/MediaPlayer/Placeholder/index.jsx
  src/app/components/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
Labels: bug, ws-london

#9847 Add data-hero attribute to Simorgh's amp-img
  src/app/containers/ImageWithPlaceholder/index.jsx
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
Labels: AMP, performance, ws-london

#9920 Update Hindi recommendation titles
  src/app/lib/config/services/hindi.js
Labels: cross-team

#9910 Adds Chartbeat Analytics to Topic Page
  src/app/containers/ChartbeatAnalytics/utils/index.js
  src/app/containers/ChartbeatAnalytics/utils/index.test.js
  src/app/pages/TopicPage/TopicPage.jsx
Labels: ws-glasgow

#9931 Add MetadataContainer and LinkedData to Topic page
  src/app/pages/TopicPage/TopicPage.jsx
  src/app/routes/topic/getInitialData/index.js
  src/app/routes/topic/getInitialData/index.test.js
Labels: ws-glasgow

#9879 Update ATI ContentId logic for CPS assets
  data/gahuza/legacyAssets/video/2016/01/160108_australia_fire_video.json
  data/pidgin/cpsAssets/tori-49450859.json
  src/app/containers/ATIAnalytics/index.test.jsx
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.js
  src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/contexts/EventTrackingContext/index.test.jsx
  src/app/lib/analyticsUtils/index.js
  src/app/lib/analyticsUtils/index.test.js
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: Good first issue, cross-team, ws-london

#9934 Update GIST's text and bullet colors
  src/app/containers/Gist/__snapshots__/index.test.jsx.snap
  src/app/containers/Gist/index.jsx
  src/app/containers/Gist/index.stories.jsx
Labels: Good first issue, ux, ws-london

#9935 Tests the Hearken and Riddle includes exist and are visible on the test asset
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
Labels: cypress, includes, cross-team

#9938 Add Optimizely tracking on control variation Hindi experiment.
  src/app/containers/CpsRecommendations/RecommendationsPromoList/index.jsx
  src/app/containers/CpsRecommendations/index.jsx
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/index.test.jsx
Labels: optimizely

#9945 Add external links to BBC Indonesia podcast
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/indonesia.js
Labels: cross-team

#9939 Remove hardcoded Optimizely experiment ID
  src/app/containers/OptimizelyPageViewTracking/index.jsx
  src/app/hooks/useOptimizelyScrollDepth/index.jsx
  src/app/hooks/useOptimizelyScrollDepth/index.test.jsx
Labels: optimizely, ws-london

#9949 Increase Disclaimer line-height
  src/app/containers/Disclaimer/index.jsx
Labels: ux, ws-london

#9933 Add Hindi experiment Related Content - Var B
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/CpsRelatedContent/index.test.jsx
  src/app/pages/StoryPage/StoryPage.jsx
Labels: optimizely, ws-london

#9953 Update Russian nav to change Ukraine war text link
  src/app/lib/config/services/russian.js
Labels: cross-team

#9894 Add Hindi Experiment variation A
  src/app/containers/CpsRecommendations/RecommendationsPromoList/index.jsx
  src/app/containers/CpsRecommendations/SplitRecommendations/index.jsx
  src/app/containers/CpsRecommendations/SplitRecommendations/index.test.jsx
  src/app/containers/CpsRecommendations/index.jsx
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/index.test.jsx
Labels: a11y, ux, optimizely, ws-london

#9954 increase line-height up to 600px breakpoint
  src/app/containers/Disclaimer/index.jsx
Labels: ux, ws-london

#9951 Optimizely article complete tracking
  src/app/containers/OptimizelyArticleCompleteTracking/index.jsx
  src/app/containers/OptimizelyArticleCompleteTracking/index.test.jsx
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: optimizely, ws-london

#9886 EOJ recommendation variation_C
  src/app/components/ExperimentalEOJ/Promo/index.jsx
  src/app/components/ExperimentalEOJ/Promo/index.test.jsx
  src/app/components/ExperimentalEOJ/PromoList/index.jsx
  src/app/components/ExperimentalEOJ/helpers/fixtureData.js
  src/app/components/ExperimentalEOJ/index.jsx
  src/app/components/ExperimentalEOJ/index.stories.jsx
  src/app/components/ExperimentalEOJ/index.test.jsx
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/fixtureData/recommendations.ltr.json
  src/app/pages/StoryPage/index.test.jsx
Labels: a11y-swarm, optimizely

#9955 Add experimental blocks to CPS `pageData` for Optimizely experiment
  src/app/routes/cpsAsset/getInitialData/index.js
Labels: optimizely, ws-london

#9959 Update Gujarati and Mundo navs to replace long URL topics
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/mundo.js
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team

#9967 Updates a11y device cross testing docs
  docs/A11y-Testing-Cross-Device.md
Labels: Documentation, cross-team

#9964 Config value for Optimizely view/click attribute
  src/app/components/ExperimentalEOJ/index.jsx
  src/app/components/ExperimentalEOJ/index.test.jsx
  src/app/hooks/useClickTrackerHandler/index.jsx
  src/app/hooks/useClickTrackerHandler/index.test.jsx
  src/app/hooks/useViewTracker/index.jsx
  src/app/hooks/useViewTracker/index.test.jsx
  src/app/lib/config/optimizely/index.js
Labels: optimizely, ws-london

#9965 Optimizely - split recs skip link fix
  src/app/containers/CpsRecommendations/SplitRecommendations/index.test.jsx
  src/app/containers/CpsRecommendations/index.jsx
Labels: optimizely, ws-london

#9973 Hindi Var C - blocks check
  src/app/components/ExperimentalEOJ/index.jsx
  src/app/components/ScrollablePromo/index.jsx
Labels: optimizely, ws-london

#9976 Update podcast links and articles podcast promotion - Persian
  src/app/lib/config/services/persian.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/persian.js
Labels: cross-team

#9977 Variation_C english storybook
  src/app/components/ExperimentalEOJ/index.stories.jsx
Labels: a11y

#9974 Add a11y logic to topic page
  src/app/pages/TopicPage/TopicGrid/index.jsx
  src/app/pages/TopicPage/TopicPage.jsx
  src/app/pages/TopicPage/TopicPromo/index.jsx
  src/app/pages/TopicPage/fixtures.js
  src/app/pages/TopicPage/index.test.jsx
Labels: ws-glasgow

#9975 Onward journey metadata display updates
  data/pidgin/articles/c1x0rq3r97ko.json
  data/pidgin/articles/cnd6yxmxvp2o.json
  data/pidgin/articles/crrrkxz2k0ko.json
  src/app/components/ScrollablePromo/Promo/index.jsx
  src/app/components/ScrollablePromo/Promo/index.test.jsx
  src/app/components/ScrollablePromo/__snapshots__/index.test.jsx.snap
  src/app/components/ScrollablePromo/helpers/fixtureData.js
  src/app/components/ScrollablePromo/index.jsx
  src/app/components/ScrollablePromo/index.stories.jsx
  src/app/components/ScrollablePromo/index.test.jsx
  src/app/containers/ArticleRelatedContent/index.jsx
  src/app/containers/ArticleRelatedContent/index.test.jsx
Labels: a11y-swarm, ws-london

#9991 fix: Sanitise aria-labelledBy
  src/app/components/ScrollablePromo/__snapshots__/index.test.jsx.snap
  src/app/components/ScrollablePromo/index.jsx
Labels: bug, a11y

#9990 Fix and logs for failing iframe test (OD TV and Audio)
  cypress/integration/pages/onDemandAudio/tests.js
  cypress/integration/pages/onDemandTV/tests.js
Labels: cypress, cross-team

#9919 Toggles preload for Article canonical [needs change freeze]
  src/app/pages/ArticlePage/ArticlePage.jsx
  src/integration/pages/articles/news/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/amp.test.js.snap
Labels: performance, ws-london

#9999 lazy load all but first topics promos
  src/app/pages/TopicPage/TopicGrid/index.jsx
  src/app/pages/TopicPage/TopicPromo/index.jsx
  src/app/pages/TopicPage/TopicPromo/index.test.jsx
Labels: ws-glasgow

#9994 Enables Winning Improved Promo Variant on Test and Local
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsFeaturesAnalysis/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: optimizely, ws-london

#9968 Adds Optimizely Documentation
  README.md
  src/app/hooks/useClickTrackerHandler/README.md
  src/app/hooks/useOptimizelyScrollDepth/README.md
  src/app/hooks/useOptimizelyVariation/README.md
  src/app/hooks/useViewTracker/README.md
Labels: Documentation, cross-team, optimizely, ws-london

#9989 Update accessibility styling on topic pages
  src/app/components/Promo/a.jsx
  src/app/pages/TopicPage/TopicTitle/index.jsx
Labels: a11y, ws-glasgow
