Repository bbc/simorgh, pull requests merged in 2022-07, with the labels that each got.

#10167 Add external links to BBC Hindi podcast
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/hindi.js
Labels: cross-team

#10169 Update nav video links to topics for Brasil, Korean and Tamil
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/tamil.js
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
Labels: cross-team

#10181 Update russian disclaimer to promote newsletter
  src/app/lib/config/services/russian.js
Labels: cross-team

#10177 [WSTEAM1-86] Switch recommendations endpoint
  src/app/lib/utilities/getUrlHelpers/getRecommendationsUrl/index.js
  src/app/lib/utilities/getUrlHelpers/getRecommendationsUrl/index.test.js
  src/app/pages/StoryPage/index.test.jsx
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.test.js
Labels: cross-team, ws-london

#10171 Check Belfrage fallback status
  cypress/integration/pages/topicPage/tests.js
  cypress/support/commands/application.js
Labels: cypress, cross-team

#10186 Preroll ads test change to Mundo (from Russian)
  cypress/integration/specialFeatures/prerollAds/config.js
Labels: cypress, cross-team

#10188 Converts Absolute URL's to Relative in Frosted Glass Promos
  src/app/components/FrostedGlassPromo/__snapshots__/index.test.jsx.snap
  src/app/components/FrostedGlassPromo/index.jsx
  src/app/components/FrostedGlassPromo/index.test.jsx
Labels: cross-team

#10190 Update external links for Hindi and Urdu podcasts
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/hindi.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/urdu.js
Labels: cross-team

#10189 Add more Topics URLs (RTL, variant)
  cypress/support/config/settings.js
Labels: cypress, ws-glasgow

#10191 Change podcast promotion on Hindi article pages
  src/app/lib/config/services/hindi.js
Labels: cross-team

#10202 Add aditional links to Hindi podcast
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/hindi.js
Labels: cross-team

#10161 Fixed topic page URL added to cypress settings
  cypress/support/config/settings.js
Labels: cypress, ws-glasgow

#10211 Force cache to miss on topics pages to get fresh data (fixes failing tests)
  cypress/integration/pages/topicPage/index.js
  cypress/integration/pages/topicPage/tests.js
Labels: cypress, cross-team
