Repository bbc/simorgh, pull requests merged in 2022-09, with the labels that each got.

#10276 Add external links to Brasil podcast
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/portuguese.js
Labels: cross-team

#10277 Log topics page SIMORGH_DATA when number of promos on page does not match number expected from BFF data
  cypress/integration/pages/topicPage/tests.js
  cypress/plugins/index.js
Labels: cypress, ws-glasgow

#10278 WSTEAM1-47 - Embed consent banner a11y fixes
  src/app/components/EmbedConsentBanner/ConsentBanner.styles.tsx
  src/app/components/EmbedConsentBanner/ConsentBanner.test.tsx
  src/app/components/EmbedConsentBanner/ConsentBanner.tsx
  src/app/components/EmbedConsentBanner/__snapshots__/index.test.tsx.snap
Labels: a11y

#10298 Update Brasil story page podcast promo and new podcast external links
  src/app/lib/config/services/portuguese.ts
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/portuguese.js
Labels: cross-team
