Repository bbc/simorgh, pull requests merged in 2022-05, with the labels that each got.

#10076 Update Vietnamese most watched page heading
  src/app/lib/config/services/vietnamese.js
Labels: cross-team

#10077 High impact promo placeholder padding fix
  src/app/components/FrostedGlassPromo/__snapshots__/index.test.jsx.snap
  src/app/components/FrostedGlassPromo/index.jsx
Labels: ws-london

#10065 Topic Page Tests
  a11y.js
  cypress/integration/pages/topicPage/index.js
  cypress/integration/pages/topicPage/tests.js
  cypress/support/config/envs.js
  cypress/support/config/settings.js
  src/app/pages/TopicPage/TopicGrid/index.jsx
Labels: cypress, ws-glasgow

#10059 add `Simorgh/ws-web-rendering` user agent to includes fetch
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/fetchMarkup/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/fetchMarkup/index.test.js
Labels: technical-work

#10079 fix fallback for empty mostread array
  src/app/containers/MostRead/Amp/index.jsx
  src/app/containers/MostRead/Amp/index.test.jsx
Labels: bug, AMP, most-read

#10090 [WSTEAM1-48] No-cookie YouTube embed
  data/mundo/cpsAssets/noticias-56669604.json
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: cross-team, ws-london

#10083 Remove margin from most read title
  src/app/pages/StoryPage/StoryPage.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: AMP, ws-articles, most-read

#10091 Remove `new_articles` route check
  src/app/routes/utils/fetchPageData/index.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
Labels: ws-london

#10092 Add most read cache to use in amp pages
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  src/app/containers/MostRead/index.jsx
Labels: AMP, most-read, ws-london

#10082 Topic page pagination tests (RTL and LTR)
  cypress/integration/pages/topicPage/tests.js
Labels: cypress, ws-glasgow

#10095 Update Persian podcast promo and add third party link to radio podcast
  data/persian/podcasts/p02pc9mc.json
  src/app/lib/config/services/persian.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/persian.js
Labels: cross-team

#10108 Remove slash from endpoint
  envConfig/live.env
  envConfig/test.env
Labels: most-read, ws-london

#10114 Fix: most read for optimo articles
  src/app/containers/MostRead/Amp/index.jsx
Labels: bug, AMP, most-read, optimo, ws-london

#10113 Update time stamp prefix for Arabic
  src/app/lib/config/services/arabic.js
Labels: cross-team

#10115 Replace Translations For Recommendation Title
  src/app/containers/CpsRecommendations/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsRecommendations/index.test.jsx
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/turkce.js
Labels: Recommendations

#10118 Render secondary column on CSP pages
  src/app/containers/MostRead/index.jsx
  src/app/containers/MostRead/index.test.jsx
  src/app/routes/cpsAsset/utils/getAdditionalPageData.js
  src/app/routes/cpsAsset/utils/getAdditionalPageData.test.js
Labels: AMP, cross-team

#10121 Clean up `audit-ci.json` allowlist
  audit-ci.json
Labels: cross-team

#10112 Topic pages - script switch Cypress tests
  cypress/integration/pages/topicPage/tests.js
  cypress/support/config/settings.js
Labels: cypress, ws-glasgow

#10117 check most read list has hrefs
  cypress/integration/pages/articles/testsForAMPOnly.js
  cypress/integration/pages/storyPage/testsForAMPOnly.js
Labels: cypress, ws-london

#10122 Add external links to Kyrgyz podcast
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/kyrgyz.js
Labels: cross-team

#10093 [WSTEAM1-53 + WSTEAM1-54] - Optimo articles ad support spike
  data/kyrgyz/articles/c88ld5g4xxxo.json
  src/app/pages/ArticlePage/ArticlePage.jsx
  src/app/routes/article/getInitialData/addMpuBlock/index.js
  src/app/routes/article/getInitialData/addMpuBlock/index.test.js
  src/app/routes/article/getInitialData/index.js
Labels: ads, optimo, ws-london

#10123 Article page `showAdsBasedOnLocation` test
  src/server/index.jsx
Labels: cross-team

#10125 Update video links to topics for Bengali, Japanese, Nepali and Thai
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/thai.js
Labels: cross-team

#10126 colour for fancy promo's visited link
  src/app/components/FrostedGlassPromo/index.jsx
Labels: a11y

#10127 Revert "bbc/article-page-ad-header-test"
  src/server/index.jsx
Labels: cross-team

#10110 Fix Webpack Bundle Size for Psammead Migration [WSTEAMA-51]
  audit-ci.json
  package.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/lib/config/services/afaanoromoo.js
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/amharic.js
  src/app/lib/config/services/arabic.js
  src/app/lib/config/services/archive.js
  src/app/lib/config/services/azeri.js
  src/app/lib/config/services/bengali.js
  src/app/lib/config/services/burmese.js
  src/app/lib/config/services/cymrufyw.js
  src/app/lib/config/services/gahuza.js
  src/app/lib/config/services/gujarati.js
  src/app/lib/config/services/hausa.js
  src/app/lib/config/services/hindi.js
  src/app/lib/config/services/igbo.js
  src/app/lib/config/services/indonesia.js
  src/app/lib/config/services/japanese.js
  src/app/lib/config/services/korean.js
  src/app/lib/config/services/kyrgyz.js
  src/app/lib/config/services/marathi.js
  src/app/lib/config/services/mundo.js
  src/app/lib/config/services/naidheachdan.js
  src/app/lib/config/services/nepali.js
  src/app/lib/config/services/news.js
  src/app/lib/config/services/newsround.js
  src/app/lib/config/services/pashto.js
  src/app/lib/config/services/persian.js
  src/app/lib/config/services/pidgin.js
  src/app/lib/config/services/portuguese.js
  src/app/lib/config/services/punjabi.js
  src/app/lib/config/services/russian.js
  src/app/lib/config/services/scotland.js
  src/app/lib/config/services/serbian.js
  src/app/lib/config/services/sinhala.js
  src/app/lib/config/services/somali.js
  src/app/lib/config/services/sport.js
  src/app/lib/config/services/swahili.js
  src/app/lib/config/services/tamil.js
  src/app/lib/config/services/telugu.js
  src/app/lib/config/services/thai.js
  src/app/lib/config/services/tigrinya.js
  src/app/lib/config/services/turkce.js
  src/app/lib/config/services/ukchina.js
  src/app/lib/config/services/ukrainian.js
  src/app/lib/config/services/urdu.js
  src/app/lib/config/services/uzbek.js
  src/app/lib/config/services/vietnamese.js
  src/app/lib/config/services/yoruba.js
  src/app/lib/config/services/zhongwen.js
Labels: technical-work, cross-team
