Repository bbc/simorgh, pull requests merged in 2022-01, with the labels that each got.

#9764 Updates snapshots with new copyright text
  src/app/Layouts/__snapshots__/defaultPageWrapper.test.jsx.snap
  src/integration/pages/articles/news/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/news/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/amp.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team

#9719 Updates deprecated JS listeners in useMediaQuery hook [DNM]
  src/app/hooks/useMediaQuery/index.jsx
Labels: cross-team

#9754 Update Russian config to fix Features / Analysis title
  src/app/lib/config/services/russian.js
Labels: cross-team

#9658 Optimizley Initial Integration for High Impact Promo Experiment
  .yarn/cache/@optimizely-js-sdk-datafile-manager-npm-0.8.1-3095e6989d-762e876a3d.zip
  .yarn/cache/@optimizely-js-sdk-event-processor-npm-0.8.2-657a66c72d-f0eda01555.zip
  .yarn/cache/@optimizely-js-sdk-logging-npm-0.1.0-43f6c5e030-b1d2de26cf.zip
  .yarn/cache/@optimizely-js-sdk-utils-npm-0.4.0-ebc6886a07-899877189e.zip
  .yarn/cache/@optimizely-optimizely-sdk-npm-4.7.0-a38d44b06a-311aae2e1a.zip
  .yarn/cache/@optimizely-react-sdk-npm-2.7.0-045f933ced-f950df837f.zip
  .yarn/cache/murmurhash-npm-0.0.2-f0ae55780b-e06d1e7cfd.zip
  .yarn/cache/utility-types-npm-3.10.0-747e7c6549-8f274415c6.zip
  envConfig/live.env
  envConfig/local.env
  envConfig/test.env
  package.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/CpsFeaturesAnalysis/__snapshots__/index.test.jsx.snap
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsFeaturesAnalysis/index.stories.jsx
  src/app/containers/CpsFeaturesAnalysis/index.test.jsx
  src/app/containers/PageHandlers/withOptimizelyProvider/index.jsx
  src/app/containers/PageHandlers/withOptimizelyProvider/index.test.jsx
  src/app/hooks/useOptimizelyVariation/index.jsx
  src/app/hooks/useOptimizelyVariation/index.test.jsx
  src/app/pages/ArticlePage/index.jsx
  src/app/pages/ArticlePage/index.stories.jsx
  src/app/pages/StoryPage/index.jsx
  src/app/pages/StoryPage/index.stories.jsx
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
  yarn.lock
Labels: optimizely

#9773 Adds Optimizely log end point to list of CSP directives
  src/server/utilities/cspHeader/index.js
  src/server/utilities/cspHeader/index.test.js
Labels: optimizely

#9776 Update Persian podcast promo and Afrique's nav bar
  src/app/lib/config/services/afrique.js
  src/app/lib/config/services/persian.js
  src/integration/pages/featureIdxPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/canonical.test.js.snap
Labels: cross-team

#9743 Adds Optimizely Mobile Integration
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsFeaturesAnalysis/index.test.jsx
  src/app/hooks/useOptimizelyVariation/index.jsx
Labels: cross-team

#9799 Re-enables optimizely on test env
  envConfig/test.env
Labels: cross-team

#9748 Optimizely Events Integration
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/CpsFeaturesAnalysis/index.test.jsx
  src/app/containers/StoryPromo/useCombinedClickTrackerHandler.js
  src/app/hooks/useClickTrackerHandler/index.jsx
  src/app/hooks/useClickTrackerHandler/index.test.jsx
  src/app/hooks/useViewTracker/index.jsx
Labels: cross-team, optimizely

#9757 Optimizely Cookie
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/CpsFeaturesAnalysis/index.stories.jsx
  src/app/containers/PageHandlers/withOptimizelyProvider/getOptimizelyUserId/index.js
  src/app/containers/PageHandlers/withOptimizelyProvider/getOptimizelyUserId/index.test.js
  src/app/containers/PageHandlers/withOptimizelyProvider/index.jsx
  src/app/containers/PageHandlers/withOptimizelyProvider/index.test.jsx
  src/app/pages/ArticlePage/index.jsx
  src/app/pages/ArticlePage/index.stories.jsx
  src/app/pages/StoryPage/index.jsx
  src/app/pages/StoryPage/index.stories.jsx
Labels: cross-team, optimizely

#9786 Send nations_producer to ATI when given
  data/news/articles/c0g992jmmkko.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/containers/ATIAnalytics/atiUrl/index.js
  src/app/containers/ATIAnalytics/params/article/buildParams.js
  src/app/containers/ATIAnalytics/params/article/buildParams.test.js
  src/app/containers/ATIAnalytics/params/index.test.js
  src/app/lib/analyticsUtils/article/index.js
  src/app/lib/analyticsUtils/article/index.test.js
Labels: analytics, cross-team

#9782 Article related content
  data/afrique/articles/c7yn6nznljdo.json
  data/pidgin/articles/c1x0rq3r97ko.json
  src/app/containers/ArticleRelatedContent/__snapshots__/index.test.jsx.snap
  src/app/containers/ArticleRelatedContent/fixtures.js
  src/app/containers/ArticleRelatedContent/index.jsx
  src/app/containers/ArticleRelatedContent/index.test.jsx
  src/app/containers/CpsOnwardJourney/index.jsx
  src/app/containers/CpsRelatedContent/RelatedContentPromo/index.jsx
  src/app/containers/CpsRelatedContent/RelatedContentPromoList/index.jsx
  src/app/containers/CpsRelatedContent/index.jsx
  src/app/containers/ImageWithPlaceholder/index.jsx
  src/app/containers/StoryPromo/index.jsx
  src/app/pages/ArticlePage/ArticlePage.jsx
  src/app/pages/ArticlePage/ArticlePageGrid.jsx
  src/app/pages/ArticlePage/index.stories.jsx
Labels: a11y-swarm

#9817 opera mini extreme mode style fix
  src/app/components/ScrollablePromo/PromoList/index.jsx
  src/app/components/ScrollablePromo/__snapshots__/index.test.jsx.snap
Labels: bug, ux

#9808 Moves Optimizely Mobile Detection To HOC
  src/app/containers/CpsFeaturesAnalysis/index.jsx
  src/app/containers/PageHandlers/withOptimizelyProvider/index.jsx
Labels: optimizely

#9826 Social embed E2E test failing
  cypress/integration/pages/storyPage/testsForCanonicalOnly.js
Labels: bug, cross-team

#9774 Fix amp media player placeholder
  src/app/lib/utilities/ichefURL/index.js
  src/app/lib/utilities/ichefURL/index.test.js
  src/app/lib/utilities/srcSet/index.js
  src/app/lib/utilities/srcSet/index.test.js
Labels: bug, Good first issue
