Repository bbc/simorgh, pull requests merged in 2022-08, with the labels that each got.

#10218 Cy.go('back') moved to beginning of next test
  cypress/integration/pages/topicPage/tests.js
Labels: cypress, cross-team

#10219 Removes the Pidgin topics page URL with Pidgin Minute causing test failures
  cypress/support/config/settings.js
Labels: cypress, cross-team

#10220 Test setting `x-frame-options` and `Cross Domain` headers for Article embeds
  src/server/index.jsx
Labels: cross-team

#10223 Revert "Test setting `x-frame-options` and `Cross Domain` headers for Article embeds (#10220)"
  src/server/index.jsx
Labels: cross-team

#10228 Update Swahili nav to add elections link
  src/app/lib/config/services/swahili.js
Labels: cross-team

#10256 Wakey wakey topics 🌤️
  cypress/integration/application/index.js
  cypress/integration/pages/topicPage/index.js
  cypress/integration/pages/topicPage/tests.js
Labels: ws-glasgow

#10262 [NEWSWORLDSERVICE-1582] Update Cache-Control header in sw.js
  src/server/index.jsx
  src/server/index.test.jsx
Labels: cross-team

#10270 Improved types for `altCalendar`, `brandSVG` and `fonts` in ServiceConfigs
  src/app/models/types/serviceConfig.ts
Labels: cross-team

#10275 Update Hindi nav to add podcast
  src/app/lib/config/services/hindi.ts
Labels: cross-team
