Repository bbc/simorgh, pull requests merged in 2023-02, with the labels that each got.

#10577 Update consent banner button translation for Persian
  src/app/lib/config/services/persian.ts
Labels: cross-team

#10557 WSTEAM1-143 Adds translation fields for upcoming rec services
  src/app/lib/config/services/afrique.ts
  src/app/lib/config/services/bengali.ts
  src/app/lib/config/services/korean.ts
  src/app/lib/config/services/marathi.ts
  src/app/lib/config/services/persian.ts
  src/app/lib/config/services/pidgin.ts
  src/app/lib/config/services/tamil.ts
  src/app/lib/config/services/thai.ts
  src/app/lib/config/services/vietnamese.ts
Labels: Do not merge, ws-london

#10550 Update to React 18
  .yarn/cache/@testing-library-react-npm-12.1.5-745f86e555-4abd049040.zip
  .yarn/cache/@testing-library-react-npm-13.4.0-eaa652c0f5-51ec548c1f.zip
  .yarn/cache/@testing-library-user-event-npm-13.5.0-1ff89b703a-16319de685.zip
  .yarn/cache/@testing-library-user-event-npm-14.4.3-2d1a75355f-852c48ea6d.zip
  .yarn/cache/@types-react-dom-npm-17.0.17-edb158f2b2-23caf98aa0.zip
  .yarn/cache/@types-react-npm-17.0.49-7408ac9c32-e2e8001bb1.zip
  .yarn/cache/react-dom-npm-17.0.2-f551215af1-1c1eaa3bca.zip
  .yarn/cache/react-dom-npm-18.2.0-dd675bca1c-7d323310be.zip
  .yarn/cache/react-is-npm-16.13.1-a9b9382b4f-f7a19ac349.zip
  .yarn/cache/react-is-npm-18.2.0-0cc5edb910-e72d0ba81b.zip
  .yarn/cache/react-npm-17.0.2-99ba37d931-b254cc17ce.zip
  .yarn/cache/react-npm-18.2.0-1eae08fee2-88e38092da.zip
  .yarn/cache/react-shallow-renderer-npm-16.14.1-b8a4f845ff-f344c663c4.zip
  .yarn/cache/react-shallow-renderer-npm-16.15.0-cf95219885-6052c7e3e9.zip
  .yarn/cache/react-test-renderer-npm-17.0.2-1086717127-e6b5c6ed2a.zip
  .yarn/cache/react-test-renderer-npm-18.2.0-cdc6051330-6b6980ced9.zip
  .yarn/cache/scheduler-npm-0.20.2-90beaecfba-c4b35cf967.zip
  .yarn/cache/scheduler-npm-0.23.0-a379a6bc3b-d79192eeaa.zip
  package.json
  scripts/bundleSize/bundleSizeConfig.js
  src/app/hooks/useClickTrackerHandler/index.test.jsx
  src/app/hooks/useOptimizelyScrollDepth/index.jsx
  src/app/legacy/components/MediaPlayer/Message/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/ConsentBanner/a11y.test.jsx
  src/app/legacy/containers/Header/index.test.jsx
  src/app/legacy/containers/MostRead/Amp/index.test.jsx
  src/app/legacy/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
  src/app/legacy/containers/PageHandlers/withLoading/index.test.jsx
  src/app/legacy/containers/WebVitals/index.jsx
  src/app/legacy/containers/WebVitals/index.test.jsx
  src/app/legacy/psammead/psammead-media-player/src/Message/__snapshots__/index.test.jsx.snap
  src/app/pages/ArticlePage/index.test.jsx
  src/app/pages/ErrorPage/__snapshots__/index.test.jsx.snap
  src/app/pages/FeatureIdxPage/index.test.jsx
  src/client.js
  src/client.test.jsx
  src/server/Document/__snapshots__/component.test.jsx.snap
  yarn.lock
Labels: Do not merge

#10504 WSTEAMA-38: Update media icons to Topics promos
  src/app/legacy/components/MediaPlayer/Placeholder/__snapshots__/index.test.jsx.snap
  src/app/legacy/components/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/legacy/components/RadioSchedule/ProgramCard/__snapshots__/index.test.jsx.snap
  src/app/legacy/components/RadioSchedule/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/ArticleMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/Bulletin/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/EpisodeList/RecentVideoEpisodes/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/FrontPageStoryRows/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/RadioSchedule/Canonical/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/StoryPromo/IndexAlsos/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/StoryPromo/MediaIndicator/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/StoryPromo/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead/psammead-assets/src/__snapshots__/svgs.test.jsx.snap
  src/app/legacy/psammead/psammead-assets/src/svgs/mediaIcons.jsx
  src/app/legacy/psammead/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead/psammead-play-button/src/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead/psammead-story-promo/src/IndexAlsos/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  src/app/pages/IdxPage/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MostWatchedPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/TopicPage/Curation/CurationGrid/index.styles.jsx
  src/app/pages/TopicPage/HierarchicalGrid/index.styles.tsx
  src/integration/pages/articles/news/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/gahuza/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team

#10597 Update social media embed disclaimer text for BBC Brasil
  src/app/lib/config/services/portuguese.ts
Labels: cross-team

#10602 Update turkce nav bar to add link to Earthquake topic
  src/app/lib/config/services/turkce.ts
  src/integration/pages/articles/news/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/gahuza/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team

#10629 Kyrgyz and Swahili navigation bar updates
  src/app/lib/config/services/kyrgyz.ts
  src/app/lib/config/services/swahili.ts
  src/integration/pages/articles/news/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/gahuza.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/gahuza.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team
