Repository bbc/simorgh, pull requests merged in 2023-01, with the labels that each got.

#10485 ENH: reorder scripts and remove modulepreload
  src/server/Document/__snapshots__/component.test.jsx.snap
  src/server/Document/component.jsx
  src/server/Document/component.test.jsx
  src/server/utilities/attributeFunctions/index.js
  src/server/utilities/attributeFunctions/index.test.js
Labels: tests-passed-including-flaky-ones

#10481 ENH: reduce logging
  src/app/legacy/containers/Include/index.jsx
  src/app/legacy/containers/Include/index.test.jsx
  src/app/legacy/containers/SocialEmbed/Cps/index.jsx
  src/app/legacy/containers/SocialEmbed/Cps/index.test.jsx
  src/app/legacy/containers/SocialEmbed/index.jsx
  src/app/legacy/containers/SocialEmbed/index.test.jsx
  src/app/lib/logger.const.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/ampMetadataExtractor/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/ampMetadataExtractor/index.test.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/fetchMarkup/index.js
  src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/fetchMarkup/index.test.js
  src/app/routes/home/getInitialData/index.js
  src/app/routes/idx/getInitialData/index.js
  src/app/routes/liveRadio/getInitialData/index.js
  src/app/routes/onDemandAudio/getInitialData/index.js
  src/app/routes/utils/withRadioSchedule/index.js
Labels: tests-passed-including-flaky-ones

#10465 [WSTEAM1-188] Podcast Downloads Tracking
  src/app/legacy/containers/PodcastExternalLinks/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/PodcastExternalLinks/index.jsx
  src/app/legacy/containers/PodcastExternalLinks/index.stories.jsx
  src/app/legacy/containers/PodcastExternalLinks/index.test.jsx
Labels: tests-passed-including-flaky-ones

#10457 [WSTEAM1-188] Podcast Downloads Experiment
  data/burmese/podcasts/p02p9f6q.json
  data/burmese/podcasts/p02pc9lh.json
  src/app/legacy/containers/PodcastExternalLinks/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/PodcastExternalLinks/index.jsx
  src/app/legacy/containers/PodcastExternalLinks/index.stories.jsx
  src/app/legacy/containers/PodcastExternalLinks/index.test.jsx
  src/app/lib/config/services/burmese.ts
  src/app/models/types/translations.ts
  src/app/routes/onDemandAudio/getInitialData/index.js
  src/app/routes/onDemandAudio/getInitialData/index.test.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/arabic.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/burmese.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/gahuza.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/hausa.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/hindi.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/index.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/index.test.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/indonesia.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/kyrgyz.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/marathi.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/nepali.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/persian.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/portuguese.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/russian.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/ukrainian.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/urdu.js
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/zhongwen.js
Labels: tests-passed-including-flaky-ones

#10503 Gnadtech 3020 test ngas on live
  src/app/legacy/containers/Ad/Canonical/index.jsx
  src/app/legacy/containers/Ad/Canonical/index.test.jsx
Labels: cross-team

#10498 Update Mundo, Brasil Nepali nav to remove World Cup
  src/app/lib/config/services/mundo.ts
  src/app/lib/config/services/nepali.ts
  src/app/lib/config/services/portuguese.ts
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
Labels: cross-team

#10507 ENH: lazy load SMP where possible
  src/app/legacy/components/MediaPlayer/Canonical/__snapshots__/index.test.jsx.snap
  src/app/legacy/components/MediaPlayer/Canonical/index.jsx
  src/app/legacy/components/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/AVPlayer/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/CpsAssetMediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/legacy/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  src/app/legacy/psammead/psammead-media-player/src/Canonical/index.jsx
  src/app/legacy/psammead/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  src/app/pages/LiveRadioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandAudioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandTvPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
Labels: tests-passed-including-flaky-ones

#10483 ENH: add some JS to the sw.js
  public/sw.js
Labels: Do not merge, tests-passed-including-flaky-ones

#10486 ENH: removing deprecated fb meta tags
  src/app/legacy/containers/Metadata/index.jsx
  src/app/legacy/containers/Metadata/index.test.jsx
  src/integration/common/SEO.js
  src/integration/pages/articles/news/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/news/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/amp.test.js.snap
  src/integration/pages/articles/scotland/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/featureIdxPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/arabic/__snapshots__/canonical.test.js.snap
  src/integration/pages/frontPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/persian_afghanistan/__snapshots__/canonical.test.js.snap
  src/integration/pages/idxPage/ukraine_in_russian/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/gahuza/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/korean/__snapshots__/canonical.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/amp.test.js.snap
  src/integration/pages/liveRadio/sinhala/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/arabicTC2/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/persian/__snapshots__/canonical.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/amp.test.js.snap
  src/integration/pages/mediaAssetPage/pidgin/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/amp.test.js.snap
  src/integration/pages/mostReadPage/vietnamese/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/afrique/__snapshots__/canonical.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/amp.test.js.snap
  src/integration/pages/mostWatchedPage/urdu/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashtoBrand/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/__snapshots__/canonical.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/photoGalleryPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/kyrgyz/__snapshots__/canonical.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/amp.test.js.snap
  src/integration/pages/storyPage/mundo/__snapshots__/canonical.test.js.snap
  src/integration/utils/runTests/index.js
Labels: Do not merge, tests-passed-including-flaky-ones

#10488 Disable /ukchina/simp/52970385 in config
  cypress/support/config/settings.js
Labels: tests-passed-including-flaky-ones

#10473 Fix fontSize prop-type warning
  src/app/legacy/psammead/gel-foundations/src/prop-types/scripts/sizes.js
Labels: tests-passed-including-flaky-ones

#10530 Update Russian podcasts to remove Yandex links
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/russian.js
Labels: cross-team

#10414 updated tests to remove duplicate code
  cypress/integration/pages/articles/tests.js
  cypress/support/config/settings.js
Labels: cypress, cross-team

#10545 Update Simorgh Release Info to include topics for all services
  docs/Simorgh-Release-Info.md
Labels: cross-team

#10539 Second refactored social embeds end to end test
  cypress/integration/pages/articles/tests.js
  cypress/support/config/settings.js
Labels: cypress
