Repository bbc/simorgh, pull requests merged in 2024-08, with the labels that each got.

#11798 WSTEAMA 1276 - onDemand TV - Remove tests (Unit, integration and E2E) against AMP versions of these pages
  cypress/e2e/pages/onDemandTV/index.cy.js
  cypress/e2e/pages/onDemandTV/tests.js
  cypress/e2e/pages/onDemandTV/testsForCanonicalOnly.js
  src/app/pages/OnDemandTvPage/index.test.jsx
  src/integration/pages/onDemandTVPage/ampTests.js
  src/integration/pages/onDemandTVPage/canonicalTests.js
  src/integration/pages/onDemandTVPage/crossPlatformTests.js
  src/integration/pages/onDemandTVPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashto.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandTVPage/pashto.expired/amp.test.js
  src/integration/pages/onDemandTVPage/pashto.expired/canonical.test.js
  src/integration/pages/onDemandTVPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/pashtoBrand/amp.test.js
  src/integration/pages/onDemandTVPage/pashtoBrand/canonical.test.js
  src/integration/pages/onDemandTVPage/somali/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandTVPage/somali/amp.test.js
  src/integration/pages/onDemandTVPage/somali/canonical.test.js
Labels: Do not merge

#11814 Brasil podcast promo change
  src/app/lib/config/services/portuguese.ts
  src/app/routes/onDemandAudio/tempData/podcastExternalLinks/portuguese.js
Labels: cross-team

#11823 Change in brand descrition for BBC Brasil podcast promo
  src/app/lib/config/services/portuguese.ts
Labels: cross-team

#11799 [DNM] Ondemand audio (Radio and Podcasts) - Remove tests (Unit, integration and E2E) against AMP versions of these pages
  cypress/e2e/pages/onDemandAudio/index.cy.js
  cypress/e2e/pages/onDemandAudio/tests.js
  cypress/e2e/pages/onDemandAudio/testsForAMPOnly.js
  cypress/e2e/pages/onDemandAudio/testsForCanonicalOnly.js
  cypress/e2e/specialFeatures/cookieBanner/index.cy.js
  scripts/ampHtmlValidator/index.js
  src/app/pages/OnDemandAudioPage/OnDemandAudioPage.jsx
  src/app/pages/OnDemandAudioPage/__snapshots__/index.test.jsx.snap
  src/app/pages/OnDemandAudioPage/index.stories.jsx
  src/app/pages/OnDemandAudioPage/index.test.jsx
  src/app/routes/utils/regex/index.test.js
  src/app/routes/utils/regex/utils/__snapshots__/index.test.js.snap
  src/app/routes/utils/regex/utils/index.js
  src/integration/common/radioSchedule.js
  src/integration/pages/onDemandAudioPage/ampTests.js
  src/integration/pages/onDemandAudioPage/canonicalTests.js
  src/integration/pages/onDemandAudioPage/crossPlatformTests.js
  src/integration/pages/onDemandAudioPage/gahuza.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/gahuza.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/gahuza.expired/amp.test.js
  src/integration/pages/onDemandAudioPage/gahuza.expired/canonical.test.js
  src/integration/pages/onDemandAudioPage/indonesia.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia.expired/amp.test.js
  src/integration/pages/onDemandAudioPage/indonesia.expired/canonical.test.js
  src/integration/pages/onDemandAudioPage/indonesia/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/indonesia/amp.test.js
  src/integration/pages/onDemandAudioPage/indonesia/canonical.test.js
  src/integration/pages/onDemandAudioPage/pashto.expired/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto.expired/__snapshots__/canonical.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto.expired/amp.test.js
  src/integration/pages/onDemandAudioPage/pashto.expired/canonical.test.js
  src/integration/pages/onDemandAudioPage/pashto/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashto/amp.test.js
  src/integration/pages/onDemandAudioPage/pashto/canonical.test.js
  src/integration/pages/onDemandAudioPage/pashtoBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/onDemandAudioPage/pashtoBrand/amp.test.js
  src/integration/pages/onDemandAudioPage/pashtoBrand/canonical.test.js
  src/integration/pages/podcastPage/ampTests.js
  src/integration/pages/podcastPage/canonicalTests.js
  src/integration/pages/podcastPage/crossPlatformTests.js
  src/integration/pages/podcastPage/portugueseBrand/__snapshots__/amp.test.js.snap
  src/integration/pages/podcastPage/portugueseBrand/amp.test.js
  src/integration/pages/podcastPage/portugueseBrand/canonical.test.js
  src/integration/pages/podcastPage/portugueseEpisode/__snapshots__/amp.test.js.snap
  src/integration/pages/podcastPage/portugueseEpisode/amp.test.js
  src/integration/pages/podcastPage/portugueseEpisode/canonical.test.js
Labels: Do not merge

#11850 Replace fetch mock with jest fetch mock
  .yarn/cache/core-js-npm-3.36.1-ab30f10365-ce1e1bfc10.zip
  .yarn/cache/fetch-mock-npm-9.11.0-6ebe138f97-4bbd312eaf.zip
  .yarn/cache/is-subset-npm-0.1.1-15dc569569-cce9aeb579.zip
  .yarn/cache/lodash.isequal-npm-4.5.0-f8b0f64d63-82fc58a83a.zip
  .yarn/cache/lodash.sortby-npm-4.7.0-fda8ab950d-38df19ae28.zip
  .yarn/cache/path-to-regexp-npm-2.4.0-ce02fd84d9-0afcae75a2.zip
  .yarn/cache/querystring-npm-0.2.1-15cb60859d-5ae2eeb8c6.zip
  .yarn/cache/tr46-npm-1.0.1-9547f343a4-6e80d75480.zip
  .yarn/cache/webidl-conversions-npm-4.0.2-1d159e6409-594187c36f.zip
  .yarn/cache/whatwg-url-npm-6.5.0-07c2c28a54-fbe8e9d81f.zip
  package.json
  src/app/components/MostRead/Amp/index.test.tsx
  src/app/components/MostRead/Canonical/index.test.tsx
  src/app/legacy/containers/RadioSchedule/Canonical/index.test.jsx
  src/app/lib/utilities/getToggles/index.test.js
  src/app/lib/utilities/getToggles/withCache.test.js
  src/app/pages/FrontPage/index.test.jsx
  src/app/pages/MediaAssetPage/__snapshots__/index.test.jsx.snap
  src/app/pages/MediaAssetPage/index.test.jsx
  src/app/pages/StoryPage/__snapshots__/index.test.jsx.snap
  src/app/pages/StoryPage/index.test.jsx
  src/app/routes/frontPage/getInitialData/index.test.js
  src/app/routes/getInitialData.test.jsx
  src/app/routes/index.test.jsx
  src/app/routes/utils/withRadioSchedule/index.test.js
  src/testHelpers/setupTests.js
  yarn.lock
Labels: dependencies

#11857 Remove dependency on mocha package as it is unused
  .yarn/cache/ansi-colors-npm-4.1.1-97ad42f223-e862fddd0a.zip
  .yarn/cache/argparse-npm-2.0.1-faff7999e6-18640244e6.zip
  .yarn/cache/browser-stdout-npm-1.3.1-6b2376bf3f-ac70a84e34.zip
  .yarn/cache/chokidar-npm-3.5.3-c5f9b0a56a-863e3ff78e.zip
  .yarn/cache/decamelize-npm-4.0.0-12410e3409-b7d09b8265.zip
  .yarn/cache/diff-npm-5.0.0-ad6900db18-4a179a75b1.zip
  .yarn/cache/glob-npm-8.1.0-65f64af8b1-9aab1c75eb.zip
  .yarn/cache/is-plain-obj-npm-2.1.0-8dffd7ae9c-cec9100678.zip
  .yarn/cache/js-yaml-npm-4.1.0-3606f32312-c138a34a3f.zip
  .yarn/cache/minimatch-npm-5.0.1-612724f6f0-2656580f18.zip
  .yarn/cache/minimatch-npm-5.1.6-1e71429f4c-126b36485b.zip
  .yarn/cache/mocha-npm-10.4.0-9c45b5940e-0147b2a86c.zip
  .yarn/cache/serialize-javascript-npm-6.0.0-0bb8a3c88d-ed3dabfbb5.zip
  .yarn/cache/workerpool-npm-6.2.1-1486cb2056-3e637f7632.zip
  .yarn/cache/yargs-parser-npm-20.2.4-1de20916a6-db8f251ae4.zip
  .yarn/cache/yargs-unparser-npm-2.0.0-930f3ff3f6-68f9a542c6.zip
  package.json
  yarn.lock
Labels: dependencies
